### ISSUE TITLE
Config validator for appveyor.yml

### ISSUE THREAD

**Issue by codito** [appveyor/ci#1]
It would be nice to have a yml validator for appveyor; it requires trial and error to fix some of the parsing failures, for instance the `ps:` commands.

Example commits which required a fix to appveyor.yml syntax:
https://github.com/codito/pomito/commit/de34e64e722cc62d72f99d533663a1bf15fb472b
https://github.com/codito/pomito/commit/11f43caab54dbcf83f455f6d7d1eb64b08b0a746

**Comment by tooomm** [comment]
In case others keep on searching the net and just find this issue...
Yes, there is an official `appveyor.yml` validator! https://ci.appveyor.com/tools/validate-yaml
