### ISSUE TITLE
Repair CodeAnalysisClient and CodeSense

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1003]
More detais here: http://help.appveyor.com/discussions/problems/5210-referencing-dlls-in-visual-studio-install-directory

Directory to check: `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\CodeSense\Framework`

**Comment by FeodorFitsner** [comment]
CodeLens is part of Visual Studio Professional and above, but AppVeyor has VS Community installed on build workers. It's recommended to put those dependencies into source control or have a separate zip and download it during the build.

**Comment by georgeduckett** [comment]
I'm developing on Community edititon and have the references, so something must enable this. I believe installing SSTD does this. See http://stackoverflow.com/questions/33144785/missing-codelens-references-count-in-vs-2015-community-edition and https://msdn.microsoft.com/en-us/library/mt204009.aspx

Is installing this on the VM image a possibility?

**Comment by FeodorFitsner** [comment]
SSDT doesn't make it, but SSMS 2016 does.

**Comment by FeodorFitsner** [comment]
We can deploy SSMS 2016 to build workers, but there is no warranty that VS team won't "fix" that later and CodeLens disappear with some VS update, right?

**Comment by georgeduckett** [comment]
SSDT does add them. Currently in a build VM installing it (with all 4 options ticked) and it's added the DLLs.

Yes, there's no guarantee the VS team won't remove CodeLens from SSTD at some point in the future. It would be great if you could add it to the image though.

**Comment by FeodorFitsner** [comment]
do you install SSDT in unattended mode?

**Comment by FeodorFitsner** [comment]
ah, never mind, I see you are doing that while in RDP. Can you drop a download link for that SSDT installer?

**Comment by georgeduckett** [comment]
No, used this page: https://msdn.microsoft.com/en-US/mt186501 Under point 3, clicked the "English (United States)" link: https://go.microsoft.com/fwlink/?LinkID=824659&clcid=0x409 Then downloaded SSDTSetup.exe. I just ran that and made sure all options were ticked.

**Comment by FeodorFitsner** [comment]
Indeed, installing SSDT with all 4 options adds missing folders. We're used to install SSDT with just 1st option "SQL Server".

**Comment by georgeduckett** [comment]
Ahh, I see. Any chance of getting it added to the build VM images?

**Comment by FeodorFitsner** [comment]
Yep, let's give it a try (and see if it breaks anything else :smile:).

**Comment by FeodorFitsner** [comment]
Closed in favor of https://github.com/appveyor/ci/issues/1011
