### ISSUE TITLE
Artifact permalink by tag

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1007]
There is an [API method](https://github.com/appveyor/ci/issues/403#issuecomment-180026470) that allows referencing artifact from the last branch build.

There should be a possibility to refer artifact from the last tag build, so this URL is possible:

    https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip?tag=1.1.2

**Comment by equalsraf** [comment]
Awesome, thanks @FeodorFitsner.
