### ISSUE TITLE
Microsoft .NET Core 1.0.0 VS 2015 Tooling Preview 2 (14.1.20810.0)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1010]
Related discussion: http://help.appveyor.com/discussions/problems/5232-need-to-build-aspnet-core-project-using-devenvexe

**Comment by LeeChenelerJS** [comment]
This is occurring again :/

http://help.appveyor.com/discussions/problems/5232-need-to-build-aspnet-core-project-using-devenvexe

**Comment by FeodorFitsner** [comment]
It's not a regression. We found a breaking issue with the latest update and build worker images were rolled back to the previous Aug 9 state. We are working on a fix. Sorry for that.

**Comment by LeeChenelerJS** [comment]
Do you think this will hit the milestone date of 14th September?

**Comment by FeodorFitsner** [comment]
It's going to be the end of this week, sorry. There was [.NET Core 1.0.1](https://github.com/appveyor/ci/issues/1041) update released. We are going to deploy this and some other updates.

**Comment by LeeChenelerJS** [comment]
Thanks for the update :)
