### ISSUE TITLE
Some ANSI colour/formatting codes not working

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1012]
Discussion: http://help.appveyor.com/discussions/problems/5230-some-ansi-colourformatting-codes-not-working

**Comment by FeodorFitsner** [comment]
With the next update it's going to look like this:

![image](https://cloud.githubusercontent.com/assets/5041459/18222950/e3482b30-715b-11e6-8d7c-6e73dd6cbafc.png)

**Comment by FeodorFitsner** [comment]
It's been deployed.

**Comment by Daniel15** [comment]
Hey @FeodorFitsner  - This looks great for the example project I linked to earlier, but I still see some incorrect ANSI codes for this project: https://ci.appveyor.com/project/Daniel15/jest. I see a few `[1m` and `[22m` and `[39m` etc... Would you be able to take a look?

**Comment by FeodorFitsner** [comment]
Will take a look, sure.

**Comment by Daniel15** [comment]
Thanks! This is the repo being used for that project: https://github.com/facebook/jest

**Comment by FeodorFitsner** [comment]
Does it look better now?

**Comment by Daniel15** [comment]
Looks great now, thank you so much @FeodorFitsner :)

**Comment by RobertBColton** [comment]
Is it possible #798 can be looked into?
