### ISSUE TITLE
Why Firefox is documented as "FireFox"?

### ISSUE THREAD

**Issue by rakhimov** [appveyor/ci#1013]

**Comment by FeodorFitsner** [comment]
Can you drop a link to that page please?

**Comment by rakhimov** [comment]
My findings (there are maybe more that I didn't find, so maybe just grep your sources):
Selenium: https://www.appveyor.com/docs/installed-software/#selenium
All your Firefox issues: https://github.com/appveyor/ci/issues?utf8=%E2%9C%93&q=is%3Aissue%20firefox
