### ISSUE TITLE
Build doesn't start when pushing to github or when clicking New Build

### ISSUE THREAD

**Issue by AlonAm** [appveyor/ci#1015]
Since I've changed my user name in github I'm having issues with one of my builds
Build sometimes doesn't start when pushing to github or when clicking "New Build"
But when i'm committing changes from github website it does start

https://ci.appveyor.com/project/AlonAmsalem/anystatus

thanks

**Comment by IlyaFinkelshteyn** [comment]
Hi Alon,


1.       On GitHub, please open your project settings, go to Webhooks&services, open Appveyor webhook, go to Recent Deliveries and check records from time it did not start after a git push. If record exist, please send us details. It would be good if you have repro from today or later because we deployed updated internal webhooks tracing on Monday.



2.       What about builds which did not start on a New build command, please send us specific date and time in UTC when it happened.


Thank you,
Ilya.

**Comment by AlonAm** [comment]
**Recent Delivery Details**

**Headers**
Request URL: https://ci.appveyor.com/api/github/webhook?id=bqr0m4e08nfkb6g2
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/ebd57e0
X-GitHub-Delivery: 779e4d80-74d8-11e6-8b4a-bf7215b03adf
X-GitHub-Event: push

**Payload**
{
  "ref": "refs/heads/master",
  "before": "beb606d8efda31428ff3572b15315eae700d8669",
  "after": "c767b4addc19657cde8bcdfbefd5afdbaadc16c9",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/AlonAm/AnyStatus/compare/beb606d8efda...c767b4addc19",
  "commits": [
    {
      "id": "a14d7b65aa4db26b6e7b14e34e01e29be764723e",
      "tree_id": "bd01786ea057adf2a53839af0b625bf24c9046e2",
      "distinct": true,
      "message": "window background",
      "timestamp": "2016-09-07T11:52:13+03:00",
      "url": "https://github.com/AlonAm/AnyStatus/commit/a14d7b65aa4db26b6e7b14e34e01e29be764723e",
      "author": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "committer": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "src/AnyStatus/Features/Edit/EditWindow.xaml",
        "src/AnyStatus/Features/New/NewWindow.xaml"
      ]
    },
    {
      "id": "c767b4addc19657cde8bcdfbefd5afdbaadc16c9",
      "tree_id": "7492928aae974b5eda0987b25acb9ac32c597a54",
      "distinct": true,
      "message": "Merge branch 'master' of https://github.com/AlonAm/AnyStatus.git",
      "timestamp": "2016-09-07T11:52:51+03:00",
      "url": "https://github.com/AlonAm/AnyStatus/commit/c767b4addc19657cde8bcdfbefd5afdbaadc16c9",
      "author": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "committer": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "CHANGELOG.md"
      ]
    }
  ],
  "head_commit": {
    "id": "c767b4addc19657cde8bcdfbefd5afdbaadc16c9",
    "tree_id": "7492928aae974b5eda0987b25acb9ac32c597a54",
    "distinct": true,
    "message": "Merge branch 'master' of https://github.com/AlonAm/AnyStatus.git",
    "timestamp": "2016-09-07T11:52:51+03:00",
    "url": "https://github.com/AlonAm/AnyStatus/commit/c767b4addc19657cde8bcdfbefd5afdbaadc16c9",
    "author": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com",
      "username": "AlonAm"
    },
    "committer": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com",
      "username": "AlonAm"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "CHANGELOG.md"
    ]
  },
  "repository": {
    "id": 65724428,
    "name": "AnyStatus",
    "full_name": "AlonAm/AnyStatus",
    "owner": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com"
    },
    "private": false,
    "html_url": "https://github.com/AlonAm/AnyStatus",
    "description": "AnyStatus Visual Studio Extension",
    "fork": false,
    "url": "https://github.com/AlonAm/AnyStatus",
    "forks_url": "https://api.github.com/repos/AlonAm/AnyStatus/forks",
    "keys_url": "https://api.github.com/repos/AlonAm/AnyStatus/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/AlonAm/AnyStatus/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/AlonAm/AnyStatus/teams",
    "hooks_url": "https://api.github.com/repos/AlonAm/AnyStatus/hooks",
    "issue_events_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues/events{/number}",
    "events_url": "https://api.github.com/repos/AlonAm/AnyStatus/events",
    "assignees_url": "https://api.github.com/repos/AlonAm/AnyStatus/assignees{/user}",
    "branches_url": "https://api.github.com/repos/AlonAm/AnyStatus/branches{/branch}",
    "tags_url": "https://api.github.com/repos/AlonAm/AnyStatus/tags",
    "blobs_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/AlonAm/AnyStatus/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/AlonAm/AnyStatus/languages",
    "stargazers_url": "https://api.github.com/repos/AlonAm/AnyStatus/stargazers",
    "contributors_url": "https://api.github.com/repos/AlonAm/AnyStatus/contributors",
    "subscribers_url": "https://api.github.com/repos/AlonAm/AnyStatus/subscribers",
    "subscription_url": "https://api.github.com/repos/AlonAm/AnyStatus/subscription",
    "commits_url": "https://api.github.com/repos/AlonAm/AnyStatus/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/AlonAm/AnyStatus/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/AlonAm/AnyStatus/contents/{+path}",
    "compare_url": "https://api.github.com/repos/AlonAm/AnyStatus/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/AlonAm/AnyStatus/merges",
    "archive_url": "https://api.github.com/repos/AlonAm/AnyStatus/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/AlonAm/AnyStatus/downloads",
    "issues_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues{/number}",
    "pulls_url": "https://api.github.com/repos/AlonAm/AnyStatus/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/AlonAm/AnyStatus/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/AlonAm/AnyStatus/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/AlonAm/AnyStatus/labels{/name}",
    "releases_url": "https://api.github.com/repos/AlonAm/AnyStatus/releases{/id}",
    "deployments_url": "https://api.github.com/repos/AlonAm/AnyStatus/deployments",
    "created_at": 1471257041,
    "updated_at": "2016-08-21T16:57:51Z",
    "pushed_at": 1473238375,
    "git_url": "git://github.com/AlonAm/AnyStatus.git",
    "ssh_url": "git@github.com:AlonAm/AnyStatus.git",
    "clone_url": "https://github.com/AlonAm/AnyStatus.git",
    "svn_url": "https://github.com/AlonAm/AnyStatus",
    "homepage": "",
    "size": 510,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "C#",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 1,
    "forks": 0,
    "open_issues": 1,
    "watchers": 2,
    "default_branch": "master",
    "stargazers": 2,
    "master_branch": "master"
  },
  "pusher": {
    "name": "AlonAm",
    "email": "alon.amsalem@gmail.com"
  },
  "sender": {
    "login": "AlonAm",
    "id": 3127610,
    "avatar_url": "https://avatars.githubusercontent.com/u/3127610?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AlonAm",
    "html_url": "https://github.com/AlonAm",
    "followers_url": "https://api.github.com/users/AlonAm/followers",
    "following_url": "https://api.github.com/users/AlonAm/following{/other_user}",
    "gists_url": "https://api.github.com/users/AlonAm/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AlonAm/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AlonAm/subscriptions",
    "organizations_url": "https://api.github.com/users/AlonAm/orgs",
    "repos_url": "https://api.github.com/users/AlonAm/repos",
    "events_url": "https://api.github.com/users/AlonAm/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AlonAm/received_events",
    "type": "User",
    "site_admin": false
  }
}

**Comment by AlonAm** [comment]
Regarding 2,
I've tried to start a new build at 9:24 AM

You may start a new build at any time

Thank You

**Comment by IlyaFinkelshteyn** [comment]
Hi Alon,

This commit from webhook you sent (https://github.com/AlonAm/AnyStatus/commit/c767b4addc19657cde8bcdfbefd5afdbaadc16c9) matches `skip_commits` statement (https://github.com/AlonAm/AnyStatus/blob/master/appveyor.yml#L3-L6) in your YAML. Therefore it is expected that it does not run.

Please try to git push commit which does not match that files mask - I believe it will work. When this commit will last one, try start with UI too.

--ilya.

**Comment by AlonAm** [comment]
Thanks Ilya 
I'll send a webhook that doesn't match the skip_commit pattern

**Comment by AlonAm** [comment]
Here's another one
This one doesn't fall into the skip_commits pattern
thanks buddy

**Headers**
Request URL: https://ci.appveyor.com/api/github/webhook?id=bqr0m4e08nfkb6g2
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/ebd57e0
X-GitHub-Delivery: 5c494600-759d-11e6-8716-daea01a05173
X-GitHub-Event: push
**Payload**
{
  "ref": "refs/heads/master",
  "before": "65e1ae89dc02200296ee7a0392c8d8c30caa3e85",
  "after": "f2dfba6f51ea57830e31f9aceb48485283358658",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/AlonAm/AnyStatus/compare/65e1ae89dc02...f2dfba6f51ea",
  "commits": [
    {
      "id": "3ef12801fe9d7c292a3bb8f97ba12df37b243b7d",
      "tree_id": "42a8bf21d864c77ab80123be66bf3283168678f7",
      "distinct": true,
      "message": "",
      "timestamp": "2016-09-08T11:21:56+03:00",
      "url": "https://github.com/AlonAm/AnyStatus/commit/3ef12801fe9d7c292a3bb8f97ba12df37b243b7d",
      "author": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "committer": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "src/AnyStatus/Features/Edit/EditWindow.xaml",
        "src/AnyStatus/Features/HealthChecks/AppVeyorBuild.cs",
        "src/AnyStatus/Features/HealthChecks/Editors/PasswordEditor.cs",
        "src/AnyStatus/Features/HealthChecks/GitHubIssue.cs",
        "src/AnyStatus/Features/HealthChecks/HttpStatus.cs",
        "src/AnyStatus/Features/HealthChecks/Item.cs",
        "src/AnyStatus/Features/HealthChecks/JenkinsBuild.cs",
        "src/AnyStatus/Features/HealthChecks/Ping.cs",
        "src/AnyStatus/Features/HealthChecks/TCP.cs",
        "src/AnyStatus/Features/HealthChecks/TeamCityBuild.cs",
        "src/AnyStatus/Features/HealthChecks/TfsBuild.cs",
        "src/AnyStatus/Features/HealthChecks/WindowsService.cs",
        "src/AnyStatus/Features/New/NewWindow.xaml"
      ]
    },
    {
      "id": "f2dfba6f51ea57830e31f9aceb48485283358658",
      "tree_id": "cc0aa802f47f42e137ceb46b64fa464dc2441504",
      "distinct": true,
      "message": "Merge branch 'master' of https://github.com/AlonAm/AnyStatus.git",
      "timestamp": "2016-09-08T11:22:08+03:00",
      "url": "https://github.com/AlonAm/AnyStatus/commit/f2dfba6f51ea57830e31f9aceb48485283358658",
      "author": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "committer": {
        "name": "AlonAm",
        "email": "alon.amsalem@gmail.com",
        "username": "AlonAm"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "CHANGELOG.md"
      ]
    }
  ],
  "head_commit": {
    "id": "f2dfba6f51ea57830e31f9aceb48485283358658",
    "tree_id": "cc0aa802f47f42e137ceb46b64fa464dc2441504",
    "distinct": true,
    "message": "Merge branch 'master' of https://github.com/AlonAm/AnyStatus.git",
    "timestamp": "2016-09-08T11:22:08+03:00",
    "url": "https://github.com/AlonAm/AnyStatus/commit/f2dfba6f51ea57830e31f9aceb48485283358658",
    "author": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com",
      "username": "AlonAm"
    },
    "committer": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com",
      "username": "AlonAm"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "CHANGELOG.md"
    ]
  },
  "repository": {
    "id": 65724428,
    "name": "AnyStatus",
    "full_name": "AlonAm/AnyStatus",
    "owner": {
      "name": "AlonAm",
      "email": "alon.amsalem@gmail.com"
    },
    "private": false,
    "html_url": "https://github.com/AlonAm/AnyStatus",
    "description": "AnyStatus Visual Studio Extension",
    "fork": false,
    "url": "https://github.com/AlonAm/AnyStatus",
    "forks_url": "https://api.github.com/repos/AlonAm/AnyStatus/forks",
    "keys_url": "https://api.github.com/repos/AlonAm/AnyStatus/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/AlonAm/AnyStatus/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/AlonAm/AnyStatus/teams",
    "hooks_url": "https://api.github.com/repos/AlonAm/AnyStatus/hooks",
    "issue_events_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues/events{/number}",
    "events_url": "https://api.github.com/repos/AlonAm/AnyStatus/events",
    "assignees_url": "https://api.github.com/repos/AlonAm/AnyStatus/assignees{/user}",
    "branches_url": "https://api.github.com/repos/AlonAm/AnyStatus/branches{/branch}",
    "tags_url": "https://api.github.com/repos/AlonAm/AnyStatus/tags",
    "blobs_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/AlonAm/AnyStatus/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/AlonAm/AnyStatus/languages",
    "stargazers_url": "https://api.github.com/repos/AlonAm/AnyStatus/stargazers",
    "contributors_url": "https://api.github.com/repos/AlonAm/AnyStatus/contributors",
    "subscribers_url": "https://api.github.com/repos/AlonAm/AnyStatus/subscribers",
    "subscription_url": "https://api.github.com/repos/AlonAm/AnyStatus/subscription",
    "commits_url": "https://api.github.com/repos/AlonAm/AnyStatus/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/AlonAm/AnyStatus/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/AlonAm/AnyStatus/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/AlonAm/AnyStatus/contents/{+path}",
    "compare_url": "https://api.github.com/repos/AlonAm/AnyStatus/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/AlonAm/AnyStatus/merges",
    "archive_url": "https://api.github.com/repos/AlonAm/AnyStatus/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/AlonAm/AnyStatus/downloads",
    "issues_url": "https://api.github.com/repos/AlonAm/AnyStatus/issues{/number}",
    "pulls_url": "https://api.github.com/repos/AlonAm/AnyStatus/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/AlonAm/AnyStatus/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/AlonAm/AnyStatus/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/AlonAm/AnyStatus/labels{/name}",
    "releases_url": "https://api.github.com/repos/AlonAm/AnyStatus/releases{/id}",
    "deployments_url": "https://api.github.com/repos/AlonAm/AnyStatus/deployments",
    "created_at": 1471257041,
    "updated_at": "2016-08-21T16:57:51Z",
    "pushed_at": 1473322940,
    "git_url": "git://github.com/AlonAm/AnyStatus.git",
    "ssh_url": "git@github.com:AlonAm/AnyStatus.git",
    "clone_url": "https://github.com/AlonAm/AnyStatus.git",
    "svn_url": "https://github.com/AlonAm/AnyStatus",
    "homepage": "",
    "size": 523,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "C#",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 2,
    "default_branch": "master",
    "stargazers": 2,
    "master_branch": "master"
  },
  "pusher": {
    "name": "AlonAm",
    "email": "alon.amsalem@gmail.com"
  },
  "sender": {
    "login": "AlonAm",
    "id": 3127610,
    "avatar_url": "https://avatars.githubusercontent.com/u/3127610?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AlonAm",
    "html_url": "https://github.com/AlonAm",
    "followers_url": "https://api.github.com/users/AlonAm/followers",
    "following_url": "https://api.github.com/users/AlonAm/following{/other_user}",
    "gists_url": "https://api.github.com/users/AlonAm/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AlonAm/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AlonAm/subscriptions",
    "organizations_url": "https://api.github.com/users/AlonAm/orgs",
    "repos_url": "https://api.github.com/users/AlonAm/repos",
    "events_url": "https://api.github.com/users/AlonAm/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AlonAm/received_events",
    "type": "User",
    "site_admin": false
  }
}

**Comment by AlonAm** [comment]
here's the actual commit
https://github.com/AlonAm/AnyStatus/commit/3ef12801fe9d7c292a3bb8f97ba12df37b243b7d

**Comment by IlyaFinkelshteyn** [comment]
It still falla into skip_commits pattern ;) This is because we apply this pattern to head commit, and only to it. Therefore even if other commits do not match this pattern, if head commit match it – build skipped.

It was https://github.com/AlonAm/AnyStatus/commit/f2dfba6f51ea57830e31f9aceb48485283358658 in this case, which is change in CHANGELOG.md

--ilya.

**Comment by AlonAm** [comment]
Okay, thank you for your help.
