### ISSUE TITLE
Microsoft.DotNet.Common.Targets(262,5): error : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1016]
Solution: Open Visual Studio 2015, create new .NET Core web application project, build.

Related discussions:

- http://help.appveyor.com/discussions/problems/5232-need-to-build-aspnet-core-project-using-devenvexe

**Comment by LeeChenelerJS** [comment]
do we know when this milestone, or more specifically this fix, will get introduced to the builder worker?

**Comment by FeodorFitsner** [comment]
It will be available tomorrow, Friday. Sorry for the delay.

**Comment by LeeCheneler** [comment]
This issue seems to have come back :/

**Comment by olegburov** [comment]
I was experiencing the same issue with my **ASP.NET Core Web Application (.NET Framework)** solution. I was able to fix it after changing my `appveyor.yml` file like shown below:

**From:**
```
before_build:
  - nuget restore .\AnnetKatan.sln
```
**To:**

```
before_build:
  - dotnet restore
```
