### ISSUE TITLE
Build pages not loading, Timeout performing EXISTS job_message_counters_...

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#1018]
e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.6101

`Timeout performing EXISTS job_message_counters_2d7m7m0a4juhn7gr, inst: 8, mgr: ExecuteSelect, err: never, queue: 43939, qu: 0, qs: 43939, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=57,Free=32710,Min=2,Max=32767), clientName: RD000D3A331834`

**Comment by FeodorFitsner** [comment]
We are looking into that.

**Comment by FeodorFitsner** [comment]
Should be fine now. Let us know if you still see it.

**Comment by tkelman** [comment]
Yeah looks fixed, thanks!
