### ISSUE TITLE
clone_folder should support environment variable expansion

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#1022]
I'm using an `appveyor.yml` with

    environment:
      GOPATH: $(HOMEDRIVE)$(HOMEPATH)\go

    clone_folder: $(GOPATH)\src\site\org\project

and I get the error

    Build folder path must be absolute.

My guess is this happens because `clone_folder` does not support expanding the `GOPATH` environment variable, as otherwise the path *is* absolute.

**Comment by sschuberth** [comment]
Thanks for fixing. Any information on why the fix will be deployed?

**Comment by FeodorFitsner** [comment]
In a day or two.

-Feodor Fitsner, AppVeyor



On Sun, Sep 11, 2016 at 12:19 PM -0700, "Sebastian Schuberth" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for fixing. Any information on why the fix will be deployed?

-

**Comment by sschuberth** [comment]
Is it deployed yet? Because I'm getting the same error still, see https://ci.appveyor.com/project/sschuberth/git-lfs/build/1.0.49

**Comment by FeodorFitsner** [comment]
It's not yet deployed, sorry for the delay. There were some other (important) updates and we are going to push them with the next update later this week.

**Comment by sschuberth** [comment]
Ok, thanks for the update.

**Comment by sschuberth** [comment]
Still failing: https://ci.appveyor.com/project/sschuberth/git-lfs/build/1.0.51

**Comment by FeodorFitsner** [comment]
Should be fine now.
