### ISSUE TITLE
Bundler v1.13.3

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1028]
https://github.com/bundler/bundler/releases/tag/v1.13.2

**Comment by XhmikosR** [comment]
@FeodorFitsner: 1.13.2 is out.

**Comment by XhmikosR** [comment]
@FeodorFitsner: 1.13.3 is out. Do you want me to make a new issue?

**Comment by FeodorFitsner** [comment]
Will rename this one.
