### ISSUE TITLE
FFMpegPlugin does not allow original source files to be disk cached

### ISSUE THREAD

**Issue by nathanaeljones** [appveyor/ci#103]
While the extracted frames can be cached to disk or memory, FFMpegPlugin currently offers no command to enable [source caching of the videos themselves](https://github.com/imazen/resizer/blob/develop/Plugins/FFmpeg/FFmpegManager.cs#L234). 

This should be exposed by a new querystring command.

**Comment by FeodorFitsner** [comment]
How is it related to AppVeyor - could you please elaborate?

**Comment by nathanaeljones** [comment]
Man, I have to stop filing issues on the wrong repos. This is getting embarrassing.
