### ISSUE TITLE
Git 2.11

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1030]

**Comment by XhmikosR** [comment]
Git 2.10.1 is out.

**Comment by XhmikosR** [comment]
Git 1.10.2 is out.

**Comment by XhmikosR** [comment]
@FeodorFitsner: was this done?

**Comment by FeodorFitsner** [comment]
Yes

**Comment by XhmikosR** [comment]
Maybe add it to the updates post on the website then and close it.

**Comment by XhmikosR** [comment]
Allright, closing then.
