### ISSUE TITLE
Error uploading artifact to Azure Blob storage: Remote server returned 404

### ISSUE THREAD

**Issue by pavelhritonenko** [appveyor/ci#1034]
I have this error on every build if there are artifacts to publish (zipped .exe in my case):

    Collecting artifacts...
    Found artifact 'MyProject.zip' matching 'MyProject.zip' path
    Uploading artifacts...
    [1/1] MyProject.zip (89,758 bytes)...100%
    Error uploading artifact to Azure Blob storage: Remote server returned 404: The specified container does not exist.

**Comment by zh99998** [comment]
I meet same problem

**Comment by pavelhritonenko** [comment]
Seems like fixed at the moment

**Comment by kveretennicov** [comment]
Also saw this yesterday, but seems to work at the moment.
