### ISSUE TITLE
Maven no longer on path? `mvn` fails

### ISSUE THREAD

**Issue by mprins** [appveyor/ci#1038]
Maven was added in #998 and worked (eg. https://ci.appveyor.com/project/mprins/maven-compass-example/build/79%20(master)/job/3h9crvosgvqk50rw#L15 ) but this morning after tweaking my build it seems that Maven was removed from the path (https://ci.appveyor.com/project/mprins/maven-compass-example/build/88%20(build-enhancements)#L12 ) and can no longer be started using `mvn`

**Comment by IlyaFinkelshteyn** [comment]
Yes, sorry. This is because we found a breaking issue with this update and build worker images were rolled back to the previous Aug 9 state.

Please watch https://www.appveyor.com/updates/. Sorry for inconvenience.

--ilya.

**Comment by mprins** [comment]
OK, thanks for the update

**Comment by mprins** [comment]
This was fixed ( in Sept 26 update I think)
