### ISSUE TITLE
Use ".appveyor.yml" if "appveyor.yml" isn't found

### ISSUE THREAD

**Issue by darconeous** [appveyor/ci#1040]
On Unixy platforms (Linux, BSD, etc), filenames prefixed with a dot (`.`) are hidden from normal view. By allowing `.appveyor.yml` to work, you give project maintainers the ability to hide clutter in their project's root directory.

**Comment by IlyaFinkelshteyn** [comment]
Hi Robert,

We just recently added support for .appveyor.yml with “.” Please give it a try. Note that appveyor.yml without “.” Is still a first choice.

--ilya.

**Comment by darconeous** [comment]
That sounds fantastic. Thanks!
