### ISSUE TITLE
.NET Core 1.0.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1041]
Official announcement: https://blogs.msdn.microsoft.com/dotnet/2016/09/13/announcing-september-2016-updates-for-net-core-1-0/

Download page: https://www.microsoft.com/net/core#windows

Discussion: http://help.appveyor.com/discussions/kb/44-net-core-rtm-support

1.0.1 `dotnet --version` returns `1.0.0-preview2-003131`

1.0.0 `dotnet --version` returns `1.0.0-preview2-003121`

**Comment by nulltoken** [comment]
@FeodorFitsner Hmmm..  I'm still seeing this. I that expected?

![image](https://cloud.githubusercontent.com/assets/92363/18648477/1eab4dee-7ebb-11e6-9a18-564f9d78c7e9.png)

Below the applied patch

```diff
diff --git a/global.json b/global.json
index e793049..9d09ab5 100644
--- a/global.json
+++ b/global.json
@@ -1,6 +1,6 @@
 ﻿{
   "projects": [ "src", "test" ],
   "sdk": {
-    "version": "1.0.0-preview2-003121"
+    "version": "1.0.0-preview2-003131"
   }
 }
diff --git a/src/xx.Web/project.json b/src/xx.Web/project.json
index a1004a6..999f37c 100644
--- a/src/xx.Web/project.json
+++ b/src/xx.Web/project.json
@@ -2,7 +2,7 @@
   "version": "1.0.0",
   "dependencies": {
     "Microsoft.NETCore.App": {
-      "version": "1.0.0",
+      "version": "1.0.1",
       "type": "platform"
     },
     "Dapper": "1.50.2",
diff --git a/test/xx.Tests/project.json b/test/xx.Tests/project.json
index 82e690a..d9bc55f 100644
--- a/test/xx.Tests/project.json
+++ b/test/`xx.Tests/project.json
@@ -31,7 +31,7 @@
       "dependencies": {
         "Microsoft.NETCore.App": {
           "type": "platform",
-          "version": "1.0.0"
+          "version": "1.0.1"
         }
       },
       "imports": [
``

**Comment by FeodorFitsner** [comment]
The image has been rolled back as we found a critical issue. Will bring it back later today. Sorry.

**Comment by stuartleeks** [comment]
Was .NET Core 1.0.1 re-added?

Thanks!

**Comment by FeodorFitsner** [comment]
Yep, it's been re-added.

**Comment by nulltoken** [comment]
Works now for me. Thanks and ❤️
