### ISSUE TITLE
problem with deleted projects

### ISSUE THREAD

**Issue by zh99998** [appveyor/ci#1054]
today I pushed 3 times to my `mycard/ygopro-images-generator` project, and then I deleted it from Appveyor.

then all my projects build is queued **MORE THAN 3 HOURS**, and my github commits shows last 2 build is still not finished.

my appveyor account is zh99998, and deleted project is zh99998/ygopro-images-generator  which github repo is
https://github.com/mycard/ygopro-images-generator/commits/master

**Comment by FeodorFitsner** [comment]
What's URL of corresponding AppVeyor project?

**Comment by zh99998** [comment]
@FeodorFitsner 
originally it is https://ci.appveyor.com/project/zh99998/ygopro-images-generator but it is deleted so i can only get a `Project not found or access denied.` now

**Comment by FeodorFitsner** [comment]
Can you try cancelling both builds and start a new one:
https://ci.appveyor.com/project/zh99998/ygopro-images
https://ci.appveyor.com/project/zh99998/ygopro/build/91

**Comment by zh99998** [comment]
@FeodorFitsner it works. thanks
