### ISSUE TITLE
Javascript endless loop on messages tab

### ISSUE THREAD

**Issue by peppy** [appveyor/ci#1057]
When entering the messages tab, browser will freeze forever. Tested on Firefox and Chrome.

https://ci.appveyor.com/project/peppy/osu-framework
https://ci.appveyor.com/project/peppy/osu-framework/build/messages

**Comment by FeodorFitsner** [comment]
Will take a look, thanks for reporting that!

**Comment by peppy** [comment]
Thanks a lot for the quick fix!
