### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by atian25** [appveyor/ci#1058]
https://ci.appveyor.com/project/eggjs/egg/build/1.0.98/job/23dpw1hvnqnxo2qc

https://github.com/eggjs/egg/blob/master/appveyor.yml

```
test/lib/agent.test.js
    agent.dumpConfig()
      √ should dump config and plugins
2016-09-20 02:38:39,197 ERROR 1160 [chair-logger:buffer_write_stream] Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\common-error.log'
Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\common-error.log'
    at Error (native)
2016-09-20 02:38:39,197 ERROR 1160 [chair-logger:buffer_write_stream] Error: EPERM: operation not permitted, open 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\egg-agent.log'
```

```
 8) test/app/extend/context.test.js ctx.logger "before each" hook for "env=local: level => debug":
     Error: EPERM: operation not permitted, lstat 'C:\projects\egg\test\fixtures\apps\demo\logs\demo\common-error.log'
      at Error (native)
      at Object.fs.lstatSync (fs.js:839:18)
      at rimrafSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:290:24)
      at C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:340:5
```

```
  10) test/app/extend/context.test.js ctx.instrument(event, action), app.instrument(event, action) "before all" hook:
     Error: ENOTEMPTY: directory not empty, rmdir 'C:\projects\egg\test\fixtures\apps\context-config-app\logs\context-config-app'
      at Error (native)
      at Object.fs.rmdirSync (fs.js:758:18)
      at rmkidsSync (C:\projects\egg\node_modules\.2.5.4@rimraf\rimraf.js:342:11
```

**Comment by FeodorFitsner** [comment]
When was the last successful build?

**Comment by atian25** [comment]
@FeodorFitsner thanks for reply.

never success...  but works at travis, https://travis-ci.org/eggjs/egg/builds/161216555

**Comment by hovancik** [comment]
Any update? I have same issue: `Uncaught Error: EPERM: operation not permitted` when I try to `open` or `unlink` file in my test: 

```
...
fs.createWriteStream(testFile)
...
fs.unlink(testFile)
```

**Comment by IlyaFinkelshteyn** [comment]
Hi Jan,

It seems this this error happens due to some race condition in node on Windows we cannot control. However [in a slightly different case](http://help.appveyor.com/discussions/problems/3147-error-eperm-operation-not-permitted-rename-on-npm-install) retry helped. Can you try to implement retry (with some wait between attempts) in your tests and see if it helps?

--ilya.

**Comment by atian25** [comment]
@popomore had solve this.

**Comment by hovancik** [comment]
retry didn't help. I will find another way to make my test.

**Comment by ert78gb** [comment]
I have a same problem https://ci.appveyor.com/project/mondalaci/agent/build/1.0.352

Any new about the problem?

**Comment by IlyaFinkelshteyn** [comment]
@ert78gb given the fact that your subsequent builds worked OK, and changes were seemingly not related, `appveyor-retry npm install` should help in your case.

**Comment by ert78gb** [comment]
@IlyaFinkelshteyn thx the fast response. I will add `appveyor-retry` to my build script.
My problem is sometimes building sometimes got an error :) but I will test your suggestion.

**Comment by vanduynslagerp** [comment]
I have the same problem on 3 different repo. All failure happened on Node 4 on each. Node 6 and 8 worked each time and 4, 6 and 8 worked on Travis each time.
https://ci.appveyor.com/project/vanduynslagerp/karma-rollup-preprocessor/build/138
https://ci.appveyor.com/project/vanduynslagerp/karma-jasmine-jquery/build/87
https://ci.appveyor.com/project/vanduynslagerp/karma-postcss-preprocessor/build/40

**Comment by vanduynslagerp** [comment]
After a bit more investigation it seems that in my case the problem happen only with NPM 5.4.0 on Node 4. Installing NPM 5.3.x instead of 5.4.0 seems to be a good workaround for now.
https://ci.appveyor.com/project/vanduynslagerp/karma-rollup-preprocessor/build/148

**Comment by IlyaFinkelshteyn** [comment]
@vanduynslagerp thanks a lot, it helps to unblock number of customers!

**Comment by jdalton** [comment]
I'm seeing this with npm 5.4.1 too \cc @zkat

**Comment by iarna** [comment]
Yeah, it's on our radar, time to spend some desktop time in Windows…

**Comment by atian25** [comment]
in my case, it's not npm version problem, see https://ci.appveyor.com/project/eggjs/egg-mock/builds/24323497/job/l45ws0pl8x8y1gjv is a node 10.x test.

it had 3 years, sorry, I give up, travis had provided win env.
