### ISSUE TITLE
Error: M2_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by damianszczepanik** [appveyor/ci#1060]
Looks like some regression in configuration:

```
Error: M2_HOME is set to an invalid directory. 
M2_HOME = "C:\Program Files (x86)\Apache\Maven" 
Please set the M2_HOME variable in your environment to match the 
location of the Maven installation 
Command exited with code 1
```

https://ci.appveyor.com/project/damianszczepanik/cucumber-reporting/build/516

**Comment by FeodorFitsner** [comment]
Maven is now part of build worker image and installed in `C:\Program Files (x86)\Apache\Maven` directory. `mvn` is added into `PATH`.

You can either reset or override `M2_HOME` variable in your build script if you are downloading Maven yourself.

**Comment by damianszczepanik** [comment]
Removed custom Maven and used built-int
https://github.com/damianszczepanik/cucumber-reporting/commit/ebb97ee335ac1fae273888f0a5cee16f542bf090

Thanks for help
