### ISSUE TITLE
"Global" YAML

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1068]
There is an idea to have a set of "global" environment variables defined on account level and applied to all projects.

Discussion: http://help.appveyor.com/discussions/suggestions/1105-suggestion-for-managing-environment-variables

Use cases:

* Environment variables for all projects
* `init` section for all projects configuring common environment, such as a key for Kiln HG repo.
* RDP/SSH in all projects on failure
* Common notification for all projects
* etc.

**Comment by devlead** [comment]
@FeodorFitsner that's an excellent idea 👍 
Would be nice with global notifications/web hooks too, now you need to configure each projects slack hook i.e.

**Comment by FeodorFitsner** [comment]
Well, that makes sense!

**Comment by ryanpolasek** [comment]
Hi, is this feature happening?  I could really use it for managing package management server credentials and settings without having to update variables in dozens of projects every time I regenerate access tokens for my servers.

**Comment by devlead** [comment]
@ryanpolasek indeed global settings makes so much sense, I've solved the acute issue of dozens of projects scenario by automation, you can find some examples of that in a blog post I wrote [here](https://medium.com/@devlead/reduce-the-pain-of-expiring-nuget-keys-794acd97127a)

**Comment by msevestre** [comment]
This would be a great addition indeed.

**Comment by mynkow** [comment]
Bump

**Comment by 3F** [comment]
+1, @FeodorFitsner, this is an excellent way to prepare any common template between my projects along with your [predefined variables](https://www.appveyor.com/docs/environment-variables/) for anything!

**Comment by IlyaFinkelshteyn** [comment]
Renaming this to the `"Global" YAML`. Settings from this YAML will be merged to specific projects and/or matrix jobs settings.

Specific projects and/or matrix jobs settings will take precedence.

**Comment by IlyaFinkelshteyn** [comment]
We have everything under the hood to deliver it quickly. Need to clarify a few things:

- is it OK if this Global YAML should be fetched over http(s) like [this](https://www.appveyor.com/docs/build-configuration/#alternative-yaml-file-location) at least for the beginning? Or UI where you can paste/edit/validate it is required?

- is it OK if settings described [here](https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration) under **Settings to be ignored** will also be ignored when merging Global YAML with project-level one?

- the same setting from project-level YAML will override Global YAML setting, correct?

**Comment by solutionsx** [comment]
Thank you for the quick response. Here are my answers to your questions.

1. Retrieving the global YAML over http would great for us for the initial version. UI would be a nice to have but not absolutely necessary.
2. I believe settings to be ignored would be fine in this situation as well.
3. Yes, but more specifically it would be ideal if project level settings overrides global and environment variables setup on the UI would still override the variable on the project YAML. So in the case of environment variables the inheritance chain would be Global YAML - Project YAML - Project UI.

On Nov 1, 2018, at 6:50 PM, Ilya Finkelshteyn <notifications@github.com<mailto:notifications@github.com>> wrote:


We have everything under the hood to deliver it quickly. Need to clarify a few things:

  *   is it OK if this Global YAML should be fetched over http(s) like this<https://www.appveyor.com/docs/build-configuration/#alternative-yaml-file-location> at least for the beginning? Or UI where you can paste/edit/validate it is required?

  *   is it OK if settings described here<https://www.appveyor.com/docs/build-configuration/#specializing-matrix-job-configuration> under Settings to be ignored will also be ignored when merging Global YAML with project-level one?

  *   the same setting from project-level YAML will override Global YAML setting, correct?

**Comment by mynkow** [comment]
For me the UI is a MUST

I think that project level variable must override the globals because you are entering in a more specific context. I am OK if the override is not included in the initial release.

**Comment by devlead** [comment]
> 1. Retrieving the global YAML over http would great for us for the initial version. UI would be a nice to have but not absolutely necessary.
> 2. I believe settings to be ignored would be fine in this situation as well.
> 3. Yes, but more specifically it would be ideal if project level settings overrides global and environment variables setup on the UI would still override the variable on the project YAML. 

+1 on this 👍

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for the quick feedback. Sorry it takes too long, will do it this year.

**Comment by PureKrome** [comment]
Just touching base with this issue @IlyaFinkelshteyn - status update?

Here's a great example of why this is important now: NuGet.org now have YEARLY expires on their API KEY's. So right now, I'll need to update _heaps_ of `.yml` files with the new secure nuget.org api key. Then in 1 year's time, i'll have to do this all over again.

Having this a global variable that is accessible to _all_ my projects (in our paid account) means I just need to change this in one spot. not dozens and dozens of files --- every year.

**Comment by IlyaFinkelshteyn** [comment]
Last few months we concentrating on major infrastructure changes and core code refactoring. We need that to reach new level of performance, scale and provide new cross-platform and hybrid scenarios.  Because of that we put many shiny but not absolutely necessary features on freeze. We plan to start delivering new features in usual pace this summer and this will be one of the first to implement.

**Comment by jiteshsojitra** [comment]
Any solution for this 3 year old issue?

**Comment by mynkow** [comment]
@IlyaFinkelshteyn could you please update us what is the status a year later?

**Comment by FeodorFitsner** [comment]
The feature is being implemented and we are going to release update in a few days.

**Comment by gep13** [comment]
@FeodorFitsner this is really exciting!  Thanks for getting this done.  Are there any docs for this, or will this come with the release?

**Comment by FeodorFitsner** [comment]
The feature has been deployed, thanks for your patience!

Global configuration can be set on **Account &rarr; Global YAML** page.

Documentation is here: https://www.appveyor.com/docs/global-yml/

Let us know how that worked for you or if you have any questions.

**Comment by mynkow** [comment]
Is it just me? The global envvar are not working using the following yaml:

```
environment:
  nuget_key: 123
  ghtoken: 123
```
![image](https://user-images.githubusercontent.com/183151/83335393-29114780-a2b5-11ea-9599-8daf9c48a80b.png)

**Comment by FeodorFitsner** [comment]
Just checked with your yaml on my personal account and it worked: https://ci.appveyor.com/project/FeodorFitsner/simple-console/builds/33216387#L75

**Comment by mynkow** [comment]
I am using the envvar in my script like [this](https://github.com/Elders/Cronus/blob/master/appveyor.yml#L17). I have removed the variables from the project and I have added the globals. May be I am missing something...

**Comment by FeodorFitsner** [comment]
Could you drop me a link to a build please?

**Comment by mynkow** [comment]
Sure => https://ci.appveyor.com/project/Elders-OSS/cronus-domainmodeling/builds/33216378

**Comment by FeodorFitsner** [comment]
Both env vars exist in that build config in "secure" form. Make sure their values were encrypted under `Elders-OSS` account as encryption key is unique per account.
