### ISSUE TITLE
PS: Encoding issue

### ISSUE THREAD

**Issue by am11** [appveyor/ci#107]
When using mocha with node.js, if we shell out the test command (mocha test) to `ps`, it encodes the Unicode character (checkmark) incorrectly: `√` as `ΓêÜ `.

Here is the example test ran with ps: https://ci.appveyor.com/project/sass/node-sass/build/153/job/iv8vm8yh7wx405qv.

Here is the same suite ran without PS (default, CMD): https://ci.appveyor.com/project/sass/node-sass/build/250/job/0r75512tu1rbb9hf.

Related https://github.com/mochajs/mocha/issues/1416.

(It seems like it requires setting `-Encoding UTF8` in PS, when piping to [other stream](http://stackoverflow.com/a/76734))

**Comment by FeodorFitsner** [comment]
This is PS issue: http://help.appveyor.com/discussions/problems/1105-utf-8-characters-in-powershell-log

There is no easy way to fix that as there is no piping occurs. AppVeyor uses custom PowerShell Host.

**Comment by am11** [comment]
@FeodorFitsner, from the links you posted in discussion thread, apparently @PaulStovell has updated his question with the solution http://stackoverflow.com/q/22349139/. If that is applicable here, perhaps that is worth a try. :)

Also over SO, it was suggested that it is a dotnet issue. If you can provide reproduction steps (part of your custom PS host), then perhaps this issue can be reported to https://github.com/dotnet/corefx/issues/, since `System.Console` and `System.Text.Encoding` are also open-sourced.

**Comment by FeodorFitsner** [comment]
Yeah, I've seen that solution - thanks for sharing a link though. However, I'm not sure that it could be applied to our case as AppVeyor doesn't do output redirection with PowerShell case. It's just implementing [PSHostUserInterface](http://msdn.microsoft.com/en-us/library/system.management.automation.host.pshostuserinterface_methods(v=vs.85).aspx) interface. Whatever is sent to `Write*` method just goes to AppVeyor real-time log endpoint.

I don't exclude it might be getting "corrupted" somewhere on its way - will play with it more.

**Comment by guw** [comment]
Is there any other workaround available to fix the issue than going via cmd? We do call node/npm from within PowerShell as we do need to apply some pre/post processing.
