### ISSUE TITLE
GitHub commit status link navigates to 404 if build version was changed

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1074]
When changing build version with `Update-AppveyorBuild` cmdlet a link to this build on GitHub commit status is unchanged which gives 404 if follow it.

It could be either a permalink or that API call should update commit status too.

Permalink can be based on unique build ID (not version).

**Comment by IlyaFinkelshteyn** [comment]
Workaround: https://gist.github.com/IlyaFinkelshteyn/def2394231afb7f06dcaeaceda1fb1ae

**Comment by jeffkl** [comment]
Is there any way for this to be fixed by an outside contributor?

**Comment by IlyaFinkelshteyn** [comment]
@jeffkl sorry, this part is closed source, so this would be complicated. We understand this is annoying, will fix (introduce permalink independent of build version) in next couple of months.

**Comment by jeffkl** [comment]
@IlyaFinkelshteyn okay thanks for the update, we look forward to having this fixed.  More and more people are using versioning outside of their environment so I see this becoming a growing problem.

**Comment by FeodorFitsner** [comment]
Finally! An annoying issue with changing build URL has been fixed by replacing version-based URLs with build permalinks!
