### ISSUE TITLE
vcpkg (Microsoft VC++ Packaging Tool)

### ISSUE THREAD

**Issue by ebraminio** [appveyor/ci#1076]
[`vcpkg`](https://github.com/Microsoft/vcpkg) is a lightweight brand new C libraries installer that makes build of software with dependencies much easier. Even the fact its installation is easy as I am downloading and using it currently for [this software](https://github.com/behdad/glyphy/pull/19), having that as a preinstalled tool just like chocolaty would be nice I think.

**Comment by FeodorFitsner** [comment]
Can you drop a link to download page of that vcpkg library?

**Comment by ebraminio** [comment]
vcpkg it self is more of tiny tool than library but it fetches libraries for VC. It seems currently its binary has to be built, as this [post](https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/) mentiones,

```
# first choose a stable path you like to put vcpkg files there
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
powershell -exec bypass scripts\bootstrap.ps1
vcpkg integrate install
# now you have vcpkg.exe compiled
# put this folder on PATH so the tool can be used by users
```

**Comment by FeodorFitsner** [comment]
OK, thanks. Will take a look.

**Comment by adam4813** [comment]
This would be a great addition as we could cache our libraries without having to rebuild them each time which takes quite awhile actually.

**Comment by adam4813** [comment]
@FeodorFitsner since this has matured a good deal and provides more broad build styles any chance that this can be directly integrated?

Being able to cache my vcpkg/installed directory to allow quick CI iteration would be 100x quicker.

**Comment by claudiofantacci** [comment]
I'm also interested in vcpkg integration.
I'm looking forward to it!

**Comment by debrouxl** [comment]
Like the other commenters, I'm interested in vcpkg integration. I know of several projects depending on a number of libraries already packaged in e.g. vcpkg's ports, which are either already using AppVeyor and could use vcpkg integration to ease their work, or could seriously consider using AppVeyor once it has vcpkg integration :)

**Comment by mloskot** [comment]
Any updates on this request?

**Comment by FeodorFitsner** [comment]
Haven't looked into this yet, sorry.

Could you guys please provide complete installation instruction that we can use (and you'll be OK with) to deploy VSPKG to build workers.

**Comment by mloskot** [comment]
I'm `vcpkg` newbie myself, but general installation is straight forward:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
powershell -exec bypass scripts\bootstrap.ps1
.\vcpkg integrate install # requires admin on first use
```

For AppVeyor use case, I guess, there are issues to be solved:
* Prerequisities: VS2015 Update 3 or VS2017 and CMake 3.8.0 or higher
* Working copy would have to be offloaded somewhere and scheduled updated configured, that is to pull updates of ports, new packages.
* `vcpkg` would have to be put in `PATH` or known location to make it callable from `appveyor.yml` 
* ...

**Comment by stekyne** [comment]
Any update on this request? Running into build time issues with a project. It takes over an hour to download, patch and install the VCPKG libraries before it even builds the project. I don't fancy waiting 4 hours every build also :) Main offenders are boost and GTK. 

My guess is you'd have to install vcpkg as described on each VM. You can specify the library locations via the --vcpkg-root command line switch.  As per the FAQ...
"Will Vcpkg support downloading compiled binaries from a public or private server?

We do plan to eventually support downloading precompiled binaries, similar to other system package managers.

In a corporate scenario, we currently recommend building the libraries once and distributing the entire vcpkg root directory to everyone else on the project through some raw file transport such as a network share or HTTP host."

You can keep them updated by running "git pull && vcpkg remove --outdated --recurse && vcpkg update" over the repo. 

I'm guessing you'll have to download every package x every triplet for completeness. Not sure how to automate that however.

**Comment by szellmann** [comment]
+1 from my side, vcpkg support would be nice!

Prerequisites should already be met by appveyor-ci: CMake 3.8.0, Visual Studio 2015 or Visual Studio 2017, and git.exe in the path.

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
REM do the following for user-wide integration
.\vcpkg integrate install
```

(cf. https://github.com/Microsoft/vcpkg/blob/master/README.md)

One of the devs mentioned that their versioning policy is basically that every commit on github master denotes a new version: https://github.com/Microsoft/vcpkg/issues/1036

**Comment by lgritz** [comment]
Any progress on this? It would really be a boon to users (not to mention drastically reduce the compute time we use building dependencies) if we knew that every Appveyor run had all of the vcpkg packages pre-installed.

**Comment by stekyne** [comment]
It is the recommended package manager for Windows now also. Would be really nice to have!

**Comment by bagong** [comment]
+1

**Comment by mloskot** [comment]
@bagong Please, stop the legacy +1'ing and use [Reactions](https://developer.github.com/v3/reactions/), then those who observe an issue won't get spammed...

**Comment by FeodorFitsner** [comment]
Final script that will be used for installing `vcpkg`:

```
git clone --depth=1 https://github.com/Microsoft/vcpkg C:\Tools\vcpkg
cd C:\Tools\vcpkg
.\vcpkg integrate install
Add-Path 'C:\Tools\vcpkg'
```

**Comment by willyd** [comment]
@FeodorFitsner Aren't you missing a call to `bootstrap.bat`? Like:

```
git clone --depth=1 https://github.com/Microsoft/vcpkg C:\Tools\vcpkg
cd C:\Tools\vcpkg
.\bootstrap.bat
.\vcpkg integrate install
Add-Path 'C:\Tools\vcpkg'
```

**Comment by FeodorFitsner** [comment]
@willyd Absolutely, thanks for the catch!

**Comment by traversaro** [comment]
The bootstrap file seems to be called `bootstrap-vcpkg.bat` in the master branch of vcpkg: https://github.com/Microsoft/vcpkg/blob/master/bootstrap-vcpkg.bat .

**Comment by stekyne** [comment]
Great news. So is it in the latest images yet?

**Comment by IlyaFinkelshteyn** [comment]
@stekyne Not yet, but should be soon. We will close this issue as new image with vcpkg deployed.

**Comment by MikeGitb** [comment]
Great! Thank you very much

**Comment by janisozaur** [comment]
vcpkg seems to be missing from current (15.5P4) VS 2017 image

**Comment by IlyaFinkelshteyn** [comment]
@janisozaur it is in `C:\Tools\vcpkg` and added to the `path` path environment variable. And I even see that [it is being used in your build](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.2.11768/job/ju1q8ybejkdk506c#L101) which uses latest `Visual Studio 2017` image...

**Comment by janisozaur** [comment]
@IlyaFinkelshteyn the link you posted is using `Visual Studio 2017` image. I mentioned the vcpkg is missing from `Visual Studio 2017 Preview` image, see https://ci.appveyor.com/project/janisozaur/vcpkg/build/1.0.12

**Comment by IlyaFinkelshteyn** [comment]
Sorry I have to read initial question better. Filed https://github.com/appveyor/ci/issues/1964.

**Comment by ebraminio** [comment]
As a conclusion, the result and the documentation https://www.appveyor.com/docs/lang/cpp/#vc-packaging-tool specially the caching part, are just fantastic, thanks for the excellent work.

**Comment by IlyaFinkelshteyn** [comment]
The whole doc is a [contribution from the community](https://github.com/appveyor/website/blame/master/src/docs/lang/cpp.md) by the way :)
