### ISSUE TITLE
Make IIS apppool  managedRuntimeVersion configurable in agent deployment

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1077]
We need to provide this out-of-the box this as ASP.NET core becomes more popular. 

http://help.appveyor.com/discussions/questions/2655-app-pool-clr-versoin-no-managed-code

**Comment by LeeCheneler** [comment]
:D

**Comment by LeeCheneler** [comment]
So the current solution is to set it in the deploy.ps1

```
Import-Module WebAdministration 
Set-ItemProperty IIS:\AppPools\$env:<app pool> managedRuntimeVersion ""
```

**Comment by FeodorFitsner** [comment]
New version of Deployment Agent 3.22.10 has been published having this feature: https://www.appveyor.com/downloads/deployment-agent/latest/AppveyorDeploymentAgent.msi
