### ISSUE TITLE
Repository rename

### ISSUE THREAD

**Issue by RaYell** [appveyor/ci#1082]
I've renamed my repository and moved it to an organization, but in Appveyor it still uses the old names in the URL and there's no way to change it via UI.

Old name: https://ci.appveyor.com/project/RaYell/selenium-helpers
Desired: https://ci.appveyor.com/project/RaYell/Selenium.WebDriver.Extensions

**Comment by FeodorFitsner** [comment]
It's been renamed.

**Comment by RaYell** [comment]
Thanks
