### ISSUE TITLE
Customize commit status context on project level

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1083]
Discussion: http://help.appveyor.com/discussions/kb/4-show-multiple-statuses-in-github-pull-requests

**Comment by brianlagunas** [comment]
Any update on this issue?  My repo has 4 projects, but only one status is shown.  So if only one project build is broken and fails, I still get a green light because the other three project builds passed.  This is not good and is very misleading.

**Comment by kapilkd13** [comment]
Is this issue solved. My repo has 2 appveyor projects, for frontend part and backend part. I can only seethe latest commit status check. 
Is there a way that a user can specify/modify commit status context. 
Hi @brianlagunas Did you found a solution to this.

**Comment by brianlagunas** [comment]
@kapilkd13 no, I have not found a way to make this work.  You would think this would be a higher priority as it is such a common need.

**Comment by bdspaul** [comment]
I have to AV projects for one GH repo. The status for the second AV project "overwrites" that of the first. I'd like to be able to specify in AV which project is the "truth".

**Comment by FeodorFitsner** [comment]
The update with this feature has been deployed.

There is now new `Custom commit status context` field on "General" tab of project settings that allows to specify custom commit status context. Works for GitHub and GitLab projects only. Let us know how that worked.

**Comment by brianlagunas** [comment]
Can you provide a link to the docs on how to use this new field and show multiple projects status for a single GitHub PR build?

**Comment by FeodorFitsner** [comment]
Well, the field is pretty self-descriptive. Just put anything into it that will differentiate one project from another (like `project A` or `project B`) and this value will be shown on status checks pane.

**Comment by brianlagunas** [comment]
Just so you know, it's not that self-descriptive and a tooltip that explains it exactly like you did would help a lot of people.

I will give it a try and let you know if it works.  Thanks,

**Comment by brianlagunas** [comment]
Also, I want o confirm hat this is supposed to show multiple checks in the GitHub PR?  One for each project?  Right now I am only seeing 1 check.

![image](https://user-images.githubusercontent.com/835562/28784877-edf36010-75d1-11e7-815b-70bd74e2f1bb.png)

**Comment by FeodorFitsner** [comment]
When the project starts it adds "pending" status and then "success/failed" when finished. Looking at screenshot I guess just the project with non-customized status context has run.

**Comment by bdspaul** [comment]
Brian - I have it running with two projects. In my second project I have the _commit status context_ set to some value ("IGNORE_ME" in my case) and that appears next to the default _continuous-integration/appveyor/pr_ from the first.

I then configure GitHub to only allow merging when the first project builds successfully (the second is a spike project so I don't care if it fails)

![pic5](https://user-images.githubusercontent.com/13587296/28785254-bdc2480c-760d-11e7-9868-be143329c852.png)

**Comment by brianlagunas** [comment]
I have confirmed this fix.  Awesome!
![image](https://user-images.githubusercontent.com/835562/28845608-dbf04564-76c5-11e7-9a2f-0b7f5fc02102.png)

**Comment by mback2k** [comment]
@FeodorFitsner Would it eventually be possible to also have a status displayed for each job? The [curl project](https://github.com/curl/curl) runs quite some jobs on AppVeyor, but that status is lost between all the other CI status and it would help to see each AppVeyor job status.
