### ISSUE TITLE
SQL database deployment provider fails to deploy to SQL Server 2016

### ISSUE THREAD

**Issue by britzkopf** [appveyor/ci#1098]
RDP to build worker and deploy manually works, but using the same dacpac file and deploying from build ui generates error.
This occurred  after manually installing latest Sql server management studio to build worker and successfully deploying dacpac, then deleting created database and continuing with build. 

https://ci.appveyor.com/project/appveyor-tests/dacpac-local-2016

**Comment by FeodorFitsner** [comment]
Error from the log:

```
Error publishing database: Could not deploy package. Internal Error. The database platform service with type Microsoft.Data.Tools.Schema.Sql.Sql130DatabaseSchemaProvider is not valid. You must make sure the service is loaded, or you must provide the full type name of a valid database platform service. Internal Error. The database platform service with type Microsoft.Data.Tools.Schema.Sql.Sql130DatabaseSchemaProvider is not valid. You must make sure the service is loaded, or you must provide the full type name of a valid database platform service.
```

**Comment by SudipNalla** [comment]
Hi

What was the issue here and how did you guys resolved it?
I am facing similar issue with my DB project where I am trying to migrate from 2012 box to 2016 box.

**Comment by FeodorFitsner** [comment]
@SudipNalla what error are you getting exactly? Is there a hosted or on-prem AppVeyor?
