### ISSUE TITLE
Blue ANSI Color too dark

### ISSUE THREAD

**Issue by fniephaus** [appveyor/ci#1102]
The blue ANSI color (`\033[34m`) is very dark/almost unreadable:
![image](https://cloud.githubusercontent.com/assets/2368856/19223861/3c5f7648-8e7a-11e6-91d7-f7fe60bb6c6a.png)
[Example build](https://ci.appveyor.com/project/smalltalkCI/smalltalkci/build/115/job/mnrlf3rsw65518et#L30)

**Comment by FeodorFitsner** [comment]
Will fix that, thanks for letting know!
