### ISSUE TITLE
Do not show branch builds in PRs for same branch

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#1115]
If AppVeyor is configured to build both branches and PRs, and a PR is not made from a fork but from a different branch of the same repository, two AppVeyor builds show up in the PR, see e.g. the `continuous-integration/appveyor/branch` and `continuous-integration/appveyor/pr` links at https://github.com/github/git-lfs/pull/1585. While it's probably not possible to avoid these duplicate builds altogether (because the PR could be filed after the branch was pushed, at a time when the branch build already completed), the build for the branch should not show up as part of the PR. It's confusing to see it there.

**Comment by FeodorFitsner** [comment]
By adding the following option to `appveyor.yml` you can avoid building feature branch if there is an open PR(s) for this feature branch:

```yaml
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
```

**Comment by sschuberth** [comment]
That does not seem to work if the feature branch has been pushed some time before the PR was filed. See https://github.com/github/git-lfs/pull/1594, which is the commit introducing this option, and yet I see both `continuous-integration/appveyor/branch` and ` continuous-integration/appveyor/pr` in the PR.

The way I think it should work is like this: If building both branches and PRs is enabled, the branch build will always start first as you cannot file a PR without having the branch pushed. Thus, if a PR is filed, it should look whether a branch build for the same SHA1 already exists. If so, just use that as the PR build. That should help to to save a lot of resources due to duplicate builds.

In any case, not both `continuous-integration/appveyor/branch` and ` continuous-integration/appveyor/pr` should show up for the same PR. Even if you could not avoid running both the branch and the PR builds, only the PR build should show up in a PR, IMO.

**Comment by FeodorFitsner** [comment]
PR build would have a different commit SHA from "head" branch build as PR builds "virtual merge" commit ("what would be" result of merging feature branch into master branch). If you don't need building feature branches you can set branches filter in `appveyor.yml`:

```yaml
branches:
  only:
    - master
```

**Comment by sschuberth** [comment]
>as PR builds "virtual merge" commit

Ah, yes, you're right. But SHA1s should only differ if that "virtual merge" if not a fast-forward "merge". If the feature branch is a strict super set of the target branch, you could still spare the PR build.

> you can set branches filter

Thanks, that might be an option.

So, the value in having both the pure feature branch build *and* the PR build of the "virtual merge commit" in the PR is to see whether the merge itself introduced any issues, i.e. whether any commits introduced into the target branch after the feature branch has been branched off introduce a breakage in conjunction with the feature branch commits. Right?

**Comment by FeodorFitsner** [comment]
Exactly!

**Comment by dahlbyk** [comment]
Is it possible to switch AppVeyor from building the "virtual merge" commit (`refs/pull/N/merge`) to using the actual branch tip (`refs/pull/N/head`)?

**Comment by IlyaFinkelshteyn** [comment]
Sorry I maybe misunderstand the question, but as it was said in the beginning of this thread, by default 2 builds happen -- both "virtual merge" and branch build. Is branch build not what you need?

**Comment by dahlbyk** [comment]
They're similar, but not the same, especially in the context of settings like "Pull Requests do not increment build number". The two specific differences I see:

1. branch build will build branches without pull requests, which is not a problem for my project but may be for others. (And there's the "don't build PR branches" setting.)
2. I believe branch builds would miss PR branches from forks.

I also get email for branch build failures but not PR build failures, which may just be specific to how my account is configured.
