### ISSUE TITLE
appveyor.yml parse error should report failed status back to repo

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#112]
Discussion: http://help.appveyor.com/discussions/problems/1381-appveyoryml-parse-error-should-report-failed-status-back-to-repo

**Comment by vors** [comment]
Also, similar problem:
https://ci.appveyor.com/project/guillermooo/powershell/build/1.0.40 reported back that build failed https://github.com/SublimeText/PowerShell/pull/73

PR was merged before build started, so appveyor should not report any status: it cannot build anything.

**Comment by FeodorFitsner** [comment]
I see, thanks. Will be fixed this week.

-Feodor

**Comment by FeodorFitsner** [comment]
Or even better I this that task might be also related to these ones:
https://github.com/appveyor/ci/issues/77
https://github.com/appveyor/ci/issues/29
https://github.com/appveyor/ci/issues/38
