### ISSUE TITLE
Node.js 4.6.1, 6.9.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1120]

**Comment by XhmikosR** [comment]
Make it 4.9.1 please.

**Comment by FeodorFitsner** [comment]
What do you mean?

**Comment by XhmikosR** [comment]
There's a newer version out.

**Comment by FeodorFitsner** [comment]
I see 4.6.1 as the last one on the home page: https://nodejs.org/en/

**Comment by XhmikosR** [comment]
And 6.9.1 as LTS, not 6.9.0.

**Comment by FeodorFitsner** [comment]
Oh, snap, indeed - there is 6.9.1! 😄 
Though both 4.6.1 and 6.9.1 are LTS now - I'm confused.

**Comment by XhmikosR** [comment]
https://github.com/nodejs/LTS#lts-schedule

**Comment by XhmikosR** [comment]
So there will be v7 soon out.

**Comment by XhmikosR** [comment]
There's a newer version out.

**Comment by FeodorFitsner** [comment]
Yep: https://github.com/appveyor/ci/issues/1131
