### ISSUE TITLE
document for artifacts types

### ISSUE THREAD

**Issue by zh99998** [appveyor/ci#1128]
https://github.com/appveyor/website/issues/192
i submitted an issue here but don't get response for more than a month

> https://www.appveyor.com/docs/packaging-artifacts/
> here artifacts has a type attribute but i can't find anywhere what types are supported?
> does build-in archive package support 7z, tar.xz, any other? or just zip?

**Comment by FeodorFitsner** [comment]
This section has been updated with artifact types: https://www.appveyor.com/docs/packaging-artifacts/#basics
