### ISSUE TITLE
choco install python

### ISSUE THREAD

**Issue by geoffviola** [appveyor/ci#1130]
I'm trying to use chocolatey to get python, because I want to follow these custom build instructions precisely: https://github.com/ros2/ros2/wiki/Windows-Install-Binary. When, I run "choco install python -y", I get error code 1638: https://ci.appveyor.com/project/geoffviola/ros2-boost/build/1.0.76. According to https://msdn.microsoft.com/en-us/library/windows/desktop/aa376931(v=vs.85).aspx error code 1638 means it's complaining that python is already installed. 

I'm not sure what it thinks is installed. Is it possible to run appveyor without a version of python?

**Comment by gep13** [comment]
@geoffviola if you check here: https://www.appveyor.com/docs/installed-software/#python you can see that there are quite a few different versions of python already installed on the build worker image for AppVeyor.  I think you should be able to use one of those, rather than first install it again.

**Comment by geoffviola** [comment]
One of the scripts specifically calls out C:\ProgramData\chocolatey\lib\python3\tools\python.exe. I ended up finding and replacing that text to just python. That seemed to have worked. Maybe, a better solutions is to try to get that project to change their script.

That being said it might be nice to have the exact same version of python as them. The difference is 3.5.1, which chocolatey uses, instead of 3.5.2, which is preinstalled. Of course, 3.5.2 seems to work fine for now.

**Comment by gep13** [comment]
Hard coding the path to this: `C:\ProgramData\chocolatey\lib\python3\tools\python.exe` is not a good idea, so from that perspective, yes, I would suggest that the original script needs to be changed.  There were some issues with the choco package where python wasn't getting added to the path, but I believe that has now been taken care of, so the requirement to hard code the path shouldn't be there anymore.

**Comment by geoffviola** [comment]
Sounds good. Thanks for the feedback.
