### ISSUE TITLE
Builds are very long to start for the conda-forge organization

### ISSUE THREAD

**Issue by hadim** [appveyor/ci#1136]
Builds are very long to start for the conda-forge organization. I think we only have 2 concurrent builds for the whole organization and it's really not enough for us.

Our goal is to bring a whole ecosystem of softwares to Linux, OSX and also **Windows**, this is why we need to have a quick feedback on our recipes and a quick start of the builds will be very helpful.

Could you do something about that ?

Thanks !

@jakirkham @ngoldbaum

**Comment by FeodorFitsner** [comment]
You can upgrade with more concurrent jobs which is $25/month per OSS job.

**Comment by kynan** [comment]
@FeodorFitsner since conda-forge is a community project there is not budget for this unfortunately (unless it was covered by sponsors).
