### ISSUE TITLE
Console colors issue with Karma test results

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1138]
https://ci.appveyor.com/project/JohnReilly/proverb-signalr-react/build/1.0.9

**Comment by Kristinita** [comment]
+1.

Green color background for:

Circle CI:

![Circle CI](https://i.imgur.com/pTz69D9.png)

Travis CI:

![Travis CI](https://i.imgur.com/NvrBNJo.png)

AppVeyor:

![AppVeyor](https://i.imgur.com/Bs3kLaE.png)

AppVeyor green background is bad.

Thanks.
