### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by matthargett** [appveyor/ci#1150]
Right now, we can build our Universal Windows App, but can't run any tests on AppVeyor. 

Please add a Windows Server 2016 environment, now that RTM build have been available for a month.

(Note: We use shared code between our WPF and UWP projects, so we still need the older OS environments available as well.)

Updating Docker:

```posh
Install-Package -Name docker -ProviderName DockerMsftProvider -Verbose -Update -Force
start-service docker
```

**Comment by FeodorFitsner** [comment]
Please look at this thread for Windows Server 2016 status: http://help.appveyor.com/discussions/questions/2652-windows-server-2016

**Comment by matthargett** [comment]
@FeodorFitsner any updates on this? is there a way my account can be added to the beta list, like you did with VS2017 RC?

**Comment by FeodorFitsner** [comment]
Still working on that. Struggling to install Docker on Windows Server 2016 image provided by Google Compute Cloud.

**Comment by matthargett** [comment]
Tweeted to @csells asking for some assistance. Hopefully he can help get some attention to the issue on the Google side.

**Comment by FeodorFitsner** [comment]
Thanks!

**Comment by csells** [comment]
What's the problem with Docker on GCP Windows Server 2016?

**Comment by FeodorFitsner** [comment]
Hi Chris,

thanks for looking into that!

What I'm really trying to do is simply:
1. Provisioning fresh VM on GCE standard "Windows Server 2016" image. I'm giving it 4 cores and 15 GB of RAM.
2. Installing system updates on its first boot.
3. Reboot VM.
4. Follow this guide to install Docker: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
5. After restarting VM I'm either able to connect via RDP, but Docker service is forever in "Restarting" state or I'm not able to connect to VM via RDP at all. It never goes online after consequent reboots - nothing helps to restore RDP connectivity.

Do you have any success deploying Docker to Windows Server 2016 machine hosted on GCE?

**Comment by fengmin75** [comment]
Hi Feodor,

This was a feature incompatibility between GCE virtual network and Docker. We are working on a fix at the moment. The work around right now is to turn off Rsc feature before installing docker.

PS C:> netsh netkvm setparam 0 *RscIPv4 0
PS C:> netsh netkvm restart 0

Please refer to the documentation below for full detail.

https://cloud.google.com/compute/docs/containers/#docker_on_windows

**Comment by FeodorFitsner** [comment]
It worked like a charm, yay! 😄 Thanks you guys for the help with solving that - we are unblocked now!

**Comment by matthargett** [comment]
Awesome! Let me know when we can try it so we can finally run our Universal Windows Tests in AppVeyor!

PS: we've been emailing team@appveyor.com to try and set up a call to discuss enterprise business plans, but haven't been getting a response there. Emails would have been from bluejeans.com or bluejeansnet.com

**Comment by FeodorFitsner** [comment]
Oh, will reply on those messages today, sorry for the delay.

**Comment by PeterMTaylor** [comment]
Hi there, on the topic of windows server 2016 for appveyor.
When executing Powershell install-module is questioning credentials installing PScribo.
I have asked the PScribo author and he found that the environment for virtual machine aren't updated to the latest. iainbrighton/PScribo#30
Can I ask if Window Server 2016 is scheduled soon or is there a workaround on Powershell side on appveyor virtual machine.
Thanks, Peter.

**Comment by FeodorFitsner** [comment]
We'll start offering `Windows Server 2016` image in a day-two. Stay tuned!

**Comment by FeodorFitsner** [comment]
`Windows Server 2016` image is ready. Please let us know if you want to give it a try!

**Comment by matham** [comment]
We would like to try it (for the KivyOrg account), and I guess on my personal account as well.
Thanks!

**Comment by dragon788** [comment]
I'd definitely check it out as I'd like to verify some Chocolatey packages work across all the versions of server available.

**Comment by matthargett** [comment]
please add @bluejeans @rozele and @matthargett so we can test UWP build of React Native Windows

**Comment by nibanks** [comment]
Please add @nibanks ([nibanks/openthread](https://ci.appveyor.com/project/nibanks/openthread)) and @jwhui ([jwhui/openthread](https://ci.appveyor.com/project/jwhui/openthread)) so we can test Windows 10 driver development.

**Comment by FeodorFitsner** [comment]
@dragon788, @bluejeans, @rozele, @matthargett, @nibanks, @jwhui added.

**Comment by FeodorFitsner** [comment]
@matham added to "KivyOrg".

**Comment by matham** [comment]
@FeodorFitsner Thanks for the add. 

So a few comments (should I do this here or on the message boards?), after adding `os: Windows Server 2016` the startup was quite slow; it took a few minutes to get started and then the cloning seemed slow. However, the bigger issue is that it still seems to have only [opengl 1.1](https://ci.appveyor.com/project/KivyOrg/kivy/build/1.0.626/job/c9inu6u99g5oxg5b#L1893) installed. That's the main reason for us to want to use it.

We do have `install: - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))` to enable the desktop, is there maybe something else we need to do?

**Comment by nibanks** [comment]
@FeodorFitsner I [validated](https://ci.appveyor.com/project/nibanks/openthread/build/0.1.631/job/uhoexxh56ea6fo9i) that I can successfully build, install and run Windows 10 drivers on the image you provided. Thanks!

I also noted that the build seemed to take a lot longer than usual to get started. Is this expected?

**Comment by nibanks** [comment]
My build finally finished and it essentially doubled in the time it took to build, as you can see from my [history](https://ci.appveyor.com/project/nibanks/openthread/history), from ~23 minutes to ~47 minutes.

**Comment by FeodorFitsner** [comment]
@nibanks Thanks for the feedback! That's right - `Windows Server 2016` image builds run on GCE and it takes around 3-4 minutes to provision and boot a new build worker VM there. As your build has multiple jobs those 3-4 additional minutes before each job add to the overall build time.

**Comment by FeodorFitsner** [comment]
@matham re: opengl - there is a "stock" Windows Server 2016 with VS 2015 on top of it. What would you need to do to get a different version of OpenGL?

**Comment by matham** [comment]
@FeodorFitsner hmm, I may have misunderstood what Server 2016 adds. I thought you'd have opengl support just with the vm, but it may need an actual graphics card that supports opengl > 1.1. See the section under `1. OpenGL 4.4 and OpenCL 1.1 API Support` [here](https://blogs.technet.microsoft.com/enterprisemobility/2014/11/05/remotefx-vgpu-updates-in-windows-server-next/).

I'm not sure if appveyor vms have graphics cards, does it?

**Comment by FeodorFitsner** [comment]
@matham `Windows Server 2016` images run on GCE. AFAIK they use KVM hypervisor - I'm not sure what capabilities its video adapter provides. Do you get required OpenGL when running on default `Visual Studio 2015` image?

**Comment by nibanks** [comment]
@FeodorFitsner When is this planned to be available for all? Until then, I assume if I merge a commit adding the usage of this, everyone who doesn't explicitly have this enabled will have their forks break?

**Comment by matham** [comment]
@FeodorFitsner so was trying to rdp to the server with the Windows server 2016 image, and something seems to be wrong with the printed rdp address. Windows says [the address](https://ci.appveyor.com/project/KivyOrg/kivy/build/1.0.630/job/qhx0yh2lxrew42ks#L124) is wrong.

**Comment by FeodorFitsner** [comment]
@matham RDP script has been fixed.

**Comment by FeodorFitsner** [comment]
@nibanks we've just started collecting feedback. I don't have an exact ETA right now. 
We’d really like to understand what people might require on that image besides Docker and VS 2015 (we really don’t want dealing with VS 2013 stuff on that image). It could be in a week or so when it will become generally available.

**Comment by matham** [comment]
@FeodorFitsner ran it again and the rdp is working again. So, no, I could not get opengl > 1.1 to work on Visual Studio 2015 image. I was hoping that server 2016 would add emulation so that you'd have opengl > 1.1 even if there was no GPU present, but it seems a [GPU is required](http://windowsitpro.com/windows-server-2016/when-gpu-can-be-utilized-session-virtualization-2016) for opengl > 1.1.

GCE doesn't seem to have GPUs on the VMs you're running, so I guess that would not be possible.

**Comment by Crevil** [comment]
Could you add `EGAppVeyor` to the image as well?

**Comment by IlyaFinkelshteyn** [comment]
@Crevil added

**Comment by PeterMTaylor** [comment]
Hi @FeodorFitsner, just to check the following points with you.
1) Is the Windows Server 2016 installed on the WMF 5 image when indicated this is installed? If not, please advise which image I need to point my appveyor.yml file to reflect this.
2) Recent tests with my appveyor.yml on the WMF 5 configuration tells me no change mentioned earlier. 
PackageManagement\Install-Package : The version '0.7.13.51' of the module 'PScribo' being installed is not catalog signed. Ensure that the version '0.7.13.51' of the module 'PScribo' has the catalog file 'PScribo.cat' and signed 
with the same publisher 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US' as the previously-installed module '0.7.13.51' with version '0.7.13.51' under the directory 'C:\Program 
Files\WindowsPowerShell\Modules\PScribo\0.7.13.51'. If you still want to install or update, use -SkipPublisherCheck parameter.
3) As indication of the root cause appears to be "a Server 2016 cumulative update issue" affecting credential on the Powershell side. Is there a way to determine which version of Windows Server 2016 affecting this 
Thanks, Peter.

**Comment by FeodorFitsner** [comment]
WMF 5 image is based on Windows Server 2012 R2.

`Windows Server 2016` image should be enabled for your account before you can see/use it. Tell us your AppVeyor account name and we'll make this image available for you.

**Comment by neonboxx** [comment]
Hi @FeodorFitsner please could you enable the 2016 image on the sequensis account? 
Would love to try out some docker builds, thanks.

**Comment by FeodorFitsner** [comment]
@neonboxx added.

**Comment by PeterMTaylor** [comment]
@FeodorFitsner, ok then, my appveyor account is the same as Github name "PeterMTaylor". Thanks.

**Comment by IlyaFinkelshteyn** [comment]
@PeterMTaylor added

**Comment by rick-powell-sfw** [comment]
A bit late to the party but would love to try docker builds too. My appveyor username is rickpowell131@hotmail.co.uk

**Comment by IlyaFinkelshteyn** [comment]
@rick-powell-sfw Added.

**Comment by MatZub** [comment]
@IlyaFinkelshteyn Hi, I would also like to test docker build functionality, as it would help speed up the development process of our applications considerably. My appveyor username is matas@mediapark.com.

**Comment by IlyaFinkelshteyn** [comment]
@MatZub Added!

**Comment by DDoSolitary** [comment]
Could you please add `DDoSolitary`? Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@DDoSolitary added

**Comment by dgageot** [comment]
Could you please add `Pinata`? Thanks a lot!

**Comment by FeodorFitsner** [comment]
@dgageot added.

**Comment by friism** [comment]
@FeodorFitsner @IlyaFinkelshteyn can you add `friism` please?

**Comment by Yshayy** [comment]
Hi, can you add TomerDvir as well?
Thanks

**Comment by IlyaFinkelshteyn** [comment]
@friism @Yshayy Added!

**Comment by friism** [comment]
@IlyaFinkelshteyn @FeodorFitsner do you think there's going to be any way to cache Docker layers between builds? The simplest way would be to cache `$Env:ProgramData\docker`, but that vastly exceeds the 100MB that's the documented build cache limit.

Having to rebuild from scratch sucks

**Comment by FeodorFitsner** [comment]
Cache is 1 GB for free accounts. 100 MB was an old limits. Give it a try and let me know how it worked.

**Comment by friism** [comment]
@FeodorFitsner ah, ok - there's a mention of 100MB [here](https://www.appveyor.com/docs/build-cache/#how-it-works), but I see there's an updated table below.

1GB is not enough either for Windows containers (eg. the base layers alone 10s of GB). I don't think larger cache limits are a reasonable request, and I'm pondering a more reasonable alternative.

**Comment by Yshayy** [comment]
Hi, is there an image version with support for both V2017RC and docker?

**Comment by FeodorFitsner** [comment]
Combined Windows 2016 + VS 2017 image will be available shortly after VS 2017 release.

**Comment by Yshayy** [comment]
Is there any workaround to build VS2017 aspnet core with docker deployment on Appveyor?

**Comment by friism** [comment]
@Yshayy You can just use Docker: https://github.com/friism/MusicStore/blob/master/Dockerfile.windows#L1

That Dockerfile builds a ASP.NET Core app. This docker-compose file runs it with SQL Server: https://github.com/friism/MusicStore/blob/master/docker-compose.windows.yml

And AppVeyor runs it: https://github.com/friism/MusicStore/blob/master/appveyor.yml#L8

You don't need it to do the above, but here's a Dockerfile with the VS2017 build tools: https://github.com/friism/dockerfiles/blob/master/vs-build-tools/17/Dockerfile

**Comment by hferentschik** [comment]
I would be interested in testing the Windows 2016 image as well. My account is 'hferentschik'.
My use case would be to run nested virtualization. Any idea whether this would work. We are working on a Go project which creates and manages a VM usings Docker's libmachine. We can already build and unit test on AppVeyor, but to be able to run our integration tests we would need nested virtualization.

**Comment by StefanScherer** [comment]
@hferentschik Nested virtualization would be great, but I don't think it will work for 64bit machines. But you can read https://stefanscherer.github.io/how-to-create-a-32bit-boot2docker-for-x86-cpus/, about a year ago I ran a 32bit docker machine in AppVeyor. Maybe that helps you a little bit.

**Comment by gbraad** [comment]
@FeodorFitsner, I work with @hferentschik on the same project. It would be great to have access to try some stuff. account name is 'gbraad'.

**Comment by IlyaFinkelshteyn** [comment]
@hferentschik @gbraad Added!

**Comment by bsideup** [comment]
Hi!

I'm co-maintainer of http://github.com/testcontainers/testcontainers-java and we would like to start testing it on Windows.

Could you please add my account (I use fork to develop) and testcontainers org to the beta program?

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@bsideup Sure, added.

**Comment by bsideup** [comment]
@IlyaFinkelshteyn thank you!

**Comment by smudge202** [comment]
Could I also be added please, @IlyaFinkelshteyn ? <3

**Comment by IlyaFinkelshteyn** [comment]
@smudge202 Sure, added!

**Comment by smudge202** [comment]
Is anyone else having problems with volume mounting? I can't for love nor money get APPVEYOR_BUILD_FOLDER mounted despite following workarounds suggested here:

* https://github.com/docker/docker/issues/12590#issuecomment-96767796
* http://superuser.com/questions/1051520/docker-windows-container-how-to-mount-a-host-folder-as-data-volume-on-windows

Example command:

```
$originalMountSpecification = "$(Get-Location)/:/app"
$mountSpecification = $originalMountSpecification.ToLowerInvariant().Replace("\", "/")
"'$originalMountSpecification' -> '$mountSpecification'"
docker run -it --rm -v ${mountSpecification} --workdir /app microsoft/aspnetcore-build bash -c "dotnet restore CleanSpace.sln && dotnet publish src/api/api.csproj -c Release -o ./obj/Docker/publish"
```

Results in error: 

```
docker : C:\Program Files\Docker\docker.exe: Error response from daemon: invalid bind mount spec "c:/projects/clean-space/:/app": invalid volume specification: 'c:\projects\clean-space\:\app'.
At C:\projects\clean-space\build\build-api-appveyor.ps1:12 char:1
+ docker run -it --rm -v "${mountSpecification}" --workdir /app microso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...n-space\:\app'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Does Windows Server 2016 require config akin the Docker for Windows shared drives? If so, can this be done on the image or does someone know how to do it on the fly?

**Comment by FeodorFitsner** [comment]
@smudge202 I believe correct mount specification for Docker with Windows Containers might be the following:

    $originalMountSpecification = "$(Get-Location)/:c:/app"

**Comment by smudge202** [comment]
The above was a linux image; I've switched to a windows image since (`microsoft/dotnet:sdk-nanoserver`). This also has issues with mapping because the symlinkd doesn't work correctly for volume mounting unless you specify the full path. The latest iteration of the above command is:

`docker run --rm -v "$(Get-Location):$(Get-Location)" --workdir "$(Get-Location)" microsoft/dotnet:sdk-nanoserver "dotnet"`

Unfortunately this errors with:

```
C:\Program Files\Docker\docker.exe: Error response from daemon: container f84ce8779894e97766115eb9080d5b6cd094aa8a95bf7f4b2124787f15125427 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"ApplicationName":"","CommandLine":"-c dotnet","WorkingDirectory":"C:\\projects\\clean-space","Environment":{"DOTNET_SDK_DOWNLOAD_URL":"https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.1/dotnet-de
v-win-x64.1.0.1.zip","DOTNET_SDK_VERSION":"1.0.1","NUGET_XMLDOC_MODE":"skip"},"EmulateConsole":false,"CreateStdInPipe":t
rue,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
```

Utterly confusing because if I run the above in interactive (`-it`) without the command, I can run the `dotnet restore/publish` without issue, and the output is correctly available to the host. From what I've seen in vaguely related issues, I think my command syntax might be slightly out (for example, if you have [options in the wrong place](https://github.com/docker/for-win/issues/212#issuecomment-264970371) you also get this issue). However, I can't see how my command differs from the docker documentation.

**Comment by StefanScherer** [comment]
@smudge202 At the moment it's a little bit difficult to see if its a linux or windows image. I also had to look at it with `docker run stefanscherer/winspector microsoft/aspnetcore-build` first and it showed me that it's not a windows image.

I tried your command in an empty folder on the host and it worked for me. Probably it depends in which folder you are on the host as you can't map to a non-empty folder in the container. So the second `Get-Location` is not needed, use a fix folder inside the container to get rid of that dependency.

Use eg.

```powershell
docker run --rm -v "$(Get-Location):C:\work" --workdir "C:\work" microsoft/dotnet:sdk-nanoserver dotnet
```

**Comment by smudge202** [comment]
Yup, so long as I specify a drive in the target bind it should be right. I tend to just hop into docker hub and walk down the dockerfile FROM's until it shows nano/win. If it's not one of those, I assume it to be a linux distro. Like you say though, not obvious.

I did get everything working in the end (in that appveyor produces nanoserver based images for my aspnetcore stuff). I don't like that the warning docker produces when it can't find an image locally causes all remaining appveyor build output to show as errored text, but it does show as build success (tips on that greatly appreciated).

For all that effort, my end goal is to get images into my Docker Enterprise swarm in azure, which is currently linux based. Off to TravisCI for that half of things it seems (I don't believe any of the appveyor images are able to produce linux based docker images?).

**Comment by hpryce** [comment]
Hi,

Is it possible to enable the image for https://github.com/palantir/docker-compose-rule so we can use it to test compatibility with Windows?

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@hpryce If I understood correctly, AppVeyor account name is `iamdanfox`. Added.

**Comment by IlyaFinkelshteyn** [comment]
The new Visual Studio 2017 build worker image is now available. It has Visual Studio Community 2017 RTM installed on Windows Server 2016 with Docker and base Docker images.

Currently, the image is being run on Google Compute Engine (GCE) environment only, so builds will be starting in 3-4 minutes (time required to provision and boot up build VM). The image will be available on Hyper-V environment later this week.

**Comment by StefanScherer** [comment]
@IlyaFinkelshteyn Awesome! 
So all the private beta testers just have to change `image: Windows Server 2016` into `image: Visual Studio 2017`. That's easy.

**Comment by FeodorFitsner** [comment]
yep!

**Comment by PeterMTaylor** [comment]
Just letting you know I got a successful run with using image from WMF 5 to Visual Studio 2017. Thanks for that.

**Comment by FeodorFitsner** [comment]
`Windows Server 2016` image has been removed. Please adjust your builds to use `Visual Studio 2017` image instead which is based on Windows Server 2016 with Docker installed.
