### ISSUE TITLE
Duplicated tests results when using NUnit3 and the SetUpFixture attribute

### ISSUE THREAD

**Issue by peto268** [appveyor/ci#1162]
I've created a SetUpFixture (https://github.com/nunit/docs/wiki/SetUpFixture-Attribute) in my tests in a default namespace, so it will be applied to all the tests and it seems to cause all the tests being duplicated in AppVeyor. First the tests are listed with the filename being the dll which hosts them and second time they appear with a filename equal to the classname which has the SetUpFixture attribute.

**Comment by IlyaFinkelshteyn** [comment]
Hi Peter, I tried to do primitive repro [here](https://ci.appveyor.com/project/IlyaFinkelshteyn/unit-test-runners/history) and could not. As you can see number of tests is always 2, and addition of this `SetupFixture` did not change the result. Also in last build I wrote to console from `SetupFixture` methods to proof that it is really being called.

Can you please create a small "hello word" repro in a public repository?

--ilya.

**Comment by peto268** [comment]
I've tried to fiddle with the project a bit and the reason why this was happening is because i'm running the tests using a custom PS script. The script was running the tests using the command:
``nunit3-console.exe --result=src\out\TestResult.xml;format=AppVeyor``
After that i'm uploading the results using the AppVeyor API.
Somehow (and i really don't know how) AppVeyor knows about the test results even before i publish the result  xml using the API. After i publish the test results, the tests gets duplicated.
Before i introduced the SetUpFixture, AppVeyor was able to deduplicate the results, but after that it kept the duplicates. So the solution for me was to remove the generation of the results xml and the API call. Now the tests aren't duplicated.
So i assume this bug can be considered closed. But anyway I would really welcome some more information on this in the docs.
Thanks for your support!

**Comment by IlyaFinkelshteyn** [comment]
Good:! If you can share your appveyor.yml it would be helpful to understand how it knows AppVeyor knows about the test results when it supposed to wait until XML provided :)

Thanks!
Ilya.

**Comment by peto268** [comment]
Hello, the yml isn't that interesting, most of the stuff is happening in a custom PS script, what i've basically did was something like:

```
$assemblies = (Get-ChildItem -Recurse -Path ".\*\bin\Debug" -Filter *.Tests.dll),
[System.Collections.ArrayList]$additionalArgs = @()

$nunit3Console = "nunit3-console.exe"
$additionalArgs.Add("--result=src\out\TestResult.xml;format=AppVeyor")

& $nunit3Console $assemblies $additionalArgs

$wc = New-Object 'System.Net.WebClient'
$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path src\out\TestResult.xml))
```

In the yml:
```
test_script:
  - powershell RunTests.ps1
```
