### ISSUE TITLE
Error running pacman on 32-bit MSYS2

### ISSUE THREAD

**Issue by asbjornu** [appveyor/ci#1170]
As mentioned in #733, we're suddenly seeing [problems like this](https://ci.appveyor.com/project/jangler/schismtracker/build/1.0.51/job/u2oidbolk5nbl3mm#L415) on 32-bit MSYS2 when running `pacman --sync --noconfirm --needed base-devel`:

```sh
could not create directory /var/lib/pacman/local/file-5.28-2/: File exists
```

[64-bit versions of the same build are successful](https://ci.appveyor.com/project/jangler/schismtracker/build/1.0.51/job/xr8d39li063vc5qy), so I wonder what's going on here. Ideas?

**Comment by FeodorFitsner** [comment]
When did it start happening? This might be some external factors. There were some recent updates to build workers, but nothing critical so far: https://www.appveyor.com/updates/

**Comment by asbjornu** [comment]
From the [build history](https://ci.appveyor.com/project/jangler/schismtracker/history), I can see that the problem started with [build 1.0.45 at October 30th](https://ci.appveyor.com/project/jangler/schismtracker/build/1.0.45), while everything was fine in [build 1.0.44 at October 8th](https://ci.appveyor.com/project/jangler/schismtracker/build/1.0.44).

The [commit that first failed the build](https://github.com/schismtracker/schismtracker/commit/f5f711aa1d1fb894238283fe5a8bf30ad41f38a0) is not related to MSYS2 or infrastructural stuff at all, so I don't understand why the build suddenly started failing some time between October 8 and 30.

**Comment by IlyaFinkelshteyn** [comment]
[This duplicate database entry error](https://ci.appveyor.com/project/jangler/schismtracker/build/1.0.45/job/xuigqxybtao9mc5x#L106) looks suspicious, can you check if it expected? 

Thanks!
--ilya.

**Comment by asbjornu** [comment]
@IlyaFinkelshteyn: I agree that looks suspicious. So I went ahead and [removed `cache: 'C:\msys32'` from appveyor.yml](https://github.com/asbjornu/schismtracker/commit/3e0c4a34c80e15e2d1870105c64da347b135accc) and now [the build succeeds](https://ci.appveyor.com/project/asbjornu/schismtracker/build/job/95qc1ln6w1waqsod). Each 32-bit build will now probably take a longer time, but at least it doesn't fail. Thanks! 😄
