### ISSUE TITLE
 Security Problem: The sftp deployment authentication error

### ISSUE THREAD

**Issue by KangLin** [appveyor/ci#1173]
Hi,
Given this in appveyor.yml:

deploy:
  provider: FTP 
  protocol: sftp 
  host: frs.sourceforge.net
  username: kl222,RabbitGIS
  password: 
    secure: 2WEtOQrdty3V3g0aEVvS3Q== 
  folder: pfs/Release   #link pfs to /home/frs/project/r/ra/rabbitgis
  draft: false
  active_mode: false

Previously successful deployment, but now the authentication fails:

Collecting artifacts...
Found artifact 'build_windows_msvc\install' matching 'build_windows_msvc\install' path
Uploading artifacts...
[1/1] build_windows_msvc\RabbitGIS_windows_msvc14_x86_qt5.7_v0.1.0.55.zip (59,543,330 bytes)...100%
Deploying using FTP provider
Cannot connect SFTP server: No suitable authentication method found to complete authentication (publickey,keyboard-interactive).

My project:
https://ci.appveyor.com/project/KangLin/RabbitGis

**Comment by IlyaFinkelshteyn** [comment]
Hello,

Hmm, I see that your .yml file did not changed since successful deployments and on AppVeyor side I don't see if something changed which can affect sftp client...

Could you please check that you still can connect to `frs.sourceforge.net` the same credentials from your computer, using some desktop clients like [WinSCP](https://winscp.net) or [FileZilla](https://filezilla-project.org/)? 

--ilya.

**Comment by KangLin** [comment]
Yes, My desktop clients can connect to frs.sorceforge.net.
I also looked at other projects that are also the same result. I think it is Appveyor deployment What is the problem, I have seen recently updated ssh, Whether it is the reason.

**Comment by IlyaFinkelshteyn** [comment]
Sorry, you are right, it does not work and it is most probably connected to changed SSH.NET package. We are investigating and will update you. As a workaround you can use custom script deployment based on [WinSCP](https://chocolatey.org/packages/winscp.portable) ([scripting manual](https://winscp.net/eng/docs/scripting)). 

--ilya.

**Comment by KangLin** [comment]
OK, I'll wait for you to update.

**Comment by IlyaFinkelshteyn** [comment]
This appears to be some authentication change on sourceforge side. You can ensure it with simple program
```
using Renci.SshNet;
class Program
{
    static void Main(string[] args)
    {
        var ftp = new SftpClient("frs.sourceforge.net", 22, "user", "password");
        ftp.Connect();
    }
}
```
It will throw the same error.
We are looking for workaround, will update you.

--ilya.
