### ISSUE TITLE
how to expose conda packages as artifacts?

### ISSUE THREAD

**Issue by denfromufa** [appveyor/ci#1174]
https://github.com/pythonnet/pythonnet/pull/281#issuecomment-260843597

**Comment by IlyaFinkelshteyn** [comment]
Hello,

According to [your YAML config](https://github.com/pythonnet/pythonnet/blob/master/appveyor.yml#L35), everything in `dist` folder is packaged as artifacts. So you need to ensure that packages are in this folder, or add another path to collect artifacts. Sure `dist` folder is relative to build folder which is by default project root, specifically `C:\projects\pythonnet`.

--ilya.

**Comment by IlyaFinkelshteyn** [comment]
It should be relative path, and not above build folder. I mean relative starting with `..\` will not work too. And yes you can use ** for recursive scan. More info [here](https://www.appveyor.com/docs/packaging-artifacts/).

**Comment by denfromufa** [comment]
@IlyaFinkelshteyn I will let @jreback comment, but most likely it is not possible to bring conda artifacts under C:\projects\pythonnet. So I guess we need to add a post-build script to copy from %PYTHON_BLD%\conda-bld\**\*.tar.bz2 to C:\projects\pythonnet\dist\?

**Comment by IlyaFinkelshteyn** [comment]
It seems like least expensive solution for me.

**Comment by denfromufa** [comment]
@IlyaFinkelshteyn is the environment variable for build directory C:\projects\pythonnet =  APPVEYOR_BUILD_FOLDER ?

**Comment by IlyaFinkelshteyn** [comment]
Yes, exactly. More [here](https://www.appveyor.com/docs/environment-variables/) :)
