### ISSUE TITLE
.NET Core 1.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1176]
Announcement: https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/
Download: https://www.microsoft.com/net/download/core

After installing .NET Core SDK 1.1 and VS Tooling:

1. Run these commands :

```
cd %temp%
md coreapp1
cd coreapp1
dotnet new
dotnet restore
dotnet run
```

2. Open VS 2015 and create a new .NET Core web project.

**Comment by janhartmann** [comment]
Is there a workaround for now? Where to obtain it during install?

**Comment by FeodorFitsner** [comment]
As far as I understand from [download page](https://www.microsoft.com/net/download/core) VS 2015 Tooling is the same and to support .NET Core 1.1 someone should install *the .NET Core 1.1 runtime* only. Am I right?

**Comment by michielpost** [comment]
Yes correct, only the .Net Core runtime is updated, VS2015 is not updated

**Comment by FeodorFitsner** [comment]
Just tried to install runtime (.NET Core 1.1 runtime - Installer) only and noticed that `dotnet --version` is the same `1.0.0-preview2-003131`. However, after additionally installing SDK (.NET Core 1.1 SDK - Installer) `dotnet --version` changed to `1.0.0-preview2-1-003177` which is what we need, right? So, my understanding is that SDK 1.1 should be installed instead to get both 1.1 runtime **and** new `dotnet` tooling.

**Comment by michielpost** [comment]
Yes sounds good, dotnet version `1.0.0-preview2-1-003177` is what we need

**Comment by lukasz-pyrzyk** [comment]
Hi folks, is there any update?

**Comment by niemyjski** [comment]
VS2017 has it labeled as `1.0.0-preview3-004056` @FeodorFitsner

**Comment by FeodorFitsner** [comment]
Working on this. .NET Core 1.1 will be available early this week.

**Comment by lukasz-pyrzyk** [comment]
Great to hear that news!

**Comment by holytshirt** [comment]
Thanks @FeodorFitsner looking forward to .NET Core 1.1 support!

**Comment by ctolkien** [comment]
For those playing along at home... would something like this work?

```
install:
- ps: appveyor DownloadFile https://go.microsoft.com/fwlink/?LinkID=835014 -FileName "c:\dotnet.exe"
- ps: c:\dotnet.exe /quiet```
```

(LInked file is to download the 1.1 SDK)

**Comment by StummeJ** [comment]
@ctolkien Does that skip UAC? @FeodorFitsner  is UAC even enabled on the build servers?

**Comment by FeodorFitsner** [comment]
UAC is disabled on build workers.

We've just deployed an image update with .NET Core 1.1 installed - no need to install it during the build.

**Comment by RonnChyran** [comment]
Is this enabled on the VS2015 image?

**Comment by FeodorFitsner** [comment]
Correct.

**Comment by Crevil** [comment]
I'm having trouble running a .NET core 1.1 project from the CLI.
When running `dotnet --info` i get the following:

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576
```

But I expected this to be:

```
dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607
```

Is the new CLI (the one with `msbuild` and `.csproj` handling) not available on AppVeyor as is?

**Comment by niemyjski** [comment]
@Crevil you need to use VS2017 RC image.. 2015 won't support the new csproj format

**Comment by IlyaFinkelshteyn** [comment]
@Crevil I added `Visual Studio 2017 RC` image to your account

**Comment by Crevil** [comment]
@IlyaFinkelshteyn Thanks. I can now see the image on my private account. I'm en need of this on an pro account. Can we get this added to that account?

**Comment by IlyaFinkelshteyn** [comment]
Sure, what is account name? It part of AppVeyor URL after `/project/`.

**Comment by Crevil** [comment]
@IlyaFinkelshteyn `EGAppVeyor`. May I ask why this is not available as per default?

**Comment by IlyaFinkelshteyn** [comment]
Added. We are collecting feedback in [this](https://github.com/appveyor/ci/issues/1179) thread, to understand what people need to be installed on this image before making it GA.

**Comment by Crevil** [comment]
@IlyaFinkelshteyn Ahh, I see. Good Job! I'll leave some feedback over there. Thanks for the quick replies.!

**Comment by IlyaFinkelshteyn** [comment]
You are welcome :)  Please also note that currently this build is running on GCE (normally builds run on our own servers at RackSpace) therefore job start is longer. It will be available on our servers later.

**Comment by Crevil** [comment]
Got it. I just thought about it. Looking forward to fast builds as usual.

**Comment by jarroda** [comment]
@IlyaFinkelshteyn may I have access to the VS2017 image as well?  We are in need of building .net core 1.1 csproj based projects.  Account name is "2020IP".  Thanks.

**Comment by IlyaFinkelshteyn** [comment]
@jarroda Sure, done!

**Comment by JamieKeeling** [comment]
@IlyaFinkelshteyn May I have access to the VS2017 image too please?

My Account name is jamie-keeling

Many thanks.

**Comment by IlyaFinkelshteyn** [comment]
@JamieKeeling sure, done

**Comment by MichaelJolley** [comment]
@IlyaFinkelshteyn, I'd love access to it as well.  My account name is AdvancedSystemsUnlimited.

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@MichaelJolley added

**Comment by AndreyAkinshin** [comment]
Hey @IlyaFinkelshteyn, May I have access to the VS2017 image too? Account name: `PerfDotNet` (see https://github.com/dotnet/BenchmarkDotNet/pull/357).

**Comment by FeodorFitsner** [comment]
@AndreyAkinshin added.

**Comment by AndreyAkinshin** [comment]
@FeodorFitsner, thanks!

**Comment by neoeinstein** [comment]
@IlyaFinkelshteyn Requesting access for "neoeinstein" and the "xyncro" organization.

**Comment by IlyaFinkelshteyn** [comment]
@neoeinstein Added!

**Comment by enyim** [comment]
Can you please enable this for the account "enyim"?

**Comment by FeodorFitsner** [comment]
@enyim added.

**Comment by jakkaj** [comment]
Hi guys. Can I please get early access for "jakkaj" to the VS2017 RC image :)

Cheers!

Jordan.

**Comment by IlyaFinkelshteyn** [comment]
@jakkaj Sure, done!

**Comment by jlopresti** [comment]
Hi all,

Can i also get access to the preview ? My account is my current Github account

Thanks guyz !

J.

**Comment by IlyaFinkelshteyn** [comment]
@jlopresti Sure, added!

**Comment by ctolkien** [comment]
Any ETA on when the 2017 image will make it into general release?

**Comment by IlyaFinkelshteyn** [comment]
This week we are releasing new image with VS 2017 RTM and Win2016 with docker combined. By default it will be available to everyone who already have access to current VS 2017 RC or Win2016 and to everyone who asked. After first iteration of patches we will make it GA.

**Comment by ctolkien** [comment]
I'd better get on the preview train as well then! This GH account is linked to my AppVeyor account for org Soda Digital

**Comment by IlyaFinkelshteyn** [comment]
@ctolkien OK, done.

**Comment by ptoonen** [comment]
Can we get the VS2017 image too? Using account 'simondel'

**Comment by keslerm** [comment]
If possible could I also get in on the preview? this github account linked to org 'Park Assist' ?

**Comment by rsuter** [comment]
@IlyaFinkelshteyn hi, can you enable VS2017RC/RTM access for the users "rsuter" and "picturepark"? Thank you

**Comment by eamodio** [comment]
@IlyaFinkelshteyn please add me as well (my github is linked to my appveyor account)

**Comment by IlyaFinkelshteyn** [comment]
@ptoonen @keslerm @rsuter Added

**Comment by IlyaFinkelshteyn** [comment]
@eamodio It is account `ion-interactive`, right? Added

**Comment by scottbrady91** [comment]
Yes, please! (RockMan)

**Comment by leastprivilege** [comment]
@IlyaFinkelshteyn me too please

**Comment by IlyaFinkelshteyn** [comment]
@scottbrady91 added

**Comment by IlyaFinkelshteyn** [comment]
@leastprivilege You were added in [this](https://github.com/appveyor/ci/issues/1179 ) thread. It does not work for you?

**Comment by leastprivilege** [comment]
I think it did - but I only see "Visual Studio 2017 RC" - is that intentional.

I also have issues with this image around package restores.

**Comment by IlyaFinkelshteyn** [comment]
@leastprivilege `Visual Studio 2017 RTM` is getting ready now. It will be available in day or two.

What about your problem with package restore, could you please start separate GH issue or [support forum](http://help.appveyor.com) thread?

**Comment by thehoneymad** [comment]
Can I kindly have access to the Visual Studio 2017 compatible images. Failing to build https://ci.appveyor.com/project/thehoneymad/nerdcats-jsonschemadefaults

**Comment by FeodorFitsner** [comment]
@thehoneymad just use `Visual Studio 2017` image.

**Comment by HarelM** [comment]
When using VS2017 and .Net core tests are not automatically discovered and ran, can you please support this?
Also a post/support for coverage and javascript tests will be nice, I had everything working before the migration to .Net core but now I'm back to square one...

**Comment by IlyaFinkelshteyn** [comment]
@HarelM please watch this https://github.com/appveyor/ci/issues/1404 and this https://github.com/appveyor/ci/issues/226. `dotnet` one is high priority right now.

**Comment by HarelM** [comment]
Thanks for the quick response! I hope I can get everything working using powershell scripts until you provide better support.
Keep up the good work!
