### ISSUE TITLE
Azure SDK 2.9.6

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1182]
https://docs.microsoft.com/en-us/azure/app-service-web/azure-sdk-dotnet-release-notes-2-9

**Comment by JSkimming** [comment]
Has this slipped to from 27th Nov to 4th Dec? If so can you confirm it will be released on the 4th Dec?

FYI I've upgraded a Cloud Service Worker Role to OS Family 5, which requires this update, and until you release this I can't Continuously Deploy using AppVayor.

If you are definitely going to release this on 4th Dec, then I'll live with having to manually deploy the worker role for another week, if not, I'll downgrade to bring back Continuous Deployment.

**Comment by FeodorFitsner** [comment]
We'll do our best to deploy image update with Azure SDK 2.9.6 early this week.

Supporting Windows Server 2016 in Azure Cloud Services is great news!

**Comment by JSkimming** [comment]
Great thanks @FeodorFitsner much appreciated.

**Comment by FeodorFitsner** [comment]
@JSkimming we are still working on the rest of build worker images update, but Azure SDK 2.9.6 is already deployed to GCE environment (but not to Pro environment yet). If you are blocked you can run your builds on GCE, by adding this environment variable to `appveyor.yml`:

```
environment:
  APPVEYOR_BUILD_WORKER_CLOUD: gce
```

**Comment by JSkimming** [comment]
@FeodorFitsner Thanks, I'll probably be producing a build today, I'll configure it to use GCE until it is released to RackSpace, assuming that's where you still host the [majority of builds](https://www.appveyor.com/blog/2016/07/16/migration-to-rackspace/ "Migrating build environment to RackSpace").

**Comment by JSkimming** [comment]
@FeodorFitsner Just feeding back that our build is running and deploying fine when I use the GCE environment.

**Comment by FeodorFitsner** [comment]
@JSkimming Azure SDK 2.9.6 has been deployed to default build worker image.
