### ISSUE TITLE
APPVEYOR_REPO_TAG correct syntax

### ISSUE THREAD

**Issue by GandaG** [appveyor/ci#1185]
What is the correct syntax for checking if a tag has been set?

I tried `if "%APPVEYOR_TAG_REPO%"=="true" "%PYTHON%\\python.exe setup.py sdist bdist_wheel"` but it [clearly isn't working](https://ci.appveyor.com/project/GandaG/bethlib/build/30/job/4jx9r6vdlx73o7rk).

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
Variable name is APPVEYOR_**REPO_TAG**, not APPVEYOR_**TAG_REPO** :) Other than that check it the same way as you check other environment variables in Python...

**Comment by GandaG** [comment]
Well, I'm dumb <.< Thanks! :D
