### ISSUE TITLE
Java 9.0.4

### ISSUE THREAD

**Issue by garydgregory** [appveyor/ci#1186]
Can we get support for Java 9 Early Access releases?

**Comment by nicolaiparlog** [comment]
I'm in favor, one detail there are two EA releases: [the regular one](http://jdk9.java.net/) and [the more modular one](https://jdk9.java.net/jigsaw/)

**Comment by garydgregory** [comment]
For now, I'd be happy with the 'regular' one. But clearly both need to be supported until we are assimilated lock, stock and barrel into the module world, for good or bad.

**Comment by garydgregory** [comment]
And who do you do that with your hair?

**Comment by sormuras** [comment]
Can we get support for Java 9 GA release?

**Comment by sormuras** [comment]
Worked-around by placing a custom `.appveyor.yml` into JUnit 5 project root directory:
```
build: off

install:
  - cinst jdk9 -params 'installdir=C:\\jdk9'
  - SET JAVA_HOME=C:\jdk9
  - SET PATH=C:\jdk9\bin;%PATH%

test_script:
  - gradlew -version
  - gradlew build --stacktrace
```

**Comment by webfolderio** [comment]
Any release date?

**Comment by JamzTheMan** [comment]
That that Java 9 has been GA for a while, any date on when we'll get it added?

**Comment by FeodorFitsner** [comment]
Yeah, looks like it's time. We are going to leave Java 8 in PATH though.

**Comment by FeodorFitsner** [comment]
JDK 9.0.1 will be installed in the following location:

    C:\Program Files\Java\jdk9

JRE 9 location:

    C:\Program Files\Java\jre9

**Comment by JamzTheMan** [comment]
Thanks!

**Comment by sormuras** [comment]
Hope you took **9.0.4**.

http://www.oracle.com/technetwork/java/javase/documentation/9u-relnotes-3704429.html
