### ISSUE TITLE
Test Discovery Problems

### ISSUE THREAD

**Issue by kevinvangelder** [appveyor/ci#1187]
Not sure if it's because of the shared project structure or NUnit, or something else entirely, but I'm having problems where AppVeyor is only finding 70 of 120 tests.

Pull Request: https://github.com/ReactWindows/react-native-windows/pull/899
AppVeyor Build: https://ci.appveyor.com/project/rozele/react-native-windows/build/1.0.1260

**Comment by IlyaFinkelshteyn** [comment]
Hi Kevin,

I think not all test assemblies match [this mask](https://github.com/ReactWindows/react-native-windows/blob/master/appveyor.yml#L38). If I understand this correctly, `ReactNative.Tests.exe` is also test assembly, but it it `.exe`, not `.dll`.

Hope this helps.
Ilya.

**Comment by kevinvangelder** [comment]
@IlyaFinkelshteyn Thanks for the quick response. Yes, ReactNative.Tests.exe is not expected to run, it's a UWP project which I understand is not yet supported.

Looks like the tests in our shared project are not getting compiled into the DLL and therefore aren't discovered and run.

**Comment by IlyaFinkelshteyn** [comment]
OK, good. Note that you can [RDP to build worker](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) at right build stage and inspect manually what is being build and in what folders. 

--ilya.

**Comment by kevinvangelder** [comment]
Running the .dll through nunit3-console returns the expected results: `Test Count: 120, Passed: 116, Failed: 0, Inconclusive: 0, Skipped: 4`. We're re-running the AppVeyor build in hopes that something just glitched.

**Comment by kevinvangelder** [comment]
As is mentioned on the pull request, the problem seems to be that `git checkout FETCH_HEAD` isn't working on that particular AppVeyor instance.

@IlyaFinkelshteyn Would you like me to close this issue and start a new one or just continue to track it here with the new information?

**Comment by IlyaFinkelshteyn** [comment]
Yes, please. Thanks!
