### ISSUE TITLE
Can't get cargo dir to cache (Rust)

### ISSUE THREAD

**Issue by matthewkmayer** [appveyor/ci#1194]
I'm trying to get the cargo directory to cache [in rusoto](https://github.com/rusoto/rusoto/pull/427) but it's always downloading new files.  I'm not seeing anything in the build logs about caching or restoring.  Also not seeing anything related in github issues or the support forum.  Can I get pointed in the right direction for making this work?  Thanks.

**Comment by IlyaFinkelshteyn** [comment]
It seems this is because it is pull request. Sorry for confusion.

**Comment by matthewkmayer** [comment]
Then when the Rusoto PR gets merged into master, builds after that merge should start using the cache instead of downloading dependencies?

**Comment by IlyaFinkelshteyn** [comment]
Yes. You can also test it by creating your fork and separate AppVeyor project targeting your fork.

**Comment by matthewkmayer** [comment]
Confirmed it works after merging to master, thanks! 

<img width="624" alt="screen shot 2016-12-01 at 10 08 28 am" src="https://cloud.githubusercontent.com/assets/4998189/20806065/3dc95654-b7ae-11e6-9064-b61a28dc3479.png">
