### ISSUE TITLE
The 'Skip branches without appveyor.yml' flag is not working

### ISSUE THREAD

**Issue by AndreyBelym** [appveyor/ci#1195]
AppVeyor is ignoring the 'Skip branches without appveyor.yml' flag since November 29, 2016, e.g. https://ci.appveyor.com/project/AndreyBelym/github-build-bot/build/1.0.1. The repository and the specified branch don't have `appveyor.yml`, but AppVeyor tried to run the build.

**Comment by FeodorFitsner** [comment]
Thanks for the catch! Indeed, there is a regression. We'll fix and deploy update shortly.

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by mjsteinbaugh** [comment]
Hi @FeodorFitsner, the ignore branch option doesn't seem to be working for me currently. Is there something I need to add to the `appveyor.yml` file? I have it configured correctly on the AppVeyor website.

**Comment by FeodorFitsner** [comment]
You cannot configure anything in `appveyor.yml` as there should be no `appveyor.yml` in branch for it to be ignored.
