### ISSUE TITLE
"Build cloud 'rs-app8-e' does not support 'Visual Studio 2015 Update 2' image" despite granted access

### ISSUE THREAD

**Issue by inducer** [appveyor/ci#1196]
I recently applied for (and, apparently, was granted) access to the "Visual Studio 2015 Update 2" for the conda-forge account:

https://github.com/appveyor/ci/issues/891#issuecomment-263455110

Trying to use the image resulted in the message in the subject line:

https://ci.appveyor.com/project/conda-forge/pyopencl-feedstock/build/1.0.6/job/8atwln49bfmh4ni7/messages

How can I fix this? Thanks!

**Comment by FeodorFitsner** [comment]
It's been fixed now. Give it another try.

**Comment by inducer** [comment]
That did the trick, thank you!
