### ISSUE TITLE
"Build worker image not found: Visual Studio 2015 Update 2" despite having enabled

### ISSUE THREAD

**Issue by mwcraig** [appveyor/ci#1197]
Access to this old build image seems to have been dropped some time in the last day. If it is still available it would be great to get that access back; the last time I checked a few weeks ago a patch for the issue we had has still not been issued by microsoft. 

Thanks!

See #891 for original issue.

Ping @astrofrog @taldcroft @eteq -- astropy Windows builds will not pass until access is restored. Worst case we'll need to change the build image and mark a few tests as xfail on Windows.

**Comment by FeodorFitsner** [comment]
Can you drop me a link to project/build where you're getting the error?

**Comment by mwcraig** [comment]
Sorry, turns out the problem was that it was also building against my personal appveyor account, closing. Link is: https://ci.appveyor.com/project/mwcraig/astropy/build/1.0.83

Re-ping  @astrofrog @taldcroft @eteq -- disregard.

**Comment by pllim** [comment]
@mwcraig , I have the same problem trying to run Appveyor on a branch of my fork. Are you saying that such things are not possible?

https://ci.appveyor.com/project/pllim/astropy/build/job/4p493dk4vanewpkw/messages

**Comment by FeodorFitsner** [comment]
@pllim it should be added under your account by request.

**Comment by pllim** [comment]
@FeodorFitsner , how and where do I put in such a request? Is it free?

**Comment by FeodorFitsner** [comment]
Yes, it's free. What's your AppVeyor account name?

**Comment by pllim** [comment]
pllim

Thanks!

**Comment by FeodorFitsner** [comment]
@pllim added.
