### ISSUE TITLE
Build to be skipped is run

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#1198]
We set the switch on all conda-forge feedstocks so that AppVeyor should not build if `appveyor.yml` is not present. However, sometimes (albeit rarely) we end up seeing a build when we shouldn't. As an example, take this [build]( https://ci.appveyor.com/project/conda-forge/vigra-feedstock/build/1.0.1 ) triggered by this [commit]( https://github.com/conda-forge/vigra-feedstock/pull/13/commits/ece05a9f082e62dd957ef7af379f24cad4bf692c ).

**Comment by IlyaFinkelshteyn** [comment]
Yes, it was a regression yesterday. https://github.com/appveyor/ci/issues/1195. Should be fixed now. Sorry.

--ilya.

**Comment by jakirkham** [comment]
Ah, sorry to dup. Missed that one. Thanks for the fix. Will close this out.

**Comment by jakirkham** [comment]
Seeing this again in PR ( https://github.com/conda-forge/ase-feedstock/pull/20 ).

**Comment by jakirkham** [comment]
Any ideas on what is going on the example above @IlyaFinkelshteyn?

**Comment by IlyaFinkelshteyn** [comment]
@jakirkham you rely on `Skip branches without appveyor.yml` setting, right? But I do not see it is set for https://ci.appveyor.com/project/conda-forge/ase-feedstock/settings...

**Comment by jakirkham** [comment]
Interesting. It should be set. I’ll have to take a look. Thanks.

**Comment by jakirkham** [comment]
Thanks @IlyaFinkelshteyn. That fixed it. :)
