### ISSUE TITLE
UWP packaging in x86 and x64 architecture not supported.

### ISSUE THREAD

**Issue by theweavrs** [appveyor/ci#1201]
When I try to add x86 and x64 to my `appveyor.yml` it gives an error while building, only ARM works. Are x86 and x64 CPU architectures supported?

**Comment by matthargett** [comment]
We're using AppVeyor for UWP builds in react-native-windows. What are you trying to do? Feel free to check out our appveyor.yml .

**Comment by IlyaFinkelshteyn** [comment]
Let me please repeat after Matt -- please share your appveyor.yml. Use Export YAML menu if you use UI. Link to failed build will be helpful too.

**Comment by theweavrs** [comment]
@matthargett @IlyaFinkelshteyn It is working wonderfully now. I changed some lines in `appveyor.yml` and it worked! Thanks a lot, guys!
