### ISSUE TITLE
Build fails with "Environment variable name or value is too long"

### ISSUE THREAD

**Issue by thomaslevesque** [appveyor/ci#1202]
The build for [FakeItEasy](https://github.com/FakeItEasy/FakeItEasy) was working fine until today, but now it fails with this error:

> Build started
> Environment variable name or value is too long.

(see the build here: https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/62)

We didn't make any change to appveyor.yml recently.

In the appveyor.yml, we have this:

```yaml
 environment:
    PATH: 'C:\Ruby200\bin;%PATH%'
```

If I remove the PATH variable and do this instead:

```yaml
install:
    - cmd: set PATH=C:\Ruby200\bin;%PATH%
```

Then it works again...

So:

- did something change today in the PATH env variable that made it exceed the limit?
- is this limit introduced by Appveyor itself? I assume it is, since setting the variable with cmd works

/cc @adamralph @blairconrad

**Comment by FeodorFitsner** [comment]
Will take a look. Thanks for reporting that. Might be a regression from [yesterday's update](https://www.appveyor.com/updates/2016/12/01/).

**Comment by thomaslevesque** [comment]
> is this limit introduced by Appveyor itself? I assume it is, since setting the variable with cmd works

Actually I'm not so sure about this now. I think PATH is truncated when I use my workaround, because if I set it to `%PATH%;C:\Ruby200\bin` instead of `C:\Ruby200\bin;%PATH%`, the build fails the same way as if `C:\Ruby200\bin` wasn't in the path at all.

**Comment by blairconrad** [comment]
I thought I'd commented last night, but I've confirmed that [rolling back to the previous os does fix the problem](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/63-mpaojtut).

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by thomaslevesque** [comment]
Thanks @FeodorFitsner!

**Comment by janisozaur** [comment]
It looks like VS2017RC image is affected by this too.

See: https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.0.5.6210/job/kv901rq6psji2uoc

**Comment by FeodorFitsner** [comment]
VS 2017 image has been fixed, thanks for the catch!
