### ISSUE TITLE
Python builds started failing November 21-23

### ISSUE THREAD

**Issue by nedbat** [appveyor/ci#1203]
I guess there's something I have to adjust in my build scripts: https://ci.appveyor.com/project/nedbat/coveragepy/history  Any clues would be appreciated. Thanks.

**Comment by FeodorFitsner** [comment]
I first thought that it might be something in [Nov 23](https://www.appveyor.com/updates/2016/11/23/) update that broke your builds. There was PIP update for all pre-installed Pythons and all latest Windows updates installed. But, apparently, your builds do not rely on pre-installed Python and Python is downloaded/installed during the build. Then I took only one configuration `2.7 32-bit` and ran it on [Nov 1](https://www.appveyor.com/updates/2016/11/01/) image (the one *before* "previous") and it error-ed too. Thus I think it's not a build worker image, but maybe some external dependency or code change broke your builds.

**Comment by nedbat** [comment]
OK, thanks, I'll try rolling back some versions.

**Comment by FeodorFitsner** [comment]
Right, re-building [last successful build](https://ci.appveyor.com/project/nedbat/coveragepy/build/default-421/job/6k35mj8gli8hp9s2) worked: https://ci.appveyor.com/project/FeodorFitsner/coverage-py/build/1.0.7

**Comment by nedbat** [comment]
@FeodorFitsner looks like i happened to choose a bad setuptools: both older and newer work better.  But also, pytest-xdist is sharing some files, and I need to figure out what to do about that.  Thanks for looking into it.
