### ISSUE TITLE
git checkout FETCH_HEAD Fails

### ISSUE THREAD

**Issue by kevinvangelder** [appveyor/ci#1207]
https://ci.appveyor.com/project/rozele/react-native-windows/build/1.0.1336#L7

As you can see, this `git checkout FETCH_HEAD` fails, despite the fact that the previous command (`git fetch -q origin +refs/pull/899/merge:`) should set the `FETCH_HEAD`. This works when I manually tested the workflow locally (note, I didn't use the `-q` flag, so the output is more verbose):
```
$ git fetch origin +refs/pull/899/merge:
remote: Counting objects: 55, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 55 (delta 33), reused 32 (delta 32), pack-reused 16
Unpacking objects: 100% (55/55), done.
From github.com:reactwindows/react-native-windows
 * branch            refs/pull/899/merge -> FETCH_HEAD
$ git checkout FETCH_HEAD
Note: checking out 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5c4afc8... Merge 0a031abeff3f82267841c2b9619cebc0bc5f3ae4 into 0d02861c619bf6b977444f46eee45df7ebcbbf1d
```

**Comment by kevinvangelder** [comment]
Pull request in question: https://github.com/ReactWindows/react-native-windows/pull/899
Previous issue for reference: https://github.com/appveyor/ci/issues/1187

**Comment by IlyaFinkelshteyn** [comment]
I created hello word repro, and it seems that `git fetch origin +refs/pull/" + $Env:APPVEYOR_PULL_REQUEST_NUMBER + "/merge:` does not work properly, because even with `-q` removed I see no actual output.

**Comment by IlyaFinkelshteyn** [comment]
This is what finally works for me. I do not know what is specific problem with PowerShell script though.

```
clone_script:
- git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- IF [%APPVEYOR_PULL_REQUEST_NUMBER%] == [] git checkout %APPVEYOR_REPO_COMMIT%
- IF NOT [%APPVEYOR_PULL_REQUEST_NUMBER%] == [] echo it is pool request!
- IF NOT [%APPVEYOR_PULL_REQUEST_NUMBER%] == [] git fetch origin +refs/pull/%APPVEYOR_PULL_REQUEST_NUMBER%/merge
- IF NOT [%APPVEYOR_PULL_REQUEST_NUMBER%] == [] git checkout FETCH_HEAD
- git submodule update -q --init --recursive
```

Note that `-qf` removed just for debugging purposes. 

--ilya.

**Comment by kevinvangelder** [comment]
Is it the trailing ':' that was tripping it up?

**Comment by IlyaFinkelshteyn** [comment]
I hoped so, because with it cmd version did not work, but removing it in PowerShell version did not helped me. Do you have a local repro to check my sanity?

**Comment by kevinvangelder** [comment]
This looks promising. For testing purposes I manually add the correct remote, manually fetch the pull request, and manually checkout `FETCH_HEAD`. The only effective difference here is that I added `-f` or force flag to the fetch command. It didn't error in the git section so now I'm waiting to see if it runs all 112 tests.

**Comment by kevinvangelder** [comment]
@IlyaFinkelshteyn As you can see, this build was able to fetch and checkout when I did them as separate statements: https://ci.appveyor.com/project/kevinvangelder/react-native-windows/build/1.0.13

But we're still getting the same failure when they're two statements in the else: https://ci.appveyor.com/project/rozele/react-native-windows/build/1.0.1342

**Comment by IlyaFinkelshteyn** [comment]
Yes, I went similar road and decided to try straightforward cmd because of this behavior.

**Comment by IlyaFinkelshteyn** [comment]
I just want to say that separate statement instead of script block are better anyway, because you don't have to check `errorlevel`/`lastexitcode` on every step, as separate statement will just throw and fail build right away. I understand that repeating `IF`s looks silly but in this specific situation is is more practical.

**Comment by kevinvangelder** [comment]
Resolved by: https://github.com/ReactWindows/react-native-windows/pull/899#issuecomment-265834307
