### ISSUE TITLE
Encryped data fails in pull request builds

### ISSUE THREAD

**Issue by ceddlyburge** [appveyor/ci#1211]
The build here (based on a pull request), failed because the Encryped data was not available.

https://ci.appveyor.com/project/ceddlyburge/canoepololeagueorganiser/build/1.0.95

When I merge in the request, the build succeeds without problems

I imagine that this is done so that the person making the pull request can see the output and fix up any problems, and thus the encrypted data can't bo shown.

However, it does mean that I can't check whether the build will work or not.

Is there are way round this?

It seems like it would be possible to use the encrypted data, but not show it on the output.

Cheers

Cedd

**Comment by IlyaFinkelshteyn** [comment]
Hi Cedd,

Right, another customer already proposed this and we filed [this issue](https://github.com/appveyor/ci/issues/1169). However this can be good as measure against unintended secrets exposure, but this does not prevent people from say uploading them to some location over HTTP or FTP or send by e email with some SMTP API calls... 

For now you can use **Enable secure variables in Pull Requests from the same repository only** in **Settings > General** tab in UI to allow use secure variables for trusted users. 

For private repositories you can enable secure variables for everyone, as you control repository access at version control system level.

Thanks!
Ilya.

**Comment by FeodorFitsner** [comment]
Another option (for GitHub at least) could be maintaining the list of "trusted" GitHub usernames on project settings page. Would that work? Do you see any security pitfalls here?

**Comment by ceddlyburge** [comment]
Sorry both, I did look for similar issues but didn't find anything.

It's a good point that they could just send themselves an email with the
secret in, I hadn't thought of that.

A list of trusted usernames does seem like it would work.

I think usually a pull request wouldn't need to be doing anything with the
secure variables, so potentially there could be an option for the owner of
the github repository to build the pull request in their own account before
merging. If there were any problems they could be added as comments to the
PR.

Maybe another thing would be to specify which bits of thegi build might
fail due to encryption, and return  special status code for those that
didn't fail pull request builds.

Anyway, its not a huge deal, I was just wondering what the usual process
was.

Cheers

Cedd

**Comment by Rondom** [comment]
(Besides a whitelist) Jenkins uses an approach where a project member has to to "verify" the PR before it is built by posting a comment with the word verify. See https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/2480
