### ISSUE TITLE
VS2017 RC support?

### ISSUE THREAD

**Issue by ifarbod** [appveyor/ci#1213]
As we know VS2017 RC is out, I would like to know if AppVeyor will support it or not.
I have tried `image: Visual Studio 2017 RC` already and it seems to fail:

```Build worker image not found: Visual Studio 2017 RC```

Does AppVeyor have any plans on supporting it?

**Comment by IlyaFinkelshteyn** [comment]
It is in a "private beta". Could you please request it here https://github.com/appveyor/ci/issues/1179#issuecomment-264055820 :)

Thanks!

**Comment by ifarbod** [comment]
Already did, Thanks.
