### ISSUE TITLE
Project build number sometimes stuck

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#122]
https://github.com/JuliaLang/julia/issues/9899#issuecomment-71250294

**Comment by jslee02** [comment]
We had similar issue. Project build number stuck from [build #1302](https://ci.appveyor.com/project/jslee02/dart/build/1302) up to several commits.

**Comment by FeodorFitsner** [comment]
Open General tab of project settings and increment build number.

**Comment by jslee02** [comment]
Thanks! That could be a solution. I could increase the build number in different way; [changing version format](https://github.com/dartsim/dart/commit/2775460febea87e14fb5b5ad5b34c0d3c6bf4dac).

I'm waiting for a [queued build](https://ci.appveyor.com/project/jslee02/dart/build/1307-1).

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/986
