### ISSUE TITLE
Miniconda2 4.2.12 (Python 2.7.12 x86/x64), Miniconda3 4.2.12 (Python 3.5.2 x86/x64)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1222]
Discussion: http://help.appveyor.com/discussions/suggestions/1154-update-miniconda-in-the-base-image

**Comment by speth** [comment]
@FeodorFitsner: The installation in `c:\miniconda-x64` seems to be broken now, and no longer contains `conda.exe` (among other things) in the `Scripts` subdirectory -- compare to the 32-bit installation in `c:\miniconda`.

Build log with directory listings for `c:\miniconda-x64\Scripts` and `c:\miniconda\Scripts`:
https://ci.appveyor.com/project/Cantera/conda-recipes/build/job/4rx2pxfcg32f6pvq

**Comment by FeodorFitsner** [comment]
Thanks for the catch. Will fix that and deploy an updated image shortly.

**Comment by FeodorFitsner** [comment]
It's been fixed and image updated.
