### ISSUE TITLE
NuGet provider for PowerShellGet module, enabled PSGallery

### ISSUE THREAD

**Issue by Paebbels** [appveyor/ci#1226]
I get the error message: "NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of NuGet provider is installed.". According to the AppVeyor documentation, the NuGet version is newer than 2.8.5 (2.8.6 or 3.4.x). So what's going wrong here?

The command is: `Install-Module -Name Pscx`.
PSCX is provided by PowerShellGallery.

So my questions are:
* Why is it not possible to install modules from PowerShellGallery?
* Any other recommendation on how to install Pscx 3.2.2?
* Why is Pscx not installed by default? It's a very common add-on.

I'm using the "WMF 5" image.
My slug is: "paebbels/ghdl".

The full error message is:
```
Exception calling "ShouldContinue" with "2" argument(s): "The method or operation is not implemented."
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7281 char:8
+     if($Force -or $psCmdlet.ShouldContinue($shouldContinueQueryMessag ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException
 
Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of NuGet provider is installed.
At C:\projects\ghdl\dist\appveyor\install.ps1:19 char:1
+ Install-Module -Name Pscx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module
```

---------------------
Related issues:
* Pscx/Pscx#18

**Comment by FeodorFitsner** [comment]
I think PS module installer requires its own "internal" NuGet. Have you tried running it with `-Force`?

    Install-Module -Name Pscx -Force

**Comment by Paebbels** [comment]
As reported by @rkeithhill, his solves the problem:

```PowerShell
Install-PackageProvider NuGet -Force
Import-PackageProvider NuGet -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
```

This adds NuGet as a package provider and registers PowerShellGallery as a trusted source. So the question remains, if NuGet and PSGallery should be registered/trusted by default? I think it's a very common source for additional needed PowerShell scripts. I'm using Pscx to get a `Write-Zip`, `Write-Tar` CmdLet so I can package my builds in archive files.

After that, PSCX can be installed with this command:

```PowerShell
Install-Module Pscx -AllowClobber
```

**Comment by FeodorFitsner** [comment]
Yes, that makes sense. Will take a look if this can be installed as part of base build image.

**Comment by capg-naveen-kumar** [comment]
Helped a lot thanks
