### ISSUE TITLE
Node.js 0.6.21

### ISSUE THREAD

**Issue by ljharb** [appveyor/ci#1232]
build: https://ci.appveyor.com/project/ljharb/node-resolve-0clfj/build/1.0.9/job/wi4pyscrjsm4xems

0.6 should work :-)

Download location: https://nodejs.org/dist/v0.6.21/

Update script:

```posh
Write-Host "Installing Node 0.6.21 ..." -ForegroundColor Cyan

New-Item C:\avvm\node\0.6.21\x64 -ItemType Directory -Force | Out-Null
New-Item C:\avvm\node\0.6.21\x86 -ItemType Directory -Force | Out-Null

$zipPath = "$env:TEMP\node-0.6.21-x64.7z"
(New-Object Net.WebClient).DownloadFile('http://av1southus4workers.blob.core.windows.net/downloads/avvm/node-0.6.21-x64.7z', $zipPath)
7z x $zipPath -oC:\avvm\node\0.6.21\x64 | Out-Null
del $zipPath

$zipPath = "$env:TEMP\node-0.6.21-x86.7z"
(New-Object Net.WebClient).DownloadFile('http://av1southus4workers.blob.core.windows.net/downloads/avvm/node-0.6.21-x86.7z', $zipPath)
7z x $zipPath -oC:\avvm\node\0.6.21\x86 | Out-Null
del $zipPath

Write-Host "Node installed" -ForegroundColor Green
```

**Comment by XhmikosR** [comment]
Why on earth would one need 0.6? It's almost 2017.

**Comment by ljharb** [comment]
Because I'm maintaining a project that has support for it, and I want to fix tests on windows without having to make a breaking change.

Some companies still use 0.4 in production; something being old is a reason that testing services *must* support it, not a reason they shouldn't. New stuff is easy to test, especially locally - old stuff is what's hard.

**Comment by XhmikosR** [comment]
Well, those companies should no longer exist.

Node.js is a fast growing project and people need to follow the LTS release cycle. It's bad for security, performance, compatibility, everything.

**Comment by ljharb** [comment]
Projects that provide a clear upgrade path by supporting old platforms and new ones simultaneous are what makes it *easy* for those companies to upgrade.

The best way to get people to upgrade a language or platform version is for the modules/packages/gems/etc you publish to support the oldest ones possible *up to* the newest ones.

**Comment by ljharb** [comment]
@XhmikosR at any rate, if you don't want to support old nodes, great, don't! That's no excuse to troll here and try to prevent me from doing so.

**Comment by XhmikosR** [comment]
It's not trolling. It's a series of facts you are deliberately ignoring and actually doing a bad thing to your users.

Sure, if you run a business you weight things differently, but still, this is the same reason why big companies mess up.

Anyway, @FeodorFitsner will decide of course, but if no one else has requested this, this should be completely ignored due to the aforementioned reasons.

**Comment by FeodorFitsner** [comment]
@ljharb have you tried installing Node.js 0.6 with this command: https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs

**Comment by ljharb** [comment]
@FeodorFitsner if you click through to the build I linked, you'll see it runs `Install-Product node $env:nodejs_version $env:platform` - is that not sufficient to install the latest version of whatever partial semver string i've provided in appveyor.yml? For example, when I say `7`, that should always be the latest node 7 (i can't conceive of why anyone would want any other behavior)

**Comment by ljharb** [comment]
If you're saying that all my commands should be using `Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version $env:platform)` then I can certainly update those (but i'm not sure why that wouldn't be the default behavior)

**Comment by FeodorFitsner** [comment]
`Install-Product` cmdlet is faster as it switches nodes pre-installed on build worker. If specified node version is not found on build worker then the command fails.

`Update-NodeJsInstallation` downloads Node.js MSI from Node.js website and installs the selected version, however it's slower. You can use `if` to run `Update-NodeJsInstallation` for 0.6 version only:

    if ($env:nodejs_version -eq '0.6') { Update-NodeJsInstallation ... } else { Install-Product ... }

**Comment by ljharb** [comment]
I'd prefer accurate over fast, so I'll just do that for every version - thanks! (i'll want 7.3.0 installed the very instant it's released, for example, just like travis).

I'll close this now, but I'd really recommend that you set `Install-Product` to fall back to `Update-NodeJsInstallation` automatically when the version isn't preinstalled - that seems much more useful.

**Comment by FeodorFitsner** [comment]
Well, looks like node archive name patter was changed from 0.6 to 0.8. Frankly, we've never tested that function with 0.6, only with 0.8 and above. I was hoping it work for 0.6, but I was wrong.

**Comment by ljharb** [comment]
Any update?

**Comment by FeodorFitsner** [comment]
Sorry for the delay. Will make it available this week.

**Comment by ljharb** [comment]
@FeodorFitsner yay! What do I need to do now to get 0.6 working? Anything different than 0.8?

**Comment by FeodorFitsner** [comment]
Nope, use the same `Install-Product` cmdlet.

**Comment by ljharb** [comment]
@FeodorFitsner so, there's a wrinkle - https://ci.appveyor.com/project/ljharb/json-file-plus/build/1.0.22/job/i0hy4lrnobbq8kod - basically, when you install 0.6.21, it self-reports as `0.6.21-pre`, and that seems to be breaking appveyor.

**Comment by FeodorFitsner** [comment]
Remove `Update-NodeJsInstallation` - it's not needed anymore.

**Comment by ljharb** [comment]
thanks, trying that now :-)

**Comment by ljharb** [comment]
Thanks, that fixed the node issue - https://ci.appveyor.com/project/ljharb/json-file-plus/build/1.0.23/job/04yp7c6f78u4a0kl - there's still an issue with `npm` not having the right SSL certs, but I'm not sure the best way to fix that.
