### ISSUE TITLE
"queued" color should not be green

### ISSUE THREAD

**Issue by ljharb** [appveyor/ci#1233]
For a full half second when I first go to a build page, the queued builds look solid green - before they fade to grey.

The only builds that should ever show green are passing ones - it's very confusing to see the same color, and for the only disambiguation to be if I happen to be watching when the animation kicks in. Could you pick another color for "queued"?

**Comment by FeodorFitsner** [comment]
Can you drop a screenshot of that?

**Comment by ljharb** [comment]
lol ok so i took the screenshots, but it turns out that since i'm using `f.lux`, and it drops the blue out of my screen, that the blue looks like the same green as the green. When I disable `f.lux`, the queued ones look blue.

<img width="1067" alt="screen shot 2016-12-20 at 11 59 35 pm" src="https://cloud.githubusercontent.com/assets/45469/21381493/85d335ca-c710-11e6-9f0d-750415e9a618.png">
<img width="1098" alt="screen shot 2016-12-20 at 11 59 31 pm" src="https://cloud.githubusercontent.com/assets/45469/21381494/85ef5df4-c710-11e6-8afc-dd21b9d050e6.png">

The only way I could think of to fix it is if there were an additional non-color-based cue that they were different - like diagonal stripes, or something - which might be good for color-blind folks too.

However, since it's clearly a problem on my end, I'll close this for now.
