### ISSUE TITLE
NuGet artifact publish fails - SemVer 2.0

### ISSUE THREAD

**Issue by onovotny** [appveyor/ci#1235]
If you try to use SemVer 2.0 on nuget packages, AppVeyor seems to have trouble adding them to its local feed:

https://ci.appveyor.com/project/dotnetfoundation/rx-net-la3iv/build/4.0.0-dev.36.build.98/messages

Might need a newer version of the NuGet libraries that the feed uses to parse/host?

**Comment by FeodorFitsner** [comment]
New NuGet package parser is in works.

**Comment by FeodorFitsner** [comment]
Closed in favor of this duplicate: https://github.com/appveyor/ci/issues/1139
