### ISSUE TITLE
Add a "checksum integrity verifier" to build workers

### ISSUE THREAD

**Issue by claudioandre** [appveyor/ci#1246]
It is just an idea/suggestion.

Would be interesting if appveyor offers a default/pre-installed tool to compute a hash of an artifact. 
* think about a new `appveyor ComputeHash FILENAME` routine. 

Any routine that calculates and verifies SHA-2 hashes are good enough. A SHA256 message digest (equivalent to sha256sum) could be an easy to implement first choice.

PS: it is a non essential but nice to have request. Feel free to close it.

Thank you.

**Comment by gep13** [comment]
@claudioandre PowerShell has a built in function `Get-FileHash` cmdlet that I think could suit your needs:

![image](https://cloud.githubusercontent.com/assets/1271146/21595773/7bbdaf16-d129-11e6-9645-d8659d8e0dab.png)

**Comment by claudioandre** [comment]
Yes, it does. Well, everything google offered me was too old or too new to expect inside a CI.

PowerShell 4.0 is reasonable target. I'll test it inside appveyor.

**Comment by gep13** [comment]
>@claudioandre said...
PowerShell 4.0 is reasonable target.

Agreed.

Another suggestion would be:

`choco install checksum`

https://chocolatey.org/packages/checksum

**Comment by claudioandre** [comment]
:+1:
