### ISSUE TITLE
Outdated Geckodriver and Firefox Version

### ISSUE THREAD

**Issue by jrbenny35** [appveyor/ci#1250]
Hello, the current geckodriver version as well as the Firefox version is outdated. The current version is 50 for firefox and 0.12 for geckodriver, and since Firefox version 47 there have been some significant changes to both firefox and geckodriver.

**Comment by IlyaFinkelshteyn** [comment]
Hi Benjamin,

As **temporary** workaround, please add the following script at `install stage`

```
Write-Host "Installing FireFox Selenium driver..." -ForegroundColor Cyan

$destPath = 'C:\Tools\WebDriver'

if(-not (Test-Path $destPath)) {
    New-Item $destPath -ItemType directory -Force | Out-Null
}

$zipPath = "$env:USERPROFILE\geckodriver-v0.12.0-win32.zip"
(New-Object Net.WebClient).DownloadFile('https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-win32.zip', $zipPath)
7z x $zipPath -o"$destPath" -aoa
del $zipPath

copy "$destPath\geckodriver.exe" "$destPath\wires.exe"

Add-Path $destPath

Write-Host "Installed FireFox Selenium driver" -ForegroundColor Green
```

Thanks!
Ilya.

**Comment by jrbenny35** [comment]
Heh, I actually wrote something like this, albeit, FAR less attractive. Thanks for the solution!
