### ISSUE TITLE
GitVersion causes "(500) Internal Server Error" when used on Pull Request

### ISSUE THREAD

**Issue by trailmax** [appveyor/ci#1252]
I'm using GitVersion to set AppVeyor version. It works fine, until I get a pull request and then I get 500 error when attempting to push the version to AppVeyor. I'm trying to decide which system is at fault here.

Please see [this build log](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/51-cendkfse#L311). This is caused by executing PUT request to AppVeyor "api/build" with contents of `{ "version": "1.3.1-PullRequest.13+3.build.51"}`. 

See [this chunk of code](https://github.com/GitTools/GitVersion/blob/v3.6.4/src/GitVersionCore/BuildServers/AppVeyor.cs#L24) from GitVersion for reference. This seems to work fine on [my branches with similar semver](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/1.5.1-BuildImprovement.1+3.build.73#L201)

But something about pull requests not liked by the API. 

Judging by the url of the build log, could it be that the build number is not just "51", but "51-cendkfse"? and this will make the PUT request to send `{ "version": "1.3.1-PullRequest.13+3.build.51-cendkfse"}` which I don't think is a valid semantic version with two dashes? (pure guesswork here)

**Comment by FeodorFitsner** [comment]
On of the reasons you get 500 while updating build version via Build Worker API is that another build with the same version already exists.

**Comment by trailmax** [comment]
Just looked through the list of builds - that is indeed the case ([1](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/1.3.1-PullRequest.13+3.build.51), [2](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/51-ytufdivg), [3](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/51-cendkfse))! 

But why is build number 51 been reused four times? ([fourth](https://ci.appveyor.com/project/trailmax/cake-sqlserver/build/1.3.1+3.build.51) when the Pull Request been accepted). Is there a special numbering for PRs?

**Comment by IlyaFinkelshteyn** [comment]
Maybe you have **Pull Requests do not increment build number** in **Settings** > **General**?

**Comment by trailmax** [comment]
@IlyaFinkelshteyn that was it - I have not realised this was possible. Ilya, Feodor, thank you for your help and time - much obliged.
