### ISSUE TITLE
docfx and appveyor

### ISSUE THREAD

**Issue by richardschneider** [appveyor/ci#1253]
I'm trying to get [docfx](https://github.com/dotnet/docfx), an API documentation generator, to work on appveyor; see https://github.com/dotnet/docfx/issues/1078.

Basically the docfx team believes its an issue with the appveyor environment and Roslyn.  Hopefully, you can come to rescue!!!

The build error is at  https://ci.appveyor.com/project/richardschneider/net-ipfs-core/build/0.5.2-ci.9.build.178#L29.  The entire project is at https://github.com/richardschneider/net-ipfs-core

I've already modified dotfx to cope with a [git detached head](https://github.com/dotnet/docfx/pull/1098).  So that's not an issue any longer.

BTW, appveyor is awesome!!!

**Comment by IlyaFinkelshteyn** [comment]
Hi Richard, thank you :)

We tried several (pretty random) workaround but was not able to fix it at least quickly. Could you please do the following:
 
-  Add [RDP blocking statement](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/)  at `install` stage
- After you connect to RDP, you will find your code in `C:\projects\net-ipfs-core`
- Try to do all steps manually, as you do on your computer

Please let us know if it works with manual steps in RDP or fail the same way?

--ilya.

**Comment by richardschneider** [comment]
@IlyaFinkelshteyn thanks for looking into it.  I'll leave it to docfx team.

**Comment by richardschneider** [comment]
The docfx team, in particular @vicancy, solved the issue, see https://github.com/richardschneider/net-ipfs-core/pull/25

After testing various changes in `appyevor.yml`, it looks like `platform: Any CPU` is the cause of all of the problems.  

Can you provide any insights?

**Comment by IlyaFinkelshteyn** [comment]
Maybe it is somehow connected to the historical inconsistency - `AnyCpu` in .csproj vs `Any CPU` in .sln files?
