### ISSUE TITLE
appveyor can reuse builds for known sha1

### ISSUE THREAD

**Issue by vors** [appveyor/ci#126]
I just updated master branch and created a new tag and it kicks-off 2 redundant builds.

![image](https://cloud.githubusercontent.com/assets/816680/5915622/c5684d28-a5bc-11e4-9270-5a14ab490f03.png)

**Comment by FeodorFitsner** [comment]
Well, check project webhook "Recent deliveries" on GitHub. There are should be corresponding "push" events. AppVeyor kicks off a new build on all "push" and "pull_request" (open and synchronize actions) events unless you have branch filter set for the project.

**Comment by vors** [comment]
I see. Feel free to close this issue.
