### ISSUE TITLE
Builds queued on pywin32

### ISSUE THREAD

**Issue by xoviat** [appveyor/ci#1263]
See https://ci.appveyor.com/project/pywin32/pypiwin32/history. The builds appear to be stuck.

**Comment by FeodorFitsner** [comment]
There was AppVeyor outage: https://appveyor.statuspage.io

Please re-start the build.

**Comment by xoviat** [comment]
@FeodorFitsner 

I have resolved this issue, but just to let you know, I actually had to remove and re-add the entire project in order to resume the builds. Simply restarting the builds would not work.

**Comment by FeodorFitsner** [comment]
OK, got it.
