### ISSUE TITLE
Add WiX toolset to PATH

### ISSUE THREAD

**Issue by NoahAndrews** [appveyor/ci#1267]
Right now, I have to hardcode the full path to WiX in my build script, which will change every time there is a new minor release of WiX. The bin folder of the WiX toolset should be in the PATH, so that I don't have to deal with it, and so that my build doesn't break every time Appveyor updates their version of WiX.

**Comment by XhmikosR** [comment]
You shouldn't need to do that because there must be an environment variable for WIX. Not sure what AppVeyor does exactly but you can try using the `WIX` environment variable.

On my dev VM I get:

```
C:\Users\xmr\Desktop>echo %WIX%
C:\Program Files (x86)\WiX Toolset v3.10\
```

**Comment by NoahAndrews** [comment]
Ah, thanks!
