### ISSUE TITLE
appveyor.yml undefined variable rendering

### ISSUE THREAD

**Issue by edenhill** [appveyor/ci#1268]
It would be great if undefined variables in appveyor.yaml would render as empty strings rather than their variable token.

Take this example S3 deployment folder which is configured to include the git tag (if any):
` folder: appveyor-windows-$(platform)-$(configuration)-tag_$(APPVEYOR_REPO_TAG_NAME)-$(APPVEYOR_REPO_COMMIT)-$(APPVEYOR_BUILD_ID)`

If there was no tag this renders as:
`appveyor-windows-x64-Debug-tag_$(APPVEYOR_REPO_TAG_NAME)-acb77e470517eea5bd6e32f3b055c9661284cddb-6565065`

which is highly impractical for tooling using these build artifacts.

It would be better if the result was this:
`appveyor-windows-x64-Debug-tag_-acb77e470517eea5bd6e32f3b055c9661284cddb-6565065`

Which is more in line with how variable substitutions work generally.

**Comment by IlyaFinkelshteyn** [comment]
Hi Magnus,

We considered it, but we decided that for many people it would be more natural the way it is now. We assume that we should behave the same way CMD behaves, where if you type `echo %non_existing_var%` you will get `%non_existing_var%` and not enpty string. Maybe we were wrong.

Anyway PowerShell behave more as you expect so you can use it to filter those variables out, with adding this statement before deployment:
```
- ps: $env:deploy_folder = "appveyor-windows-$env:platform-$env:configuration-tag_$env:APPVEYOR_REPO_TAG_NAME-$env:APPVEYOR_REPO_COMMIT-$env:APPVEYOR_BUILD_ID"
```
and the use this for S3 deployment settings:
```
folder: $(deploy_folder)
```

Thank you,
Ilya.

**Comment by edenhill** [comment]
Thanks for the explanation and workaround, @IlyaFinkelshteyn
