### ISSUE TITLE
New Projects don't require GH-User to be Admin/Collaborator

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#127]
Currently, when adding a new repo, the authenticated GitHub user needs to be an Admin/Collaborator of that repo.

Maybe change it so the code checks to see if the SSH key is provided. If not, show message and stop, else continue (because key exists).

**Comment by PureKrome** [comment]
Reference: http://help.appveyor.com/discussions/problems/1438-trying-to-add-a-new-project-error-adding-ssh-key-to-github-repository.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
