### ISSUE TITLE
Azure Blob Storage Headers and Content Types

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1270]
[Initial suggestion] http://help.appveyor.com/discussions/suggestions/1183-azure-blob-storage-headers

  - We noticed there’s no way to set custom headers on the files when they’re uploaded to Blob Storage. For example, we’d like to be able to set Cache Control headers for our static content.

  - Perhaps more significantly, we noticed that also we have “Set blobs Content Type based on file extensions” ticked in the Environment settings, we noticed that woff2 fonts do not have their Content Type set correctly. For example, files with the ‘woff2’ extension should have ‘application/font-woff2’ as their Content Type but at the moment they seem to be ‘application/octet-stream’.

**Comment by michaelchart** [comment]
We're experiencing this same issue with woff2 fonts having the wrong mime type. Is there any update as to when this woff2 issue is going to be fixed?

**Comment by roklenardicestable** [comment]
+1 from our side as well. Without setting cache and compression Azure Static Website storage is not useful for production sites.

**Comment by FeodorFitsner** [comment]
Setting headers is one thing, but regarding compression - could it be better to compress each file during the build (with your favourite tool) rather than doing that in the provider?

**Comment by roklenardicestable** [comment]
Yes, compressing files during the build is an acceptable solution, but for some reason, Azure Static Web pages only serves gzip files if they keep their original names, e.g. .js, are zipped and have compression header set correctly. AWS S3 is smarter than that and can serve .js or .gzip file according to request headers, Azure doesn't know how to do that.

**Comment by FeodorFitsner** [comment]
It's been implemented: https://www.appveyor.com/docs/deployment/azure-blob/
