### ISSUE TITLE
Intel Parallel Studio

### ISSUE THREAD

**Issue by mancoast** [appveyor/ci#1276]
Greetings,

Mandelbulber project requests Intel Parallel Studio for k1om Build-Packages.
We request "private build cloud" feature for azure.
We need guidance from the administrators of Appveyor.
We need our implementation to remain free.

Please assist Engineering our specific use case scenario.
REFERENCE:
https://github.com/buddhi1980/mandelbulber2/issues/155

Looking forward to a happy dialogue!

**Comment by mancoast** [comment]
Intel® Xeon Phi™ Coprocessor - Request 02348003
![image](https://cloud.githubusercontent.com/assets/7040493/22184261/2e67fd7a-e09c-11e6-877a-fd8e32e1443c.png)

**Comment by IlyaFinkelshteyn** [comment]
Hi Robert, please let us know your AppVeyor account name for us to enable **private build could** feature for you. 
And yes, this require your own Azure subscription. 

Thank you,
Ilya.

**Comment by FeodorFitsner** [comment]
Also, I'd like to clarify one more time that all incurring charges for running build VMs on your cloud will be added to your Azure subscription bill.

**Comment by mancoast** [comment]
https://software.intel.com/en-us/articles/intel-compilers-for-windows-silent-installation-guides
We might be able to do a simple install using minimal components.
http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/9955/parallel_studio_xe_2017_update1_cluster_edition_online_setup.exe

**Comment by IlyaFinkelshteyn** [comment]
OK, please let us know how it goes and if this minimal components install leave you enough time to build.

**Comment by IlyaFinkelshteyn** [comment]
I am also adding [initial discussion](http://help.appveyor.com/discussions/suggestions/1185-intel-parallel-studio) to keep history of the problem in one place.

**Comment by mancoast** [comment]
REFERENCE:

parallel_studio_xe_2017_update1_composer_edition_for_cpp_setup.exe --help
Intel(R) Parallel Studio XE 2017 Update 1 Composer Edition for C++ Windows* package. 
 
Usage: <Web image executable> [options] [--a <arguments>] 
 
If no command is specified, the Web Image program will proceed in the Interactive GUI mode. 
 
 Options: 
 --------------------------------------------------------
 --h | --help 
 Show this help
 
 --s | --silent 
 Silent Mode: No GUI, use default setting from command line 
 
 --f  | --extract-folder <extract folder>
 Set extraction folder where content of package will be saved 
 
 --x | --extract-only 
 Skip launching installation after extracting web image content. This option just unpacks the web image 
 
 --l | --log <log file> 
 Log all actions into this log file 
 
 --r | --remove-extracted-files <yes|no> 
 Remove temporarily extracted files after installation 
 
 --a <arguments>
 Pass command line arguments: all arguments after “–a “ switch will be passed as command line arguments into setup.exe (option for launch executable). Includes any argument which setup.exe supports 
########
########
########
extracted setup.exe --help
Commands
--------------------------------------------------------
install - install the product
remove - remove the product
repair - repair existing installation
modify - modify existing installation

Mandatory arguments for non-interactive mode
--------------------------------------------------------
--output=<file> command: all
Specify a file to which the output will be redirected. This option cannot be omitted.
--eula={accept|reject}    command: install
Specify if you accept or reject the End User License Agreement (EULA). You should explicitly accept the EULA to proceed with the installation.

Optional arguments for non-interactive mode
--------------------------------------------------------
--installdir=<installdir> command: install
Specify the installation directory.
--license=<license file> command: install
Activates product using license file(s). <license file> can point to either a file or folder. If folder is specified, Installer will look at all *.lic files in the folder. This option may be used multiple times to specify multiple locations. Do not use this option with the '--sn' option.
--sn=<s/n> command: install
Activates product using a serial number. An internet connection is required in this case. Do not use this option with the '--license' option.
--eval command: install
Evaluate product. Product will be installed in trial mode. Do not use this option with '--sn' and/or '--license' options.
--update={no|always|coexist} command: install
Define if the Installer should force removal of the currently installed version of the product prior to installing the version in this package. The options are: 'no' - do not remove the currently installed version, and if any version is found, end the installation; or 'always' - remove the currently installed version (if any) and proceed with the installation or 'coexist' - install so that currently installed version and new version coexist. The default value is 'no'.
--log=<path> command: all
Specify a location for a LOG files. Log file are used for debug purposes. Support Engineer can ask you to send these files.
--send-data={yes|no} command: install
Indicates agreement to participate in Intel(R) Software Improvement Program, by default is 'no'.
--components={all|default|component1, component2, ...} command: install, modify
Specify a list of components for install or modify. The options are: 'all' - install all components (full install); 'default' - install only default components.
--silent=<file> command: install
Run install silently, with settings in the configuration file <file>.

--ignore-cpu command: install
Skip CPU model check.

Comments on activation:
You can activate the product by either specifying license file (--license) or by specifying serial number (--sn). If you don't specify any of these options, the Installer simply checks if the product is already activated.

Arguments for Setup Wizard mode
--------------------------------------------------------
--duplicate=<file>
Save install configuration collected using Setup Wizard mode to a file for further install duplications in a silent mode. 
--download-only
Run Installer to download only selected components. Installation and the product configuration process is skipped with this option. Downloaded install content could be used for further serial installations.
--download-dir=<folder>
Specify a folder to store downloaded content.
 
Support information
--------------------------------------------------------
Support Web Site: http://www.intel.com/software/products/support/

**Comment by IlyaFinkelshteyn** [comment]
Do you need help with creating install script?

**Comment by mancoast** [comment]
something along the lines of:
`
parallel_studio_xe_2017_update1_composer_edition_for_cpp_setup.exe --silent -a install --eval --eula=accept --output=install-IPS.log
`

Does that seem correct?

**Comment by IlyaFinkelshteyn** [comment]
I usually create simple build job with [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/), go to VM and debug whole thing from download to install interactively, and only after that add this to the build config.

**Comment by mancoast** [comment]
RDP makes this much easier.

IPS functions operate normally with evaluation activation.
Now we need mpss:
http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11193/mpss-3.8.1-windows.zip

Lastly, mpss Libraries:
http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11193/mpss-3.8.1-k1om.tar

**Comment by IlyaFinkelshteyn** [comment]
I provided working script for MPSS in the [original post](http://help.appveyor.com/discussions/suggestions/1185-intel-parallel-studio), right?

**Comment by mancoast** [comment]
excellent!

> 
> ```
> 
> $zipPath = "$($env:USERPROFILE)\mpss-3.8.1-windows.zip"
> (New-Object Net.WebClient).DownloadFile('http://registrationcenter-download.intel.com/akdlm/irc_nas/11193/mpss-3.8.1-windows.zip', $zipPath)
> 7z x $zipPath -y -ompss | Out-Null
> & '.\mpss\mpss-3.8.1\Intel(R) Xeon Phi(TM) coprocessor essentials.exe' /S /v/qn
> sleep 60 #sleep to ensure installation completed
> ```

**Comment by mancoast** [comment]
Any hints for generation of RPM from a given folder for build-package using windows platform?

ex: MyApp/build-package  -->  MyApp-v1.35-mpss-3.8.1-k1om.rpm

**Comment by IlyaFinkelshteyn** [comment]
We don't have a lot of experience with it (mostly .NET shop)... I found [this](http://zcourts.com/2012/09/11/building-rpms-on-windows/#sthash.aQZUNlt2.dpbs) and it seems that we already have `rpmbuild` as part of MSYS2 (`C:\msys64`) installation. With this information and debugging  in RDP I hope you can make it :)

**Comment by mancoast** [comment]
Greetings,

I am seeing failure with k1om libs download. Not sure why? Any suggestions?

```
        $k1omPath = "$($env:USERPROFILE)\mpss-3.8.1-k1om.tar"
        (New-Object Net.WebClient).DownloadFile('http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11193/mpss-3.8.1-k1om.tar', $k1omPath)
        7z x $k1omPath -y -ok1om | Out-Null
```

I need the k1om libs for cross compilation:
```
        ## BUILD
        echo call-vcvarsall
        pushd 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC'    
        cmd /c "vcvarsall.bat x86_amd64&set" |
        foreach {
          if ($_ -match "=") {
            $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
          }
        }
        popd
        echo call-iclvars
        pushd 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin'    
        cmd /c "iclvars.bat intel64&set" |
        foreach {
          if ($_ -match "=") {
            $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
          }
        }
        popd
        write-host "`nMicrosoft Visual Studio 14.0-VC." -ForegroundColor Red
        refreshenv
        echo cl-version
        echo ICC-compiler
        $compilerPathICC = "${env:ProgramFiles(x86)}\\IntelSWTools\\compilers_and_libraries\\windows\\bin\\intel64_mic\\icc.exe"
        # & $compilerPathICC -help
        echo ICPC-compiler
        $compilerPathICPC = "${env:ProgramFiles(x86)}\\IntelSWTools\\compilers_and_libraries\\windows\\bin\\intel64_mic\\icpc.exe"
        # & $compilerPathICPC -help
        echo ICL-compiler
        $compilerPathICL = "${env:ProgramFiles(x86)}\\IntelSWTools\\compilers_and_libraries\\windows\\bin\\intel64\\icl.exe"
        # & $compilerPathICL -help
        echo k1om-Compilation
        # Build k1om #
        $SYSROOT=./k1om
        $MPSSDIR=$SYSROOT
        CC=icc CXX=icpc ^
        CXXFLAGS="-g -O3 -fPIC -mmic" ^
        CFLAGS="-g -O3 -fPIC -mmic" ^
        cmake ^
        -DCMAKE_SYSTEM_NAME=Linux ^
        -DCMAKE_SYSTEM_PROCESSOR=k1om ^
        -DCMAKE_FIND_ROOT_PATH=$MPSSDIR ^
        -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER ^
        -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY ^
        -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY ^
        -DCMAKE_INSTALL_PREFIX=./install-mic/gsl ^
        -C$SRC/TryRunResults-mic.cmake ^
        .
        msbuild /m GSL.sln
```

**Comment by mancoast** [comment]
We need to extract rpms in folder: C:\projects\icc-ci\k1om\mpss-3.8.1\k1om
![image](https://cloud.githubusercontent.com/assets/7040493/22615097/6dec8d26-ea5b-11e6-8403-8f578b3e97df.png)

On Linux [CentOS]:
for rpm in *.rpm; do rpm2cpio $rpm | cpio -idm; done

Any Suggestions for an easy powershell/7z solution?
https://ci.appveyor.com/project/mancoast/icc-ci/build/1.0.1.0.0.7.30-master

**Comment by mancoast** [comment]
@IlyaFinkelshteyn Have you been able to override CMAKE CXX and CC variables for specification of compiler executable?  CMAKE always wants to use icl.exe instead of icpc.exe and icc.exe.  Any suggestions?

**Comment by mancoast** [comment]
resolved using nmake generator for CMAKE with CXX and CC overrides pointing to ICPC and ICC respectively.  everything good to go, thanks!

**Comment by IlyaFinkelshteyn** [comment]
@mancoast Oh thanks for update. I tried to produce some useful answer during a week but it is dark area for me :)

**Comment by zbeekman** [comment]
@rouson @porteri @kgeelhood: This is a reminder to see how intel parallel studio can be installed in appveyor Windows instance. (Note to self @zbeekman.)
