### ISSUE TITLE
Environment variables CONFIGURATION and PLATFORM case is invalid.

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#1278]
There are errors with launch .net35 based custom build steps: https://ci.appveyor.com/project/sergey-s-betke/itg-metrcontrol-2-4/build/0.1.0-bootstrapper-vnext.136.build.68

MSBuild adds this variables as `Configuration` and `Platform`. .net35 has error with case sensitive environment variables: http://stackoverflow.com/questions/8732816/c-sharp-system-diagnostics-processstartinfo-environmentvariables-being-case-inse

Please, don't  add variables `CONFIGURATION` and `PLATFORM`, but add `Configuration` and `Platform`.

Thank You.

**Comment by FeodorFitsner** [comment]
That's the thing AppVeyor's **already** adding them as `Configuration` and `Platform` though as far as I know environment variables have been always case-insensitive.

**Comment by sergey-s-betke** [comment]
Yes, environment variables case-insensitive. But .net35 based tools (this is .net35 bug) can not create child processes when variables with same id's exist (case-insensitive same id's, but case-sensitive - not the same id's).

**Comment by sergey-s-betke** [comment]
AppVeyor adding `Configuration`, not `CONFIGURATION`? Where is `CONFIGURATION` variable from? From msbuild? Variables ID's case must be equal for AppVeyor and MSBuild...

**Comment by FeodorFitsner** [comment]
I don't know - might be something specific to your build config. Take a look at the results of `SET` command: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.2558#L42 - it's definitely `Configuration`.

**Comment by sergey-s-betke** [comment]
Excuse me!!! It is my error: https://github.com/Metrolog/ITG.MetrControl.2.4/commit/0b580916c91cbc66e738a3ec854d5656580b16e5
