### ISSUE TITLE
Qt 5.8.0

### ISSUE THREAD

**Issue by martinrotter** [appveyor/ci#1279]
:)

**Comment by martinrotter** [comment]
Come on, guys. :) Waiting for this desperately.

**Comment by srazi** [comment]
Now Qt-5.8 has been added to installed software list and also you said:
> In fact, Qt 5.8 has been just deployed to all images. We are publishing update post shortly.

But:
![appveyor_qt58](https://cloud.githubusercontent.com/assets/1328454/23203381/8b37382c-f8f7-11e6-8071-e128b1d73d1a.PNG)

**Comment by martinrotter** [comment]
I am experiencing probably same problems as person above this comment.

**Comment by dismine** [comment]
Confirm. The same thing for me.

**Comment by FeodorFitsner** [comment]
guys, that image with Qt 5.8 was rolled back because of issues with Miniconda. We are deploying an updated one. Sorry for the inconvenience.
