### ISSUE TITLE
Xamarin 4.2.2.11 for VS 2015

### ISSUE THREAD

**Issue by ChrisMaddock** [appveyor/ci#1280]
Appveyor currently builds Android 6.0 projects with no additional install needed, but not projects using the latest version, 7.1.

Any chance of an update to the relevant SDKs/APIs? 😄 I could of course install myself, but if any version is going to be available by default, it would be nice if the latest was.

**Comment by FeodorFitsner** [comment]
How would you update the SDKs with a script?

**Comment by ChrisMaddock** [comment]
Thanks for the speedy update. I'm afraid I'm not totally sure - I haven't tried anything yet, sorry! My comment was inspired by [this support topic](http://help.appveyor.com/discussions/problems/3177-how-to-add-more-android-sdks-to-build-agents).

Thus far, I've only ever used Android SDK Manager GUI on development machines. If I was actually going to script it, I'd probably use Chocolatey, but I guess that's not a helpful response!

**Comment by ChrisMaddock** [comment]
Have just thought, this is installed with the latest Xamarin for VS update - which I guess could be where the existing installation comes from?

https://developer.xamarin.com/releases/vs/xamarin.vs_4/xamarin.vs_4.2/

**Comment by FeodorFitsner** [comment]
OK, I see - we'll do Xamarin for VS 2015 update. Thanks.

**Comment by ChrisMaddock** [comment]
Great - thanks! 😄

**Comment by ChrisMaddock** [comment]
Thanks @FeodorFitsner!

**Comment by FeodorFitsner** [comment]
This is a fix that should be applied to avoid running `adb.exe` during the build:

```posh
$xmlPath = 'C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets'
$xml = [xml](get-content $xmlPath)
$target = $xml.Project.Target | where {$_.Name -eq "_GetPrimaryCpuAbi"}
$target.RemoveChild($target.FirstChild) | Out-Null
$xml.Save($xmlPath)
```

More about Xamarin bug in this discussion: https://forums.xamarin.com/discussion/89230/latest-xamarin-starts-adb-exe-when-earlier-version-did-not-causing-ci-issue?

We are deploying image update.
