### ISSUE TITLE
C# 7.0 Compatibility

### ISSUE THREAD

**Issue by Kr4ken-9** [appveyor/ci#1283]
Although C# 7.0 is still new and only available with VS 2017 RC (as far as I know) compatibility with it would be nice as MSBuild [cannot compile](https://ci.appveyor.com/project/Kr4ken-9/rocket-unturned/build/1.0.12) my inline variable declarations.

**Comment by IlyaFinkelshteyn** [comment]
Please ask for VS 2017 build worker trial at https://github.com/appveyor/ci/issues/1179. I just forked your build and tried on VS 2017 and it worked good.

Ilya.

**Comment by Kr4ken-9** [comment]
Thank you Ilya!
