### ISSUE TITLE
LLVM 4.0.0 Compiler Infrastructure libraries

### ISSUE THREAD

**Issue by eliaskosunen** [appveyor/ci#1284]
Hi!

My project depends on the LLVM libraries. Currently, only Clang and some of the LLVM command line utilities can be found in `C:\Program Files\LLVM\`. Since building LLVM can be really hard and time-consuming (it can take over an hour, which is the time limit AFAIK) on Windows, it'd be great to be available prebuilt.

Thanks!

**Comment by FeodorFitsner** [comment]
Can you please provide installation instructions for these additional libraries?

**Comment by eliaskosunen** [comment]
Sure!

LLVM has some documentation has some information on building on MSVC: http://llvm.org/docs/GettingStartedVS.html



1. Download the source from LLVM website: http://releases.llvm.org/download.html (only "LLVM source code" is needed). Current version is 3.9.1
2. Run CMake. It shouldn't need any special configuration. Only watch out for spaces in pathnames or build configuration may fail
2.1. Or maybe LLVM_ENABLE_RTTI and LLVM_ENABLE_EH could be enabled (OFF by default)? I don't need them, but some other people might.
3. LLVM.sln in generated
4. Build INSTALL-project
5. Wait patiently. It took 1 hour and 10 minutes on my machine (Win10 VM, i5-6600K, 8GB of RAM)
6. LLVM install directory (set in CMAKE_INSTALL_PREFIX) now has 4 directories: bin, include, lib and tools

**Comment by FeodorFitsner** [comment]
Thanks, will give it a try!

**Comment by eliaskosunen** [comment]
What is the current state of this issue?

**Comment by FeodorFitsner** [comment]
I guess it should done for LLVM 4.0 now, right?

**Comment by FeodorFitsner** [comment]
All right, I gave it a shot and it failed on running CMake step.

I will appreciate if you could hop into AppVeyor build worker VM [via RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) and do all the required steps to build LLVM. I'd then follow the steps that actually work. Thank you.

**Comment by eliaskosunen** [comment]
@FeodorFitsner It seems like the configuration fails on VS 15 (2017) due to a missing assembler. I assume this is an issue with LLVM. Nevertheless, I got it to build properly by using VS 14. The default CMake options seem to be fine.

**Comment by FeodorFitsner** [comment]
I tried building it with VS 2015 and it failed. Could you please give me exact commands that work and I can follow?

**Comment by eliaskosunen** [comment]
That's really strange. I simply downloaded the source in the folder `C:\Users\appveyor\Downloads`, extracted it, created a subdirectory named `build` in it and ran `cmake -G "Visual Studio 14 2015" ..". It generated the project files properly. I ran the build for about 10 minutes and it gave me no errors.

Do you happen to have spaces in the build/download path? That could make the configuration step fail.

**Comment by FeodorFitsner** [comment]
Yep, the command worked. Building in VS now. Thank you!

**Comment by FeodorFitsner** [comment]
Well, it took 1h+ to build llvm.sln in VS 2015 IDE but at the end I've got this error:

```
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
209>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
```

Nothing has generated in `CMAKE_INSTALL_PREFIX` directory. I used the following CMake command to specify directory:

    C:\Users\appveyor\Downloads\llvm-4.0.0.src\build>cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=c:\C:\Users\appveyor\Downloads\llvm-4.0.0.build ..
```

**Comment by eliaskosunen** [comment]
It looks like the installation step failed. I'll make sure to try finding out what's wrong when I get home from school.

**Comment by eliaskosunen** [comment]
> `-DCMAKE_INSTALL_PREFIX=c:\C:\Users\appveyor\Downloads\llvm-4.0.0.build`

That's not a valid path. The error you got usually means that CMake can't write in a directory. Fix the installation path and run VS as administrator just for good measure.

**Comment by FeodorFitsner** [comment]
Good catch! Trying correct command now:

    C:\Users\appveyor\Downloads\llvm-4.0.0.src\build>cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=C:\Users\appveyor\Downloads\llvm-4.0.0.build ..

**Comment by FeodorFitsner** [comment]
I've been able to build everything and put into this archive: https://storage.googleapis.com/appveyor-download-cache/llvm/llvm-4.0.0.build.7z

Can you please check its contents to see everything is OK before we deploy it to build workers?

**Comment by eliaskosunen** [comment]
Looks alright to me.

Since this build also includes the LLVM 4.0 binaries, I guess it would solve #1393 as well.

**Comment by FeodorFitsner** [comment]
OK, thanks. I'm not sure if this is an important component, but LLVM installer from http://releases.llvm.org/download.html page has some integration with Visual Studio through .props and .targets files.

**Comment by eliaskosunen** [comment]
Since I don't use Visual Studio myself I don't know, but I'd assume the installer might be useful for some people.

**Comment by eliaskosunen** [comment]
> The minimum compiler version required for building LLVM has been raised to 4.8 for GCC and 2015 for Visual Studio.

[From here](http://releases.llvm.org/4.0.0/docs/ReleaseNotes.html#non-comprehensive-list-of-changes-in-this-release). The label `VS 2013` should probably be removed.

**Comment by FeodorFitsner** [comment]
That label is for kinda "internal" use - means "deployed to VS 2013 image".

**Comment by EricWF** [comment]
The only change you need from the above instructions in order to build and install Clang and LLD is to checkout their source code into `llvm/tools/clang` and `llvm/tools/lld` (assuming you're top-level LLVM directory is called `llvm`.

Instructions for building and installing LLVM, Clang, LLD, and their respective libraries and headers:

1. Download the source for LLVM, Clang, and LLD from (http://releases.llvm.org/download.html)
2. Extract LLVM to a folder called `llvm`.
3. Extract Clang to `llvm/tools/clang`
4. Extract LLD to `llvm/tools/lld`
5. Configure CMake:
   * I do this from within a developer command prompt, and I configure to target Ninja instead of Microsoft build files.
   * The build directory you use should be outside of the LLVM source tree.
   * My CMake invocation typically looks like `cmake -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_INSTALL_PREFIX=<prefix> <llvm-source-root>`
   * Simply run `ninja` to build everything and `ninja install` to install it.

@FeodorFitsner Let me know if I can be any more help.

**Comment by FeodorFitsner** [comment]
I don't have any experience with neither CMake, nor Ninja. Could you provide more detailed, ready-to-run instructions for #5 please? Also, we'd need x64 binaries as well as noted [here](https://github.com/appveyor/ci/issues/1518)?

**Comment by EricWF** [comment]
Ack. I'll provide a CMD script to clear up any ambiguity.

**Comment by EricWF** [comment]
@FeodorFitsner Actually I imagine an `appveyor.yml` that builds the required libraries would work as well?

**Comment by FeodorFitsner** [comment]
Absolutely, thanks!

**Comment by EricWF** [comment]
@FeodorFitsner I think this [`appveyor.yml`](https://gist.github.com/EricWF/28b1e46fdecee9bb0219d5aa55293041) should be sufficient for showing how to build LLVM/Clang/Clang tools extra/LLD. The file is for the top-level LLVM repository.  I have a [sample build going here](https://ci.appveyor.com/project/EricWF/llvm)

The `appveyor.yml` provides a number of configurations, including x86 and x64 builds with MSVC 2017, MSVC15, and clang-cl. You'll have to modify it to use the 4.0 sources instead of the git trunk, but that should be easy. Let me know if you need any help.

**Comment by EricWF** [comment]
Note that this will also install the full Clang toolchain as well, but I can't imagine that being an issue.

/Eric
