### ISSUE TITLE
Find a way to expose Do not drop users in SQL deployment

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1285]
Not exposed directly in DacDeployOptions Class, but available in recent [SSDT tools](https://blogs.msdn.microsoft.com/ssdt/2015/02/23/new-advanced-publish-options-to-specify-object-types-to-exclude-or-not-drop/). Need to find a way to manage it with .NET and then expose in SQL deployment config.

**Comment by IlyaFinkelshteyn** [comment]
http://stackoverflow.com/questions/21917669/dacpac-exclude-users-and-logins-on-export-or-import

Look for // THIS IS THE MAGIC SETTING THAT FINALLY WORKED.

**Comment by FeodorFitsner** [comment]
https://blogs.msdn.microsoft.com/ssdt/2015/02/23/new-advanced-publish-options-to-specify-object-types-to-exclude-or-not-drop/

**Comment by IlyaFinkelshteyn** [comment]
Probably this should be set when `Do not drop users` checkbox selected
```
ExcludeObjectTypes = new[] { 
             ObjectType.Users,
             ObjectType.Logins,
             ObjectType.RoleMembership }
```
