### ISSUE TITLE
Render a "Build: unknown" badge instead of error text for status badges

### ISSUE THREAD

**Issue by carols10cents** [appveyor/ci#1288]
Hi! We've recently added support for adding one's appveyor status badges to [crates.io](http://crates.io), but there are instances where people have specified the badge before setting up appveyor or typoed their repo name or otherwise made a mistake. 

For example, carols10cents/rustlings is a repo that I haven't set up in appveyor, but I could specify the badge for crates.io and it would attempt to use this URL: https://ci.appveyor.com/api/projects/status/github/carols10cents/rustlings?svg=true&branch=master

That URL currently returns JSON text:

```
{"message":"Project not found or access denied."}
```

which causes the image loading to fail on crates.io and the alt text to be displayed:

<img width="230" alt="screen shot 2017-01-29 at 11 03 46 am" src="https://cloud.githubusercontent.com/assets/193874/22405555/ac56b160-e612-11e6-9463-93fa7eb39b22.png">

As you can see in that screenshot, what TravisCI does is instead of an error or a 404, it renders a "build unknown" badge. Example: https://api.travis-ci.org/carols10cents/rustlings.svg?branch=master returns this image: <img src="https://api.travis-ci.org/carols10cents/rustlings.svg?branch=master" />

It'd be awesome if appveyor could do a similar thing and return a "build unknown" image instead of error text! Thanks!! <3

**Comment by FeodorFitsner** [comment]
An update displaying "unknown" has been deployed.

**Comment by carols10cents** [comment]
Thank you!!! ❤️ ❤️ ❤️
