### ISSUE TITLE
project rename

### ISSUE THREAD

**Issue by atagirov** [appveyor/ci#1289]
I've renamed my repository and configure appveyor project to new repo name, but in Appveyor it still uses the old names in the URL and there's no way to change it via UI.

Old name: https://ci.appveyor.com/project/xplat/dealerapi
Desired: https://ci.appveyor.com/project/xplat/xplat.agent.webapi

**Comment by IlyaFinkelshteyn** [comment]
Hi Arthur,

We renamed it for you.

Ilya.

**Comment by atagirov** [comment]
Thanks!
