### ISSUE TITLE
Single .yml file per solution .sln file

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#129]
Discussions: http://help.appveyor.com/discussions/suggestions/375-i-need-a-way-to-specify-which-yml-file-to-use

If a _repo_ has a number of solutions, it's hard to have specific configuration per solution (currently).

The idea is to have a single `yml` file per solution file. If none is found, then fall back the default name.

eg.
- Solution: `MyAwesomeIdea.sln`; 
- Configuration file: `MyAwesomeIdea.yml`, then `appveyor.yml`.

Note: the `yml` file casing should *not* be case sensitive (currently it is).

Initial convo-Reference: [This convo on help.AV](http://help.appveyor.com/discussions/questions/916-multiple-slns-per-repo)

Also references https://github.com/appveyor/ci/issues/40

**Comment by FeodorFitsner** [comment]
Reading appveyor.yml specific for solution name won't work because it's more like chicken-egg problem.

However, what can be (seems like easily) done is an ability to specify the name of configuration YML file on UI that should be used with the project. Kind of appveyor.yml is default config name and you can specify a custom one. And then inside that specific yml you can specify solution file name to build.

**Comment by FeodorFitsner** [comment]
Requested by Adazzle too.

**Comment by PureKrome** [comment]
Sounds like a great solution @FeodorFitsner :) That's waaaay simpler and more accessible. No one needs to read docs to figure out the conventions, etc blah blah blah

:)

**Comment by Martaver** [comment]
Just registering my interest and support for this feature.

Upvote.

**Comment by pedershk** [comment]
Closed - what did the solution become?

We have 15-20 solutions in same repo - and need git filtering per project/solution (only build this solution when this directory/path is changed) as well as YML per project.

What's current status?

**Comment by PureKrome** [comment]
@pedershk - right now, the Appveyor **UI** has a field in the first tab that allows you to specify the name of the file. This custom file can be called anything _and_ can exist in a subfolder (if you have lots of .yml files and you want to keep your repo nice and clean).

This means u need **one AppVeyor Project per Solution** so it's a simple 1-to-1 direct relationship.

For example..

```
\
 \--AppVeyor
     |--- Nightly-Release.yml
     |--- ProjectOne.yml
     |--- ProjectTwo.yml ....
 |-- SomeSolution1.sln
 |-- SomeSolution2.sln
....
```

![image](https://cloud.githubusercontent.com/assets/899878/19017937/9afd3b16-889b-11e6-9ba2-fc86bebcf9a6.png)
