### ISSUE TITLE
Git 2.11.1

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1290]
https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows.1

**Comment by XhmikosR** [comment]
https://github.com/git-for-windows/git/releases/tag/v2.11.1.windows.1

**Comment by ashmaroli** [comment]
https://github.com/git-for-windows/git/releases/tag/v2.12.0.windows.1 :smile:

**Comment by FeodorFitsner** [comment]
Created a new issue for it: https://github.com/appveyor/ci/issues/1345

**Comment by XhmikosR** [comment]
You could just rename the issue, but anyway.
