### ISSUE TITLE
An assembly is mistakenly is treated  as testable

### ISSUE THREAD

**Issue by godrose** [appveyor/ci#1293]
I have an assembly which references NUnit but contains no tests. The assembly itself is portable and it crashes the build because the test runner is unable to run portable assemblies.
".NETPortable test assemblies are not yet supported by the engine".

**Comment by IlyaFinkelshteyn** [comment]
AppVeyor test auto detection uses .NET reflection and yes it looks for references to determine if assembly is test assembly and what test runner to run against it.
What you can do is disable auto detection and [specify what test assemblies](https://www.appveyor.com/docs/running-tests/#selecting-assemblies-to-test). 
I believe you have a reason to reference NUnit without creating any tests, so I am not advising to remove thise reference :)

**Comment by godrose** [comment]
Thanks a lot.
