### ISSUE TITLE
MinGW 5.3.0

### ISSUE THREAD

**Issue by seladb** [appveyor/ci#1302]
Hi, latest version of MinGW32 includes gcc 5.3.0 and latest version of MinGW-w64 includes gcc 6.3.0.
Currently MinGW in appveroyr includes gcc 4.9.3 and MinGW-w64 in appveyor includes gcc 5.3.0
Could you please upgrade both to the latest version?

**Comment by FeodorFitsner** [comment]
Installed into `C:\MinGW`

**Comment by seladb** [comment]
Thanks, what about MinGW-w64? Could you please upgrade it as well?

**Comment by FeodorFitsner** [comment]
Yes, there is an issue for that: https://github.com/appveyor/ci/issues/1329

**Comment by FeodorFitsner** [comment]
Hey, but it's not yet deployed.  We'll close the issue when it's deployed.

**Comment by seladb** [comment]
Cool, thanks a lot!

**Comment by IlyaFinkelshteyn** [comment]
@erguotou520 what build worker image you are using? As you can see [here](https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin) it not going to be available on `Visual Studio 2017`

**Comment by erguotou520** [comment]
Oh~ I didn't see the image filter on the right, sorry.
