### ISSUE TITLE
Commits no longer trigger builds

### ISSUE THREAD

**Issue by Jaben** [appveyor/ci#1304]
For REPO: https://github.com/ChangemakerStudios/Papercut

I moved the repo few months back so that may have something to do with it. How do I get it building again? Delete and recreate?

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
Can you please check if webhooks still being sent after commits, and if yes, please send us response,  `X-GitHub-Delivery` header and time sent of some unsuccessful webhook.

You can find them at https://github.com/ChangemakerStudios/Papercut/settings/hooks

Thanks!
Ilya.

**Comment by Jaben** [comment]
Sure. Thank you:

```
Headers
Cache-Control: no-cache
Content-Length: 65
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Feb 2017 00:41:51 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Body
{"message":"Push request and project repositories do not match."}
```

**Comment by Jaben** [comment]
Old repo: https://github.com/Jaben/Papercut.git
New repo: https://github.com/ChangemakerStudios/Papercut.git

**Comment by Jaben** [comment]
Also can't push release artifact: 

![image](https://cloud.githubusercontent.com/assets/448726/22718567/13657b12-ed6f-11e6-9342-2ad74fc6a018.png)

**Comment by IlyaFinkelshteyn** [comment]
Can you please try to update repository  name as in attachement?
![image](https://cloud.githubusercontent.com/assets/3248386/22723041/055c1322-ed70-11e6-9967-2110f5a0cd5b.png)
![image](https://cloud.githubusercontent.com/assets/3248386/22723056/30896a0e-ed70-11e6-917e-d80f29760a20.png)

**Comment by Jaben** [comment]
Doh, that works! Thanks.
