### ISSUE TITLE
appveyor.yml specified install script not running

### ISSUE THREAD

**Issue by docrinehart** [appveyor/ci#1309]
I have a single git repo set up against two appveyor projects (so everything should run EXACTLY the same)

One is setup as a regular git repo: https://ci.appveyor.com/project/Headspring/serenityhr
One as bitbucket: https://ci.appveyor.com/project/Headspring/serenityhr-6930k

The install script that should be updating the node version doesn't appear to get run against the "normal" git repo project in appveyor.

![serenityhr_1_0_1_-_appveyor_and_serenity_hr_1_0_20_-_appveyor](https://cloud.githubusercontent.com/assets/5891405/22808936/6ffe096c-eef4-11e6-8949-eaaa93eeb229.png)

**Comment by FeodorFitsner** [comment]
"Regular" Git repos do not support `appveyor.yml` - they can be configured via UI only.

**Comment by docrinehart** [comment]
Is there a specific reason it isn't supported for non-integrated git repos? Seems restrictive...

**Comment by FeodorFitsner** [comment]
Yes. There is no way (technically) to fetch a single file from the repository without cloning entire repository. AppVeyor fetches `appveyor.yml` before build is created (GitHub, BitBucket provides API to fetch a single file) and entire repo is cloned to a clean isolated build VM only which is decommissioned when the build is over.

**Comment by IlyaFinkelshteyn** [comment]
@docrinehart  you can use https://github.com/appveyor/ci/issues/1089 if you want to use YAML with classic Git.

**Comment by docrinehart** [comment]
@IlyaFinkelshteyn I'm alright, I figured out the issue with the BitBucket repo (and why it wouldn't appear for me). However, to make this a little easier for others, I'd recommend adding it to the documentation (if it's not already) or making it easier to find if it is.

Perhaps on the "Build Configuration" docs page, under the bullet list _"While working with YAML there are few important points to be aware of:"_

- appveyor.yml cannot be read by default with a "classic git repo" (screenshot with arrow or highlight box of some sort). To use yaml with a classic git repo, (either instructions, or a link to a dedicated page, or a link to #1089) 

This would at least provide a place of reference to keep some of us from hunting through github issues and stack-overflow questions trying to figure out what's going on with our build.

Since my problems are solved/answered, I'm closing this issue. I do however seriously recommend adding/referencing that little tidbit in the documentation. ~Doc

**Comment by docrinehart** [comment]
Also thanks to @FeodorFitsner for your quick reply. Saved me additional hours of digging for an answer out of curiosity.

**Comment by FeodorFitsner** [comment]
Glad to be helpful :)

**Comment by burningTyger** [comment]
This should be in bold or marquee when selecting a regular git repo as a source. Took me an hour to figure out why the appveyor.yml wasn't picked up.
