### ISSUE TITLE
x64 version of Python27.dll

### ISSUE THREAD

**Issue by nicolas-f** [appveyor/ci#1311]
Hi,

In this project https://github.com/Ifsttar/I-Simpa we use AppVeyor to do the build of the project.

The CMake file copy the dll from c:/windows/system32/PYTHON27.dll to the final setup.exe.

However this dll is in 32 bits not 64 bits:

https://ci.appveyor.com/project/nicolas-f/i-simpa/build/1.0.24#L5209

Do you know why this dll is not x64 ?

**Comment by nicolas-f** [comment]
Its weird, the copied file is not the same at the source. Its seem that the problem is CMake not AppVeyor. Sorry for the inconvenience

**Comment by nicolas-f** [comment]
After inspection I think there is an issue.

I run a Hash 512 of c:/windows/system32/PYTHON27.dll

And the result is 
```42bd4b66483224530161d986ad3d6b99bb9ec650cd00e08b677bb69ec16948e2b1571fe5ec06886263cee8a465a04ca352fa8907ee63c8925bf9404565a46f7f```


This is the 32 bit version of Python 2.7

It should be 
```3c7226274bc7b94f64ac8cf74b6b9858f583d122f9231c1bcebaaef20aeffeed85f378b1dd36f3c7008436bc5e9b9bbacf62aaa661ad19c001358e3f3a8f16bb```

**Comment by IlyaFinkelshteyn** [comment]
Hi Nicolas,

Please check versions of Python installed on AppVeyor build worker [here](https://www.appveyor.com/docs/installed-software/#python)

Thanks!
Ilya.

**Comment by nicolas-f** [comment]
Hi,

Thank you I have already read this, this is how I set the Path. 

I just say that python 32 bits dll is in the wrong path. It should be into c:/windows/sysWow32/ not in c:/windows/system32/ (or none of theses path if you have multiple version of python)

Something interesting could be the publishing of the file list with size and sha256 hash of the appveyor machine. Maybe I could create a job to publish this.

I will continue to search the 64 bits dll on the AppVeyor machine.

**Comment by nicolas-f** [comment]
I use AppVeyor yml file to copy the python27.dll into the c:/python27_x64/ folder.

```bash
copy c:\windows\system32\PYTHON27.DLL C:\Python27-x64\python27.dll
```

Cmake fail to do this because cmake.exe is a 32 bit file and as such windows redirect request from system32 folder to syswow64 folder. So the appveyor program seem to be 64 bits program and so successfully copy from the system32 folder.

As if find a workaround this issue is resolved. But I still advise to keep the python dll only in the python folder because you have multiple version of python.

Thanks for reading

**Comment by FeodorFitsner** [comment]
As far as understand installing 32-bit Python 2.7 puts `python27.dll` to `C:\Windows\SysWOW64` directory and installing 64-bit Python 2.7 puts `python27.dll` to `C:\Windows\System32`, correct?

**Comment by nicolas-f** [comment]
Yes it is correct. 

But I don't know if this is the 64 bits version of CMake that is installed on AppVeyor. It seems not.

**Comment by FeodorFitsner** [comment]
AppVeyor build workers have 32-bit CMake installed, however, as part of your build you can download 64-bit CMake from [CMake download page](https://cmake.org/download/), unpack it to some folder and change `PATH` variable.
