### ISSUE TITLE
never-ending build freezes queue

### ISSUE THREAD

**Issue by keradus** [appveyor/ci#1312]
hi ;)

For few weeks **all** builds of my project stuck in queue and were not consumed.
Finally, I had found an reason of this. AV is consuming builds one by one. One of the build have been executing for **651 hours** (!!!). After manually canceling that build, queue has been unblocked and come back to work normally.

Problematic build: https://ci.appveyor.com/project/keradus/php-cs-fixer/build/dev-4534

My issue is solved, but I want to bring your attention into problematic build, so maybe we will avoid such problem in future.

**Comment by keradus** [comment]
BTW, JS code that will cancel all builds visible in build list (so one doesn't need to wait for processing hundreds of outdated builds)
```js
$(".cancel-build").trigger("click")
```

**Comment by FeodorFitsner** [comment]
Yeah, thanks. That was a glitch on our side.

**Comment by keradus** [comment]
As I didn't encounter it for ages, closing.
