### ISSUE TITLE
Add ability to change 'Accounts' without having to log out

### ISSUE THREAD

**Issue by TravisEz13** [appveyor/ci#1313]
## Description
After I login using my GitHub account, I have a list of choices of AppVeyor accounts to use.  It would be nice if I didn't have to log out and log back in to change accounts.  

## Suggestion
A menu option in my user drop down.

**Comment by IlyaFinkelshteyn** [comment]
We should fix another problem in the same change. We do not support more than one GitHub team per user per account. So people should be able to seamlessly switch between `Account / GitHub team` options, not just account.

**Comment by TravisEz13** [comment]
@IlyaFinkelshteyn  This is what I intended to say.

**Comment by IlyaFinkelshteyn** [comment]
It should be actually `Account / AppVeyor role` (sorry for confusion), in this case person who is member of a few GitHub teams (which in turn granted different roles) can select not only account but role too.

This will help to fix limitation described [here](https://www.appveyor.com/docs/team-setup/#understanding-relationship-between-github-team-and-appveyor-role)

**Comment by thomaslevesque** [comment]
Is this change on the roadmap? It's really annoying to logout and relogin all the time to switch between org projects and personal projects.

**Comment by IlyaFinkelshteyn** [comment]
I cannot say specific ETA, but given the pain it brings to our customers we definitely increased it priority and  it should be done in visible future. Sorry once again for vague terminology ;)

**Comment by thomaslevesque** [comment]
@IlyaFinkelshteyn thanks for your reply. Good to know that it's on your radar!

**Comment by andrewgunn** [comment]
@IlyaFinkelshteyn Can I just express that it does indeed cause a lot of pain. I work for an agency where clients will add us to their AppVeyor accounts and it's frustrating going between them.

**Comment by IlyaFinkelshteyn** [comment]
It is implemented. Thank you for your patience :)
![2018-10-13_01h38_00](https://user-images.githubusercontent.com/3248386/46903408-392ea600-ce89-11e8-8fa2-c87e2e925b6d.png)

**Comment by thomaslevesque** [comment]
Nice! That's great, thanks!
