### ISSUE TITLE
Build crashes if "clone_folder" contains spaces

### ISSUE THREAD

**Issue by estar73** [appveyor/ci#1314]
I have a requirement: the clone folder name is prescribed and contains spaces.
When I set the folder in UI it works without problems.
But the same folder name in the appveyor.yml (by the way, it is generated by UI)
`clone_folder: c:\projects\Path with spaces`
causing error:
```
Build started
git clone -q --branch=master git@github.com:ae38/ci-test.git c:\projects\Path with spaces
Too many arguments.
```
I tried to quote the path in YAML, but things get worse.
I guess this is a bug.

**Comment by IlyaFinkelshteyn** [comment]
Thank you, looks like a bug. We investigate. For now temporary workaround is custom clone with quites:
```
clone_folder: c:\projects\Path with spaces
clone_script:
- cmd: git clone -q --branch=%APPVEYOR_REPO_BRANCH% git@github.com:ae38/ci-test.git "c:\projects\Path with spaces"

```

Thanks!
Ilya.

**Comment by estar73** [comment]
It works, thank you!

**Comment by estar73** [comment]
It works as expected now, thank you.

**Comment by IlyaFinkelshteyn** [comment]
Sorry, we were needed to roll back build worker image with updated build agent because of [another issue](https://github.com/appveyor/ci/issues/1279#issuecomment-281757805). It will be fixed soon.
