### ISSUE TITLE
WAP packaging broke if solution contains WebJobs

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1315]
[Discussion](http://help.appveyor.com/discussions/problems/977-deploy-web-job-using-appveyor#comment_38674884)

For unknown reason msbuild is trying to publish web job projects when you call msbuild with `/p:DeployOnBuild=True /p:PublishProfile=<profile_name>` against **solution file**. In this case check for publishing XML fails because AppVeyor creates publishing XML only for Web application projects.
When solution also has cloud service, this code path is skipped and msbuild with `/p:DeployOnBuild=True /p:PublishProfile=<profile_name>` parameters is called against each **web application project** separately. So existence of cloud service hide this issue. 
We need to determine if solution contains any WebJob project and if yes, behave the same way is if it contains cloud service -- call msbuild with `/p:DeployOnBuild=True /p:PublishProfile=<profile_name>` against each **web application project** separately.

**Comment by davidebbo** [comment]
If you have a Web App where WebJobs were added from VS, the Web App imports a special target files. e.g. see [here](https://github.com/davidebbo-test/WebAppWithWebJobsVS/blob/5471db17dc3ba9ccfc632dde3feecdf69c5cf853/WebAppWithWebJobsVS/WebAppWithWebJobsVS.csproj#L273).

Once that's set up, there really should be nothing special about building the Web App with all the WebJobs. e.g. try this:

- Clone https://github.com/davidebbo-test/WebAppWithWebJobsVS
- Run: `nuget restore`
- Run: `msbuild WebAppWithWebJobsVS\WebAppWithWebJobsVS.csproj /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="c:\artifacts";Configuration=Release`

And you'll get everything in the artifact folder: Web App and the WebJobs in app_data.

I highly suggest that you build things as 'normally' as possible, and not try to detect if there are WebJobs. This is just standard msbuild and it should work as is, just like it does from VS, Kudu, VSTS, etc...
