### ISSUE TITLE
Build custom statuses

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#132]
Ability to optionally add a custom status (values to be configured/defined by us) to a build. As my ideal scenario would be for our system testers to set a custom status on a specific build to say “Ready for RTM”, which then would start a “deployment/group deployment” or to fire off a web hook to allow me to auto download all the artifacts to send to a client.

**Comment by IlyaFinkelshteyn** [comment]
closing in favor of https://github.com/appveyor/ci/issues/1502
![2018-03-08_12h00_36](https://user-images.githubusercontent.com/3248386/37173411-6057b66c-22c8-11e8-8e3c-db5820508708.png)
