### ISSUE TITLE
MinGW-w64 6.3.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1329]
Download installer: https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe

Installed into: `C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1`

**Comment by vszakats** [comment]
On a slightly related request: Would it be possibly to update the MSYS2 packages (C:\msys64\) in the VM image?

It currently takes about ~9 minutes per build to download and install MSYS2 mingw-w64 (32 and 64-bit) updates to get to version 6.3.0.

**Comment by FeodorFitsner** [comment]
Added a new issue for that: https://github.com/appveyor/ci/issues/1344

**Comment by vszakats** [comment]
Thank you!

**Comment by chronoxor** [comment]
I think it is good to have x86_64 as well
