### ISSUE TITLE
appveyor.yml defined environment variables are overridden by web UI settings

### ISSUE THREAD

**Issue by AArnott** [appveyor/ci#1332]
You can see this confirmed on [this build](https://ci.appveyor.com/project/AArnott/nerdbank-gitversioning/build/1.0.377) where my script:

```
Write-Host "VisualStudioVersion = $env:VisualStudioVersion"
```

outputs:

```
VisualStudioVersion = 14.0
```

Even though [my appveyor.yml file that went into this build was set to 15.0](https://github.com/AArnott/Nerdbank.GitVersioning/blob/4736bc589f26ca180490f1690c0f23320f2417db/appveyor.yml#L13).

This happens when the [web settings](https://ci.appveyor.com/project/AArnott/nerdbank-gitversioning/settings) for this project set the same environment variable to 14.0. 

As discovered and originally reported [here](https://github.com/appveyor/ci/issues/1179#issuecomment-280874866).

**Comment by FeodorFitsner** [comment]
Well, that's actually a known "feature" - environment variables (and notifications) defined on UI overwrite the ones defined in `appveyor.yml`: https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence

**Comment by AArnott** [comment]
I see. Thanks.
