### ISSUE TITLE
Feature Request: Pre-install Azure Storage Emulator on build machines

### ISSUE THREAD

**Issue by camelofcode** [appveyor/ci#1335]
We've just moved to AppVeyor from VSTS and all is great - except we have had to temporarily disable our integration tests as they are expecting Azure Storage Emulator to be running on the build machine.

We could install this via Powershell at the start of each build, but this would probably slow our builds down quite a lot, so we'd prefer if it came preinstalled like the services and databases available here: https://www.appveyor.com/docs/services-databases/

MSI for Azure Storage Emulator can be found here: https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409

More details about Azure Storage Emulator: https://docs.microsoft.com/en-us/azure/storage/storage-use-emulator

**Comment by FeodorFitsner** [comment]
The latest Azure Storage Emulator 4.6 is already installed on all build workers:
https://github.com/appveyor/ci/issues/1248
https://www.appveyor.com/docs/installed-software/#sdks
