### ISSUE TITLE
Miniconda 2.7 x64 not working

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#1339]
We are encountering a large number of incidents in the past ~10hrs of Miniconda 2.7 x64 being unable to activate. Details can be seen in issue ( https://github.com/conda-forge/conda-smithy/issues/462 ).

**Comment by FeodorFitsner** [comment]
Sorry about that. We were rolling up images update and found an issue with Miniconda installations. Some of them were missing (for some reason) either `conda.exe` or `python.exe` files. We roll backed original images for now. Will push another update tomorrow evening with Miniconda installations fixed: https://www.appveyor.com/updates/2017/02/21/

**Comment by jakirkham** [comment]
No worries. Thanks for handling this so quickly. Already seeing things returning to normal.
