### ISSUE TITLE
Filter build messages by status

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#134]
Discussion:
http://help.appveyor.com/discussions/suggestions/555-filter-build-messages

**Comment by guidobouman** [comment]
Thanks man!

**Comment by ili** [comment]
Please, make paging, or just chek build log, and suggest to download it...
a have  >20k lines in log, so build page hungs, for ex: https://ci.appveyor.com/project/ili/bltoolkit/build/4.3.0.21
and really i do not need to see this log by default...

**Comment by FeodorFitsner** [comment]
Right, doesn't look cool. Loading large logs shouldn't be blocking. I've filed a bug: https://github.com/appveyor/ci/issues/313

**Comment by FeodorFitsner** [comment]
OK, large build log is not blocking UI anymore.

**Comment by ili** [comment]
That's super! Thanks!

**Comment by guidobouman** [comment]
Actually, supporting reversing the log would already help a lot.

Having the latest output at top allows to instantly see the error. The latest info is the most relevant in the logs. Right?

**Comment by laedit** [comment]
It could also be useful to be able to sort/filter with the filename or project column.
