### ISSUE TITLE
RDP not working

### ISSUE THREAD

**Issue by nicowilliams** [appveyor/ci#1346]
https://ci.appveyor.com/project/nicowilliams/jq

I'm trying to debug `./configure`'s failure to find flex.

The IP address shown in the log does not respond to pings.  I cannot connect to the given port on that IP address.  RDP fails, naturally.

**Comment by FeodorFitsner** [comment]
Yes, because once the build is finished its virtual machine is off and deleted. Use "blocking" RDP: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by nicowilliams** [comment]
I couldn't connect even during the build.  The IP was not reachable.  Anyways, I can connect now.  Whatever the problem was, it was transient.  Maybe a routing problem in the middle.  Thanks.

**Comment by nicowilliams** [comment]
Although, mind you, I did have this:

```
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
```

and still, it disconnects when the build fails.

**Comment by IlyaFinkelshteyn** [comment]
It should not, can you please send link to specific change in `appveyor.yml` and related build?
