### ISSUE TITLE
Download issue with URLs containing &

### ISSUE THREAD

**Issue by srazi** [appveyor/ci#1347]
Both `appveyor DownloadFile` and `curl -fsS` can not download file `KillProcDll&FindProcDll.zip` from:
http://nsis.sourceforge.net/mediawiki/images/5/53/KillProcDll%26FindProcDll.zip

**Note:** I was able to download file on my computer using  `curl -fsS` . As a workaround I uploaded file after removing `&` from its name.

output for `appveyor DownloadFile "http://nsis.sourceforge.net/mediawiki/images/5/53/KillProcDll%26FindProcDll.zip"`:
```log
Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 404: Not Found
```

output for `curl -fsS -o "KillProcDll&FindProcDll.zip" "http://nsis.sourceforge.net/mediawiki/images/5/53/KillProcDll%26FindProcDll.zip" `:
```log
curl: (22) The requested URL returned error: 404 Not Found
Command exited with code 22
```

**Comment by IlyaFinkelshteyn** [comment]
Hello,
Please try 
```
- ps: (New-Object Net.WebClient).DownloadFile("http://nsis.sourceforge.net/mediawiki/images/5/53/KillProcDll%26FindProcDll.zip", "$env:APPVEYOR_BUILD_FOLDER\KillProcDll&FindProcDll.zip")
```
It should work OK.

Ilya.

**Comment by srazi** [comment]
@IlyaFinkelshteyn Thank you, it works. tbh, I'm not good in PS. :D
