### ISSUE TITLE
Ruby 2.4.1-1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1350]
Installer: https://github.com/larskanis/rubyinstaller2
Discussion: https://twitter.com/blowmage/status/835940096163471360
Silent installation instructions: https://github.com/larskanis/rubyinstaller2/wiki/FAQ

**Comment by FeodorFitsner** [comment]
https://github.com/larskanis/rubyinstaller2/issues/24

**Comment by larskanis** [comment]
While I really appreciate a pre-installed RubyInstaller-2.4 on appveyor, please note, that the rubyinstaller2 is still beta. I hope to have a release quality when ruby-2.4.1 comes out, but I wouldn't recommend to install it now. There are still some significant changes in the pipeline. Please wait for an official release.

**Comment by FeodorFitsner** [comment]
That makes sense, thanks for commenting on that.

**Comment by larskanis** [comment]
@FeodorFitsner RubyInstaller-2.4.1 is finally released! It would be great, if it could be made available on Appveyor as a preinstalled program. Don't hesitate to contact me, if there are any issues with it.

**Comment by FeodorFitsner** [comment]
Great news, thanks for the update! We'll try deploying it withing the nearest update (next week or so).
