### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by Thealexbarney** [appveyor/ci#1352]
Apparently there's still no user-facing method to do this yet.
I renamed my GitHub repo from `Thealexbarney/LibDspAdpcm` to `Thealexbarney/VGAudio`, but there's no option to change the AppVeyor URL to `https://ci.appveyor.com/project/Thealexbarney/vgaudio`.

Thanks in advance for any assistance.

**Comment by IlyaFinkelshteyn** [comment]
Yes, we have to expose it. Updated.
