### ISSUE TITLE
unzip for Cygwin installed but not working?

### ISSUE THREAD

**Issue by fniephaus** [appveyor/ci#1356]
Hi there,

this [`.appveyor.yml`](https://github.com/fniephaus/appveyor-experiments/blob/3caed577f35f9377e60bbd46de0297f4bb764ada/.appveyor.yml) causes [a build error](https://ci.appveyor.com/project/fniephaus/appveyor-experiments/build/1.0.1/job/dwkv6t3vk4pt0oel), because it cannot find `unzip`.
However, it looks like the build downloaded `unzip` before:
> C:\cygwin\var\cache\setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/unzip/unzip-6.0-16.tar.xz

Any idea why this is happening?

Many thanks,
Fabio

Related: https://github.com/hpi-swa/smalltalkCI/issues/264

**Comment by fniephaus** [comment]
Apparently, `which unzip` returns `/usr/bin/unzip`, but still `unzip` does not seem to work:

https://ci.appveyor.com/project/fniephaus/appveyor-experiments/build/1.0.3

**Comment by Rondom** [comment]
If you are installing new packages, you need to update Cygwin as well.

     -g --upgrade-also                 also upgrade installed packages

**Comment by Rondom** [comment]
I don't think Cygwin supports installing newer packages over older installations without upgrading. I mean, the packages do not have versioned dependencies...

**Comment by fniephaus** [comment]
Thanks, this seems to resolve the problem!
