### ISSUE TITLE
No builds triggered for PRs to spdx/tools-python

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#1359]
I'm expecting https://github.com/spdx/tools-python/pull/20 to trigger builds at https://ci.appveyor.com/project/spdx/tools-python/history, but nothing shows up, the GitHub web interface shows "Waiting for status to be reported".

Background: I used to trigger AppVeyor builds using my personal AppVeyor account (I signed in via my personal GitHub account), but then I wanted to replace my builds with [builds for an org](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization). So I created the org account on AppVeyor, created a separate user on GitHub, gave the GitHub user access to the GitHub org and repo, logged in via the org account at AppVeyor and added the project, and since then PRs do not get built anymore.

What went wrong? Thank sin advance for any insights.

**Comment by sschuberth** [comment]
The webhook was missing, I had to manually add it. What process adds the webhook automatically usually?

**Comment by IlyaFinkelshteyn** [comment]
Hi Sebastian,

It is https://github.com/appveyor/ci/issues/1183 issue. Sorry for confusion.

Ilya.

**Comment by sschuberth** [comment]
Thanks.
