### ISSUE TITLE
APPVEYOR_JOB_NUMBER environment variable

### ISSUE THREAD

**Issue by ai** [appveyor/ci#1362]
Could you add `APPVEYOR_JOB_NUMBER` to [environment variables](https://www.appveyor.com/docs/environment-variables/)?

We use AppVeyor to test PostCSS on Windows — thanks for great service. In PostCSS tests we have spelling check. We try to be responsible and keep CI from unnecessary load. So, why to run spelling check (it sends network request, so it is not so fast) on every node.js version?

To run spelling sheck only on first job in current build I created [yaspeller-ci](https://github.com/ai/yaspeller-ci). In Travis it [just looks](https://github.com/ai/yaspeller-ci/blob/master/bin.js#L7) into `TRAVIS_JOB_NUMBER`.

But I did not find good way to detect first job on AppVeyor (right now I [check](https://github.com/ai/yaspeller-ci/blob/master/bin.js#L9) job name, which is not future proof).

Adding `APPVEYOR_JOB_NUMBER` will be very helpful for me and AppVeyor :).

**Comment by xoviat** [comment]
It's `APPVEYOR_JOB_ID`.

**Comment by ai** [comment]
@xoviat `APPVEYOR_JOB_ID` could be `6q08m3jmav4genwj`. I have no idea how detect that it is first job in current task.

**Comment by xoviat** [comment]
What about `APPVEYOR_JOB_NAME`?

**Comment by ai** [comment]
@xoviat job name could be `Environment: nodejs_version=7`. As you can se there is no job sequence number here.

Right now I use `APPVEYOR_JOB_NAME` to check `/nodejs_version=7/`, but this way is not future proof and `APPVEYOR_JOB_NUMBER` will be much better.

**Comment by hcodes** [comment]
+1

**Comment by ai** [comment]
Done? I can add `APPVEYOR_JOB_NUMBER` to Yaspeller CI?

**Comment by FeodorFitsner** [comment]
Yes! 😃

**Comment by ai** [comment]
Thanks, [implemented](https://github.com/ai/yaspeller-ci/commit/0150d295ae84b05707f1667510531494eb9b195b) it in `yaspeller-ci` 0.4.
