### ISSUE TITLE
Python 3.6 Miniconda

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#1365]
Could the latest Miniconda3 be installed in 32-bit and 64-bit varieties as `C:\\Miniconda36` and `C:\\Miniconda36-x64` respectively please?

**Comment by FeodorFitsner** [comment]
There are already 32- and 64-bit Miniconda installations in `C:\Miniconda36` and `C:\Miniconda36-x64` respectively: https://www.appveyor.com/docs/installed-software/#python

**Comment by jakirkham** [comment]
Awesome. Thanks.
