### ISSUE TITLE
Support for .NET Core SDK 1.0.0

### ISSUE THREAD

**Issue by Kralizek** [appveyor/ci#1367]
Now that finally the .NET Core SDK is out and GA, people will start converting their project.json projects to the new csproj format.

I am experiencing the problem here https://ci.appveyor.com/project/Kralizek/loggingextensions

Am I right if I see these issues solved when a Visual Studio 2017 image is out?

**Comment by ptoonen** [comment]
@Kralizek there's a (closed) issue about it here: https://github.com/appveyor/ci/issues/1176

**Comment by Kralizek** [comment]
oh thanks a lot! :)

**Comment by Kralizek** [comment]
I closed the issue since the `Visual Studio 2017` image is already available
