### ISSUE TITLE
Accounts have a Timezone setting

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#137]
Have the ability to display time/date's under a specific timezone instead of UTC.
- [ ] Accounts have a TimeZone setting
- [ ] Notifications (eg a Slack notification) can now display the `commitDate` converted into the timezone.

**Comment by mikemad** [comment]
I vote for this. An easy fix in the meantime would be some kind of formatting support on the commitDate. Is there any? But ideally an account timezone would be needed. Any progress on this?

**Comment by jamesdixon** [comment]
Any update on this? Just noticed my Slack notifications are about 6 hours off :smile:

**Comment by FeodorFitsner** [comment]
So the issue is in notifications only, right?

**Comment by jamesdixon** [comment]
That's the only place I've seen the issue thus far.

**Comment by mikemad** [comment]
<img width="499" alt="appveyor notification" src="https://cloud.githubusercontent.com/assets/6867661/14030044/cb7d7280-f1c2-11e5-95ff-9d68f136f7c4.png">

Here's an example notification.

**Comment by PureKrome** [comment]
@mikemad and I'm guessing that should say: `Commit 34543534534 by Mike Maddox on 3/23/2016 12:45PM` ?

**Comment by mikemad** [comment]
Yes, that's right!

**Comment by TimMurphy** [comment]
Will the account timezone take date & time format into consideration? e.g. In Australia we display dates as dd/mm/yyyy instead of mm/dd/yyyy.

**Comment by PureKrome** [comment]
@TimMurphy where abouts (in the UI) do you mean? can u paste a quick, rough photoshop'd image, as an example?

**Comment by waynebrantley** [comment]
2 years later, no progress?

**Comment by FeodorFitsner** [comment]
AppVeyor update has been deployed that allows changing account time zone on account details page: https://ci.appveyor.com/account

Selected time zone affects dates in notifications and NuGet feeds.

**Comment by PureKrome** [comment]
Woot! thanks @FeodorFitsner !

**Comment by FeodorFitsner** [comment]
Nope, the setting affects notifications and NuGet feeds only. Time zone on build machine could be easily changed during the build with a single line in `appveyor.yml`.

**Comment by waynebrantley** [comment]
Thanks for clarification.  Great feature, this will help a bunch!!
