### ISSUE TITLE
Scheduled build should not respect any filters

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1372]
Builds started with API or UI are "forced", and do not respect any of [commit filters](https://www.appveyor.com/docs/how-to/filtering-commits/), which is expected behavior.

However scheduled builds do respect commit filters, which sometimes is source of confusion. Probably we need to make scheduled builds to behave the same way as API/UI-started ones. 

This is still an open question, we need to understand is there any real scenarios which can be broken by this change.

**Comment by IlyaFinkelshteyn** [comment]
[+1](http://help.appveyor.com/discussions/problems/6720-scheduled-build-do-not-start-anymore)

**Comment by msevestre** [comment]
+1
