### ISSUE TITLE
Allow skipping build via Build Worker API

### ISSUE THREAD

**Issue by refack** [appveyor/ci#1373]
Maybe remove the `-Name` from being mandatory on `Update-AppveyorTest`
```
Update-AppveyorTest [-Name <string>]
       -Outcome <outcome> { None | Running | Passed | Failed | Ignored | Skipped
```
Or add
```
Update-AppveyorBuild -Outcome Skipped
```

**Comment by IlyaFinkelshteyn** [comment]
[Another similar request](http://stackoverflow.com/questions/42810213/how-to-quit-script-prematurely-on-purpose-on-appveyor)

**Comment by IlyaFinkelshteyn** [comment]
https://www.appveyor.com/docs/build-worker-api/#forcibly-terminate-current-build-with-success
