### ISSUE TITLE
Deleting build should delete its NuGet packages from feeds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1375]

**Comment by serialseb** [comment]
+100. I sometimes get my build number wrong, that pushes a nuget on the project wrong. I can delete the build, and it doesn't mess the UI anymore, but i'm left with the overhanging nuget package in the project feed. Only alternative I know of is to delete and recreate the project, but then i lose all build history.

**Comment by csmager** [comment]
@serialseb You can [delete a package from the command line](http://help.appveyor.com/discussions/questions/603-delete-nuget-package-from-account-feed).

**Comment by serialseb** [comment]
@cmager thanks for the pointer. As you can see from above, I was referring to the package feed, not the account one, and the comand line doesn't help for that one. Deleting a build should delete the associated package in the project feed, and maybe from the account feed too.

**Comment by csmager** [comment]
@serialseb ah, oops! I hadn't even appreciated there were two feeds, I'd only used my account feed (and had deleted a build from that). If it's not possible to delete off the project feed, then I agree with your comments.
