### ISSUE TITLE
.NET Core 1.1.1 with SDK 1.0.1

### ISSUE THREAD

**Issue by rbeauchamp** [appveyor/ci#1377]
Can you please install .NET Core 1.1.1 on the build workers? Or can I install it myself during the build?

Getting this error:

```
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.1
      1.0.3
      1.1.0
  - Alternatively, install the framework version 1.1.1

**Comment by FeodorFitsner** [comment]
Also, in case you use default `Visual Studio 2015` image you can install .NET Core 1.1.1 during the build:

```posh
Write-Host "Installing .NET Core 1.1.1 SDK 1.0.1..." -ForegroundColor Cyan

Write-Host "Downloading..."
$exePath = "$env:TEMP\dotnet-core-sdk-1.1.1.exe"
(New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=843448', $exePath)
Write-Host "Installing..."
cmd /c start /wait "$exePath" /install /quiet /norestart
del $exePath 

Write-Host "Installed" -ForegroundColor Green
```

**Comment by rbeauchamp** [comment]
Okay, thanks! I'll give that a try.

**Comment by ozhelenkov** [comment]
@FeodorFitsner Feodor, thanks for a workaround. But it will be great to have 1.1.1 preinstalled. We have lots of projects and we will wait in case you have planned to have this updated in a close time.
Otherwise, ofc, we will use workaround.

Could you please advise are there any ETA for this update on your side?

Many thanks in advance!

**Comment by FeodorFitsner** [comment]
We are going to roll out VS 2017 image later today which has this SDK installed. That should work for you, right?

**Comment by rbeauchamp** [comment]
The install during the build worked. Thanks @FeodorFitsner .

For others who might want to do this, my YAML file was updated to contain:
```
# install .NET Core 1.1.1
install:
  - ps: Write-Host "Installing .NET Core 1.1.1 SDK 1.0.1..." -ForegroundColor Cyan
  - ps: Write-Host "Downloading..."
  - ps: $exePath = "$env:TEMP\dotnet-core-sdk-1.1.1.exe"
  - ps: (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=843448', $exePath)
  - ps: Write-Host "Installing..."
  - ps: cmd /c start /wait "$exePath" /install /quiet /norestart
  - ps: del $exePath 
  - ps: Write-Host "Installed" -ForegroundColor Green

**Comment by ozhelenkov** [comment]
@FeodorFitsner I believe yes. Thanks!

**Comment by FeodorFitsner** [comment]
The new `Visual Studio 2017` build worker image is now available. Currently, it's being run on Google Compute Engine (GCE) environment only, so builds will be starting in 3-4 minutes (time required to provision and boot up build VM). The image will be available on Hyper-V environment later this week.

**Comment by FeodorFitsner** [comment]
# Fixing "Microsoft.DotNet.Props was not found" error
.NET Core SDK 1.0.1 is now installed on `Visual Studio 2015` image. Various versions of .NET Core Runtime and SDK can work side-by-side and we plan to have the latest runtimes/SDKs always installed to `Visual Studio 2015` image, so CLI-oriented projects can benefit from it.

If you develop .NET Core app in Visual Studio 2015 which has "preview" SDK installed (relying on `project.json` and `.xproj`) you may get `error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found.` error. You should tell build system to use correct version of .NET Core SDK.

## global.json

Add `global.json` file to the folder with your .sln file:

```json
{
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
```

## Removing .NET Core 1.0.1 SDK

This is not a recommended way (as future SDKs will be added), but can be a quick fix to get back to previous SDK.

Add this command to your `appveyor.yml`:

```yaml
install:
- rd /s /q "C:\Program Files\dotnet\sdk\1.0.1"
```

## Switch to Visual Studio 2017

According to Microsoft .NET Core tooling for Visual Studio 2015 won't get any more updates (no switch to `.csproj`-based projects), so consider migrating your projects to Visual Studio 2017 having the most recent tooling for .NET Core.
