### ISSUE TITLE
VS 2017 RTM build failure

### ISSUE THREAD

**Issue by Cisien** [appveyor/ci#1379]
I'm attempting to build a dotnet core 1.1.1 application and getting a failure that appears to be related to not running the nuget restore msbuild tasks.

Project: https://github.com/Cisien/OniBot/
Build: https://ci.appveyor.com/project/Cisien/onibot

Output:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error : Assets file 'C:\projects\onibot\OniBot\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\projects\onibot\OniBot\OniBot.csproj]
C:\Users\appveyor\AppData\Local\Temp\1\.NETCoreApp,Version=v1.1.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [C:\projects\onibot\OniBot\OniBot.csproj]

**Comment by FeodorFitsner** [comment]
Add this to your `appveyor.yml`:

```yaml
before_build:
- nuget restore OniBot.sln
```

**Comment by Cisien** [comment]
Thanks, that got me past the nuget erors. I'm now having an issue building the docker project (.dcproj)

**Comment by Cisien** [comment]
Thanks, that got me past the nuget erors. I'm now having an issue building the docker project (.dcproj)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets(153,5): error MSB4018: Microsoft.DotNet.Docker.CommandLineClientException: Unable to run 'docker-compose'. Verify that Docker for Windows is installed and running locally. For troubleshooting, please review http://aka.ms/DockerToolsTroubleshooting. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified [C:\projects\onibot\docker-compose.dcproj]

The VS 2017 RTM image has docker installed, right?

**Comment by FeodorFitsner** [comment]
@Cisien yes, it does have Docker installed, but I'm not sure `docker-compose` is installed. What's the correct download location for `docker-compose`?

**Comment by Cisien** [comment]
it appears to come with the Docker for Windows installer

**Comment by Cisien** [comment]
it appears to come with the Docker for Windows installer
https://docs.docker.com/docker-for-windows/install/

**Comment by FeodorFitsner** [comment]
@Cisien OK, try adding the following to your `appveyor.yml`:

```yaml
install:
- ps: (New-Object Net.WebClient).DownloadFile('https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Windows-x86_64.exe', "C:\Program Files\docker\docker-compose.exe")
```

**Comment by Cisien** [comment]
The build is passing! Thanks for the prompt assistance!

Things I still have left to figure out -- posting here in case the answer is known by someone.
- How do I switch Docker into "Windows" mode (I'm building a Windows container)
- How do I push to docker.io (I'm fairly sure this will involve me issuing a docker login command, and a docker push command).

**Comment by FeodorFitsner** [comment]
This article could help: https://stefanscherer.github.io/setup-windows-docker-ci-appveyor/

**Comment by Cisien** [comment]
That post will help out a lot, however, it is lacking the one piece of information I haven't been able to find. I need to switch Docker over to Windows Container mode. Everything I've found so far requires me to interact with the icon in the system tray https://puu.sh/uCgVB/44e0503c90.png

**Comment by FeodorFitsner** [comment]
It's already running in Windows Container mode. `Visual Studio 2017` image is based on Windows Server 2016 OS and Docker installed on it works with Windows Containers.

You're probably talking about "Docker for Windows" which is a separate product. Docker for Windows configures a new Hyper-V VM with Linux and Docker installed on it.

**Comment by Cisien** [comment]
I see. I was getting confused by a tag I saw in the build output. It turns out the tag was sourced by the stock docker-compose template
    ```labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"```
Thanks for the assistance!
