### ISSUE TITLE
Feature: node.js v0.12

### ISSUE THREAD

**Issue by am11** [appveyor/ci#138]
The stable version of node.js is v0.12 now. See http://nodejs.org/.

Currently it is giving us error: https://ci.appveyor.com/project/sass/node-sass/build/463/job/6k18kwus26d2rf5d.

It would be really nice if you guys incorporate nvmw (node version manager for Windows): https://github.com/hakobera/nvmw in order to automate the process. `nvmw` also supports io.js (https://github.com/hakobera/nvmw#usage). TravisCI uses nvm (https://github.com/creationix/nvm) which is only available for Linux/Mac.

Moreover, the current version of io.js is 1.1: https://github.com/iojs/io.js/releases which is also unrecognised: https://ci.appveyor.com/project/sass/node-sass/build/463/job/8o4woalaci4cencf.

**Comment by FeodorFitsner** [comment]
node 0.12 will be added today.

We have our own node version manager and also, you can use this cmdlet to install any version of node/io: http://www.appveyor.com/docs/lang/nodejs-iojs#installing-em-any-em-version-of-node-js-or-io-js

**Comment by am11** [comment]
Thanks!  :)

There are number of ways to detect the stable version. For example, io.js has distribution releases listed in JSON and tabular formats here: https://iojs.org/dist/ which points to their stable release. Similarly, node.js has distribution releases listed here: http://nodejs.org/dist/latest/. 

AppVeyor can perhaps use a Windows service which constantly check for stable versions once a day and download/cache it.

My 2¢.
