### ISSUE TITLE
PostgreSQL not available?

### ISSUE THREAD

**Issue by roji** [appveyor/ci#1383]
Trying to use PostgreSQL (include `postgresql` in services) in the VS2017 image seems to fail:

```
Starting PostgreSQL 9.5
Start-Service : Cannot find any service with service name 'postgresql-x64-9.5'.
At line:1 char:1
+ Start-Service 'postgresql-x64-9.5'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (postgresql-x64-9.5:String) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StartServiceCommand
```

Note sure if this is related to the new image or to something else. #615 seems to describe some sort of workaround but the state of things isn't very clear.

**Comment by FeodorFitsner** [comment]
PostgreSQL 9.5 has been installed on `Visual Studio 2017` image.
