### ISSUE TITLE
Question: Is there a way to emit current matrix information in user code?

### ISSUE THREAD

**Issue by am11** [appveyor/ci#139]
With multiple node-like *runtimes* (https://github.com/sass/node-sass/issues/655), there is are use-cases which demand awareness of current runtime (io.js, node.js, atom-shell).

On TravisCI, we can call Linux `which node` command to get the full path of the executable the current matrix is using (they switch the version with `nvm` and hence `which` returns the absolute path to active version's executable). Is there a way to get that information from AppVeyor?

Note that this is different that [identifying the runtime within JS script](https://github.com/am11/node-sass/blob/4c72885a2a37d3707eb239d43a2c70d838aca414/lib/extensions.js). We need it to instantiate the npm jobs defined in package.json (such as `npm test`) with corresponding runtime (as opposed to generic `node node_modules/blah`).

**Comment by am11** [comment]
@FeodorFitsner,

Here is the commit that is failing because `npm test` is invoked by node.js with "io.js job": https://ci.appveyor.com/project/sass/node-sass/build/509/job/j64xahfv6bej00br#L191

The corresponding TravisCI job is https://travis-ci.org/sass/node-sass/jobs/50524897#L582. You will notice that io.js job, all calls to `node` are redirected to io.js.

I think this could be the better solution than making users write a runtime-redirection script for npm?

**Comment by FeodorFitsner** [comment]
Oh, could you please elaborate what do you mean?

**Comment by am11** [comment]
With io.js job, `node` should be an alias to `iojs.exe`.

**Comment by FeodorFitsner** [comment]
Right, there are two similar executables in io.js distribution:

![image](https://cloud.githubusercontent.com/assets/5041459/6197508/9b5cf33e-b39b-11e4-9b69-2b51721c0cff.png)

**Comment by am11** [comment]
Thanks for pointing that out. I did not noticed that  up until now that io.js packs binaries with both aliases. 

The trouble is, [our script](https://github.com/sass/node-sass/blob/dfc026bae39bd4e3e5aae9b3d10dbe25d9ae36bd/lib/extensions.js#L10-L16) relies on `process.execPath` property to detect the [current runtime](https://github.com/sass/node-sass/issues/655). The reason why we don't have this issue with TravisCI is that `process.execPath` in io.js path actually returns `/path/to/io.js/iojs` executable with command run through `node`. On AppVeyor, it returns `\\path\\to\\io.js\\node.exe`, where the problem occur. Would be nice if you guys can figure out the way TravisCI is handling it (using `nvm`).

**Comment by am11** [comment]
@FeodorFitsner, nvmw downloads only io.js and then they make a copy of `alias-node.cmd` to `node.cmd` in iojs version installation directory like this: [nvmw.bat#L170](https://github.com/hakobera/nvmw/blob/31c2429d3e74f3c5c3cfa260b2c6b97fed200779/nvmw.bat#L170), where [alias-node.cmd](https://github.com/hakobera/nvmw/blob/31c2429d3e74f3c5c3cfa260b2c6b97fed200779/alias-node.cmd) has the canned content:

```cmd
:: Created by nvmw, please don't edit manually. 
 @IF EXIST "%~dp0\iojs.exe" ( 
   "%~dp0\iojs.exe" %* 
 ) ELSE ( 
   iojs %* 
) 
```

node-sass uses C++ add-on and it will cause many issues only by using different exec (which emits different information), not by node-sass but the pangyp, which is the build tool.

**Comment by FeodorFitsner** [comment]
I'm not sure [the way you detect node.js/io.js runtime](https://github.com/sass/node-sass/blob/dfc026bae39bd4e3e5aae9b3d10dbe25d9ae36bd/lib/extensions.js#L10-L16) is correct. You rely on availability of redirecting `node.cmd` on Windows platform, however standard io.js distribution doesn't include it. This batch is nvmw-specific feature. If I use node-sass on my Windows with node.exe from io.js distribution the tool will detect it as `node` which is incorrect. Or I just don't understand the whole logic behind that?

**Comment by am11** [comment]
Here is the latest version: [extensions.js#L11-L24](https://github.com/sass/node-sass/blob/6dc6c632cd47f3929a196674b488b8164f9a4793/lib/extensions.js#L11-L24). This is still debateable how to identify the runtime as you can see here: https://github.com/TooTallNate/node-gyp/pull/564. Meanwhile our solution to identify runtime is working out fine.

For Linux, io.js provides a symlink called `node` which points to iojs (4bytes) in `bin/` dir, which nvmw mimics via `node.cmd`. On Windows we can also create a symlink, which [this line](https://github.com/sass/node-sass/blob/6dc6c632cd47f3929a196674b488b8164f9a4793/lib/extensions.js#L12) <b><sup>†</sup></b> resolves to real executable. The decision io.js made specifically for Windows is unreliable IMVHO. Since Windows symbolic links are not share FS objects, they actually mirror the real object as soon as you try to move, copy or package it to a zip, `node.cmd` is the only solution we can propose on io.js issue tracker. Meanwhile AppVeyor can adapt nvmw approach.

*<b><sup>†</sup></b> that line is not necessary to resolve the symlink on Linux, it is also a Windows-only issue in libuv. see: https://github.com/iojs/io.js/issues/851 & https://github.com/libuv/libuv/issues/206.*
