### ISSUE TITLE
Provide padded build number for nuget

### ISSUE THREAD

**Issue by roji** [appveyor/ci#1390]
Nuget sorts prerelease tags lexicographically, so `MyPackage-ci-2` is considered more recent than `MyPackage-ci-12`. Because of this, it seems to be standard practice to zero-pad: `MyPackage-ci-00002`.

Appveyor provides `$(build)` and `APPVEYOR_BUILD_NUMBER`, it would be very useful to also have a padded version of these, for passing to `dotnet pack --version-suffix`.

**Comment by FeodorFitsner** [comment]
You can simply add to your `appveyor.yml`:

```yaml
install:
- ps: $env:padded_build_number = $env:appveyor_build_number.ToString("00000")
```

Then use `padded_build_number` environment variable in `dotnet pack` command.

**Comment by roji** [comment]
@FeodorFitsner thanks for the Powershell trick (it's much better than the cmd workaround I had in place).

Since anyone publishing nugets as part of their continuous integration needs to do this, it seems to make sense to have it in appveyor rather than repeating this same snippet - but I understand wanting to keep things simple on your side.

**Comment by roji** [comment]
FYI your snippet failed: `Cannot find an overload for "ToString" and the argument count: "1"`.

However, the following works: `ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')`

**Comment by FeodorFitsner** [comment]
Good catch! This is because `appveyor_build_number` is a string.

This works too:

```yaml
install:
- ps: $env:padded_build_number = ([int]$env:appveyor_build_number).ToString("00000")
```
