### ISSUE TITLE
Deployment notifications

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#14]
Discussions:
http://help.appveyor.com/discussions/suggestions/391-deployment-notifications
http://help.appveyor.com/discussions/suggestions/451-deployment-success-or-failure-slack-status

**Comment by JSkimming** [comment]
Has this been implemented? In step 12 of the [Build Pipeline](http://www.appveyor.com/docs/build-configuration#build-pipeline) it states _Call deployment_success webhooks_, though I can find no other reference to `deployment_success`.

**Comment by FeodorFitsner** [comment]
Not yet. Think about doing that as part of the next release together with other deployment-related items like Permissions and Agent improvements.

**Comment by ravisakaria** [comment]
:+1:  Looking forward to this one too... thanks. Great product.

**Comment by rajinders** [comment]
I also need to be able to notify on deployments.
When we check in code to do a build. It has inline deployment as well. It generates notifications in slack to tell our developers that and deployment were completed.
For Test and Production we have Environment based deployments that are manually triggered. We want to send notifications after those deployments are complete.

Any ETA for when this will be available? 

Thanks

**Comment by FeodorFitsner** [comment]
Don't have an ETA, but can assure you that this and other deployment improvements (such as permissions, and history) have highest priority. Will start working on that this week.

**Comment by briandonahue** [comment]
:+1: For deployment notifications - Slack preferred over email :)

**Comment by anthony-sheehy** [comment]
+1 this would be great

**Comment by oyvindvalland** [comment]
+1 I'm really missing this for HipChat.

**Comment by sbosell** [comment]
+1 would be helpful for hipchat notifications on deployments.

**Comment by jbaxleyiii** [comment]
Any updates on this timeline?

**Comment by LSTANCZYK** [comment]
+1 for this

**Comment by briandonahue** [comment]
@FeodorFitsner This is added?  Any docs/info available yet?  Thanks!

**Comment by FeodorFitsner** [comment]
Yes, that's added. Docs are coming. Basically, open Environment settings and then configure notifications on "Notifications" tab. Also, email deployment notifications can be enabled "globally" as build ones on https://ci.appveyor.com/notifications page.

**Comment by briandonahue** [comment]
Awesome, thank you!

On Mon, Feb 1, 2016 at 2:16 PM Feodor Fitsner <notifications@github.com>
wrote:

> Yes, that's added. Docs are coming. Basically, open Environment settings
> and then configure notifications on "Notifications" tab. Also, email
> deployment notifications can be enabled "globally" as build ones on
> https://ci.appveyor.com/notifications page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appveyor/ci/issues/14#issuecomment-178136922>.
>
-- 
Brian Donahue
Vitreo, LLC
215.586.3965

**Comment by oyvindvalland** [comment]
Amazing! Thanks!

**Comment by briandonahue** [comment]
@FeodorFitsner Is it possible to get the Job Name/Machine Name for deployments with more than 1 target, so that you can create a notification template that details which machines were deployed to?

**Comment by FeodorFitsner** [comment]
Currently, you can get environment details only, for example its name `{{environment.name}}`.

**Comment by gilios** [comment]
my appveyor.yml has "notifications" configuration for events:
on_build_success 
on_build_failure 
on_build_status_changed 
are there any deploy events ? 
it seems like the deployment notifications are available only from the environments page

**Comment by IlyaFinkelshteyn** [comment]
Hello,

Yes, only environment deployment has notifications, but you can use environment as part of the build. Will creating a new environment, and use it as your deployment provider in your build works for you? If not, please elaborate your requirements and current configuration more.

Thanks!
--ilya.
