### ISSUE TITLE
RDP not working with `image: Visual Studio 2017`

### ISSUE THREAD

**Issue by refack** [appveyor/ci#1409]
I'm not able to RDP to workers running `image`: `Visual Studio 2017`.
Since it's a new image I'm suspicious...

**Comment by IlyaFinkelshteyn** [comment]
We have some inconsistent behavior with newly added servers which maps to higher port range. Can you please send us non-working port number and if build is still available do not cancel it for us to investigate?

If you already cancelled the build, please retry, it will most probably work next time.

**Comment by refack** [comment]
https://ci.appveyor.com/project/refack/windows-autoconf/build/1.0.116/job/w4wt6utw4dby797b

**Comment by Thealexbarney** [comment]
I can't connect via RDP even after retrying a few times. I currently have a dummy build running [here](https://ci.appveyor.com/project/Thealexbarney/xenobladesave).

**Comment by FeodorFitsner** [comment]
@Thealexbarney I've been able to RDP into [that build](https://ci.appveyor.com/project/Thealexbarney/xenobladesave/build/1.0.8) - as a proof I deleted text file on desktop to make it continue.

**Comment by Thealexbarney** [comment]
I asked others if they could connect to the build worker, and they couldn't either. I also tried using a different RDP client, and that didn't change anything.
Since you were able to connect to my earlier build after about 50 minutes, I tried waiting that long to see if maybe that changed anything, but it didn't.

**Comment by FeodorFitsner** [comment]
Please ping me next time you can't connect but don't cancel a build.

**Comment by Thealexbarney** [comment]
@FeodorFitsner I've started [another dummy build](https://ci.appveyor.com/project/Thealexbarney/xenobladesave/build/1.0.11) that just runs the enable-rdp script. I'm unable to connect to it.

**Comment by FeodorFitsner** [comment]
It worked again for me - I unblocked the build. Maybe that custom `34xxx` ports is the problem? Have you tried connecting from other locations?

**Comment by FeodorFitsner** [comment]
Can you please start another build (and check if you can connect) and let me know - *I* will check from a different location.

**Comment by Thealexbarney** [comment]
@FeodorFitsner [Here's](https://ci.appveyor.com/project/Thealexbarney/xenobladesave/build/1.0.12) another build.

I just now tried from multiple locations, Internet connections and computers, and none of them have worked.

**Comment by FeodorFitsner** [comment]
Checking...

**Comment by FeodorFitsner** [comment]
OK, it looks like this is a firewall issue on our side. We are going to work with our data center to resolve that. Will let here know when it's OK.

**Comment by FeodorFitsner** [comment]
It's been fixed. Sorry for inconveniences.

**Comment by TerraVenil** [comment]
Using `image: Visual Studio 2017` can't connect via RDP to build worker.
