### ISSUE TITLE
appveyor eats error messages from PowerShell DSC

### ISSUE THREAD

**Issue by vors** [appveyor/ci#141]
If you run this script locally on PS v 4 (we need Enable-PSRemoting for Start-DscConfiguration):
```
Enable-PSRemoting -Force
Configuration TestConfiguration
    {
        Script script1
        {
            SetScript = { Write-Error "ERROR!!!!"}
            GetScript = "Test script1"
            TestScript = { $false }
        }
    }
TestConfiguration
Start-DscConfiguration -Wait -Verbose .\TestConfiguration -Force
```

you will get an "ERROR!!!!" in error stream:

![image](https://cloud.githubusercontent.com/assets/816680/6183277/06b9e950-b308-11e4-935c-7039808731cc.png)

If you put it in `appveyor.yml` test_script, you will not get this error.

![image](https://cloud.githubusercontent.com/assets/816680/6183291/39e27964-b308-11e4-8386-2b58cc163705.png)

**Comment by FeodorFitsner** [comment]
Interesting issue. Is there any way to know how the output from `SetScript` is getting processed.

Seems `Write-Error` by itself works perfectly fine:

![image](https://cloud.githubusercontent.com/assets/5041459/6198196/c7663f08-b3aa-11e4-9df3-5a520c274d64.png)

**Comment by vors** [comment]
Yes, exactly. The code for Script resource can be found in `C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCResources\MSFT_ScriptResource\MSFT_ScriptResource.psm1`, you may take a look to `Set-TargetResource function`.

But it's DSC specific. DSC runs under SYSTEM account. When `Start-DscConfiguration` is called with `-Wait` it uses remoting to retrieve streams. Problem is probably with error stream via remoting.
