### ISSUE TITLE
VSO authentication token expires sporadically

### ISSUE THREAD

**Issue by vors** [appveyor/ci#142]
Every 3 days VSO acces token is expired.

![image](https://cloud.githubusercontent.com/assets/816680/6195267/2f26f206-b381-11e4-9d13-ad9fbe080604.png)

I go to the web interface and grant VSO access again.

**Comment by FeodorFitsner** [comment]
Will take a look. It should be automatically renewed. Maybe something changed on VSO side.



-Feodor

**Comment by vors** [comment]
Today it happened 3 times.

**Comment by FeodorFitsner** [comment]
So, it's randomly, not once in 3 days...

That `Start-AppveyorBuild` cmdlet - does it use HTTPS or HTTP protocol to call REST API?

**Comment by FeodorFitsner** [comment]
Apparently, lots of changed in VSO OAuth 2.0 support since we added it into AppVeyor, like scopes for example. I'm going to revisit this stuff.

**Comment by vors** [comment]
It's https, but same happens for portal: I push a branch and it hangs on queueing it for build. Apparently it hits the same problem: cannot retrive commit metadata.

**Comment by FeodorFitsner** [comment]
Still can't reproduce the issue....

**Comment by vors** [comment]
Should I let you know next time it would happen? What kind of information do you need to troubleshoot it?

**Comment by FeodorFitsner** [comment]
The only "fragile" place in AppVeyor could be token renewal... Are you using only one VSO login?

**Comment by vors** [comment]
Yes, only one.

**Comment by vors** [comment]
How often tokens expire?

**Comment by FeodorFitsner** [comment]
Every 15 minutes. But every time it's accessed in code AppVeyor checks its expiration time and renew it if current time greater than expiration time.

**Comment by vors** [comment]
What if it's expired in 15 minutes, nobody accessed it. Then VSO call service hook to trigger build. I just guessing :)

**Comment by FeodorFitsner** [comment]
It's getting renewed. "Renewal" token is never expired. http://www.visualstudio.com/integrate/get-started/auth/oauth (see Refresh token section)

**Comment by vors** [comment]
Just happened again

**Comment by FeodorFitsner** [comment]
Do you use "Visual Studio Online" login button?

**Comment by vors** [comment]
Yes.

**Comment by FeodorFitsner** [comment]
Will add more logging around renewal logic to see what's going on.

**Comment by FeodorFitsner** [comment]
Deployed update with additional logging. Next time it happens, hopefully, we'll see what's going on there.

**Comment by vors** [comment]
Just happened again.

**Comment by FeodorFitsner** [comment]
OK, I've checked logs. When AppVeyor attempts to refresh access token it receives `response code: 400, response body: {"Error":"invalid_request","ErrorDescription":"The access token is not valid"}` from VSO API. More weird it seems like only your account has been throwing that during the last 2 days (though we have many other VSO customers).

I'm going to add even more logging to see even successful token refresh attempts.

**Comment by vors** [comment]
Thank you for looking into that

**Comment by vors** [comment]
Just happened again

**Comment by FeodorFitsner** [comment]
I've checked logs. Seems like it's kind of racing condition when two threads are trying to renew the token and, obviously, the second one fails as refresh token is already used! :) Let me see how to better fix that.

**Comment by vors** [comment]
Cool

**Comment by FeodorFitsner** [comment]
We deployed an update with the fix. It should be fine now.
