### ISSUE TITLE
.NET Core SDK 1.0.1

### ISSUE THREAD

**Issue by Thealexbarney** [appveyor/ci#1422]
The most current version of the SDK is version 1.0.1. It's the version offered for download on the [official download page](https://www.microsoft.com/net/core#windowscmd).

**Comment by FeodorFitsner** [comment]
Do you need 1.0.1 SDK on Visual Studio 2015 or Visual Studio 2017 image?

**Comment by Thealexbarney** [comment]
Me personally? The 2017 image.

It could be useful on the 2015 image as well since the .NET Core SDK doesn't depend on Visual Studio.

I don't know if it will conflict with the preview2 tools in VS 2015, but if the 1.0.0 release is already working when installed on the 2015 image, then the 1.0.1 release shouldn't have any issues.

**Comment by FeodorFitsner** [comment]
We've deployed .NET Core SDK 1.0.1 to VS 2017 image. The image is being copied at the moment. Will be available in hour or so.

I'm going to close this ticket when it's done.
