### ISSUE TITLE
curl not found from bash?

### ISSUE THREAD

**Issue by krlmlr** [appveyor/ci#1424]
Failing build: https://ci.appveyor.com/project/hadley/dplyr/build/1.0.658/job/e6m0q6eft5uhc2wu#L19

The relevant PowerShell code: https://github.com/krlmlr/r-appveyor/blob/ab7d1ae00ec293f1f7433cfbea25fb49846bda90/scripts/appveyor-tool.ps1#L92

I should be able to use PowerShell facilities instead, but it certainly would be easier for me if I just could continue using curl. Thanks.

**Comment by FeodorFitsner** [comment]
There is an explanation and solution: http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491

**Comment by krlmlr** [comment]
Awesome, thanks!
