### ISSUE TITLE
curl seems to have disappeared

### ISSUE THREAD

**Issue by ezyang** [appveyor/ci#1425]
Compare https://ci.appveyor.com/project/23Skidoo/cabal/build/%233338%20(master) (3 days ago) with https://ci.appveyor.com/project/23Skidoo/cabal/build/%233339%20(master) (just now).

**Comment by krlmlr** [comment]
Duplicate of #1424?

**Comment by ezyang** [comment]
Yep, that's right!

A changelog note about this would be much appreciated!
