### ISSUE TITLE
curl.exe is not on PATH

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1426]
Previous versions of Git had `curl.exe` in `C:\Program Files\Git\usr\bin` folder which is added in `PATH` on build workers. The main reason it was on PATH was `ssh.exe` utility Git (and Mercurial) required to fetch repo via SSH.

Now, `curl.exe` has gone from `C:\Program Files\Git\usr\bin` and left in `C:\Program Files\Git\mingw64\bin` only. To fix the build add this to your `appveyor.yml`:

```
install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
```

Alternatively, CURL can be installed via Chocolatey with `choco install curl` command or used from other locations such as MinGW, Cygwin and MSYS: https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin, for example:

* `C:\msys64\usr\bin`
* `C:\cygwin\bin`

We are not yet completely sure whether we should explicitly add `C:\Program Files\Git\mingw64\bin` folder into PATH on build workers or not - there is always a risk of causing another conflict. Less stuff on PATH is better.

**Comment by jakirkham** [comment]
Would it be possible to copy it back? Even when I say it, I know it sounds pretty hacky. Just thinking of the best way to fix things quickly given this change.

**Comment by FeodorFitsner** [comment]
Yes, we are going to fix that by adding `C:\Program Files\Git\mingw64\bin` to `PATH`.

**Comment by jakirkham** [comment]
Out of curiosity is there anything else of note in that directory?

**Comment by FeodorFitsner** [comment]
https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.2670#L392

**Comment by jakirkham** [comment]
Thanks. There are a few things that could clash. Though we make sure are stuff is searched first. So I don't think it will be an issue.

**Comment by FeodorFitsner** [comment]
Does curl.exe depend on some other libs/dlls or it's standalone exe? Maybe we could just copy it somewhere under `C:\Tools` and add that folder into PATH?

**Comment by jakirkham** [comment]
From my notes, it could be linked to zlib.

**Comment by Diggsey** [comment]
This is really unhelpful! Can't you make updates to the system images be manual, so that we can deal with changes at a convenient time?

**Comment by avh4** [comment]
Thanks for the quick updates!  The suggested workaround had me up and running again in a few minutes.

**Comment by IlyaFinkelshteyn** [comment]
@Diggsey sorry for the trouble. We need to make this experience better and filed https://github.com/appveyor/ci/issues/1430

**Comment by FeodorFitsner** [comment]
We're going to have `curl` installed on build workers and added to `PATH`: https://github.com/appveyor/ci/issues/1431
