### ISSUE TITLE
curl 7.53.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1431]
`curl` will be installed to all AppVeyor build workers into separate folder and added to `PATH`.

* Download location: https://bintray.com/vszakats/generic/curl/7.53.1
* Installation location: `C:\Tools\curl`
* Should be added into beginning of `PATH` variable to have highest priority
* Update installed software page on website
* Check that pre-installed curl is not conflicting with the one installed by Chocolatey

**Comment by piem** [comment]
hi! is there an estimated time-frame for this one?

many thanks, piem

**Comment by piem** [comment]
oh, I see the 26-Mar-2017 milestone now. cheers!
