### ISSUE TITLE
Update build cache after failure

### ISSUE THREAD

**Issue by alberthdev** [appveyor/ci#1434]
Currently, the behavior seems to be that if the build fails in some way, the build cache will not be uploaded. Is this intended behavior, and if so, is there any way it could be adjusted?

(I'm using the build cache to detect if the last build succeeded or not - not the best way to do it for sure, but it works!)

**Comment by IlyaFinkelshteyn** [comment]
Hi Albert,

Please check [this](https://gist.github.com/IlyaFinkelshteyn/03fb15779904c50ea19b6d348a76e29c) sample on how to get last build status from build with API.

**Comment by alberthdev** [comment]
Thanks for the sample! This looks like a much easier solution, and I'll aim for using this method for detecting past build failure!

Regarding regular build cache use (e.g. not detecting build success/failure), is the current build cache behavior going to stay? Just wanted some clarification in case I use the build cache in the future!

**Comment by IlyaFinkelshteyn** [comment]
We are thinking on more general change in this direction. We need provide customers with more flexible scenarios not only for cache step. One idea is to implement `goto` functionality, another is custom steps order. We have no good vision yet, but yes we need scenario to be more flexible.

**Comment by IlyaFinkelshteyn** [comment]
@alberthdev please check recently implemented `APPVEYOR_SAVE_CACHE_ON_ERROR` environment variable.  Documented [here](https://www.appveyor.com/docs/build-cache/#saving-cache-for-failed-build).
