### ISSUE TITLE
APPVEYOR_PULL_REQUEST_REPO_NAME and APPVEYOR_PULL_REQUEST_REPO_BRANCH variables

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1435]
[Discussion](http://help.appveyor.com/discussions/questions/3292-getting-github-branch-name)

Exact variable names:

* `APPVEYOR_PULL_REQUEST_REPO_NAME`
* `APPVEYOR_PULL_REQUEST_REPO_BRANCH`

Also according to [another discussion](http://help.appveyor.com/discussions/problems/6531-environment-variable-to-get-head-of-pull-request-being-built) we might need to add
* `APPVEYOR_PULL_REQUEST_HEAD_COMMIT_ID`

**Comment by Rondom** [comment]
I hope it is okay to mention another issue here.
If you decide to implement this issue, it would not be much work to implement the "before-push-sha1" as well, because both enhancements are done probably in the same parts of the code.
#1157

**Comment by IlyaFinkelshteyn** [comment]
The following variables are in production (for GitHub only now):
`APPVEYOR_PULL_REQUEST_HEAD_COMMIT`
`APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME`
`APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH`

Keeping this issue opened, until https://github.com/appveyor/ci/issues/1157 added + the same at least for BitBucket

**Comment by ivailop** [comment]
As initially named/spec-ed you were planning to provide `APPVEYOR_PULL_REQUEST_REPO_NAME/BRANCH` (no `HEAD` in the name)?

**Comment by IlyaFinkelshteyn** [comment]
Yes... We though it would be more self-explaining name if include `HEAD`...

**Comment by ivailop** [comment]
I just tried it for both `fork` and `branch` PR builds and found that `APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH` is never set.

**Comment by IlyaFinkelshteyn** [comment]
I tried this today in the morning with [this](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/1.10.254) simple test and it worked. Can you please point me to the repro in public repository?

**Comment by ivailop** [comment]
`fork` PR - https://ci.appveyor.com/project/munderseth/build-box/build/1.0.100
`branch` PR - https://ci.appveyor.com/project/munderseth/build-box/build/1.0.101

In both cases `APPVEYOR_PULL_REQUEST_HEAD_COMMIT` and `APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME` were properly set. But `APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH` was not.

**Comment by ivailop** [comment]
The mentioned above builds were **reruns**. I just tried again with a **new** build and it worked all fine. Sorry for creating any unnecessary noise.

**Comment by IlyaFinkelshteyn** [comment]
Oh, thanks for clarification, this is not unnecessary noise! I believe we can make it work for reruns and calls from API too.

**Comment by IlyaFinkelshteyn** [comment]
This is still not fully completed

**Comment by IlyaFinkelshteyn** [comment]
@ivailop now for rerun it works too. Still keeping the issue open as not everything requested is done.

**Comment by Megamouse** [comment]
https://www.appveyor.com/docs/environment-variables/

I guess they are missing here, unless I am blind.
Sorry for posting on this closed issue but didn't want to open a new one just for that

**Comment by IlyaFinkelshteyn** [comment]
@Megamouse Thank you, sure https://github.com/appveyor/website/pull/363
