### ISSUE TITLE
Coverity support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#144]
http://help.appveyor.com/discussions/suggestions/497-coverity-static-analysis-support
http://arkfps.github.io/2015/01/07/using-coverity-scan-with-appveyor/

**Comment by csMACnz** [comment]
:+1:

**Comment by csMACnz** [comment]
My 40 minute time-out triggers just trying to download the coverity files sometimes, it is a whopping 411Mb file compressed, it would be good to have this on the server to stop my builds failing. Having it somewhere on the vm and the bin folder added to the Path would work for me.

**Comment by csMACnz** [comment]
Update: I've created my own subset zip (stripped out java stuff) down to a size of 223Mb, which now only adds 10-20 mins to the build, which helps, but still a pretty large chunk of slow in my builds.

**Comment by gep13** [comment]
@csMACnz have you put this stripped down version somewhere, or can you let me know what you took out?  I have been thinking about adding this into the build process for a couple projects, but not had a chance to look at it yet.  Thanks!

**Comment by FeodorFitsner** [comment]
We'll schedule the deployment of Coverity to build workers during the next week.

**Comment by gep13** [comment]
:+1:

**Comment by csMACnz** [comment]
:+1:

**Comment by csMACnz** [comment]
@gep13 its on my dropbox, so probably not something you want to build a dependency around, worth waiting for the deployment I think :)

**Comment by gep13** [comment]
@csMACnz yip, given that @FeodorFitsner is going to go ahead with getting this on the build worker image, I will hold off until I know it is there.  Thanks!

**Comment by FeodorFitsner** [comment]
Looks like download link for Coverity build tool is project specific: https://communities.coverity.com/message/6120#6120

Does it embed something into downloaded archive? Could someone comment on this?

**Comment by csMACnz** [comment]
My guess is that this is 'authentication' and nothing more, but will check on this.

**Comment by csMACnz** [comment]
Looks like no specific project stuff in there. All date-stamps of files are the same, and they provide a public checksum to verify the zip.

**Comment by holytshirt** [comment]
Awesome! Was going to ask if Coverity could be done.
:+1:

**Comment by FeodorFitsner** [comment]
We've just updated build worker images: `Coverity Scan Build Tool 7.6.0 x64` was added to all workers in `C:\Tools\Coverity`. `C:\Tools\Coverity\bin` added to `PATH`.

**Comment by sawilde** [comment]
awesome I was just looking into this today and saw the download size and thought - "there is no way I want that in my repo" - thanks again.

**Comment by csMACnz** [comment]
Also for those interested in using coverity, check out https://www.nuget.org/packages/PublishCoverity and let me know what you think.

This little console utility can zip the folder, as well as post it to Coverity.

https://github.com/csmacnz/coveritypublisher

**Comment by holytshirt** [comment]
:+1:

**Comment by Mailaender** [comment]
Has anyone successfully set up this up so I can steal the AppVeyor.yaml configuration? Tried it myself at https://github.com/OpenRA/OpenRA/pull/8313 but the publishing ends up doing nothing so I am not sure what is going wrong: https://ci.appveyor.com/project/OpenRA/openra/build/1.0.3478

**Comment by gep13** [comment]
@Mailaender I have this working for GitReleaseManager here:

https://github.com/gittools/gitreleasemanager

Although, my build on Friday night (I have a scheduled build) failed, so I think something has changed on the Coverity side of things.  I haven't dug into it yet, but I noticed this:

https://arkfps.github.io/2015/01/07/using-coverity-scan-with-appveyor/#comment-2052366861

Which I need to dig into.

**Comment by csMACnz** [comment]
Hey @gep13, I spent the weekend looking into that issue. suspect something changed at their end stopping my submissions. Nevermind. should be working again if you try and update to PublishCoverity version 0.10.0 https://www.nuget.org/packages/PublishCoverity

**Comment by gep13** [comment]
Nice one! I will wait and see if my build on Friday works! Thanks for looking into this! :-)

**Comment by MikhailTymchukDX** [comment]
Looks like Coverity script setup is quite complex, according to this blog post: https://thehermeticvault.com/software-development/using-coverity-scan-with-appveyor

@csMACnz Can I use [PublishCoverity](https://www.nuget.org/packages/PublishCoverity) from within AppVeyor build pipeline?

**Comment by gep13** [comment]
@MikhailTymchukDX I was able to get this working well, yes.

You can see how I was doing this here: https://github.com/GitTools/GitReleaseManager/blob/develop/BuildScripts/default.ps1#L551

**Comment by MikhailTymchukDX** [comment]
@gep13 Very cool, thanks!
