### ISSUE TITLE
Document how to setup Visual Studio build environments (x86, x64)

### ISSUE THREAD

**Issue by mloskot** [appveyor/ci#1444]
There are several questions on help.appveyor.com about how to properly configure build environments to directly run Visual Studio toolset programs (`cl.exe`, `link.exe`, `nmake.exe`). This is necessary when building a project with NMAKE and makefiles, CMake with "NMake Makefiles" generator and perhaps some other builders.

It would be good if the commands necessary to run can make it into the docs somewhere:

* Toolset to target 32-bit

```
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
```

* Toolset to target 64-bit
```
call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
```

Often, users do not know/remember to run both scripts for 64-bit.

**Comment by IlyaFinkelshteyn** [comment]
It would be great if you can contribute to our docs, our website is open source!

**Comment by mloskot** [comment]
Yes and [I did that several times](https://github.com/appveyor/website/pulls/mloskot), but in this case I have no idea where such info belongs to,  which page, section.

**Comment by IlyaFinkelshteyn** [comment]
What do you think about creating C++ related page at https://github.com/appveyor/website/tree/master/src/docs/lang?

**Comment by mloskot** [comment]
@IlyaFinkelshteyn Done
