### ISSUE TITLE
CoApp Support

### ISSUE THREAD

**Issue by NaxAlpha** [appveyor/ci#1446]
Hi,

[CoApp](http://coapp.org/) is better alternative to writing NuGet for C/C++. But it is not pre installed on AppVeyor. I tried to install it by myself but it didn't work. Following is code in post build:

    Invoke-WebRequest -OutFile CoApp.Tools.Powershell.msi http://coapp.org/files/CoApp.Tools.Powershell.msi
    Start-Process -FilePath ".\CoApp.Tools.Powershell.msi" -ArgumentList "/passive" -PassThru |Wait-Process
    [System.Environment]::SetEnvironmentVariable("PSMODULEPATH", [System.Environment]::GetEnvironmentVariable("PSMODULEPATH", "User") , "User")

And following is code in pre-deploy (as said in CoApp documentation):

    Write-NuGetPackage .\xyz.autopkg

But it gives following error

    Write-NuGetPackage : The term 'Write-NuGetPackage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 

It would be good idea if CoApp would be pre installed on server. Or I may be doing something wrong if someone can help me!

Thanks

**Comment by FeodorFitsner** [comment]
Corrected installation script that worked for me:

```posh
Invoke-WebRequest -OutFile CoApp.Tools.Powershell.msi http://coapp.org/files/CoApp.Tools.Powershell.msi
Start-Process -FilePath ".\CoApp.Tools.Powershell.msi" -ArgumentList "/passive" -PassThru |Wait-Process
$env:psmodulepath = "C:\Program Files (x86)\Outercurve Foundation\Modules\CoApp;$env:psmodulepath"
```

**Comment by NaxAlpha** [comment]
Thanks a lot. That really helped!
