### ISSUE TITLE
VS 2017 Image does not contain Xamarin

### ISSUE THREAD

**Issue by Cheesebaron** [appveyor/ci#1448]
When building a Xamarin.iOS library we get the following error:

```
error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by FeodorFitsner** [comment]
Visual Studio 2017 targets for iOS are located in `C:\Program Files (x86)\Microsoft Visual Studio 2017\Community\MSBuild\Xamarin\iOS` folder. If you create a new iOS library project in VS 2017 it compiles perfectly fine on `Visual Studio 2017` image. Was your project created in VS 2017? Can you share a link to its repo (if it's public) or make a simple repro in a public repository?

**Comment by Cheesebaron** [comment]
This is a project which was created long ago. The repo is the linked issue https://github.com/MvvmCross/MvvmCross/issues/1657

It builds fine on my desktop where I have both VS2015 and VS2017 installed. Haven't tried on a clean install though.

**Comment by Cheesebaron** [comment]
Looking at the log it can't find the targets for Xamarin.Android either. I was not aware that the path had changed to *C:\Program Files (x86)\Microsoft Visual Studio 2017\\{VSType}\MSBuild\Xamarin\iOS*

**Comment by Cheesebaron** [comment]
@FeodorFitsner how does the targets line look like in your VS2017 project?

```
<Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />
```

**Comment by IlyaFinkelshteyn** [comment]
Please try to run your build in call VS command prompt environment by adding this into your build configuration:
```
install:
- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
```

**Comment by Cheesebaron** [comment]
```
Error parsing appveyor.yml: (Line: 19, Col: 5, Idx: 539) - (Line: 19, Col: 28, Idx: 562): While parsing a quoted scalar, find unknown escape character.
```

**Comment by IlyaFinkelshteyn** [comment]
Please send us full YAML file to check

**Comment by Cheesebaron** [comment]
https://github.com/MvvmCross/MvvmCross/blob/develop/appveyor.yml

**Comment by IlyaFinkelshteyn** [comment]
My bad, I sent wrong sample, it should be single-quoted:
```
install:
- `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat`
```
Note that you can test and fix YAML using https://ci.appveyor.com/tools/validate-yaml

**Comment by Cheesebaron** [comment]
https://ci.appveyor.com/project/MvvmCross/mvvmcross/build/1.0.166 still fails.
https://github.com/MvvmCross/MvvmCross/pull/1657/commits/ceacbd0af8dc6ab1cc3aff333d0867d696f4fb42

Are we just going to play around until it works or what?

**Comment by FeodorFitsner** [comment]
Correct command has two sets or quotes around it:

```
install:
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
```

Outer single quotes make yaml happy and inner double quotes are for CMD 😄

**Comment by Cheesebaron** [comment]
That helped on that particular command. However, NuGet.exe won't do its job:

https://ci.appveyor.com/project/MvvmCross/mvvmcross/build/1.0.168

**Comment by IlyaFinkelshteyn** [comment]
Tomasz,

Let us indeed stop "play around until it works" for a moment and clarify what we want to achieve. 
Solution was build OK on `Visual Studio 2017 RC` because that image was basically `Visual Studio 2015` with `Visual Studio 2017 RC` installed on top of it. Your local computer is probably has the same history, and that's why it worked on `Visual Studio 2017 RC` image and works on your computer now.

New `Visual Studio 2017` is different. It is clean install of VS 2017 **RTM** on Windows Server 2016. We later added Visual Studio 2015 to it, but with minimum number of components. Thus it exposes all issues old project have. I am pretty sure that if you try to build your solution on any local clean installation of VS 2017 you will have all the same issues.

We could add Xamarin to VS 2015 on this new `Visual Studio 2017`, but in this case it will not be clean and will not expose dependency issues like yours. Then your solution will historically depend on 2 VS versions installed and every new developer should have them both.

Therefore I think that you have 2 options now:

- use `Visual Studio 2015` image. Anyway if you check you latest successful build on `Visual Studio 2017 RC` [log](https://ci.appveyor.com/api/buildjobs/b2o9f10fy8sl0qu5/log) it always uses msbuild 14 which has nothing to do with VS 2017

- migrate to VS2017, ensure it builds on local clean VS2017 and start using `Visual Studio 2015' image.

**Comment by martijn00** [comment]
I've got a clean Windows 10 machine with only VS2017 installed. I've got these workloads installed:
* Universal windows development
*  .NET Desktop development
* ASP.NET and web development
* Mobile development with.NET (Xamarin)
* Visual studio extension development
* .NET Core cross platform development

I can build my solution without problems, but when building on AppVeyor, it has the same problem as this issue: https://ci.appveyor.com/project/martijn00/xamarinmediamanager

**Comment by onovotny** [comment]
You should not need to install Xamarin bits for VS 2015. Those are only there for some older Win8 reference assms. Installing the Xamarin workload from the VS 2017 installer should be sufficient.

**Comment by onovotny** [comment]
Lets take a step back there, because I don't think VS 2015 has anything to do with this.

**Comment by martijn00** [comment]
@onovotny So you are saying the Xamarin workload is installed on Appveyor? What's the difference with our project and any other random Xamarin project that does build?

**Comment by martijn00** [comment]
I think this is an issue with the VS2017 machine. We have no connections to VS2015 or older Windows parts like wp8 in our code base.

**Comment by onovotny** [comment]
@martijn00 I'm not saying there isn't an issue with the current image, I'm just saying that there shouldn't be anything to do with VS 2015's install or not.

**Comment by martijn00** [comment]
Right. Also because i can build this perfectly fine on my machine which just has VS2017RTM, never had VS2015 on it.

**Comment by Cheesebaron** [comment]
I just made a fresh VM with Windows 10 Pro + VS2017, nothing else. It builds just fine.

Had to do some changes to the Cake bootstrapper for it to restore NuGets which I also did in the repo now. Now the build fails on updating the AppVeyor build number...

https://ci.appveyor.com/project/MvvmCross/mvvmcross/build/4.5.0-PullRequest.1657+2000.build.173

**Comment by Cheesebaron** [comment]
This might be useful: http://cakebuild.net/blog/2017/03/vswhere-and-visual-studio-2017-support

It still puzzles me, why the exact same script works fine on a clean Win 10 + VS2017 machine and not the AppVeyor environment...

**Comment by FeodorFitsner** [comment]
@martijn00, @Cheesebaron OK, I've provisioned a new VM with "Visual Studio Community 2017 and Windows Server 2016" from Azure catalog and tried building `develop` branch of [XamarinMediaManager](https://github.com/martijn00/XamarinMediaManager/tree/develop) project. It fails with similar errors as on AppVeyor. Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/5041459/24517808/86eed15e-1534-11e7-9201-71b36ea5137f.png)

That VM is still running - I left all opened windows intact - if you want to play with it and see how to make XMM build working there please drop a message to "team AT appveyor.com" and I'll send you RDP details.

**Comment by Cheesebaron** [comment]
I've sent you a mail. Hopefully we can dig out what is going on here and how it is different from our VM's.

**Comment by FeodorFitsner** [comment]
Details sent.

**Comment by Cheesebaron** [comment]
I haven't come closer to any conclusion.

I get varying results whether I use the cake build script or invoke MSBuild directly.

When using the cake script if for some reason looks for the Xamarin targets in 

    C:\Program Files (x86)\MSBuild\Xamarin

Until run the VsCmd.bat before.

Invoking MSBuild directly on the sln file it looks correctly at

    C:\Program Files (x86)\Microsoft Visual Studio 2017\Community\MSBuild\Xamarin

Invoking MSBuild directly it still fails because now it cannot find csc.exe, however, only on Release configuration builds 🤔 

It is looking for

     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\Roslyn\csc.exe

However the Roslyn folder is not present in amd64 but is present directly in the Bin folder.

I really have no idea what is going 😢

**Comment by onovotny** [comment]
@FeodorFitsner How did you get MSBuild working? I suspect that adding MSBuild to the path may not be enough....proper use may need the VsCmd.bat to work. Not 100% sure. I'm not suggesting that AppVeyor needs to fix this, it may need to be something within Cake?

I've run my Xamarin builds using msbuild.exe / powershell that calls msbuild, with AppVeyor and it works fine. This looks to be something within Cake that's not interacting with VS 2017 the right way?

**Comment by onovotny** [comment]
@Cheesebaron The real test is to just use 

nuget restore MySolution.sln
msbuild /t:build MySolution.sln /p:Configuration=Release

And see what happens. 

If that works, then something within Cake isn't quite right then....

**Comment by FeodorFitsner** [comment]
@onovotny - I did nothing (for the purpose of clean experiment) more but ran all the steps from [this appveyor.yml](https://github.com/martijn00/XamarinMediaManager/blob/develop/appveyor.yml) for `develop` branch on a "stock" Azure VM created from "Visual Studio Community 2017 with Windows Server 2016" image. @Cheesebaron was playing with the same machine. If you like to look at it I can share RDP details over email.

Maybe we should start from a more basic repro and see what's missing/wrong with building VS 2017 Xamarin projects in command line?

**Comment by Cheesebaron** [comment]
For now I am just moving our stuff to a personal VSTS build agent where things work. We are kind of dependent on working builds. Also this way I can control which Android SDK versions to use too.

However, we would still very much like to use AppVeyor as build logs etc are publicly visible.

I am going to try what @onovotny suggested later today to see if that yields anything interesting. That is if that VM is still running @FeodorFitsner

**Comment by FeodorFitsner** [comment]
That VM was deleted, however you can easily bring it up on Azure from this template: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Microsoft.VisualStudioCommunity2017onWindowsServer2016x64?tab=Overview

**Comment by Cheesebaron** [comment]
OK, I'll try that then 👍

**Comment by Cheesebaron** [comment]
So I span up a new Windows Server 2016 x64 with VS 2017 Community. I went into Android SDK manager and installed Android API 24. Then I ran the build.ps1 script through Powershell.

_everything_ went well ✅ . 

None of the same issues as I encountered with the VM I was logged into you provided @FeodorFitsner 

What is the difference here? Why does it fail on your image, and not with the one I span up? They should be similar, no?

**Comment by FeodorFitsner** [comment]
Can you please provide exact list commands you ran before `build.ps1` (once you logged into VM for the first time)? Last time I followed commands from [this appveyor.yml](https://github.com/martijn00/XamarinMediaManager/blob/develop/appveyor.yml), i.e. installing/upgrading Android stuff via command line - everything was done via command line.

**Comment by gep13** [comment]
@Cheesebaron have you tried running Cake in Diagnostic mode?

http://stackoverflow.com/questions/38658660/how-to-enable-diagnostic-verbosity-for-cake

That will show you exactly what command is being executed, and from there, you can do a comparison between what you run directly and when it works, and when it doesn't.

**Comment by Cheesebaron** [comment]
I didn't run any commands. I went into Android SDK manager in `Program Files (x86)\Android` and just ticked SDK Platform for API 24. That should be the equivalent of:

` - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-24`

@gep13 I don't have access to @FeodorFitsner's instance anymore. However it was MSBuild failing not finding the correct paths. It couldn't find `csc.exe` in the x64 folder when trying to compile Xamarin.iOS projects. This works on the instance I fired up 🤔

**Comment by FeodorFitsner** [comment]
@Cheesebaron what you are doing manually here is not the same at in [appveyor.yml](https://github.com/martijn00/XamarinMediaManager/blob/develop/appveyor.yml#L43-L52). Rather than using pre-installed Android SDK you are downloading it, installing required libs and changing `ANDROID_HOME`. The experiment couldn't be clean then.

**Comment by Cheesebaron** [comment]
I don't think this matters at all, because the Android SDK is not the issue.

**Comment by Cheesebaron** [comment]
Seems like this can be closed
