### ISSUE TITLE
Canceled builds don't go away Projects dashboard

### ISSUE THREAD

**Issue by vors** [appveyor/ci#145]
Few canceled builds stick on project page (https://ci.appveyor.com/projects) forever:

![image](https://cloud.githubusercontent.com/assets/816680/6222179/12b139da-b604-11e4-9374-3f3769fa6ba1.png)

Above (yellow) is the current build for first project.
Below (green) is the last build of the second project.

Builds in a red rectangle should not be visible on this dashboard.

**Comment by FeodorFitsner** [comment]
Have you cancelled them by clicking "Cancel"? I see they are "queued".

**Comment by vors** [comment]
Yes, I canceled them by clicking 'Cancel'. They are freeze in "Queued" state after that. I canceled them, when they where in "Queued" state.

**Comment by FeodorFitsner** [comment]
OK, have you tried cancelling them again? Are there any errors in browser's developer console? Try doing CTRL + F5 to see if their status has changed.

**Comment by vors** [comment]
Yes, in dev console I see `DELETE https://ci.appveyor.com/api/builds/DSC-Solutions/<my-project>/undefined 500 (Internal Server Error)` when I hit Cancel again.

**Comment by FeodorFitsner** [comment]
OK, I see. The version is empty. What kind of repo is that? Are you updating build details from build worker by chance?

**Comment by FeodorFitsner** [comment]
Looks like some sort of racing condition in `Fix paths` case. The one with `Pending...` is more interesting. Look like it was started by hitting generic "git" webhook. Can you recall - have you started it through UI or by pushing changed to git repo?

**Comment by vors** [comment]
It's VSO git repo. It was triggered by pushing changes.
It actually probably relate to #142: VSO hook triggers the build, but appveyor cannot retrieve details (i.e. `appveyor.yml`) from VSO, because it doesn't have token.

**Comment by vors** [comment]
Can you, please, clean up these two build for our project?

**Comment by FeodorFitsner** [comment]
Done.

**Comment by vors** [comment]
I still see them in UI :(

**Comment by FeodorFitsner** [comment]
What's the name of the project?

**Comment by vors** [comment]
I will send you details by email.

**Comment by FeodorFitsner** [comment]
...and I don't see them as pending
