### ISSUE TITLE
VS2017 Image missing "Reference Assemblies" for Xamarin targets

### ISSUE THREAD

**Issue by olevett** [appveyor/ci#1456]
On the VS2015 images, under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework` there are some targets for Xamarin (MonoAndroid, MonoTouch, Xamarin.iOS etc) but these are missing on the VS2017 images. On my local machine (Windows 10, VS2017 relatively recent install) I've got the relevant targets, but I'm not entirely certain where they come from.

VS2017 image
![image](https://cloud.githubusercontent.com/assets/8627917/24478788/1be31f4c-14d4-11e7-9ed0-4bdc19188eac.png)

Local install
![image](https://cloud.githubusercontent.com/assets/8627917/24478919/cd28a9ac-14d4-11e7-901e-1db932047b36.png)

For a bit of background, I'm currently attempting to move ReactiveUI onto VS2017 projects, but it relies on building events from all the reference assemblies, so them not being there is a bit of an inconvenience.

**Comment by olevett** [comment]
I think, but I'm not certain, these come with the "Xamarin" standalone installer (https://dl.xamarin.com/installer/XamarinInstaller.exe) which appears to be present on 2015 but not 2017.

**Comment by onovotny** [comment]
You don't need the XamarinInstaller on 2017--they're packaged differently there. With VS 2017, they need to make sure the Xamarin workload is installed, but it should be?

**Comment by IlyaFinkelshteyn** [comment]
Please check `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin` folder. Also please note that if your solution works locally with VS 2017 RC, you may hit some issues on AppVeyor, where we have RTM version now.

**Comment by martijn00** [comment]
This seems to be the same issue as: https://github.com/appveyor/ci/issues/1448

**Comment by olevett** [comment]
So I've found what's mostly the same `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid` which should resolve it for me - I don't think this is quite the same as #1448 in that we can successfully build an iOS project on the 2017 images.

**Comment by onovotny** [comment]
This makes sense as VS 2017 is SxS.

**Comment by olevett** [comment]
Happy that files are somewhere and it was a case of finding them, so closing this.

Thanks for your help :)
