### ISSUE TITLE
New build, Re-build commit and cancel build buttons not visible in safari 

### ISSUE THREAD

**Issue by ap--** [appveyor/ci#146]
I can see them in chrome Version 40.0.2214.115 (64-bit), but not in safari Version 8.0.3 (10600.3.18).
This is on OSX 10.10

**Comment by FeodorFitsner** [comment]
Will take a look. Never used Safari on Mac :)

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
