### ISSUE TITLE
CMake could not find Visual Studio 2017

### ISSUE THREAD

**Issue by HarpyWar** [appveyor/ci#1462]
Why `Visual Studio 2017` template includes CMake 3.7.2 which doesn't support Visual Studio 2017?
https://www.appveyor.com/docs/build-environment/

**Comment by FeodorFitsner** [comment]
According to [CMake 3.7 release notes](https://cmake.org/cmake/help/v3.7/release/3.7.html#generators) it does support VS 2017.

**Comment by HarpyWar** [comment]
May be it supports only 2017 RC version but not the latest. 
It stops with error `The CXX compiler identification is unknown` which means that compiler is not found.

**Comment by FeodorFitsner** [comment]
Do you have a repro in a public repository?

**Comment by HarpyWar** [comment]
Yes, https://ci.appveyor.com/project/HarpyWar/pvpgn/build/1.99.7.576#L54
```
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_CXX_COMPILER could be found.
```
There is an external tool used to run cmake, and there is no direct `cmake` command in appveyor.yml.
But you can see that all works fine with that tool when used downloaded CMake 3.8.0 RC3 https://ci.appveyor.com/project/HarpyWar/pvpgn/build/1.99.7.571

Downloading takes about 20 seconds that's critical [sometimes](https://ci.appveyor.com/project/HarpyWar/pvpgn/build/1.99.7.570), because of that I want use installed CMake.

**Comment by FeodorFitsner** [comment]
We'll deploy CMake 3.8.0 RC4 to VS 2017 image: https://github.com/appveyor/ci/issues/1463

**Comment by HarpyWar** [comment]
Is update date of the image known or not yet?

**Comment by FeodorFitsner** [comment]
Should be ready by the end of today.

**Comment by brunocodutra** [comment]
Is there anything specific one has to do in order to get CMake 3.8 in the PATH? 
I still get CMake 3.7.2 as of April 5th https://ci.appveyor.com/project/brunocodutra/metal/build/job/qb1eqpml3o8pn9s2

**Comment by FeodorFitsner** [comment]
[`image` doesn't work](https://github.com/brunocodutra/metal/blob/85eba4ff19e96dfdf5583f878984f57792c23d22/appveyor.yml#L19) in environment variables matrix, should be:

    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

**Comment by brunocodutra** [comment]
Thanks for the heads up!
