### ISSUE TITLE
Trailing slash in cache entry breaks caching

### ISSUE THREAD

**Issue by xaizek** [appveyor/ci#1465]
Some time ago (around middle of last December) builds started to fail as if cached data was missing. I thought it's a temporary issue and cleared cache manually for a while (it's very inconvenient, by the way), but the issue is still there.

Quick examination of restored directories has shown that for cache item like `src/cached/` AppVeyor creates `src/cached/cached/` and restores all files there. My guess is that trailing slash isn't stripped during restore operation, which causes some kind of copy command to create extra directory level.

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for the catch!
