### ISSUE TITLE
Display "unknown" badge for nonexistent projects

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1468]
Original issue: https://github.com/appveyor/website/issues/280

**Comment by Arcanemagus** [comment]
Looks like this will also fix https://github.com/appveyor/ci/issues/1288.

**Comment by FeodorFitsner** [comment]
An update displaying "unknown" has been deployed.

**Comment by Arcanemagus** [comment]
Thanks! I'm still seeing the JSON in the original example, but I'm guessing that's a caching issue that will resolve itself.

**Comment by FeodorFitsner** [comment]
Well, looks like there is still an issue. Will fix that today.

**Comment by FeodorFitsner** [comment]
Fixed.
