### ISSUE TITLE
Add windows ddk to appveyor image

### ISSUE THREAD

**Issue by KangLin** [appveyor/ci#1471]
DDK is not installed when compiling the driver.  pre-installed ddk to appveyor image?

**Comment by FeodorFitsner** [comment]
Can you please drop a download link to that?

**Comment by KangLin** [comment]
https://msdn.microsoft.com/en-us/library/windows/hardware/ff557573(v=vs.85).aspx

**Comment by FeodorFitsner** [comment]
WDK 10 is already installed on `Visual Studio 2015` image: https://www.appveyor.com/docs/build-environment/#visual-studio-2015

**Comment by Rondom** [comment]
This is identical to #1554.
