### ISSUE TITLE
InnoSetup 5.5.9

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1477]
http://www.jrsoftware.org/isinfo.php

Installation location on build workers: `C:\Program Files (x86)\Inno Setup 5`

**Comment by Jaex** [comment]
Currently [NSIS](http://nsis.sourceforge.net/Main_Page) and [WiX](http://wixtoolset.org/) is pre installed: https://www.appveyor.com/docs/build-environment/#pre-installed-software

Inno Setup is even more widely used then those installers I think, at least in open source projects.
