### ISSUE TITLE
Visual Studio 2017 update - version 15.1 (26403.00)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1478]
Release notes: https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

**Comment by ifarbod** [comment]
May not be the right place for it but, Does this includes the 15063 SDK too? I mean like, will it be installed by default?

**Comment by FeodorFitsner** [comment]
Yes, it will be installed on the image.

**Comment by PinpointTownes** [comment]
@FeodorFitsner really great news! Does that mean we can now target .NET 4.7 on AppVeyor?

**Comment by FeodorFitsner** [comment]
If it's part of 15.1 update.

**Comment by PinpointTownes** [comment]
It is, but AFAIK, it's an opt-in feature:

![image](https://cloud.githubusercontent.com/assets/6998306/24876737/16fa6c9e-1e2d-11e7-905a-3005b6e5d286.png)

**Comment by FeodorFitsner** [comment]
Is it part of [15.1.1 update](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes)? I don't see that option in 15.1.

**Comment by PinpointTownes** [comment]
It was introduced with 15.1 and requires Windows 10 Creators Update (it's not yet available on older OS).

**Comment by FeodorFitsner** [comment]
I see. [Announcement](https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/) says .NET 4.7 will be available for other OSes "pretty soon".

Added a new issue for .NET 4.7 installation: https://github.com/appveyor/ci/issues/1488

**Comment by PinpointTownes** [comment]
> Added a new issue for .NET 4.7 installation: #1488

Thanks, I'll track this ticket.

> Announcement says .NET 4.7 will be available for other OSes "pretty soon".

FYI, "pretty soon" means a few weeks:

> It is weeks. More than 3, less than 10 and hopefully closer to the first number. We have some quality-related process to still go through to get the release ready. This week’s release was one Windows version. We now have to get the product ready to ship for nearly over a dozen different variations.

**Comment by kzu** [comment]
How about the "plain" 15.1 VS2017 update? (even without .NET 4.7, it would be useful to pick up MSBuild fixes)
