### ISSUE TITLE
Latest git-for-windows snapshot fixes 2.12 regression with path casing

### ISSUE THREAD

**Issue by asottile** [appveyor/ci#1483]
See https://github.com/git-for-windows/git/issues/1106

Not sure if appveyor runs snapshots in build workers but figured I'd mention that this bug gets fixed with whatever version gets released next

**Comment by FeodorFitsner** [comment]
Git 2.12.2(2) is scheduled for installation during the next update: https://github.com/appveyor/ci/issues/1482

**Comment by asottile** [comment]
Awesome! I'll follow that and close this
