### ISSUE TITLE
Add Windows 10 Creators Update SDK for C++

### ISSUE THREAD

**Issue by xoofx** [appveyor/ci#1485]
Hi there,
Would it be possible to add the Windows 10 Creators Update SDK C++ to the Visual Studio 2017 image?

It is part of this setting in the VS2017 installer (but not activated by default):

![windows10sdkcpp](https://cloud.githubusercontent.com/assets/715038/24852727/d742d252-1dd8-11e7-9365-6165872621ef.png)

Thanks!

**Comment by ifarbod** [comment]
It's a part of #1478, I mentioned it there. :)

**Comment by FeodorFitsner** [comment]
The image has been updated.

**Comment by xoofx** [comment]
Amazing, thanks!
