### ISSUE TITLE
.NET Framework 4.7 support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1488]
Add .NET Framework 4.7 support as soon as it's available for Windows Server platform.
Announcement: https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/

**Comment by onovotny** [comment]
@FeodorFitsner Can you install the targeting pack in VS 2017 / 15.1? It should be an optional install there now. That and the Creators Update SDK.

**Comment by FeodorFitsner** [comment]
It's not yet available for Windows Server 2016. Will be "pretty soon" according to [the announcement](https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/) - I guess it might be weeks.

**Comment by FeodorFitsner** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/05/02/announcing-the-net-framework-4-7-general-availability/

**Comment by CDAGaming** [comment]
@FeodorFitsner Seems it is rolling out at this time, has started initial rollout 3 days ago

**Comment by CDAGaming** [comment]
http://go.microsoft.com/fwlink/?LinkId=825319 - Dev/Targeting Pack
http://go.microsoft.com/fwlink/?LinkId=825299 - Runtime/Public

**Comment by FeodorFitsner** [comment]
Installing [Microsoft .NET Framework 4.7 Developer Pack](https://www.microsoft.com/en-us/download/details.aspx?id=55168). However, looks like [.NET Framework 4.7 development tools](https://msdnshared.blob.core.windows.net/media/2017/04/VS2017-dotnet47-install-1024x535.png) option in VS 2017 is only available on Windows 10 Creators Update.

**Comment by CDAGaming** [comment]
Wasn't really what Microsoft had said before, which was you had just needed the current version of VS2017, and a supported OS for .net 4.7

**Comment by FeodorFitsner** [comment]
Yep, this is frustrating. However, I'm wondering if you still can build against .NET 4.7 on Server 2016 even if you can'd develop in VS 2017. We'll see when a new VS 2017 image update is available.
