### ISSUE TITLE
Visual Studio 2017 regression: UWP build error scale-100.appx not found

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1489]
Original report: http://help.appveyor.com/discussions/problems/6461-uwp-vs2017-build-error-scale-100appx-not-found
Solution: http://stackoverflow.com/questions/43246485/visual-studio-2017-and-windows-10-sdk-10-0-15063-scale-100-appx-not-found
Original source of solution: https://developercommunity.visualstudio.com/content/problem/40376/error-file-csomepathbinarmreleaseapp-112180-scale.html?childToView=40706#comment-40706

AppVeyor workaround - add this to `appveyor.yml`:

```yaml
install:
- ps: (New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/appveyor/ci/master/scripts/hot-fixes/vs2017-uwp-scale-100-fix/Microsoft.AppxPackage.Targets', "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppxPackage.Targets")
```

**Comment by Thealexbarney** [comment]
​It looks like this was fixed with patch 26403.7
