### ISSUE TITLE
"Re-build" button

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#15]
http://help.appveyor.com/discussions/suggestions/393-retry-build-button-network-errors

**Comment by tcr-ableton** [comment]
Hi @FeodorFitsner this ticket has been closed, however you did not mention the status of this feature. Is it implemented yet? 

Cheers

**Comment by gep13** [comment]
Is this what you are looking for:

![image](https://cloud.githubusercontent.com/assets/1271146/10601715/64a8aaf2-770b-11e5-82b6-b90014bd4922.png)

On any commit, you have the option of starting a new build, or rebuilding the same commit.

**Comment by tcr-ableton** [comment]
@gep13 kind of! But is there a way to automate retries through the appveyor.yml declaration file? Like ``travis-retry`` previously mentioned?

**Comment by gep13** [comment]
@tcr-ableton nothing that I am aware of, no.  But I think that this would be a separate issue.  This issue seemed to be focusing on implementing the ability in the AppVeyor UI, not in the yml file.

**Comment by tcr-ableton** [comment]
@gep13 Should I open a new issue then? We need this feature very bad.

**Comment by gep13** [comment]
@tcr-ableton you might want to start the discussion here:

http://help.appveyor.com/

As there might already be something in place, but @FeodorFitsner would be the best person to answer that question.

**Comment by FeodorFitsner** [comment]
You can use this script as an example for creating universal re-try script: https://github.com/appveyor/ci/blob/master/scripts/nuget-restore.cmd

**Comment by fommil** [comment]
where is this button? I am logged in and cannot see it. I go the long way and re-send the webhook payload, which is not very convenient.

**Comment by FeodorFitsner** [comment]
What buttons do you see in build details page - could you drop a screenshot please?

**Comment by fommil** [comment]
Agh, I just left the house. I'll try to do this tonight.

**Comment by fommil** [comment]
ok, buttons definitely there. Sorry for the noise.

**Comment by george-polevoy** [comment]
When running the new build command, it always builds master (default branch) even if its not in the 'build only following branches list'

When running the rebuild command, it uses the old settings.

Honestly - rewrite this feature from scratch, its unusable.

**Comment by george-polevoy** [comment]
My bad, the build settings are updating fine.

**Comment by gaearon** [comment]
I can't find the Rebuild button.

Commit: https://github.com/facebookincubator/create-react-app/pull/1402/commits/d981198f1077878268ee207feb7134ab49e57ca4

Build: https://ci.appveyor.com/project/Facebook/create-react-app/build/1.0.102

<img width="1021" alt="screen shot 2017-03-05 at 3 07 46 pm" src="https://cloud.githubusercontent.com/assets/810438/23588444/853582a0-01b5-11e7-8593-df4719038ef2.png">

Individual test:

<img width="1018" alt="screen shot 2017-03-05 at 3 08 05 pm" src="https://cloud.githubusercontent.com/assets/810438/23588450/93a073a4-01b5-11e7-8b46-89936d764021.png">

Where can I find the rebuild button?

**Comment by FeodorFitsner** [comment]
You either don't have enough permissions to manage that project or should re-login to "Facebook" account.

**Comment by gaearon** [comment]
Thanks for explaining. I was confused because I thought I saw settings at some point, but it turned out that I saw them in my fork's CI.

**Comment by rmmh** [comment]
One way to trigger a rebuild if you're not an owner on the project is to close and reopen your PR.

**Comment by IlyaFinkelshteyn** [comment]
@rmmh, right but adding [user](https://www.appveyor.com/docs/team-setup/#user) or [collaborator](https://www.appveyor.com/docs/team-setup/#collaborator) with [role](https://www.appveyor.com/docs/team-setup/#role) which has `Run project builds` [permission](https://www.appveyor.com/docs/team-setup/#permissions) seems like a better approach.
