### ISSUE TITLE
Report latest PR status when build is skipped with ``[skip ci]``

### ISSUE THREAD

**Issue by bsipocz** [appveyor/ci#1503]
Currently one receives a potentially false "green" build status on GH if the latest commit has the skip string in its commit message.

E.g. and otherwise failing build is getting the all green here https://github.com/astropy/astroquery/pull/887 as the last commit had ``[skip ci]`` in an otherwise too long message, so none of the maintainer spotted the issue before merging the PR.

**Comment by IlyaFinkelshteyn** [comment]
@bsipocz AppVeyor does not write build status on skipped build at all. I am not sure I can find "green" build which was skipped by AppVeyor. Potentially it can happen if some other CI service/services set build to "green", while AppVeyor does not set any status. I do not believe we can do much in this situation, we assume that `[skip ci]` is set for a reason.

**Comment by bsipocz** [comment]
Yes, that may be it, but when all CIs are skipped a PR is almost always green. Would you consider having an option in setting that would make  commit inherit the last build status (is exists) on a given branch? It can be a bit of a headache for maintainers when contributors use ``[skip ci]`` sometimes randomly. 
(I already have asked about this issue from github support, but they were very firmly sent me to talk to the CIs instead...)

**Comment by IlyaFinkelshteyn** [comment]
Could you please send me link to "green" commit with all CIs skipped?
I do not feel that it is right for us to set any CI status is CI itself does not happen, we have no rights to assume...
Also I wonder where how `[skip ci]` appear in message? This most probably mean people **do** want to skip CI for some reason, right?

**Comment by IlyaFinkelshteyn** [comment]
@bsipocz We talked about this more and maybe this scenario indeed can allow untested commits. We are thinking that we might need to implement UI option to "never skip commits for PR".  But I still cannot reproduce this issue. I created simple PR with first commit with happy build and second commit with `[skip ci]` and it does not have status and not "green". Please check PR named `Goof PR1` [on my test project](https://github.com/IlyaFinkelshteyn/ProjectA/pulls). We would really appreciate if you can help us with step-by-step repro.

**Comment by bsipocz** [comment]
@IlyaFinkelshteyn - Thanks for picking up this request.

I think the following PR is a good example: https://github.com/astropy/astroquery/pull/887

It has three commits, the last one (https://github.com/astropy/astroquery/pull/887/commits/8844849a6605bd465f26f4ff8341d4ab31277fa9) only adds a changelog entry, thus the committer added the ``[skip ci]``. However it was done while CI was still running for the previous commit, thus no one noticed that the real status of the PR is still failing as GH used the status of the last commit (without CI).

In this scenario what I would prefer is that the status is set based on the CI results of the last run. If there is no CI run on that branch, well, then the current behaviour is OK. 

"never skip commits for PR" is still not ideal, as it would potentially waste CI time, as the commit above indeed didn't needed to be tested.

**Comment by bsipocz** [comment]
(obviously I suggest this to be opt in, rather than default if that clears up some concerns.)

**Comment by FeodorFitsner** [comment]
You may want to look at [protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks) where you can "require" certain status checks.

**Comment by bsipocz** [comment]
Thanks for the tip. We use protected branches in another repo, and it's a real pain and it's not practical at all for this repo. Among others, it gives a grey, non-clickable merge button that totally disallows trivial PRs merged asap, and it also disable direct pushes to master (rarely, but we rely on it for e.g. when doing a release).
