### ISSUE TITLE
Question: Possible to get last known deployment when using inline deployment?

### ISSUE THREAD

**Issue by ctolkien** [appveyor/ci#1505]
Scenario is I'm trying to get the commit id from the last known deployment so that I can `git log` between it and the currently running build and in the scenario that it is _also_ a deployment, I can update our project management tool with the list of commits that were included in the last deployment.

Via the API, all the 'deployment' fields seem to be blank if using `inline deployment`. This looks like it would be possible with an `Environment Deployment` as there are specific API calls for that, but I'd rather not move to that scenario (prefer to keep all config in the appveyor.yml).

**Comment by IlyaFinkelshteyn** [comment]
Right, this is not exposed in our API right now. Please consider the following (not ideal) workaround:

- add some specific message as part of **after deploy** script using [build worker API](https://www.appveyor.com/docs/build-worker-api/#add-message) 
- Iterate through [project history](https://www.appveyor.com/docs/api/projects-builds/#get-project-history), looking for specific message for each **successfull** build job with the following API endpoint: `https://ci.appveyor.com/api/buildjobs/<jobId>/messages`
- return `commitId` from the first job with specific message found. [Project history](https://www.appveyor.com/docs/api/projects-builds/#get-project-history) is sorted chronologically, so first found should be last known good deployment. 

Do you believe this might work for you?

**Comment by ctolkien** [comment]
That's the scenario I've built and it feels like a bit of a hack - just figured I'd ask if there were a better option :)

**Comment by IlyaFinkelshteyn** [comment]
Filed https://github.com/appveyor/ci/issues/1511 to track this
