### ISSUE TITLE
Dotnet core project fails to build

### ISSUE THREAD

**Issue by godrose** [appveyor/ci#1506]
The following error is displayed:
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk

**Comment by IlyaFinkelshteyn** [comment]
Please check [this](https://github.com/appveyor/ci/issues/1377#issuecomment-287644271) post.

If it does not help please provide more information:
- What kind of project is it? Classic .NET or .NET Core one?
- What Visual Studio version this project is being developed in?
- Does it builds locally OK with command line? If yes, what command line tool -- `msbuild`, `dotnet`?
- What AppVeyor build worker image is used?
- Build configuration in YAML format and full build log will help too.

**Comment by godrose** [comment]
Will check the link.
For now the answers for your questions:

1.  .NET Core

2. VS 2015 Update 3

3. Yes, with dotnet

4. I haven't modified anything beyond the default options.

5. Attached the yaml and build log files.

Yaml:
configuration: TestsWithFake

before_build:
- nuget restore

build:
  verbosity: minimal
  
notifications:
- provider: Email
  to:
  - gennady.verdel@logoui.co.il
  - david@logoui.co.il
  - dmitry.bublik@logoui.co.il
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

Build Log:

[log (1).txt](https://github.com/appveyor/ci/files/949472/log.1.txt)

**Comment by FeodorFitsner** [comment]
Take a look at this comment with the fix: https://github.com/appveyor/ci/issues/1377#issuecomment-287644271

**Comment by godrose** [comment]
@FeodorFitsner Thanks. The first suggestion with global.json did the trick.
