### ISSUE TITLE
Artifacts: set content-disposition to instruct the browser about the filename

### ISSUE THREAD

**Issue by domenkozar** [appveyor/ci#1507]
Weird issues can arise at the moment when one tries to download a file from appveyor artifacts tab.

Mainly, the file could be named differently and end up with stripped extension in users folder.

I recommend you set `Content-Disposition: attachment; filename="$filename.pdf` header when downloading files.

**Comment by IlyaFinkelshteyn** [comment]
We actually doing this, could you please send us specific example? Maybe we missed it in some scenario we did not think about...

**Comment by domenkozar** [comment]
I don't see `Content-Disposition` in the output of:

```
$ curl -v https://ci.appveyor.com/api/buildjobs/xdvo3a0wxi3obyak/artifacts/installers%2Fdaedalus-win64-0.3.1218.0-installer.exe
```

The reason this is biting us is Internet Explorer tripping `.exe` suffix. The bug is explained in http://stackoverflow.com/questions/2185570/internet-explorer-removes-exe-extension-from-download-when-followed-by-url-para together with one possible workaround.

**Comment by FeodorFitsner** [comment]
Right, it's because they are stored in Azure blob storage. Our artifact link is just a redirect. Will take a look what can be done to add Content-Disposition header there.

http://www.devtrends.co.uk/blog/fixing-azure-blob-storage-content-disposition

**Comment by domenkozar** [comment]
Thanks @FeodorFitsner, let me know when you have the fix and I'll help test.

**Comment by domenkozar** [comment]
@FeodorFitsner any status update? I'm fine it this won't hit May 7th deadline, just so we know if we need to implement workarounds.

**Comment by FeodorFitsner** [comment]
Still working on that. This is going to be deployed next week, sorry for the delay.

**Comment by domenkozar** [comment]
@FeodorFitsner does this mean the issue is fixed?

**Comment by IlyaFinkelshteyn** [comment]
@domenkozar I remember Feodor worked on it and even checked something in :)

**Comment by FeodorFitsner** [comment]
It should be added to new artifacts only.

**Comment by domenkozar** [comment]
Thanks!

**Comment by jcsteh** [comment]
The Content-Disposition header is now indeed being set. However, it breaks when there are commas (and probably other characters) in the file name. For example, for this artifact:
https://ci.appveyor.com/api/buildjobs/h2o3o551nqtaquix/artifacts/output/nvda_snapshot_next-14089,7a46f9b3.exe
The header is as follows:

> `Content-Disposition: attachment; filename=nvda_snapshot_next-14089,7a46f9b3.exe`

This causes the following error in Chrome:

> This page isn’t working
> appveyorcidata.blob.core.windows.net sent an invalid response.
> ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

The file name should be quoted so that commas, etc. (as permitted by [RFC 6266](https://tools.ietf.org/html/rfc6266#section-4.1) are included in the value and not treated as part of the header syntax.

**Comment by FeodorFitsner** [comment]
Will fix that, thanks for the catch.
