### ISSUE TITLE
.NET Core SDK 1.0.1 and 1.0.3 on Visual Studio 2017 image should be pre-cached

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1508]
Discussion: http://help.appveyor.com/discussions/problems/6516-dotnet-command-unpacking-on-vs2017-image

**Comment by casperOne** [comment]
What versions are you planning on preheating?

I ask because the tooling (global.json) should dictate the version of the CLI tools if you have it installed.

I'm currently using `1.1.0-preview1-001100-00` (that's the latest supported on Azure), but others may want to use different versions.

**Comment by FeodorFitsner** [comment]
Is `1.1.0-preview1-001100-00` available for download?

**Comment by casperOne** [comment]
Create a global.json in a directory like so:

```
{
	"sdk": {
		"version": "1.1.0-preview1-001100-00"
	}
}
```

And run `dotnet`.  It will download automatically.

This is probably the procedure you'll want to run in order to prime the image whenever you want a new version to be pre-loaded.

**Comment by FeodorFitsner** [comment]
Is it officially announced somewhere?

**Comment by casperOne** [comment]
Oddly enough, I can't find it on my machine.  I have 1.0.1 -> 1.0.3, as well as some preview builds, but not *that* specific version.

In my case, I wouldn't expect it to be pre-heated; the main point was about the freedom we have with global.json indicating the CLI version (and the variance as a result).

If I specified 1.0.3 (for a self-contained deployment), then I'd hope this is pre-warmed on the machine.

**Comment by FeodorFitsner** [comment]
The list of pre-installed .NET Core per image is here: https://www.appveyor.com/docs/build-environment/#net-framework

**Comment by casperOne** [comment]
This certainly will sate most not publishing to Azure.

But I imagine you have a large number of consumers publishing to Azure.

Not necessary for the preview version that I pointed out, but would probably benefit a good number of people.

The Kudu/Azure GitHub repos may be the place to ask about the CLI versions in Azure.
