### ISSUE TITLE
Build cache save failure should not affect build status

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1509]

**Comment by IlyaFinkelshteyn** [comment]
Discussions:
http://help.appveyor.com/discussions/problems/6512-build-cache-errors
http://help.appveyor.com/discussions/problems/6509-when-the-cache-server-is-down-the-whole-build-fails

**Comment by robertbell** [comment]
Did this actually get fixed? I run into this issue often.

**Comment by IlyaFinkelshteyn** [comment]
@robertbell can you provide an example? We need `appveyor.yml` (or result of `Export YAML` if you use UI) and link to the problem build.

**Comment by JeremyTCD** [comment]
@IlyaFinkelshteyn 

Hello, I've just encountered the same issue: [appveyor.yml](https://github.com/JeremyTCD/WebUtils.SyntaxHighlighters.Prism/blob/master/.appveyor.yml) and the [build](https://ci.appveyor.com/project/JeremyTCD/webutils-syntaxhighlighters-prism/build/5). Is there any way to work around this issue other than by disabling caching?
