### ISSUE TITLE
Image doesn't seem to change if switching from web interface

### ISSUE THREAD

**Issue by daveaglick** [appveyor/ci#1510]
I was using the Visual Studio 2015 image and recently switched to the Visual Studio 2017 image from the web interface. This has worked fine for other projects of mine. However, something must have been different in one of my projects because after changing the image the build was still using MSBuild 14 (presumably because it was still building with the old image). I had to add the following line to my `appveyor.yml` as well (which wasn't in my original file):

```
image: Visual Studio 2017
```

Once I did that I presume the image actually changed because it found the correct MSBuild 15 tooling.

**Comment by IlyaFinkelshteyn** [comment]
Ah, this is expected. We have number of [build worker images](https://www.appveyor.com/docs/build-environment/#build-worker-images), and not every one of them has VS 2017 installed. It is really painful and non-practical to have everything installed side by side on single VHD. 
We cannot switch build worker image during the build (as VM already created when VS solution is being parsed), but maybe we need more meaningful error if current build worker image is not suitable for current solution...

**Comment by daveaglick** [comment]
Ah, I see - and further I think I was getting caught up in this:

> Please note that appveyor.yml has precedance over UI settings, so when appveyor.yml exists the image should be specified in YAML, not on UI.

Since I had a YAML configuration file, the web UI setting must not have been "taking".
