### ISSUE TITLE
Prebuilt LLVM 4.0 x64 library support

### ISSUE THREAD

**Issue by rongjiecomputer** [appveyor/ci#1518]
Prebuilt LLVM library in `C:\Libraries\llvm-4.0.0` is x86, but I need x64 library.

```
fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64
```

Related to #1284

**Comment by FeodorFitsner** [comment]
What would be build steps for x64 version?

**Comment by rongjiecomputer** [comment]
This should build x86 and x64 binaries together.

```
C:\Users\appveyor\Downloads\llvm-4.0.0.src\build>cmake -G "Visual Studio 14 2015" ^
-DCMAKE_BUILD_TYPE=RELEASE -DLLVM_TARGETS_TO_BUILD=X86;AArch64 ^
-DCMAKE_INSTALL_PREFIX=C:\Users\appveyor\Downloads\llvm-4.0.0.build ..
```

**Comment by FeodorFitsner** [comment]
Thanks, will look into that!

**Comment by rongjiecomputer** [comment]
@FeodorFitsner I tried to build LLVM locally to help you.

`-DLLVM_TARGETS_TO_BUILD=X86;AArch64` is incorrect. `-DLLVM_TARGETS_TO_BUILD=X86` alone is enough to produce LLVM binaries that can generate x86 and x86-64 code, but you can't build the x86 and x86-64 LLVM libraries itself together.

The solution is to build x86 libraries and x86_64 libraries separately with different install path prefix.

CMake configuration for x86

```
C:\Users\appveyor\Downloads\llvm-4.0.0.src\build>cmake -G "Visual Studio 14 2015" ^
-DCMAKE_BUILD_TYPE=RELEASE -DLLVM_TARGETS_TO_BUILD=X86 ^
-DCMAKE_INSTALL_PREFIX=C:\Users\appveyor\Downloads\llvm-4.0.0-x86.build ..
```

CMake configuration for x86_64.

```
C:\Users\appveyor\Downloads\llvm-4.0.0.src\build>cmake -G "Visual Studio 14 2015 Win64" ^
-DCMAKE_BUILD_TYPE=RELEASE -DLLVM_TARGETS_TO_BUILD=X86 ^
-DCMAKE_INSTALL_PREFIX=C:\Users\appveyor\Downloads\llvm-4.0.0-x86_64.build ..
```

**Comment by marco-c** [comment]
@FeodorFitsner are there both x86_64 and x86 libraries available? In `C:\Libraries\llvm-5.0.0` there are the x86_64 ones, where are the x86 ones?

**Comment by FeodorFitsner** [comment]
There are only x86_64.

**Comment by marco-c** [comment]
> There are only x86_64.

OK, I've filed https://github.com/appveyor/ci/issues/2258.
