### ISSUE TITLE
Boost 1.64

### ISSUE THREAD

**Issue by ekmett** [appveyor/ci#1520]
Boost 1.64 was recently released.

It finally includes support for MSVC 2017.

This means it could actually install in the Visual Studio 2017 target, and this would let folks who are on the bleeding edge actually run boost code without jumping through complex hoops to install it themselves or to lie to old versions of boost to trick them into compiling on MSVC 2017.

**Comment by FeodorFitsner** [comment]
Sure, will look into that!

**Comment by mloskot** [comment]
Would there be any update?

**Comment by jschueller** [comment]
they added it for vs2017, but not vs2015: https://www.appveyor.com/docs/build-environment/#boost
