### ISSUE TITLE
Java 8 build 

### ISSUE THREAD

**Issue by thomasmodeneis** [appveyor/ci#1521]
Hi,

I'm trying to create a build for a opensource project that uses JDK 8 and Maven.
This is the build
https://ci.appveyor.com/project/thomasmodeneis/soujava-test-kit

Any ideas how can I get this sorted ?

Cheers.

**Comment by IlyaFinkelshteyn** [comment]
By default AppVeyor automatically builds .NET solutions and projects. For other frameworks people use custom build scripts. If you search GitHub for `appveyor.yml maven`, you can find a lot of examples how people do that.

**Comment by XhmikosR** [comment]
@IlyaFinkelshteyn  this can be closed.
