### ISSUE TITLE
Rolling builds are not useful for active and long-running OSS projects.

### ISSUE THREAD

**Issue by EricWF** [appveyor/ci#1529]
For OSS projects with frequent commits and long build times the "Rolling Builds" option is not useful. For example say a single commit takes ~60 minutes to build, but the project averages more than one commit per hour. This results in a build that never completes and never reports failure or success, but instead is perpetually interrupted. This behavior is not useful for detecting and isolating new build/test failures.

I think the original behavior described in Issue #38 by @FeodorFitsner is greatly preferable to the current behavior:

> There is an idea of "rolling" builds, so the system do not start a new build for each commit, but waits until the build is completed and then queues another build of all check-ins that have not yet been built. This could be done per-branch.

Rolling builds should not cancel current builds. It should only cancel and stack queued commits. (Note that queued configurations for a currently building commit should not be canceled)

This makes a significant usability difference for big and busy OSS projects. For example say a project `P` averages a commit every 10 minutes during a ~10 hour work day period, so roughly ~60 commits a day, and a build takes one hour to complete. 

With the current Rolling Build semantics only one build will complete during the work day. Failures caused by commits at the beginning of the day will only be reported ~10 hours later, and the blamelist will contain all 60 commits.

With the suggested semantics 10 builds will complete during the day. Failures will be reported within an hour and the blamelist will average ~6 commits.

Note that without rolling builds the builder cannot keep up building all 60 commits in a day.

PS. The project I have in mind is LLVM and its subprojects including Clang and Libc++, the last of which I'm working on setting up bots for. Clang/LLVM builders may come later if I can get everything working. Thank you for this amazing service.

**Comment by FeodorFitsner** [comment]
Hi Eric,

Thanks for your thoughts! I think you are describing a valid scenario. Looks like we need additional `Do not cancel running builds` option for "rolling" builds. Look at this discussion about the issue: http://help.appveyor.com/discussions/problems/586-cancel-queued-builds-for-old-commits-of-the-same-branch#comment_42495777

**Comment by tkelman** [comment]
In Julia we've been using this snippet
```
# If there's a newer build queued for the same PR, cancel this one
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
throw "There are newer queued builds for this pull request, failing early." }
```
since before rolling builds were an option to fast-fail superseded PR builds. It takes less than a minute for the VM to spin up and get to this bit of code. This specifically applies only to pull requests as written, but should be adaptable to branch builds without too much trouble.

**Comment by EricWF** [comment]
@FeodorFitsner May 7th milestone? Amazing Thank you!

**Comment by FeodorFitsner** [comment]
It's been deployed:

![image](https://cloud.githubusercontent.com/assets/5041459/25785807/0c086ad6-333e-11e7-9c50-76454d43526f.png)

**Comment by EricWF** [comment]
It's working great! Thank you.
