### ISSUE TITLE
Update Chocolatey to 0.9.8.33

### ISSUE THREAD

**Issue by gep13** [appveyor/ci#153]
Currently, version 0.9.8.27 of Chocolatey is installed on the Build Worker image.  Any chance of getting this updated to the latest version, which is 0.9.8.33?

Cheers!

**Comment by FeodorFitsner** [comment]
Sure, will deploy next week.



-Feodor

**Comment by gep13** [comment]
:+1:

**Comment by ferventcoder** [comment]
:+1:

**Comment by gep13** [comment]
@FeodorFitsner Chocolatey 0.9.9.1 was released the other day, however, you might not want to install this one quite yet.  There are a number of changes, that some automated build scripts (which is likely what is running on AppVeyor) are not ready for.  Perhaps only install 0.9.8.33, and then send out an email to your users, explaining when 0.9.9.1 is going to be installed, and then point them at the release notes for the latest chocolatey, where it explains what has changed, and what they will need to look out for:

https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#099-march-3-2015

**Comment by FeodorFitsner** [comment]
Wow, this is bold! Thanks for the heads up!




Now I'm wondering how to install that specific 0.9.8.33 version of Chocolatey?



-Feodor

**Comment by gep13** [comment]
Got you covered...

https://github.com/chocolatey/chocolatey.org/issues/162

**Comment by FeodorFitsner** [comment]
Nice, thank you!



-Feodor

**Comment by gep13** [comment]
Noice one, thank you :-)
