### ISSUE TITLE
YAML validator doesn't finish if the configuration is a sequence and contains syntax errors

### ISSUE THREAD

**Issue by mknejp** [appveyor/ci#1535]
The following string inserted into https://ci.appveyor.com/tools/validate-yaml makes the validation never finish:
```
- configuration Release
```
Note that it's a syntax error as the colon after `configuration` is missing. This seems to only affect YAML files where the root object is a sequence, as the following is correctly reported as an error:
```
configuration Release
```

It only seems to affect syntax errors as the following string is processed correctly:
```
- blaa: Release
```

**Comment by FeodorFitsner** [comment]
Thanks for the catch! Will be fixed in the next update.
