### ISSUE TITLE
Deploy to multiple environments at once

### ISSUE THREAD

**Issue by guidobouman** [appveyor/ci#1536]
We would like to be able to deploy a build to certain groups of deploy targets.

Our projects often consist of multiple deploy targets. Individually deploying to each get annoying really fast. We would like to configure deployment groups, for environments that are linked together. Development, testing, acceptance & production are some of our environments. Each environment has a site, api, cms and sometimes a fourth project we can deploy to.

Duplicate this yet again for production, where we deploy to multiple CDN regions. Deploying to 6 (3*2) targets when we go to production is already cumbersome. When we have 4 projects, and use 4 CDN edges this suddenly becomes 16 targets.

Creating groups where we can deploy a build to, would make our lives a lot easier.

**Comment by guidobouman** [comment]
@FeodorFitsner Stressing the importance of this issue.

**Comment by FeodorFitsner** [comment]
Yeah, thanks! Let's discuss that a little.

Can you give more concrete example of how you'd configure those "groups" from user perspective and in AppVeyor terms (if possible) and then how deployment process would look like? How do they related to current "deployment environments"?

**Comment by guidobouman** [comment]
Thanks for getting back to me so quickly.

The groups could quite simply be arrays of existing deployment environments. That way we can instantiate a single deploy to a group of deployment environments.

I assume they would all start the deploy in parallel. Adding things like deploying in a specific sequence or waiting for deployment results before doing another deployment is something of a whole different issue if you ask me.

This feature could be rather small, but a great improvement in our workflow. A small comparison below.

Deploying usually requires us to:
- Select a build we want to deploy. (1 click)
- Duplicate tabs or copy-paste URLs. (4*2 = 8 clicks)
- Select each deployment environment individually in each tab. (4*2 = 8 clicks)
- Then check that all environments are the same. (4 clicks)
- Lastly kick them off one-by-one. (4*2 = 8 clicks)

Compared to:
- Select a build we want to deploy. (1 click)
- Select the deployment environment group. (2 clicks)
- Kick off all deployments in one click. (1 click)

Totals: 29 clicks vs 4 clicks.

**Comment by FeodorFitsner** [comment]
Thanks for additional input! We'll give it more thoughts later when start working on deployment improvements later this year.

**Comment by andrewgunn** [comment]
@FeodorFitsner Any update on this?

I like the idea of groups but it seems like a quick win solution. 

Alternatively, I wouldn't mind having the concept of a Deployment which behaves similarly to a Build. They'd have a pipeline with hooks that can be configured. Keep the Environments as they are, but allow a Deployment to trigger one or more of them. This would allow you to configure post deploy steps such as database migrations too. It'd be nice if Deployments could see ALL of the artifacts from a Build. This solves the problem where a single repository has multiple artifacts (website, API, service, etc). 

This sort of behaviour is currently possible by triggering deploys to one or more Environments after a successful build. That's fine if everything goes to plan. What if one of the deployments fails, or you want to rollback to a previous version. I'd rather not trigger another build but it'd take longer and _may_ product a different artifact. 

I feel like this is the only thing that really let's AppVeyor down. The Build process has been given a lot of thought and it shows. I can't wait to see any improvements in this area.

**Comment by andrewgunn** [comment]
@FeodorFitsner... any update on this???

**Comment by danielmackay** [comment]
We would also really like this feature.  Our solution is hosted in Azure with many web jobs.  The Main website can be built and deployed.  But then we would need to configure and environment for every web job we need to deploy (which could be around 10).  Multiply this by deployments for each client and environment (staging, prod, etc).  And the number of Appveyor Environments starts to grow quick.

Any update on when environment grouping will be developed?

**Comment by FeodorFitsner** [comment]
This and other deployment-related features have high priority in our todo list. You'll see a lot of deployment flow improvements in the coming months. Thank you for your patience.

**Comment by danielmackay** [comment]
Great to hear, and thanks for the response.

**Comment by guidobouman** [comment]
Hi @FeodorFitsner nice to see that it's high on the priority list. What's the current status? Can we opt in to testing this feature anywhere? 😁Or any extra input that might help?

**Comment by IlyaFinkelshteyn** [comment]
@guidobouman  we added this to **Q2-2018** milestone, this should give you an idea about ETA. We cannot do more specific promises though...

**Comment by hflynntegna** [comment]
I feel the amount of frustration as above. In my support email, I mention that I have one project that must go to 111 environments each week, 2 regional environments and 1 stage environment for 37 sites. I can't even count the number of clicks it takes me to make this happen. Between the clicking and the refresh rate to return to the original project to start again, not to mention the potential for human error when selecting a site one at a time from a drop down of a 111 choices! This is tedious to say the least, i lose several hours to this process.

**Comment by guidobouman** [comment]
@IlyaFinkelshteyn Thanks, Q2 is already great.

A rough estimation already helps us in deciding on priorities for temporary workarounds.

**Comment by IlyaFinkelshteyn** [comment]
@guidobouman speaking of temporary workarounds, did you consider [deployment projects](https://www.appveyor.com/blog/2015/11/04/deployment-projects/)? You can create single project like this and add multiple "inline" deployments to it. But they are not going to be truly "inline" because this project will only deploy bits built before...

**Comment by Rzpeg** [comment]
It's 2019 already, any progress ?

**Comment by guidobouman** [comment]
@FeodorFitsner 2018 has passed, 2019 has passed, maybe Q1 2020?

**Comment by guidobouman** [comment]
Over 3 years, with no implementation. I'll just close this issue as it seems the product is not willing to improve. This has caused our company to migrate to Azure DevOps with all of our projects.

@FeodorFitsner Feel free to reopen if you want to actually work on this.
