### ISSUE TITLE
Some Project list UI Enhancements

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#155]
[Here's the conversation](http://help.appveyor.com/discussions/suggestions/584-project-list-enhancements) about this.
- [ ] Pin
- [ ] Orderings
- [ ] Tags

**Comment by PureKrome** [comment]
Closed - not going to implement?
Closed - partially implemented?
Closed - all implemented?

**Comment by FeodorFitsner** [comment]
"Tags" are already done.

For "pins" and "orderings" - it might more sense to create separate more atomic issues. Though they could become irrelevant as we are going to revisit "Projects" page experience later this year.
