### ISSUE TITLE
Cache with Pull Request builds

### ISSUE THREAD

**Issue by gqmelo** [appveyor/ci#1553]
I've been experimenting with caching compilation objects (```ccache```) on [conda-forge](http://conda-forge.github.io/) builds, but without pull request builds caching would not be very useful for us. 

As some builds spend most of the time compiling we could greatly benefit from caching on PR builds. 
Would it be possible to implement this feature?

**Comment by jakirkham** [comment]
Any feedback on this?

**Comment by jakirkham** [comment]
It looks like there is a project setting for this. Though I haven't really played with it yet.

**Comment by IlyaFinkelshteyn** [comment]
Oh, right, this was implemented a while ago (https://github.com/appveyor/ci/issues/1730). Sorry for missing this issue and duplication. This UI-only setting already looks like this.
![2018-01-09_16h03_47](https://user-images.githubusercontent.com/3248386/34749598-25b0833e-f557-11e7-8efa-1a1f7d5c3916.png)
Closing...

**Comment by jakirkham** [comment]
No worries. Thanks for the confirmation.

Is there an API we can use to enable this as well?

**Comment by IlyaFinkelshteyn** [comment]
Sure, here is a PowerShell script example:

```posh
$env:API_TOKEN="<replace>"
$env:APPVEYOR_ACCOUNT_NAME="<replace>"
$env:APPVEYOR_PROJECT_SLUG="<replace>"

$headers = @{
  "Authorization" = "Bearer $env:API_TOKEN"
  "Content-type" = "application/json"
}
    
$s = Invoke-RestMethod -Uri "https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/settings" -Headers $headers  -Method Get
$s.settings.saveBuildCacheInPullRequests = $true
Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects' -Headers $headers  -Body ($s.settings | ConvertTo-Json -Depth 10) -Method Put
```

**Comment by jakirkham** [comment]
Great, thanks!
