### ISSUE TITLE
Support .NET Core 2.0 Preview 1

### ISSUE THREAD

**Issue by thiennn** [appveyor/ci#1555]
It would be great if we can have .NET Core 2.0 preview 1 supported.

https://www.microsoft.com/net/core/preview

Thank you,

**Comment by FeodorFitsner** [comment]
You'll have an access to .NET Core 2.0 preview with "VS 2017 Preview" image we are going to provide soon: https://github.com/appveyor/ci/issues/1549

I'm closing this issue for now as duplicate.
