### ISSUE TITLE
Add Visual Studio 2015 Update 2 image

### ISSUE THREAD

**Issue by zemasoft** [appveyor/ci#1556]
Hi,
Can you please add Visual Studio 2015 Update 2 image for my repo https://github.com/zemasoft/tetris?
Thanks a lot.

**Comment by IlyaFinkelshteyn** [comment]
@zemasoft Done, please let us know is know if you see it now.

**Comment by zemasoft** [comment]
Yes, it is accessible for me now. Thanks.
