### ISSUE TITLE
Chocolatey 0.10.7

### ISSUE THREAD

**Issue by philippgille** [appveyor/ci#1557]
I have a build script that contains: `choco pack "$PSScriptRoot\..\chocolatey\$appName.nuspec" --out $artifactsDir`

When building locally with Chocolatey 0.10.5 everything works fine.

When building on AppVeyor I got these logs:

    Chocolatey v0.10.3
    File specified is either not found or not a .nuspec file. 'C:\projects\hello-netcoreapp\scripts\..\chocolatey\hello-netcoreapp.nuspec -out C:\projects\hello-netcoreapp\scripts\..\artifacts'

You can see that it's looking for the file here:
- `C:\projects\hello-netcoreapp\scripts\..\chocolatey\hello-netcoreapp.nuspec -out C:\projects\hello-netcoreapp\scripts\..\artifacts`

instead of here:
- `C:\projects\hello-netcoreapp\scripts\..\chocolatey\hello-netcoreapp.nuspec`

I also tested with `--out`, which is what should be used [according to the documentation](https://github.com/chocolatey/choco/wiki/CommandsPack), but it lead to the same result (worked locally, didn't work on AppVeyor).

Thankfully the Chocolatey version is printed in the logs, so I noticed the difference to my local system and tried out adding `choco upgrade chocolatey -y` to the `appveyor.yml`. **This solved the problem!**

So I would recommend to upgrade the default Chocolatey version of your VMs from 0.10.3 to 0.10.5.

**Comment by FeodorFitsner** [comment]
Yeah, will deploy it during the next environment update.
