### ISSUE TITLE
ci.appveyor.com show json message instead of build log.

### ISSUE THREAD

**Issue by krhubert** [appveyor/ci#1558]
Hi,

Right after start a build and click on build log (https://ci.appveyor.com/api/buildjobs/rmca900l59j2b6c4/log),
I see json page, which is unclear.

{"message":"Value cannot be null.\r\nParameter name: content"}

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by clmcgrath** [comment]
getting this right now

**Comment by IlyaFinkelshteyn** [comment]
@clmcgrath yes this is still an open issue. However you should be able to open that link as long as build started.

**Comment by FeodorFitsner** [comment]
It's been fixed.
