### ISSUE TITLE
LibSass builds queued for many days

### ISSUE THREAD

**Issue by am11** [appveyor/ci#156]
Sometimes the builds are queue forever, for example; I stopped this build after eight days: https://ci.appveyor.com/project/sass/libsass/build/1.0.204 and restarted it: https://ci.appveyor.com/project/sass/libsass/build/1.0.205.

**Comment by FeodorFitsner** [comment]
There is a running build on other project: https://ci.appveyor.com/project/sass/node-sass/history
Only one concurrent build job is allowed at the moment.

**Comment by am11** [comment]
@FeodorFitsner, thanks for the quick reply.

But that build was queued for eight days. I am sure there was time when no build was running there from node-sass side. Is there any other gotcha we need to consider?

**Comment by FeodorFitsner** [comment]
Build `1.0.204` was created on `2015-03-01 20:26:51 UTC`. That date 8 days ago is commit date, not build created date.

**Comment by am11** [comment]
You are right, the commit was added to the PR sometime ago: https://github.com/sass/libsass/pull/910#issuecomment-76637048.

Sorry for the nudge. :smile: 

And thanks for your support. :+1:
