### ISSUE TITLE
How to download newer file only? wget -N equivalent

### ISSUE THREAD

**Issue by craftwar** [appveyor/ci#1561]
Something like  "wget -N". Download only when remote file is modified.

**Comment by IlyaFinkelshteyn** [comment]
You can add `choco install wget -y` at install stage of AppVeyor build to have wget installed on AppVeyor build worker and us it to download newer files only.

**Comment by craftwar** [comment]
I find out "curl -z" can do this. Add this to doc?

**Comment by IlyaFinkelshteyn** [comment]
Sure, our website is open source, feel free to send a PR :)
