### ISSUE TITLE
Add FCIV.exe to windows build images

### ISSUE THREAD

**Issue by Cyberboss** [appveyor/ci#1562]
To allow in build computation of checksums for artifacts.

https://support.microsoft.com/en-us/help/841290/availability-and-description-of-the-file-checksum-integrity-verifier-utility

**Comment by IlyaFinkelshteyn** [comment]
You can add `choco install fciv` using chocolatey [package](https://chocolatey.org/packages?q=FCIV) at `install` stage of AppVeyor build. The whole installation takes about 20 seconds on AppVeyor build worker.

**Comment by Cyberboss** [comment]
That worked perfectly, thank you
