### ISSUE TITLE
Builds don't start just hanging on initial state

### ISSUE THREAD

**Issue by osoykan** [appveyor/ci#1567]
My .net open source projects that under my github user name (@osoykan) don't start on appveyor and hanging on initial state.

Am i missing a configuration or is there a problem ? Because they worked before and i triggered latest successful builds for check nevertheless new builds didn't work too.

**Comment by FeodorFitsner** [comment]
Can you drop a link to a build please?

**Comment by osoykan** [comment]
Sure,
https://ci.appveyor.com/project/osoykan/fluentassemblyscanner
https://ci.appveyor.com/project/osoykan/autofac-extras-iocmanager
https://ci.appveyor.com/project/osoykan/stove-jo52k

**Comment by FeodorFitsner** [comment]
It should be fixed now. Please restart one of those builds.

**Comment by osoykan** [comment]
@FeodorFitsner, Thanks a lot.
