### ISSUE TITLE
Random Suffixes on Build Numbers

### ISSUE THREAD

**Issue by davidsbond** [appveyor/ci#1575]
Some of my build numbers have seemingly random combinations of letters appended to them:

![Screenshot](http://i.imgur.com/F4XM2Ut.png)

They seem to happen on pull requests more often.

**Comment by IlyaFinkelshteyn** [comment]
You probably have `Pull Requests do not increment build number` in your UI settings (or `pull_requests: /   do_not_increment_build_number: true` in YAML if you use it), right?

**Comment by davidsbond** [comment]
That's correct, have I reported a feature as a bug?

**Comment by IlyaFinkelshteyn** [comment]
Maybe it is little bug-looking, but yes, it is a feature :)

![image](https://cloud.githubusercontent.com/assets/3248386/26513955/6e01cce8-4223-11e7-9d11-769f671a23d8.png)

**Comment by davidsbond** [comment]
Fair enough!
