### ISSUE TITLE
Yarn 0.24.6

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1576]
@FeodorFitsner: the reason for this is some errors we get [here](https://github.com/GoogleChrome/lighthouse/pull/2382).

**Comment by ro-savage** [comment]
Using an old version of Yarn is also causing [Create React App](https://github.com/facebookincubator/create-react-app) end to end tests to crash on windows machines.

See facebookincubator/create-react-app/pull/2400 & yarnpkg/yarn/issues/2591

**Comment by XhmikosR** [comment]
@FeodorFitsner: Will this be in the image update?

**Comment by FeodorFitsner** [comment]
@XhmikosR sure.
