### ISSUE TITLE
Status badge is always red

### ISSUE THREAD

**Issue by deivid-rodriguez** [appveyor/ci#1577]
Hi!

I added appveyor to the [rubocop](https://github.com/bbatsov/rubocop) project a few days ago, but the status badge is constantly red even if the build status is constantly green.

Do you know what might be going on?

**Comment by FeodorFitsner** [comment]
There another project (apparently, abandoned) exists on AppVeyor building the same repository: https://ci.appveyor.com/project/jonas054/rubocop - badge lookup by repository name yields that project.

I'd recommend using a badge with ID.

**Comment by deivid-rodriguez** [comment]
Thanks for the information @FeodorFitsner! :heart_eyes:
