### ISSUE TITLE
UNC paths support regression

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1579]
Discussions:

http://help.appveyor.com/discussions/problems/6765-environmental-change-blocking-unc-path-access
http://help.appveyor.com/discussions/problems/6806-azure-files-smb-support-on-appveyor

**Comment by harshavardhana** [comment]
We are having the same issue here currently attempting to disable the network share test - https://github.com/minio/minio/pull/4446

https://github.com/minio/minio/blob/master/pkg/x/os/stat_windows_test.go#L73 

It the test that is failing.

**Comment by FeodorFitsner** [comment]
@harshavardhana can you please do a simple script in a separate public repository reproducing the issue? Would be great having it for our integration tests.

**Comment by harshavardhana** [comment]
> @harshavardhana can you please do a simple script in a separate public repository reproducing the issue? Would be great having it for our integration tests.

Sure will do do you guys run `go` tests as part of integration tests?

**Comment by FeodorFitsner** [comment]
We can. If you can provide similar to https://github.com/zware/appveyor-test?files=1 with appveyor.yml that would be great.

**Comment by harshavardhana** [comment]
> We can. If you can provide similar to https://github.com/zware/appveyor-test?files=1 with appveyor.yml that would be great.

@FeodorFitsner - https://github.com/harshavardhana/os should have the tests..

**Comment by billziss-gh** [comment]
@FeodorFitsner I am wondering if there is an update on this.

Testing network share functionality is fundamental for my project (which includes a file system driver) so I would rather not disable those tests unless you believe this will take a long time to fix.

**Comment by FeodorFitsner** [comment]
We are deploying updated image later today.

**Comment by billziss-gh** [comment]
Excellent. Thank you as always for the amazing support.

**Comment by mamaso** [comment]
@FeodorFitsner 

I'm still seeing the same error in http://help.appveyor.com/discussions/problems/6806-azure-files-smb-support-on-appveyor - has the updated image been deployed?

**Comment by FeodorFitsner** [comment]
Yes, it's been deployed, However, by default outgoing "File sharing" ports are blocked on VM firewall. Try disabling SMB rule with PS during the build:

```posh
Disable-NetFirewallRule -DisplayName 'File and Printer Sharing (SMB-Out)'
```

**Comment by mamaso** [comment]
@FeodorFitsner thanks, that works!

**Comment by harshavardhana** [comment]
> Disable-NetFirewallRule -DisplayName 'File and Printer Sharing (SMB-Out)'

Can confirm this is working.

**Comment by mamaso** [comment]
It appears that this may have regressed, or it's possible that this is related to the connectivity issue described here: https://appveyor.statuspage.io/incidents/m2vdvw39kdk8

**Comment by FeodorFitsner** [comment]
@mamaso What image do you use? What error are you getting?

**Comment by mamaso** [comment]
I'm using the VS2015 image, and am getting this error:

```
net : System error 53 has occurred.
At line:5 char:5
+     net use J: \\$env:FILES_ACCOUNT_NAME.file.core.windows.net\jenkin ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System error 53 has occurred.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The network path was not found.
```

I also successfully run `Disable-NetFirewallRule -DisplayName 'File and Printer Sharing (SMB-Out)'` prior to attempting to mount the share

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
Could you give me a full command you use to mount remote Azure share (with any sensitive info removed)?

**Comment by MikeStall** [comment]
@FeodorFitsner  - this is our AppVeyor.yml file:   https://github.com/Azure/azure-webjobs-sdk/blob/v2.x/appveyor.yml#L41

**Comment by FeodorFitsner** [comment]
You should now disable these two rules to make it work:

```posh
Disable-NetFirewallRule -DisplayName 'File and Printer Sharing (SMB-Out)'
Disable-NetFirewallRule -DisplayName 'Core Networking - Group Policy (NP-Out)'
```

**Comment by fabiocav** [comment]
Thank you! That did the trick!
