### ISSUE TITLE
Support Batch labels

### ISSUE THREAD

**Issue by simonewebdesign** [appveyor/ci#1580]
I'm trying to use AppVeyor to automate installation and testing of a Batch script. Here you can find the [installation script](https://github.com/simonewebdesign/elm-new/blob/master/install.bat) I use.

It fails with this error:

```
Build started
git clone -q --branch=master https://github.com/simonewebdesign/elm-new.git C:\projects\elm-new
@echo off
echo Initializing...
Initializing...
mkdir C:\Tools\elm-new
echo Downloading...
Downloading...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://codeload.github.com/simonewebdesign/elm-new/zip/v1.3.0', 'C:\Tools\elm-new\elm-new.zip')"
echo Extracting...
Extracting...
call :unzip "C:\Tools\elm-new" "C:\Tools\elm-new\elm-new.zip"
The system cannot find the batch label specified - unzip
Command exited with code 1
```

The `:unzip` label is defined right at the bottom of the file. I tried moving it on top but I get a syntax error.

Also the `@echo off` doesn't seem to be working.

**Comment by IlyaFinkelshteyn** [comment]
I just copy-pasted your `install.bat` into my experimental project and it was [built OK](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/1.10.400). If you point me to specific AppVeyor build URL with the repro I may got some idea why it do not work for you. However note that we have 7zip installed on build workers so you can use it for unzip.

**Comment by simonewebdesign** [comment]
Thanks, that solved my issue. What I did initially was copy-pasting the file contents into the build script field, but what I actually wanted was to just execute install.bat.
