### ISSUE TITLE
Test unit just stucked

### ISSUE THREAD

**Issue by tuananh** [appveyor/ci#1592]
It's just stuck, not throwing anything. Seems all fine on my windows machine.

Previous build was fine as well.

https://ci.appveyor.com/project/tuananh/camaro/build/job/1tdo1vja9cf7xtqh

Thank you in advance.

**Comment by IlyaFinkelshteyn** [comment]
Please [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) to build worker at `init` stage and see what is happening. Maybe some interactive window pops up and waiting for the input, or some process consumes all VM resources.

**Comment by tuananh** [comment]
Thanks. I didn't know i can RDP into build worker. Thanks
