### ISSUE TITLE
Incorrect build number and link

### ISSUE THREAD

**Issue by ruslo** [appveyor/ci#1595]
Hit the problem with the conflicting "build numbers".

I see that different commits `7ee80d1f` and `3128b0ff` assigned to the same build number `1.0.1817`:
* https://ci.appveyor.com/project/ingenue/hunter/history

Screen for the history:
![conflict](https://user-images.githubusercontent.com/4346993/26955137-897c1452-4cbd-11e7-89d2-1075bc7bca6a.png)

Both links go to the same page so I can't see second build at all (is it launched?).

**Comment by IlyaFinkelshteyn** [comment]
Yes, this is [known issue](https://ci.appveyor.com/project/ingenue/hunter/history) which fortunately happens very rarely. Sorry for pointing you to the pretty old issue. Though we cannot give you ETA, we plan to fix it in near future.

**Comment by ruslo** [comment]
> Yes, this is known issue which fortunately happens very rarely

Link go to the history of builds, do you mean some opened appveyor issue?

**Comment by IlyaFinkelshteyn** [comment]
Sorry, updated the link

**Comment by ruslo** [comment]
Ok, thanks. Closing.
