### ISSUE TITLE
Chrome 59.0.3071.86

### ISSUE THREAD

**Issue by filipesilva** [appveyor/ci#1597]
Some builds of ours are failing due to Chrome being older than `58.0.3029.0`, could it be updated please? If there's a way to update it myself I'm happy to, just following what seems to be the issue format of https://github.com/appveyor/ci/issues/1412 and http://help.appveyor.com/discussions/problems/2917-upgrade-chrome-browser-please.

/cc @FeodorFitsner

**Comment by FeodorFitsner** [comment]
Will upgrade Chrome on build workers.

**Comment by filipesilva** [comment]
Thanks for getting back to this, and for updating chrome!
