### ISSUE TITLE
Build fails because of Chrome version must be >= 58.0.3029.0 while e2e tests (using Chrome). Why?

### ISSUE THREAD

**Issue by sharikovvladislav** [appveyor/ci#1600]
Hi!

I have this problem: https://ci.appveyor.com/project/sharikovvladislav/ng2-goods-list/build/1.0.48#L72

```
[19:31:02] I/direct - Using ChromeDriver directly...
[19:31:05] E/launcher - session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)
[19:31:05] E/launcher - SessionNotCreatedError: session not created exception: Chrome version must be >= 58.0.3029.0
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64)
```

I have this in the log.

What is the problem? Do appveyor needs an update? How I can solve it myself? Any wokraround?

**Comment by sharikovvladislav** [comment]
May be this relates to: https://github.com/appveyor/ci/issues/1599

**Comment by FeodorFitsner** [comment]
Chrome will be updated to the latest version this week: https://github.com/appveyor/ci/issues/1597

For now, you can upgrade it with Chocolatey: http://help.appveyor.com/discussions/problems/2917-upgrade-chrome-browser-please#comment_39289617

**Comment by sharikovvladislav** [comment]
@FeodorFitsner is it possible to add command `choco install googlechrome` without changing `appveyor.yml`?

**Comment by FeodorFitsner** [comment]
Nope, unless you do all config via UI and enable "ignore appveyor.yml". It's either UI or yml.

**Comment by sharikovvladislav** [comment]
Ok. Ty. It does not take too much time, so I will just save it in my yml
