### ISSUE TITLE
clone_depth not working (on GitLab?)

### ISSUE THREAD

**Issue by Ede123** [appveyor/ci#1602]
I just tried my first steps setting up CI for a project on GitLab (Inkscape, which just switched to git!)

However already configuring the git clone command fails for me:
* I tried setting `clone_depth: 1` in appveyor.yml
* I tried the setting "Git clone depth" to 1 in the web UI

However the clone command still looks like
`git clone -q --branch=master https://gitlab.com/Ede123/inkscape.git C:\projects\inkscape`

Am I doing something wrong or is something broken?

As the repository is large already cloning requires ~10 min now and has to download 1.5 GB of data which is obviously undesired...

**Comment by Ede123** [comment]
Some links:
* [current appveyor.yml](https://gitlab.com/Ede123/inkscape/blob/master/appveyor.yml) (might change though)
* [my appveyor project](https://ci.appveyor.com/project/Ede123/inkscape)

**Comment by FeodorFitsner** [comment]
Hi Eduard,

Have you added the project as "GitLab" or plain "Git" project?

**Comment by Ede123** [comment]
I added it as a  "GitLab" project,

**Comment by FeodorFitsner** [comment]
OK, looks like there is a bug. Will fix that and deploy update shortly this weekend.

**Comment by Ede123** [comment]
Great! Looking forward to it.

**Comment by Rondom** [comment]
@Ede123 once this is fixed you might want to set it to a higher number than one. Otherwise it will fail when there is another push before the build started.

**Comment by FeodorFitsner** [comment]
The fix has been deployed.

**Comment by Ede123** [comment]
Thanks, fix confirmed!

@Rondom: Thank you for the hint, I have adapted my configuration.
