### ISSUE TITLE
[BUG] Incorrect parsing of 

### ISSUE THREAD

**Issue by webknjaz** [appveyor/ci#1605]
Hello,

I'm seeing my test runner tool name in FILE NAME column. It's `py.test` and it's specified in `name` attribute of the `<testsuite>`. However each `<testcase>` has correct `file` attribute stated, which holds the real file name where the test is specified.

Ref: https://ci.appveyor.com/project/jaraco/cherrypy/build/job/argwk21tag5em5h2/tests

**Comment by IlyaFinkelshteyn** [comment]
Forked your repo, found a bug, fixing now.

**Comment by webknjaz** [comment]
How is it going? It should be easy to fix. Any ETA?

**Comment by IlyaFinkelshteyn** [comment]
Yes, fix indeed is very simple and it is checked in. It will be deployed alongside with others in 1-3 days. We will close this as soon as it is deployed.
