### ISSUE TITLE
Setting up Visual Studio for debugging extensions. This one-time operation may take a minute or more.

### ISSUE THREAD

**Issue by niemyjski** [appveyor/ci#1608]
Setup build image with vs debugging extensions...

I'm not sure how to go about doing this, but every build is 2 minutes longer as it's waiting for `Setting up Visual Studio for debugging extensions. This one-time operation may take a minute or more.`

**Comment by FeodorFitsner** [comment]
Could you please do "Hello, world" project in a public repo setting up extensions during the build, so we can use it for build worker image "warm up"?

**Comment by roji** [comment]
Duplicate of #1391 ("hello world" project still not submitted...)

**Comment by roji** [comment]
[See this](http://comealive.io/AppVeyor-Times-Out-VSIX/) for a workaround.

**Comment by IlyaFinkelshteyn** [comment]
@roji Thanks a lot!

**Comment by igitur** [comment]
> [See this](http://comealive.io/AppVeyor-Times-Out-VSIX/) for a workaround.

@roji The link is dead. Can you please provide the work-around here on the issue page?

**Comment by FeodorFitsner** [comment]
You can initialize Visual Studio Experimental Instance with the following script"

```posh
& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit
```

We'll add that into build image during the next update.
