### ISSUE TITLE
Builds stuck on cancelling

### ISSUE THREAD

**Issue by DaveMiscampbell** [appveyor/ci#1610]
Let's say we have a project configured with a build matrix with 3 environments.

The first environment begins to build and fails. Then the build is cancelled.

In this situation the overall build remains in the "Cancelling" status.

This is fairly minor but just thought you guys would like to know.

**Comment by FeodorFitsner** [comment]
Can you drop a link to that build please?

**Comment by DaveMiscampbell** [comment]
This is actually happening on 2 builds -
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/218
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/215

**Comment by FeodorFitsner** [comment]
OK, it's been fixed.

**Comment by DaveMiscampbell** [comment]
@FeodorFitsner This is now happening again across these 6 builds:

https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/2029
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/1284
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/808
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/805
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/646
https://ci.appveyor.com/project/stormideas/hailto-web-qkuhd/build/601

Is it possible to have these fixed also?

**Comment by IlyaFinkelshteyn** [comment]
@DaveMiscampbell all should be `cancelled` now.

**Comment by DaveMiscampbell** [comment]
Thanks @IlyaFinkelshteyn
