### ISSUE TITLE
VS2017 regression: "Debugging tools for Windows" (part of Windows SDK) missing

### ISSUE THREAD

**Issue by Rondom** [appveyor/ci#1615]
The "Debugging tools for Windows", which are part of the Windows SDK are not installed on the VS-2017-image. They were available in the VS-2015-image.

Use case: The command-line versions of windbg.exe (cdb.exe and kd.exe) are quite useful for producing stack traces in case of crashes. Logging in via RDP and installing them manually, by going to the control panel and modifying the installation-options, makes our crash analysis-script work again.

**Comment by FeodorFitsner** [comment]
How did you install those tools exactly while being logged via RDP?

**Comment by Rondom** [comment]
Select "Windows SDK" in programs and features and modify the installation (right-click) and tick "Debugging Tools for Windows"

**Comment by FeodorFitsner** [comment]
@Rondom Could you please clarify what SDK should be modified to install debugging tools? There is no just `Windows SDK`, but a number of SDKs available:

![image](https://user-images.githubusercontent.com/5041459/27810663-209c0f7e-6012-11e7-87aa-dd8949d0a357.png)

**Comment by Rondom** [comment]
🤔 Pick the newest  🤗
