### ISSUE TITLE
Multiple builds for single commit (GitLab)

### ISSUE THREAD

**Issue by Ede123** [appveyor/ci#1617]
Unless I did something very wrong that I'm not aware of, a single commit to a branch (not the master branch) on GitLab just spawned three separate builds.

See https://ci.appveyor.com/project/Ede123/inkscape/history (builds shortcuts-{56,57,58})

**Comment by FeodorFitsner** [comment]
It's not only you. Looks like there is some issue with GitLab pipelines and external services causing it to call webhook multiple times: https://gitlab.com/gitlab-org/gitlab-ce/issues/25784 
GitLab team believes the issue on our side while we still fail to understand it or reproduce 😃

**Comment by Ede123** [comment]
Is there a possibility to see if (and how often) a webhook was triggered (i.e. "webhook log")?

That way we could check if the webhook is triggered multiple times on GitLab side (which would probably make it a GitLab issue) or if multiple jobs are created for a single webhook request.

**Comment by FeodorFitsner** [comment]
You can try adding [requestb.in](https://requestb.in/) webhook to the same repository (assuming it will be called the same number of times as AppVeyor's webhook). Alternatively, we track webhook calls on our side, so we can look into logs if you give us webhook id and timestamp it was called (email sensitive details, don't post here).

**Comment by Ede123** [comment]
Thanks... Results are "interesting" to say the least. For a push to https://gitlab.com/Ede123/inkscape/ (at 2017-07-05 17:23:54 GMT)
* requestb.in logged one (and only one) webhook request (see https://requestb.in/yt7fudyt?inspect#1ejr0y or the attached file in case the link gets invalidated)
* this also matches with "Recent Deliveries" as available via GitLab UI for the requestb.in webhook (didn't know it existed before, but there seems some logging available too)
* AppVeyor spawned *five* jobs for this single push at https://ci.appveyor.com/project/Ede123/inkscape/ (see master-94 to master-98). They spawned with a delay of approx. 1 minute between each other.
* "Recent Deliveries" as available via GitLab UI for the AppVeyor webhook claims to not have done any request at all (seems like an obvious lie!)


[push_hook.txt](https://github.com/appveyor/ci/files/1125517/push_hook.txt)

**Comment by IlyaFinkelshteyn** [comment]
Please see attached files. First line is time when they arrive according to our traces.
[hook2.txt](https://github.com/appveyor/ci/files/1126074/hook2.txt)
[hook3.txt](https://github.com/appveyor/ci/files/1126075/hook3.txt)
[hook4.txt](https://github.com/appveyor/ci/files/1126077/hook4.txt)
[hook5.txt](https://github.com/appveyor/ci/files/1126076/hook5.txt)
[hook1.txt](https://github.com/appveyor/ci/files/1126078/hook1.txt)

**Comment by Ede123** [comment]
Well, I'm consistently seeing five builds now for the project mentioned before...

I really hope this can be fixed (building every commit five times is obviously ridicoulous) so if I can provide further information to debug this please let me know.

**Comment by FeodorFitsner** [comment]
Did you see any changes in Recent Deliveries on GitLab for AppVeyor webhook?

**Comment by Ede123** [comment]
Not really but I might be on to something: I found some older issues regarding multiple webhooks being fired:
https://gitlab.com/gitlab-org/gitlab-ce/issues/15
https://gitlab.com/gitlab-org/gitlab-ce/issues/2229
https://gitlab.com/gitlab-org/gitlab-ce/issues/2779

In all of them the issue seems to have been caused by the webhook request timing out. Apparently GitLab retries the webhook in this case which might explain the duplicated requests we're seing.

If gitlab.com sticks to the default the relevant variable `webhook_timeout` is likely set to 10 seconds. Is it possible AppVeyor takes longer to answer the request?


This could also explain why the number of duplicated jobs seems not to be constant (maybe sometimes AppVeyor answers in time) but apparently has an upper limit of 5 (which could be the maximum number of retries,; I'll ask about this over at GitLab.com to verify).
Maybe this is also the reason why the request get's not logged in "Recent deliveries" (GitLab could assume the request failed for good if it timed out five times) although a "failed request" log entry would obviously be desirable in this case...

**Comment by FeodorFitsner** [comment]
Will take a look. This is definitely an issue we are going to fix!

**Comment by FeodorFitsner** [comment]
GitLab webhook handler is fully asynchronous now - its processing time is only the time required to put a new message into the queue. Let me know if you still experiencing multiple builds from a single commit.

**Comment by Ede123** [comment]
For the two push hooks I fired in GitLab manually I'm only seeing one job each, so looking good to me so far!

However for the attached hook I'm seeing builds of 558fb7230c83dfffc8994cacf7a2955beb3d88a1 (the "before" commit) instead of f56b521545dcf908a25ed5127af468d1cab1a121 (the "after" commit or "checkout_sha").
Is there a regression or did I find another issue that happens when manually triggering hooks?

**Comment by FeodorFitsner** [comment]
Could you please clarify how to manually trigger the hook?

**Comment by Ede123** [comment]
In GitLab there are options to "test" a hook and you can also choose "Resend Request" for a hook that was sent before. Both resulted in the request I attached and seem to have caused AppVeyor to build the wrong commit.

I can test a real push this evening to see if it makes a difference.

**Comment by Ede123** [comment]
OK, normal pushes seem fine (don't know what went wrong with my manual test this morning).

Also so far no duplicated jobs. Thanks for fixing!

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!
