### ISSUE TITLE
Enable Powershell function to take screenshot && upload as artifact

### ISSUE THREAD

**Issue by mancoast** [appveyor/ci#1620]
Greetings,

It would be incredibly useful if we can take screenshots during build.
These artifacts are useful for test automation and GUI verification.

Thanks,
coast

**Comment by FeodorFitsner** [comment]
It's already possible. Looks how it's done here: https://github.com/appveyor-tests/selenium-tests/blob/master/appveyor.yml#L18-L22

`take-screenshot.ps1`: https://github.com/appveyor-tests/selenium-tests/blob/master/take-screenshot.ps1

**Comment by mancoast** [comment]
Thanks!
