### ISSUE TITLE
AssemblyInfo patching for native DLLs

### ISSUE THREAD

**Issue by oviwankenobi** [appveyor/ci#1621]
is there a way to patch a native DLL (not managed) with the build number?
so when I right click on the dll and choose Properties I can see in the Details tab "Production Version" as the build number? or maybe any other property there set as build number generated by appveyor?

I did turn on the ASsemblyInfo patching but the native DLL (not managed) was not patched with the build number, so I suspect this AssemblyInfo is just for managed assemblies?... 

What I need is the build number appveyor generates with every build to be accessible "somehow" to the methods defined in the native DLL so at run time to be able to use this build number.

Can you please help out?
thank you

**Comment by IlyaFinkelshteyn** [comment]
Answered [here](https://stackoverflow.com/questions/44684827/assemblyinfo-patching-for-native-dlls/44688033#44688033)
