### ISSUE TITLE
Default the setting "Enable secure variables in Pull Requests from the same repository only" to true for private repos

### ISSUE THREAD

**Issue by paddie** [appveyor/ci#1624]
We use a shared YAML in our organisation with shared variables etc. But our process is to _always_ work in pull requests and our developers keep getting surprised and frustrated by having to go into the settings in the UI and enable the field.

I can't immediately see a case where having secure variables be enabled by default in private repos would constitute a security issue (unless the github permissions are already too open), but you've probably thought more about it than me. Any concerns about doing this might also be addressed by  issue #1169 that I see is in progress.

As a completely alternative approach, you could allow projects to enable (but not disable) 'Enable secure variables in *' through the YAML file. If a project later removed that line (which I guess is the reason for the setting), the console could print out a very clear line saying that the secure variables could not be disabled from the YAML file.

![enable_secure_variables_in_pull_request](https://user-images.githubusercontent.com/427074/27434161-08f7a4ae-5758-11e7-99f5-82709521c8da.png)

**Comment by FeodorFitsner** [comment]
That makes sense. Will deploy the change later this week.

**Comment by paddie** [comment]
Fantastic news. We keep being impressed by your response speed, especially considering the number of open issues.

Thanks for a great product!

Kind regards / Venlig hilsen

Patrick Madsen

**Comment by paddie** [comment]
So, is this a default now? Wow, you are the man @FeodorFitsner !

**Comment by FeodorFitsner** [comment]
Yep, it's default. You're welcome 😃
