### ISSUE TITLE
Update VS 2017 Preview image to 15.3 Preview 3

### ISSUE THREAD

**Issue by onovotny** [appveyor/ci#1629]
Just came out last night....lots of fixes in it!

**Comment by FeodorFitsner** [comment]
Thanks for letting know - will do the update.

**Comment by onovotny** [comment]
Related to this, .NET Core 2 Preview 2 would be nice to have on the Preview image: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md

**Comment by FeodorFitsner** [comment]
`Visual Studio 2017 Preview` image has been updated with VS 2017 15.3 Preview 3. .NET Core SDK 2.0 Preview 2 was also installed.
