### ISSUE TITLE
Do not build virtual merge on Pull Requests

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1636]
Discussion: http://help.appveyor.com/discussions/questions/5082-preventing-master-ci-run-when-a-commit-a-made-on-a-feature-branch

**Comment by minggo** [comment]
I think you can disable the building for PR by adding `skip_branch_with_pr: true`

**Comment by IlyaFinkelshteyn** [comment]
@minggo `skip_branch_with_pr: true` does not prevent virtual merge to master to be build when PR is created

**Comment by sschuberth** [comment]
Actually, I think it would be nice if it was completely configurable for a PR whether you want to build only the source branch of the PR, only the "virtual" merge with the target branch, or both. Maybe some configuration setting like this:

    pr_builds:
      source_branch: {true|false}
      target_merge: {true|false}

**Comment by IlyaFinkelshteyn** [comment]
@sschuberth Note that if you disable `Pull request` in GitHub webhook settings, virtual merge does not happen. This issue is mostly about to make the same in YAML (so have all settings in one place), but right now it is doable with altering GitHub webhook too.

**Comment by sschuberth** [comment]
Ah, thanks @IlyaFinkelshteyn for pointing out to configure this via GitHub's web interface. It seems this would also allow to only build the virtual merge by only leaving the "Pull request" event checked.

**Comment by IlyaFinkelshteyn** [comment]
@sschuberth AppVeyor starts building virtual merge when it receives PR webhook. If this webhook is not being sent, nothing happens. Normal pushes to the feature branch will still be built, because `Push` is still checked and webhook is being sent fro them.

**Comment by sschuberth** [comment]
Thanks for the clarification!

**Comment by smtakeda** [comment]
+1 for adding "Not run test for PR" option unless the secure file can be decrypted in PR: https://www.appveyor.com/docs/how-to/secure-files/
```
Note that file won’t be decrypted on Pull Request builds as secure variables are not set during PR build.
```
Since our builds use an encrypted file, PR build always fails.
https://github.com/snowflakedb/libsnowflakeclient/pull/22

**Comment by IlyaFinkelshteyn** [comment]
@smtakeda `Secure files` use feature directly depends on [secure variables](https://www.appveyor.com/docs/build-configuration/#secure-variables). You can enable secure variables in Pull Requests in Project General Setting (UI only) -- for branches in the same repository only if your project is open source projects, and for branches in any repository if your project is private.

**Comment by smtakeda** [comment]
@IlyaFinkelshteyn, ah, thank you! It worked now!

**Comment by nealkruis** [comment]
@IlyaFinkelshteyn you said:

> Note that if you disable Pull request in GitHub webhook settings, virtual merge does not happen. This issue is mostly about to make the same in YAML (so have all settings in one place), but right now it is doable with altering GitHub webhook too.

I haven't been able to find where to change this setting. Is there an option in the GitHub interface, or must this be set through the API?

**Comment by nealkruis** [comment]
Never mind. I found it under repository settings (I was searching under user/organization settings).

**Comment by scottbelden** [comment]
I'm not sure if this is still active but I wanted to add a voice in favor of this. I recently found out about the `skip_branch_with_pr: true` option and thought that when I set that and created a PR I would only get one build but was confused to still see it build twice. It's something I can live with but it sure would be nice to reduce the duplicate building. Thanks!

**Comment by IlyaFinkelshteyn** [comment]
Oh, it is actually implemented a while ago as part of different work. Check `Do not build on "Pull request" events` setting in General Settings tab in the UI. Setting is UI-only for security reasons so even if you use YAML for configuration, this setting should be set in UI.

**Comment by scottbelden** [comment]
Thanks! I don't think I ever would have guessed that. I also assumed that all of the UI settings were not used if a YAML file was present.

**Comment by IlyaFinkelshteyn** [comment]
@scottbelden check https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence

**Comment by scottbelden** [comment]
Thanks!
