### ISSUE TITLE
xunit test failing to publish results to batch api

### ISSUE THREAD

**Issue by Cisien** [appveyor/ci#1640]
```
dotnet : When sending 'POST http://localhost:1563/api/tests/batch' with body '[{"testName":"CSDiscordService.AuthTests.Auth_EachTokenWorks(token: 
\"test\")","testFramework":"xUnit","fileName":"CSDiscordService.Tests.dll","outcome":"Running"}]', exception was thrown: Object reference not set to an instance of an object.
At line:1 char:1
+ dotnet xunit
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (When sending 'P...e of an object.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
When sending 'PUT http://localhost:1563/api/tests/batch' with body 
'[{"testName":"CSDiscordService.AuthTests.Auth_BadSchemeWithGoodTokenReturns401","testFramework":"xUnit","fileName":"CSDiscordService.Tests.dll","outcome":"Passed","durationMilliseconds":13
53,"StdOut":""}]', exception was thrown: Object reference not set to an instance of an object.
```

build: https://ci.appveyor.com/project/Cisien/csdiscord

The test appears to complete successfully, however the failure happens when the results are posted.
This is using the latest pre-release on nuget for xunit
```
        <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
        <PackageReference Include="xunit.runner.reporters" Version="2.3.0-beta3-build3705" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
        <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
```

**Comment by IlyaFinkelshteyn** [comment]
If you run tests in `cmd`, e.g. simple `- dotnet xunit` [here](https://github.com/Cisien/CSDiscord/blob/master/appveyor.yml#L28), warning will remain, but will not creak the build. Because status code of `dotnet xunit` will be still `0`. In PowerShell that warning is written into `stdErr`.

However I even do not call this a good workaround, we still need to investigate this `POST` issue in the first place. Will keep this issue open.

**Comment by Cisien** [comment]
It appears the code responsible for throwing this exception is at https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters/AppVeyorClient.cs#L99-L124

I'll give your workaround a try.
