### ISSUE TITLE
Nested visualization support for private Hyper-V clouds

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1642]
Some scenarios require to spin up VMs inside build VM for end-to-end testing. As long as Windows Sever 2016 support this, we can add this as well on our Hyper-V platform.

**Comment by FeodorFitsner** [comment]
Just to add some clarity to this issue: it's nested virtualization support for "custom" private build clouds, not for our public hosted build cloud. Sorry about the confusion added by this issue.
