### ISSUE TITLE
Rebuild button not showing

### ISSUE THREAD

**Issue by pfmoore** [appveyor/ci#1643]
I am an administrator of the pypa/pip project on github. For that project, we have Appveryor testing set up, and an "Appveyor Admins" role. We have a "pypa" account on appveyor (not linked to a github account, as we don't have a team github account, just individual team members), and under that account we have the "pypa/Appveyor Admins" team mapped to the Administrators role.

From my understanding, with this setup, when I click on the "Appveyor build details" button in github, I should be taken to the Appveyor page and be able to restart builds if needed. I do get taken to the page (although I'm not logged in, so I need to log in to Appveyor) but on that page I don't see the "Re-start build" button. All I can see is the "Log" button.

Have I got something set up wrongly, or is there a problem here?

![Screenshot](https://i.imgur.com/uFLHyRy.png)

**Comment by IlyaFinkelshteyn** [comment]
Interesting... I cannot reproduce it though. Few questions:
- If you navigate to `HISTORY` and then navigate back, do you see other buttons than `Log`?
- Do you see another buttons if you logged on to AppVeyor *before* you press `AppVeyor build details` on GitHub?
- Do you see another buttons is you simple log on to AppVeyor and look at some random build in build history?

**Comment by pfmoore** [comment]
> If you navigate to HISTORY and then navigate back, do you see other buttons than Log?

No

> Do you see another buttons if you logged on to AppVeyor before you press AppVeyor build details on GitHub?
> Do you see another buttons is you simple log on to AppVeyor and look at some random build in build history?

No, to both of these. I see the same behaviour (no buttons) no matter how I get to the page.

It looks precisely as if I were not a member of the "pypa/Appveyor Admins" group in github.

**Comment by IlyaFinkelshteyn** [comment]
What account do you choose when you log in? `pfmoore` or `pypa`?

**Comment by pfmoore** [comment]
pfmoore. I see the buttons with pypa.

**Comment by IlyaFinkelshteyn** [comment]
This  is expected. `pfmoore` is your own account created automatically when you register with AppVeyor. You are collaborator with Administrator right in `pypa` and should login to that account to manage it. We have https://github.com/appveyor/ci/issues/1313 issue to make it more convenient.

**Comment by pfmoore** [comment]
So what's the point in my pmoore account having the Administrator role via my membership of the github team? How can I allow contributors in my github organisation to restart failed builds without sharing the credentials for the Appveyor owning account?

I feel like I'm missing something about how roles work in Appveyor...

**Comment by IlyaFinkelshteyn** [comment]
I re-read your initial post and I now I realized that you you have [GitHub integration](https://www.appveyor.com/docs/team-setup/#github-integration) set up. However to benefit from it, you and your team members need to sign-in with "GitHub" button.

**Comment by pfmoore** [comment]
That's what I do.

**Comment by IlyaFinkelshteyn** [comment]
OK, and if you select `pypa` account, it works as expected. Maybe you expect that as long as you are already signed on to GitHub, you should not have to do additional login to AppVeyor, even with "GitHub" button?

**Comment by pfmoore** [comment]
Oh. I think I see. I request login via github, and I get a choice between pfmoore and pypa. I always choose pfmoore as that's the name of my github account - but what you're saying is that I got authenticated to github, and these are the two *appveyor* accounts I'm allowed to log in as. If I log in to the "pypa" account, I show as logged in as "Paul Moore" but I can now access the extra options for the projects associated with the "pypa" account. But *not* the ones owned by "pfmoore".

OK. That's really confusing but I see how it works now.

I was expecting that as I had admin rights to both my own account and the pypa account, I'd be able to restart builds (and do other admin jobs) for projects under either account, not that I'd have to select which one I was administering at login time.

At a minimum, I'd suggest this needs better documentation. I'd like to have something I can point my other team members at to understand how to do this, and I'm not sure I could explain it clearly to them myself :-( But thanks for your patience in sticking with this till I understood.

**Comment by IlyaFinkelshteyn** [comment]
We tried to cover it [here](https://www.appveyor.com/docs/team-setup/). This is open source, feel free to contribute :)
