### ISSUE TITLE
Build process fails when Nunit is added to a test project.

### ISSUE THREAD

**Issue by Arash-Sabet** [appveyor/ci#1645]
Please consult [the error messages available here](https://ci.appveyor.com/project/Arash-Sabet/sharpsimplenlg/build/messages) to learn about the details of the build issue. A project has been setup in VS 2017 with a reference to Nunit and compiles successfully on a local machine. When pulled by appveyor and compiled, the build process fails.

**Comment by IlyaFinkelshteyn** [comment]
It looks like Nunit package is not being restored properly. Can you please check, does it still compile on your local machine if you "Clean solution" in Visual Studio?

**Comment by Arash-Sabet** [comment]
@IlyaFinkelshteyn I followed your instructions on my local machine and it compiles flawlessly.

**Comment by IlyaFinkelshteyn** [comment]
What if you delete packages folder from local machine? Here is the picture I see in VS when I forked your repo, created project and connected with [RDP ](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/), and this is after `dotnet restore`
![2017-07-07_11h36_08](https://user-images.githubusercontent.com/3248386/27971768-bf25ca9c-6308-11e7-8303-392949a1a264.png)

**Comment by Arash-Sabet** [comment]
I made some slight changes and committed the code. The code compiles well on my local machine after deleting packages folder. This folder is recreated and the code compiles smoothly. After committing the code to the repo, appveyor failed to compile again by exhibiting the same issue.

**Comment by IlyaFinkelshteyn** [comment]
@Arash-Sabet Please check [installed:](https://ci.appveyor.com/project/Arash-Sabet/sharpsimplenlg/build/1.0.10#L41) report. I do not see that `nuget restore` reports that any packages were installed to `C:\projects\sharpsimplenlg\SharpSimpleNLGTests\SharpSimpleNLGTests.csproj`.

**Comment by Arash-Sabet** [comment]
@IlyaFinkelshteyn  I added nuget restore command and it made the things work. Thanks for the help.
