### ISSUE TITLE
Artifact url is temporary Azure blob url in notifications

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1646]
Discussion: http://help.appveyor.com/discussions/problems/7031-notification-link-to-artifact-expires

**Comment by topic2k** [comment]
Any news if this will be fixed? I would like to avoid to use a workaround.

**Comment by IlyaFinkelshteyn** [comment]
@topic2k will try to fix this in near time

**Comment by IlyaFinkelshteyn** [comment]
Just to clarify: It is fixed. `Url` property stays the same (for not to break people who need it this way. New property called `permalink` is AppVeyor (not Azure) URL which do not expire.
