### ISSUE TITLE
Cache invalidation broken?

### ISSUE THREAD

**Issue by smtrat** [appveyor/ci#1647]
I'm trying to invalidate my build cache very much like shown in the very first example at [the tutorial](https://www.appveyor.com/docs/build-cache/#cache-dependencies):

    cache:
      - C:\Libraries\mpir-3.0.0 -> .appveyor.xml

However, this does not seem to work at all. See for example this [commit](https://github.com/smtrat/carl/commit/cf0d2c656f3090a234295d270a702edd2d3dd073) which renames `appveyor.xml` to `.appveyor.xml`, however the cache is [not invalidated](https://ci.appveyor.com/project/smtrat/carl/build/1.0.114).
This may be a corner case, however this [other commit](https://github.com/smtrat/carl/commit/393a6577fcda8e8731f8ee931c91ba01c1f719cf) just did a regular modification to `appveyor.xml` and still the cache was [not invalidated](https://ci.appveyor.com/project/smtrat/carl/build/1.0.106).

What exactly do I miss here? Or is this just broken?

Update: And as you might argue that this is still a special case (as the modification concerned the cache settings), here is [yet another commit](https://github.com/smtrat/carl/commit/6e3ec28e56942085eda6823d3d892350fbec06f6) that did not change the cache settings at all, but the cache was [not invalidated](https://ci.appveyor.com/project/smtrat/carl/build/1.0.63).

**Comment by IlyaFinkelshteyn** [comment]
It is `appveyor.`**x**`ml` [here](https://github.com/smtrat/carl/blob/master/.appveyor.yml#L9), but file is actually `appveyor.`**y**`ml`

**Comment by smtrat** [comment]
Oh my. You are right and I'm an idiot... Thanks.
