### ISSUE TITLE
Unable to log in as an GitHub organization

### ISSUE THREAD

**Issue by iantalarico** [appveyor/ci#1651]
I am a public member of an organization but when I try to log into appveyor via the GitHub button I do not see the organization.

**Comment by IlyaFinkelshteyn** [comment]
You have to be a member of specific GitHub **team** (some [details](https://www.appveyor.com/docs/team-setup/#github-integration)) to be able to see specific AppVeyor **account** when you login (in dialog like [this](https://www.appveyor.com/docs/team-setup/#switching-between-accounts)). Can you please check that you are member of the team which is set up in AppVeyor? If you are not sure about what is that team name, please email `team at appveyor.com` and I will send you that information.

**Comment by iantalarico** [comment]
Discussed offline.  It looks like I need to be in a team not organization.
