### ISSUE TITLE
msys2 broken due to runtime update

### ISSUE THREAD

**Issue by Optiligence** [appveyor/ci#1664]
Builds don’t get past the core system upgrade.

**Comment by IlyaFinkelshteyn** [comment]
Could you please clarify the issue a little bit? Link to the build and `appveyor.yml` will not hurt.

**Comment by Optiligence** [comment]
i don’t think that will help much, but here you go: 
https://github.com/knossos-project/knossos/blob/52e632ccaa516f166b2d0c13630e0fe123ad9458/.appveyor.yml
https://ci.appveyor.com/project/al3xst/knossos-r575n/build/1.0.203

the preinstalled msys2 core probably needs to be updated

**Comment by Ede123** [comment]
Inkscape builds are still working: https://ci.appveyor.com/project/inkscape/inkscape
Maybe it works when updating on the AppVeyor shell before switching to MSYS2 shell?

I did notice however that my locally installed MSYS2 locked up on last core system upgrade and I had to kill the mintty process manually - might well be that's the issue you're facing!

**Comment by Optiligence** [comment]
Yeah, well, it’s probably not very clever of us to use msys2 bash to evaluate our build script. I didn’t know we were doing that. I’ll check on that. Updating appveyor’s msys2 core would also fix this though (although only for now).

**Comment by Optiligence** [comment]
I guess i’ll close this then (thx @Ede123). Would be nice if the msys2 base would be updated anyways.

**Comment by Optiligence** [comment]
@Ede123 Without `bash -lc` pacman is effectively run outside msys2. Couldn’t this become a problem? Currently it works, but I assume it would break on post_install scripts/hooks.

**Comment by Ede123** [comment]
Yes, it definitely can break on post_install scripts/hooks (so you certainly shouldn't do that for updating other things).
For the core system it seems to work (as far as I can tell this also doesn't try to run any install scripts).

The only thing I'm afraid of: What will happen if AppVeyor actually updates the core system to the latest version at some point? Then I assume the first pacman command will already update other packages which potentially *might* use install scripts!

**Comment by Optiligence** [comment]
Now using
>image: Visual Studio 2019

msys2 does seem to get updated from time to time, which – with the workaround discussed here – creates the problem that the _core system upgrade_ gets skipped, indeed resulting in failed `post_upgrade` for other packages. 
The build goes trough and the binaries seem to work, not sure about any other adverse effects. 
It sure would be nice if `pacman` could be told to quit after the _core system upgrade_.

**Comment by FeodorFitsner** [comment]
@Optiligence Could you please look at [this MSYS installation script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_msys64.ps1) and tell me how to fix it (or do a PR), so it will make the next image update? Thank you!

**Comment by Optiligence** [comment]
@FeodorFitsner i only noted this as a current observation – i’m actually not sure there exists a solution right now. 

If the env is too old bash won’t terminate after an upgrade – this was the original problem in this issue. (idk which package actually is/was the problem)
However, the »workaround« for that only works if the image is old enough to not skip over the _core system upgrade_. 
If the image is too new the workaround breaks and it also means the image creation itself might exhibit this issue at some point. 
Also, the workaround can only be removed if the image is guaranteed to be upgraded enough to preempt it. (which i don’t think is realistic)

**Comment by Optiligence** [comment]
ok, it seems like also doing the first run of `pacman -Syuu --noconfirm` _within_ `bash -lc` is fine
(the `Visual Studio 2019` image seems to run well with this now while the `Visual Studio 2015` image is probably broken anyway as of today)

Essentially just running pacman twice inside bash but making sure it’s terminated _if_ there are core system upgrades and the second run being a noop if not. 

The initial issue still is that that can’t be done in a single bash invocation, which is a caveat we’ll probably not loose for a long time. 

@FeodorFitsner
`--needed` doesn’t do anything for upgrades, only when packages for installation are specified
and i think the `--ask=20` hack is not required anymore, `--noconfirm` should be enough
only 2 `bash 'pacman -Syuu --noconfirm'` should suffice, although i assume the `grep 'gpg-agent'` is required for both (i don’t know about the issue that one is trying to solve anyway)

**Comment by FeodorFitsner** [comment]
OK, thank you for your comments. The new image update is being baked right now with incorporated changes.
