### ISSUE TITLE
* Missing C libraries: eay32, ssl32

### ISSUE THREAD

**Issue by domenkozar** [appveyor/ci#1665]
```
Process exited with code: ExitFailure 1
    Logs have been written to: C:\w\.w\logs\cryptonite-openssl-0.6.log
    Configuring cryptonite-openssl-0.6...
    Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependencies on foreign
    libraries:
    * Missing C libraries: eay32, ssl32
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
```

We are using following flags:

    --extra-lib-dirs=C:\OpenSSL-Win64
    --extra-include-dirs=C:\OpenSSL-Win64\include

Example build log: https://ci.appveyor.com/project/jagajaga/cardano-sl/build/0.4.8482

Has there been an update of Visual Basic 2015 image in last 12h? Builds are starting to fail suddenly.

**Comment by FeodorFitsner** [comment]
We are rolling out a new build worker image with OpenSSL updated: https://github.com/appveyor/ci/issues/1619

`Visual Studio 2015` image has been updated but an entry in updates will be published later today.

**Comment by domenkozar** [comment]
@FeodorFitsner thanks, could you help us where are `eay32, ssl32` libraries located now?

**Comment by FeodorFitsner** [comment]
I'm not sure I understand what you mean. Full installs of OpenSSL are available in the same locations: `C:\OpenSSL-Win64` and `C:\OpenSSL-Win32` - it was just version bumped to 1.1.0f. You can run `dir` command or use RDP to see what's in there. I hoped you'll be able to tell us if there any changes (regression) in OpenSSL 1.1.0f 😃

**Comment by domenkozar** [comment]
According to https://mta.openssl.org/pipermail/openssl-dev/2016-August/008351.html this is a breaking change: eay32/ssl32 libraries were renamed /cc @jmitchell

**Comment by billy1arm** [comment]
moving from 1.0.x versions to 1.1.x is a breaking change,
To quote a reply form the openSSL dev team....

1.1.0 introduced major changes in the build process.  The libraries are now called libcrypto.lib (formerly libeay32.lib) and libssl.lib (formerly ssleay32.lib).  The DLLs have also changed:  libcrypto-1_1.dll and libssl-1_1.dll respectively.

The 1.0.2 series is supported for quite a while yet:

https://www.openssl.org/source/

"Also available is the 1.0.2 series.  This is also our Long Term Support
(LTS) version (support will be provided until 31st December 2019)."

**Comment by jmitchell** [comment]
After making a patch for the library name change I'm seeing another breaking change: `unknown symbol `EVP_CIPHER_CTX_init'`.

**Comment by jmitchell** [comment]
@FeodorFitsner, is AppVeyor dropping support for OpenSSL 1.0.x? As others have stated, this upgrade is a breaking change and 1.0.2 is the upstream LTS version supported until the end of 2019.

**Comment by FeodorFitsner** [comment]
We were unaware about breaking changes in 1.1 - our goal is to have the latest and freshest on build workers (provided it's RTM'd).

Well, we can keep 1.1.x in the default `C:\OpenSSL-Win32` and `C:\OpenSSL-Win64` locations and if your project is not ready to switch to 1.1 yet you can easily install 1.0.x side-by-side into alternate `C:\OpenSSL-Win32-v10` and `C:\OpenSSL-Win64-v10` directories with a simple PS script:

```posh
Write-Host "Installing OpenSSL v1.0 32-bit ..." -ForegroundColor Cyan
Write-Host "Downloading..."
$exePath = "$($env:USERPROFILE)\Win32OpenSSL-1_0_2L.exe"
(New-Object Net.WebClient).DownloadFile('https://slproweb.com/download/Win32OpenSSL-1_0_2L.exe', $exePath)
Write-Host "Installing..."
cmd /c start /wait $exePath /silent /verysilent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win32-v10
Write-Host "Installed" -ForegroundColor Green

Write-Host "Installing OpenSSL v1.0 64-bit ..." -ForegroundColor Cyan
Write-Host "Downloading..."
$exePath = "$($env:USERPROFILE)\Win64OpenSSL-1_0_2L.exe"
(New-Object Net.WebClient).DownloadFile('https://slproweb.com/download/Win64OpenSSL-1_0_2L.exe', $exePath)
Write-Host "Installing..."
cmd /c start /wait $exePath /silent /verysilent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win64-v10
Write-Host "Installed" -ForegroundColor Green
```

**Comment by domenkozar** [comment]
@FeodorFitsner I want you to reconsider the bump as most software is not ready for OpenSSL 1.1.0. Even bleeding edge Linux distributions have stopped the migration: https://lists.debian.org/debian-devel/2016/11/msg00573.html

It would be wise to do it the other way around, 1.0.x being the default and having a way to install 1.1.x

Then carefully plan with customers the upgrade path, which breaks API.

**Comment by FeodorFitsner** [comment]
@domenkozar agree. Let's leave 1.0.x as default option: https://github.com/appveyor/ci/issues/1671
Will be updating images later today.

**Comment by MadMaxMangos** [comment]
@FeodorFitsner Did the images get updated? Will you let us know when they have been?

**Comment by FeodorFitsner** [comment]
Deploying later today.
