### ISSUE TITLE
Add dist.nuget.org to workaround

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1667]

**Comment by FeodorFitsner** [comment]
No longer needed as the problem has been fixed on CDN side.

**Comment by gep13** [comment]
@FeodorFitsner is this an issue that is likely to keep happening?

**Comment by FeodorFitsner** [comment]
It could happen sometimes though it shouldn't be a frequent issue. The "routing" issue could happen to any hosting provider.

**Comment by gep13** [comment]
@FeodorFitsner I wasn't trying to appoint any blame, I understand that these things can happen.  Just wondering if you thought that this was going to be an ongoing issue.

**Comment by IlyaFinkelshteyn** [comment]
@gep13 We never know what can happen with infrastructure beyond our control. But what we can and should do is to implement much more agile way to apply any workaround side, without even bothering our customers with any details. This is what we are implementing right now: https://github.com/appveyor/ci/issues/1673
