### ISSUE TITLE
Make OpenSSL 1.0.x branch the default option

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1671]
In response to https://github.com/appveyor/ci/issues/1665 we are bringing OpenSSL 1.0.x branch as default option installed into `C:\OpenSSL-Win32` and `C:\OpenSSL-Win64` directories.

Going forward people will be installing 1.1.x with a script during their builds into alternative `C:\OpenSSL-Win32-v11` and `C:\OpenSSL-Win64-v11` directories: 

```posh
Write-Host "Installing OpenSSL 1.1 32-bit ..." -ForegroundColor Cyan
Write-Host "Downloading..."
$exePath = "$($env:USERPROFILE)\Win32OpenSSL-1_1_0f.exe"
(New-Object Net.WebClient).DownloadFile('https://slproweb.com/download/Win32OpenSSL-1_1_0f.exe', $exePath)
Write-Host "Installing..."
cmd /c start /wait $exePath /silent /verysilent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win32-v11
Write-Host "Installed" -ForegroundColor Green

Write-Host "Installing OpenSSL 1.1 64-bit ..." -ForegroundColor Cyan
Write-Host "Downloading..."
$exePath = "$($env:USERPROFILE)\Win64OpenSSL-1_1_0f.exe"
(New-Object Net.WebClient).DownloadFile('https://slproweb.com/download/Win64OpenSSL-1_1_0f.exe', $exePath)
Write-Host "Installing..."
cmd /c start /wait $exePath /silent /verysilent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win64-v11
Write-Host "Installed" -ForegroundColor Green
```

**Comment by misery** [comment]
Will C:\OpenSSL-Win32-v11 and C:\OpenSSL-Win64-v11 be provided in images some day? Qt 5.10 and higher can use OpenSSL 1.1.
Our application requires Qt and OpenSSL so Qt needs to be build against the same OpenSSL version as our application.

**Comment by FeodorFitsner** [comment]
Added a new issue to have it pre-installed on images: https://github.com/appveyor/ci/issues/2554
