### ISSUE TITLE
IE Selenium driver error on Visual Studio 2017 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1677]
OpenQA.Selenium.WebDriverException : Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

**Comment by toddmeinershagen** [comment]
Just an additional comment -- this works for the Visual Studio 2015 image.  So, you might want to look at the configuration on that image to match them.  Hope it helps.

**Comment by FeodorFitsner** [comment]
Sure, thanks for the note.
