### ISSUE TITLE
Unloaded projects are still built

### ISSUE THREAD

**Issue by godrose** [appveyor/ci#1680]
I've  unloaded several projects from the solution. 
Yet they are still built and result in failing build.

Please see https://ci.appveyor.com/project/LogoFX/samples-specifications for reference

**Comment by IlyaFinkelshteyn** [comment]
Seems like to figured out the issue and [this](https://ci.appveyor.com/project/LogoFX/samples-specifications/build/1.0.73) build is OK, please confirm.

**Comment by godrose** [comment]
Thanks for the reply.
I had to manually remove the unloaded projects to pass the build.
This is not the expected behaviour.

**Comment by IlyaFinkelshteyn** [comment]
Per my understanding `unload` is Visual Studio UI-only thing.  It is saved in `.suo` file ([check this SO post](https://stackoverflow.com/questions/12275753/when-i-unload-projects-in-visual-studio-where-does-vs-save-this-setting)). 
`.suo` file by default ignored by git (check normal `.gitignore` created by VS), and does not respected by `msbuild`.

**Comment by godrose** [comment]
I see. Thanks a lot. The lack of respect by `msbuild` is somewhat strange as it builds locally perfectly.

**Comment by IlyaFinkelshteyn** [comment]
I just called `msbuild /verbosity:minimal` on local computer from solution folder, for solution which has 2 projects. First time with default settings, second with one project "unloaded". In both cases `msbuild` **command line** tool build both projects.
