### ISSUE TITLE
git getting submodule from public repository failing.

### ISSUE THREAD

**Issue by Takaloy** [appveyor/ci#1684]
Hi,

was wondering if you can help me figure out what I did wrong here, the repository has a submodule and it should be cloned before building , so i added a command on a the pre build but it seems to be failing on account of public key.

perhaps it's just a "duh" moment for me :)

Running Install scripts
git submodule -q update --init
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:barrett777/Heroes.ReplayParser.git' into submodule path 'C:/projects/heroes-draftviewer/Heroes.ReplayParser' failed
Failed to clone 'Heroes.ReplayParser'. Retry scheduled
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by Takaloy** [comment]
actually answered my own question here.

the problem is using SSH over Appveyor seems to be a problem. changing it to clone via HTTPS resolves the problem with the public key.

**Comment by IlyaFinkelshteyn** [comment]
It happened because the same "deploy key" cannot be used on more than one GitHub repository. However, you can move the key from repository to account level (https://github.com/settings/keys), so you can clone any repo with the same key (found on General tab of AppVeyor project settings).
