### ISSUE TITLE
How to make build status failure when VS building failure

### ISSUE THREAD

**Issue by minggo** [appveyor/ci#1687]
VS build [reports error](https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.24#L11961) but the build status is also success. The building script is

```
& msbuild $env:APPVEYOR_BUILD_FOLDER\build\cocos2d-win32.sln /t:Build /p:Platform="Win32" /p:Configuration="Release" /m
```

How to change the build status to failure when VS build reports error? Thanks.

**Comment by IlyaFinkelshteyn** [comment]
This is because `build.ps1` PowerShell script itself does not return error. You can add something like this into it : `if ($lastexitcode -ne 0) {throw}`. Or change script to be cmd. Or simple run `msbuild` command as `cmd` command from YAML directly.

**Comment by minggo** [comment]
The corresponding `.appveryor.yml` is [here](https://github.com/cocos2d/cocos2d-x/blob/v3/.appveyor.yml):

* [./tools/appveyor-scripts/before-build.ps1](https://github.com/cocos2d/cocos2d-x/blob/v3/tools/appveyor-scripts/before-build.ps1)
* [./tools/appveyor-scripts/build.ps1](https://github.com/cocos2d/cocos2d-x/blob/v3/tools/appveyor-scripts/build.ps1)

**Comment by IlyaFinkelshteyn** [comment]
Yes, I already took a look before initial reply and provided you with a few solutions.

**Comment by minggo** [comment]
@IlyaFinkelshteyn thanks for reply, but i don't quite understand.

>> You can add something like this into it : `if ($lastexitcode -ne 0) {throw}`

Where to add?

>> Or change script to be cmd. 

How to do it?

>> Or simple run msbuild command as cmd command from YAML directly

Did you mean don't use PowerShell script, just copy the command into [it](https://github.com/cocos2d/cocos2d-x/blob/v3/.appveyor.yml#L21)? But i think using script is more useful since may add more codes in future.

Thanks.

**Comment by IlyaFinkelshteyn** [comment]
>> Where to add?

Add this as second line after `msbuild` command to the script

>> How to do it?

rename file to build.cmd, remove `&` and use variables in `cmd` style, which is `%%`
use with ` - ` or ` - cmd: ` prefix.

>> Did you mean don't use PowerShell script, just copy the command into

Yes, but change it to `cmd` style. and use ` - ` or ` - cmd: ` prefix.

The way you do it is up to you. If you are not sure with YAML syntax you can always create configuration in UI and then press `Export YAML`.

**Comment by minggo** [comment]
Thanks for your help. It is helpful, and i always use the configuration UI to export YAML :)
