### ISSUE TITLE
error MSB8013 when building projects that were working previously

### ISSUE THREAD

**Issue by cenit** [appveyor/ci#1690]
I have a strange issue which I could not solve by myself

I prepared a small appveyor.yml script for this project: 
https://github.com/ALaDyn/Propaga

Initially it worked:
https://ci.appveyor.com/project/cenit/propaga/build/1.0.2

then yesterday without changing anything I re-run it because I was seeing a strange behaviour in other projects and I wanted to re-build a working project
https://ci.appveyor.com/project/cenit/propaga/build/1.0.3

It is not building anymore, with this strange message that "error MSB8013: This project doesn't contain the Configuration and Platform combination of Release|Win32. "
As you can see, it is rebuilding the same commit that was working before, and that is working anyway.

I cannot reproduce locally (it works perfectly).
Maybe some updates to the newest Visual Studio 2017 image didn't go very well?

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
I compared those builds and see 2 differences in external dependencies:

|           | Old (successful)|Current(failed)|
| ------:|:----:| :------:|
|cmake|3.8.2|3.9.0 |
|VCPKG_VERSION|5a74d30aab81e2e0d1f210117fa05e76b39b5fab|59792e9e463d3781c7b95d96c49e24e1f9b7f154|

Can you build locally with latest cmake and vspkg on Win32 platform successfully?

**Comment by cenit** [comment]
yes absolutely. Here it looks like cmake is not even called...

**Comment by IlyaFinkelshteyn** [comment]
Sorry, I did not follow. Does it builds OK with the  **latest** `cmake` and `vspkg` on **Win32** platform **locally**?

**Comment by cenit** [comment]
yes, sorry if I was not clear. I have everything up to date on my computer and it works perfectly, with exactly the same setup: make 3.9 from chocolatey and vcpkg up to date.
The error on appveyor is strange because I think that cmake fails to start and so MSBuild does not find anything later to build
I saw you just noticed a similar bug here: http://help.appveyor.com/discussions/problems/7188-odd-cmake-build-failures-unrelated-to-code-changes
I hope it can be fixed soon because it is spreading in many of our repositories which were perfectly good before. They just fail as soon as we push an update, which works perfectly locally and also on every other tested platform, triggering unjustified alarms.

**Comment by cenit** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/17118
Here they say that cmake 3.9.1 should fix it. Let's hope so!

**Comment by cenit** [comment]
make 3.9.1 has been released and it seems to have fixed the problems!
