### ISSUE TITLE
junit test result upload uses wrong attribute "type" for the error "message"

### ISSUE THREAD

**Issue by blairmcg** [appveyor/ci#1691]
See, e.g., this build: https://ci.appveyor.com/project/dolphinsmalltalk/dolphin-db22v/build/7.0.44.6/tests
And expand the result for https://ci.appveyor.com/project/dolphinsmalltalk/dolphin-db22v/build/7.0.44.6/tests
Note that the error message reported is "MessageNotUnderstood", but the XML looks like this:
```
<testcase name="testResizeDoesNotMove" classname="ViewComposerTest">
    <error message="ViewComposerTest does not understand #getStaticTextResource" type="MessageNotUnderstood">...
```
It seems that the AppVeyor junit upload is using the type attribute, rather than the message attribute. These are defined in the schema as follows:

```
<xs:attribute name="message" type="xs:string">
  <xs:annotation>
    <xs:documentation xml:lang="en">The error message. e.g., if a java exception is thrown, the return value of getMessage()</xs:documentation>
  </xs:annotation>
</xs:attribute>
<xs:attribute name="type" type="xs:string" use="required">
  <xs:annotation>
    <xs:documentation xml:lang="en">The type of error that occured. e.g., if a java execption is thrown the full class name of the exception.</xs:documentation>
  </xs:annotation>
```
So the wrong attribute is being used here.

**Comment by IlyaFinkelshteyn** [comment]
Looking into this, thanks for reporting.

**Comment by IlyaFinkelshteyn** [comment]
@blairmcg Should be fixed now, thanks for reporting!

**Comment by blairmcg** [comment]
@IlyaFinkelshteyn, yes I can confirm it is working for me. Thanks.
