### ISSUE TITLE
Install MSYS2 in VS2017 image

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1693]

**Comment by XhmikosR** [comment]
@FeodorFitsner: any chance we could have this too?

**Comment by FeodorFitsner** [comment]
It's already installed in `C:\msys64` directory.

**Comment by tico-tico** [comment]
o_0 really? then please update your docs.

**Comment by IlyaFinkelshteyn** [comment]
it is [in docs](https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin)

**Comment by tico-tico** [comment]
I can't see a green dot in `MSYS2 (C:\msys64)` line under VS2017. Did I miss something?

**Comment by IlyaFinkelshteyn** [comment]
@tico-tico  sorry, you are rigt

**Comment by FeodorFitsner** [comment]
Docs have been updated.
