### ISSUE TITLE
CMake 3.9.1

### ISSUE THREAD

**Issue by jschueller** [appveyor/ci#1695]

**Comment by slokhorst** [comment]
Yes please! ["CUDA is now supported by the Visual Studio Generators for VS 2010 and above"](https://cmake.org/cmake/help/v3.9/release/3.9.html) is especially nice.

**Comment by IlyaFinkelshteyn** [comment]
We will hold on with CMake 3.9 for now until [this](http://help.appveyor.com/discussions/problems/7188-odd-cmake-build-failures-unrelated-to-code-changes) and [this](https://github.com/appveyor/ci/issues/1690#issuecomment-319074249) has any solution or workaround.

Error in both cases is `error MSB8013: This project doesn't contain the Configuration and Platform combination of <configuration>|<platform>.` with different Configuration and Platform in different cases.

**Comment by cenit** [comment]
make 3.9.1 is out, which fixed the problem!

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for update! We will install 3.9.1 on our image then.
