### ISSUE TITLE
cannot use mingw64

### ISSUE THREAD

**Issue by simonbyrne** [appveyor/ci#1698]
I keep getting the following error when attempting to use mingw64
```
gcc: CreateProcess: No such file or directory
```

Steps to reproduce:
```
set PATH="C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin";%PATH%
gcc hello.c
```
hello.c is from [here](https://www.programiz.com/c-programming/examples/print-sentence).

I get the same results with mingw installed from choco.

**Comment by IlyaFinkelshteyn** [comment]
Please remove double quotes from `set path` command.

**Comment by simonbyrne** [comment]
ah thanks :man_facepalming:
