### ISSUE TITLE
Git clone error in VS2017 image

### ISSUE THREAD

**Issue by slodki** [appveyor/ci#1700]
During **Clone** default step only in VS2017 image:

```
git clone -q --depth=10 --branch=appveyor-opt https://github.com/slodki/moneymanagerex.git C:\projects\moneymanagerex
fatal: Invalid path '/cygdrive/c/projects/moneymanagerex/C:\projects\moneymanagerex': No such file or directory
Command exited with code 128
```

No jobs can be started.

**Comment by FeodorFitsner** [comment]
Could you drop a link to a build please?

**Comment by slodki** [comment]
https://ci.appveyor.com/project/slodki/moneymanagerex/build/392

**Comment by slodki** [comment]
PATH variable breaks git:
```yml
environment:
  path: 'C:\cygwin64\bin;C:\cygwin\bin;%path%'
```

After change to
```yml
environment:
  path: '%path%;C:\cygwin64\bin;C:\cygwin\bin'
```
works.

So there is cygwin git version installed incompatible with Appveyor scripts.
Both cygwin64 and cygwin brake builds.

**Comment by FeodorFitsner** [comment]
OK, thanks for the update!

**Comment by IlyaFinkelshteyn** [comment]
@slodki if you still need initial order of variables you can do `set path=C:\cygwin64\bin;C:\cygwin\bin;%path% ` in `install` stage, which happens after Git clone.
