### ISSUE TITLE
DirectX SDK on Visual Studio 2017 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1721]
Related issue: https://github.com/appveyor/ci/issues/1386
Download page: https://www.microsoft.com/en-us/download/details.aspx?id=6812

Encountered "S1023" error while installing: https://support.microsoft.com/en-us/help/2728613/-s1023-error-when-you-install-the-directx-sdk-june-2010

Visual C++ 2010 SP1 Redistributable downloads:

* x86: http://www.microsoft.com/en-ca/download/details.aspx?id=8328
* x64: http://www.microsoft.com/en-ca/download/details.aspx?id=13523

**Comment by mirh** [comment]
I haven't checked personally, but if you could start the installer in unattended mode, then perhaps it might be possible to skip reinstalling steps.

**Comment by FeodorFitsner** [comment]
Interesting, will take a look.
