### ISSUE TITLE
Please update dotnet SDK to 2.0.0

### ISSUE THREAD

**Issue by WeihanLi** [appveyor/ci#1728]
I update my project to dotnet core 2.0,and build failed on appveyor,please update dotnet SDK to 2.0.0.
Or is there something I can do to set the dotnet sdk version??

**Comment by FeodorFitsner** [comment]
We are working on build worker image update: https://github.com/appveyor/ci/issues/1683

For now, you can install .NET Core SDK 2.0 during the build: https://github.com/paulcbetts/refit/blob/master/appveyor.yml#L7-L9

I'm going to close this issue as a duplicate.

**Comment by WeihanLi** [comment]
Thanks

**Comment by lemieuxs** [comment]
It takes for ever to install the sdk on each build.

Is there anyway to fast forward this request. Would be greatly appreciated.

![image](https://user-images.githubusercontent.com/10490601/29383211-8392fdba-829d-11e7-97a2-c1522c952523.png)

**Comment by IlyaFinkelshteyn** [comment]
Please watch https://github.com/appveyor/ci/issues/1729, it should be done soon.
