### ISSUE TITLE
.NET Core SDK 2.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1729]

**Comment by FeodorFitsner** [comment]
An updated `Visual Studio 2017` image has been published with .NET Core SDK 2.0.
`Visual Studio 2015` image is to be updated yet.

**Comment by tidusjar** [comment]
With the 2017 image my builds no longer work when attempting to restore my .Net core 1.1 project. Switching to the VS2015 image everything is fine.

I am using CAKE's DotNetRestore function. You can see the errors here: https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.1910

**Comment by dasjestyr** [comment]
I'm also having issues during the restore process. Here are a few lines where it starts to fail and I don't really understand them. This does not happen when built locally:

> Installing MSBump 2.1.0.
> Installing NETStandard.Library 2.0.0.
> Unable to resolve 'C:\projects\das-infrastructure\src\standard\DAS.Practices\DAS.Practices.csproj' for '.NETStandard,Version=v2.0'.
> Unable to resolve 'C:\projects\das-infrastructure\src\standard\DAS.Practices\DAS.Practices.csproj' for '.NETStandard,Version=v2.0'.

**Comment by FeodorFitsner** [comment]
@tidusjar Do you have `global.json` for pinning .NET Core SDK version: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?

**Comment by tidusjar** [comment]
@FeodorFitsner I do not. @dasjestyr you are having a different issue.

**Comment by FeodorFitsner** [comment]
@tidusjar try adding that to see if that works. Pinning SDK version is required if multiple SDKs installed.

**Comment by dasjestyr** [comment]
@FeodorFitsner  which versions are on that image? I notice that my build seems to be running 1.0.4 even when I specify 2.0.0 or 2.0.0-preview2-006497 in the global.json

**Comment by FeodorFitsner** [comment]
Do you use `Visual Studio 2017` image?

**Comment by dasjestyr** [comment]
I just removed the yaml file before i tried that and it reverted back to 2015. I thought to recheck it as soon as I asked the question, my bad lol

**Comment by tidusjar** [comment]
@FeodorFitsner I am now getting the following:

> The specified SDK version [1.1.0] from global.json [C:\projects\requestplex\global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by FeodorFitsner** [comment]
@tidusjar what build image do you use?

**Comment by tidusjar** [comment]
@FeodorFitsner 2015

**Comment by FeodorFitsner** [comment]
Can you please drop the contents of your global.json file?

**Comment by niemyjski** [comment]
I'm getting some pretty crazy errors while building (https://ci.appveyor.com/project/Exceptionless/exceptionless/build/4.1.2881) I'm targeting 2.0.0 of the sdk via global.json. Any ideas?
