### ISSUE TITLE
Download sporadically failing for Visual Studio 2015

### ISSUE THREAD

**Issue by hkaiser** [appveyor/ci#1739]
We're building our code base on both VS2015 and VS2017 images. Sporadically, the builds on VS2015 images fail because a file download complaining about not being able to connect to the server. See here for an example: https://ci.appveyor.com/project/hkaiser/hpx/build/master-550. Not sure how to further diagnose this...

**Comment by IlyaFinkelshteyn** [comment]
We recently expanded into new datacenter and it looks like firewall on `stellar-group.org` is blocking external IP address of that new location, while connections from old location are fine. Please check that all [those IPs](https://www.appveyor.com/docs/build-environment/#ip-addresses) are allowed. Most probably problem is with `67.225.139.254` which is recently added. Sorry for the trouble -- we are thinking how to notify people about such changes better, but without spamming.

**Comment by hkaiser** [comment]
I have no control over firewall setting as this is a hosting provider we use for those files. I will try to open a ticket with them, though.

**Comment by FeodorFitsner** [comment]
@hkaiser We'll investigate from our side too.

For a workaround you can download the file from our storage: https://storage.googleapis.com/appveyor-download-cache/hpx/vcpkg-export-hpx-dependencies.7z

**Comment by hkaiser** [comment]
@FeodorFitsner thanks! The hosting provider just told me that they have removed 67.225.139.254 from their list of blocked IP addresses. Let's see if the builds go through now.

**Comment by IlyaFinkelshteyn** [comment]
@hkaiser it would be great if your hosting provider elaborate the reason this address was blacklisted. This could help us preventing those cases in the future.

**Comment by hkaiser** [comment]
@IlyaFinkelshteyn I asked them and will convey back the information they will give me (if any). Thanks again!

**Comment by hkaiser** [comment]
This seems to be fixed now, thanks again for your help!
