### ISSUE TITLE
"443: Timed out" errors when connecting to GitHub

### ISSUE THREAD

**Issue by bkimminich** [appveyor/ci#1740]
My build https://ci.appveyor.com/project/bkimminich/juice-shop started failing frequently when trying to access GitHub. Sometimes this happens when trying to clone the repo itself, sometimes later in the process when resolving dependencies. See examples below:

```
Build started
git config --global core.autocrlf true
git clone -q https://github.com/bkimminich/juice-shop.git C:\projects\juice-shop
fatal: unable to access 'https://github.com/bkimminich/juice-shop.git/': Failed to connect to github.com port 443: Timed out
Command exited with code 128
```
(https://ci.appveyor.com/project/bkimminich/juice-shop/build/1716/job/uggcqccy4udxb406)

```
ttps://github.com/moment/moment.git", exit code of #128 fatal: unable to access 'https://github.com/moment/moment.git/': Failed to connect to github.com port 443: Timed out
Additional error details:
fatal: unable to access 'https://github.com/moment/moment.git/': Failed to connect to github.com port 443: Timed out
```
(https://ci.appveyor.com/project/bkimminich/juice-shop/build/1717/job/2gpsmmgclo021ukb)

```
https://github.com/lipis/flag-icon-css.git", exit code of #128 fatal: unable to access 'https://github.com/lipis/flag-icon-css.git/': Failed to connect to github.com port 443: Timed out
Additional error details:
fatal: unable to access 'https://github.com/lipis/flag-icon-css.git/': Failed to connect to github.com port 443: Timed out
```
(https://ci.appveyor.com/project/bkimminich/juice-shop/build/1715/job/tsmx5chh6ptktttv)

**Comment by IlyaFinkelshteyn** [comment]
It was connectivity issues on GitHub, please check recent status history https://status.github.com/messages

**Comment by bkimminich** [comment]
Seems all is back to normal, last build passed fine. Thanks!
