### ISSUE TITLE
Environments list needs filtering and grouping (like the Projects list)

### ISSUE THREAD

**Issue by andrewgunn** [appveyor/ci#1744]
Environments are great, until you've got loads of them and can't find the one you're looking for.

The [Environments list](https://ci.appveyor.com/environments) is a flat list of EVERY Environment. The only way to find a particular one is to use CTRL+F.

It'd be nice to see similar functionality that's available on the [Projects list](https://ci.appveyor.com/projects) - group Projects using tags and search by Project name. 

It'd also be nice to have a paged list.

**Comment by FeodorFitsner** [comment]
It's been deployed.

**Comment by DaveMiscampbell** [comment]
This is great but is there any chance of having more items per page? 10 seems like a super small number

**Comment by FeodorFitsner** [comment]
Absolutely, page size can be changed on https://ci.appveyor.com/profile
