### ISSUE TITLE
Commit message indentation is not retained

### ISSUE THREAD

**Issue by am11** [appveyor/ci#175]
It is very common to use markdown in commit messages. When we create a PR on GitHub with one commit, it shows the extended message in the description box.

On TravisCI, it retains the indentation of commit message:

![travis-commit-message](https://cloud.githubusercontent.com/assets/3840695/6543616/674b1778-c52b-11e4-976e-3fb2f1cfef62.PNG)

But AppVeyor does not retains this indentation:

![appveyor-commit-message](https://cloud.githubusercontent.com/assets/3840695/6543625/958cf7be-c52b-11e4-97a1-f812fb87d9f0.PNG)

**Comment by FeodorFitsner** [comment]
Will fix that.

**Comment by FeodorFitsner** [comment]
It's been fixed - will deploy update early next week:

![image](https://cloud.githubusercontent.com/assets/5041459/6549462/bccd0b20-c5d0-11e4-9fd2-1347aab81697.png)

**Comment by am11** [comment]
This is super fast! Thanks. :sunglasses: :+1:

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by am11** [comment]
Looking great! :+1:
