### ISSUE TITLE
refreshenv: deletes env var manually defined

### ISSUE THREAD

**Issue by mh-cbon** [appveyor/ci#1755]
in this build,

https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.208

`refreshenv` is called after some env vars are defined manually,

https://github.com/mh-cbon/go-msi/blob/9a855ad7ff53237575e69ffca34b03e2b641f661/appveyor.yml#L16
```yml
install:
  - set GH_APP=%APPVEYOR_PROJECT_NAME%
  - set GH_USER=%APPVEYOR_ACCOUNT_NAME%
  - set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - if "%x%"=="%VERSION%" set VERSION=1.0.2
  - set PATH=%WIX%\bin;%PATH%
  - set PATH=%GOPATH%\bin;%PATH%
  # - set PATH=%ProgramFiles%\changelog;%PATH%
  # - set PATH=%ProgramFiles%\gh-api-cli;%PATH%
  - choco install changelog gh-api-cli -y
  - refreshenv
```

It erased GOPATH, thus the build finishes with

```
glide install
'glide' is not recognized as an internal or external command,
operable program or batch file.
```

in this build, 
https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.209

it is applied before,
https://github.com/mh-cbon/go-msi/blob/daeee0e6196c47d6caf3f328b33d55d849fc9466/appveyor.yml#L16

it did not break 
https://ci.appveyor.com/project/mh-cbon/go-msi/build/1.0.209#L46

(it did break, but it does not matter here)

**Comment by IlyaFinkelshteyn** [comment]
This is know issue with `refreshenv`. It reloads `path` from registry, but `set path` command sets it only in current user session. You can run **changelog-specific** `set path` command after you install **changelog** with chocolatey or run all `set path` commands commands after `refreshenv`.

**Comment by mh-cbon** [comment]
confirmed.
