### ISSUE TITLE
Pre-installed software table doesn't list WinSDK 8.1 for VS2017 image

### ISSUE THREAD

**Issue by danilaml** [appveyor/ci#1768]
According to this https://github.com/appveyor/ci/issues/1694 it looks like Windows SDK 8.1 (crucial for targeting Windows Vista and up) is installed on VS2017 image (as it probably should be). But it is not lsited as installed software in https://www.appveyor.com/docs/build-environment/#pre-installed-software

**Comment by FeodorFitsner** [comment]
Docs have been corrected. Thanks for the catch.
