### ISSUE TITLE
AssemblyVersion, FileVersion, InformationalVersion to .csproj patching

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1772]
https://github.com/appveyor/ci/issues/1750#issuecomment-325274792
https://github.com/appveyor/ci/issues/1404#issuecomment-327189462

**Comment by IlyaFinkelshteyn** [comment]
@bramborman, @ig-sinicyn I did not find a lot of examples with those properties in `.csproj` online, so please check my sanity -- is [this](https://github.com/appveyor-tests/dotnetcore-patch-csproj) test good enough for this feature?

**Comment by ig-sinicyn** [comment]
@IlyaFinkelshteyn 
Yes, all version-related props are covered:)

**Comment by bramborman** [comment]
@IlyaFinkelshteyn Yeah, seems good to me too.

**Comment by nathanaeljones** [comment]
Waiting on this, as I want to use SemVer2, but AssemblyVersion and FileVersion require only numerical values.

**Comment by larsudengaard** [comment]
I need this too. Here my workaround for now:
```
before_build:
- cmd: dotnet restore
- ps: $path = (Get-Item .\Project\Project.csproj).FullName
- ps: $csproj = [xml](Get-Content $path)
- ps: $csproj.Project.PropertyGroup.AssemblyVersion = "$Env:APPVEYOR_BUILD_VERSION.0"
- ps: $csproj.Project.PropertyGroup.FileVersion = "$Env:APPVEYOR_BUILD_VERSION.0"
- ps: $csproj.Save($path)
```
Source: https://www.arthurrump.com/2017/03/17/visual-studio-2017-csproj-version-patching-in-appveyor/

Let me know if there is a better way 😃

**Comment by IlyaFinkelshteyn** [comment]
[Documentation updated](https://www.appveyor.com/docs/build-configuration/#net-core-csproj-files-patching)
