### ISSUE TITLE
Project X is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project X supports: netstandard2.0 (.NETStandard,Version=v2.0)

### ISSUE THREAD

**Issue by FacticiusVir** [appveyor/ci#1776]
I've just updated [my projects](https://ci.appveyor.com/project/FacticiusVir/sharpvk/build/Build%20233#L137) to .NET Standard 2.0 & Core 2.0, and while they build and run locally I get "Project is not compatible with netcoreapp2.0" errors in the AppVeyor build when referencing a .NET Standard 2.0 library from a .NET Core 2.0 console app.

**Comment by FacticiusVir** [comment]
For clarity, I've reproduced the issue with a stripped-down codebase: https://github.com/FacticiusVir/StandardTest with example build failure: https://ci.appveyor.com/project/FacticiusVir/standardtest

**Comment by IlyaFinkelshteyn** [comment]
Please check https://github.com/appveyor/ci/issues/1774

**Comment by FacticiusVir** [comment]
I saw that issue, and applied the fix to the SharpVk projects, but the error is still there - note that that issue related to package references, while mine is project dependencies within a solution.

**Comment by IlyaFinkelshteyn** [comment]
It [works for me](https://ci.appveyor.com/project/IlyaFinkelshteyn/standardtest/build/1.0.1) in my fork. Here is my configuration exported to YAML. You can press `Export YAML` in your project settings and compare.
```
version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
```

**Comment by FacticiusVir** [comment]
Okay, spotted the difference - I'd set the install & before_build scripts as Powershell, and they both had to be Cmd. Thanks for the help!
