### ISSUE TITLE
LLVM 5.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1778]

**Comment by andrewrk** [comment]
Here are instructions:

https://github.com/zig-lang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source#windows

**Comment by andrewrk** [comment]
Release mode recommended. This should ensure that we get clang headers (See #1514)
You could mirror the steps for LLD if you wanted to add that as well.
