### ISSUE TITLE
Re-build commit using the REST API

### ISSUE THREAD

**Issue by adigherman** [appveyor/ci#1779]
I'm using the REST API to (re)start build jobs for a specific commit ID but the new build although is created and runs normally, does not deploy although the original build was able to. 

`"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")` 

The structure of the request POST (to /api/builds) is :
```
{
    "accountName": "your-account-name",
    "projectSlug": "project-slug-from-url",
    "branch": "develop",
    "commitId": "3e9d9468"
}
```
Is there any way to also add a tag to this restarted build? I'm hoping this will re-enable deployment. Thanks!

**Comment by IlyaFinkelshteyn** [comment]
I think that this should work:

```
{
    "accountName": "your-account-name",
    "projectSlug": "project-slug-from-url",
    "branch": "develop",
    "commitId": "3e9d9468",
    "environmentVariables": {
       "appveyor_repo_tag": "true"
    }
}
```

**Comment by adigherman** [comment]
Thanks. I've tried it and I'm still not able to attach tags to the restarted builds. Here's the array I'm passing (after doing a `json_encode` on it):
```R
array(
   "accountName" => "XXX_account", 
   "projectSlug" => "repo_name", 
   "branch" => "branch_name", 
   "commitID" => "commit_ID", 
   "environmentVariables" => array(
         "appveyor_repo_tag" => "true",
         "appveyor_repo_tag_name" => "tag_string"
))
```
I've tried adding the `appveyor_repo_tag_name` variable to see if that works. The response I'm getting from `/api/builds` contains `"isTag":false`. Other than that the build is restarted, it just does not deply since it's not tagged. Any suggestions as to what else I can try next?

Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@adigherman Sorry, my bad, this environment variable is being overwritten. Do you need this only to restart deployment of the same bits? Do you actually need to rebuild or only re-deploy? If you need re-deploy only, maybe it would be better to use deployment Environment? Difference between Inline and Environment deployments is described [here](https://www.appveyor.com/docs/deployment/#overview).  Main idea behind deployment Environments is to decouple deployment from build. Please let me know what you think and maybe elaborate your scenario more.

**Comment by adigherman** [comment]
Thanks @IlyaFinkelshteyn! I am trying to code the "RE-BUILD COMMIT" from the package AppVeyor menu. It looks like if I click that, from within the AppVeyor website, the build is restarted, the tag is passed onto the new build and deployment is possible. The overall idea behind my task is to automate package checks for Neuroimaging packages and also provide a way to restart CI checks from our interface that include deployments. So it's a re-build & re-deploy combo.

**Comment by IlyaFinkelshteyn** [comment]
Actually you can do this with very simple request body:
```
{
    "buildId": "<tagged_build_id>",
}
```
**Important:** it should be `PUT` (not `POST`). `buildId` you can get from [project history](https://www.appveyor.com/docs/api/projects-builds/#get-project-history).

Sorry once again for misleading you initially.

**Comment by adigherman** [comment]
Excellent, this works. Thanks for all your help @IlyaFinkelshteyn!
