### ISSUE TITLE
Investigate ways to improve artifacts download speed

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#178]
Discussion: http://help.appveyor.com/discussions/problems/1713-slow-deploy

**Comment by tsolbjor** [comment]
Any progress on this?

**Comment by FeodorFitsner** [comment]
Yeah, actually it's been done already. Currently, artifacts are being downloaded directly from cloud storage (Azure or Google), so no AppVeyor in between.

**Comment by tsolbjor** [comment]
My artifacts seems to be downloaded from appveyorcidata.blob.core.windows.net, the download speed is ~100KB/s

**Comment by FeodorFitsner** [comment]
What location are you downloading them from?

**Comment by tsolbjor** [comment]
Im in Norway 

(using Chrome and click on the link on the Artifacts tab on Latest Build, but have the same experience using the Deployment Agent)

**Comment by FeodorFitsner** [comment]
We may try storing your artifacts on Google storage and see if that makes a difference. Let's continue over email. Could you please send as your AppVeyor account name to team@?
