### ISSUE TITLE
Miniconda2 4.3.27, Miniconda3 4.3.27

### ISSUE THREAD

**Issue by HazenBabcock** [appveyor/ci#1780]
My builds are breaking because Miniconda2 (64 bit) version 4.3.11 errors out when trying to install the pytest package.

```
conda config --add channels conda-forge
conda install --yes pytest
Fetching package metadata .............
Solving package specifications: .
ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'conda-forge::pytest-3.2.2-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda-x64\lib\site-packages\conda\resources\cli-64.exe
Attempting to roll back.
```

I'd appreciate it if you could update the pre-installed Miniconda2 to the current version (4.3.21), which does not seem to have this problem. Thanks!

**Comment by FeodorFitsner** [comment]
It's been scheduled for the next image update.

**Comment by HazenBabcock** [comment]
Great, thanks!

**Comment by FeodorFitsner** [comment]
We'll close the issue when it's deployed.

**Comment by tdaff** [comment]
Is there an ETA on this?

Thanks!

**Comment by FeodorFitsner** [comment]
Yes - this week or early next week. Sorry for the delay - we need some more time to test a few things.
