### ISSUE TITLE
Add app_offline support to Deployment Agents

### ISSUE THREAD

**Issue by ondrejpialek** [appveyor/ci#1781]
I am getting the following error:

>Web Deploy cannot modify the file 'MyLib.dll' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.

Standard WebDeploy Environment supports an `app_offline` switch to drop the app_offline.htm file into the app's root. Could this be added to Deployment Agents too?

I know that as a workaround I can use the pre & post deploy scripts.

**Comment by IlyaFinkelshteyn** [comment]
Yes, we can do that.

**Comment by IlyaFinkelshteyn** [comment]
@ondrejpialek you need to download and install latest agent
