### ISSUE TITLE
Built-in Bash support is broken

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1782]
With the latest Git 2.14.1 update calling any `.sh` script fails with `Command exited with code -1073741819`.
Looks like `C:\Program Files\Git\git-bash.exe` is the root cause as downgrading to 2.13.1 fixes the issue.

As a fix we are changing association for `.sh` files to use `bash.exe` from msys64:

```posh
cmd /c ftype sh_auto_file="C:\msys64\usr\bin\bash.exe" "`"%L`"" %* | out-null
```

**Comment by FeodorFitsner** [comment]
Related git issue: https://github.com/git-for-windows/git/issues/1293

**Comment by MSP-Greg** [comment]
@FeodorFitsner 

Just a reminder that Git is now at 2.14.2.  As I mentioned in the Ruby doc, there are a lot of similar files with 'bash' layers.

See C:\Program Files\Git\usr\bin and C:\msys64\usr\bin.  Whether this might affect this issue...
