### ISSUE TITLE
TypeScript 2.5.2 for Visual Studio 2015/2017

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1785]
[Discussion](http://help.appveyor.com/discussions/problems/7859-typescript-problems-on-vs2017-build)

Download location: https://blogs.msdn.microsoft.com/typescript/2017/08/31/announcing-typescript-2-5/

**Comment by cyberzed** [comment]
Is there a more public way to see the progress on this one, we are planning to upgrade to either 2.4 or 2.5 next month so I'm just early checking out if it is supported

**Comment by IlyaFinkelshteyn** [comment]
@cyberzed We track everything on GitHub, you should get notification when this issue status changed...

**Comment by cyberzed** [comment]
@IlyaFinkelshteyn my bad phrasing...was just curious what was in the discussion that was linked 😄

**Comment by IlyaFinkelshteyn** [comment]
Oh, it appears to be private discussion on our support forum, I did not notice that this is private when I linked it. There are nothing very special other than request to install TypeScript 2.5.2 there :)

**Comment by cyberzed** [comment]
@IlyaFinkelshteyn alright as long as TS 2.5 is ready sometime in October I'm happy 🚀

**Comment by cyberzed** [comment]
I assumed it was upgraded on the VS2017 but when we test our dev-branch in a build we see this...

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript\Microsoft.TypeScript.targets(68,5): warning : Your project specifies TypeScriptToolsVersion 2.5, but a matching compiler was not found. The latest available TypeScript compiler will be used (2.3). To remove this warning, install the TypeScript 2.5 SDK or update the value of TypeScriptToolsVersion.`

**Comment by FeodorFitsner** [comment]
It's not yet delivered. ETA for this update is this week.

**Comment by cyberzed** [comment]
Alright, that should be ok for us to await :)
