### ISSUE TITLE
VSTS - Commit Number URL is Incorrect on Build Page

### ISSUE THREAD

**Issue by jruckert** [appveyor/ci#1786]
Hi,

This is for Visual Studio online only, When we click on the "Commit Number" next to the branch on the build pages, it always defaults part of the URL to "DefaultCollection", but we are running multiple projects with different "Project/Team Names".

e.g it shows as

https://<tenant>.visualstudio.com/DefaultCollection/_git

but in our case should be

https://<tenant>.visualstudio.com/<project/teamname>/_git

Is this a problem with VSTS or AppVeyor?

Cheers, 
Jonathan

**Comment by IlyaFinkelshteyn** [comment]
@jruckert can you please check now?

**Comment by jruckert** [comment]
Works like a charm! Thanks for getting this fixed.
