### ISSUE TITLE
Enable secure variables for PRs

### ISSUE THREAD

**Issue by nemakam** [appveyor/ci#1788]
Related to #917 

Is there an admin way to enable secure variables for all PRs for a public repo? Even for pull requests from a forked repo?
We have tests that we need to run before we can complete the PRs. My plan is to have a build script (powershell) which reads values from environment variables and then updates the environment variable values with garbage before build is even triggered. So this way, even if tests try to read those secure variables, they would just get garbage, and I would have access to the variables. 
The plan is to `Ignore appveyor.xml` and then have entire logic put in through a build script in UI.

**Comment by IlyaFinkelshteyn** [comment]
We do not have such plans because it opens too much security vulnerabilities. But let us think what workaround can we do here. As I understand secure variable are going to be used in your script, because after that they will be unusable. What this script will do besides reading secure variables value and replacing them with garbage?

**Comment by IlyaFinkelshteyn** [comment]
Actually, as long as you plan to set `Ignore appveyor.xml`, why those variables have to be secure at all? They can be normal variables your script can read, when whatever it needs to do and then replace with garbage, right?

**Comment by nemakam** [comment]
@IlyaFinkelshteyn , so this is how my script currently is

$secret = [Environment]::GetEnvironmentVariable('secretValue')
[Environment]::SetEnvironmentVariable('secretValue', ' ')

msbuild.exe myRepo.sln
-------------------
// Use $secret here to initialize our test bed on azure
----------------
dotnet test .\test\test.csproj
-------------------
// Use $secret here to delete our test bed on azure
----------------

**Comment by nemakam** [comment]
> Actually, as long as you plan to set Ignore appveyor.xml, why those variables have to be secure at all? They can be normal variables your script can read, when whatever it needs to do and then replace with garbage, right?

That is how I'm currently using it. I wasn't sure what the implications of not marking them as secure would be.
What are your opinions on the script layout above?

**Comment by nemakam** [comment]
Also, do you know if the environment variables are set at user level, process level or machine level?

**Comment by IlyaFinkelshteyn** [comment]
Process. This is pretty safe. To avoid usage of Azure secrets at all, you can create separate AppVeyor project, with secure variables, and make this project just initialize your Azure test bed. Then create user with role which has the only one permission "Run project builds".  Use that user access token to start that separate AppVeyor project from your script. Accidentally exposing API access token of that restricted user is less risk than exposing Azure secrets. But honestly for me it is overkill.

**Comment by IlyaFinkelshteyn** [comment]
Also, as long as your script is all in UI, why bother with environment variables and not hard-code secrets in that script in UI?

**Comment by IlyaFinkelshteyn** [comment]
Disregard last one, thus they can be exposed in the screen.

**Comment by nemakam** [comment]
Cool. In my opinion as well, it might be overkill. I'll go ahead with my current setup. Will get back if it doesn't work out for me. Thanks..
