### ISSUE TITLE
Clone tag if specified in webhook ref field

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1789]
W have to use tag name with `--branch` parameter in `git clone` command if tag is specified in `ref` filed. Right now we use the from `base_ref` if it exists.

**Comment by gep13** [comment]
@IlyaFinkelshteyn Thank you for looks at this!  Was this due to a change in the webhook content being sent over from GitHub?

**Comment by IlyaFinkelshteyn** [comment]
@gep13 we are not aware of any change in the GitHub webhook content. It just recently exposed that our logic for `git clone` is not exactly correct. In case build is tagged, we use branch name from the `base_ref`, if it not empty and tag name from `ref` if `base_ref` is empty. We will still use the same logic to define branch name, but for the  `--branch` parameter in `git clone` command we will use tag name if it exist and branch name if tag does not exist. This issue did not manifest itself very often because in many cases with tagged build `base_ref` is empty and branch name naturally became the same as tag name.

**Comment by gep13** [comment]
@IlyaFinkelshteyn gotcha, I understand.  The reason that I asked is that we use the concept of "if you master branch and tagged" do some additional work in our builds.  However, two different people on the same day, on different projects, reported issues where the tag was being reported as coming from the develop branch, when in actual fact it was coming from master.

From the outside, it seemed like something must have changed from the GitHub side of things.

**Comment by gep13** [comment]
@FeodorFitsner has this shipped? The milestone name would suggest it should have, thanks.

**Comment by FeodorFitsner** [comment]
Not yet. Going to deliver it this week.

**Comment by gep13** [comment]
@FeodorFitsner great news, thank you!

**Comment by IlyaFinkelshteyn** [comment]
Fix is deployed.
