### ISSUE TITLE
RubyInstaller-2.4.2-2 available

### ISSUE THREAD

**Issue by larskanis** [appveyor/ci#1790]
RubyInstaller-2.4.2-2 [is released](https://rubyinstaller.org/2017/09/15/rubyinstaller-2.4.2-2-released.html) today. It fixes several [bugs](https://github.com/oneclick/rubyinstaller2/issues/68) and issues partly related to Appveyor. Please update the pre-installed RubyInstaller version in the Appveyor image! Thank you!

**Comment by MSP-Greg** [comment]
@FeodorFitsner 

Thanks for this also...

**Comment by MSP-Greg** [comment]
@FeodorFitsner

I've got some utilities that I run on AV, and the 2.4.2 files look somewhat odd.  Was it by chance an 'in-place' update, or was the old version removed first?

The AV build shows:

```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
bigdecimal (1.3.0)
bundler (1.15.4, 1.15.1)
did_you_mean (1.1.0)
io-console (0.4.6)
json (2.0.4, 2.0.2)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (2.0.5, 2.0.3)
power_assert (0.4.1)
psych (2.2.2)
rake (12.0.0)
rdoc (5.0.0)
rubygems-update (2.6.13, 2.6.12)
test-unit (3.2.3)
xmlrpc (0.2.1)
```

Notice that several gems have two versions.

My local build shows:

```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
gem --version -> 2.6.13
bigdecimal (default: 1.3.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.4)
mini_portile2 (2.3.0)
minitest (5.10.1)
net-telnet (0.1.1)
nokogiri (1.8.1)
openssl (default: 2.0.5)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)
```

I believe a fresh install and the following are all that's needed:

1. `gem update --system`
2. `gem install bundler`
3. `gem uninstall rubygems-update`

I think (off the top of my head) that there were some 'windows specific' updates in rubygems 2.6.14...

FYI, since you'll probably be installing ruby 2.5 in a couple of months, bundler is now included.

Thanks again,  Greg

**Comment by FeodorFitsner** [comment]
Do you have a test build that produces the result like that?

**Comment by larskanis** [comment]
Thanks for updating ruby-2.4! I successfully updated [some](https://github.com/larskanis/pkcs11) [gems](https://github.com/larskanis/ruby-pg) which require the new version.

IMHO the ruby setup is OK how it is. All versions are as expected for me. There is nothing wrong with having several gem versions installed. This the expected behavior for a rubyinstaller update. Removing gem versions while the update could break dependencies in Gemfile.lock.

**Comment by MSP-Greg** [comment]
@FeodorFitsner 

We may have decided a full replace is more in order.  Re a test build, I've got a start on one [here](https://ci.appveyor.com/project/MSP-Greg/testing-appveyor/build/1).  Took 49 seconds (for both 32 & 64).  Does the following:

1. Download both versions.
2. Prep for install with RubyGems update, Bundler install, etc.
3. Renames outdated version folder.
4. Moves/renames new version.
5. Deletes downloads & outdated versions.
6. Checks common CLI files.
6. Prints configuration.

Uses one cmd file and two ruby files.  To install a version, it just takes a few changes to [appveyor.yml](https://github.com/MSP-Greg/testing-appveyor/blob/master/appveyor.yml).  I left the yml file kind of 'commandy', as I wasn't sure whether it would be used.  FYI, the files are in my 'testing' repo, so it contains several more  files...

Thanks, Greg

**Comment by MSP-Greg** [comment]
@FeodorFitsner

I just updated my [Appveyor Ruby](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby) project, it now shows multiple gem versions.

Comparing 2.4.2 with all other versions (or the version shown [here](https://ci.appveyor.com/project/MSP-Greg/testing-appveyor/build/1))...

I don't know how you prefer to update images, Running scripts in the cloud (no UI), pushing files from a local system, etc.

Whatever you prefer, I think @larskanis and I will be willing to help so that future updates are as simple (and fast) as possible.

**Comment by FeodorFitsner** [comment]
Thanks guys for your feedback!

I don't understand how it happens 2.4 installation has double versions of bundler and gem.

In our Ruby installation script we just do this right after Ruby installation:

```
gem install rubygems-update --no-ri --no-rdoc
update_rubygems
gem update --system

gem install bundler --no-ri --no-rdoc
```

Then we make sure correct versions installed by:

```
ruby --version
gem --version
bundler --version
```

Is it 2.4 only behavior? Do we need to uninstall default gems first?

**Comment by MSP-Greg** [comment]
@FeodorFitsner

The critical issue is how are you installing the new version of Ruby?  It looks like you're extracting the  rubyinstaller-2.4.2-2-*.7z files over the old installs?

If that's the case, non-default gems will not overwrite other gems, iow, there may be duplicates.

Default gems will overwrite the code for previous versions, but multiple gemspec files may still exist. 
 Hence, the duplicate listing for json & openssl.

> I don't understand how it happens 2.4 installation has double versions of bundler and gem.

`gem install` will not remove previous versions, [`gem cleanup`](https://msp-greg.github.io/ruby_trunk/rubygems/file.command-reference.html#gem-cleanup) needs to be run to do that.

The `rubygems-update` gems that are listed are a byproduct of updating rubygems.  They can be uninstalled ([`gem uninstall rubygems-update -all`](https://msp-greg.github.io/ruby_trunk/rubygems/file.command-reference.html#gem-uninstall)) once the update is finished.  I believe you can remove the last line of:

```
gem install rubygems-update --no-ri --no-rdoc
update_rubygems
gem update --system
```

The first two lines accomplish the same thing as the last line.  But the `gem update --system` has not always worked across all Ruby/RubyGems combinations...

> Then we make sure correct versions installed by:

Just for good measure, you might add `rake -V` to that.

FYI, [Travis info on Ruby builds](https://travis-ci.org/MSP-Greg/travis-ruby), [Appveyor info on Ruby builds](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby).  Travis ruby-head is broke...

**Comment by FeodorFitsner** [comment]
This is how we do Ruby 2.4 installation (excerpt):

```posh
cmd /c start /wait $exePath /verysilent /dir="$($ruby.install_path.replace('\', '/'))" /tasks="noassocfiles,nomodpath,noridkinstall"
```

However, unlike with pre-2.4 Rubys coming in .7z archives we do not uninstall/delete previous 2.4 installation assuming the installer will do that for us. Or this assumption is incorrect and we do need to uninstall previous 2.4 first?

**Comment by MSP-Greg** [comment]
I work almost exclusively with trunk.  I'll defer to @larskanis on that question.  I know he mentioned working on some updates to the installer package...
