### ISSUE TITLE
Update MSYS64

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1799]
MinGW OpenSSL 1.0.2l

[Discussion](http://help.appveyor.com/discussions/suggestions/2726-request-for-install-mingw-openssl-102l-update-to-102k)

update script:

```
  - set PATH=C:\msys64\usr\bin;C:\ruby%RUBY_VERSION%\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows
  - pacman -Syuu --noconfirm
  - echo %ERRORLEVEL%
  - pacman -Suu --noconfirm
```

Original post: https://github.com/appveyor/ci/issues/1822#issuecomment-333336660

**Comment by MSP-Greg** [comment]
@FeodorFitsner

MinGW OpenSSL 1.0.2 => Update MSYS64

That's my preference, but I wasn't going to ask for that...

Thank you for supporting OSS.

**Comment by solenwin2** [comment]
readme_eddit

**Comment by MSP-Greg** [comment]
@FeodorFitsner

Thank you.  All okay from my perspective...
