### ISSUE TITLE
Incorrect branches for GitHub webhooks

### ISSUE THREAD

**Issue by 3F** [appveyor/ci#1801]
```
git push master exp_map dev_v2
```

* dev_v2 `0cf0a3ae`
* master `4f806c75`
* exp_map `b1a61716`

https://ci.appveyor.com/project/3Fs/mvssln/build/build-19 - master `4f806c75`
https://ci.appveyor.com/project/3Fs/mvssln/build/build-20 - master `4f806c75`
https://ci.appveyor.com/project/3Fs/mvssln/build/build-21 - master `4f806c75`

that is, for all this has been placed the following command:
```
git clone -q --branch=master ...
```

here https://ci.appveyor.com/project/3Fs/dllexport/history was ok at least for:
```
git push exp_38_gnt master
```

some new changes or a bug ? o_O

**Comment by IlyaFinkelshteyn** [comment]
Those 3 builds seems to be started manually, not with as a result of webhooks. To benefit from GitHub integration, AppVeyor project should be created as a `GitHub`, but this project is created as a generic `git` one.

**Comment by 3F** [comment]
http://help.appveyor.com/discussions/questions/1983-how-to-change-bitbucket-repository-on-similar-repo-from-github

why you don't want to support this for your `git repository` type ?

```
X-GitHub-Delivery: 91a3f086-9d4a-11e7-8f0a-b6c3fa4a77df
"ref": "refs/heads/dev_v2",
...
```

```
X-GitHub-Delivery: 917a5cc6-9d4a-11e7-8375-ac9f1da32ee1
"ref": "refs/heads/master",
...
```

```
X-GitHub-Delivery: 90d7036e-9d4a-11e7-833a-6af38efb2830
"ref": "refs/heads/exp_map",
...
```

**Comment by 3F** [comment]
btw, now it also does not work for single branch:
```
git push <any_other_branch>
```

```
git push dev
```

still starts from `master` >(  please return it back as before !

**Comment by IlyaFinkelshteyn** [comment]
I am not aware of any changes. Please send us link to specific build to check.

**Comment by 3F** [comment]
https://ci.appveyor.com/project/3Fs/mvssln/build/build-22

pushed as `git push dev_v2`


why it still `git clone -q --branch=master ...` ?!


check it:
```
2017-09-27 17:33:39
User-Agent: GitHub-Hookshot/f767822
X-GitHub-Delivery: da98d83c-a390-11e7-9138-51145d4cd666
...
"ref": "refs/heads/dev_v2",
```

?

for 2+ years I don't remember similar problems, I have a lot of other projects that was linked to AppVeyor:
see https://ci.appveyor.com/project/3Fs

**Comment by IlyaFinkelshteyn** [comment]
[Commit](https://github.com/3F/MvsSln/commit/22d27731a461ed0597fd587e35380ef32dea5834) was done 2 days ago, while build started 7 hours ago. And I do not see webhook coming in our logs before that build. Which means that build was not triggered by webhook.

**Comment by 3F** [comment]
because it was in my local repo and pushed only after (that is, separately, if you can't support `git push master dev_v2` today)

see hook:
```
User-Agent: GitHub-Hookshot/f767822
X-GitHub-Delivery: e561208a-a390-11e7-9efa-d2d6f9de4358
```

**Comment by IlyaFinkelshteyn** [comment]
When in GitHub's recent deliveries it was sent (exact time with time zone)? What you see if you redeliver it?

**Comment by 3F** [comment]
> What you see if you redeliver it?

please clarify, what do you need ?

1. dev_v2 in 2017-09-27 17:33:39  - first push
2. master in 2017-09-27 17:33:57  - second

![recent_deliveries](https://user-images.githubusercontent.com/3246589/30940956-d6bd9d46-a3eb-11e7-840c-55c573c5ef5a.png)

**Comment by IlyaFinkelshteyn** [comment]
The one you do not see expected results, probably `dev_v2`

**Comment by IlyaFinkelshteyn** [comment]
Also I do not see a time zone so I cannot check my logs for previous deliveries

**Comment by 3F** [comment]
I clicked "Redeliver" and yes it still master, so... what's going on o_O

**Comment by IlyaFinkelshteyn** [comment]
please send specific time **with time zone** and GitHub delivery id

**Comment by IlyaFinkelshteyn** [comment]
Disregard, I see it. 5 sec

**Comment by IlyaFinkelshteyn** [comment]
Sorry I still need GitHub delivery id for webhooks you resent

**Comment by 3F** [comment]
>please send specific time with time zone

where I should to look this ? 

```
X-GitHub-Delivery: e561208a-a390-11e7-9efa-d2d6f9de4358

    "created_at": 1497814220,
    "updated_at": "2017-07-09T21:22:28Z",
    "pushed_at": 1506522837,
    
  Response: 
     Date: Wed, 27 Sep 2017 22:32:49 GMT
     
```

```
X-GitHub-Delivery: da98d83c-a390-11e7-9138-51145d4cd666

    "created_at": 1497814220,
    "updated_at": "2017-07-09T21:22:28Z",
    "pushed_at": 1506522819,
   
   Response:    
     Date: Wed, 27 Sep 2017 22:31:42 GMT

```

**Comment by 3F** [comment]
> Sorry I still need GitHub delivery id for webhooks you resent

*missed reply*


you about webhook id from appveyor ?

```
Request URL: https://ci.appveyor.com/api/git/webhook?id=d5bb7dfdtma1fv01
```

or I don't understand, thye **GitHub delivery id** isn't this id:
`e561208a-a390-11e7-9efa-d2d6f9de4358` and `da98d83c-a390-11e7-9138-51145d4cd666` ?

**Comment by IlyaFinkelshteyn** [comment]
It is not very safe to expose your webhook id, sorry for now asking clearly. We reset your webhook id, you can find in in project settings.

As for main problem, reason is that your webhook is ignored, because content type should be set to `application/json` for generic Git webhook. It is probably set to `application/x-www-form-urlencoded`

**Comment by 3F** [comment]
just noticed :)

yes, content type for this old projects - `application/json`:

* https://github.com/3F/Conari
* https://github.com/3F/vsSolutionBuildEvent
...

and yes `application/x-www-form-urlencoded` for this problem.

I updated webhook id and changed type to json, now it seems have a correct branch:

https://ci.appveyor.com/project/3Fs/mvssln/build/build-26

so probably it should work also for several branch as `git push b1 b2 b3` I'll check it later.
