### ISSUE TITLE
Unable to add AppVeyor to Github organization

### ISSUE THREAD

**Issue by mcollina** [appveyor/ci#1803]
I'm getting 

<img width="1034" alt="schermata 2017-09-20 alle 10 38 46" src="https://user-images.githubusercontent.com/52195/30634840-b6bb6ae2-9df0-11e7-8f79-23d906b71bd6.png">

after I go through the marketplace signup process.

AppVeyor is granted on the github organization side.

https://github.com/fastify/fastify/issues/256

I have also tried signing up for a new account, but I couldn't see the repos as well.

https://github.com/fastify/fastify/issues/256

**Comment by FeodorFitsner** [comment]
Will take a look.

Are you able to signup from this page with GitHub button: https://ci.appveyor.com/signup ?

**Comment by mcollina** [comment]
I see various accounts, including mine. When I click "new project", I can't see Fastify repositories.

**Comment by IlyaFinkelshteyn** [comment]
@mcollina Please open your GitHub account settings > **Authorized OAuth Apps** > **AppVeyor CI** and check **Organization access**

**Comment by mcollina** [comment]
Thanks it worked!
