### ISSUE TITLE
mingw-w64 seems to crash on exceptions

### ISSUE THREAD

**Issue by Luthaf** [appveyor/ci#1804]
So I have a weird issue with the provided mingw-w64 compilers (in `c:\mingw-w64`): building the same commit worked fine a month ago (https://ci.appveyor.com/project/Luthaf/chemfiles/build/720), but the exact same code/appveyor.yml is now crashing (https://ci.appveyor.com/project/Luthaf/chemfiles/build/738).

It looks like C++ code compiled with is crashing when an exception is thrown: the exception is not caught (`catch` blocks are ignored), and thus abort is called. That all I could see by stepping in the code with remote desktop access and gdb. I am saying it *looks like* because I could not reproduce this failure in a simple example. But the fact that the same commit was fine a month ago is puzzling. I could also not reproduce this on local virtual machines.

Did anything changed in the build environment since last month ?

**Comment by IlyaFinkelshteyn** [comment]
It seems related to [cmake update happened recently](https://github.com/appveyor/ci/issues/1695). I was able to make it work in my fork by adding PowerShell script with this content to `install` stage:

```
$cmakeUninstallPath = "${env:ProgramFiles(x86)}\CMake\Uninstall.exe"
if([IO.File]::Exists($cmakeUninstallPath)) {
    Write-Host "Uninstalling previous CMake ..." -ForegroundColor Cyan
    # uninstall existent
    "`"$cmakeUninstallPath`" /S" | out-file ".\uninstall-cmake.cmd" -Encoding ASCII
    & .\uninstall-cmake.cmd
    del .\uninstall-cmake.cmd
    Start-Sleep -s 10
}

Write-Host "Installing CMake 3.8.2 ..." -ForegroundColor Cyan
$msiPath = "$($env:TEMP)\cmake-3.8.2-win32-x86.msi"

Write-Host "Downloading..."
(New-Object Net.WebClient).DownloadFile('https://cmake.org/files/v3.8/cmake-3.8.2-win32-x86.msi', $msiPath)

Write-Host "Installing..."
cmd /c start /wait msiexec /i $msiPath /quiet
del $msiPath

Add-Path 'C:\Program Files (x86)\CMake\bin'

remove-path 'C:\ProgramData\chocolatey\bin'
add-path 'C:\ProgramData\chocolatey\bin'

Write-Host "CMake 3.8.2 installed" -ForegroundColor Green
```

I also tried cmake 3.9.2, but that did not help. I am not sure if this is test or cmake issue. But you have a workaround for now.

**Comment by Luthaf** [comment]
Wow, thank you very much ! I followed your work through email notifications, this is really nice of you !

**Comment by IlyaFinkelshteyn** [comment]
Welcome :)
