### ISSUE TITLE
Improve performance of tests page

### ISSUE THREAD

**Issue by 304NotModified** [appveyor/ci#1807]
I would be nice if the performance of the test page could be improved. 

With many tests (4K) it takes 10-30 sec, on mobile it takes sometimes a minute:

https://ci.appveyor.com/project/nlog/nlog/build/4.5.0-beta6146/tests

To improve the performance, I was thinking of the following possibilities:

- Show the results paged and/or
- Show only failed tests by default, and/or
- Use a faster framework: https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html

NB: as there is (currently) no search, it should be still possible to show all results in one page.

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of more general https://github.com/appveyor/ci/issues/1708
