### ISSUE TITLE
SourceForge downloads stopped working

### ISSUE THREAD

**Issue by carlosperate** [appveyor/ci#1813]
https://ci.appveyor.com/project/carlosperate/pyqtconsole-test/build/1.0.19#L39

```
Start-FileDownload 'http://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe' -FileName pyqt5_installer.exe -Timeout 600000
Downloading pyqt5_installer.exe (652 bytes)...100%
pyqt5_installer.exe /S
The system cannot execute the specified program.
Command exited with code 1
```

Note the size of the file (652 bytes).

Also discussed in the support forum: http://help.appveyor.com/discussions/problems/8155-not-recognized-as-an-internal-or-external-command-graphicsmagic-recently-failed-to-install-on-appveyor

**Comment by gep13** [comment]
@carlosperate we show a similar problem on our automatic package creation tool:

https://github.com/chocolatey/chocolatey-coreteampackages/issues/854#issuecomment-332422549

**Comment by carlosperate** [comment]
Is it a problem with SourceForge itself then? Whatever server I get directed to from my location it seems to serve http://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe correctly.

**Comment by IlyaFinkelshteyn** [comment]
Google search for 'SourceForge status" returns [this](https://twitter.com/sfnet_ops/status/913044025791467520?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet)

**Comment by carlosperate** [comment]
Thanks, I guess we'll have to wait it out.

**Comment by IlyaFinkelshteyn** [comment]
Consider [build cache](https://www.appveyor.com/docs/build-cache/) to depend on the "other side" less

**Comment by carlosperate** [comment]
Thanks @IlyaFinkelshteyn, that's been on my to-do list for a while, will definitely push it to the top after this.

**Comment by carlosperate** [comment]
Look like it's back to normal https://twitter.com/sfnet_ops/status/913183031111929857
