### ISSUE TITLE
Error 400 returned by nuget publishing for some customers

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1825]
[Discussion](http://help.appveyor.com/discussions/problems/8215-cannot-publish-to-nuget-get-400-bad-request-error)

**Comment by yaakov-h** [comment]
How can I use the workaround from the discussion linked above if my `appveyor.yml` file has multiple `deploy` items? Does the `deploy_script` replace both?

**Comment by IlyaFinkelshteyn** [comment]
@yaakov-h  `deploy_script` and `deploy` are mutually exclusive, but you can do this nuget workaround as `after_deploy` script in your case.

**Comment by baynezy** [comment]
@IlyaFinkelshteyn - any update on this? On the forum discussion you intimated that is would take about a week to fix. That was 9 days ago.

Thanks.

**Comment by IlyaFinkelshteyn** [comment]
Sorry we planned to update last weekend, but found blocking issues and postpones this to the next weekend.

**Comment by anangaur** [comment]
@IlyaFinkelshteyn If you are blocked on anything from NuGet, do let me know. I see some people are hitting this issue again including @tathamoddie. 
https://github.com/NuGet/Announcements/issues/10 should have all the information you need.

**Comment by IlyaFinkelshteyn** [comment]
@anangaur fix was deployed this weekend. However this is still the same workaround when we fallback to `nuget.exe` if API call do not work. Proper fix is tracked in https://github.com/appveyor/ci/issues/1845.
