### ISSUE TITLE
Specify a project or solution file. The directory does not contain a project or solution file error

### ISSUE THREAD

**Issue by tuananh** [appveyor/ci#1827]
This issue is happening intermittently.

This one failed: https://ci.appveyor.com/project/tuananh/camaro/build/1.0.230-master
while this one work: https://ci.appveyor.com/project/tuananh/camaro/build/1.0.227-master

same commit.

**Comment by IlyaFinkelshteyn** [comment]
Where this `build\binding.sln` comes from? It is solution file [detected and build by AppVeyor](build\binding.sln), but I do not see it in [your repo](https://github.com/tuananh/camaro). It is somehow downloaded at `install` stage?

**Comment by tuananh** [comment]
It's in submodule.

**Comment by tuananh** [comment]
it's generated by node-pre-gyp i think

**Comment by IlyaFinkelshteyn** [comment]
By default AppVeyor works in "Msbuild" mode, it searches for `.sln` or `.csproj` files and tries to build it.  If `.sln` or `.csproj` files cannot be found (in your case it was not downloaded by npm), error described above happens. I have no idea why `.sln` file should be in this module at all and if you really need to build it. Usually people build source code cloned from repo, not node modules content. To disable default "Msbuild" mode, you should remove this:

```
build:
  parallel: true
  verbosity: minimal
```

and use `build_script` if needed.  My theory that this `.sln` file never supposed to be in that module. It was there by mistake and AppVeyor (in default "Msbuild" mode) was happy. Now module authors probably realized that mistake and removed unneeded files from it, which broke your build.

For future I would recommend to use as simple `appveyor.yml` as possible and leave only part you really need.

**Comment by tuananh** [comment]
I copied it from another project. some of it i don't quite understand. lemme try removing it.

**Comment by IlyaFinkelshteyn** [comment]
You can always configure build from UI and then press `Export YAML`, result will be much simpler.

**Comment by tuananh** [comment]
Many thanks. It's working now.
