### ISSUE TITLE
Qt 5.9.1 msvc2015 32-bit on Visual Studio 2017 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1832]
Completing Qt 5.9.1 installation on VS 2017 according to this note: https://github.com/appveyor/ci/issues/1588#issuecomment-333625711

Directory `C:\Qt\5.9.1\msvc2015` is missing on VS 2017 image.

**Comment by charliewolf** [comment]
Been blocked by this for a couple months, any ETA?

**Comment by charliewolf** [comment]
Any progress on this one?

**Comment by FeodorFitsner** [comment]
Yes, sorry for the delay with that. We are going to publish image early next week. There were a couple of last minute issues.

**Comment by charliewolf** [comment]
revised ETA?

**Comment by FeodorFitsner** [comment]
It’s been added to VS 2017 image. Give it a try and let us know if that worked.

**Comment by jrfonseca** [comment]
It took me a while, but I finally updated and verified -- https://ci.appveyor.com/project/jrfonseca/apitrace/build/556 .  Thanks!
