### ISSUE TITLE
Update windowsservercore docker image to 10.0.14393.1715 or later

### ISSUE THREAD

**Issue by donny-dont** [appveyor/ci#1839]
I'm attempting to use appveyor to push a docker image for building WebKit on Windows and need to install Visual Studio 2017 on the image. There is a known issue with `microsoft/windowsservercore:10.0.14393.1593` where the bootstrapper fails to launch the process which is the current version packaged with appveyor. Pulling the latest image causes the build to fail because it runs out of space.

> Installing Visual Studio 2013, 2015, or 2017 on microsoft/windowsservercore:10.0.14393.1593 (which may be your locally cached :latest depending on when you last pulled) fails. The bootstrapper fails to launch the installer. Please use either an older tagged build like :10.0.14393.1480 or newer tagged build like :10.0.14393.1715 – the current :latest when this post was first published.

From https://blogs.msdn.microsoft.com/heaths/2017/09/18/installing-build-tools-for-visual-studio-2017-in-a-docker-container/

**Comment by FeodorFitsner** [comment]
Closing the issue in favor: https://github.com/appveyor/ci/issues/1840
