### ISSUE TITLE
SQL Server 2017 Developer edition

### ISSUE THREAD

**Issue by potatoqualitee** [appveyor/ci#1841]
Hello,
SQL Server 2017 has RTM'd and we would love to see this added to the vm. 

Backwards compatibility is also important to our project, and we are happy to see SQL Server 2008 R2 still included.

Cumulative Update 1 for SQL Server 2017: https://support.microsoft.com/en-us/help/4038634/cumulative-update-1-for-sql-server-2017

**Comment by FeodorFitsner** [comment]
Cool news, thanks for letting know!

Is there a Developer edition available for SQL Server 2017?

**Comment by FeodorFitsner** [comment]
Nevermind, found it: https://www.microsoft.com/en-us/sql-server/sql-server-downloads

**Comment by potatoqualitee** [comment]
Yes thank you 🚜

**Comment by tynorton** [comment]
Any idea when the next images update will be available with SQL 2017?

**Comment by IlyaFinkelshteyn** [comment]
Sorry but you have to wait for one more week. We planned to deploy this on this weekend, but found blocking issues, so we sleep till next weekend, sorry.

**Comment by potatoqualitee** [comment]
Thank you for the update @IlyaFinkelshteyn!

**Comment by potatoqualitee** [comment]
Hello, sorry to 🐛 but do you have an ETA for 2017?

thanks much!

**Comment by FeodorFitsner** [comment]
Week or so. We are currently working on the next build worker images update.

**Comment by johlju** [comment]
@FeodorFitsner I'm using the SQL Server media for integration testing installations using PowerShell DSC over at https://github.com/PowerShell/xSQLServer. I'm having trouble finding a good CDN source for downloading the SQL Server 2017 media (trial or Developer edition) and was wondering if it is possible for you to keep the installations media on a separate disk that is also mounted with the build worker. Maybe you have a source from where you install everything, and I thought that maybe that could be disk that is kept mounted. It doesn't hurt to ask. 😄
