### ISSUE TITLE
GitHub PR notifications not working in apache/arrow

### ISSUE THREAD

**Issue by wesm** [appveyor/ci#1842]
See example PR https://github.com/apache/arrow/pull/1155

The builds are running though: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/history. Any ideas how to fix this? Just started happening in the last 48 hours

**Comment by IlyaFinkelshteyn** [comment]
I see one more issue. Build statuses are not being set. I see that when AppVeyor is trying to set statuses, GitHub returns 404, so it is OAuth error probably. To fix statuses, please try to go to https://ci.appveyor.com/account, revoke GitHub access and authorize GitHub again.
Regarding Pull Request notifications I am having hard time to find anything in our traces. I also do not see notification settings in YAML. Do you use UI? And if yes, do you set "Personal access token" or leave it empty? Both options are valid, I just need to know it to troubleshoot.

**Comment by wesm** [comment]
I'm a bit beholden to ASF Infra to help with this, the ticket is https://issues.apache.org/jira/browse/INFRA-15219. I will alert them to your response

**Comment by pono** [comment]
Greetings from ASF Infra! I've reauthed the Appyveyor account, so I believe the permissions issue should be fixed now. @wesm  let me know if you continue to experience problems and we can liaise with Appveyor on this.

**Comment by wesm** [comment]
Looking good @pono thank you!
