### ISSUE TITLE
Boost 1.65.1

### ISSUE THREAD

**Issue by pavelkryukov** [appveyor/ci#1847]
Boost 1.65.1 fixes compatibility issues with Microsoft Visual Studio 2017. Can you please add it to the image?

**Comment by pavelkryukov** [comment]
When can we expect this Boost version?

**Comment by FeodorFitsner** [comment]
In a week or so.

**Comment by FeodorFitsner** [comment]
Installation location: `C:\Libraries\boost_1_65_1`

**Comment by pavelkryukov** [comment]
I don't see it on the image now, will it be available on 19 Nov?
https://ci.appveyor.com/project/pavelkryukov/mipt-mips/build/master-ci-412/job/kxfcgimjg64a4lm8

**Comment by FeodorFitsner** [comment]
Yes, image update will be delivered by the end of this week.

**Comment by pavelkryukov** [comment]
@FeodorFitsner Thank you!
