### ISSUE TITLE
CI env vars change broke codecov's CI detection

### ISSUE THREAD

**Issue by webknjaz** [appveyor/ci#1853]
Current env vars are:
```
CI=True
APPVEYOR=true
```

Which differs from doc: https://www.appveyor.com/docs/environment-variables/
doc says that it must be `APPVEYOR=True` (uppercase T)

Because of this `codecov` python client fails to detect that it's running into CI and thus fails to send coverage data to its servers.

**Comment by FeodorFitsner** [comment]
Do you mean the behavior of this variable was changed by some recent update?

**Comment by webknjaz** [comment]
It's value is used to be `True` (titlecase) and now it's `true` (lowercase). This broke some checks.

**Comment by FeodorFitsner** [comment]
Do you know (last good build link and first failing) when it started happening?

**Comment by webknjaz** [comment]
No, I just noticed this today. I'll tell you if I find something. But it's still in the docs.

**Comment by webknjaz** [comment]
It's been broken since the very first use in your repo 2 months ago: https://ci.appveyor.com/project/jaraco/cherrypy/build/1.0.262/job/g86t0a7qh3ype1g4#L438

**Comment by IlyaFinkelshteyn** [comment]
@webknjaz  I double-checked that it is being set to `True` as expected, in our code and with [this](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/33.464.537) test build. Then I realized that you overwrite this variable [here](https://github.com/cherrypy/cherrypy/blob/master/appveyor.yml#L3) :)

**Comment by webknjaz** [comment]
Wow! I didn't realize that!
I should've done the homework better.
Thank you :)
