### ISSUE TITLE
Builds queued

### ISSUE THREAD

**Issue by xoviat** [appveyor/ci#1854]
I am unable to run any builds since today. I have removed all of my repositories, but builds are still queued.

**Comment by xoviat** [comment]
Sorry for the multiple issues. GitHub seems to be having some problems. I will attempt to close the duplicates.

**Comment by FeodorFitsner** [comment]
Could you please confirm your AppVeyor account?

**Comment by xoviat** [comment]
Example: https://ci.appveyor.com/project/xoviat/scipy-wheels/build/1.0.2

**Comment by FeodorFitsner** [comment]
It should be fixed now - please restart the build.

**Comment by xoviat** [comment]
Thanks.
