### ISSUE TITLE
dotnet restore fails to pull SemVer 2.0.0 package

### ISSUE THREAD

**Issue by JustArchi** [appveyor/ci#1861]
This is something I'm having issues with since yesterday. https://ci.appveyor.com/project/JustArchi/ArchiSteamFarm/build/4689-master#L212

Apparently `dotnet restore` comamnd ran on AppVeyor does not see SemVer 2.0.0 **[SteamKit2 2.0.0-Beta.1](https://www.nuget.org/packages/SteamKit2/2.0.0-Beta.1)** package, it only sees old versions. Initially I thought that it could be some kind of NuGet cache and that the package will pop up later, but I've waited a good 12 hours and no luck, so I've decided to open this issue.

> This package has a SemVer 2.0.0 package version.
> This package will only be available to download with SemVer 2.0.0 compatible NuGet clients, such as Visual Studio 2017 (version 15.3) and above or NuGet client 4.3.0 and above.

It might be connected with lack of NuGet 4.3 in https://github.com/appveyor/ci/issues/1818 but I'm honestly confused as **[Travis](https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/287912797#L559)** with exactly the same `dotnet restore` command in exactly the same .NET Core SDK version (2.0) works properly on Linux. My own dev machine also doesn't have any issues pulling that package on Windows (I'm using .NET Core SDK 2.0 in VS 17 15.5 Preview). Is `dotnet restore` on Windows based on third-party dependencies such as VS and NuGet version? If not, where exactly the issue comes from? Could you take a look?

Thank you in advance for assisting me with this.

**Comment by IlyaFinkelshteyn** [comment]
I tried few obvious workarounds as updating nuget and try using `nuget restore` on my fork as you might seen, which did not help. Then I switched to my computer and created basic .NET Core console app from the template and tried to add this package. I cannot even add this version in VS (15.4.0). I managed to add this by adding `Alpha10` and than upgrading to `2.0.0-Beta.1`.  But after that restore failed: with VS, with `dotnet restore`. `nuget restore` and `msbuild /t:restore`. I have latest .NET Core SDK (2.0) and nuget (4.3) installed. Then I tried to install VS 15.5. Preview on clean VM (with .NET Core and nuget) and get the same result...
Can you please repeat the experiment with basic console app on your computer? Also what does `nuget source` returns on your computer?

**Comment by JustArchi** [comment]
![image](https://user-images.githubusercontent.com/1069029/31712522-a1e74340-b3fb-11e7-9e2f-400dab515517.png)

Works for me.

**Comment by JustArchi** [comment]
According to VS it's NuGet 4.5.0

![image](https://user-images.githubusercontent.com/1069029/31712702-1d6aa2b4-b3fc-11e7-8a75-b7e369766393.png)

Let me know if there is anything else I can help with.

**Comment by JustArchi** [comment]
I've also did `dotnet nuget locals --clear all` to ensure that `dotnet restore` works without cache, and it does too.

![image](https://user-images.githubusercontent.com/1069029/31713034-328b7654-b3fd-11e7-8a51-d73633511d65.png)

As you can see it's using standard nuget source, nothing custom.

**Comment by IlyaFinkelshteyn** [comment]
I think I found hint for the workaround [here](https://github.com/NuGet/Home/issues/1448#issuecomment-159119488) and after [this change](https://github.com/IlyaFinkelshteyn/ArchiSteamFarm/commit/fa72d87695155ba5f0c25d52fc899e14fdb3f44b) restore worked for me.

**Comment by JustArchi** [comment]
I can confirm that your change indeed worked for me, thank you! https://ci.appveyor.com/project/JustArchi/archisteamfarm/build/4703-master-kbqcfhmj 💓

Is there anything in terms of AppVeyor CI that should be corrected regarding this? I'm 100% happy with the solution and the issue can be closed, but other people might stumble upon this too. I'm wondering what might be the root cause of this and if it can be corrected in the CI itself.

In any case, thanks a lot for help! 👍

**Comment by onovotny** [comment]
This is related to #1869

**Comment by JustArchi** [comment]
Since it's already tracked in https://github.com/appveyor/ci/issues/1869 which looks better documented with actual repro, I'm going to close this issue. Thanks for help once again!
