### ISSUE TITLE
help me get cache working?

### ISSUE THREAD

**Issue by andrewrk** [appveyor/ci#1862]
appveyor.yml
```yml
cache:
  - 'llvm+clang-5.0.0-win64-msvc-release.tar.xz'
```

snippet from build
```
C:\projects\zig-d3l86>bash -lc "cd ${APPVEYOR_BUILD_FOLDER} && if [ -s ""llvm+clang-5.0.0-win64-msvc-release.tar.xz"" ]; then echo 'skipping LLVM download'; else wget 'https://s3.amazonaws.com/superjoe/temp/llvm%2bclang-5.0.0-win64-msvc-release.tar.xz'; fi && tar xf llvm+clang-5.0.0-win64-msvc-release.tar.xz"   || exit /b 
```

on second run it still downloaded this file. how can I fix?

**Comment by andrewrk** [comment]
does the build have to succeed for the cache to happen?

**Comment by IlyaFinkelshteyn** [comment]
@andrewrk Right, this is default behavior. But you can tweak it with setting `APPVEYOR_SAVE_CACHE_ON_ERROR` [environment variable](https://www.appveyor.com/docs/environment-variables/) to `true`.

**Comment by andrewrk** [comment]
OK actually this is working perfectly. Thanks!
