### ISSUE TITLE
.NET 4.7.1 support

### ISSUE THREAD

**Issue by johnkors** [appveyor/ci#1868]
Similar to #1488 , but for 4.7.1.

Download: https://www.microsoft.com/en-us/download/details.aspx?id=56119

**Comment by FeodorFitsner** [comment]
I assume it is related to "Visual Studio 2017 Preview" image where we should install [VS 2017 15.5 with .NET 4.7.1 targeting support](https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/)?

**Comment by johnkors** [comment]
Hm, I'm just using the `dotnet sdk` directly, and that worked even in the 2015 image. But yeah - I guess it relates to both the 2015 and 2017 appveyor images..?

**Comment by jp2masa** [comment]
The .NET Framework 4.7.1 targeting pack can be installed separately, but VS 2017 15.5 will include support to target .NET Framework 4.7.1 without any additional installation.

@FeodorFitsner are there any docs about the "Visual Studio 2017 Preview" image?

**Comment by waynebrantley** [comment]
@FeodorFitsner You can just install 4.7.1 sdk on the normal image.  Should have no impact.

**Comment by tompazourek** [comment]
I know it's only been like 2 weeks since it's been released, but is there some expected time frame for when we could start using .NET 4.7.1 with AppVeyor?

**Comment by FeodorFitsner** [comment]
It's scheduled to the "next images update" milestone which is going to be end of this or next week.

**Comment by waynebrantley** [comment]
@FeodorFitsner Is this still expected this week sometime?

**Comment by FeodorFitsner** [comment]
Yearly next week.

**Comment by wongsyrone** [comment]
One naive method is:

```cmd
"C:\Program Files\Git\mingw64\bin\curl" -O https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe

NDP471-DevPack-ENU.exe /q /norestart

exit /B 0
```

and execute this batch file on before_build hook.

**Comment by waynebrantley** [comment]
@FeodorFitsner Any chance of getting this ASAP?

**Comment by FeodorFitsner** [comment]
Images are being tested right now. Will deliver them tomorrow or early Friday.

**Comment by felixfbecker** [comment]
Currently prevents me from using a .NET Standard 2.0 DLL in PowerShell: https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/command-line-simple-example.md#using-a-net-standard-20-based-binary-module-in-windows-powershell

```
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
At C:\projects\ps-nvm\nvm.psm1:5 char:1
+ Import-Module (Join-Path $PSScriptRoot 'SemVer.dll')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by felixfbecker** [comment]
@wongsyrone your workaround didn't work for me unfortunately

**Comment by wongsyrone** [comment]
@felixfbecker

It's expected. The installer requires rebooting your system to take effect. But if you do reboot, boom, everything is gone. That's why I add `/norestart` to the cmdline. And use `exit /B 0` to cheat the CI to ignore any ERRORLEVEL set by the installer. If you do check the error code, it means you have to reboot your system.

In fact, the installer installs two components: runtime and develop modules. I just need develop modules.

**Comment by FeodorFitsner** [comment]
.NET 4.7.1 has been deployed to build workers.
