### ISSUE TITLE
Default NuGet feed list has old protocol endpoint on VS 2017 image

### ISSUE THREAD

**Issue by onovotny** [appveyor/ci#1869]
Somehow the image/user profile in the VS 2017 images has the old NuGet v2 endpoint. This causes builds that need SemVer2 packages to fail.

The default endpoint is set to `https://www.nuget.org/api/v2`. That's incorrect. It should be `https://api.nuget.org/v3/index.json`.

The value in `%appdata%\Nuget\NuGet.config` needs to be updated to have:

` <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />` 

Instead of the value present now. That's what a clean/new install has.

Here's an example failing build: https://ci.appveyor.com/project/onovotny/bc-csharp/build/1.0.62#L157

**Comment by FeodorFitsner** [comment]
Good catch!

Could you please suggest a quick regression test for that? We are currently finalizing VS 2017 - would be cool to push this fix there.

**Comment by onovotny** [comment]
Quick regression would be to use an SDK style project with the following:

`<PackageReference Include="MSBuild.Sdk.Extras" Version="[1.1.0-preview.2.build.8]" PrivateAssets="All" />`

With the `[]` brackets, that should force an exact match and fail if it's not found.

**Comment by FeodorFitsner** [comment]
Thanks, we've got a repro for that!

**Comment by FeodorFitsner** [comment]
@onovotny some people were getting `GatewayTimeout` on v3 feed:

```
GatewayTimeout https://api.nuget.org/v3-flatcontainer/microsoft.owin.host.systemweb/3.1.0/microsoft.owin.host.systemweb.3.1.0.nupkg 6ms
WARNING: Error downloading 'Microsoft.Owin.Host.SystemWeb.3.1.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.owin.host.systemweb/3.1.0/microsoft.owin.host.systemweb.3.1.0.nupkg'.
Response status code does not indicate success: 504 (Gateway Timeout).
```

Do you think there were intermittent issues on NuGet side or because of some packages are missing from v3 feed?

**Comment by skofman1** [comment]
CDN had an incident, that was mitigated, More information here: https://status.verizondigitalmedia.com/pages/incident/5736344c90417cda1a000f3f/59edf9e681f36d04de8bd347

**Comment by onovotny** [comment]
@skofman1 Can the CDN status be more directly integrated into the green/red overall status of status.nuget.org?

**Comment by skofman1** [comment]
@onovotny , our status page (status.nugget.org) has a link to CDN status page:
![image](https://user-images.githubusercontent.com/16807822/31901909-d312d9e0-b7d7-11e7-9977-4ebfddde366f.png)

Not all CDN issues affect api.nuget.org connectivity, so if we show "red" every time CDN has an issue it will be noisy and confusing.

**Comment by FeodorFitsner** [comment]
Thank you guys for the update!
