### ISSUE TITLE
The current py.exe on AppVeyor is inherently broken

### ISSUE THREAD

**Issue by dhermes** [appveyor/ci#1870]
I made a simple [project][1] to showcase this. You can see the [build][2] failing.

The problem (summarized in the project `README`) is that the `py.exe` on the image is from `3.4.4` and it was inherently broken. It makes a list of Python versions but stops when it encounters a registry key with more than 4 chars (which happens when it hits `3.5-32`).

A simple fix: use `py.exe` from `3.6.1` (or even better, `3.6.3` once #1770 is resolved).

[1]: https://github.com/dhermes/appveyor-py-launcher
[2]: https://ci.appveyor.com/project/dhermes/appveyor-py-launcher

**Comment by FeodorFitsner** [comment]
Thank you for bringing this to our attention!

We are going to fix that by installing `py.exe` from Python 3.6.3 x64 in the coming update.

**Comment by dhermes** [comment]
Thanks for the super fast turnaround @FeodorFitsner!

Confirmed it is working as intended: https://ci.appveyor.com/project/jonparrott/nox/build/1.0.303.master
