### ISSUE TITLE
Compile boost libraries for mingw usage.

### ISSUE THREAD

**Issue by GilesBathgate** [appveyor/ci#1871]
My project requires boost dlls to be compiled for mingw. Currently I have to do this manually before the build using:

```
call bootstrap.bat mingw
.\b2 toolset=gcc variant=release
```
It would be nice if boost was already compiled for mingw development on the images.

**Comment by Biswa96** [comment]
You could use the pre-compiled boot library package from MSYS2/MinGW-w64 environment. Use `pacman -S --needed mingw-w64-x86_64-boost` to download it.

**Comment by GilesBathgate** [comment]
Thanks I will give that a try.
