### ISSUE TITLE
Executing 'dotnet new' commands from PowerShell throw an exception only when being run in AppVeyor

### ISSUE THREAD

**Issue by bergmeister** [appveyor/ci#1873]
When calling `dotnet new mstest` or `dotnet new xunit` from `PowerShell` in `AppVeyor` using the `Visual Studio 2017` image, it throws an error (but seems to succeed)
I have created a repository to showcase this [here](https://github.com/bergmeister/appveyor_dotnetCLi_bug) and the build result is [here](https://ci.appveyor.com/project/bergmeister/appveyor-dotnetcli-bug/build/1.0.4)

The error is:
```powershell
dotnet : 
At line:1 char:1
+ dotnet new mstest
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Restore succeeded.
Command executed with exception: 
```

If I remember correctly this was working fine at the start of this week but suddenly started to fail (with no code change) in the last 2 days.

**Comment by IlyaFinkelshteyn** [comment]
Looks like `dotnet new <something>` writes output to `stdErr`, and custom PowerShell host AppVeyor build runs in treats everything going to StdErr as exception. This is know issue and the only recommendation is to run this in `CMD` mode.

**Comment by bergmeister** [comment]
@IlyaFinkelshteyn Thanks for your response. I think you are right, I opened a bug in the dotnet cli repository instead and will therefore close this one.
