### ISSUE TITLE
Build stuck

### ISSUE THREAD

**Issue by xoviat** [appveyor/ci#1874]
AppVeyor appears to be stuck on cancelling a build:

https://ci.appveyor.com/project/scipy/scipy/history

This seems to be a known problem:

http://help.appveyor.com/discussions/problems/5896-build-stuck-on-cancelling-disallowing-further-builds

Does anyone know of a way to fix it or are we going to have to contact them?

Ref scipy/scipy#8062

**Comment by FeodorFitsner** [comment]
It should be fixed now. Please restart a build or kick of a new one.

**Comment by xoviat** [comment]
Confirmed, thanks.
