### ISSUE TITLE
Git clone over HTTPS times out

### ISSUE THREAD

**Issue by DaveMiscampbell** [appveyor/ci#1875]
This morning all of our builds which attempt to clone from Github over HTTPS just hang at the git clone stage and then time out after an hour. We've not changed any settings so just wondering if there's something not right?

Thanks!

**Comment by Philo** [comment]
I have also been seeing the same issue on our repos.

**Comment by FeodorFitsner** [comment]
The issue has been fixed. Sorry for the inconveniences.

Will make sure the case is added to our regression tests.

**Comment by FeodorFitsner** [comment]
Fix script:

```
git config --system --unset credential.helper
```
