### ISSUE TITLE
Qt 5.9.2

### ISSUE THREAD

**Issue by mmatyas** [appveyor/ci#1883]
Qt 5.9.2 got released [earlier this month](https://blog.qt.io/blog/2017/10/06/qt-5-9-2-released/). Could you install it please?

**Comment by FeodorFitsner** [comment]
Add mappings:

```
rd C:\Qt\5.9
mklink /J C:\Qt\5.9 C:\qt\5.9.2
mklink /J C:\Qt\5.9.1 C:\qt\5.9.2
```

**Comment by ismail** [comment]
There is a typo at the website (https://www.appveyor.com/docs/build-environment/)

>Qt 5.9.2: C:\Qt\5.9.1 (C:\Qt\5.9 mapped to C:\Qt\5.9.1 for backward compatibility)

Path to 5.9.2 should be updated.

**Comment by FeodorFitsner** [comment]
Thanks for the catch! It's been fixed.
