### ISSUE TITLE
Windows Server 1709 with Docker

### ISSUE THREAD

**Issue by StefanScherer** [appveyor/ci#1885]
Building Windows Docker images based on the new and smaller base images microsoft/windowsservercore:1709 and microsoft/nanoserver:1709 require a Docker host running on Windows Server version 1709 (host kernel version must match container image version).

But the other way building Windows Docker images for the LTS channel (Windows Server 2016 10.0.14393) you need the LTS version of Windows Server 2016 or if running on WIndows Server 1709 you need HyperV to run the "old" Windows Docker images as HyperV containers.

So what is the plan at AppVeyor with the Windows Semi Annual Channel (https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview) ?

**Comment by FeodorFitsner** [comment]
Sorry for the delay with reply. I've just realized it's a completely new "Windows Server" release! :)

So, it comes in "Core" state only, right? What would you need on such image besides Git and AppVeyor build agent?

**Comment by StefanScherer** [comment]
Exactly, it is server core only. It is more like a different edge channel beside the current LTS channel. 

Well, Docker EE (17.10.0 EE is in preview 3, but don‘t know exact release date) and these base images

microsoft/windowsservercore:1709
microsoft/nanoserver:1709

which fit the host OS version 10.0.16299.x.

Building Docker images for both channels requires both build agents. How could I setup a build pipeline to run something like a matrix build, but with two image builder versions?

**Comment by NPadrutt** [comment]
Are there currently any plans to upgrade generally to 1709? We have a UWP app and want target FCU as minimal and target version to enable some of the new capabilities, which needs a 1709 Windows to build it.

**Comment by FeodorFitsner** [comment]
@NPadrutt Server 1709 doesn't have UI. Thus I'm wondering if it's still possible to build/test VS-based solutions on it?

**Comment by NPadrutt** [comment]
@FeodorFitsner oh, that is a very good question. To be honest I assumed that they would offer a server version as well of the 1709 release.

**Comment by godrose** [comment]
@FeodorFitsner Any update on this issue? Maybe after the holidays?

**Comment by FeodorFitsner** [comment]
OK, my questions was "what would you expect to see installed on that image besides git, mercurial and docker"? Windows Server 1709 is headless OS, so VS won't get there - that's my understanding.

**Comment by tianon** [comment]
Git and Docker would be plenty for the Docker official-images use case, at least!  If it has Powershell as well, it should be fairly easy for folks to install their own tools too (if they don't want to use Docker to do the same task for some reason).

**Comment by godrose** [comment]
https://docs.microsoft.com/en-us/windows-server/get-started/get-started-with-1709

**Comment by godrose** [comment]
@FeodorFitsner Any ETA for the associated milestone?

**Comment by IlyaFinkelshteyn** [comment]
@godrose this is definitely one of top priority projects. We just cannot say specific ETA right now, sorry.

**Comment by godrose** [comment]
@IlyaFinkelshteyn Thanks for the response!

**Comment by godrose** [comment]
@IlyaFinkelshteyn Just a ping. Any update on this? Thanks.

**Comment by IlyaFinkelshteyn** [comment]
@godrose today you probably got email from us about AppVeyor for Linux This was huge work and we could not concentrate on another infrastructure projects. Now we hope we can pay attention to this. 

But, I wonder if Linux builds (on Ubuntu VMs) could eliminate your need for Windows Server 1709?

**Comment by tianon** [comment]
For build-testing Docker images based on `microsoft/windowsservercore:1709`, they have to run on a Windows Server 1709 host, so Linux doesn't really help there. :sweat_smile: :heart:

**Comment by IlyaFinkelshteyn** [comment]
I see. As you can see we changed milestone to **Q2-2018**. This should give some idea when we hope to make it work. Still cannot do exact promises.

**Comment by StefanScherer** [comment]
Thanks for the update and congrats to your Linux build agents. Have to look into it for some multi-arch Docker images Linux + Windows ;-)

For 1709 images we need a real Windows Server 1709. Notice, as 1709 is a semi-annual release which is now six months live, be prepared for the next semi-annual release 1803 very soon... 👼

**Comment by FeodorFitsner** [comment]
Yeah, thanks for kind words and heads up! :)

**Comment by FeodorFitsner** [comment]
@godrose What is your business case for 1709? Could you please elaborate?

**Comment by mback2k** [comment]
@FeodorFitsner My business case is building up-to-date Docker images for Windows Server 1709 or Windows Server 1803.

**Comment by FeodorFitsner** [comment]
We are looking into Windows 10 support. Investing into that direction could be better rather than dealing with semi-annual headless Windows releases.

**Comment by StefanScherer** [comment]
Windows 10 sounds interesting and is able to use latest 1803 images, but Hyper-V is required for Docker to run Containers on Windows 10.

**Comment by FeodorFitsner** [comment]
Right. What if you have Windows Server 2016 10.0.14393 with Hyper-V enabled - can you work with 1709/1803 containers then provided they are run in Hyper-V isolation mode?

**Comment by StefanScherer** [comment]
No, even Hyper-V is not enough to run newer 1709/1803 containers on a 14393 Windows Server 2016.
So the easier way would be a Windows 10 April 2018 update with 1803. Here you can run all 2016/1709 and 1803 container through Hyper-V.

**Comment by StefanScherer** [comment]
MS is working on this issue, maybe some release in the future is able to run newer containers with Hyper-V than the host OS. But not the current releases.

**Comment by FeodorFitsner** [comment]
Nice, so Windows 10 with nested virtualization and Hyper-V would be a good fit.

**Comment by alangford** [comment]
Any update on this issue? I'm also running into an issue when trying to build a .net core 2.2 docker image using the latest microsoft/dotnet image.

This is the error I'm receiving ` a Windows version 10.0.17134-based image is incompatible with a 10.0.14393 host`

**Comment by IlyaFinkelshteyn** [comment]
@alangford  please check https://github.com/appveyor/ci/issues/2676#issuecomment-485564003 regarding `Windows Server 2019` image. Just enabled it for your account, please try.

**Comment by StefanScherer** [comment]
Oh, I‘ll close this one as 1709 got its last update in April and is now deprecated. 
Yes, Windows Server 2019 is the thing now!

**Comment by IlyaFinkelshteyn** [comment]
Yes, this image does not have 1709 docker image on it, but all others are in place: https://ci.appveyor.com/project/appveyor-tests/win2k19-azure/builds/24024378#L94

**Comment by mback2k** [comment]
@IlyaFinkelshteyn Sounds great. Could you also enable my AppVeyor account please? Same as on Github, @mback2k.

**Comment by IlyaFinkelshteyn** [comment]
@mback2k sure, enabled/
