### ISSUE TITLE
AppVeyor doesn't trigger tag build when last commit is not tagged commit

### ISSUE THREAD

**Issue by JustArchi** [appveyor/ci#1887]
This is the issue I stumbled upon several times by now, and it's very easy to reproduce.

~Basically I can't trigger tag build (which deploys release in my case) if the "tagged" commit is PR merge commit. Despite of GitHub delivering webhook message, CI build simply does not trigger.~

I'm not sure whether this is connected with some specific CI settings or a general issue, but I believe that this is a bug.

For reference, `appveyor.yml` on which I managed to reproduce the bug looks like **[this](https://github.com/JustArchi/ArchiSteamFarm/blob/9006b368/appveyor.yml)**.

~In order to reproduce the bug it's enough to open GitHub pull request, merge it using classical PR merge commit (like **[this](https://github.com/JustArchi/ArchiSteamFarm/commit/7df7906f38d7cf610c99f36ddbcc5d93614b84d7)**), then `git tag 1.2.3.4` and `git push origin 1.2.3.4`. In my case, merge commit builds properly due to building on push, but there is no second build of the same commit triggered by new tag being published.~

~Of course, as long as I add any other commit on top of it, such as **[this one](https://github.com/JustArchi/ArchiSteamFarm/commit/4a3ea78ee60b378c031493ab6f6c6a6703410661)**, and tag again, then AppVeyor correctly builds one build made from commit being pushed, and another build from tag being published (which in my case also commits deploy).~

The issue is based on tagging a commit prior to the one that is a HEAD of the given branch, as further explained in https://github.com/appveyor/ci/issues/1887#issuecomment-339994446.

Thank you in advance for looking into this.

**Comment by IlyaFinkelshteyn** [comment]
This is probably because you have `branches: / only: / - master` in your YAML, but in webhook tag name is set as a branch. If you send us specific time (in UTC or with time zone) and GitHub delivery id, we can double-check it in our traces.

**Comment by JustArchi** [comment]
I also believe that it's because of my specific AppVeyor settings, otherwise you'd catch this issue much earlier.

I compared "broken" tag event with working one on the GitHub itself:

![diff](https://user-images.githubusercontent.com/1069029/32107638-882acd2e-bb2f-11e7-8f03-28cf5c76b91c.png)

I believe the issue comes from `base_ref` being `null`. Now the question is - why is it null, and why it points to the commit **before** pull request merge, I'm 100% sure I tagged the PR commit itself and not the commit before that... I might want to reproduce this on some clean fork of my repo because I'm no longer sure whether it was my screwup of tagging a commit before, or some black magic going on.

I'll update the issue accordingly once I'm done, I just hope I didn't bother you with nothing if the issue is on my side, thanks for response!

**Comment by JustArchi** [comment]
After tests it seems that indeed it was my screwup back then, but it uncovered an interesting scenario that perhaps is worth to be fixed anyway.

The bug I've stumbled upon was no build being triggered when tagged commit is not the latest one in the branch, and we're only building that specific branch. In this case, that tag will have `base_ref` of `null` like shown above, and the build will not trigger, despite of tag being in fact applied to a given fixed point of time on master branch.

Is there any interest in fixing this particular scenario? In theory I'd expect AppVeyor to build it, since after all it is a tag applied to master branch, but I have no clue if that's possible to fix easily, since `base_ref` no longer points to `master`. If you consider this issue as worth correcting, feel free to left it open, otherwise feel free to close it, since that one is not necessarily my concern anymore 🙂.

Tests:

https://github.com/JustArchi/ArchiSteamFarm-Test/releases/tag/0.0.0.3
https://ci.appveyor.com/project/JustArchi/archisteamfarm-test/history
