### ISSUE TITLE
Certificate error on https://nuget.smbsrc.net

### ISSUE THREAD

**Issue by adriangodong** [appveyor/ci#1888]
This is not an issue with AppVeyor but filed here for visibility.

SymbolSource Nuget server is currently using an expired certificate and when publishing source packages, you may get the following error:
```
Deploying using NuGet provider
Publishing xxx.0.0.1.nupkg to https://www.nuget.org/api/v2/package...OK
Publishing xxx.0.0.1.symbols.nupkg to https://nuget.smbsrc.net/api/v2/package...
An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
```

I don't see any open issue tracker, but [this issue on NuGet/Home](https://github.com/NuGet/Home/issues/6082) seems like a good place to monitor.

**Comment by adriangodong** [comment]
Certificate has been fixed.

**Comment by mvadu** [comment]
I got this error today again.. (ref: [influxdb-client-net/builds](https://ci.appveyor.com/project/AdysTech/influxdb-client-net/builds/28059794)). 

```
Publishing AdysTech.InfluxDB.Client.Net.0.9.0.symbols.nupkg to https://nuget.smbsrc.net/api/v2/package...An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

**Comment by FeodorFitsner** [comment]
It's https://github.com/NuGet/Home/issues/6082 again. Try switching to `.snupkg`.
