### ISSUE TITLE
TLS 1.2 not supported by default

### ISSUE THREAD

**Issue by pganssle** [appveyor/ci#1889]
I noticed in [this build](https://ci.appveyor.com/project/dateutil/dateutil/build/2.3.707/job/qasc59g58lyaxars) that the PyPA site for downloading ensure-pip (`https://bootstrap.pypa.io/get-pip.py`) is not reachable from AppVeyor because of a TLS error:

```powershell
Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:242 char:2
+     Start-FileDownloadInternal -Url $Url -FileName $FileName -Timeout ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-FileDownloadInternal], Exception
    + FullyQualifiedErrorId : System.Exception,Appveyor.BuildAgent.Api.Utils.StartFileDownloadInternalCmdlet
```

The reason for this is that `bootstrap.pypa.io` now *only* supports the TLS 1.2 protocol (the latest protocol), and apparently that is not enabled by default on AppVeyor. The two options I see for users are [enable TLS 1.2 as was done in this repo](https://github.com/log2timeline/plaso/commit/296495fb420bc34201d34af235ff3e3c22dd1565), or, because AppVeyor's Python versions already have pip installed, [remove the download](https://github.com/dateutil/dateutil/pull/484). That said, this seems like it will cause problems for a lot of builds if the default for Start-FileDownloadInternal is not changed to support TLS 1.2.

The [FAQ on this](https://www.appveyor.com/docs/how-to/download-file/#start-filedownload-cmdlet) mentions the problem in general terms, but is misleading:

> this most probably means that build worker and server could not agree on SSL protocol, because server does not support modern protocol with highest security.

The problem here is not that the server does not support modern protocols with the highest security, but that AppVeyor doesn't (which is confusing when you look at the cert and find that it's using TLS 1.2).

**Comment by IlyaFinkelshteyn** [comment]
Fixed, default ServicePointManager setting changed to enable this scenario.

**Comment by pganssle** [comment]
Thanks @IlyaFinkelshteyn!

Also, thanks for this service. You guys are probably the main reason that a huge percentage of open source libraries and applications continue to work on Windows.
