### ISSUE TITLE
NUnit tests are running but not showing in the Tests tab

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#1890]
I've just setup my first .net core project and out of the box appveyor is running the tests and I'm seeing the results in the console, but I'm not seeing the results in the Tests tab. I tried running the command manually via `dotnet test` and that had the same results. I know this works because [stripe-dotnet](https://ci.appveyor.com/project/stripe-appveyor-ci/stripe-dotnet/build/tests) has results in their builds. The only difference between the two setups that I'm seeing is they're using xUnit while I'm using NUnit. Is there only support for xUnit with this or is there additional setup that's needed? I didn't see anything in the docs relating to testing .net core.

**Comment by IlyaFinkelshteyn** [comment]
Right, xUnit has built-in AppVeyor logger. Please add Appveyor.TestLogger package to your test project to make it work. Sorry, will update documentation.

**Comment by xt0rted** [comment]
I added that package and updated my script to use the following and it works now:

```cmd
dotnet test test/MyProject/MyProject.csproj --test-adapter-path:. --logger:Appveyor
```

I got the instructions from [Faizan2304/LoggerExtensions#appveyor-logger](https://github.com/Faizan2304/LoggerExtensions#appveyor-logger)

**Comment by IlyaFinkelshteyn** [comment]
You do not have to do that. AppVeyor will detect that package and run appropriate command if you remove `test_script` altogether.

**Comment by xt0rted** [comment]
Even better, removed my `test_script` section and everything works as expected. Thanks for the help.
