### ISSUE TITLE
Node.js 9.0.0

### ISSUE THREAD

**Issue by nschonni** [appveyor/ci#1895]
Now the "current" branch for Node.js https://nodejs.org/en/blog/release/v9.0.0/

**Comment by FeodorFitsner** [comment]
Thanks for letting know! Will deploy it tomorrow.

**Comment by stefanpenner** [comment]
@FeodorFitsner hey, friendly ping. Any luck getting node 9x deployed?

**Comment by FeodorFitsner** [comment]
It's been just deployed!

**Comment by nschonni** [comment]
Thanks!

**Comment by FeodorFitsner** [comment]
Let’s keep the issue open to make sure Node is updated on build workers during the next update.

**Comment by stefanpenner** [comment]
@FeodorFitsner if its helpful, https://github.com/sass/node-sass/pull/2130 appears to have picked up node 9 correctly.

**Comment by FeodorFitsner** [comment]
Closed in favor of https://github.com/appveyor/ci/issues/1880
