### ISSUE TITLE
PHP 7.1 installation failed

### ISSUE THREAD

**Issue by Soullivaneuh** [appveyor/ci#1896]
Chocolatey currently fails to install PHP 7.1.

Related PR: https://github.com/Soullivaneuh/IsoCodesValidator/pull/119/files

Errored log example: https://ci.appveyor.com/project/Soullivaneuh/isocodesvalidator/build/256/job/y2v95omte2wcsuhx#L138

It works for PHP 5.6 and 7.0 with the same configuration.

**Comment by gep13** [comment]
@Soullivaneuh there is a known issue when trying to apply Windows Updates on the AppVeyor images.  There is a high chance that the required dependencies are already in place, so you should try installing php using `choco install php --ignoredependencies`.

However, this will cause another problem in that you will still require the chocolatey-core.extension package.  So I would suggest that you do the following:

`choco install chocolatey-core.extension -y`
`choco install php --ignoredependencies -y`

Hope that helps!

**Comment by Soullivaneuh** [comment]
Thanks for the tip @gep13, I had indeed to activate windows update service, see the PR diff for more details.

It works as is even if it's quite difficult to figure out why, but I'll stop at this state. :wink:

**Comment by gep13** [comment]
@Soullivaneuh glad you got it sorted out! 👍
