### ISSUE TITLE
Miniconda3 default installation is ancient, updating not always possible

### ISSUE THREAD

**Issue by msarahan** [appveyor/ci#1897]
There was a recent change to Anaconda's package index that ended up being incompatible with very old versions of conda: https://github.com/conda/conda/issues/6251

Your C:\Miniconda3 and C:\Miniconda3-64 have conda 3.16.0 in them, which is very old.  At some point, it may not be possible for users to update from 3.16.0 to whatever the current version is.  Anaconda can't commit to upgrades always working from arbitrarily old installations.

My proposal would be to change C:\Miniconda3 and C:\Miniconda3-64 to be whatever the current miniconda3 release is, and have C:\Miniconda34 and C:\Miniconda34-64 keep this old version accessible.  This is similar to the behavior of users who download the "Miniconda3-latest" installers.

I understand this is a pretty large change in what some users are expecting.  I don't know exactly what the right answer is, so please consider my proposal, but take it with a grain of salt.

**Comment by ngoldbaum** [comment]
Alternately, perhaps provide a miniconda3-latest image that gets continuously updated?

**Comment by FeodorFitsner** [comment]
There are `C:\Miniconda36` and `C:\Miniconda36-x64` with "Miniconda3 4.3.27 Python 3.6.2" in them.

**Comment by msarahan** [comment]
Yes, and I have advised people to change to that.  Unfortunately, people see C:\Miniconda3 and think it is whatever is current.  C:\Miniconda3 is a bad name because it is underspecified, and people must be careful what they are using.

**Comment by AndrewAnnex** [comment]
I need the conda version for python 3.4 updated for my project as I need to build against the correct visual studio version for a given python distribution (unless someone can show me how to make a generic build). And using conda to install a different python version is likely not an option for me as conda cannot upload artifacts from non root environments, unless that has now been fixed.

👍  for changes purposed here.

**Comment by FeodorFitsner** [comment]
What if we install `Python 3.4.3 (Miniconda3 3.16.0)` to `C:\Miniconda34` and `C:\Miniconda34-x64` and then make `C:\Miniconda3` as symbolic link to `C:\Miniconda36` and `C:\Miniconda3-x64` to `C:\Miniconda36-x64` correspondingly?

Would that work? Does Miniconda play well with symbolic links? Could you guys give it a try please?

We use the same approach with Golang and it worked.

**Comment by msarahan** [comment]
That is exactly the right idea in my opinion. I think it should work, but I
have next to no experience with symlinks on Windows. It's worth a try. If
there's a way I can help with testing, let me know.

**Comment by FeodorFitsner** [comment]
Try adding the following to your build and then run your build/tests against `C:\Miniconda`:

```
ren C:\Miniconda3 Miniconda34
ren C:\Miniconda3-x64 Miniconda34-x64
mklink /J C:\Miniconda3 C:\Miniconda36
mklink /J C:\Miniconda3-x64 C:\Miniconda36x64
```

**Comment by msarahan** [comment]
Sorry, I can't seem to add new projects via github right now.  After the authorization page, appveyor just always loops back to the choice between "public repositories only" and "private and public repositories".  I wanted to fork yt and test with it, but someone else may need to do so.

I am 100% behind your proposed change @FeodorFitsner, and about 95% sure that what you propose with symlinks will work.

**Comment by FeodorFitsner** [comment]
OK, could you do a simple test project in a public repository that we can run to make sure Conda works with junctions?

**Comment by msarahan** [comment]
Thanks for working on this.
