### ISSUE TITLE
How do fetch  the artifacts generated by the previous job in the following job?

### ISSUE THREAD

**Issue by KangLin** [appveyor/ci#1898]
How do fetch  the artifacts generated by the previous job in the following job?

This document provides an invalid method: https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact

When the build is end. Can fetch the artifacts. 
Why don't fetch the artifacts at build time?

My project: https://ci.appveyor.com/project/KangLin/rabbitthirdlibrary/build/0.1.1.388

**Comment by IlyaFinkelshteyn** [comment]
Check [this sample](https://gist.github.com/IlyaFinkelshteyn/79af78657660e118b15d3ab9d62ab8a1)

**Comment by KangLin** [comment]
How to get the ApiKey?

**Comment by IlyaFinkelshteyn** [comment]
https://ci.appveyor.com/api-token

If this link does not work for you, this means that you do not have enough permission and you need to ask your AppVeyor account owner or administrator to add you to the role which has `Generate API keys` permission.
