### ISSUE TITLE
Qt 5.x Unknown module webenginewidgets

### ISSUE THREAD

**Issue by Aztorius** [appveyor/ci#1899]
I tried with Qt 5.8 and 5.9.1 but every time there is : 
`Project ERROR: Unknown module(s) in QT: webenginewidgets`
after a qmake.

I know that normally there is Qt WebEngine as a default module, but it doesn't seem to work.
The project works well under Linux and MacOSX.

**Comment by FeodorFitsner** [comment]
We'll take a look if that module is already installed on build worker images.

**Comment by FeodorFitsner** [comment]
I've checked and both 5.8 and 5.9 have this module installed? You may [RDP into VM](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) and check if anything is missing there.

**Comment by Aztorius** [comment]
WebEngine is not available with MinGW under Windows. Working with Visual Studio.
