### ISSUE TITLE
how to update yarn to latest?

### ISSUE THREAD

**Issue by ctaggart** [appveyor/ci#1900]
There is a way to install a particular Node. Is there a way to install a particular Yarn?
``` yml
install:
  - ps: Install-Product node 8 x64
```

Something like this may be nice:
``` yml
install:
  - ps: Install-Product yarn 1.3.2
```

https://github.com/yarnpkg/yarn/releases

The current issue is yarn 1.2.1 is not complains about node 9. I just locked the node version to 8, but it would be nice to have some way to update yarn.

**Comment by FeodorFitsner** [comment]
You can use this script installing Yarn 1.3.2 during the build - takes seconds:

```posh
Write-Host "Installing Yarn 1.3.2..."
(New-Object Net.WebClient).DownloadFile('https://github.com/yarnpkg/yarn/releases/download/v1.3.2/yarn-1.3.2.msi', "$env:temp\yarn-1.3.2.msi")
cmd /c start /wait msiexec.exe /i $env:temp\yarn-1.3.2.msi /quiet
yarn --version
```

In the meantime, I've added a new issue here to upgrade Yarn during the next image update: https://github.com/appveyor/ci/issues/1901

**Comment by ctaggart** [comment]
Thank you @FeodorFitsner!

**Comment by JimiC** [comment]
In case someone is looking for this:
```ps
Write-Host "Installing Yarn!"
$webClient = New-Object Net.WebClient
$latestVersion = $webClient.DownloadString('https://yarnpkg.com/latest-version')
$webClient.DownloadFile("https://github.com/yarnpkg/yarn/releases/download/v$latestVersion/yarn-$latestVersion.msi", "$env:temp\yarn.msi")
cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet
yarn --version
```

**Comment by claygriffiths** [comment]
I ran into this issue recently and struggled to get the MSI to cooperate.

In the end, I went with `choco install yarn` which simplifies things quite a bit. You can even specify a version like so: `choco install yarn --version 1.13`

**Comment by JimiC** [comment]
Or you can use the script I made https://github.com/JimiC/ps-yarn-install without the need of `choco`.

**Comment by IlyaFinkelshteyn** [comment]
Please watch https://github.com/appveyor/ci/issues/2929 if you prefer to remove a workaround later
