### ISSUE TITLE
Add environmental variable for pull request creator's username

### ISSUE THREAD

**Issue by hcorion** [appveyor/ci#1908]
The closest thing we have is `APPVEYOR_REPO_COMMIT_AUTHOR` but the problem is that if the owner of the repository (the one that is receiving the PR) does a `update branch` through the GitHub UI, `APPVEYOR_REPO_COMMIT_AUTHOR` will not show the desired value.

I propose then a new environmental variable, `APPVEYOR_PULL_REQUEST_USERNAME`

**Comment by IlyaFinkelshteyn** [comment]
We read commit author name from the `head` commit in PR. Can you please describe step-by-step how to reproduce the issue with `update` branch through the GitHub UI?

**Comment by IlyaFinkelshteyn** [comment]
`APPVEYOR_REPO_COMMIT_AUTHOR` is being taken from the `head` commit in PR.
