### ISSUE TITLE
Is it possible to get the actual start time for a build

### ISSUE THREAD

**Issue by gep13** [appveyor/ci#191]
I could put this information as the first part of my build script, but it strikes me that this:

![image](https://cloud.githubusercontent.com/assets/1271146/6682820/baef25bc-cc75-11e4-801a-6aeb40b2fe32.png)

Should either be replaced, or combined with the actual start time.

Just a thought :smile_cat: saves me having to do sums in the morning!

**Comment by FeodorFitsner** [comment]
How about showing build start/end time in popup hint?

![image](https://cloud.githubusercontent.com/assets/5041459/6683041/b2eb954a-cc3d-11e4-8853-b400b88e3e8a.png)

**Comment by gep13** [comment]
Oooo, that would be nice.  Didn't think to hover over the time.  I can see the current tooltip shows the start time, including the end time would be a great idea.
