### ISSUE TITLE
Cygwin/GDB x64 crash on execute.

### ISSUE THREAD

**Issue by schnommus** [appveyor/ci#1912]
Something has recently changed, caused the following code to fail: (batch file, executed from .yml)
```
@ECHO ON
C:\cygwin64\setup-x86_64.exe -q -P gdb
set PATH=C:\cygwin64\bin;%PATH%
gdb --version
@IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%
```
The GDB call will crash - it seems to be due to a python dll being incompatible with the GDB binary  (GDB complains about a missing entry point in the libpython2.7 dll).

The only change from a broken to working build on our system was cygwin installing a 2.7.14-1 version of python instead of 2.7.13-1, caused by upstream changes.

The latest cygwin installer and packages seem to work fine in a windows VM, so I suspect that there is an issue with the cygwin install on Appveyor at the moment.

Since we haven't been able to figure out how to rectify the issue by using cygwin commands, could the packages and installer be updated/fixed? Alternatively a workaround would also be helpful.

Cheers!

**Comment by FeodorFitsner** [comment]
So, updating `C:\cygwin64` will help?

**Comment by schnommus** [comment]
Yes - I think updating cygwin64 will probably fix it.

**Comment by FeodorFitsner** [comment]
OK, will do that during the next update.

**Comment by schnommus** [comment]
Great, thanks!
