### ISSUE TITLE
'platform: Any CPU' breaks 'dotnet test' execution

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1915]
https://github.com/appveyor/ci/issues/1404#issuecomment-342172318

**Comment by grokys** [comment]
Should this have been fixed? I'm still experiencing this now: https://ci.appveyor.com/project/AvaloniaUI/Avalonia/build/0.1.4467

**Comment by IlyaFinkelshteyn** [comment]
Fixed
