### ISSUE TITLE
AppVeyor check for GitHub PRs disappeared

### ISSUE THREAD

**Issue by kjin** [appveyor/ci#1917]
Starting on Monday, the AppVeyor check for GitHub PRs disappeared on one of our repositories ([example](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/584)). The CI still runs -- it just doesn't report back.

Not sure if it's related but I first observed this after the NuGet issues that occurred mid-day Monday (two days ago). We have [another repo](https://github.com/GoogleCloudPlatform/cloud-debug-nodejs) whose AppVeyor PR checks are working correctly, but that one doesn't download anything from NuGet, while the repo whose checks disappeared does.

Any suggestions on what might have gone wrong, and how I can fix it?

**Comment by IlyaFinkelshteyn** [comment]
@kjin please check GitHub authorization at https://ci.appveyor.com/account. Revoke GitHub authorization and authorize GitHub again, even if correct account is being used (to refresh OAuth token).

**Comment by marscher** [comment]
thank you @IlyaFinkelshteyn this helped a lot.
