### ISSUE TITLE
Creating environment via API specifying projects

### ISSUE THREAD

**Issue by gunndabad** [appveyor/ci#1920]
I'm creating environments via the API but I can't find a way of specifying the list of projects that can be deployed to the environment.

I'm specifying `"projectsMode": 1` inside the 'settings' element in POST to https://ci.appveyor.com/api/environments which seems to correspond to 'Only selected projects' on the UI. I've tried adding selectedProjects attribute, like the GET operation returns, but that doesn't seem to work.

Is there a way of setting the projects via the API?

**Comment by IlyaFinkelshteyn** [comment]
Sorry, this is little bit more complicated. You need to create environment and then update it with those settings in request body. I created this [PowerShell sample](https://gist.github.com/IlyaFinkelshteyn/ec675f05bf25405a0086e1b476dab38f) to eliminate the confusion.

**Comment by gunndabad** [comment]
Fantastic. Many thanks.
