### ISSUE TITLE
Repository naming clarification

### ISSUE THREAD

**Issue by SPodjasek** [appveyor/ci#1924]
IMHO you should change names in "Select repository" page. "Stash" should be "Bitbucket Server/Data Center" and "Bitbucket" should be "Bitbucket Cloud" to reflect how Altassian currently names them.

I've just wasted some time to discover that to use `appveyor.yml` one should use non-custom Git repository  (#990, #545). RTFM you can say ;), but maybe "Bitbucket Server" would struck my eyes and I will use it instead of Git, and save some time...

**Comment by FeodorFitsner** [comment]
Good suggestion, thank you. Will do that change in the nearest update.

**Comment by FeodorFitsner** [comment]
It's been renamed.
