### ISSUE TITLE
The built-in vcpkg needs to be updated.

### ISSUE THREAD

**Issue by drako0812** [appveyor/ci#1925]
When recently starting to use AppVeyor for my project https://github.com/drako0812/DRAK-0 I ran into an issue. I had to manually update vcpkg for every build so I could use my dependencies (namely SFML). I tried caching vcpkg to reduce build times, but caching vcpkg uses about 300 MiB per configuration and I have 4 configurations. That is more than my 1 GiB allotment. I am currently compromising and manually updating vcpkg each build, but caching the built libraries, but an updated built-in vcpkg would help immensely.

**Comment by FeodorFitsner** [comment]
Could you please suggest the command updating vcpkg packages?

**Comment by drako0812** [comment]
What I have to do during my install script is:

```
cd "C:\Tools\vcpkg"
git pull
.\bootstrap-vcpkg.bat
cd "C:\projects\<project-name>
```
