### ISSUE TITLE
Bundler 1.16.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1926]
`bundler.bat` is not available anymore.

**Comment by ashmaroli** [comment]
Why is `bundler.bat` not available anymore?

**Comment by FeodorFitsner** [comment]
When we refresh Ruby versions and gems on build worker images we do not do in-place "upgrade", but we do clean Ruby install. Right after install `gem update --system` is run to update rubygems. Apparently, Bundler 1.16.0 is being pulled by latest `gem update --system` and `bundler.bat` is not in `bin` folder anymore, only `bundle.bat`. Is it a regression or intended "change" - we could ask Ruby devs.

I just did clean re-install of Ruby 2.4 on my dev machine and got only `bundle.bat`:

![image](https://user-images.githubusercontent.com/5041459/32986904-1ee02e9a-cc91-11e7-8587-acc8661de5c3.png)

This is installation log for clean Ruby 2.4 install:

```
c:\>ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

c:\>gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.2.gem (100%)
Successfully installed rubygems-update-2.7.2
Parsing documentation for rubygems-update-2.7.2
Installing ri documentation for rubygems-update-2.7.2
Installing darkfish documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 34 seconds
Parsing documentation for rubygems-update-2.7.2
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.2
Bundler 1.16.0 installed
RubyGems 2.7.2 installed
Regenerating binstubs
RubyGems system software updated
```

**Comment by FeodorFitsner** [comment]
File an issue on Bundler: https://github.com/bundler/bundler/issues/6176

**Comment by ashmaroli** [comment]
I don't think this is a bug within Bundler, but rather within Rubygems..

**Comment by FeodorFitsner** [comment]
Maybe - let's wait for Bundler team response. Personally, I think it's better (and safer) to do a switch to `bundle`. We did so in all our projects. [Their docs](http://bundler.io/docs.html) use only `bundle` command as well.

**Comment by ashmaroli** [comment]
Probably. IMO, the easiest fix is uninstalling Bundler and re-installing manually with `gem install bundler` and shipping a new AppVeyor Image.. :smiley: 

Of course, I know its easier said than done..

**Comment by FeodorFitsner** [comment]
Right, let me see if we can do a quick fix though...
