### ISSUE TITLE
How to use Square Brackets in appveyor.yml?

### ISSUE THREAD

**Issue by roozbehid-ic** [appveyor/ci#1930]
I want to have following code but it gives me an error because of square brackets

    init:
     - tzutil /s "Mountain Standard Time"
     - ps: [System.TimeZoneInfo]::ClearCachedData()

**Comment by IlyaFinkelshteyn** [comment]
Use single quotes, e.g. `- ps: '[System.TimeZoneInfo]::ClearCachedData()'`. Note that you can always enter the command in UI, and then use **Export YAML** menu option to get correct syntax.
