### ISSUE TITLE
Error connecting FTP server: A call to SSPI failed, see inner exception.

### ISSUE THREAD

**Issue by jeroen** [appveyor/ci#1931]
Keep getting [this error](https://ci.appveyor.com/project/jeroen/base/build/1.0.39/job/gdqbibt62meh1e8e) when trying to deploy to ftp/ftps. Happens both with and without `beta: true`.

```
Collecting artifacts...
Found artifact 'R-3.4.2patched-win.zip' matching 'R-3.4.2patched-win.zip' path
Uploading artifacts...
[1/1] R-3.4.2patched-win.zip (82,499,581 bytes)...100%
Deploying using FTP provider
220 (vsFTPd 3.0.3)
AUTH TLS
234 Proceed with negotiation.
Error connecting FTP server: A call to SSPI failed, see inner exception.
```

What would be a way to debug this? I verified the ftp credentials and they are OK.

**Comment by jeroen** [comment]
Ah perhaps the issue is that my server is using a self signed certificate. Is there any  way I can skip the check?

**Comment by IlyaFinkelshteyn** [comment]
It should be able to negotiate any of the following: SSL 3, TLS, TLS 1.1, TLS 1.2. Can you create test account on your server and send to `team at appveyor com` for us to debug?

**Comment by jeroen** [comment]
OK I sent the email.

**Comment by jeroen** [comment]
Closing this because I switched to sftp so I am no longer blocked by this. 

For future reference: the problem is in the ssl protocol negotiation between vsFTPd and the Windows ftps client. The problem was partly solved by disabling SSL3 in vsFTPD:

```
ssl_tlsv1=YES
ssl_sslv3=NO
ssl_ciphers=HIGH
```

This allowed to connect but it still [fails](https://ci.appveyor.com/project/jeroen/base/build/1.0.44/job/dfqbu8hx94w54n1i) for data transfer connections:
```
Uploading "archive/r-release/73368/32bit.log"...TYPE I
200 Switching to Binary mode.
SIZE archive/r-release/73368/32bit.log
213 421217
EPSV
229 Entering Extended Passive Mode (|||42171|)
STOR archive/r-release/73368/32bit.log
150 Ok to send data.
Time to activate encryption: 0h 0m 0s, Total Seconds: 0.1406301.
426 Failure reading network stream.
Disposing FtpSocketStream...
QUIT
221 Goodbye.
Failure reading network stream.
```
This is where I gave up and switched to sftp (over ssh) instead.
