### ISSUE TITLE
File overwriting option for FTP deployment

### ISSUE THREAD

**Issue by jeroen** [appveyor/ci#1936]
Is it possible for `ftps` deployment to automatically overwrite existing files on the FTP server? Currently it seems to skip over files that already exist. I would like to update them instead.

**Comment by IlyaFinkelshteyn** [comment]
It overwrites file if file already exists in the target folder. Just double checked with code and tested in lab...

**Comment by jeroen** [comment]
I think it may be another issue then. It looks like my build sometimes hit the time limit, in the middle of a deploy (the sftp upload is very slow and takes a few minutes).

Could it be that appveyor kills of the vm in the middle of a deploy? That would explain why some of the files were not updated.

**Comment by IlyaFinkelshteyn** [comment]
Can you point to the specific build?

**Comment by jeroen** [comment]
The [latest build](https://ci.appveyor.com/project/jeroen/base/build/1.0.49) seems to have correctly updated all files indeed. So my initial diagnosis was incorrect, the ftp deployment **does** overwrite existing files, at least for sftp.

Still not sure why some previous deployments contained a bunch of old files. I went though the build history and there were a few timouts like [this one](https://ci.appveyor.com/project/jeroen/base/build/1.0.41/job/u3d5x9991s8om6gw/messages) but none during the deploy phase.

Anyway given that my builds are often near the time limit; it's still a valid concern. Does appveyor kill the build in the middle of a deploy, or does it wait until the deploy has completed @IlyaFinkelshteyn ? 

Thanks for your amazing support!

**Comment by IlyaFinkelshteyn** [comment]
Thank you :) When build timeout reached, build VM just being destroyed regardless of what stage build is in. 

You can look at "Environment" deployment. Some info is here:
https://www.appveyor.com/docs/deployment/#overview
https://www.appveyor.com/docs/deployment/environment/

Environment deployment timeout is 20 minutes so you can create two Environments, one for each artifact. Note though that Environment deployment is asynchronous ("fire and forget" from the build point of view) and failed deployment do not fail the build.

Another option is to add say 10 minutes to your build timeout, if that is going to be enough.

**Comment by jeroen** [comment]
@IlyaFinkelshteyn I have converted to environment deployment and that seems more reliable. Thank you! The ftp upload deployment is still a bit slow (about 15 min for a 80MB file) but at least it has not timed out yet.

**Comment by IlyaFinkelshteyn** [comment]
Good, ping us if you need deployment timeout increase. We can do it too, within reasonable bounds.

**Comment by jeroen** [comment]
OK great. I'm going to close this issue now because it has gone off topic. If I run into timeout limits I may bother you again :)
