### ISSUE TITLE
New failures with freeze_gun on all Python versions

### ISSUE THREAD

**Issue by pganssle** [appveyor/ci#1937]
Posted this also at spulec/freezegun#214 because I'm not sure if this is an Appveyor or freeze_gun issue or both, but all my builds using `freeze_gun` started breaking on Appveyor recently due to a failure to import `syslog`, but in a kinda weird way.

From [this build](https://ci.appveyor.com/project/dateutil/dateutil/build/2.3.823/job/01qcd77i23scpyus):

```python
================================== FAILURES ===================================
_____________________________ UtilsTest.testToday _____________________________
c:\python27\lib\site-packages\freezegun\api.py:494: in wrapper
    with self:
c:\python27\lib\site-packages\freezegun\api.py:365: in __enter__
    return self.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <freezegun.api._freeze_time object at 0x03B419B0>
          [ ... trimmed ... ]
    
        with warnings.catch_warnings():
            warnings.filterwarnings('ignore')
    
            for mod_name, module in list(sys.modules.items()):
                if mod_name is None or module is None:
                    continue
                elif mod_name.startswith(self.ignore):
                    continue
                elif (not hasattr(module, "__name__") or module.__name__ in ('datetime', 'time')):
                    continue
>               for module_attribute in dir(module):
E               ImportError: No module named syslog
c:\python27\lib\site-packages\freezegun\api.py:421: ImportError
```

I'm not quite sure why `syslog` is in `sys.modules.items()` in the first place, nor why the `ImportError` is being raised only when `dir(module)` is called, but it seems like the issue arose recently, because re-building builds that worked recently is now breaking.

**Comment by IlyaFinkelshteyn** [comment]
Feels like related to https://github.com/pytest-dev/py/pull/171

**Comment by FeodorFitsner** [comment]
It's been fixed in the mainstream: https://github.com/pytest-dev/py/issues/169
