### ISSUE TITLE
error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. 

### ISSUE THREAD

**Issue by m-tmatma** [appveyor/ci#1947]
I was using Visual Studio 2015, then switched to Visual Studio 2017.
Then I changed 'Build worker images' to Visual Studio 2017.
But I am still getting the error.

I saw #1719. But I can't resolve it yet.
I tried both UI setting and appveyor.yml with "image: Visual Studio 2017".

**Comment by FeodorFitsner** [comment]
In addition to setting `image: Visual Studio 2017` you can also try setting path to MSBuild 15.0 explicitly in your build:

```
init:
- set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%
```

**Comment by m-tmatma** [comment]
Thanks.
It worked.
I used the full path to invoke msbuild.exe.
("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe")
