### ISSUE TITLE
Trying to find a deployment on a given date is... impossible?

### ISSUE THREAD

**Issue by ctolkien** [appveyor/ci#1948]
Once you go a certain distance back, simply listing how many months ago doesn't really help? Am trying to look for a deployment on a certain date.. and I don't think the deployment date is actually displayed anywhere.

![image](https://user-images.githubusercontent.com/515955/33111358-bc586788-cfa1-11e7-81ad-aae72e8c7210.png)

**Comment by FeodorFitsner** [comment]
You should see exact date/time by hovering mouse over that “ago” date.

**Comment by Ede123** [comment]
It might be nice if one could navigate / sort / filter by
* commit hash
* branch
* job name

Navigating is extremely inconvenient even if one knows what to search for...

Along these lines I'd also like to give #1564 a push... It's currently impossible to get a link that would lead to the latest build of a specific branch (which would at least be a workaround to having a predictable download link for the artifcats).
