### ISSUE TITLE
Update Qt 5.9.2 to 5.9.3

### ISSUE THREAD

**Issue by ismail** [appveyor/ci#1949]
It's the latest LTS release: https://blog.qt.io/blog/2017/11/22/qt-5-9-3-released/ Thank you!

```
rd C:\Qt\5.9
mklink /J C:\Qt\5.9 C:\qt\5.9.3
```

**Comment by FeodorFitsner** [comment]
Thanks for letting know!

**Comment by ismail** [comment]
Meanwhile also Qt 5.10 is out :)

**Comment by thiagomacieira** [comment]
Qt 5.9.4 is out today. Looks like the `C:\Qt\5.9` link is broken.

**Comment by FeodorFitsner** [comment]
The link should be good now. Thanks for the catch!
For Qt 5.9.4 I've just created a new issue: https://github.com/appveyor/ci/issues/2046

**Comment by thiagomacieira** [comment]
Confirmed. I've just rebuilt my project that was failing and it's now passing.
