### ISSUE TITLE
cccccchcedvegtrgggnctffrlrnnfhbfledbvvvcdnjc

### ISSUE THREAD

**Issue by SPodjasek** [appveyor/ci#1951]

**Comment by FeodorFitsner** [comment]
@SPodjasek is it like something dropped on your keyboard or kids playing with your computer? 😄

**Comment by SPodjasek** [comment]
Sorry... my kid was playing with this shiny little thing sticking out of my USB, which happens to be my YubiKey. So it generated some TOTP tokens which by coincidence start with 'c' and that surprisingly is "New issue" keyboard shortcut on Issues page.
:sweat_smile:

**Comment by FeodorFitsner** [comment]
Ha, nice! Was in the same situation once 😄
