### ISSUE TITLE
Update npm to 5.6.0

### ISSUE THREAD

**Issue by filipesilva** [appveyor/ci#1958]
There's a particularly nasty problem with `npm` where rolling back optional packages in windows often causes problems: https://github.com/npm/npm/issues/17671. This often causes flakes in Appveyor runs.

It seems to be mostly fixed in `npm@5.6.0` so it would be nice if it was updated.

**Comment by FeodorFitsner** [comment]
You can install the latest npm during the build with the following commands:

```
npm -g install npm@latest
set PATH=%APPDATA%\npm;%PATH%
```

**Comment by filipesilva** [comment]
Roger, will do that meanwhile. Thanks for the tip 👍

**Comment by felixfbecker** [comment]
Note: npm 5.6 is currently `@next`, not `@latest`.

**Comment by XhmikosR** [comment]
@FeodorFitsner This can be closed.
