### ISSUE TITLE
Visual Studio 2017 15.5.1

### ISSUE THREAD

**Issue by janisozaur** [appveyor/ci#1963]
Version 15.5 is out

https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.5

**Comment by FeodorFitsner** [comment]
Thanks for letting us know!

**Comment by matt77hias** [comment]
Any ideas when the VS image will be updated on your servers?

**Comment by FeodorFitsner** [comment]
Will try pushing that this week. Thanks for your patience.

**Comment by TheBeardedLlama** [comment]
@FeodorFitsner is this definitely completed? I am still getting errors in the build

I was getting those errors on my local too until I updated VS2017
