### ISSUE TITLE
Cmake 3.10.1

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1969]

**Comment by ismail** [comment]
Please wait for 3.10.1 instead since 3.10.0 breaks clang-cl usage: https://gitlab.kitware.com/cmake/cmake/merge_requests/1522

**Comment by FeodorFitsner** [comment]
@ismail Thank you for letting know about this issue!

**Comment by ismail** [comment]
cmake 3.10.1 is now out: https://blog.kitware.com/cmake-3-10-1-available-for-download/

**Comment by robindegen** [comment]
Is there any update for when this will be integrated? (or what is the status of the 14-jan-2018 milestone?)

**Comment by FeodorFitsner** [comment]
It's coming in the next update for sure. [14-jan-2018](https://github.com/appveyor/ci/milestone/104) milestone is quite massive, so it needs more time to test. We are currently looking at the end of this week.

**Comment by robindegen** [comment]
@FeodorFitsner Great thank you.

**Comment by robindegen** [comment]
@FeodorFitsner Is there anything in specific I need to do to enable 3.10 now that this issue is closed?

I'm still receiving the error:
```
CMake Error at CMakeLists.txt:24 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 3.8.2
```

When trying to rebuild old builds that failed because of this.

**Comment by FeodorFitsner** [comment]
It should be in a `PATH`. Make sure you use current image.

**Comment by robindegen** [comment]
@FeodorFitsner Apparently it only works on the regular Visual Studio 2017, but not on the Preview version. Is this supposed to be like that? And if so, when will cmake 3.10 be added to the preview image? Thanks

**Comment by robindegen** [comment]
@FeodorFitsner I had the "Preview" still selected. And I think this is the pre-release preview, not the preview of upcoming updates right? Putting it on Vs2017 worked. Thanks

**Comment by FeodorFitsner** [comment]
Added a new issue for that: https://github.com/appveyor/ci/issues/2048
