### ISSUE TITLE
[Windows SDK] missing license file from the version #16299

### ISSUE THREAD

**Issue by cenit** [appveyor/ci#1980]
I started having an issue: vcpkg cannot find the file
```
C:/Program Files (x86)/Windows  Kits/10/Licenses/10.0.16299.0/sdk_license.rtf
```
inside the Windows SDK 16299 and so some scripts cannot go on.

edit: the forward slashes are not the problem since it used to work perfectly ;)

**Comment by IlyaFinkelshteyn** [comment]
Indeed this files is gone after [last build image update](https://www.appveyor.com/updates/). Not sure what exactly, made it gone. Will take a look. Please use `Previous` image for now.

**Comment by IlyaFinkelshteyn** [comment]
@cenit can you please provide a repro?

**Comment by cenit** [comment]
@IlyaFinkelshteyn thanks for looking into this
Here it is a project that started failing
https://ci.appveyor.com/project/cenit/intrphysycom

**Comment by cenit** [comment]
any news on it?

**Comment by IlyaFinkelshteyn** [comment]
Sorry this is still open issue, planned to be fixed in next update. Workaround is to add the following at `install` stage:

```posh
Write-Host "Installing Windows 10 SDK 10.0.16299.91..." -ForegroundColor Cyan
Write-Host "Downloading Windows 10 SDK..."
$exePath = "$env:TEMP\winsdksetup.exe"
(New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/8/C/3/8C37C5CE-C6B9-4CC8-8B5F-149A9C976035/windowssdk/winsdksetup.exe', $exePath)
Write-Host "Installing Windows 10 SDK..."
cmd /c start /wait "$exePath" /quiet /norestart
del $exePath 
```

It will cost your build from 5 t0 10 minutes, but should fix the problem.

**Comment by cenit** [comment]
Fixed in vcpkg https://github.com/Microsoft/vcpkg/pull/2648
Really sorry for the troubles, it was not an appveyor problem in the end.

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!

Will make sure vcpkg is updated in the next image update: https://github.com/appveyor/ci/issues/2051
