### ISSUE TITLE
.NET Core SDK 2.1.4

### ISSUE THREAD

**Issue by plioi** [appveyor/ci#1991]
Similar to https://github.com/appveyor/ci/issues/1935 there is a new .NET Core SDK version to include in an image update.  This version has important fixes enabling .NET Framework projects to reference netstandard2.0 libraries.

**Comment by FeodorFitsner** [comment]
It's on `Visual Studio 2017` image already - give it a try. Will deploy to VS 2015 though.

**Comment by plioi** [comment]
Thanks. Works!

**Comment by FeodorFitsner** [comment]
Let's keep it opened to make sure VS 2015 images updated.
