### ISSUE TITLE
Python error: failed to get random numbers

### ISSUE THREAD

**Issue by Rudloff** [appveyor/ci#1995]
Hello,

Since today, I get this error when I try to run `C:\Python36\python.exe`:
```
Fatal Python error: failed to get random numbers to initialize Python
```

It used to work correctly before.

**Comment by Rudloff** [comment]
Turns out I can't reproduce with a minimal `.appveyor.yml` so it must be something wrong with my setup.

**Comment by jayvdb** [comment]
@orsinium , I guess from https://github.com/dephell/dephell_venvs/issues/1 that you also encountered this, and it was because of the envvar `PYTHON` was set?

**Comment by orsinium** [comment]
@jayvdb thank you for mentioning.

> if anyone has the same issue, the Python process needs to inherit AppVeyor's environment variables to work.

That's the answer that helped me. I tried to use totally clean environment for subprocess, but it doesn't work for appveyor

https://github.com/dephell/dephell_venvs/blob/2cedadfc709ddbc3a381417f6b20e06251d62629/dephell_venvs/_builder.py#L108

**Comment by orsinium** [comment]
> it was because of the envvar PYTHON was set?

No, it's because I dropped all other variables as well. I didn't discover which var exactly appveyor needs, but it's not `PYTHON*`

**Comment by jimporter** [comment]
For what it's worth, I ran into a similar issue on Github CI and it seems the magic environment variable you need is `SYSTEMROOT`. Based on this PR I found, you may only need to include `SYSTEMROOT` if `PATH` is set: https://github.com/nerdvegas/rez/pull/775.
