### ISSUE TITLE
Unable to Create New Account

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [appveyor/ci#2001]
Each time I tried to connect my github account with appveyor, I would meet this error:
"There was an error while creating new AppVeyor account. Please contact AppVeyor support."

I have no idea what's going on, is there any advice?

**Comment by FloriansGit** [comment]
I have the same problem. Tried with Chrome, Edge and Firefox. Revoked the access rights after having granted them to start over again. No luck.

![image](https://user-images.githubusercontent.com/13184503/35526454-bc1a29d0-0527-11e8-8923-7b9d8931aa20.png)

**Comment by Yannnnnnnnnnnn** [comment]
Anyone can help us?

**Comment by shrektan** [comment]
I meet the same case. Revoke doesn't help.

**Comment by lbininhbl** [comment]
No body can help?

**Comment by Undefined01** [comment]
I got the same problem.

**Comment by zdzhaoyong** [comment]
Seems no body helps...

**Comment by standbyme** [comment]
I have emailed to official Email account. No reply....

**Comment by zhztheplayer** [comment]
Same issue when I login with my Github account or try to sign up via https://ci.appveyor.com/signup.

**Comment by fengjiachun** [comment]
Me too. Revoke doesn't work.

**Comment by haozia816** [comment]
Me too. error message: "There was an error while creating new AppVeyor account. Please contact AppVeyor support."

**Comment by InanisV** [comment]
Me too. Have the same problem and cannot signup with my github account.

**Comment by Hades-001** [comment]
Me too. Have the same problem and cannot signup with my github account.

**Comment by canyie** [comment]
Same. And I noticed that we all seem to be from China, it's strange.

**Comment by fangbinwei** [comment]
I can sign up with gmail

**Comment by PJ-Ming1** [comment]
> Anyone can help us?

Maybe you can try to change the registered email of GitHub, i also meet this problem and I solved this problem by creating an account with a new email address
