### ISSUE TITLE
miniconda should have the conda-build package installed by default

### ISSUE THREAD

**Issue by swaldhoer** [appveyor/ci#2002]
# What's missing (in my opinion)
The package `conda-build` is not installed by default in AppVeyor's `miniconda`.

# How to fix
Install `conda-build` in the `miniconda`s available on AppVeyor.

# Benefit
There are 8 versions of [miniconda](https://www.appveyor.com/docs/build-environment/#miniconda) installed on the VM. If I need to installed `conda-build` in every version, this makes the build significant slower.
Therefore all projects building `conda` packages would no longer have to install the package by hand.

# Drawback
There is non in my opinion.

**Comment by FeodorFitsner** [comment]
Shouldn't be updated every time then?

**Comment by swaldhoer** [comment]
I do not fully understand what you mean. Could you please elaborate a bit more on that sentence?

**Comment by FeodorFitsner** [comment]
I mean if we pre-install conda-build package it should be constantly updated then? What's better for others - installing the latest (or specific version) package in their builds or finding out there is an older package pre-installed that needs to be upgraded/re-installed?

**Comment by swaldhoer** [comment]
I personally try to always use the latest version. But for each package I build successfully I save the `conda-build` version used and roll back if I see errors that are **not** related to the package, but to `conda-build`. Therefore, I can still build "good" updated packages, but with an older `conda-build ` version.
How often are your VM’s updated? As `conda-build` get updated relatively often, maybe this should be considered?

Long-story short:
- As default the (or somewhat near) latest version would be good.
- Better would be if you can specify the `conda-build` version somewhere in `appveyor.yml`, but I think this would cause some implementation work, and I don’t know how many people will use/need it. Furthermore, I have no good idea in which section something like that would be specified.

**Comment by swaldhoer** [comment]
Any update on this?

**Comment by jakirkham** [comment]
Agree this is probably a good idea. Might help cutdown our build times a bit.

cc @isuruf @msarahan @mariusvniekerk

**Comment by swaldhoer** [comment]
If you fix the missing `conda-build` package, you should also include `conda-verify` as `conda-build` tries to run a verify step after building. If `conda-verify` is missing, nothing happens, but a I am sure there are people who would like to verify the packages and it does not have any drawbacks to install it by default.

**Comment by FeodorFitsner** [comment]
So, what command(s) should we use to pre-install those packages? Thank you!

**Comment by swaldhoer** [comment]
You can install it by: `conda install conda-build conda-verfiy -y`
