### ISSUE TITLE
Link error for non-existing lib file

### ISSUE THREAD

**Issue by matt77hias** [appveyor/ci#2014]
I use Visual Studio 2017 15.5.2. 
My solution includes 5 projects (C++) which successfully build locally. Unfortunately, AppVeyor does not succeed to build due to a linker error:

`LINK : fatal error LNK1181: cannot open input file 'C:\projects\mage\MAGE\Shaders\bin\x64\Release\Shaders.lib' [C:\projects\mage\MAGE\FPS.vcxproj]`

`Shaders.lib` is, however, the only of the 5 projects that does not result in a `.exe` or `.lib` file. It merely contains some HLSL shaders which are compiled to C++ header files. So, I have no idea how that `.lib` is somehow involved in the build process?

**Comment by matt77hias** [comment]
I tried this on multiple PCs using clean clones and the same level of output verbosity, but I never encounter a line mentioning that non-existing lib?

**Comment by IlyaFinkelshteyn** [comment]
@matt77hias is it possible to create a repro in a public repo for us to investigate?

**Comment by matt77hias** [comment]
- [Github Repository](https://github.com/matt77hias/MAGE)
- [AppVeyor output](https://ci.appveyor.com/project/matt77hias/MAGE/build/job/24cg59a7hlym3ksg)
- Local output after a Clean Solution + Rebuild Solution:
```
1>------ Rebuild All started: Project: Shaders, Configuration: Release x64 ------
2>------ Rebuild All started: Project: Utilities, Configuration: Release x64 ------
1>Target PrepareForBuild:
1>  Creating directory "Shaders\bin\x64\Release\".
1>Target InitializeBuildStatus:
1>  Creating "Shaders\tmp\x64\Release\Shaders.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
2>Target InitializeBuildStatus:
2>  Creating "Utilities\tmp\x64\Release\Utilities.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
2>Target ClCompile:
2>  ...
1>Target FxCompile:
1>  ...
2>Target Lib:
2>  Utilities.vcxproj -> D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Utilities\bin\x64\Release\Utilities.lib
2>Target FinalizeBuildStatus:
2>  Deleting file "Utilities\tmp\x64\Release\Utilities.tlog\unsuccessfulbuild".
2>  Touching "Utilities\tmp\x64\Release\Utilities.tlog\Utilities.lastbuildstate".
2>
2>Build succeeded.
2>    0 Warning(s)
2>    0 Error(s)
1>Target FinalizeBuildStatus:
1>  Deleting file "Shaders\tmp\x64\Release\Shaders.tlog\unsuccessfulbuild".
1>  Touching "Shaders\tmp\x64\Release\Shaders.tlog\Shaders.lastbuildstate".
1>Target CleanupEmptyRefsFolder:
1>  Removing directory "D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Shaders\bin\x64\Release\".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
3>------ Rebuild All started: Project: MAGE, Configuration: Release x64 ------
3>Target InitializeBuildStatus:
3>  Creating "MAGE\tmp\x64\Release\MAGE.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
3>Target ClCompile:
3>  ...
3>Target Lib:
3>  MAGE.vcxproj -> D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\MAGE\bin\x64\Release\MAGE.lib
3>Target FinalizeBuildStatus:
3>  Deleting file "MAGE\tmp\x64\Release\MAGE.tlog\unsuccessfulbuild".
3>  Touching "MAGE\tmp\x64\Release\MAGE.tlog\MAGE.lastbuildstate".
3>
3>Build succeeded.
3>    0 Warning(s)
3>    0 Error(s)
4>------ Rebuild All started: Project: Scripts, Configuration: Release x64 ------
4>Target InitializeBuildStatus:
4>  Creating "Scripts\tmp\x64\Release\Scripts.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
4>Target ClCompile:
4>  ...
4>Target Lib:
4>  Scripts.vcxproj -> D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Scripts\bin\x64\Release\Scripts.lib
4>Target FinalizeBuildStatus:
4>  Deleting file "Scripts\tmp\x64\Release\Scripts.tlog\unsuccessfulbuild".
4>  Touching "Scripts\tmp\x64\Release\Scripts.tlog\Scripts.lastbuildstate".
4>
4>Build succeeded.
4>    0 Warning(s)
4>    0 Error(s)
5>------ Rebuild All started: Project: FPS, Configuration: Release x64 ------
5>Target ResolveProjectReferences:
5>  Target GetNativeManifest:
5>Target InitializeBuildStatus:
5>  Creating "FPS\tmp\x64\Release\FPS.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
5>Target ClCompile:
5>  ...
5>Target ResolvedLinkLib:
5>Target Link:
5>     Creating library FPS\bin\x64\Release\FPS.lib and object FPS\bin\x64\Release\FPS.exp
5>  Generating code
5>  All 12535 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
5>  Finished generating code
5>  FPS.vcxproj -> D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\FPS\bin\x64\Release\FPS.exe
5>Target GetCopyToOutputDirectoryItems:
5>  Target AssignTargetPaths:
5>Target FinalizeBuildStatus:
5>  Deleting file "FPS\tmp\x64\Release\FPS.tlog\unsuccessfulbuild".
5>  Touching "FPS\tmp\x64\Release\FPS.tlog\FPS.lastbuildstate".
5>
5>Build succeeded.
5>    0 Warning(s)
5>    0 Error(s)
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========
```

**Comment by matt77hias** [comment]
It is also worth noting the difference in command line options for the linker.

Release|x64 as shown in Visual Studio:

`/OUT:"FPS\bin\x64\Release\FPS.exe" /MANIFEST /LTCG:incremental /NXCOMPAT /PDB:"FPS\bin\x64\Release\FPS.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" "D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\MAGE\bin\x64\Release\MAGE.lib" "D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Math\bin\x64\Release\Math.lib" "D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Scripts\bin\x64\Release\Scripts.lib" "D:\Users\Matthias\Documents\Visual Studio 2017\Projects\MAGE\MAGE\Utilities\bin\x64\Release\Utilities.lib" /DEBUG /MACHINE:X64 /OPT:REF /INCREMENTAL:NO /PGD:"FPS\bin\x64\Release\FPS.pgd" /SUBSYSTEM:WINDOWS /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"FPS\tmp\x64\Release\FPS.exe.intermediate.manifest" /OPT:ICF /ERRORREPORT:PROMPT /NOLOGO /TLBID:1 `

Release|x64 as shown in AppVeyor output:

```
/OUT:"FPS\bin\x64\Release\FPS.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\lib" /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\lib\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\Tools\vcpkg\installed\x64-windows\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"FPS\bin\x64\Release\FPS.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"FPS\bin\x64\Release\FPS.lib" /MACHINE:X64 FPS\tmp\x64\Release\engine_settings.res
         FPS\tmp\x64\Release\display_settings.res
         FPS\tmp\x64\Release\FPS.obj
         FPS\tmp\x64\Release\brdf_scene.obj
         FPS\tmp\x64\Release\forrest_scene.obj
         FPS\tmp\x64\Release\sibenik_scene.obj
         FPS\tmp\x64\Release\sponza_scene.obj
         C:\projects\mage\MAGE\Utilities\bin\x64\Release\Utilities.lib
         C:\projects\mage\MAGE\Math\bin\x64\Release\Math.lib
         C:\projects\mage\MAGE\Shaders\bin\x64\Release\Shaders.lib
         C:\projects\mage\MAGE\MAGE\bin\x64\Release\MAGE.lib
         C:\projects\mage\MAGE\Scripts\bin\x64\Release\Scripts.lib


```

**Comment by matt77hias** [comment]
After trying some approaches, I found a workaround to trick AppVeyor. 

Setting the project configuration type to `Utility` works for header-only projects. It works for projects containing shader files as well at the expense of losing `HLSL Compiler` from the the `Configuration Properties` for the project and its shader files.

Setting the project configuration type to `Application` works for header-only projects and projects containing shader files without losing `HLSL Compiler` from the the `Configuration Properties` for the project and its shader files.

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for update -- we could not find this solution ourselves.

**Comment by matt77hias** [comment]
I am closing this issue, since the cause of the problem is Visual Studio not having flexible enough configuration types.
