### ISSUE TITLE
Download from external server failing

### ISSUE THREAD

**Issue by hkaiser** [appveyor/ci#2015]
We suddenly see download failures from an external server (see for instance here: https://ci.appveyor.com/project/hkaiser/hpx/build/master-1614/job/0tk0vp9y6kb47oud). The file in question is definitely available. Any suggestions?

**Comment by IlyaFinkelshteyn** [comment]
Do you restrict downloads by the source IP address. If yes, this maybe the reason. We added another external IP `67.225.138.82` recently. Please update your access list. Sorry for the inconvenience.

Side note: consider using [build cache]() and download only if cached folder does not contain what you need. 

Please let us know if this helps.

**Comment by hkaiser** [comment]
That did the trick, thanks!
