### ISSUE TITLE
C:/Miniconda36 has Python 2.7 instead of 3.6

### ISSUE THREAD

**Issue by native-api** [appveyor/ci#2023]
According to https://ci.appveyor.com/project/matthew-brett/multibuild/build/1.0.171/job/e4g3n3f6vk3wthwx :

> Environment: PYTHON=C:\Miniconda36, PYTHON_VERSION=3.6, PYTHON_ARCH=32
>
> SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
> conda info
> Current conda install:
> &lt;...&gt;
> python version : 2.7.14.final.0
> root environment : C:\Miniconda36  (writable)

**Comment by native-api** [comment]
Could you do a quick check if your environment is okay? If it is, this means the script does something really weird and somehow replaces the installation without anyone seeing.

**Comment by IlyaFinkelshteyn** [comment]
[here](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/build/33.464.971) is simple build testing those folders. It does not install anything, but uses pre-installed [miniconda versions](https://www.appveyor.com/docs/build-environment/#miniconda). I am not sure but I have a feeling that [install.ps1](https://github.com/matthew-brett/multibuild/blob/devel/ci/appveyor/install.ps1) doing something weird. Not sure if you need it though, as all those versions are pre-installed.

**Comment by IlyaFinkelshteyn** [comment]
I am closing this issue. Please feel free to re-open if you feel that problem is still related to the AppVeyor infrastructure.

**Comment by native-api** [comment]
Without the call to `install.ps1`, the problem vanishes: https://ci.appveyor.com/project/native-api/multibuild/build/1.0.4 . Looks like those hacks are no longer needed. I don't feel like digging this any deeper.

**Comment by IlyaFinkelshteyn** [comment]
@native-api good, thanks a lot for the update :)
