### ISSUE TITLE
Mingw64 always compile i386 dll

### ISSUE THREAD

**Issue by davide-romanini** [appveyor/ci#2032]
I'm struggling trying to automate my comictagger windows build on appveyor: https://github.com/davide-romanini/comictagger/tree/feature/101-appveyor

I tested my build script on a windows 10 [Modern IE VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), running:
 - Miniconda
 - Mingw (installed via Chocolatey)

The resulting application includes a compiled version of libunrar that works without problems.
But when running on appveyor, I can't compile unrar code in x86_64. I'm installing the same mingw version I have locally (with choco).
```
c++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
The resulting dll generated, as seen with `objdump -af`:

```
unrar/libunrar.so:     file format pei-i386
unrar/libunrar.so
architecture: i386, flags 0x0000013b:
HAS_RELOC, EXEC_P, HAS_DEBUG, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x6ee81410
```
My local copy compiled with the exact same copy of mingw and c++ shows:
```
 objdump -af .\ext\unrar\libunrar.so

.\ext\unrar\libunrar.so:     file format pei-x86-64
.\ext\unrar\libunrar.so
architecture: i386:x86-64, flags 0x0000013b:
HAS_RELOC, EXEC_P, HAS_DEBUG, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x000000006ec813e0
```

I also tried all mingw versions available on appeveyor, but have no clue what am I doing wrong..
Any help will be appreciated.

**Comment by IlyaFinkelshteyn** [comment]
[This](https://github.com/davide-romanini/comictagger/blob/feature/101-appveyor/windows/fullbuild.ps1#L2) line looks suspicious for me. It places new path into the end, so it has least priority. Try `$env:PATH="C:\tools\mingw64\bin;C:\Miniconda-x64;C:\Miniconda-x64\Scripts;$env:path"` instead.

**Comment by davide-romanini** [comment]
Thanks, it saved my night. :+1: 
I used several combination for %PATH% and lost myself.
