### ISSUE TITLE
Pull Requests From "Feature Branches" Increment Build Number

### ISSUE THREAD

**Issue by RobertBColton** [appveyor/ci#2037]
Ok, so this is pretty simple: #351 added a feature for PRs to not increment the build number. However, it seems to only work when a PR is sent from the master branch. But it does not work if a feature or change is made in a branch of a fork other than master and then the PR is opened on master. What happens is the build number is incremented.

You can see evidence of this in our project history:
https://ci.appveyor.com/project/enigma-dev/enigma-dev/history
Despite having this setting enabled, PRs keep incrementing our build number.

**Comment by IlyaFinkelshteyn** [comment]
`appveyor.yml` (both in [master](https://github.com/enigma-dev/enigma-dev/blob/master/appveyor.yml) and [feature](https://github.com/enigma-dev/enigma-dev/blob/3df33cc05e268f1cb486caba58dcc8ff1ca1933d/appveyor.yml) branches) does not contains this setting:

```
pull_requests:
  do_not_increment_build_number: true
```

You probably set `Pull Requests do not increment build number` in UI. This is not UI-only feature (like for example `Enable secure variables in Pull Requests from the same repository only` which is UI-only for obvious security reasons), and `appveyor.yml` takes over UI. Note that this setting should be in `appveyor.yml` in feature branch so if some branch was forked before this change it should be updated from `master`.
