### ISSUE TITLE
Adding debug binaries to the Python installation

### ISSUE THREAD

**Issue by ghost** [appveyor/ci#2040]
Is it possible to add debug binaries to the Python installations? Specifically `python_d.exe`, `python36_d.lib`, and `python36_d.dll`?

**Comment by FeodorFitsner** [comment]
Standard Python installers don't have them. Do you know where/how to get them?

**Comment by xoviat** [comment]
Yes, they do. You need to check the "device libraries" box.

**Comment by fwilliams** [comment]
I am also having this issue with AppVeyor. It would be nice to be able to debug my Python/C++ library on AppVeyor.

**Comment by fwilliams** [comment]
@FeodorFitsner Bump. The lack of debug binaries make it hard to debug broken C++/Python code on Appveyor. There is a [workaround](https://bugs.python.org/issue22411) but it requires pretty invasive changes to the code base and throws away debug symbols inside python.

**Comment by IlyaFinkelshteyn** [comment]
@fwilliams for what Python version you need it?

**Comment by IlyaFinkelshteyn** [comment]
Notes for ourselves: add `Include_debug=1` (https://docs.python.org/3.7/using/windows.html)

**Comment by fwilliams** [comment]
@IlyaFinkelshteyn thanks for the reply! 2.7 and 3.X would be nice. I want to run CI for 3.X and 2.7.

**Comment by IlyaFinkelshteyn** [comment]
Hopefully 2.7 installed supports `Include_debug=1` too.

**Comment by fwilliams** [comment]
Let me know what the status is. I don't have a windows machine to test on right now. In the worst case, we'll run the 2.7 build in release mode only.

**Comment by IlyaFinkelshteyn** [comment]
@fwilliams For status please watch this issue and subscribe to "Technical updates" at https://ci.appveyor.com/notifications. We always notify about build images update using that channel.

**Comment by FeodorFitsner** [comment]
Debug symbols will be installed with Python 3.7.5 and 3.8.0 only. For Python 2.7.17 symbols could be downloaded during the build from https://www.python.org/downloads/release/python-2717/

**Comment by khyveasna** [comment]
Hi I'm going to be in

**Comment by khyveasna** [comment]
> have been in contact
