### ISSUE TITLE
CosmosDB 1.20.91.1

### ISSUE THREAD

**Issue by mgiannikouris** [appveyor/ci#2054]
I believe the current emulator version is 1.20.91.1

As of 1.7.0 of the Cosmos .NET Core SDK an emulator update was required (https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet-core). I'm not sure if the version currently in the appveyor build environments is before that change, but we've needed to download the latest emulator as part of our build script before we can run successfully run our integration tests (https://aka.ms/cosmosdb-emulator).

Hopefully the change is old enough that it makes sense to provide the new emulator by default.

**Comment by IlyaFinkelshteyn** [comment]
@mgiannikouris meanwhile you can use [this script](https://gist.github.com/IlyaFinkelshteyn/764e85204f12859e87c1ff1faf9c631e) at `install` stage as a workaround
