### ISSUE TITLE
What does "Enable secure variables in Pull Requests from the same repository only" mean?

### ISSUE THREAD

**Issue by VJalili** [appveyor/ci#2056]
I find the following checkbox label misleading: 

    Enable secure variables in Pull Requests from the same repository only

because I can interpret an **unchecked** checkbox in both following ways: 

a: secure variables are _enabled_ for PRs from **all** repos. 
b: secure variables are _NOT enabled_ 

I would suggest updating the checkbox label to avoid any possible confusion.

**Comment by IlyaFinkelshteyn** [comment]
Though this is described [here](https://www.appveyor.com/docs/build-configuration/#secure-variables), I agree that on UI it could be more self-explainable. Updating checkbox itself will make it too long, but we can add tooltip.

**Comment by VJalili** [comment]
Alternatively, you may link to this documentation.
