### ISSUE TITLE
Error creating GitHub release: Cannot deserialize the current JSON object

### ISSUE THREAD

**Issue by parkouss** [appveyor/ci#206]
Hello,

I'm trying to use the github deployment from appveyor, And I got the following issue:

Error creating GitHub release: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Newtonsoft.Json.Linq.JToken[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'message', line 1, position 11.

appveyor.yml file: https://github.com/parkouss/mozregression/blob/gui-releases/appveyor.yml
Build output: https://ci.appveyor.com/project/parkouss/mozregression-fqsi0

I hope this is not a stupid error of yml formatting from me, but I tried multiple times (looking at http://www.appveyor.com/docs/appveyor-yml and http://www.appveyor.com/docs/deployment/github) without success.

**Comment by parkouss** [comment]
Oh, I just discovered https://ci.appveyor.com/tools/validate-yaml and validated the content of my appveyor.yml file with success so it does not seems to be an issue with the yaml formatting.

**Comment by FeodorFitsner** [comment]
Most probably `auth_token` provided is invalid. Try running this request:

    GET https://api.github.com/repos/parkouss/mozregression/releases?page=1&per_page=10

    With this header:
      Authorization: token <your_auth_token>

**Comment by parkouss** [comment]
Thanks for your quick answer ! You lead me on the right direction.
It appears that my auth_token was valid, but I reused the encryption provided by travis-ci and this does not work.

I apologize for the noise here, I should have followed the documentation because it is clearly explained here: http://www.appveyor.com/docs/deployment/github.

Thanks again!

**Comment by FeodorFitsner** [comment]
No prob, thanks for the update!
