### ISSUE TITLE
Rolling Builds only for PRs

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2066]
[Discussion](https://help.appveyor.com/discussions/problems/11832-rolling-builds-only-for-prs)

**Comment by IlyaFinkelshteyn** [comment]
Please try now, should work. Feel free to re-open the issue if something is not as expected,

**Comment by isuruf** [comment]
@IlyaFinkelshteyn, is there a separate option? Linked discussion is private.

**Comment by IlyaFinkelshteyn** [comment]
Sorry did not notice that it is private discussion. This is UI option, check attached picture.
![2018-03-05_13h07_46](https://user-images.githubusercontent.com/3248386/36999852-4af238f0-2076-11e8-9eff-84add5f83510.png)

**Comment by isuruf** [comment]
Thanks. I don't see it in my settings. I guess this feature is not rolled out to everybody

**Comment by isuruf** [comment]
Sorry. I can see it. Thanks

**Comment by IlyaFinkelshteyn** [comment]
:)
