### ISSUE TITLE
Locally Trigger Deployment Single-Instance Deployment Via Appveyor Deployment Agent

### ISSUE THREAD

**Issue by briandonahue** [appveyor/ci#2067]
Similarly to AWS CodeDeploy, it would be nice to be able, via CLI command, ideally, to have the Deployment Agent deploy the most recent deployed artifacts for an environment to a specific machine.  For example, spinning up a new instance in an group where all instances are in the "Production" environment, we could then trigger the agent to download and deploy the most recent successfully deployed versions of all artifacts and deploy on that new instance to bring it up to date with the others.  Right now this can only be done with some fairly complex powershell scripting, when it would seem easier to do via the agent itself.

**Comment by briandonahue** [comment]
Here is some background on my scenario: https://help.appveyor.com/discussions/questions/15015-any-commonstandard-way-for-pulling-latest-versions-of-apps-to-newly-launched-instances

**Comment by IlyaFinkelshteyn** [comment]
Lets look if we can create secondary deployment group called ad a computer name.

**Comment by briandonahue** [comment]
I was thinking that instead of using a temporary deployment group, couldn't the agent just request the latest successfully deployed versions for an environment/group and deploy locally only?
