### ISSUE TITLE
Mark scheduled jobs in the build history

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#2073]
In the build history overview, could you please mark builds that were scheduled to clearly make then stand out against builds that were triggered by code changes?

**Comment by IlyaFinkelshteyn** [comment]
Usually people create separate project (against the same repository) for scheduled builds. It has a lot of benefits (for example different notification settings).  Also in the bottom of General project setting in UI you can find a `Tag` setting which will make it even easier to filter out.

**Comment by sschuberth** [comment]
While I wasn't aware that AppVeyor supports multiple projects for the same repo (good to know), I'd still prefer to keep it at a single project for simplicity.

**Comment by IlyaFinkelshteyn** [comment]
Lets keep this open. However this rises other questions, for example: should we also display if project was started with API, UI, or Webhook? We are working on Audit log feature for people to get easy answers to all that questions. However this is not the same what you are asking.

**Comment by IlyaFinkelshteyn** [comment]
closing in favor of https://github.com/appveyor/ci/issues/2140
