### ISSUE TITLE
Deployment notification status is showing as failed for successful zip push deployment

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#2075]
I just setup a zip push deployment and customized the slack notification as follows
```
<{{build.buildUrl}}|Deployment of {{build.projectName}} version {{build.buildVersion}} {{build.status}}>
Commit <{{build.commitUrl}}|{{build.commitId}}> by {{build.commitAuthor}} on {{build.commitDate}}:
_{{build.commitMessage}}_
```

The deployment was successful according to the website, but the notification's `build.status` is showing as `failed`. The color of the notification is also green.

The deployment that this happened on is `/project/xt0rted/slack-notifications/deployment/1226923`

**Comment by IlyaFinkelshteyn** [comment]
@xt0rted here is what happened:

- You deploy using **Environment** provider, which happens asynchronously (difference described [here](https://www.appveyor.com/docs/deployment/#overview)).

- At the moment **deployment** finished, **build** is still running. Any build status other than `success` considered `failed` from notifications standpoint. This behavior may be arguable, but I don't think we will change it as some customers already rely on it.

- If you need **build** status, I would recommend you **build-level** notification.

- If you need **deployment** status, use `status` without `build` prefix in your **deployment-level** notification template.

- Generally I do not see too much benefits of using **Environment** deployment from within the build. **Environment** deployment was created with idea of decoupling deployment from the build, and really useful when promoting some bits to staging or production without rebuilding. For your case I believe it would be more straightforward to use **Inline** deployment and **build-level** notification.

I am closing this issue. Please let me know if you feel that I have to keep to open.

**Comment by xt0rted** [comment]
@IlyaFinkelshteyn I'm moving the deploy settings into my appveyor.yml instead of using a deployment environment. With this setup can I customize the deployment notifications? Aside from the custom message format I also send deployment notifications into a different slack channel than build notifications.

**Comment by IlyaFinkelshteyn** [comment]
If you want deployment-specific notifications and build-specific ones are not good enough, them leave configuration as is, but use `status` without `build` prefix -- this will send deployment, not build status.

**Comment by xt0rted** [comment]
When using the `async_deploy` option for `AzureAppServiceZipDeploy` does AppVeyor poll the returned url until it's completed? One of my recent deploys notified me as failed because the request timed out, but Azure still received the zip file and did a successful deployment. I'm trying to figure out if the async option will get around that issue but the docs aren't really clear on that.

**Comment by IlyaFinkelshteyn** [comment]
Search for `?isAsync=true` at [Zip push deployment documentation](https://blogs.msdn.microsoft.com/appserviceteam/2017/10/16/zip-push-deployment-for-web-apps-functions-and-webjobs/). Yes, it does not wait while deployment is finished. But downside of it is that you do not know for sure if it finished successfully. Can you please send us a link to that timed-out deployment? I wonder if we have to increase and/or expose timeout setting...

**Comment by xt0rted** [comment]
This was the deployment `/project/xt0rted/slack-notifications/deployment/1230271`

**Comment by xt0rted** [comment]
@IlyaFinkelshteyn can notifications have conditions like deployments? I'm wondering if I can setup two slack notifications but add conditions so one's for PRs and one's for anything in master?

**Comment by IlyaFinkelshteyn** [comment]
@xt0rted  sorry for delay with answer, please watch https://github.com/appveyor/ci/issues/272
