### ISSUE TITLE
Build stuck in queue

### ISSUE THREAD

**Issue by ashmaroli** [appveyor/ci#2083]
This could be just a glitch instead of a bug in the code somewhere, but the issue is that a build has been stuck in the queue for a long time now.. (about 12 hours as of opening this ticket), and has stalled all consecutive build requests.

Build: https://ci.appveyor.com/project/jekyll/jekyll/build/2942

**Comment by FeodorFitsner** [comment]
Should be fixed now. Please restart one of the builds or start a new one.
