### ISSUE TITLE
Test autodiscovery failing on netcore 2.0.

### ISSUE THREAD

**Issue by AeonLucid** [appveyor/ci#2086]
The appveyor build fails to run (/ detect) my tests.

- [My repository](https://github.com/aeonlucid/radarrcore)
- [Appveyor.yml](https://github.com/AeonLucid/RadarrCore/blob/ci/appveyor/appveyor.yml)
- [Project with tests](https://github.com/AeonLucid/RadarrCore/tree/ci/appveyor/src/Radarr.Common.Test)
  - Framework: netcoreapp2.0  
  - Related dependencies:
     - nunit: 3.9.0
     - NUnit3TestAdapter: 3.9.0
     - Microsoft.NET.Test.Sdk: 15.5.0

An example build can be found here https://ci.appveyor.com/project/AeonLucid/radarrcore/build/1.0.0.6.
What am I doing wrong?

**Comment by IlyaFinkelshteyn** [comment]
Right now tests auto-detection for .NET Core test projects works together with automatic Msbuild mode. Try commenting out [those 2 lines](https://github.com/AeonLucid/RadarrCore/blob/ci/appveyor/appveyor.yml#L15-L16) -- AppVeyor should build and run tests after that.
Also add https://www.nuget.org/packages/Appveyor.TestLogger package to your test project -- to see test results on the Tests tab.
