### ISSUE TITLE
Visual Studio 2017 image doesn't select MSBuild 15.0

### ISSUE THREAD

**Issue by ssg** [appveyor/ci#2088]
Despite the changes, it sticks with MSBuild 12.0 which fails to build C# 7,.0 code.

Repro: https://ci.appveyor.com/project/ssg/pathcleaner

**Comment by FeodorFitsner** [comment]
Solution is still VS 2013: https://github.com/ssg/PathCleaner/blob/master/PathCleaner.sln#L3

Convert solution to VS 2017.

**Comment by ssg** [comment]
thanks @FeodorFitsner, I didn't know SLN would impact the version selection. fixed it now.
