### ISSUE TITLE
choco install googlechrome gives an error in appveyor

### ISSUE THREAD

**Issue by damienbod** [appveyor/ci#2089]
https://ci.appveyor.com/project/damienbod/angular2webpackvisualstudio/build/1.0.240

How do I fix this, or is the image broken?

Greetings Damien

```
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - dotnet --version
  - dotnet restore
  - choco install googlechrome 
```

**Comment by damienbod** [comment]
Looks like it's the choco googllechrome lib

https://chocolatey.org/packages/GoogleChrome

**Comment by damienbod** [comment]
fixed with choco install googlechrome  --ignore-checksums

The choco package is broken, not appveyor, sorry.

**Comment by gep13** [comment]
> @damienbod said...
The choco package is broken,

While that might appear to be the case, it isn't quite that simple.  Google don't provide a versioned URL to download Google Chrome from, and instead, the same URL always downloads the latest version of Chrome.  As a result, there is a time delay between the software application getting released, and the Chocolatey Package "catching" up.  In this instance, looks like the page that is used to update the Chocolatey Package is returning an error, which means that the package hasn't yet been updated.
