### ISSUE TITLE
Cannot download Bitbucket repository contents: BadGateway

### ISSUE THREAD

**Issue by polarbit** [appveyor/ci#2093]
Hi, we have private bitbucket repositories; with ip restrictions. We added appveyor ip adresses in allowed ip list on bitbucket. Sometimes we get the error: "Fetching repository commit (cdd6229)...Cannot download Bitbucket repository contents: BadGateway" in builds. Generally retrying works.

What can be the problem ?

**Comment by IlyaFinkelshteyn** [comment]
Can you please clarify what exactly IP addresses you added? All from https://www.appveyor.com/docs/build-environment/#ip-addresses? Also we need links to number of builds which had this issue to check if all them related to the specific IP address.

Also before you added IP addresses to the white list, was error always the same? I am asking because `502 Bad Gateway` does not look like error related to IP restriction, but usually happens some back-end server does not respond.

**Comment by polarbit** [comment]
Hi Ilya, as you mentioned, I added ip-addresses at https://www.appveyor.com/docs/build-environment/#ip-addresses . Actually, there seems no ip related problem. 

Whether the bitbucket or appveyor had connectivity issues at the time I mentioned about the error. Because error was not continoue, we faced it time to time on that day.

Now, we haven't  faced any error since yesterdey.

**Comment by IlyaFinkelshteyn** [comment]
`Bad Gateway` is coming from the server on the "other side" when AppVeyor is trying to fetch repository as zip archive over HTTP. If you share links to specific builds, we can write to Bitbucket in hope they have some traces. Also you can remove `shallow_clone: true` (or uncheck `Fetch repository as zip archive` if you use UI), so AppVeyor will do standard Git clone -- in this case repo clone theoretically can be a little bit slower, but you for sure will not hit this specific error.

**Comment by polarbit** [comment]
Now we again face same issue.  We can not do build and deployment at the moment.

Sampe builds: 
https://ci.appveyor.com/project/biletbank/biletbankv4/builds/19635830
https://ci.appveyor.com/project/biletbank/biletbankv4/builds/19635809
https://ci.appveyor.com/project/biletbank/biletbankv4

**Comment by IlyaFinkelshteyn** [comment]
@polarbit this is probably related to [this Bitbucket issue](https://status.bitbucket.org/incidents/hstyrkqsztbh). Now it seems fixed. Workaround would be uncheck `Fetch repository as zip archive` is you use UI, or remove/comment `shallow_clone: true` is you use YAML.

**Comment by polarbit** [comment]
Thank @IlyaFinkelshteyn  . If we face again, we will disable shallow_clone.
