### ISSUE TITLE
Additional artifact is produced

### ISSUE THREAD

**Issue by craftwar** [appveyor/ci#2095]
https://ci.appveyor.com/project/craftwar_appveyor/suspend/build/29/artifacts

suspend.zip should not be uploaded

In my appveyor.yml
artifacts:
- path: suspend.7z
- path: 'suspend with docs.7z'

**Comment by IlyaFinkelshteyn** [comment]
We see the bug, should be fixed soon. As a temporary workaround you can use dashes `-` instead of spaces in your artifact file name.

**Comment by IlyaFinkelshteyn** [comment]
Should be fixed now.
