### ISSUE TITLE
Console log: No longer able to link to a specific row

### ISSUE THREAD

**Issue by johlju** [appveyor/ci#2109]
Today the log output is only showing the last 2000 rows. This is good, it faster to load large logs. But it seems I can no longer reference to a specific line in the logs.

For example this output the last 2000 rows
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.220.0

But the actual error that made this test run fail was ~100 rows in the beginning of the log. 

I thought this would get me line 100-2100, but it does not. It still gives me the last 2000 rows.
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.220.0#L100

Referencing a specific row is a good way to point out the problem in a review or issue. 

Would it be possible to be able to get the second URL working, or even better would be able to select the interval (with a max row limit of 2000)
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.220.0#L100-105

Or, is there a different way referencing lines now? Maybe I'm using the tool wrong.

**Comment by FeodorFitsner** [comment]
Hi Johan,

Thanks for your feedback!

I'm trying to figure out what would be the better solution here.

One idea is to make "Display full log" link, next to "Download full log" one. Would that solve your case? Are there any other ideas?

**Comment by johlju** [comment]
A "Display full log" would be helpful, becuase it is much easier to search for red text in the console view, indicating an error message, than opening the log and searching for "Error" which in test cases could be used in test descriptions. So a "Display full log" link would be great.
Although, when referencing a particular line it should then automatically use "display full log" to be able to go to the correct line.

I think the best option (for loading speed) is to have a link "Display full log" (on the initial view that shows 2000 rows) and the possibility to reference a range (with a max limit), for example using `#L100-105` in the URL would just show line 100-105. That would be fast for the user. And if the user want to see the full log, the user could then click "Display full log".

**Comment by FeodorFitsner** [comment]
Yeah, we will add “Full log” link shortly.

**Comment by johlju** [comment]
@FeodorFitsner Thanks so much! 😄 🙇

**Comment by FeodorFitsner** [comment]
A link to display full log has been added.

**Comment by johlju** [comment]
@FeodorFitsner Works perfectly!! 👍  Thank you! 😄
