### ISSUE TITLE
Github release deployment error: No artifacts were published.

### ISSUE THREAD

**Issue by parkouss** [appveyor/ci#211]
Hello,

I am not able to send an artifact to github release when I push a tag. Everything goes well, except that I got a warning:
No artifacts were published. Make sure you have specified correct artifacts filter.

And nothing is submitted. I am trying to send a single file, see https://github.com/parkouss/mozregression/blob/gui-releases/appveyor.yml.

I am sure the file exists since I added a dir command to list the directory content, see the end of the output of https://ci.appveyor.com/project/parkouss/mozregression-fqsi0/build/1.0.38.

I also tried to use forward slashes in the artifact name, when I found http://help.appveyor.com/discussions/problems/1559-in-theory-i-should-have-artifacts-but-it-says-there-is-none but still no luck.

**Comment by FeodorFitsner** [comment]
Deployment is always done from artifacts. You [package artifacts](http://www.appveyor.com/docs/packaging-artifacts) and then deploy from there. You should add to `appveyor.yml` something like this:

```
artifacts:
  - path: gui\dist\mozregression-gui.exe
```

**Comment by parkouss** [comment]
Awesome, thanks again for you really quick reaction. :)

I am not sure, but I think I tried that. Anyway I added the section, and to be sure moved the commands generating the file from the before_deploy section to the test_script section and all is working well now!

Thanks!

**Comment by joeferraro** [comment]
thanks @parkouss, for me this was the important factor:

> moved the commands generating the file from the before_deploy section to the test_script section

**Comment by mzvast** [comment]
This works for me. It makes me crazy, so simple, but few example cover this.
//appveyor.yaml
```
artifacts:
- path: dist/installers/*.exe
  name: myartifact
deploy:
  artifacts: myartifact
  ...
```
