### ISSUE TITLE
Console downloaded full log does not contain row numbers

### ISSUE THREAD

**Issue by johlju** [appveyor/ci#2110]
The Console log view only shows the last 2000 rows, but gives a link to download the log. The downloaded log does not contain row numbers. In large logs is hard to point out a specific row for others to look at. A row number is easier for people to find, and there will be no mistake which row is referenced.

Is it possible to add a row count (the same number sequence) that is shown in the console?

**Comment by FeodorFitsner** [comment]
Thought about that as well, but then realized that would be duplication of functionality that present in any text editor out there:

![image](https://user-images.githubusercontent.com/5041459/36984608-23e8df06-204a-11e8-9546-67cd6bee1783.png)
