### ISSUE TITLE
Support for .net core 2.1 preview

### ISSUE THREAD

**Issue by barld** [appveyor/ci#2120]
Have you planed to support the new .net core sdk soon on the preview image?

https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1

**Comment by kasper3** [comment]
@FeodorFitsner, can you please tell how to use it?

**Comment by kasper3** [comment]
`image: Visual Studio 2017 Preview` then `dotnet --info` gives me:

```cmd
.NET Command Line Tools (2.1.101)
Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0
```

whereas I expect:

```cmd
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview3-008618
 Commit:    c2713b41c3
```

**Comment by FeodorFitsner** [comment]
We are currently updating the image with `2.1.300-preview2-008530` (Preview2 is the latest preview release).

**Comment by kasper3** [comment]
@FeodorFitsner, could you please try the following:

```powershell
invoke-webrequest -Out dotnet21.zip https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip
Expand-Archive dotnet21.zip -Force -DestinationPath c:\dotnet21\ > $null

c:\dotnet21\dotnet --info
```

I am getting ` Version:   2.1.300-preview3-008618` atm

**Comment by FeodorFitsner** [comment]
OK, we've just updated `Visual Studio 2017 Preview` image with the latest Visual Studio 2017 version 15.7 Preview 3 and dotnet version `2.1.300-preview2-008530`.

**Comment by kasper3** [comment]
thanks, that was quick and it worked!

**Comment by hack2root** [comment]
@FeodorFitsner Actuall corrent version is not 2.1.300-preview2-008530, this is a typo error,  it's actually a 

**2.1.300-preview2-008533**

**Comment by kasper3** [comment]
these days the latest is 2.1.300-rc1-008673

**Comment by hack2root** [comment]
@kasper3 ok
