### ISSUE TITLE
VS2017 Image: Find-Package Broken due to v3 url

### ISSUE THREAD

**Issue by JustinGrote** [appveyor/ci#2123]
The nuget.org provider registered for the powershell find-package and install-package commands doesn't work. Below images are from an RDP session into the build host:

![image](https://user-images.githubusercontent.com/15258962/37118687-ecf0116a-2209-11e8-86f9-7ffbb2c22b5a.png)

Even if you remove and try to re-register it with same v3 url it fails:
![image](https://user-images.githubusercontent.com/15258962/37118759-2479efb6-220a-11e8-85d8-43f52c09e193.png)

Removing it and registering with the v2 URL works fine, this is my current workaround. Recommend to fix URL back to old v2 URL, or update PackageManagement module to one that uses v3 APIs

![image](https://user-images.githubusercontent.com/15258962/37118829-59420940-220a-11e8-9a7f-0f8701e37bc5.png)
![image](https://user-images.githubusercontent.com/15258962/37118838-615df90e-220a-11e8-99be-9df422c0c7d8.png)

![image](https://user-images.githubusercontent.com/15258962/37118877-7ef97bf0-220a-11e8-8ee7-033c37342f4e.png)

**Comment by FeodorFitsner** [comment]
@onovotny Oren, could you please suggest a proper way to fix that?

**Comment by JustinGrote** [comment]
PackageManagement still doesn't support anything other than a v2 repository it seems, so not sure about this since they share the same repository information.

Probably not worth changing the default value, but if someone else comes across this, here's two ways around it:

Quick and Dirty:
`$PSDefaultParameterValues.add("Install-Package:Source",'http://www.nuget.org/api/v2')`

Proper but may break other applications looking for nugetv3 api:
`
Unregister-PackageSource nuget.org
Register-PackageSource nuget.org -Location 'http://www.nuget.org/api/v2' -provider 'NuGet' -Trusted:$true
`

Best compatability:
`Register-PackageSource nuget.org-v2 -Location 'http://www.nuget.org/api/v2' -provider 'NuGet' -Trusted:$true`
`Find-Package -source nuget.org-v2 <mypackage>`

**Comment by JustinGrote** [comment]
Closing this issue since I can't really propose a fix and a workaround is available, at least it's here in case someone comes googling along :)
