### ISSUE TITLE
SSH access to Linux build worker

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2124]
[Discussion](https://help.appveyor.com/discussions/questions/18251-ssh-access-to-linux-build-worker)

**Comment by ruzickap** [comment]
Description: 
Access Appveyor Linux build worker (https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/) via `SSH` like it's for Windows with `RDP` (https://www.appveyor.com/docs/how-to/rdp-to-build-worker/).

**Comment by FeodorFitsner** [comment]
It's done and documented here: https://www.appveyor.com/docs/how-to/ssh-to-build-worker/

**Comment by SergeGautherie** [comment]
Thanks!

> https://www.appveyor.com/docs/how-to/ssh-to-build-worker/

Could you double-check this page?
For example:
{{
APPVEYOR_SSH_BLOCK - if set to true SSH connection details will be displayed and the build will continue; otherwise SSH details will be displayed and the build will block until ~/build.lock is deleted. This variable is optional with with default value false.
}}
- "if set to true": should be "false"!
- "with with" typo.

**Comment by FeodorFitsner** [comment]
Thanks for the catch!

**Comment by SergeGautherie** [comment]
* "rsa-key-20180328" point remains.

Some more:

* Add an example of how to use `APPVEYOR_SSH_BLOCK` within the code, as in the Windows RDP page.
Like "init/false" + "finish/true".

* When I delete `~/build.lock`, `SSH session has been finished.` is added to the log.
The two are unrelated, that message should instead be added when the network connection is actually closed, either by the client or the server.
And/or did you meant to log "lock removed" here?

**Comment by SergeGautherie** [comment]
3 first points fixed.
2 additional points remain.

**Comment by IlyaFinkelshteyn** [comment]
@roozbehid-ic [this](https://www.appveyor.com/docs/how-to/ssh-to-build-worker/) is what should be used with Linux. To select what commend to use on what OS/image, please follow [this](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side) doc.

**Comment by SergeGautherie** [comment]
@roozbehid-ic, your comment was already filed as #2167!

**Comment by IlyaFinkelshteyn** [comment]
@roozbehid-ic sorry I misunderstood your request. Right we will condition with `$isLinux` inside `enable-rdp.ps1` file.

**Comment by SergeGautherie** [comment]
> 2 additional points remain.

My 2 PRs fixed them.

**Comment by Zingam** [comment]
It would be nice if you add the following information about configuring ssh/keys as described here:
https://help.github.com/en/articles/error-permission-denied-publickey
