### ISSUE TITLE
c# 7.0 Inline Out Variables 

### ISSUE THREAD

**Issue by lukehutton** [appveyor/ci#2137]
Any reason why they cannot compile?

Getting error "CS1003: Syntax error, ','"  for code such as:

`p.GetCoordinates(out int x, out int y);`

Image is set right in appveyor.yml:

image: Visual Studio 2017

**Comment by IlyaFinkelshteyn** [comment]
please share a link to the problem build

**Comment by lukehutton** [comment]
Sure, https://ci.appveyor.com/project/Xeraflop_Technologies/duber-inventory/build/1.0.490

**Comment by IlyaFinkelshteyn** [comment]
I see that it still uses `Visual Studio 2015` image. Don't you also have `o:` setting by any chance in your YAML? It takes over `image`...
If this does not help, please share your YAML (feel free to delete all secrets).

**Comment by lukehutton** [comment]
oh yes you are right, I see OS settings

`# version format
version: 1.0.{build}

# use VS2017 to enable C#7
image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - master
    - qa

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012`

Strange, it did seem to build fine a few builds ago, I will update os to 2016, thanks!

**Comment by IlyaFinkelshteyn** [comment]
No, just remove it, it is duplication to `image` setting, we have it historically.

**Comment by lukehutton** [comment]
ok thanks nuked deprecated tag
