### ISSUE TITLE
Event log

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2140]
Present build meta-information to customers be able to answer questions such as:
- why my commit did not fired the build? 
- where my configuration came from -- YAML or UI?
- who started deployment over API?

and so on.

**Comment by janisozaur** [comment]
This got closed, but without any information provided here. Based on the milestones, it would appear to be done, can you please leave some links to documentation or comment how to use this feature?

**Comment by FeodorFitsner** [comment]
Docs are coming, for sure. The goal for this milestone was to deliver Event Log infrastructure with only basic entities/events covered. Over the time more and more events will be logged there.

For example, you can see User events at the bottom of [Profile](https://ci.appveyor.com/profile) page and Account events at the bottom of [Account](https://ci.appveyor.com/profile) page.
