### ISSUE TITLE
Environment variables are not expanded in "clone_folder" on Linux

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2148]
"clone_folder: $HOME/reactos-cov" causes "Build folder path must be absolute.".

**Comment by SergeGautherie** [comment]
> \# "Build folder path must be absolute."
clone_folder: ~/[...]
\# "Build folder path must be absolute."
clone_folder: $HOME/[...]
\# Works fine.
clone_folder: /home/appveyor/[...]

**Comment by SergeGautherie** [comment]
Verified fixed. (Both `$HOME` and `~`.)
