### ISSUE TITLE
Resetting next version to 1 will paralyze the system

### ISSUE THREAD

**Issue by shytikov** [appveyor/ci#215]
I don't know how, but when I reset next build number in web interface to `1` and build process stuck. `AppVeyor` did not increased next build number, and in addition I had en error in next commit, so I came to situation I'm describing in #214 — I had series of builds labeled with the same number `1` and they all was failing, so I could not navigate to log to investigate what is wrong with them. Until I have manually increased the next build version to 2. This made `AppVeyor` unstuck.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
