### ISSUE TITLE
qmake not found

### ISSUE THREAD

**Issue by dagheyman** [appveyor/ci#2150]
Are you having troubles with the Qt installations? We are suddenly getting builds failing with the error message `'qmake' is not recognized as an internal or external command`, without making any changes to our appveyor.yml files.

Example: https://ci.appveyor.com/project/Yubico53275/yubikey-manager-qt/build/1.0.326/job/dw13e2664jfwawlg

**Comment by FeodorFitsner** [comment]
Qt 5.10.0 has been replaced with 5.10.1: https://github.com/appveyor/ci/issues/2149#issuecomment-372545543

**Comment by gillesdegottex** [comment]
There were '_opengl' environments for Qt-OpenGL (e.g. msvc2013_64_opengl in C:\Qt\5.4\).
Since the move to Qt5.10, these do not appear anymore.
Is it something forgotten or should we link with an additional lib now?
