### ISSUE TITLE
How to re-set the github repo hook?

### ISSUE THREAD

**Issue by LebedevRI** [appveyor/ci#2156]
I manually deleted the appveyor webhook in the repo settings (because #2121), and now i can not understand just how to get it back. 
And i'm not seeing anything in docs, or can't find anything in google.
This is kinda unintuitive.

**Comment by IlyaFinkelshteyn** [comment]
https://help.appveyor.com/discussions/questions/2272-github-webhook-deleted-how-to-recreate

**Comment by LebedevRI** [comment]
Thanks.
Hmm, tried that already, but without the content type = json.
But that info really should be in the more logical place, like docs.
Not sure if it is working or not, the github's test did not trigger the new build.
(Also, any reason why this isn't a proper service, in github repo "Integrations & services", like travis/obs/... ?)
