### ISSUE TITLE
Parallel builds seems to be not working

### ISSUE THREAD

**Issue by shytikov** [appveyor/ci#216]
It should be something deep inside...

In my definitions file I have: 
```
build:
  parallel: true
```
In build log I clearly see `/m` switch added to the `msbuild` command line:
```
msbuild "Cinteros.XrmToolBox.Plugins.sln" /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
```
However, later in the log I see strange: 
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/26/2015
Project "C:\projects\xrmtoolbox-plugins\Cinteros.XrmToolBox.Plugins.sln" on node 1 (default targets).
```

I'm not sure is it bug of `msbiuld` or `AppVeyor`, but it seems to be `parallelization` is not working...

**Comment by FeodorFitsner** [comment]
If you are building on Free plan there are "Small" instances with 1 virtual core, so `/m` switch doesn't make any difference.

**Comment by shytikov** [comment]
:+1:
