### ISSUE TITLE
Add additional commit message information to the build notification payload

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#2165]
The build notification payload contains only the first line of the commit message. It was mentioned to me that this isn't changing any time soon since customers expect that behavior.

There's two environment variables for commit message which are `APPVEYOR_REPO_COMMIT_MESSAGE` and `APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED`. Could the build notification payload be expanded to include a `commitMessageExtended` as well? Or maybe a `commitMessageFull`?

The issue I'm facing is my deployment messages are showing
```
Merge pull request ### from xt0rted/branch-name
```
instead of
```
Merge pull request ### from xt0rted/branch-name
Added some awesome new feature and fixed all the bugs
```

The notification is much more useful if the full commit message, which in this case is the PR title, is also shown.

**Comment by IlyaFinkelshteyn** [comment]
@xt0rted do you think this https://github.com/appveyor/ci/issues/2079 can help you when fixed?

**Comment by xt0rted** [comment]
After asking about this I setup a webhook notification for some of my deployments and logged the payloads. After looking through them I noticed there was already a `commitMessageExtended` property in it. I'm not sure if this was added after I asked about it or if it's just been missing from the documentation. I was able to use it in the build notification template so that resolves my issue.

**Comment by IlyaFinkelshteyn** [comment]
My bad, it is been around for a while. Sorry for misleading. Closing as this seems solved.
