### ISSUE TITLE
Visual Studio 2015 image has Boost 1.65.1 built with Platform Toolset 141

### ISSUE THREAD

**Issue by nightlark** [appveyor/ci#2169]
CMake is having trouble detecting the Boost 1.65.1 libraries on the latest Visual Studio 2015 image. It looks like it is because the Boost 1.65.1 libraries were built with Platform Toolset 141 instead of 140, since the libraries for Boost 1.63.0 are detected and work without any issues.

**Comment by FeodorFitsner** [comment]
Will fix that shortly, thanks for pointing out.
