### ISSUE TITLE
newer msbuild (15.6.82.30579) breaking users previously successful build

### ISSUE THREAD

**Issue by OwenMcDonnell** [appveyor/ci#2171]
No repro provided by user (VSTS repository)

**Comment by edsnider** [comment]
Is there a fix or any info how to get around the issue with 15.6.82.30579 breaking previously successful builds?

**Comment by OwenMcDonnell** [comment]
The repo that this issue was created in response to was fixed by a visual studio update on the build agent image. 
Could you post your issue in the [appveyor forums](https://help.appveyor.com/discussions/problems), or send an email to support (team@appveyor.com). When you do, links to repo, logs, and/or configuration yaml are all helpful as well.

**Comment by edsnider** [comment]
Will do, thank you.

**Comment by edsnider** [comment]
https://help.appveyor.com/discussions/problems/13857-msbuild-version-1568230579-is-breaking-previously-working-builds.  Appreciate any help or guidance. Thanks!
