### ISSUE TITLE
Option to use dotnet cli instead of msbuild

### ISSUE THREAD

**Issue by shibayan** [appveyor/ci#2173]
MSBuild is used for Windows, but dotnet cli is used for Ubuntu, so behavior has changed on the platform and it is awkward to handle.
For .NET Core, it is convenient to use dotnet cli for Windows and Ubuntu.

![image](https://user-images.githubusercontent.com/1356444/37462733-48b673f8-2896-11e8-97da-e4426ea29f61.png)

**Comment by FeodorFitsner** [comment]
Good catch!

Our proposal would be switching to `dotnet build` on Windows if only *ALL* projects within the solution are .NET Core projects. What do you think?

**Comment by shibayan** [comment]
Great! I think that it is simple and better than switching by option.

**Comment by IlyaFinkelshteyn** [comment]
We will postpone this a little bit, until https://github.com/appveyor/ci/issues/2212 done. Because before that build logger will not work properly.
