### ISSUE TITLE
install cmake in ubuntu image

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#2174]

**Comment by scivision** [comment]
For reference, Travis-CI currently has CMake 3.9 in their Ubuntu 14.04 images.
I need at least CMake 3.7.

May as well put the latest CMake release in the AppVeyor images.

**Comment by Wasapl** [comment]
```
$ cmake --version
cmake version 3.11.0-rc3
```

**Comment by SergeGautherie** [comment]
Is it expected to be installed in `$HOME`?

```
appveyor@appveyor-vm:~$ pwd
/home/appveyor

appveyor@appveyor-vm:~$ ll
drwxr-xr-x   6 appveyor appveyor  4096 May 15 05:39 cmake-3.11.0-rc3-Linux-x86_64/
```

**Comment by Wasapl** [comment]
@SergeGautherie Cmake installed by default:
```
$ command -v cmake
/usr/bin/cmake
```
What you see is a sources left by installation process.

On contrary Python virtual environments was installed into $HOME directory on purpose. This way takes less switches to root account both for image installation process and for users.

**Comment by SergeGautherie** [comment]
> cmake [...] will be removed on next image release.

Confirmed. Thanks.

> fewer switches to root account [...] for users

There are also the `.localpython*/`. And some more directories, it seems.
I am not familiar with these softwares, yet I wonder what actual path has to do with being root or not.
Couldn't they live in `/usr/bin` for example, or at least all under `~/bin`?

**Comment by Wasapl** [comment]
Those are python flavors which one can use in their build with line like `stack: python 3.4` in appveyor.yml.
It's better to keep them in user's directory. This way one should not use root privileges to install packages in those pythons.
