### ISSUE TITLE
CMake 3.11.0

### ISSUE THREAD

**Issue by argakiig** [appveyor/ci#2180]
Boost 1.66 isnt properly detected with cmake 3.10.1 and earlier.
Can we add support for atleast cmake 3.10.2 which fixed the issue.

**Comment by vadz** [comment]
This update broke [SOCI project](https://ci.appveyor.com/project/SOCI/soci) builds, apparently there is a bug/regression in [CMake itself](https://gitlab.kitware.com/cmake/cmake/issues/17874).

**Comment by mloskot** [comment]
@argakiig FYI, CMake is often one step behind Boost.

You can work around this with [simple hack we use in Boost.GIL](https://github.com/boostorg/gil/blob/develop/CMakeLists.txt#L31-L38):

```
# Latest FindBoost.cmake has likely been updated to detect Boost version not yet released
if (NOT EXISTS "${CMAKE_BINARY_DIR}/cmake/FindBoost.cmake")
  message(STATUS "Downloading FindBoost.cmake from https://gitlab.kitware.com/cmake/ master branch")
  file(DOWNLOAD
    "https://gitlab.kitware.com/cmake/cmake/raw/master/Modules/FindBoost.cmake"
    "${CMAKE_BINARY_DIR}/cmake/FindBoost.cmake")
endif()
list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_BINARY_DIR}/cmake)

```

**Comment by argakiig** [comment]
Yup, had a similar workaround covered
