### ISSUE TITLE
Permalink to build artifacts not deployed from pull requests?

### ISSUE THREAD

**Issue by x1nixmzeng** [appveyor/ci#2184]
I am looking to find a permalink to the last merged change into the master branch. Here is the URL:

`https://ci.appveyor.com/api/projects/<owner>/<project>/artifacts/<artifact>?branch=master&job=Configuration:%20Release` 

However, pull requests are allowed to build and publish artifacts - which is treated as the "latest build". So the last job is potentially a pull-request!

Is there a parameter we can provide (similar to the tag method from #1007) to the latest link not from a pull request? On the AppVeyor website, the project history marks pull request builds differently.

**Comment by IlyaFinkelshteyn** [comment]
I believe that it is already implemented:
https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact. 

Sample:
```
https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip?pr=false
```
