### ISSUE TITLE
Qt 5.6.3

### ISSUE THREAD

**Issue by past-due** [appveyor/ci#2185]
When compiling and targeting XP (with the `v141_xp` toolchain) on the VS 2017 image, we also need the latest (LTS) version of Qt 5.x that officially supports Windows XP - which is: **Qt 5.6**.

Since [Qt for VS 2015 is fully ABI compatible with VS 2017](https://forum.qt.io/topic/80583/prebuild-qt-32-bit-versions-for-visual-studio-2017), what we need installed (with the same options as the VS 2015 image, like QScript) is:
- [qt-opensource-windows-x86-msvc2015-5.6.3.exe](https://download.qt.io/archive/qt/5.6/5.6.3/qt-opensource-windows-x86-msvc2015-5.6.3.exe)

Since VS 2017 still provides a supported XP build toolchain, it would be ideal to have the last Qt version that supports Windows XP available.

Adding symlinks for Qt:

```
rd C:\Qt\5.6
mklink /J C:\Qt\5.6 C:\qt\5.6.3
```

**Comment by past-due** [comment]
Just a gentle bump on this. We'd love to be able to build everything on the VS 2017 images, but this is blocking our ability to make XP-compatible 32-bit builds.

**Comment by FeodorFitsner** [comment]
So, only `msvc2015` (32-bit) required?

**Comment by past-due** [comment]
For our purposes, yes.

Any projects targeting Windows XP 64-bit would presumably need [qt-opensource-windows-x86-msvc2015_64-5.6.3.exe](https://download.qt.io/archive/qt/5.6/5.6.3/qt-opensource-windows-x86-msvc2015_64-5.6.3.exe]) installed too... but I'm not aware of many projects that target 64-bit Windows XP.
