### ISSUE TITLE
Enable c# 7.1

### ISSUE THREAD

**Issue by lemieuxs** [appveyor/ci#2188]
I would like to know when will the c# 7.1 new features be available or how to enable them if it's already deployed.

I am building an app with an async Main and it's throwing an error because it's available only since c# 7.1.

Many thanks.

**Comment by IlyaFinkelshteyn** [comment]
Are you using `Visual Studio 2017` [build worker image](https://www.appveyor.com/docs/build-environment/#build-worker-images)?

**Comment by lemieuxs** [comment]
yes

**Comment by lemieuxs** [comment]
Never mind I found out that there was a build condition on the target and platforme in my csproj for the langversion property

Thanks
