### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#219]
Discussions:
http://help.appveyor.com/discussions/suggestions/632-better-integrate-with-gitlab
https://twitter.com/david_obrien/status/606239645962280960

API: https://github.com/gitlabhq/gitlabhq/tree/master/doc/api

**Comment by equalsraf** [comment]
Any news on this front? I have a couple of projects in gitlab that could use Appveyor.

**Comment by sils1297** [comment]
:+1: we'd love to have that too.

**Comment by kkm000** [comment]
Ahem?

**Comment by SneakyMax** [comment]
:+1:

**Comment by FeodorFitsner** [comment]
AppVeyor has got built-in support for GitLab with OAuth, appveyor.yml, webhooks and commit statuses

**Comment by mattmckinstry** [comment]
Could you point me to the documentation for the GitLab support?  Thanks

**Comment by FeodorFitsner** [comment]
Basically, the flow is the same as for other repositories - just add a new project, select "GitLab" then your repo. Webhook will be added automatically. Configure project on UI or add `appveyor.yml` with config to the root of your repo.

**Comment by c33s** [comment]
you should add this info to your docs (https://www.appveyor.com/docs)
landed here because of looking for gitlab support. it is possible that you scare some people away, which are looking for gitlab support (or maybe other git hosting provider your may also support)

> Step 2 - Add your projectAnchor link for: step 2 add your project
> 
> Authorize GitHub or BitBucket to list your repositories. For open-source project developers who are using the same GitHub account for both personal and private company repositories AppVeyor offers a choice between two scopes: public repositories exclusively or public and private.

**Comment by jangorecki** [comment]
Is there any way to use appveyor windows machines as GitLab CI runners? so the windows builds could be part of the GitLab CI pipeline instead of just separate loose build? If there is separate issue for that please link.

**Comment by FeodorFitsner** [comment]
I don't think it's easy as AppVeyor VMs are transient.

**Comment by darrencl** [comment]
Hi, is there any update on this?

I am hosting private repo in GitLab but it seems that AppVeyor only allows to be used in GitLab public repo. GitLab CI seems to offer beta version of Windows shared runner though, but it doesn't include python pre-installed and can't use docker image, so setting up the environment can be a hassle. Is there any alternative to this?

Thanks!

**Comment by jangorecki** [comment]
GitLab windows shared runners feature is in beta. Be sure to provide feedback to them about the software you would like to have pre-installed. My understanding is that once it will go out of beta they will provide different VM configurations. They just need to first know what are the most common configurations.
