### ISSUE TITLE
Integration tests failing on writing to text files

### ISSUE THREAD

**Issue by Lauchi** [appveyor/ci#2190]
I have some Integration Tests running on AppVeyor, that write generated classes to .cs files and assert if the content is the same. Locally (on windows and osx) the tests run, they also run on travis CI and circleCi. But on AppVeyor the tests run and the file gets written, but the content seams to be off, as the tests fail. But if i read the log correctly, the content is indeed the same. Are the services running on some machine that might mess with the decoding of the file? I tried replacing lineendings, change decoding, removing tabs, only use "Contains" instead of equal, but nothing seems to work. Am i doing something wrong here or is this a bug/known issue?

This is the build right now: https://ci.appveyor.com/project/Lauchi/genericwebservicebuilder

The 3 tests running are the tests that only check if the files are namend correctly and are in the correct location

**Comment by IlyaFinkelshteyn** [comment]
Please check [this forum post](https://help.appveyor.com/discussions/problems/948-tests-fail-on-appveyor-but-not-locally#comment_35102707), seems similar.

Side note: use https://www.nuget.org/packages/Appveyor.TestLogger to get nicer results in UI and build history. Also I believe you can skip build script and AppVeyor will detect and run your tests.

**Comment by Lauchi** [comment]
Hi,

thanks for the relpy! I tried replacing the newlines, deleting them, (all \r\n, \n, and \r) but the assertion still fails. I figured it would be something like that, but it soemhow isnt. I somehow thought that this is because of unix/window lineendings, but i run that on 3 other cis, my mac and my windows pc without any problem. And i think i read somewhere, that you are using windows for the build? Should that not be \r\n all the way? 

I installed the TestLogger but can not see any difference in the result on the ui (at least not something that poins me in the direction, that there is a newline wrong).

**Comment by Lauchi** [comment]
My bad, after a few build the Testlogger started writing different lines and there was indeed a \n expected, but my filewriter writes a \r\n somehow. Will have to figure out why it does that in that context and not on my local machine. 

Thanks for the tip!
