### ISSUE TITLE
Caching layers of common docker images?

### ISSUE THREAD

**Issue by roozbehid-ic** [appveyor/ci#2191]
Can you guys update your images with some layers of docker images cached?

For example if you download few of those images, all other images sharing those layers will not need to download them and it will boost speed on building and I assume save you money too!

We use aspnetcore, aspnetcore-build mostly but I assume downloading some of linux flavors (ubuntu,buildpack-deps:jessie-scm,debian:jessie,...) would also save lots of time too.

**Comment by FeodorFitsner** [comment]
You mean `Ubuntu` image, correct?

**Comment by roozbehid-ic** [comment]
Actually I thought Windows images support Linux containers which later I figured it is not the case. 
But still to my point using apsnet images, it took long time to build (which I assume uses windows server or maybe nano)

**Comment by FeodorFitsner** [comment]
Created more specialized issue: https://github.com/appveyor/ci/issues/2206
