### ISSUE TITLE
Java 10

### ISSUE THREAD

**Issue by rleigh-codelibre** [appveyor/ci#2195]
Similar to https://github.com/appveyor/ci/issues/1186, would it be possible to add Java 10 to your images?  The final release is out now.

Thanks,
Roger

**Comment by gep13** [comment]
@rleigh-codelibre in the interim, a new Chocolatey Package was pushed yesterday that would allow you to get it installed:

https://chocolatey.org/packages/jdk10

As the first step in your build you should be able to do:

`choco install jdk10`

**Comment by Xerus2000** [comment]
I second this request

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by FeodorFitsner** [comment]
Installation path:

* JDK: `C:\Program Files\Java\jdk10`
* JRE: `C:\Program Files\Java\jre10`

**Comment by Andrei-Pozolotin** [comment]
works, thank you
