### ISSUE TITLE
CSC : error CS0006 on new 'Visual Studio 2017' image

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2200]
This should not block image update as user has a workaround on the current image, but we need to check if next update will fix it.

[discussion](https://help.appveyor.com/discussions/problems/13099-csc-error-cs0006-metadata-file-could-not-be-found-works-locally)

**Comment by martijn00** [comment]
I think this is fixed in Visual studio 15.6.4: https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.6.4

**Comment by FeodorFitsner** [comment]
@martijn00 I'm testing your project on the image with latest 15.6.4 and it doesn't look like it's being fixed: https://ci.appveyor.com/project/appveyor-tests/oauth2plugin/build/1.0.5

Do you have any ideas what may be wrong?

**Comment by martijn00** [comment]
@FeodorFitsner My project is https://github.com/MvvmCross/MvvmCross on the develop branch.

This is the issue that is fixed: https://developercommunity.visualstudio.com/content/problem/218674/assets-file-cxxxxxxobjprojectassetsjson-doesnt-hav.html

**Comment by FeodorFitsner** [comment]
Related issue: https://github.com/appveyor/ci/issues/2219

**Comment by FeodorFitsner** [comment]
A new image with VS 2017 15.6.4 has been just deployed. Let me know if that fixes your issue.
