### ISSUE TITLE
.NET Core SDK 2.1.103, 2.1.104, 2.1.105

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2233]
SDK download pages:
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.105
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.104
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.103

Added runtimes:

* 2.0.7

**Comment by xt0rted** [comment]
The [docs](https://www.appveyor.com/docs/build-environment/#net-framework) have this version listed now but there isn't mention of 2.1.102 or 2.1.104, are these available now as well?

**Comment by IlyaFinkelshteyn** [comment]
No, neither of them were installed. `2.1.103` is the one automatically installed with the latest Visual Studio 2017 update. Next update will bring us another latest one, which as I understand is `2.1.105` right now).
Side note: to double check and have a good illustration, I followed [this](https://www.hanselman.com/blog/dotnetSdkListAndDotnetSdkLatest.aspx) advise and forked [this](https://github.com/faniereynders/dotnet-sdk-helpers) and created [this](https://ci.appveyor.com/project/IlyaFinkelshteyn/dotnet-sdk-helpers/build/job/f9ylraw0hfd4a45c) build. You can do the same to always have a full answer.

**Comment by FeodorFitsner** [comment]
Download pages:
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.105
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.104
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.103
