### ISSUE TITLE
Cannot open include file: 'afxwin.h': No such file or directory

### ISSUE THREAD

**Issue by dlemstra** [appveyor/ci#2238]
In the builds from the last couple days I suddenly get the following error message:

> c:\imagemagick\visualmagick\configure\stdafx.h(17): fatal error C1083: Cannot open include file: 'afxwin.h': No such file or directory [C:\ImageMagick\VisualMagick\configure\configure.vcxproj]

It looks like this has happened after the April 2 update of the images. I then tried the VS 2015 build and the previous VS 2013 build but they both failed:

- Visual Studio 2013: https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2572
- Visual Studio 2015: https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2573
- Previous Visual Studio 2013: https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2574

And the logs also shows the following message (no idea if that is related):
>The license for Visual Studio has expired.

**Comment by FeodorFitsner** [comment]
I see you're used to build on `Visual Studio 2013` image. Have to say we've been very conservative updating `Visual Studio 2013` image - nothing substantial have been changed there for a long time. And the fact it's not working on `Previous Visual Studio 2013` gives more signs that it might be some code change.

Can you try re-building (from UI) last successful build, for example this one: https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2554

**Comment by dlemstra** [comment]
Running the build on an older commit won't be a proper check because we always clone the latest version of a repository when we run the build. 

I just pushed a change to do a checkout at a specific date and this produces the exact same result: https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2579/job/a3isn4p1cnn6reyf. The code that is being build is a checkout from this commit: https://github.com/ImageMagick/VisualMagick/commit/f2e6296 and that commit was done 14 days ago.

**Comment by FeodorFitsner** [comment]
This might be related to https://github.com/appveyor/ci/issues/2240

Working on the update will let you know when it's done.

**Comment by dlemstra** [comment]
Thanks for the quick response 👍. The 2015 build that also failed did not report a license expired message so I wonder if that is the cause of this issue for the 2015 image.

**Comment by FeodorFitsner** [comment]
Well, looking at your build history there was a successful build on April 3rd (https://ci.appveyor.com/project/dlemstra/imagemagick-windows/build/ImageMagick-master.2562) which was *after* the very last image update on April 2nd (https://www.appveyor.com/updates/2018/04/02/). Additionally, the fact it doesn't work on either `Previous Visual Studio 2013` and `Visual Studio 2013` gives another hint that might be some changes in the code or external dependencies.

**Comment by FeodorFitsner** [comment]
Thanks for the update. Anyway, VS 2013 license on `Visual Studio 2013` image has been updated.
