### ISSUE TITLE
Environment variables in deployment provider settings key

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2241]
For deployment agent instead of having a load of settings like this:

ABC.deploy_website | true
-- | --
ABC.deploy_website | true
ABC.site_name | abc-domain.com
XYZ.deploy_website | true
XYZ.site_name | xyz-domain.com
DEF.deploy_website | true
DEF.site_name | def-domain.com

We would use variables in the keys and have:

$(name).deploy_website | $(deploy_site)
-- | --
$(name).site_name | $(artifact_name)

Making the settings much easier to manage plus configurable through the yml file (making multiple environments easier to deploy to).

**Comment by polarbit** [comment]
Very good idea. 👍

**Comment by FeodorFitsner** [comment]
The feature has been deployed.

**Comment by timgaunt** [comment]
Excellent work @FeodorFitsner thanks! Are we able to _just use it_ inline with what I proposed or is the implementation slightly different?
