### ISSUE TITLE
Node.js 8.x is default installation now (because of Node.js 4 EOL)

### ISSUE THREAD

**Issue by StefanScherer** [appveyor/ci#2246]
I see in our builds `Uninstalling node 4.8.7 (x86)` when we switch to our Node.js version.
Just a heads-up: Node.js 4 is EOL end of April 2018.

https://github.com/nodejs/Release#nodejs-release-working-group

Switching to a newer LTS version would be useful.
Node.js 8.11.1 is the current LTS version, or 6.14.1 which is Active LTS till end of April, then Maintenance LTS until April 2019.

As this might be a breaking change for some customers those ones wanting to get back to 4.x should add the following into their `appveyor.yml`:

    init:
    - ps: Install-Product node 4

**Comment by FeodorFitsner** [comment]
Thanks for the heads up! We'll switch default version of Node to 8.x during the next image update.

**Comment by FeodorFitsner** [comment]
As this might be a breaking change for some customers those ones wanting to get back to 4.x should add the following into their `appveyor.yml`:

    init:
    - ps: Install-Product node 4
