### ISSUE TITLE
Setting Environment Variables Inside Scripts Does Not Work

### ISSUE THREAD

**Issue by swaldhoer** [appveyor/ci#2252]
I have a `ps1`-script which does basically only create directories, copy some files and set some environment variables. This script works perfectly when running locally, but on AppVeyor it fails.

The failing part is:
```
Write-Host "Setting environment variables"
[System.Environment]::SetEnvironmentVariable("LUA_DIR", $INSTALL_BIN, `
    [System.EnvironmentVariableTarget]::User)
[System.Environment]::SetEnvironmentVariable("LUA_CPATH", `
    "?.dll;%LUA_DIR%\?.dll", [System.EnvironmentVariableTarget]::User)
[System.Environment]::SetEnvironmentVariable("LUA_PATH", `
    "?.lua;%LUA_DIR%\lua\?.lua", [System.EnvironmentVariableTarget]::User)
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Lua\bin", `
    [EnvironmentVariableTarget]::User)

Write-Host "LUA_DIR:    $env:LUA_DIR"
Write-Host "LUA_CPATH:  $env:LUA_CPATH"
Write-Host "LUA_PATH:   $env:LUA_PATH"
Write-Host "PATH:       $env:Path"
```
All these entries are empty or get not correctly extended.

The error can be seen here: https://ci.appveyor.com/project/swaldhoer/native-lua#L316 

How to fix this? I do not want to copy the install script content to the yaml-file, but run this script as well on AppVeyor as anyone could run it locally.

**Comment by FeodorFitsner** [comment]
Why not simply:

```posh
$env:LUA_DIR = $INSTALL_BIN
$env:LUA_CPATH = "?.dll;$env:LUA_DIR\?.dll"
$env:LUA_PATH = "?.lua;$env:LUA_DIR\lua\?.lua"
$env:PATH = "C:\Lua\bin;$env:PATH"

Write-Host "LUA_DIR:    $env:LUA_DIR"
Write-Host "LUA_CPATH:  $env:LUA_CPATH"
Write-Host "LUA_PATH:   $env:LUA_PATH"
Write-Host "PATH:       $env:Path"
```

**Comment by swaldhoer** [comment]
Yeah of course I could do it like that, but this is not what I want to do.
I don't want to duplicate a logical that is a already implement in a **working** script. Furthermore running this script is also some kind of test - namely if it works as expected - so I would like to run it in AppVeyor.

Can you explain why it is not working or why I **must** do it as you described on AppVeyor?

**Comment by IlyaFinkelshteyn** [comment]
@swaldhoer use `[System.EnvironmentVariableTarget]::Process` instead of  `[EnvironmentVariableTarget]::User`.  With `User` even on local machine you have to restart PowerShell session for change to take effect. You can test it with new values on your local machine.

**Comment by swaldhoer** [comment]
Ok I will do it that way. Thanks
