### ISSUE TITLE
XUnit test results are not being parsed

### ISSUE THREAD

**Issue by webknjaz** [appveyor/ci#2256]
Please inspect an artifact from https://ci.appveyor.com/project/amol-/dukpy/build/job/5hlu4d6nxf87vbvn/artifacts

**Comment by webknjaz** [comment]
Thanks. I think, docs should be OK improved then to point this out clearly.

**Comment by IlyaFinkelshteyn** [comment]
Our documentation is open source, please feel free to contribute :)
