### ISSUE TITLE
Ubuntu image has pre-release version of PowerShell Core (6.1.0-preview1 instead of 6.0.2)

### ISSUE THREAD

**Issue by bergmeister** [appveyor/ci#2267]
This is probably caused by a bug in how the PowerShell Core team configured the apt-get package provider that does not recognize that 6.1.0-preview is pre-release only.
The correct version should be 6.0.2
Related: https://github.com/PowerShell/PowerShell/issues/6496

**Comment by Wasapl** [comment]
Will fix this in next ubuntu image.
Meanwhile you can downgrade powershell in your appveyor.yml like this:
```
init:
- sh: apt-get -y -qq update && apt-get -y -q --allow-downgrades install powershell=6.0.2-1.ubuntu.16.04
```
And if you need to upgrade all other packages in build VM you can prevent updating powershell package:
```
init:
- sh: apt-get -y -qq update && apt-get -y -q --allow-downgrades install powershell=6.0.2-1.ubuntu.16.04
- sh: echo "powershell hold" | sudo dpkg --set-selections
- sh:  apt-get -y -qq update && apt-get -y -qq upgrade
```

**Comment by bergmeister** [comment]
@Wasapl I see [here](https://ci.appveyor.com/project/bergmeister/appveyor-test/build/1.0.35) that the updated image has been fixed now with version `6.0.2`. However, there seem to be some problems with the `PATH` variable, because `pwsh` is not on the `PATH` any more. see example [here](https://ci.appveyor.com/project/bergmeister/appveyor-test/build/1.0.36) where I am just calling `pwsh -command '"Hello World"'` (this used to work in previous images)

**Comment by Wasapl** [comment]
@bergmeister according to your appveyor.yml you run `pwsh -command '"Hello World"'` in PowerShell:
`- pwsh: pwsh -command '"Hello World"'`
Please use `sh:` prefix or no prefix instead of `pwsh:` prefix.
More information you may find at https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#bash-and-powershell

**Comment by Wasapl** [comment]
Powershell version 6.0.2 installed in recent ubuntu image update
