### ISSUE TITLE
Boost python libraries are linked to wrong python versions

### ISSUE THREAD

**Issue by zeule** [appveyor/ci#2271]
All boost python libraries are linked to python 2.7. Even this one (boost_python3):
```
Dump of file c:\Libraries\boost_1_65_1\lib64-msvc-14.0\boost_python3-vc140-mt-1_65_1.dll

File Type: DLL

  Image has the following dependencies:

    python27.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
```
This is a problem on itself because python 2.7 itself is linked to another C runtime (https://wiki.python.org/moin/WindowsCompilers).  However, when configuration system of the testing software takes that information into account, and selects correct python version for the compiler runtime (python 3), the compilation of an application that uses boost::python produces linking errors because of the python library mismatch.

Might be related: https://github.com/boostorg/python/issues/129

**Comment by FeodorFitsner** [comment]
So, how would you suggest to fix that?

**Comment by FeodorFitsner** [comment]
Yes, we install binary distribution. Will install Boost 1.67: https://github.com/appveyor/ci/issues/2275

**Comment by evsh** [comment]
Thanks, that would be good.

**Comment by XhmikosR** [comment]
This can be closed.
