### ISSUE TITLE
Build starting correctly, but status not displayed on GitHub

### ISSUE THREAD

**Issue by SylvainCorlay** [appveyor/ci#2273]
It appears that the builds for my project are starting properly on all CI services including appveyor, 

but appveyor does not report back the status for the build.

**Comment by SylvainCorlay** [comment]
The project is xtensor.

**Appveyor not displayed in the running CI:**

<img width="633" alt="screen shot 2018-04-24 at 7 54 34 pm" src="https://user-images.githubusercontent.com/2397974/39204865-5a40b1d8-47f9-11e8-8d61-ca365a53eaf3.png">

**Appveyor build running as expected:**

<img width="425" alt="screen shot 2018-04-24 at 7 55 24 pm" src="https://user-images.githubusercontent.com/2397974/39204935-8b98860c-47f9-11e8-9c54-96b4ac77d3e8.png">

**Comment by OwenMcDonnell** [comment]
Are both _Appveyor_ and _Appveyor CI_ are approved in your organization's GitHub 'settings->Third-party access' tab?

**Comment by SylvainCorlay** [comment]
We only have Appveyor CI approved for the organization. 

However, we never actually removed it and it worked before today...

**Comment by IlyaFinkelshteyn** [comment]
@SylvainCorlay  can you please try to open https://ci.appveyor.com/account, revoke GitHub authorization and authorize GitHub again. What I see in our traces is that GitHub API returns 404 when trying to set statuses for `QuantStack/xtensor`. GitHub API returns 404 when permission issues happened too. By re-authorizing you have a good chance to fix it.

**Comment by SylvainCorlay** [comment]
This does not appear to impact the organization, only my personal account.

**Comment by SylvainCorlay** [comment]
Sure:

In appveyor, the QuantStack account (corresponding to my firsname.lastname@quantstack.net) has github access as @SylvainCorlay

<img width="757" alt="screen shot 2018-05-01 at 3 07 48 pm" src="https://user-images.githubusercontent.com/2397974/39473903-88fb85ea-4d51-11e8-9265-67577537ad2c.png">

In my personal GitHub account, appveyor and appveyor CI are properly enabled:

<img width="606" alt="screen shot 2018-05-01 at 3 07 04 pm" src="https://user-images.githubusercontent.com/2397974/39473917-a4ae48d6-4d51-11e8-8d65-6b05482add7e.png">

However, in the QuantStack organization, only Appveyor CI is enabled.

<img width="590" alt="screen shot 2018-05-01 at 3 06 16 pm" src="https://user-images.githubusercontent.com/2397974/39473935-b57f28b0-4d51-11e8-855a-8bf0548b7f19.png">

**Comment by SylvainCorlay** [comment]
Oddly, in the QuantForge organization, which also belongs to us, the Appveyor app is properly enabled.

<img width="590" alt="screen shot 2018-05-01 at 3 06 16 pm" src="https://user-images.githubusercontent.com/2397974/39474021-31ed3eaa-4d52-11e8-92d1-2b9eebd56a82.png">

**Comment by SylvainCorlay** [comment]
Revoking appveyor everywhere triggers the dialog for requesting access, but only for Appveyor CI, not Appveyor.

**Comment by SylvainCorlay** [comment]
This appears to be solved now.
