### ISSUE TITLE
Duplicate builds for PR, never finishes

### ISSUE THREAD

**Issue by OmarTawfik** [appveyor/ci#2277]
I've the following PR: https://github.com/sb/SmallBasic-Online/pull/22
Creating the PR triggered two appveyor builds (pr and branch). pr completed, but branch was never queued.

* Why is a branch build triggered for this? this is a PR from a fork, not from a feature branch.
* Why was the branch build never triggered?
* Since I've two jobs split in my .yml file, is there a way to show them both in the GitHub PR page? right now, I have to click into the build to see the two jobs within. Should I define two jobs? how?

I'm suspecting this has to do with the fact that I've two appveyor projects in my account (one for the main, and one for my fork). Is there something wrong with the settings? how can I fix this?

**Comment by IlyaFinkelshteyn** [comment]
I think I understand what happens. You probably have protected branch settings for branch `master` undr `sb/SmallBasic-Online` like this:

![2018-04-25_15h51_39](https://user-images.githubusercontent.com/3248386/39277066-d3522550-48a0-11e8-9cf2-5e9ef8efc4f7.png)

However build for the fork branch happened under **different** AppVeyor account and project, [here](https://ci.appveyor.com/project/otawfik-ms/smallbasic-online/build/1.0.5). 

`SmallBasic-Online` AppVeyor project under `OmarTawfik` account has not way of knowing that it should update status for `sb/SmallBasic-Online` and not `OmarTawfik/SmallBasic-Online` GitHub repo. Also it does not necessary have permissions to do that.

So if you plan to send PRs from the fork, I would recommend to uncheck `continuous-integration/appveyor/branch` from protected branch settings.

Or you can modify your fork build to update status in the main repo with some custom script like [this](https://gist.github.com/IlyaFinkelshteyn/def2394231afb7f06dcaeaceda1fb1ae) but for me it is overkill.

Hope this makes sense. If you have any ideas how we can make make this experience better, you are welcome!

**Comment by OmarTawfik** [comment]
@IlyaFinkelshteyn perfect! that was the problem.
Do you know how can I set up the two configurations (debug/release) as two separate appveyor jobs that appear in the PR page (below), instead of having just one, and having to click through it to find the two runs?

![image](https://user-images.githubusercontent.com/15987992/39279964-279affe6-48b1-11e8-82c1-8157afd5d043.png)

**Comment by IlyaFinkelshteyn** [comment]
Please watch https://github.com/appveyor/ci/issues/1805, seems that we need to force it, especially with [Linux/Windows](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side)  builds.
