### ISSUE TITLE
Azure CLI 2.0

### ISSUE THREAD

**Issue by andrejohansson** [appveyor/ci#2278]
Im trying to use the command ``az login`` (as per https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest) from appveyor and the command is not found. I´ve tried both the ``Visual Studio 2015`` image and the ``Visual Studio 2017`` image.

I also tried to install it using chocolately (``choco install azure-cli``) which succeeded but did not seem to add the ``az`` command.

From what I can tell Azure Cli should be pre-installed on the 2015 Image atleast.

Is it missing or am I doing something wrong?

**Comment by andrejohansson** [comment]
I will try that, but even if it works, it adds minutes to my build...so, isnt the cli supposed to be on the image already?

**Comment by FeodorFitsner** [comment]
Will take a look and fix.

**Comment by FeodorFitsner** [comment]
During the next images update we'll make sure the latest version of Azure CLI is installed on all images.

**Comment by andrejohansson** [comment]
Thank you!
