### ISSUE TITLE
.NET 4.7.2 support

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#2290]
https://blogs.msdn.microsoft.com/dotnet/2018/04/30/announcing-the-net-framework-4-7-2/

**Comment by halex2005** [comment]
I'm using `Vistual Studio 2017 Preview` image.

I've tried to build and run .NET Framework 4.7.2 project using `dotnet` CLI, but got error:
(https://ci.appveyor.com/project/halex2005/dotnet-new-nunit-g8axg/build/1.0.19)

```
> dotnet test CSharpNet472
Build started, please wait...
C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\projects\dotnet-new-nunit-g8axg\CSharpNet472\CSharpNet472.csproj]
```

Here is my [appveyor.yml](https://github.com/halex2005/dotnet-new-nunit/blob/master/appveyor.yml).

What I'm doing wrong?
Does `Vistual Studio 2017 Preview` image have .NET Framework 4.7.2 installed?

**Comment by FeodorFitsner** [comment]
Will check and fix shortly: https://github.com/appveyor/ci/issues/2369
