### ISSUE TITLE
Qt 5.3, 5.4, 5.5, 5.7, 5.8 reached EOL removed from VS 2015 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2291]
According to [Qt versions history](https://en.wikipedia.org/wiki/Qt_version_history#Qt_5) page support has already ended for the following Qt 5.x releases:

* 5.3
* 5.4
* 5.5
* 5.7
* 5.8

We are removing them from the image to free up the space for newer Qt releases and other software.

**Comment by pbek** [comment]
That's very sad, users of [QOwnNotes](https://www.qownnotes.org) are still using Windows XP with Qt 5.7 and are now complaining that it doesn't work any more. :(
see: https://github.com/pbek/QOwnNotes/issues/828#issuecomment-390333844

Is there an other way to get Qt 5.7 working on the AppVeyor CI build system (which I love a lot)?

(btw. the documentation still features Qt 5.7: https://www.appveyor.com/docs/build-environment/#qt)

**Comment by pbek** [comment]
I kindly wanted to ask if there are any news @FeodorFitsner.

**Comment by IlyaFinkelshteyn** [comment]
@pbek default [build worker image](https://www.appveyor.com/docs/build-environment/#build-worker-images) is called `Visual Studio 2015`. Build is running on this image unless other one specified with image:` or `os:` setting`, or alternatively with `APPVEYOR_BUILD_WORKER_IMAGE` environment variable. 

You have [os: unstable](https://github.com/pbek/QOwnNotes/blob/develop/appveyor.yml#L7) setting, which you probably inherited from some older configuration. But as long as we do not have image called `unstable` right now, your builds are being executed on `Visual Studio 2015`.

Sorry for confusion. I would remove `os: unstable` though.

**Comment by pbek** [comment]
Thank you for your answer, @IlyaFinkelshteyn! I removed the setting `os: unstable`, but Qt 5.7 was still not found. Build details: https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3619/job/s39r1n7e35vlpit1

**Comment by FBachofner** [comment]
@IlyaFinkelshteyn,  Is there any forthcoming resolution for supporting Qt 5.7 for @pbek 's build process?

We support a few Windows XP machines because of legacy hardware driver issues and are now significantly behind on being able to update his excellent QOwnNotes software on these Windows XP machines.

Thanks in advance for whatever you can do to support Patrizio's desired use to continue builds with Qt 5.7 !

**Comment by FBachofner** [comment]
@FeodorFitsner @IlyaFinkelshteyn @pbek -- is there any progress on a resolution to this issue of 32-bit build using Qt 5.7?

Thanks in advance.

**Comment by FeodorFitsner** [comment]
Added this issue: https://github.com/appveyor/ci/issues/2502 It's online when it's closed.

**Comment by pbek** [comment]
Thanks a lot @FeodorFitsner!
