### ISSUE TITLE
update kernel in Ubuntu image 

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#2294]

**Comment by l3uddz** [comment]
Kernel 4.13.0 would be perfect for me.

**Comment by desimaniac** [comment]
Im with @l3uddz.

Basically we need `linux-generic-hwe-16.04`..

```
 sudo apt-get install --install-recommends linux-generic-hwe-16.04  
```

**Comment by Wasapl** [comment]
Kernel updated to 4.13.0 in recent ubuntu image update
