### ISSUE TITLE
Cancel button for individual job

### ISSUE THREAD

**Issue by kasper3** [appveyor/ci#2295]
In addition to `Cancel Build`, please provide a `Cancel Job` button for individual job in the build.

Travis CI example:

<img src="https://user-images.githubusercontent.com/33230602/39480435-d6eba054-4d70-11e8-8eab-33ff2a093cf4.png" width="30%" />

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/58.

**Comment by kasper3** [comment]
Ok :)
