### ISSUE TITLE
'az login' requires sudo to run

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2300]
Actual behavior:

When trying to log into azure using `az login` the following error occurs:

```
with open(self.config_path, 'w') as configfile:PermissionError: [Errno 13] Permission denied: '/home/appveyor/.azure/config'
```

Expected behavior:
`appveyor` user should have access to `/home/appveyor/.azure/config`

**Comment by vivet** [comment]
Use ````sudo az login```

**Comment by Wasapl** [comment]
Fixed in recent ubuntu image
