### ISSUE TITLE
Ubuntu: clone_folder partially belongs to root

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2305]
I use `clone_folder: /home/appveyor/ros_workdir/reactos-cov`.
Per #2124, I think this was still working well 7 days ago: I assume this is a regression.
It is possible I modified my `yml`, though I don't remember so. Anyway, it should work...

Today, my build fails, because of wrong `ug`:
`drwxr-xr-x   3 root     root      4096 May  3 15:40 ros_workdir/`

For what it's worth, I tried to build 3 times and I always got `ssh appveyor@67.225.139.144 -p 22603`.

PS:
* New attempt, same IP different port.
* Workaround: `sudo chown -v --from=root:root appveyor:appveyor ~/ros_workdir`.

---

Also, not sure if it belongs here or to separate issue, I noticed the VMs had a `~/.bash_history` with lots of commands.
I believe it should not exists, or at least be minimal.

**Comment by FeodorFitsner** [comment]
Thanks for reporting that! We'll take a look.

**Comment by Wasapl** [comment]
Fixed in recent ubuntu image update

**Comment by SergeGautherie** [comment]
Verified fixed.
