### ISSUE TITLE
Visual Studio 2017 version 15.7.1

### ISSUE THREAD

**Issue by martijn00** [appveyor/ci#2310]
https://blogs.msdn.microsoft.com/visualstudio/2018/05/07/visual-studio-2017-version-15-7-and-version-15-8-preview-1/

Visual Studio 15.7 is out as well. It would be great to have this updated and released soon, as MSBuild has been broken for almost 2 months now.

**Comment by OwenMcDonnell** [comment]
Correspondingly, 'Visual studio 2017 preview' image should be [updated](https://blogs.msdn.microsoft.com/visualstudio/2018/05/07/visual-studio-2017-version-15-7-and-version-15-8-preview-1/) to 15.8 preview 1.

**Comment by FeodorFitsner** [comment]
Right, added a new issue: https://github.com/appveyor/ci/issues/2317
