### ISSUE TITLE
GitHub Apps integration for granular per-repository permissions

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2312]
Related issue: https://github.com/appveyor/ci/issues/527

**Comment by FeodorFitsner** [comment]
https://www.appveyor.com/blog/2018/10/02/github-apps-integration/

**Comment by zvirja** [comment]
@FeodorFitsner I've installed the [AppVeyor app](https://github.com/marketplace/appveyor), however it isn't displayed in the list of installed apps... Is it expected? On the marketplace page it's listed as installed:
![image](https://user-images.githubusercontent.com/1074182/47876721-a8613f80-de22-11e8-9350-3836d560814f.png)

but on the settings page it's absent:
![image](https://user-images.githubusercontent.com/1074182/47876764-c62ea480-de22-11e8-8717-5c9dce27cb4e.png)

**Comment by FeodorFitsner** [comment]
In Marketplace there is still an OAuth app, not a GitHub App.

**Comment by zvirja** [comment]
@FeodorFitsner Thanks for the hint!

For guys like me - follow the "Migrating existing projects to GitHub Apps" section described in the [article above](https://www.appveyor.com/blog/2018/10/02/github-apps-integration/).
