### ISSUE TITLE
Add pip/virtualenv to default Python installations

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#232]

**Comment by cjw296** [comment]
+1

**Comment by FeodorFitsner** [comment]
pip is included with Python 2.7.9 and 3.4.x: https://pip.pypa.io/en/latest/installing.html#pip-included-with-python

so, we'd need to add pip to 3.3.x only.

**Comment by cjw296** [comment]
Do you not support 2.6? Also, please install virtualenv if possible!

**Comment by FeodorFitsner** [comment]
Oh, 2.6? Would you help me to find Windows installer for it: https://www.python.org/download/releases/2.6.9/?

**Comment by cjw296** [comment]
The last release with a binary installer is here:

https://www.python.org/download/releases/2.6.5/

I'd imagine you would be able to compile 2.6.9 from source though...

**Comment by FeodorFitsner** [comment]
Tried compiled 2.6.9 from sources - tons of errors - it's definitely not mine :)
virtualenv was installed to all pythons
