### ISSUE TITLE
Stuck on conan user

### ISSUE THREAD

**Issue by p-groarke** [appveyor/ci#2328]
Following these instructions https://docs.conan.io/en/latest/integrations/appveyor.html, build is stuck on the command "conan user".

https://ci.appveyor.com/project/p-groarke/ns-getopt/build/1.0.40
https://github.com/p-groarke/ns_getopt

I haven't found any log that would be useful for investigation.

**Comment by p-groarke** [comment]
Seems related to UI environment variables.

**Comment by OwenMcDonnell** [comment]
Do you have `CONAN_PASSWORD` set in UI environment variables?

**Comment by p-groarke** [comment]
Yes. I’ve RDPed into the VM and don’t see the environment variable. However, I’m guessing it is local to the build environment?

I’ve tried locking and unlocking CONAN_PASSWORD variable (in the UI).
Also tried bringing it in the yaml file this way: CONAN_PASSWORD: $(CONAN_PASSWORD)

My Appveyor knowledge is limited, so I’m hitting the limit of what I can debug. Running “conan user” in the RDP session worked.

**Comment by OwenMcDonnell** [comment]
Can you try just adding it to yaml as a [secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables). Go to 'encrypt data` page of your AppVeyor account and put encrypted value in yaml as,
```yaml
environment:
  CONAN_PASSWORD:
    secure: <encrypted_value>
```

**Comment by OwenMcDonnell** [comment]
When you RDP into the VM and it works, did you reset every variable that you have exactly as they are in the configuration?

**Comment by p-groarke** [comment]
Nope. Just spawned a cmd prompt and ran conan user. It logged in anonymously though (since no environment variables are set).

**Comment by OwenMcDonnell** [comment]
So then we can conclude that there is some bad values w.r.t conan variables, no?

**Comment by p-groarke** [comment]
If the script and UI variables are supposed to be set system wide on the machine.

See my first reply : “I’ve RDPed into the VM and don’t see the environment variable. However, I’m guessing it is local to the build environment?”

**Comment by OwenMcDonnell** [comment]
>If the script and UI variables are supposed to be set system wide on the machine.

Are they? I don't see that mentioned in the [conan docs](https://github.com/conan-io/conan-package-tools#appveyor-integration). 
But if you think it matters, I guess you could try `[Environment]::SetEnvironmentVariable("<conan_variable>", "<value>", "Machine")`.

Doesn't it seem more likely that the `conan user` command is blocking because one of your values is unexpected/unaccepted? Seems to me, again, without knowledge of conan cofig, it would make sense that when you RDP and there are no variables that cause some error which subsequently blocks the command, some defaults are used, and the command succeeds.

**Comment by p-groarke** [comment]
Could be, will do some more testing tomorrow.
Thx for helping out.

**Comment by OwenMcDonnell** [comment]
No problem. 
Though its be a bit of a typing nuisance, It might be worth RDPing and resetting all those variables in command session just to see if the `conan user` command fails or not. 
Don't hesitate to ping with any other questions or updates.

**Comment by OwenMcDonnell** [comment]
You mean you did that via RDP?
