### ISSUE TITLE
Arangodb support?

### ISSUE THREAD

**Issue by johnvcoleman** [appveyor/ci#233]
Would it be possible to add Arangodb support to your build workers?  It's small and can be installed as a Windows service easily:  https://www.arangodb.com/download/

Thanks!

**Comment by FeodorFitsner** [comment]
Hey John,

Looks like it could be easily XCOPY-deployed from a zip: https://docs.arangodb.com/cookbook/XCopyInstallWindows.html

**Comment by johnvcoleman** [comment]
Yep, that was going to be my plan B.  I just wasn't looking forward to wrestling with/debugging the appveyor.yml script.  This is one of the reasons I don't care for Travis CI, getting the .yml file right is very time consuming.  Then again, I guess I could tap into the "before build" script from within the AppVeyor UI and execute a powershell script to install Arangodb.

Does that sound like the simplest way to get it done to you?

**Comment by FeodorFitsner** [comment]
Absolutely, you can configure everything on UI and then export to YML if necessary! "Before build script" or "Install script" are the right places to install ArangoDB.

**Comment by johnvcoleman** [comment]
Thanks!
