### ISSUE TITLE
Filter by mutiple branches

### ISSUE THREAD

**Issue by craftwar** [appveyor/ci#2338]
1. I want display history in branch=master or branch=dev
2. download latest one artifact from latest build in multiple branches
Is this possible in https request?

**Comment by OwenMcDonnell** [comment]
To answer second question first, you can download build artifacts using a script like [this](https://www.appveyor.com/docs/api/samples/download-artifacts-ps/).

Could you elaborate a little more on the first question?

**Comment by craftwar** [comment]
https://www.appveyor.com/docs/packaging-artifacts/, I can download without script but from only one branch.
I expect something like
1. https://ci.appveyor.com/api/projects/johnsmith/myproject/?branch=master&branch=dev
to display branch master and dev
2. https://ci.appveyor.com/api/projects/johnsmith/myproject/artifacts/bin/debug.zip?branch=master&branch=dev
download latest one build form master or dev branch (only one artifact is downloaded)
Sorry, I miss one word in second case. I don't want to expose my api token. Currently, I use curl to download artifact in different scripts.
