### ISSUE TITLE
Commit message text is not escaped

### ISSUE THREAD

**Issue by jawshooah** [appveyor/ci#234]
On the build page, the displayed commit message text does not appear to have been escaped before rendering, so anything that looks like an HTML tag is cut out.

For example, if my commit message is

```
Test angle brackets

This won't show up: (<test>)
```

It renders as 

```
Test angle brackets

This won't show up: ()
```

This may even be a XSS attack vector, but I haven't checked.

**Comment by FeodorFitsner** [comment]
Thanks for reporting that! Nice catch.
