### ISSUE TITLE
The Spectre mitigation libraries are not installed (Windows SDK version 1803)

### ISSUE THREAD

**Issue by heydojo** [appveyor/ci#2347]
Related to : https://github.com/appveyor/ci/issues/2296
The Spectre mitigation libraries are not installed in image: Visual Studio 2017.
This results in the following build message, if you are trying to mitigate Spectre in your application:

> warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka.ms/Ofhn4c for more information.

This causes the linker to fail with the following message:
`LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib' [c:\somefolder\someproject.vcxproj]`

You are able to see what's missing if you expand the individual components section using the Visual Studio installer and look for:

- VC++ 2017 v15.7 v14.14 libs for Spectre (x86 and x64)

Are there any plans to add these new libs?
Thanks.

**Comment by FeodorFitsner** [comment]
Will add them in the coming days, for sure.

**Comment by heydojo** [comment]
Great!
I'll check back next image update. Thanks.
