### ISSUE TITLE
Add option to skip granting website folder permission to apppool

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2349]
Customer has huge folders which does not change (skipped with `skip_dirs`), and resetting it's permission consumes a lot of time and CPU. Customer prefers to control ACLs himself.

**Comment by filipesousa** [comment]
We have this issue as well. The website is huge and it takes about 15 mins just to grant read permissions to all the files.

**Comment by IlyaFinkelshteyn** [comment]
This is actually done. Please use `<artifact_name>.skip_acl: true`.

**Comment by IlyaFinkelshteyn** [comment]
@filipesousa do not forget to install [latest](https://www.appveyor.com/downloads/deployment-agent/latest/AppveyorDeploymentAgent.msi) agent for that option to work :)
