### ISSUE TITLE
.NET 4.7.2 support with XML doc generation

### ISSUE THREAD

**Issue by RalfKoban** [appveyor/ci#2353]
Hi, I've seen that there has been .NET 4.7.2 support added (#2290). That's great. :smiley:

Unfortunately, Microsoft made a mistake in their F# XML documentation which prevents to correctly build XML documentation for .NET 4.7.2 projects using Sandcastle Help File Builder (and all other tools that use XML docs). I've created an issue for that (https://github.com/EWSoftware/SHFB/issues/604)

However, to fix that, there is only a workaround available.
You need to manually edit the file
_`C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.3.0\FSharp.Core.xml`_
to remove the duplicated `</returns>` in line 5900.

As I don't have access to that file, would it be possible if an admin could remove that duplicated `</returns>` / fix that line?

**Comment by IlyaFinkelshteyn** [comment]
You can use the following script at `init` stage:

```
$filePath =  "C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.3.0\FSharp.Core.xml"
$fileContent = Get-Content $filePath
$fileContent | % { If (!($_.ReadCount -eq 5900 -and $_ -eq " </returns> ")) {$_}} | Set-Content $filePath
```

Let us know if this helps.  We will consider updating this globally if we see more people hurt by this,

**Comment by RalfKoban** [comment]
@IlyaFinkelshteyn 
Thanks for the script. 😃 👍 
A new version of Sandcastle Help File Builder has been [released](https://github.com/EWSoftware/SHFB/releases/tag/2018.5.29.0) which contains a fix for the issue.
Hence there is no need anymore to adjust the script.
