### ISSUE TITLE
Ruby - update to RubyGems 2.7.7 & Misc

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2354]
In the RubyGems repo, they recently updated to bundler 1.16.2, and it caused fails in several Ruby versions.  As of 20-May, see https://github.com/rubygems/rubygems/commits/master.

Anyway, I investigated, found a solution/fix that I used in a PR there, and then decided to generalize it for future use.  It updates all versions from 2.0 and later.

The code is in my 'testing-appveyor' repo, the main file is [rubygems_update.ps1](https://github.com/MSP-Greg/testing-appveyor/blob/master/rubygems_update.ps1), with an additional file that prints several folders' contents out, which is [dir_out.ps1](https://github.com/MSP-Greg/testing-appveyor/blob/master/dir_out.ps1).  All that's in the appveyor.yml file is launching `rubygems_update.ps1`.

It upgrades RubyGems to 2.7.7 (which also adds Bundler 1.16.2), updates minitest & rake, and removes old gem versions.  The console is [here](https://ci.appveyor.com/project/MSP-Greg/testing-appveyor/build/16).  All the updating occurs first, then `gem list` and the folder contents are printed for each version.

I don't know if you can use PowerShell scripts to update images, but I think this will do the trick, as it solved the issue with the RubyGems testing...

Thanks again,  Greg

**Comment by MSP-Greg** [comment]
@FeodorFitsner

For you, both done.  See [testing-appveyor 17](https://ci.appveyor.com/project/MSP-Greg/testing-appveyor/build/17).

Thanks, Greg

**Comment by FeodorFitsner** [comment]
Well, while you are looking into the Ruby (thank you for doing that!) may I ask you to look through PS script we use to install Ruby on AppVeyor images: https://github.com/appveyor/ci/blob/master/scripts/enterprise/install_ruby.ps1 You definitely will spot something unusual and maybe incorporate your proposes fix! 😃 
Your help is greatly appreciated!

**Comment by MSP-Greg** [comment]
I can do that; trying to finish up one other project, which is assembling fat binary gems on Appveyor.

With a quick look - 

1. `cmd /c` is being used quite a bit, I don't know if that's needed.  Have you found it helpful?
2. Bundler is being explicitly installed, but the Rubygems update now includes it.

I'll fork it and have a real look at by running it locally...

Thanks again, Greg

**Comment by MSP-Greg** [comment]
@FeodorFitsner

I may have gone to far, but I updated the [install_ruby.ps1](https://github.com/MSP-Greg/ci/blob/msp_greg/scripts/enterprise/install_ruby.ps1).  I changed several things, but one thing I added was allowing the code to install a new version (say 2.4/2.5), but run the update on all versions. 
Done via these two lines:
```powershell
$rubies_install = $r19 + $r20 + $r21 + $r22 + $r23 + $r24 + $r25
$rubies_update  = $r19 + $r20 + $r21 + $r22 + $r23 + $r24 + $r25
```

You may have looked at the repo I have that lists info on MSYS2 / MinGW and all the installed ruby versions.  I took the script from that, and added it.

Latest build console is [here](https://ci.appveyor.com/project/MSP-Greg/ci/build/1).  Total time was 10:56 to install and update all ruby versions.

One issue that I wrestled with, and that's encoding.  The 'info' section of the above build has some mangled characters that should be solid lines.  The odd thing is that using what I believe is the exact same code, it looks fine in the other [repo's builds](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby).  Any ideas on that one?

Finally, I could do a PR, or you can take what you want...

Thanks,  Greg

**Comment by FeodorFitsner** [comment]
Oh, great, will take a closer look!

At a glance - I'd like to keep Ruby installations in the locations as they are now as changing locations will break tons of builds.

Thank you for your efforts!

**Comment by MSP-Greg** [comment]
I set it up that way just so I could check it locally, as all my ruby versions match AV's.

And yes, moving them would **break everything Ruby**.  Hence, if we go with a PR, I'll move it back to C:\

Thanks, Greg

**Comment by FeodorFitsner** [comment]
Got it. Will review it tomorrow.

**Comment by FeodorFitsner** [comment]
OK, cool. So, I'm changing `$ruby_pre = 'C:\AV'` to `$ruby_pre = 'C:\'` to test on "production" like environment?

**Comment by MSP-Greg** [comment]
Yes, but (since I made a similar mistake earlier), change lines 11-14 to

```Powershell
# Path prefix for rubies
$ruby_pre = 'C:\'
if( !(Test-Path -Path $ruby_pre) ) { New-Item -Path $ruby_pre -ItemType Directory 1> $null }
$ruby_pre = $ruby_pre.Trim('\') + '\Ruby'
```

Finally, while AFK today, I realized that I need to check the update code to see if it re-applies updates that werepreviously done.  For example, if one has already updated to RubyGems 2.7.7, re-running updates won't change anything in the image.  Same for Psych...

Thanks, Greg

**Comment by FeodorFitsner** [comment]
But we are re-installing Rubies on VM images from scratch anyway, so I’m good to go and try the script?

**Comment by MSP-Greg** [comment]
Sorry, intermittently AFK this afternoon.

Yes.  I just pushed an update that allows the update code to be rerun and not re-install anything that isn't needed.  I just did a [build on AV](https://ci.appveyor.com/project/MSP-Greg/ci/build/5) using `C:\`.  So, the update code could be split out for your enterprise customers or your use...

> But we are re-installing Rubies on VM images from scratch anyway

Are you referring to AV or enterprise customers, or both?

Thanks, Greg

**Comment by FeodorFitsner** [comment]
Both.

Thank you - will give it a try later today.

**Comment by MSP-Greg** [comment]
Didn't know that.  I always assumed that you could do incremental updates, rather than from scratch with every change.  Probably takes a while for all the scripts to run...

Thanks, Greg

**Comment by MSP-Greg** [comment]
@FeodorFitsner

Just a heads up that the OneClick Ruby releases for versions 2.4 & 2.5 have jumped to a `-2` rev.

**Comment by FeodorFitsner** [comment]
Thanks for letting know!

Added two new issues:
https://github.com/appveyor/ci/issues/2470
https://github.com/appveyor/ci/issues/2471

**Comment by MSP-Greg** [comment]
@FeodorFitsner

I'm okay to close this if you are...

**Comment by FeodorFitsner** [comment]
OK, cool.
