### ISSUE TITLE
Secure variables on pull requests not working

### ISSUE THREAD

**Issue by csMACnz** [appveyor/ci#2355]
I am aware that there is functionality that allows secure variables to become available to the pull request build on appveyor.  However the secure variable seem to not be available to the build.

This fails for both windows and linux builds.

* I have turned on the setting `Enable secure variables in Pull Requests from the same repository only` from the UI for the repository
* I have opened the PR between two branches from the same repository

PR: https://github.com/csMACnz/Coveralls.net-Samples/pull/7
Build: https://ci.appveyor.com/project/MarkClearwater/coveralls-net-samples

As far as I can tell, this functionality should be working fine (based on other issues in this repo). But the environment variable is empty

**Comment by csMACnz** [comment]
A few thoughts:
* is there a delay for the setting taking effect?
* Is there a cache that is causing the setting change not to apply?
* does this work between two non-master branch names?
* could there be a case sensitivity between the repo and appveyor in the repo name so that it thinks it isn't the same?

I haven't tried reproducing this in any other repos, yet.

**Comment by IlyaFinkelshteyn** [comment]
@csMACnz Secure variables are not allowed in PRs for security reason. Some details in the bottom of [this](https://www.appveyor.com/docs/build-configuration/#interpreters-and-scripts) part of documentation.

There is a UI-only option `Enable secure variables in Pull Requests from the same repository only` for public projects and both `Enable secure variables in all Pull Requests` and  `Enable secure variables in Pull Requests from the same repository only`for private projects. It is located in General project settings.

**Comment by csMACnz** [comment]
@IlyaFinkelshteyn can you take a closer look at what I am doing? I have read this information and have already turned on Enable secure variables in Pull Requests from the same repository only on my public repository as mentioned.

Is there any other reason this wouldn't be working as described in the documentation?

**Comment by csMACnz** [comment]
Ok, there was a case sensitivity issue with the `GitHub repository` general setting as well. I had `csmacnz/Coveralls.net-Samples` and that didn't match `csMACnz/Coveralls.net-Samples` So presumably it thought I was in a fork.


Changing `GitHub repository` to `csMACnz/Coveralls.net-Samples`  has fixed the problem.

**Comment by IlyaFinkelshteyn** [comment]
@csMACnz sorry for premature answer. Indeed I should have to look closer... And thank you for the update.
