### ISSUE TITLE
Builds that miss a whole first part of their log, after being silently truncated

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2357]
Build 338, both console and file, has its last 4603 lines only.
Build 439, both console and file, has its last 4650 lines only.
Build 448, both console and file, has its last 4643 lines only.

Compared to some similar builds, these compile tests in addition to code, so generating even more logs.

Could you check/fix this issue?

**Comment by OwenMcDonnell** [comment]
There is an option above the log to display the full log which links to this url (https://ci.appveyor.com/project/SergeGautherie/reactos/build/reactos.appveyor.338?fullLog=true). Note the 'fullLog=true' query parameter.
![display_full_log](https://user-images.githubusercontent.com/7119543/40375811-8aedbd4a-5da1-11e8-82cc-43d5ad448223.png)

**Comment by xt0rted** [comment]
Above the log it says
>The last 2,000 lines of the build log are shown. Display or download complete log.

![image](https://user-images.githubusercontent.com/831974/40378288-1b12d792-5dc1-11e8-8e59-94343abb527c.png)

Click the `Display` link and you'll be able to see the full log.

**Comment by SergeGautherie** [comment]
> you'll be able to see the full log

No, I am not! Are you?

**Comment by xt0rted** [comment]
Both logs start at line 1 after clicking `Display`, and match the download files, but I'm not sure if that's actually the first line of the log.

![image](https://user-images.githubusercontent.com/831974/40391269-ae2ca9a8-5de5-11e8-8302-f1e35403e079.png)

**Comment by SergeGautherie** [comment]
> Both logs start at line 1 after clicking Display, and match the download files,

Yes, that is what I see/get too.

> but I'm not sure if that's actually the first line of the log.

It is not, obviously!

**Comment by IlyaFinkelshteyn** [comment]
@it is actually expected behavior. After log reaches a 8Mb so it is being overwritten. Please decrease log verbosity.

**Comment by SergeGautherie** [comment]
> it is actually expected behavior. After log reaches a 8Mb it is being overwritten.

Really? Ah! Is this limitation documented somewhere?

While limiting console output size, even in "full" mode, seems useful,
truncating the file itself feels more like a broken behavior, as the remaining log becomes somewhat useless.

For the record, the file size of these example logs, after truncation, is about 512 MiB "only".

Example issues I notice:
- There is not even a warning added to tell (why) the log/file was truncated.
- For example, details about `RDP`/`SSH` are lost when enabled in `init:`.
Though I will file a dedicated issue about that.

Possible solutions:
- Do not truncate the file at all.
- Create chunks, as in `log.1` `log.2`...
- Roll the log instead of truncating it, so the size remains at 8 MiB.
- ...

> Please decrease log verbosity.

I'll check what I can do, though that is only a workaround in any case.

**Comment by FeodorFitsner** [comment]
Will close it when "rolling log" fix is deployed to production.

**Comment by SergeGautherie** [comment]
For what it's worth, see `ave-5.6` issues: #2492 and #2495.

**Comment by FeodorFitsner** [comment]
The fix has been deployed to production.

**Comment by SergeGautherie** [comment]
> Will close it when "rolling log" fix is deployed to production.

Could you briefly explain how "rolling log" is intended to behave?

> The fix has been deployed to production.

I ran [test build ROS-747](https://ci.appveyor.com/project/SergeGautherie/reactos/build/reactos.appveyor.747) and the current issue doesn't look fixed:
log console/file starts at `[00:07:06]` and is 6.7 MiB.

Please, reopen.

**Comment by FeodorFitsner** [comment]
The maximum log size is still 8 MB and this is the sum of all control structures (JSON) the log is made of, so if the log consists of a large number of small chunks it's "downloadable" size could be less than 8 MB.

With that update we changed the way the log is truncated - if the log exceeds 8 MB you will see the last 8 MB of it.

**Comment by SergeGautherie** [comment]
> it's "downloadable" size could be less than 8 MB.

The reason was not obvious, Thanks for the explanation. That improvement works as intended.
Is that "max/rolling log" documented somewhere?

> With that update

I understand you may not want to "fix" the 8 MiB limitation in any way, as "wanted by design".
Yet, adding a message would be an acceptable fix for this very issue:
- at the beginning of the log, if possible? And/Or, at least, at the end?
- in the UI, in any case. Like the "max 60 min" message.
