### ISSUE TITLE
Cygwin setup-x86.exe not at stated location

### ISSUE THREAD

**Issue by jawshooah** [appveyor/ci#236]
Here is [the failed build](https://ci.appveyor.com/project/jawshooah/overcommit/build/163/job/d7ub0b9lcwk3nmb5).

Going by [this post](http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin#comment_35059453), I'm attempting to install `grep` via `cygwin` with the following command:

```
C:\cygwin\setup-x86.exe -qnNdO -R C:\cygwin -s http://cygwin.mirror.constant.com -l C:\cygwin\var\cache\setup -P grep
```

But apparently, `setup-x86.exe` isn't there:

```
The system cannot find the path specified.
```

Is `cygwin` no longer pre-installed? Has the path changed?

**Comment by gep13** [comment]
This is the list that I go by in terms of what is available on the build worker images:

http://www.appveyor.com/docs/installed-software

I believe that it is kept reasonably up to date.

**Comment by jawshooah** [comment]
Ah, that's a shame. Cygwin is universally useful enough that it should probably have remained pre-installed, but maybe there were problems with it. @FeodorFitsner, could you shed any light on this?

**Comment by gep13** [comment]
Depending on the answer, you can always run:

```choco install cygwin```

i.e. install via [Chocolatey](https://chocolatey.org/packages/Cygwin)

As the first step in your build process, and this will get it installed.  I use this approach for a number of my build dependencies.

**Comment by jawshooah** [comment]
True, but cygwin takes an agonizingly long time to install, which means I'll be waiting at least 15 minutes for my build to even start. Yes, there's the build cache, but that doesn't help when builds are failing.

**Comment by FeodorFitsner** [comment]
Sorry for the delay with reply. Cygwin is installed on `unstable` image. Add this to `appveyor.yml`:

    os: unstable
