### ISSUE TITLE
skip_commits for files does not work

### ISSUE THREAD

**Issue by romani** [appveyor/ci#2363]
`skip_commits` for `files` does not work or there is some misconfiguration that I can not catch. 

config: https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L8

full build: https://ci.appveyor.com/project/Checkstyle/checkstyle/build/11586/job/94bhw356l8aiui33

commit is only for file that should be always skipped:
https://github.com/checkstyle/checkstyle/commit/24583fd82f611325f4df02cdfbe7542f5f28967c

**Comment by IlyaFinkelshteyn** [comment]
Maybe because it is [travis.yml](https://github.com/checkstyle/checkstyle/blob/master/appveyor.yml#L8) without a dot (`.`) in the beginning, e.g. not `.travis.yml`?

**Comment by romani** [comment]
my bad, I saw blind, thanks a lot.

can you share here a link to documentation on how to define to skip all files in folder?

**Comment by IlyaFinkelshteyn** [comment]
@romani no worries, please check [this doc](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits-2)
