### ISSUE TITLE
.NET Core 2.1

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#2373]
.net core 2.1 rtmed today with the official release around May 30th. Links to the SDK downloads can be found at https://github.com/aspnet/Home/wiki/2.1.0-Early-Access-Downloads#ok-can-i-have-the-bits-now-please

**Comment by FeodorFitsner** [comment]
OK, let's wait for official release then! 😃

**Comment by kasper3** [comment]
I would read the section with three exclamation signs before and after before trying it install it https://github.com/aspnet/Home/wiki/2.1.0-Early-Access-Downloads#caveats---read-this. Lets wait for few more days 😄

**Comment by xt0rted** [comment]
Hot off the presses https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by FeodorFitsner** [comment]
Cool, will make it into production this week.

**Comment by JustArchi** [comment]
Works for me - https://ci.appveyor.com/project/JustArchi/archisteamfarm/build/job/lgf6rgh0cl217bf7

**Comment by xt0rted** [comment]
I'm seeing it now as well

**Comment by FeodorFitsner** [comment]
Yep, this is the test: https://ci.appveyor.com/project/appveyor-tests/dotnet-core/build/1.0.163#L45

@tidusjar Do you have `global.json`? Can you share a link to your build (or contact us via email if the project is private) please?

**Comment by leastprivilege** [comment]
Works for me now as well on Visual Studio 2017 image - do I need to do anything special for Ubuntu?

**Comment by FeodorFitsner** [comment]
Ubuntu update is coming: https://github.com/appveyor/ci/issues/2413

**Comment by leastprivilege** [comment]
thanks

**Comment by tidusjar** [comment]
@FeodorFitsner apologies for the late reply.

I do not have a `global.json` file and here is the build:
https://ci.appveyor.com/project/tidusjar/requestplex/build/3.0.3367

**Comment by FeodorFitsner** [comment]
This project is still targeting 2.0: https://github.com/tidusjar/Ombi/blob/master/src/Ombi/Ombi.csproj

**Comment by OwenMcDonnell** [comment]
@tidusjar Seems your publish settings are picking up older version from [this line](https://github.com/tidusjar/Ombi/blob/feature/dotnetcore2.1/build.cake#L29). Try changing it to `netcoreapp2.1`.

**Comment by tidusjar** [comment]
oh man your right! sorry!
