### ISSUE TITLE
Change $APPVEYOR on Ubuntu from 'true' to 'True'

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#2376]
Please, add `$APPVEYOR` and other environment variables to Ubuntu image...

**Comment by sergey-s-betke** [comment]
`$APPVEYOR` does not defined on Ubuntu image:
https://ci.appveyor.com/project/sergey-s-betke/marks/build/1.0.0%20(Build%20107)/job/v4d2xcdu7l0skqr0

See echo $APPVEYOR command line.

**Comment by Wasapl** [comment]
It's there but in your example it's hard to find after long output of `apt-get install` command.
You see, you couple `apt-get ...` and `echo $APPVEYOR` lines in one sh block. Therefore commands printed out together (with blue color) and commands output follows.
So tiny `true` on line 89 is the value of `$APPVEYOR`.

**Comment by sergey-s-betke** [comment]
@Wasapl, yes, `$APPVEYOR == 'true'` on Ubuntu image, but `$APPVEYOR == 'True'` on WMF5 image! But in [help](https://www.appveyor.com/docs/environment-variables/) value must be 'True'!

**Comment by Wasapl** [comment]
You're right. Will fix help for ubuntu image.

**Comment by FeodorFitsner** [comment]
Docs updated.
