### ISSUE TITLE
Add Push-AppveyorArtifact and other commandlets to Ubuntu image

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#2377]
https://ci.appveyor.com/project/sergey-s-betke/marks/build/1.0.0%20(Build%20108)/job/sjcp03d5u48ew0nh

**Comment by FeodorFitsner** [comment]
Looks like AppVeyor cmdlets are not available when invoked from a custom `pwsh` call.

We have to load the module via PS profile.

**Comment by sergey-s-betke** [comment]
Ok, thank You!

**Comment by sergey-s-betke** [comment]
@FeodorFitsner , what is the module name?

**Comment by FeodorFitsner** [comment]
It's `/opt/appveyor/build-agent/AppVeyor.BuildAgent.PowerShell.dll`.

**Comment by sergey-s-betke** [comment]
Yes, it worked!

**Comment by FeodorFitsner** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6#paths

```
~/.local/share/powershell/Modules
~/.local/share/powershell/Modules/AppVeyor/appveyor.psm1
~/.local/share/powershell/Modules/AppVeyor/AppVeyor.BuildAgent.PowerShell.dll
/opt/appveyor/build-agent/AppVeyor.BuildAgent.PowerShell.dll
```

**Comment by johlju** [comment]
@FeodorFitsner Do the AppVeyor cmdlets exist on the Windows images for PS Core as well now (this module)? If so issue  https://github.com/appveyor/ci/issues/2263 is resolved?

**Comment by IlyaFinkelshteyn** [comment]
@johlju https://github.com/appveyor/ci/issues/2263 is a little bit different issue, we set it's milestone to Q3

**Comment by sergey-s-betke** [comment]
@FeodorFitsner, I can test it now?

**Comment by FeodorFitsner** [comment]
Nope, it's in production yet, sorry.

**Comment by sergey-s-betke** [comment]
@Wasapl, can I test it now (without explicit module loading)?

**Comment by Wasapl** [comment]
@sergey-s-betke, Yes you can. We released new ubuntu image yesterday. Fix for this issue is in it.
