### ISSUE TITLE
Do not build tags option in web GUI is ignored (when I do git push with --tags)

### ISSUE THREAD

**Issue by brodybits** [appveyor/ci#238]

**Comment by FeodorFitsner** [comment]
Do you use `appveyor.yml`?

**Comment by brodybits** [comment]
Yes but this option is not configured in `appveyor.yml`. Shouldn't it be enough to enable it on the web page?

**Comment by FeodorFitsner** [comment]
Nope, you should use `skip_tags: true` in `appveyor.yml`.

**Comment by brodybits** [comment]
> Nope, you should use skip_tags: true in appveyor.yml.

I added `skip_tags: true` to appveyor.yml. Then when I tried the following command:
```
git push bb test3 --tags
```

I got the following output:
```
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 305 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To https://github.com/brodybits/cordova-windows.git
 * [new branch]      test3 -> test3
 * [new tag]         3.9.0-nufixpre-01 -> 3.9.0-nufixpre-01
 * [new tag]         3.9.0-pre-nufixpre -> 3.9.0-pre-nufixpre
```

and then in https://ci.appveyor.com/project/brodybits/cordova-windows/history I got exactly two new builds queued: one for the change in `test3` and one for `3.9.0-pre-nufixpre`. I really do not understand this.

**Comment by brodybits** [comment]
> I got exactly two new builds queued: one for the change in `test3` and one for `3.9.0-pre-nufixpre`.

Looks like that was a corner case. The following:

```
C:\Users\Chris\Documents\GitHub\cwintest\cordova-windows [master +8 ~0 -0 !]> git push lh --tags master
Counting objects: 68, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (25/25), 2.59 KiB | 0 bytes/s, done.
Total 25 (delta 19), reused 0 (delta 0)
To https://github.com/litehelpers/cordova-windows-nufix.git
   e857332..46dfabf  master -> master
 * [new tag]         3.9.0-nufixpre-01 -> 3.9.0-nufixpre-01
```

did not give me any extra builds.

I do still find it confusing though if the GUI offers this option and it is ignored without notice in case `appveyor.yml` is present.

**Comment by FeodorFitsner** [comment]
It's default behavior - UI settings are ignored if `appveyor.yml` is found. The only exception there is environment variables and notification settings defined on UI which are added to those ones from yml.

**Comment by FeodorFitsner** [comment]
Also, to see why build was (not) created you may check "Recent deliveries" section on GitHub webhook settings.

**Comment by brodybits** [comment]
Thanks for your help.

**Comment by sdesalas** [comment]
I too found this a bit confusing, as the options in the web UI and `appveyor.yml` dont exactly overlap. So I assumed that the WebUI applied if the option was missing in the yml file.
