### ISSUE TITLE
Preinstall openJDK 9.0.4

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#2382]
Download it from http://jdk.java.net/archive/

**Comment by adamretter** [comment]
@Wasapl another alternative is to use the OpenJDK builds provided by Azul https://www.azul.com/downloads/zulu/zulu-linux/

**Comment by adamretter** [comment]
@Wasapl So was this fixed? I don't see any reference to any commits or details?

**Comment by Wasapl** [comment]
Oh, I'm sorry I didn't comment on this. Yes it's fixed and new image released some days ago. Here is release note: https://www.appveyor.com/updates/2018/06/08/

**Comment by adamretter** [comment]
@wasapl No worries, thanks for the fix :-)
