### ISSUE TITLE
Git-lfs panic failure

### ISSUE THREAD

**Issue by andrejohansson** [appveyor/ci#2388]
Appveyor seems to be running git-lfs v 2.4.0 which contains a bug that causes a panic failure in some conditions. See https://github.com/git-lfs/git-lfs/issues/3031

Updating to version > 2.4.1 should fix the issue, but note that just running the installer doesnt help (I had to remove git lfs from the mingw folder in order for git to use the newly installed one by git lfs installer).

**Comment by OwenMcDonnell** [comment]
[Added](https://github.com/appveyor/ci/issues/2392) to next images update.
