### ISSUE TITLE
xUnit.Tests never start

### ISSUE THREAD

**Issue by godrose** [appveyor/ci#2393]
The following project's tests suddenly failed to start. Any build compiles successfully and then freezes at the `test` stage:

This is the project's url:
https://ci.appveyor.com/project/LogoFX/logofx-client-mvvm-viewmodel-extensions

This is the log
[log-3.txt](https://github.com/appveyor/ci/files/2049770/log-3.txt)

**Comment by IlyaFinkelshteyn** [comment]
@godrose [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) to build VM and see what happens. Probably some interactive window pops up and waiting for the user input, or some process (or thread child to xunit console) stuck. Let us know what you found.

**Comment by godrose** [comment]
I was unable to establish RDP even after following all the steps in the tutorial. 
I got **logon failed** attempt. I tried to set the password both via `.yaml` and the **Environment** variables.

**Comment by IlyaFinkelshteyn** [comment]
Did you paste encrypted value in to Environment UI by any chance and then press "lock"? If yes, password becomes double-encrypted and is not being decoded to the original text. In any case you can simple do not set `APPVEYOR_RDP_PASSWORD` and AppVeyor will generate and print random password fro you.

**Comment by godrose** [comment]
@IlyaFinkelshteyn  Only `.yaml` is used

**Comment by OwenMcDonnell** [comment]
As @IlyaFinkelshteyn mentioned, try to remove `APPVEYOR_RDP_PASSWORD` from your yaml completely and just rely on the auto-generated password and see if you can RDP that way.

**Comment by godrose** [comment]
@OwenMcDonnell Where can I see this auto-generated password?
Can you point to the exact location? Thanks.

**Comment by godrose** [comment]
@ilya finkelshtein. It’s rather amusing as there are no visible environment variables in the UI as well as no such variables are defined in the .yaml file
https://github.com/LogoFX/logofx-client-mvvm-viewmodel-extensions/blob/master/appveyor.yml

**Comment by OwenMcDonnell** [comment]
I forked your repo and built and got the password in the console, as you can see in the first image. Also attached are my UI settings on the 'environment' tab. 

So your settings match mine?

![rdp-password](https://user-images.githubusercontent.com/7119543/41015699-48fbc8ea-6900-11e8-8ced-fa2c2b9608e7.png)
![rdp-password-ui](https://user-images.githubusercontent.com/7119543/41015703-4d97697c-6900-11e8-8772-308799261f08.png)

**Comment by godrose** [comment]
@owen mcdonell. I can’t see any difference. Looks identical to me.

**Comment by IlyaFinkelshteyn** [comment]
@godrose this is really becoming interesting :) Can you add ` - ps: echo $env:APPVEYOR_RDP_PASSWORD` at `init` stage before you run `enable-rdp.ps1` script and re-run the build?

**Comment by godrose** [comment]
@IlyaFinkelshteyn @OwenMcDonnell
I'm able to see the password now 
The only difference between the executions is that I used 'New Build' option instead of 'Re-build commit' one (besides the time difference of course).
I see an open shell window and the build agent window. Nothing more
<img width="1678" alt="screen shot 2018-06-06 at 9 09 26 am" src="https://user-images.githubusercontent.com/7791651/41019897-5bc9939e-6969-11e8-8038-ec06a64d3245.png">

**Comment by OwenMcDonnell** [comment]
I did a little investigating via RDP but couldn't find anything that seemed like an obvious cause resource wise on the build machine. I'm not sure how the CMD shell processes are being activated and then closed by each step of the build. 

I also tried the build on the 'Previous Visual Studio 2017' image but the build failed before testing. 

Are you able to build and test this project locally?

**Comment by godrose** [comment]
Yes. It works locally without any issues. Which part of my local configuration should I share to help you understand what’s missing/different between the environments?

**Comment by godrose** [comment]
@IlyaFinkelshteyn Any resources which could help to resolve this issue? This is a real blocker

**Comment by IlyaFinkelshteyn** [comment]
@godrose something wrong with multi threading there, see https://github.com/LogoFX/logofx-client-mvvm-viewmodel-extensions/pull/11 for workaround which should unblock you.
