### ISSUE TITLE
Ubuntu JAVA_HOME set to C:\Program Files\Java\jdk10

### ISSUE THREAD

**Issue by JamzTheMan** [appveyor/ci#2410]
So this is driving me nuts trying to get a linux build done.  I finally removed the windows image part from my yml and just tested with the following and this is what I'm getting the below.

PS Are we getting 10 preinstalled anytime soon? It seems to be the default for Windows VM?

```
image: Ubuntu
build_script:
  - which java && which javac && java -version
  - echo java home is $JAVA_HOME
  - sudo update-alternatives --config java
  - gradle build -x spotlessCheck
```

Results:

```
Build started
git clone -q --branch=1.4.5.0 https://github.com/JamzTheMan/MapTool.git /home/appveyor/projects/maptool
git checkout -qf 0cd75fe60c389e91a17ff822f0f6d48f1079e1cd
Running "build_script" scripts
which java && which javac && java -version
/usr/lib/jvm/java-9-openjdk-amd64/bin/java
/usr/lib/jvm/java-9-openjdk-amd64/bin/javac
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-21-232247.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-21-232247.buildd.src, mixed mode)
echo java home is $JAVA_HOME
java home is C:\Program Files\Java\jdk10
sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).
  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      auto mode
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
* 3            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      manual mode
Press <enter> to keep the current choice[*], or type selection number: gradle build -x spotlessCheck
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk10
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Command exited with code 1
Build failed
```

**Comment by FeodorFitsner** [comment]
Oh, will take a look. That's weird indeed.

**Comment by JamzTheMan** [comment]
Thanks, Let me know if you need any other info from my side.  I only posted a snippet of my yml but you can see the full source on that branch on my my repo. (The rest of the yml is straight forward and for deployment and notification and such).

**Comment by Wasapl** [comment]
@JamzTheMan , I cant reproduce your results:
https://ci.appveyor.com/project/appveyor-tests/vp-ssh#L107
Can you please share your full `appveyor.yml`

**Comment by JamzTheMan** [comment]
Sure, this is one of the versions that produced this issue:

```
version: '{branch}.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: false
platform: x64
image: Ubuntu
build_script:
  - which java && which javac && java -version
  - echo java home is $JAVA_HOME
  - sudo update-alternatives --config java
  - gradle build -x spotlessCheck
after_build:
  - gradle deploy
artifacts:
  - path: build\libs\MapTool-*.jar
    name: MapTool-Jar
  - path: releases\release-*\MapTool-*.exe
    name: MapTool-Windows
  - path: releases\release-*\MapTool-*.deb
    name: MapTool-Linux
deploy:
  - provider: GitHub
    description: Windows release from AppVeyor
    auth_token:
      secure: HXIHe/F7K2yGOZ0I56DW5PevrQDe+zjyunjORGKYaUGxFtvPYPcmOdjZT69tzHcS
    artifact: MapTool-Jar, MapTool-Windows, MapTool-Linux
    draft: true
    prerelease: true
    force_update: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Webhook
    url: 
      secure: AYQNchUXucpUxTDKoURYmnesdyYxxAPeGmGf0tM/aJhGVp8X5yuiKoZNjULxjoOICX47ufGpdz+BEJ9nYaj7WrBSNx5dJJOoxsZ+dpPZfPOlidHW/JoNWHM8JMP0P5TwRGaTOGOk3aIlUBftDA/wRVQhRcjiwivpoA0mzD6PSsY=
    method: POST
    body: >-
      {
        "embeds": [
          {
            "title": "Build {{buildId}}",
            "url": "{{buildUrl}}",
            "color": {{#passed}}40973{{/passed}}{{^passed}}11672839{{/passed}},
            "footer": {
              "icon_url": "{{#passed}}https://i.imgur.com/Rf4g8v6.png{{/passed}}{{^passed}}https://i.imgur.com/QaERwAW.png{{/passed}}",
              "text": "{{#passed}}Success{{/passed}}{{^passed}}Failure{{/passed}}"
            },
            "author": {
              "name": "{{commitAuthor}}",
              "url": "https://github.com/{{repositoryName}}/commit/{{commitId}}"
            },
            "fields": [
              {
                "name": "Commit",
                "value": "[{{commitMessage}}](https://github.com/{{repositoryName}}/commit/{{commitId}})"
              },
              {
                "name": "Duration",
                "value": "{{duration}}",
                "inline": true
              },
              {
                "name": "Build version",
                "value": "{{buildVersion}}",
                "inline": true
              }
            ]
          }
        ]
      }
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
```

**Comment by JamzTheMan** [comment]
FYI: Looking at your log, it looks like a lot of vars are getting set, especially:
JAVA_HOME=/usr/lib/jvm/java-9-openjdk-amd64

Note, I'm not specifying JAVA_HOME in this config, hence, I'm thinking it's picking up the default environment variable from the VM.

If I explicitly set export JAVA_HOME it's ok (but per the sample in the doc, this var is not set for Ubuntu images)

**Comment by Wasapl** [comment]
@JamzTheMan , all variables you see in my log are set by bash during boot of Appveyor Build Agent. Most of them (including `$JAVA_HOME`) are set in `.profile` and `.bashrc`. `env` command only shows all variables set. Also you may click on commit this build was made from and you'll see that i'm not setting any variables (except `APPVEYOR_SSH_*` vars): https://github.com/appveyor-tests/vp-ssh/blob/ca5ab45ae599e32bf6c21894a98c42fa617dfccc/appveyor.yml

**Comment by Wasapl** [comment]
@JamzTheMan can you please share the link to build where you got this reproduced.

**Comment by JamzTheMan** [comment]
OK. I'm still coming up to speed so wasn't sure if the configuration: - joppa3 pulled in and defaults or anything.

So what sets this VM to be linux? Is that the default if you don't supply the Image tag?

**Comment by JamzTheMan** [comment]
https://ci.appveyor.com/project/JamzTheMan/maptool/build/1.4.5.0.147

This should show config that produced the error.

**Comment by Wasapl** [comment]
Image is set by variable APPVEYOR_BUILD_WORKER_IMAGE via appveyor UI.
That `configuration - joppa3` is just a previous test of yaml validation and it does not affect anything.

**Comment by JamzTheMan** [comment]
FYI: I'm now also seeing this ->
"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "", should be "true")

BUT I'm only seeing it on the Ubuntu build. Windows uploads it's artifacts ok. I'm not using 'on branch' and creating a tagged release via github. It's always worked for me in Windows builds.

**Comment by JamzTheMan** [comment]
I was wondering if it may be a case sensitivity thing but would think other people would have issues.

I'll give it a try.
