### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by mchaloupka** [appveyor/ci#2412]
I have renamed GitHub project but can't seem to be able to change the name used by AppVeyor in the URL. I believe this is the same issue as discussed in #562 and #999. Can you please update the following project:

Old name: https://ci.appveyor.com/project/mchaloupka/dotnetr2rmlstore
Desired new name: https://ci.appveyor.com/project/mchaloupka/evi

Thanks

**Comment by IlyaFinkelshteyn** [comment]
Done.

**Comment by mchaloupka** [comment]
Thanks!
