### ISSUE TITLE
.NET Core SDK 2.1 on Ubuntu

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2413]

**Comment by FeodorFitsner** [comment]
Correct, thank you.

**Comment by Wasapl** [comment]
due to lack of donet-host-2.1.0-rc1 package in microsoft's repository next packages can't be installed:
dotnet-sdk-2.1.300
dotnet-runtime-2.1.0

**Comment by bergmeister** [comment]
@wasapl Can you reference or create an issue in one of the dotnet repos for that?
Having the 2.1.300 would be a great improvement in terms of build times

**Comment by sebastienros** [comment]
Can you explain the issue? Can't you setup the sdk by running `dotnet-install.sh` ?

**Comment by bergmeister** [comment]
@sebastianros Yes, you can install the SDK yourself but I have seen slightly different behaviour in my repo. In a pwsh step I installed it as follows:
```powershell
Invoke-WebRequest 'https://dot.net/v1/dotnet-install.sh' -OutFile dotnet-install.sh
bash dotnet-install.sh --version 2.1.300          [System.Environment]::SetEnvironmentVariable('PATH', "/home/appveyor/.dotnet$([System.IO.Path]::PathSeparator)$PATH")
```

**Comment by sebastienros** [comment]
@bergmeister sorry, it was not meant for you, just for @Wasapl to understand why it can't be setup on the default images.

**Comment by Wasapl** [comment]
@bergmeister @sebastienros Guys I'm sorry for misleading you. I was talking about `RC1` versions of sdk and runtime. 
`dotnet-runtime-2.1.0-rc1`  Depends on `dotnet-hostfxr-2.1.0-rc1`,
and `dotnet-hostfxr-2.1.0-rc1` : Depends: `dotnet-host`.
But here what `apt-get install`  says:
```
# apt-get install dotnet-hostfxr-2.1.0-rc1
[....SKIPPING regular messages....]
The following packages have unmet dependencies:
 dotnet-hostfxr-2.1.0-rc1 : Depends: dotnet-host (>= 2.1.0-rc1) but 2.1.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
I do understand now why version `2.1.0-rc1` of dotnet-host package was deleted from the repo. That is because of apt thinks `2.1.0-rc1` version more recent than `2.1.0-1` version.

**Comment by sebastienros** [comment]
Why do you care about RC1, it's now RTM, and maybe why this package was removed.

**Comment by sebastienros** [comment]
Actually it seems RC1 doesn't work, why would you still spend some effort on it when you could just focus on RTM? I tried and I see it is on Visual Studio 2017 images but still not Ubuntu.
