### ISSUE TITLE
Which version of InnoSetup 5.5.9 is installed on the build images?

### ISSUE THREAD

**Issue by m-tmatma** [appveyor/ci#2421]
https://www.appveyor.com/docs/build-environment/#tools says that "InnoSetup 5.5.9 (C:\Program Files (x86)\Inno Setup 5)"  is pre-installed on the build images.

There are two versions of InnoSetup 5.5.9, innosetup-5.5.9.exe and innosetup-5.5.9-unicode.exe
at http://www.jrsoftware.org/isdl.php.

Which version of InnoSetup is installed on the build images?

**Comment by FeodorFitsner** [comment]
It's innosetup-5.5.9-unicode.exe. Docs updated.
