### ISSUE TITLE
https://gitlab.com/api/v3/ is gone

### ISSUE THREAD

**Issue by mcepl** [appveyor/ci#2422]
When trying "New Build" on my M2Crypto project, I get this error:
```
Cannot read last commit information from GitLab repository mcepl/m2crypto:
HTTP GET to https://gitlab.com/api/v3/projects/mcepl%2fm2crypto
returned status code 410: Gone Full response body:
{"error":"API V3 is no longer supported. Use API V4 instead."}
```

**Comment by mcepl** [comment]
See also https://help.appveyor.com/discussions/problems/14603-cant-add-new-gitlab-project

**Comment by IlyaFinkelshteyn** [comment]
Please subscribe to https://appveyor.statuspage.io/incidents/5qh9tjh5t7qg

**Comment by IlyaFinkelshteyn** [comment]
https://github.com/appveyor/ci/issues/2426 fixed
