### ISSUE TITLE
Add VirtualBox to Ubuntu image

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#2423]
Similar to issue 176 (VirtualBox on Windows) and issue 2405 (KVM on Ubuntu).

**Comment by FeodorFitsner** [comment]
https://www.ostechnix.com/install-oracle-virtualbox-ubuntu-16-04-headless-server/

**Comment by Wasapl** [comment]
VirtualBox on ubuntu images installed: https://www.appveyor.com/updates/2018/11/14/
