### ISSUE TITLE
PowerShell cmdlet Push-AppveyorArtifact not available any more after latest Ubuntu image update

### ISSUE THREAD

**Issue by bergmeister** [appveyor/ci#2428]
See [here](https://ci.appveyor.com/project/PowerShell/psscriptanalyzer/build/1.0.2870/job/fes5y3bghcodt9gm) for an example build failure introduced by the latest Ubuntu image update in the last days

**Comment by JustArchi** [comment]
ref: https://github.com/appveyor/ci/issues/2183#issuecomment-395883717

**Comment by Wasapl** [comment]
Fixed. @bergmeister Can you please verify that your build works fine.

**Comment by bergmeister** [comment]
@Wasapl Awesome, yes it is fixed now. Thanks. Amazing support :-)
