### ISSUE TITLE
Missing Microsoft Enterprise WDK

### ISSUE THREAD

**Issue by rozmansi** [appveyor/ci#2446]
Hi!

We have ported the OpenVPN's Windows TAP driver building process to use Microsoft Enterprise WDK (EWDK). EWDK is portable and distributed as an ISO image. However, it is 5GB in size making it inappropriate to download on each build.

Is it possible to mount EWDK ISO image in the AppVeyor's build environment? Or even better: have it preinstalled in the build environment(s) in like C:\EWDK?

Thank you and best regards,
Simon Rozman

**Comment by rozmansi** [comment]
Thank you for your generous offer.

However, I was hoping you'd pre-install the EWDK to the VS2017 build worker image making it standard feature for Windows driver development CI.

**Comment by IlyaFinkelshteyn** [comment]
Build worker images are quite difficult to manage and update, so we try to keep only software which some considerable amount if customers need. If we see higher demand, we will add it. I will re-open the issue to see if other people will vote for this.

Another alternative for you is using private build cloud and maintain your own image. More info:
https://www.appveyor.com/docs/build-environment/#private-build-cloud
https://www.appveyor.com/docs/enterprise/how-to/#private-build-clouds

Let us know if you ant to try, so we can enable this feature for you,

**Comment by rozmansi** [comment]
Unfortunately, we don't have resources (men×hours) to establish a private build cloud.

It is most likely that we will reintroduce building using WDK until EWDK is available in any of the AppVeyor build worker images.

Thank you for your assistance.
