### ISSUE TITLE
Is there any way to shorten timeout?

### ISSUE THREAD

**Issue by m-tmatma** [appveyor/ci#2457]
If #2456 happens, it takes 60 minutes to fail the build.
Is there any way to shorten a build timeout?

**Comment by OwenMcDonnell** [comment]
Presently, build timeout can only be set at account level and would therefore affect all projects belonging to that account. 

Let us know if you would like your build timeout customized.

**Comment by m-tmatma** [comment]
Do you have a plan that build timeout can be customizable by appveyor.yml?
I saw #517, but there was no progress for three years.

**Comment by m-tmatma** [comment]
By applying https://github.com/sakura-editor/sakura/pull/156, we are not in an urgent need of this issue.

**Comment by IlyaFinkelshteyn** [comment]
Closing it. @m-tmatma let us know if you need us to keep it open.
