### ISSUE TITLE
Restart-computer command can indefinitely stall build in init stage

### ISSUE THREAD

**Issue by OwenMcDonnell** [appveyor/ci#2459]
Compare [build](https://ci.appveyor.com/project/britzkopf/projecta/build/0.0.144) with command in init stage to [build](https://ci.appveyor.com/project/britzkopf/projecta/build/0.0.146) with command in install stage.

**Comment by IlyaFinkelshteyn** [comment]
This should be fixed now

**Comment by IlyaFinkelshteyn** [comment]
@trexinc there is a race condition, which is specific to the `init` step. If you set sleep value to 10 seconds, it would be more than enough to eliminate its possibility and continue to restart at `init` step. Let us know if this helps.
