### ISSUE TITLE
CMD command cannot include a '%' (percent sign) character

### ISSUE THREAD

**Issue by vszakats** [appveyor/ci#246]
Appveyor engine appears to _strip_ escaped percent sign `%%` and convert `%n` (where n = 0-9) character pair to empty string in CMD (Windows batch) commands, making it not possible to use the percent character in an executed command. Percent sign has an important role in URL escaping and can be useful in other use-cases, too. Probably it'd be nice to support it like `.bat` files do.

More detail: http://help.appveyor.com/discussions/questions/1218-is-there-a-way-to-include-percentage-sign-in-a-batch-command

**Comment by vszakats** [comment]
Closing this, assuming a `wontfix`.

**Comment by vszakats** [comment]
This remained an unresolved problem and so far all workaround had some unwanted side effects. I settled on using an URL shortener, but that makes the build log opaque by hiding the effective URL and the need to configure and rely on a 3rd party service:
   https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.127#L28

**Comment by vszakats** [comment]
@FeodorFitsner Is there any hope for this Issue to be considered in a future update?

At the moment I'm using workaround below, but anybody looking into the log output cannot say for certain which URL was downloaded, and it's also a mess to update:
```
# Long URL: "https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.2.0/threads-posix/sjlj/x86_64-5.2.0-release-posix-sjlj-rt_v4-rev0.7z"
- curl -fsS -L --proto-redir =https https://goo.gl/mQF6vO -o mingw.7z
```

**Comment by FeodorFitsner** [comment]
Have you tried running that command as `ps`?

    - ps: curl -fsS -L --proto-redir =https https://<full-url> -o mingw.7z

**Comment by vszakats** [comment]
I did now with [this](https://github.com/vszakats/harbour-core/blob/740d4ffe1ba388ba3b5b4e2812929326b9546b35/appveyor.yml#L45) command:
```
- ps: curl -fsS -L --proto-redir =https https://www.mirrorservice.org/sites/dl.sourceforge.net/pub/sourceforge/m/mi/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.2.0/threads-posix/sjlj/x86_64-5.2.0-release-posix-sjlj-rt_v4-rev0.7z -o mingw.7z
```

It's possible I missed to quote something for PowerShell (I'm completely unfamiliar with it), but [this error](https://ci.appveyor.com/project/vsz/harbour-core/build/3.4.593#L20) was the result:
![screen shot 2015-11-03 at 20 28 56](https://cloud.githubusercontent.com/assets/1446897/10919254/16d77c26-826a-11e5-8806-a1b1e850b178.png)

**Comment by FeodorFitsner** [comment]
That's weird. Looks like there is some sort of `curl` alias in PowerShell. Try disabling it: https://github.com/lukesampson/scoop/issues/56

**Comment by vszakats** [comment]
That did the trick! Thank you very much for the tips, I'm all set with this new method.

Closing the Issue with: Successfully worked around without significant drawbacks.

* https://github.com/vszakats/harbour-core/blob/743f503468cc4f2aa713ca97608457d86ed66ac6/appveyor.yml#L45-L46
* https://ci.appveyor.com/project/vsz/harbour-core/build/3.4.594#L21

**Comment by jayvdb** [comment]
Why cant this be fixed?  There are some obvious ways of reducing the surface area of this problem, if it cant be eliminated completely.

**Comment by jayvdb** [comment]
A fairly easy workaround is to use cmd in ps like `ps: cmd /c ftype rubyfile=C:\Ruby24\bin\ruby.exe '"%L"' '%*'`

But that doesnt help people who dont find this issue, and spend hours trying to figure out how to escape the percents.

**Comment by steve-chavez** [comment]
I also got this issue when running the following git command:

```bash
git show -s --format="%cd-%h" --date="format:%Y-%m-%d-%H-%M"

fatal: invalid --pretty format: h
```

Using double percentage didn't help. The error confused me and lead me to debug git versions. Finally I landed on using Powershell, which works fine.

There are some **Do not use** warnings on the [appveyor docs](https://www.appveyor.com/docs/build-configuration/). It would be nice to have a similar **Do not use %%** warning.

**Comment by Kristinita** [comment]
**Status: Not fixed** :crying_cat_face:

### 1. Problem

10 years after the opening of this issue I still get errors if I use percent sign in my command. [**Example build**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging#L54):

```shell
git log -1 --pretty=%B
fatal: invalid --pretty format: B

```

I don’t reproduce the problem on my local Windows.

When I run the command `git log -1 --pretty=%B`, for example, from Grunt, [**I don’t reproduce the problem**](https://ci.appveyor.com/project/Kristinita/sashagruntdebugging/builds/51679612#L27).

### 2. Reopening

In my opinion, the issue must be reopened, because the problem isn’t solved. It would be nice if in the future users can use in the file `appveyor.yml` the same commands as they use on the local cmd.exe prompt.

Thanks.

**Comment by binki** [comment]
I found I could work around this by double-escaping the percent sign. To apply this example to your `appveyor.yml`, to enumerate a directory called `"%USERPROFILE%\Downloads\reportprojects-4.0.0\$MSBuild\Reporting%20Services"`, use:

```yaml
install:
  - DIR "%USERPROFILE%\Downloads\reportprojects-4.0.0\$MSBuild\Reporting%%%%20Services"
```

EDIT: This suggests that a double-expansion of some sort is happening. I have not tried investigating this (yet?).
