### ISSUE TITLE
Errors from Appveyor CI webhooks

### ISSUE THREAD

**Issue by Mariatta** [appveyor/ci#2465]
Hello,

I'm noticing a number of webhooks to Appveyor CI resulting in 500 errors. Thought I report them here.
These are from [python/cpython](https://github.com/python/cpython) repository.

See screenshots:

<img width="757" alt="screen shot 2018-06-23 at 9 48 19 am" src="https://user-images.githubusercontent.com/5844587/41811768-d9bc6132-76ca-11e8-8fe9-6223c6640de9.png">

The error message says `{"message":"Object reference not set to an instance of an object."}`:

<img width="802" alt="screen shot 2018-06-23 at 9 50 52 am" src="https://user-images.githubusercontent.com/5844587/41811772-f422b8e6-76ca-11e8-9339-927629c8fade.png">

Thanks.

**Comment by FeodorFitsner** [comment]
Could you please email the payload (headers and body) for one of the failing calls?

**Comment by Mariatta** [comment]
For sure, where can I email it to?

**Comment by FeodorFitsner** [comment]
team@appveyor.com

**Comment by Mariatta** [comment]
Sent. Thanks!

**Comment by FeodorFitsner** [comment]
Got it. Looking into that.

**Comment by FeodorFitsner** [comment]
The fix has been deployed. It should be fine now.

**Comment by Mariatta** [comment]
Thanks for the quick fix!!
