### ISSUE TITLE
`exit 0` causes build to hang in `install` or `build_script`

### ISSUE THREAD

**Issue by arbourd** [appveyor/ci#2469]
Hi there,

We have a condition when we need to bail out of a build early and it appears to hang, in both `install` or `build_script` on Ubuntu.

Build logs:
```sh
git clone -q --branch=appveyor-chart-changes git@github.com:redacted/charts.git /home/appveyor/projects/charts
git checkout -qf ace6cb1b2395c27032b631d80939764f34c8bbdb
Running "install" scripts
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v${MINIKUBE_VERSION}/minikube-linux-amd64
chmod +x minikube
sudo mv minikube /usr/local/bin/.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 9 40.7M    9 4096k    0     0  8619k      0  0:00:04 --:--:--  0:00:04 8605k100 40.7M  100 40.7M    0     0  48.2M      0 --:--:-- --:--:-- --:--:-- 48.2M
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64.4M  100 64.4M    0     0  58.0M      0  0:00:01  0:00:01 --:--:-- 58.0M
curl https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar xz
chmod +x linux-amd64/helm
sudo mv linux-amd64/helm /usr/local/bin/.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8946k  100 8946k    0     0  17.1M      0 --:--:-- --:--:-- --:--:-- 17.1M
Starting 'services'
Starting Docker
Running "build_script" scripts
exit 0
```

<img width="996" alt="screen shot 2018-06-26 at 4 44 54 pm" src="https://user-images.githubusercontent.com/7211830/41938166-4ddb2c46-7960-11e8-8aee-d747a088ea33.png">

**Comment by arbourd** [comment]
This seems to be a duplicate of #2427. 

Also, `appveyor exit` also doesn't work.

**Comment by FeodorFitsner** [comment]
yep, we are looking into that. Thanks for reporting!

**Comment by IlyaFinkelshteyn** [comment]
@arbourd closed prematurely :) It is actually fixed but not yet deployed, should be closed for good in coming days.

**Comment by Wasapl** [comment]
@arbourd I'm sorry I messed with commit description. I was not aware that simple reference in commit description can close issue ))
As Ilya said we found the root cause and we will deploy new image soon.

**Comment by arbourd** [comment]
Hey guys! No worries, thanks for keeping us in the loop.

I work for a company thats using this to replace a chunk of our Kubernetes work, and are excited to see this being worked on. Big fan of the feedback too!

Thank you both for your hard work. 🚀

**Comment by Wasapl** [comment]
Fix released https://www.appveyor.com/updates/2018/07/04/
