### ISSUE TITLE
dotnet restore results in 401 errors

### ISSUE THREAD

**Issue by tylerbhughes** [appveyor/ci#2474]
I've created a .NET Standard library that I'm trying to get it to build using Appveyor. When I run dotnet resotore like so:

```
before_build:
- cmd: dotnet restore
```

I get a bunch 401 errors when it runs. I saw online where someone said to use nuget restore but that presents me with errors about the csproj file not being supported by msbuild. Which method should I be using?

**Comment by IlyaFinkelshteyn** [comment]
Seems like problem discussed [here](https://help.appveyor.com/discussions/problems/6024-build-stalled-prompting-for-nuget-permissions#comment_41867748)

**Comment by IlyaFinkelshteyn** [comment]
Most probably it is that problem, looking into [this](https://github.com/tylerbhughes/Telegraph/blob/afa92bb56abe3bb83ed9e4d6168875e37fb80af5/appveyor.yml#L42) YAML setting. Let us know if this helps. Closing it for now.
