### ISSUE TITLE
Access realtime build log

### ISSUE THREAD

**Issue by kenkit** [appveyor/ci#2478]
Hi is there a way to access the build log in realtime, like the webaccess buildlog ?

**Comment by IlyaFinkelshteyn** [comment]
Please check [this](https://www.appveyor.com/docs/api/projects-builds/#download-build-log) API and [this](https://gist.github.com/IlyaFinkelshteyn/26be0b5e7e10a684bc7e2c1ae94c0fbf) sample (created to wait for specific entries appear in log).

**Comment by kenkit** [comment]
Ok, thanks I'll try it out
