### ISSUE TITLE
Delete build history

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#248]
Discussion: http://help.appveyor.com/discussions/questions/1238-deleting-builds-from-history

**Comment by micdenny** [comment]
+1

**Comment by TanielianVB** [comment]
+1

**Comment by dmccaffery** [comment]
:+1:

**Comment by cssho** [comment]
:+1:

**Comment by mvmf** [comment]
:+1:

**Comment by joelself** [comment]
:+1:

**Comment by PureKrome** [comment]
![](http://www.picgifs.com/reaction-gifs/reaction-gifs/upvotes/picgifs-upvotes-8935622.gif)

![](http://graphics8.nytimes.com/packages/images/blogs/tmagazine/buzzfeed/06-Upvote.gif)

**Comment by rstarkov** [comment]
:+1:

**Comment by majkinetor** [comment]
+1

**Comment by RadarNyan** [comment]
It's been over a year, any update on this? I don't want to delete and re-create my project once in a while just to keep the build history clean.

Also, it would be nice to have an option to set the maximum history versions so older builds are deleted automatically. If deleting indevidual history build is not an option, at least make it possible to hide some history builds?

**Comment by FeodorFitsner** [comment]
That will be implemented before the end of this year.

**Comment by PureKrome** [comment]
[](http://i.giphy.com/dkGhBWE3SyzXW.gif)

**Comment by FeodorFitsner** [comment]
It's been implemented.

**Comment by daviwil** [comment]
Thanks Feodor!

**Comment by RadarNyan** [comment]
Nice, will there be batch delete feature? @FeodorFitsner 
I mean - it would be such a pain if I have to go click "delete" on every single old build I don't want. I need methods like:
* delete builds between xxxxxx...xxxxxx (commit hash)
* delete any builds before Dec 1, 2016 / between a range of **build time** (not to be confused with commit time)
* delete all builds on "test-1" branch

**Comment by FeodorFitsner** [comment]
Well, it could be part of future API?

**Comment by RadarNyan** [comment]
@FeodorFitsner Looking forward to it. 👍

**Comment by jjpepper** [comment]
I've seen several mentions that this feature has been implemented, but I'm finding it very hard to find out how to use the feature.

**Comment by jjpepper** [comment]
Worked it out.  It's in the REST API but not in the UI for anyone looking and who didn't know about the REST API :-)

**Comment by PureKrome** [comment]
@jjpepper It is there. It's hard to find. When you goto your HISTORY for a build, there is no VISUAL CLUE to delete an _individual item_. E.g.

![image](https://user-images.githubusercontent.com/899878/39132067-4efa0c20-4754-11e8-88e0-0ce3d90100d6.png)

But when you move your mouse OVER the history item, then the `delete` link appears!

![image](https://user-images.githubusercontent.com/899878/39132155-7ffbbf58-4754-11e8-8fef-462253e351ef.png)

NOTE: my mouse cursor isn't displayed in the 2nd image, but it's HOVERING over the line item.

![](https://media.giphy.com/media/12NUbkX6p4xOO4/giphy.gif)

**Comment by ericnewton76** [comment]
This would be much better implemented by just presenting a checkbox in a column next to the builds, to enable batch delete.

**Comment by Walkman100** [comment]
The link on the webpage doesn't work for me for any of my projects in firefox on my desktop. Even with all by modifying extensions disabled (Adblock, HTTPS Everywhere e.t.c.). Works on my phone though, in desktop mode...

built in console has this:
```log
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ app-c9e29ab4d1.min.js:6:5
Disconnected from SignalR app-c9e29ab4d1.min.js:18:20275
SignalR will try to reconnect in 20 seconds app-c9e29ab4d1.min.js:18:20349
SignalR connection is starting... app-c9e29ab4d1.min.js:18:20479
switched account to: Walkman100 app-c9e29ab4d1.min.js:18:16994
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").
SignalR connected via webSockets app-c9e29ab4d1.min.js:18:20878
AccountHub: subscribeAccountEvents(undefined, 13087) app-c9e29ab4d1.min.js:18:21494
ProjectHub: subscribeProjectEvents(null, 643060) app-c9e29ab4d1.min.js:18:21725
TypeError: event.target.hasAttribute is not a function 2 inject.js:59:22
```

that error at the end shown twice (the 2 before inject.js) only shows if I leave the page for a while then do the delete process, not on first load...
