### ISSUE TITLE
Detect if "Re-Build Commit" was clicked?

### ISSUE THREAD

**Issue by JustinGrote** [appveyor/ci#2481]
Hi,

I am wanting to have the following work flow:
1. First Build, completely noninteractive, if it fails, then it fails
2. If I click "Re-Build Commit", it will run again but this time with much more verbose logging, and will have RDP checkpoints along the way that I can RDP in and tweak something for testing if required.

Is there any way in appveyor.yml or in the build itself to detect if a "rebuild" has been requested, and set an environment variable or something to that effect so I can act on it?

**Comment by JustinGrote** [comment]
I also know I can trigger on a failed build, but I don't want every failed build to be sitting out there in RDP-land for an hour waiting for me to delete the RDP file to continue, and I don't want to do a new commit or temporary new branch just to get a verbose build.

**Comment by IlyaFinkelshteyn** [comment]
@JustinGrote you can use `APPVEYOR_RE_BUILD` [environment variable](https://www.appveyor.com/docs/environment-variables/) to detect if build was restarted.
