### ISSUE TITLE
在使用appveyor的时候报如下问题，不知道该怎么配置，情老师指点

### ISSUE THREAD

**Issue by shijianzhong** [appveyor/ci#2488]
Hi，

I'm a beginner in electron
info【
Creating "0.1.1" release for repository "shijianzhong/wx-electron" tag "0.1.1" commit "970401a3fc00e04f791918151fc7b0f8f2f3857f"...OK
No artifacts were published. Make sure you have specified correct artifacts filter.】

**Comment by shijianzhong** [comment]
how to config this artifacts

**Comment by IlyaFinkelshteyn** [comment]
Please check [this part of documentation](https://www.appveyor.com/docs/packaging-artifacts/)
