### ISSUE TITLE
Test summary not shown

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#2490]
I'm trying to set up AppVeyor for Babeljs, see https://github.com/babel/babel/pull/8201.

I noticed that the tests summary isn't shown in the output nor in the log file if downloaded. Locally it works fine though, see the screenshot:

![babel](https://user-images.githubusercontent.com/349621/42381186-04b772a0-8139-11e8-96fd-332c1c54ecd3.jpg)

**Comment by Wasapl** [comment]
I see that the output of the latest build contains  all summary lines from your screenshot: https://ci.appveyor.com/project/babel/babel/build/12/job/ach74uu983wdaecj
Do you need help from our side still?

**Comment by XhmikosR** [comment]
Weird, if you check out the older builds you will the summary is missing. For example https://ci.appveyor.com/project/babel/babel/build/9/job/5pd6paj1r5gufox6

**Comment by XhmikosR** [comment]
This happened for me again with the latest build but after I refreshed the page the summary was shown. Still for some builds I get no output even after refreshing the page, like with https://ci.appveyor.com/project/babel/babel/build/9/job/5pd6paj1r5gufox6

**Comment by XhmikosR** [comment]
@FeodorFitsner could this be the same as #2682 ? My PR still hasn't been merged upstream in babel, but I do recall hitting this numerous times...
