### ISSUE TITLE
Fail in building R packages.

### ISSUE THREAD

**Issue by wenlong-liu** [appveyor/ci#2504]
To whom it may concern,

Thanks for reading this post.  I came up with an issue to run appveyor for R packages. The error statement shows:

> Build started
git clone -q --branch=master https://github.com/wenlong-liu/getFertilizer.git C:\projects\getfertilizer
git checkout -qf bcb1bd8d7a5e569193b8c90300c8f242c0e94c60
Project file "getFertilizer.Rproj" is not a valid MSBuild project file which must be an XML.

This is the setting for appveyor if it is of interest.

https://github.com/wenlong-liu/getFertilizer/blob/master/appveyor.yml

Thank you in advance for your time and efforts.

Wenlong Liu

**Comment by IlyaFinkelshteyn** [comment]
@wenlong-liu seems that your `appveyor.yml` is not being respected. I see that your last good build was a while ago, so maybe OAuth token got “stale”.

Can you please try re-authorize AppVeyor against GitHub? For that open https://ci.appveyor.com/account, revoke GitHub access and authorize GitHub again.

**Comment by wenlong-liu** [comment]
Thanks, it is fixed.  Have a good one.

Wenlong
