### ISSUE TITLE
Mysql57 suddenly fails.

### ISSUE THREAD

**Issue by henrykironde** [appveyor/ci#2505]
Last build to pass: https://ci.appveyor.com/project/henrykironde/retriever/build/1.0.1346
First build to fail https://ci.appveyor.com/project/henrykironde/retriever/build/1.0.1347

For some unknown reason, mysql started failing. I have tried to set the defaults character set names and the collate but the tests are still fail.

The tests have non ASCII characters that were working fine initially, but are failing now.

**Comment by henrykironde** [comment]
This could have caused the change https://github.com/PyMySQL/PyMySQL/pull/692/files

**Comment by IlyaFinkelshteyn** [comment]
@henrykironde thanks for update. Right it must be some external dependency issue. AppVeyor build image `Visual Studio 2015` on which your builds are running, was last time [updated](https://www.appveyor.com/updates/2018/06/03/) more than month ago.

**Comment by henrykironde** [comment]
Thanks for getting back @IlyaFinkelshteyn.

**Comment by henrykironde** [comment]
Solved
