### ISSUE TITLE
.NET Core 2.1.2

### ISSUE THREAD

**Issue by joostvanhassel** [appveyor/ci#2508]
https://www.microsoft.com/net/download/all

Sorry @FeodorFitsner I know you _just_ updated to 2.1.1 (https://github.com/appveyor/ci/issues/2440), but at more or less the same time a new version was released due to a CVE: https://github.com/aspnet/Announcements/issues/310

Edit; another CVE was also fixed in this version: https://github.com/aspnet/Announcements/issues/311

**Comment by FeodorFitsner** [comment]
No problem, will deploy it later this week.

**Comment by bvizureanu** [comment]
@FeodorFitsner, thank you :D
