### ISSUE TITLE
Renaming github teams should propogate on all screens

### ISSUE THREAD

**Issue by vors** [appveyor/ci#252]
I renamed team **xSharePoint owners** to **xSharePoint write** in PowerShell github org.

https://ci.appveyor.com/team screen (old name):
![image](https://cloud.githubusercontent.com/assets/816680/7404527/14a6a752-ee99-11e4-96e7-adbbb67f2839.png)

https://ci.appveyor.com/gitHubTeams screen (new name):
![image](https://cloud.githubusercontent.com/assets/816680/7404544/4d263fb6-ee99-11e4-8129-daf383a278b6.png)

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
