### ISSUE TITLE
Cannot see check results in GitHub

### ISSUE THREAD

**Issue by AlexShemeshWix** [appveyor/ci#2522]
When i do pull request in github i can see build runs in AppVeyor. But when build finishes i cant see results in PR checks in GitHub.
It was working ok last week.
We should i look for trouble?

**Comment by IlyaFinkelshteyn** [comment]
Are you looking for `Checks` or `Statuses`? `Checks` is a relatively new thing and we are just adding support for it right now. `Statuses` are being supported for a long time and if you do not see AppVeyor status, it is most probably authorization problem. Open https://ci.appveyor.com/account, revoke GitHub authorization and authorize GitHub again. Then re-run the build.

**Comment by AlexShemeshWix** [comment]
It never helped.
Now i have second repo that does not receive commit for appveyor builds.
Can you check the logs or something? Do some debuging?
I need solution for this problem ASAP. So please dont send me away with "plug off / plugin in" solutions.
If its such known problem, can you detect it and send me email please?
Thanks

**Comment by IlyaFinkelshteyn** [comment]
@AlexShemeshWix Actually I think I found [the build](https://ci.appveyor.com/project/AlexShemeshWix/stylable/build/1.0.292/job/iv2ga0tvsxeyds74). And yes, here is the error from our logs:

```
HTTP POST to https://api.github.com/repos/wix/stylable/statuses/e63ab84ee32dd4cdb8c423510e7e1a5e7f092b28 returned status code 404: Not Found
Full response body:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}"
```

So let us please check organizational access described above.

**Comment by AlexShemeshWix** [comment]
Hi.
Thanks for response.
Yes we have all the mentioned permissions enabled. 
Ive double checked it my self.After our GitHub services guys went over it and assured me that everything is enabled.
They also assured me that nothing got changed in last few weeks so this auth problem is out of the blue.
The account that it runs under is registered for my username in github. May be this is the problem?
Thanks

**Comment by IlyaFinkelshteyn** [comment]
Can you try to set commit status with [this script](https://gist.github.com/IlyaFinkelshteyn/def2394231afb7f06dcaeaceda1fb1ae#file-set-github-commit-status-ps1) using API token from your account for experiment?

**Comment by AlexShemeshWix** [comment]
I dont think i ever provided github token for AppVeyor. Ive just logged in with my GitHub permissions and i've authorized AppVeyor in GitHub.
By the way on my personal account in github i can only see AppVeyor CI app authorized.
No AppVeyor app and dont see how i can add it if i delete it.

**Comment by AlexShemeshWix** [comment]
Ive tried to remove and add AppVeyor and AppVeyor CI from my personal account list of Authorized apps.
After i log out and login to my Account in AppVeyor it asked me to grant access and added only AppVeyor app. Not AppVeyor CI.

**Comment by AlexShemeshWix** [comment]
And im on MacOS i dont have powershell.

**Comment by AlexShemeshWix** [comment]
BTW im paying for service. Can i have like account manager or something.
Somebody i can link with our github services team to resolve this issue?

**Comment by IlyaFinkelshteyn** [comment]
AppVeyor is a small company of 5 people, and 4 of us are engineers. We do not have account managers or something, and we treat our customers as fellow developers regardless if they pay or not.

Right, GitHub token is not being used by AppVeyor. But when you run script with your token, you authorized at GitHub **as you**, and thus you can have independent (from AppVeyor) test if you have permissions to update statuses.

[PowerShell for Mac](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6) is actually exist. But the same can be easily done with `curl`. If you are not familiar with it, I can re-write this script to use `curl` for you. Or you can use any other tool of your choice to call [this API](https://developer.github.com/v3/repos/statuses/#create-a-status).

`AppVeyor` application is used by `GitHub` login button. `AppVeyor CI` application is used by AppVeyor to access repositories (including setting statuses). You can restore `AppVeyor` application by opening https://ci.appveyor.com/profile, press `Unlink GitHub` and then `Link GitHub account`. However I doubt this will help as this, as I said, is only for `GitHub` login button.

**Comment by AlexShemeshWix** [comment]
Hi 
Thanks for response.
Awesome job for 5 people to bring up service like that.
Please do write curl script for me , i dont want to debug bash scripts while my team has not visibility into CI tests.
Im sure it will work, ive done it many times. I have Travis Ci running in parallel - it has no problem to post statuses. But just to be clear we have checked everything lets do it.
IMHO you needed to ask for GitHub token explicitly during setup of account, instead of doing all this GitHub login trick , its very confusing.
Meanwhile ive send mail to github support to check how things look on their end. Do you want me to add to you to CC?
Thanks

**Comment by Wasapl** [comment]
here is bash version of script Ilya posted above:
```
#!/bin/bash

#GitHub_Token is secure variable

if [[ -n "${APPVEYOR_PULL_REQUEST_NUMBER}" ]]; then
    CONTEXT="continuous-integration/appveyor/pr"
else
    CONTEXT="continuous-integration/appveyor/branch"
fi

BODY="
{
  \"context\": \"${CONTEXT}\",
  \"target_url\": \"https://ci.appveyor.com/project/${APPVEYOR_ACCOUNT_NAME}/${APPVEYOR_PROJECT_SLUG}/build/${APPVEYOR_BUILD_VERSION}\",
  \"state\": \"pending\",
  \"description\": \"Waiting for AppVeyor build to complete\"
}
"

curl -X POST "https://api.github.com/repos/${APPVEYOR_REPO_NAME}/statuses/${APPVEYOR_REPO_COMMIT}" \
 -H "Authorization: token  ${GitHub_Token}" \
 -H "Content-type: application/json" \
 -d "${BODY}"
```
Ilya, I posted it as a comment to your gist for your convenient.

**Comment by AlexShemeshWix** [comment]
Ive tested your script manually on my computer. Something is not working indeed. Ill contact you later on. Please do not close this ticket. We have holidays at Friday and Saturday. And it 6 PM here im not sure i will be able to catch all the people fast.

**Comment by Wasapl** [comment]
@AlexShemeshWix make sure you export GitHub_Token variable with your GitHub token as the value before running this script (let me remind variable names are case sensitive in bash).
Also, you can add `-v` option to curl command to see all communications happen between curl and GitHub.

**Comment by IlyaFinkelshteyn** [comment]
@AlexShemeshWix also can you please send screenshots of all settings we discussed earlier to `team at appveyor.com`? We we missed something in previous conversation, we will spot this on screenshots.

**Comment by AlexShemeshWix** [comment]
Ive double checked with out GitHub services team. I have all the permissions. If i run the script you sent me localy i can see that it sets comment on my commits in github.
Now when i run appveyor build it says. Cannot read last commit information from GitHub repository 
`
 returned status code 401: Unauthorized Full response body: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}`
Ive revoked and granted permissions for Appveyor both on my account and on org level.

**Comment by FeodorFitsner** [comment]
Go to [New project](https://ci.appveyor.com/projects/new) page and authorize GitHub there. It should be fine after that.

**Comment by AlexShemeshWix** [comment]
Thanks for all the help.
The problem was that my git hub account had not enough rights to put commits on repos in different org.

**Comment by FeodorFitsner** [comment]
Thanks for the update.
