### ISSUE TITLE
'System.ValueTuple' version makes Visual Studio 2017 solution build fail

### ISSUE THREAD

**Issue by godrose** [appveyor/ci#2526]
I've consolidated the System.ValueTuple version across all the projects in the solution.
All E2E tests run fine. However the remote build fails to load this assembly.
Attached is the log of the recent build.
The project name is https://ci.appveyor.com/project/LogoFX/samples-specifications
Thanks!
[log-4.txt](https://github.com/appveyor/ci/files/2198273/log-4.txt)

**Comment by IlyaFinkelshteyn** [comment]
Duplicate to https://help.appveyor.com/discussions/problems/15126-systemvaluetuple-version-makes-build-fail-it-runs-fine-locally
