### ISSUE TITLE
Update Ubuntu distribution to a newer one that ships with gcc/g++/c++-7

### ISSUE THREAD

**Issue by CatGirlsAreLife** [appveyor/ci#2539]
As much as I like AppVeyor, when it comes to this build which uses std::experimental::filesystem with stream classes, the currently shipped compiler and standard library makes the compile fail. Attempting to update renders the proper packages unable to be found which then would require installing some ppa’s if the image supports adding apt source repositories. The better option would be to ubgrade the distribution for Ubuntu itself then just use the latest version of gcc/g++/c++ releases as default compiler, and all older versions are then alt installations. That way everyone can be happy.

The affected build is here: 
https://ci.appveyor.com/project/Elskom/newsmake/build/0.1.0a15/job/75uqerh6bw5gpk5x

Edit: Apperently there is a gcc-8 package now. So I guess gcc 8.x is available now?

Also seems this install script should probably work but not sure as I use cmake which configuration to the program named c++.

    install:
    - sh: >-
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    
        sudo apt-get -y update
    
        sudo apt-get -y install gcc-7 g++-7
    
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    
        sudo apt -y autoremove

And I will test if installing gcc-8 and g++-8 works too. Also what about the standard library headers though? Will it automatically update them?

**Comment by CatGirlsAreLife** [comment]
Build with gcc-8:

    Running "build_script" scripts
    Set-Location -Path build
    cmake ..
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Ubuntu")
    {
    c++ --version
    make
    }
    else
    {
    msbuild newsmake.sln /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    }
    Set-Location -Path ..
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/appveyor/projects/newsmake/build
    c++ (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
    Copyright (C) 2018 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    Scanning dependencies of target newsmake
    [ 50%] Building CXX object CMakeFiles/newsmake.dir/main.cpp.o
    [100%] Linking CXX executable newsmake
    [100%] Built target newsmake
    Updating build cache...
    Cache 'build' - Updated
    Build completed

Both 7 and 8 seems to compile fine despite using -r/test instead of -/precise.

**Comment by Wasapl** [comment]
We have preinstalled gcc-7 and gcc-8 along with gcc-5. you may switch between them with `update-alternatives` command:
```
sudo update-alternatives --set gcc /usr/bin/gcc-8
```
