### ISSUE TITLE
Diagnostics Extension deployment in Azure SDK 2.6

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#254]
Discussion: http://help.appveyor.com/discussions/suggestions/662-azure-sdk-26
Blog: http://www.rajinders.com/2015/05/03/azure-sdk-2-6-diagnostics-improvements-for-cloud-services/

**Comment by rajinders** [comment]
Azure SDK 2.5 made big changes to diagnostics. It started using diagnostics extensions to configure diagnostics. This cause big problems. These issues are documented in the comment section of this blob post.
http://blogs.msdn.com/b/kwill/archive/2014/12/02/windows-azure-diagnostics-upgrading-from-azure-sdk-2-4-to-azure-sdk-2-5.aspx?PageIndex=2

We need SDK 2.6 ASAP because we will start testing on Monday and right now our diagnostics deployment does not work due to bugs in SDK 2.5 Powershell.

I will upgrade to SDK 2.6 as soon as I know that SDK 2.6 is available.

**Comment by FeodorFitsner** [comment]
No worries, will deploy it over weekend.



- Feodor

**Comment by rajinders** [comment]
Feodor,

SDK 2.6 made a change that is helpful in deploying diagnostics extension for cloud services.
AppVeyor does this:
msbuild <ccproj_file> /t:Publish /p:PublishDir=<temp_path>
It also uses TargetProfile property to select a specific configuration.

Can you tell me what the value of <temp_path>  is?
I did not find any environment variable so I assume that it is a subdirectory of the 
$env:appveyor_build_folder

sdk 2.6 create cspkg file and service configuration file like it used to do.
In addition to this it create a subdirectory called extensions. It has PaaSDiagnositcs pubconfig.xml file for each role. 
I need to use this file with Set-AzureServiceDiagnosticsExtension to deploy the diagnostics.
I need to run this script after deployment.

Thanks

**Comment by FeodorFitsner** [comment]
Azure SDK 2.6 has been deployed to build workers.

`TargetProfile` is not set when AppVeyor is publishing cloud service. By default, I guess it's "Cloud" however you can choose that by setting `TargetProfile` environment variable with the profile to publish. Anyway, AppVeyor pushes to artifacts **all** publishing profiles from the project, so you can choose required one *later* during deployment.

Regarding calling `Set-AzureServiceDiagnosticsExtension` - when you deploy from "Environments" page or using `Environment` deployment provider there is no way to call PowerShell. However, if you do synchronous deployment during the build using `AzureCS` provider you can call this cmdlet after that.

**Comment by rajinders** [comment]
Thanks for adding SDK 2.6 support so quickly.

There are two ways of deploying the diagnostics extension.
One of them is to deploy/update the cloud service first and then call  Set-AzureServiceDiagnosticsExtension cmdlet for each role. It takes 3-4 minutes per role so this can slow down the deployment considerably.

A better approach is this:
For New Deployments and update deployments we create the diagnostics configuration with the help of pubxml files generated by msbuild.

$workerconfig = New-AzureServiceDiagnosticsExtensionConfig -StorageContext $storageContext -DiagnosticsConfigurationPath $workerrolediagconfig -role “WorkerRole1″
$webroleconfig = New-AzureServiceDiagnosticsExtensionConfig -StorageContext $storageContext -DiagnosticsConfigurationPath $webrolediagconfig -role “WebRole1″

#deploy to the new cloud service with diagnostics
New-AzureDeployment -ServiceName rajsdk26diagdemo -Package $package -Configuration $configuration -Slot $slot -ExtensionConfiguration @($workerconfig,$webconfig)

There is a parameter called -ExtensionConfiguration where we can pass the extension configuration for each role at the same time. This is much faster as compared with calling Set-AzureServiceDiagnosticsExtension individually.

Even while upgrading the deployments 
Set-AzureDeployment also has the same paramter -ExtensionConfiguration where extension configuration for all roles can be passed at once.

Set-AzureDeployment -Upgrade -ServiceName $service_name -Mode Auto -Package $package -Configuration $configuration  -Slot Production -ErrorAction SilentlyContinue -ErrorVariable errorVariable -ExtensionConfiguration @($workerconfig,$webconfig, $hardworkconfig)

In my cloud service there were 3 roles and it took 5 minutes to complete the deployment when I used the -ExtensionConfiguration parameter as compared with 12 minutes for calling Set-AzureServiceDiagnosticsExtension on each role sequentially.

What is the best way to implement it using AppVeyor. Does the existing AzureCS provider have the ability to automatically apply the diagnostics extension during deployment. It has everything it needs and it will perform the best.

Let me know your thoughts about this. I can live with the Set-AzureServiceDiagnosticsExtension during my builds for now and hope that AzureCS will be updated to do this automatically in near future.

Thanks

**Comment by FeodorFitsner** [comment]
OK, I see. Thanks for additional insight. We use .NET API for deploying Azure Cloud Services. I'll take a look if there is a way to pass `ExtensionConfiguration`.

**Comment by rajinders** [comment]
Here is the documentation for rest api that shows how to pass ExtensionConfiguration.

CreateDeployment and passing ExtensionConfiguration
https://msdn.microsoft.com/en-us/library/azure/ee460813.aspx

Update Deployment and passing ExtensionConfiguration
https://msdn.microsoft.com/en-us/library/azure/ee460793.aspx

**Comment by FeodorFitsner** [comment]
Thanks for the links. I see there are corresponding fields in .NET management API too:
https://github.com/Azure/azure-sdk-for-net/blob/9f92179070f8f1429920c25bc82a21767deb95de/src/ComputeManagement/Generated/Models/DeploymentCreateParameters.cs
https://github.com/Azure/azure-sdk-for-net/blob/9f92179070f8f1429920c25bc82a21767deb95de/src/ComputeManagement/Generated/Models/ExtensionConfiguration.cs

This is great! Now we should figure out how does ExtensionConfiguration for diagnostics look like in serialized form.

**Comment by rajinders** [comment]
This is what I use to create the XML configuration from pub XML file.

#create storage context  
$storageContext = New-AzureStorageContext –StorageAccountName $storage_name –StorageAccountKey $key

$workerconfig = New-AzureServiceDiagnosticsExtensionConfig -StorageContext $storageContext -DiagnosticsConfigurationPath $workerrolediagconfig -role "WorkerRole1"
$webroleconfig = New-AzureServiceDiagnosticsExtensionConfig -StorageContext $storageContext -DiagnosticsConfigurationPath $webrolediagconfig -role "WebRole1"

I can execute the script on my PC and capture the request/response that sends the XML. I don't know if that will be helpful. I will have to send you this information in a secure manner.

**Comment by FeodorFitsner** [comment]
That will help for sure. Please send it to team@appveyor.com

**Comment by rajinders** [comment]
I sent you the serialized xml along with input files and powershell script.

**Comment by FeodorFitsner** [comment]
Extension configuration for one of the roles:

```
ProviderNameSpace     : Microsoft.Azure.Diagnostics
Type                  : PaaSDiagnostics
Version               :
CertificateThumbprint :
ThumbprintAlgorithm   :
PublicConfiguration   : <PublicConfig
                        xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">
                          <WadCfg>
                            <DiagnosticMonitorConfiguration overallQuotaInMB="4096">
                              <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter="Error" />
                              <Directories scheduledTransferPeriod="PT1M">
                                <IISLogs containerName="wad-iis-logfiles" />
                                <FailedRequestLogs containerName="wad-failedrequestlogs" />
                              </Directories>
                              <PerformanceCounters scheduledTransferPeriod="PT1M">
                                <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes"
                        sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI
                        Extension Requests/sec" sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes
                        Total/Sec" sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\ASP.NET
                        Applications(__Total__)\Requests/Sec" sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\ASP.NET
                        Applications(__Total__)\Errors Total/Sec" sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Queued"
                        sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Rejected"
                        sampleRate="PT3M" />
                                <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor
                        Time" sampleRate="PT3M" />
                              </PerformanceCounters>
                              <WindowsEventLog scheduledTransferPeriod="PT1M">
                                <DataSource name="Application!*" />
                              </WindowsEventLog>
                              <CrashDumps>
                                <CrashDumpConfiguration processName="WaIISHost.exe" />
                                <CrashDumpConfiguration processName="WaWorkerHost.exe" />
                                <CrashDumpConfiguration processName="w3wp.exe" />
                              </CrashDumps>
                              <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Error" />
                            </DiagnosticMonitorConfiguration>
                          </WadCfg>
                          <StorageAccount>rajcentraldiag</StorageAccount>
                        </PublicConfig>
PrivateConfiguration  : <PrivateConfig
                        xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">
                          <StorageAccount name="diagstgaccountname"
                        key="diagstorage account key"
                        endpoint="https://core.windows.net/" />
                        </PrivateConfig>
Roles                 : {WorkerRole1}
X509Certificate       :
```

**Comment by rajinders** [comment]
I was wondering if we will support for deploying SDK 2.6 diagnostic extension. Here are  my needs:
1. automatically install diagnostics extension for cloud services. (this will be preferred)
2. Help in come up with  steps I need to follow to do this on my own via PowerShell. I know which powershell cmdlets to use. I just need to figure out how to get access to the files generated by the build process that are used as input to the install paas diagnostics extension.


Thanks

**Comment by FeodorFitsner** [comment]
Certainly, this feature is planned for development, but I can't give you an ETA right now.

Regarding CS packages location - you have two options here:

1. Use `$artifacts` hashtable to [get the information about uploaded artifacts](http://www.appveyor.com/docs/packaging-artifacts#getting-information-about-uploaded-artifacts).
2. Replace automatic publishing with your own command and known `PublishDir` property.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
