### ISSUE TITLE
Add tag filtering.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [appveyor/ci#2542]
So, like I know it is possible to commit filter, or even a branch filter but what about a tag filter as well?

For example, you want to build tags, but exclude some tags because you release prereleases on every AppVeyor build and when that you use the version set at the top of the yml with a "v" prefix appended to it.

However I do not see a way to filter those if for example:

- tag name is "v{version}" with the build number of the last job that completed.

The condition above could be a endless loop of packing releases and builds which then is a major problem.

So I think allowing this in the yml would be great:

    tags:
      exclude:
      # exclude all tags that starts with v
      # and contains the letter a in it.
      # ex. tag v1.4.9.8a600 would be
      # excluded from tag build.
      - 'v**a**'
      # also exclude all tags that starts with v
      # and contains the letter b in it.
      # ex. tag v1.4.9.8b800 would be
      # excluded from tag build.
      - 'v**b**'

I think if something like this was added it would be nice, and avoids release deployment loops that can easily be avoided while releasing all commits and feature branch builds to the same repository instead of a dummy one to avoid conflicts like this with AppVeyor currently.

**Comment by IlyaFinkelshteyn** [comment]
To avoid that kind of deployment loops, you can set `tag: $(APPVEYOR_REPO_TAG_NAME)` in GitHub deployment provider settings. So new tag will not be created, existing one will be used instead. \

It is described in GitHub releases [deployment documentation](https://www.appveyor.com/docs/deployment/github/).

Please let us know if this works for you.

**Comment by CatGirlsAreLife** [comment]
I was referring to when I want AppVeyor to work when I:
1. Push a new tag myself.
2. Have AppVeyor create the tag from changes I push (pre-release) to then not create a new build from those tags that the previous AppVeyor build made.

My current workaround that works is then check before_deployment if tag name matches the cases on first message, then call Exit-AppVeyorBuild.

**Comment by IlyaFinkelshteyn** [comment]
Yes, we can do that. Thanks for the idea!

**Comment by IlyaFinkelshteyn** [comment]
Appears to be duplicate to https://github.com/appveyor/ci/issues/486
