### ISSUE TITLE
Unable to start Service Fabric Host Service 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2543]
[Discussion](https://help.appveyor.com/discussions/problems/15323-service-fabric-cluster-cleanup-hanging)

workaround (points to the root cause):

```
- '"C:\Program Files\Docker\Docker\Docker for Windows Installer.exe" uninstall'
- ps: $fabricSdk = Get-WmiObject Win32_Product | ? {$_.Name -match "Microsoft Azure Service Fabric SDK"}; $fabricSdk.Reinstall(10)
```

**Comment by FeodorFitsner** [comment]
Figured our a better, and faster workaround! Add the following line into `appveyor.yml`:

```yaml
install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/fix-service-fabric-docker.ps1'))
```

The script downloads Docker CE and puts its directory to `PATH` so Service Fabric could see "correct" `dockerd.exe` while starting.

**Comment by FeodorFitsner** [comment]
Successful test run: https://ci.appveyor.com/project/appveyor-tests/service-fabric-docker
