### ISSUE TITLE
System variables that "touch" are not parsed properly

### ISSUE THREAD

**Issue by cernoch** [appveyor/ci#2544]
When the [validator](https://ci.appveyor.com/tools/validate-yaml) is asked to parse
```
cache:
  - %HOMEDRIVE%%HOMEPATH%\.m2
```
it gives an error (consistent with a similar line inside my `appveyor.yml`):
> (Line: 2, Col: 5, Idx: 11) - (Line: 2, Col: 6, Idx: 12): While scanning for the next token, find character that cannot start any token.

Is this a bug? I think so, because in a Windows Command Propmpt, I get:
```cmd
echo %HOMEDRIVE%%HOMEPATH%\.m2
C:\Users\[my user name]\.m2
```

**Comment by IlyaFinkelshteyn** [comment]
It is not a bug. Symbols like `%` have special meaning in YAML and lines like this should be wrapped in single quotes, e.g. `- '%HOMEDRIVE%%HOMEPATH%\.m2'`

It is useful to use UI for initial configuration and use `Export YAML` button to get proper syntax.
