### ISSUE TITLE
LLVM 6.0.1

### ISSUE THREAD

**Issue by pavelkryukov** [appveyor/ci#2546]
Hi

LLVM 6.0.1 has been released recently. It has improved version of LLD, which should work with Windows resource files. We would be appreciated if the new version was available on AppVeyor.

Link: http://releases.llvm.org/6.0.1/LLVM-6.0.1-win64.exe

**Comment by FeodorFitsner** [comment]
Make sure LLVM is in `PATH`:

```posh
Add-Path 'C:\Program Files\LLVM\bin'
```
