### ISSUE TITLE
Unable to add project that I collaborate on

### ISSUE THREAD

**Issue by billziss-gh** [appveyor/ci#2548]
I was recently made collaborator of [libfuse/sshfs](https://github.com/libfuse/sshfs) with the explicit purpose of setting up AppVeyor CI for it.

However the libfuse/sshfs project does not appear in my list of projects when I do "New Project" (https://ci.appveyor.com/projects/new). At the same time I can see other projects that I collaborate on.

Can you please advise if it is possible for a GitHub project collaborator to setup CI in this fashion?

Related PR: libfuse/sshfs#138

**Comment by billziss-gh** [comment]
To clarify the account has not changed. I am using the same account as before.

The GitHub `billziss-gh` account was made a collaborator of the libfuse/sshfs project last night. I expected that this would be enough for me to see the libfuse/sshfs project in my "New Project" list. For example, this happens with other projects that are not my own:

<img width="221" alt="screen shot 2018-08-02 at 11 34 33 am" src="https://user-images.githubusercontent.com/15330948/43603565-22a28c54-9648-11e8-8ae9-ef923c6c6486.png">
<img width="663" alt="screen shot 2018-08-02 at 11 35 01 am" src="https://user-images.githubusercontent.com/15330948/43603568-258f0b5e-9648-11e8-8a42-ab55edf74f81.png">

**Comment by billziss-gh** [comment]
And yes, I did sign out and then back in but it dit not make a difference.

**Comment by OwenMcDonnell** [comment]
But i don't see that you are a collaborator on any other accounts. When you see the drop down that i pointed to in the screenshot above, how many accounts are available in that menu?

**Comment by billziss-gh** [comment]
Here is a screenshot from my GitHub Settings|Repositories:

<img width="777" alt="screen shot 2018-08-02 at 2 34 28 pm" src="https://user-images.githubusercontent.com/15330948/43612476-5304d794-9661-11e8-9c5b-d5405f677066.png">

You will notice that I am listed as collaborator of mgeisert/cygfuse and libfuse/sshfs. The mgeisert/cygfuse project is available for me to do "New Project". The libfuse/sshfs project is not.

When I sign out of AppVeyor and I then try to sign back in, I see the following:

<img width="874" alt="screen shot 2018-08-02 at 2 38 49 pm" src="https://user-images.githubusercontent.com/15330948/43612652-d44edeee-9661-11e8-8c13-bbfa9058b0d2.png">

I then click on the "GitHub" button and I am taken to my dashboard. In this process I never saw a dropdown button. (NOTE: I only have one GitHub account.)

<img width="1032" alt="screen shot 2018-08-02 at 2 40 09 pm" src="https://user-images.githubusercontent.com/15330948/43612712-026b15a4-9662-11e8-8291-c2c91321f68f.png">

(The sshfs project listed here is my own fork of libfuse/sshfs at [billziss-gh/sshfs](https://github.com/billziss-gh/sshfs). My problem is that I cannot do "New Project" for libfuse/sshfs; I can of course do "New Project" for billziss-gh/sshfs.)

**Comment by OwenMcDonnell** [comment]
Sorry, I was thinking that you were added as a collaborator to an _AppVeyor_ account. 

In this case, can you navigate to your GitHub user settings and go to **Applications -> Authorized OAuth Apps** and then click on **AppVeyor CI**.

You should see **Organization Access** section. Is 'libfuse' listed and granted permission?

**Comment by billziss-gh** [comment]
@OwenMcDonnell I think you have found the problem. I currently have no access to libfuse. I am only listed as collaborator in the sshfs project. I was under the impression that this was enough for me to setup CI for sshfs.

I will follow up with the libfuse owner. BTW, I see both "AppVeyor" and "AppVeyor CI" listed. Do I need both or only AppVeyor CI?

<img width="750" alt="screen shot 2018-08-02 at 6 01 28 pm" src="https://user-images.githubusercontent.com/15330948/43618604-20149708-967e-11e8-9d49-b3499991623a.png">

Thank you for the help.

**Comment by OwenMcDonnell** [comment]
I don't think you need anything more from libfuse owner though. There should be a 'Grant' button beside that organization label that you can click, is there not?
If so, grant access to both.

**Comment by billziss-gh** [comment]
Unfortunately that is not the case. Here is what I have under "Organization access":

<img width="766" alt="screen shot 2018-08-02 at 10 50 51 pm" src="https://user-images.githubusercontent.com/15330948/43626432-9b73e214-96a6-11e8-80c4-d5c3746caed6.png">

**Comment by billziss-gh** [comment]
Closing this as it has been resolved. After requesting access by pressing the "Request" button (pictured above) I was able to create the project.

Thank you for your support.

**Comment by OwenMcDonnell** [comment]
Great! Thanks for letting us know.
