### ISSUE TITLE
WMF 5

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#255]
http://www.microsoft.com/en-us/download/details.aspx?id=46889

**Comment by am11** [comment]
:+1: 

PS team is also moved to GitHub bringing many [DSC templates](https://github.com/PowerShell/DscResources) to table: https://github.com/powershell/.

**Comment by raghushantha** [comment]
Hi Feodor.

Is this the issue to track availability of 2012R2 image with WMF5.0 on it?

If yes, please let us know when we can expect the image to be available for consumption.

We need the image to integrate Appveyor with https://github.com/PowerShell/PSScriptAnalyzer

Thanks,
Raghu

**Comment by FeodorFitsner** [comment]
Yeah, this is correct issue to track. We are looking to deliver an image with WMF 5 it this week.



- Feodor

**Comment by raghushantha** [comment]
Great! Thanks..

**Comment by FeodorFitsner** [comment]
What version of Visual Studio are you going to use for running tests against WMF 5: VS 2013 or VS 2015?

**Comment by raghushantha** [comment]
2013. 

2015 must also work.

**Comment by FeodorFitsner** [comment]
It's been deployed to `unstable` image. To use it add the following to `appveyor.yml`:

    os: unstable

**Comment by raghushantha** [comment]
Thanks Feodor. I will give it a try.
