### ISSUE TITLE
Bumping time limit for llvmdev

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#2555]
Would it be possible to bump the time limit for [`llvmdev`]( https://ci.appveyor.com/project/conda-forge/llvmdev-feedstock/ ) to 2hrs? Seems to be nearly done at 1hr30mins and then it is [terminated]( https://ci.appveyor.com/project/conda-forge/llvmdev-feedstock/build/1.0.127 ).

**Comment by IlyaFinkelshteyn** [comment]
Made it 110 minutes for now. Please ping us if this appear to be not enough.

**Comment by jakirkham** [comment]
Thank you 😄

**Comment by jakirkham** [comment]
Could this be bumped again please? Looks like it is stopping at 90mins.

**Comment by jakirkham** [comment]
No worries. Thanks for the fix. :)
