### ISSUE TITLE
Linux Nuget deployment should tolerate error 409 (like Windows one)

### ISSUE THREAD

**Issue by hanabi1224** [appveyor/ci#2557]
nuget deploy script works fine on windows, however, it causes build failure on ubuntu image.

Repro:
https://ci.appveyor.com/project/hanabi1224/RuAnnoy/build/job/349jg8xqnc7aaoj7
git: https://github.com/hanabi1224/RuAnnoy

![image](https://user-images.githubusercontent.com/6546635/44064482-0730a8c2-9f1a-11e8-9593-ca34a55ac879.png)

![image](https://user-images.githubusercontent.com/6546635/44064527-50d7000c-9f1a-11e8-9bbd-60cdefb69298.png)

**Comment by OwenMcDonnell** [comment]
I think that nuget package versions cannot be overwritten so you would need to change the assembly version in your `dotnet/Directory.Build.Props` file.

**Comment by hanabi1224** [comment]
@OwenMcDonnell  I don't want to bump package version here, on windows it will skip publishing for the same case, but will cause build failure on ubuntu

![image](https://user-images.githubusercontent.com/6546635/44065750-534c8ac6-9f21-11e8-981f-4d45cc36c21f.png)

**Comment by IlyaFinkelshteyn** [comment]
@hanabi1224 agreed. We need to make Linux Nuget deployment provider to be the same. 

For now you have 2 workarounds:
1. [Patch .csproj](https://www.appveyor.com/docs/build-configuration/#net-core-csproj-files-patching) so nuget package will have the unique version for each build.
or
2. Create Nuget deployment Environment at https://ci.appveyor.com/environments and call it from YAML as described [here](https://www.appveyor.com/docs/deployment/environment/). Environment deployments use the same module as Windows inline deployments so it would tolerate error 409 the same way. [More info](https://www.appveyor.com/docs/deployment/#overview) on difference between Environment and inline deployments. Downside of Environment deployment is that it is asynchronous so failed deployment will not fail the build.

**Comment by hanabi1224** [comment]
@IlyaFinkelshteyn  Thank you so much!

**Comment by hanabi1224** [comment]
@IlyaFinkelshteyn  Kindly ping, any update?
