### ISSUE TITLE
Visual Studio Community 2017 Preview version 15.9.0 Preview 1.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2559]
.NET Core SDK 2.2.100-preview1 installed as well: https://www.microsoft.com/net/download/dotnet-core/2.2

**Comment by ge0rdi** [comment]
Hello.
It seems that 15.8 was just released officially.

https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.8
