### ISSUE TITLE
VS2015 RC

### ISSUE THREAD

**Issue by am11** [appveyor/ci#256]
https://www.visualstudio.com/downloads/visual-studio-2015-downloads-vs#Fragment_downloads

On a related note, there are some duplicate entries in OS list with "Previous" prefix:

![appveyor os list](https://cloud.githubusercontent.com/assets/3840695/7440795/b5a5c7d8-f0d2-11e4-840a-786c3f688724.PNG)

**Comment by FeodorFitsner** [comment]
Those `Previous *` images are those ones from previous deployment: http://www.appveyor.com/updates/2015/04/25

**Comment by FeodorFitsner** [comment]
The new build worker image with Visual Studio 2015 RC has been deployed: http://www.appveyor.com/updates/2015/05/03
