### ISSUE TITLE
Ninja

### ISSUE THREAD

**Issue by DaanDeMeyer** [appveyor/ci#2569]
Ninja is a cross platform C++ build system that is used a lot as an alternative CMake generator on Windows (instead of MSBuild). It'd be great to have it installed on Appveyor images.

https://ninja-build.org/

**Comment by IlyaFinkelshteyn** [comment]
This can can be done on-the-fly and it takes seconds (inspired by [one of our customers YAML](https://github.com/acgetchell/CDT-plusplus/blob/develop/.appveyor.yml#L21-L30)):

```
install:  
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
```

**Comment by DaanDeMeyer** [comment]
I looked at using Chocolatey since it's preinstalled on Appveyor but it's version of Ninja is outdated. I'm using Scoop (alternative to Chocolatey) instead:

```
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop install ninja
```
