### ISSUE TITLE
I as ADMIN would like to see who cancelled build 

### ISSUE THREAD

**Issue by carlosealonso** [appveyor/ci#2575]
Our Team has more than 5 projects and some of our developers are cancelling builds from others developers to get ahead on building FIFO.
As Admin I'd like to see who is cancelling builds.

**Comment by mvofreire** [comment]
Same problem here!

**Comment by IlyaFinkelshteyn** [comment]
We will add events indicating this.

**Comment by IlyaFinkelshteyn** [comment]
@carlosealonso Though it should not take too long to add those events, I think you also might look at project-level [permissions](https://www.appveyor.com/docs/team-setup/#permissions) and [deny all](https://www.appveyor.com/docs/team-setup/#deny-all-approach) approach. With that you restrict people from even seeing projects they should not care about :)

**Comment by carlosealonso** [comment]
Hello @IlyaFinkelshteyn at this point would be difficult to show the user name who cancelled the build? ![image](https://user-images.githubusercontent.com/15216605/44800615-399b0800-ab8d-11e8-81eb-45b4948d6835.png)

**Comment by IlyaFinkelshteyn** [comment]
Yes, change is on its way to production. It will be in `Events` though. And it will stay there even if build was deleted (after being cancelled). Will look like this:
![2018-08-29_09h45_49](https://user-images.githubusercontent.com/3248386/44802446-9cca7180-ab70-11e8-983c-c19e70dcac22.png)

**Comment by IlyaFinkelshteyn** [comment]
Change is deployed

**Comment by carlosealonso** [comment]
Thanks, I've used and it is perfect.
