### ISSUE TITLE
Update Azure VM sizes list 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2576]
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes

**Comment by Damien-Displayr** [comment]
Any update on this? Currently looking to upgrade out build VMs to `Esv3-series` machines, but there is no option to do so. 

Thanks

**Comment by IlyaFinkelshteyn** [comment]
Sorry it took so long, will do it in a couple if weeks. Meanwhile to can set up VM size using our REST API. Please check [this sample](https://gist.github.com/IlyaFinkelshteyn/4d6055e02d6d9e3c962a591628d6556a) and let us know if it works for you.

**Comment by Damien-Displayr** [comment]
That worked. Thanks

**Comment by IlyaFinkelshteyn** [comment]
Fix has been deployed.
