### ISSUE TITLE
Golang 1.11, 1.10.4, 1.9.7

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2580]
Original request: https://help.appveyor.com/discussions/support/38-go-111-stable-in-base-image

**Comment by ncw** [comment]
That link is private :-(  But assuming it says that go1.11 isn't supported it has my support!

**Comment by lvillani** [comment]
Thanks @FeodorFitsner, your hard work and the mere existence of AppVeyor is what makes our open source project possible! 👍
