### ISSUE TITLE
Reset experimental instance of Visual Studio 2015/2017

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2583]
This is required for integration testing of VSIX packages: https://github.com/appveyor/ci/issues/1391

Reset VS 2015:

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit

Reset VS 2017:

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit

**Comment by sharwell** [comment]
❤️ This was at least a 15% improvement in build time for tunnelvisionlabs/MouseFastScroll, in addition to reducing failure rates.

**Comment by FeodorFitsner** [comment]
Glad it worked for you! Thanks for the update.
