### ISSUE TITLE
Add support for .appveyor.yml (with dot)

### ISSUE THREAD

**Issue by filips123** [appveyor/ci#2606]
Currently, AppVeyor only accept `appveyor.yml` configuration file. This is OK, but many other CI systems are using dot-files (hidden files) for configuration (`.codeclimate.yml`, `.coveralls.yml`, `.travis.yml`, `.scrutinizer.yml`...). It will be great if AppVeyor will also accept such files. It should accept `appveyor.yml` (for backward compatibility) and also `.appveyor.yml` (with dot). Documentation should also be updated.

**Comment by xt0rted** [comment]
According to the docs this is already supported https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming

**Comment by filips123** [comment]
Thanks! I missed that part of the docs.
