### ISSUE TITLE
Tool for encrypting/decoding arbitrary files

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#261]
http://www.codeproject.com/Tips/704372/How-to-use-Rijndael-ManagedEncryption-with-Csharp
http://stackoverflow.com/questions/6460793/using-rijndael-to-encrypt-decrypt-files

Encrypt:

    secure-file -encrypt <filename.ext> -secret <keyphrase> -out <filename.ext.enc>

Decrypt:

    secure-file -decrypt <filename.ext.enc> -secret <keyphrase> -out <filename.ext>

**Comment by FeodorFitsner** [comment]
Discussion: http://help.appveyor.com/discussions/suggestions/694-encrypt-files

**Comment by maxkorp** [comment]
Big +1 on this :+1:

**Comment by FeodorFitsner** [comment]
Documented here: http://www.appveyor.com/docs/how-to/secure-files
