### ISSUE TITLE
Git 2.19.0

### ISSUE THREAD

**Issue by xt0rted** [appveyor/ci#2622]
A new version of git was just released https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.19.0.txt

Some more info on this release https://blog.github.com/2018-09-10-highlights-from-git-2-19/

**Comment by XhmikosR** [comment]
Hmm I created #2683 a week ago, not sure which one should be kept.

**Comment by XhmikosR** [comment]
@IlyaFinkelshteyn I'd say close this one since we have #2683

**Comment by IlyaFinkelshteyn** [comment]
OK
