### ISSUE TITLE
mkdir with error /bin/sh: 1: /dev/null: Permission denied on Ubuntu

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#2643]
https://ci.appveyor.com/project/sergey-s-betke/marks/build/2.4.0.508/job/3p8dn5beg4jgg44e

**Comment by Wasapl** [comment]
Can you please elaborate that command fails ?

In my tests redirect to `/dev/null` works fine:
```
$ echo foo >/dev/null
$
```

**Comment by sergey-s-betke** [comment]
` mkdir -p config/subprojectExports ` in project folder.

**Comment by sergey-s-betke** [comment]
This command executed by GNU make, shell - by default.

**Comment by Wasapl** [comment]
Can you increase verbosity of `make`  ?

**Comment by Wasapl** [comment]
Obviously, `mkdir -p config/subprojectExports` in project folder does nothing with `/dev/null`. I'm pretty sure there is something hidden happens under the hood of `make`...

**Comment by sergey-s-betke** [comment]
Can You test this script:

    sudo apt-get install -y imagemagick hp2xx
    mkdir -p config/subprojectExports

`mkdir` **after** installation.

**Comment by sergey-s-betke** [comment]
@Wasapl , You are right: https://ci.appveyor.com/project/sergey-s-betke/marks/build/job/boknelopv9q4cs5s

**Comment by sergey-s-betke** [comment]
@Wasapl, it is my mistake, I catch error:

    HIDE = /dev/null <

    %/$(DIRMARKERFILE):
    	$(MAKETARGETDIR)
    	$(HIDE) $@
