### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by zemasoft** [appveyor/ci#2644]
Could you please change my repo's URL?

Current: https://ci.appveyor.com/project/zemasoft/eset-challenge-evm2-machine
Desired: https://ci.appveyor.com/project/zemasoft/eset-challenge-evm2

**Comment by IlyaFinkelshteyn** [comment]
Just yesterday exposed this with API, you can do it yourself with the script [like this](https://gist.github.com/IlyaFinkelshteyn/8f195010434075074bfa4ee48e3fa347)

**Comment by zemasoft** [comment]
Not exactly the most convenient way but works :-) Thanks.
