### ISSUE TITLE
Encrypted Environment variable fails for Coveralls

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#2647]
I'm trying to test AppVeyor Ubuntu for a repo. I need to integrate coveralls there. If I go to <https://ci.appveyor.com/tools/encrypt>, encrypt my coveralls repo token and add it as `COVERALLS_REPO_TOKEN` in the Environment variables via the Web UI, then it fails with:

```
> foo@0.0.1 coveralls /home/appveyor/projects/foo
> nyc report --reporter=text-lcov | coveralls
/home/appveyor/projects/foo/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

If I use the token unecrypted it works but this isn't a good solution obviously. On the other hand, Travis CI works out of the box without the need to even add manually any token, encrypted or not.

**Comment by IlyaFinkelshteyn** [comment]
What most probably happened is that you double-encrypted the token.  https://ci.appveyor.com/tools/encrypt generates encrypted value which can be safely used in YAML file. If you paste encrypted to UI and then press "lock" button, it is being encrypted second time and during the build it is de-crypted to incorrect value. So paste clear text key to the UI and then press "lock" button.

P.S. This is neither bug or feature request, but rather support question. Please use https://help.appveyor.com for support.

**Comment by XhmikosR** [comment]
No, I didn't double encrypted it.

**Comment by IlyaFinkelshteyn** [comment]
Did you pasted clear text value into UI?

**Comment by XhmikosR** [comment]
That works. But then it's unecrypted, isn't it?

**Comment by IlyaFinkelshteyn** [comment]
If you press "lock" button, it is stored in encrypted form in our database.

**Comment by XhmikosR** [comment]
It only works without the "Lock" button nor encrypted with the tool. Only unecrypted.

**Comment by IlyaFinkelshteyn** [comment]
So you are saying that you enter **clear text** value into UI, press "lock" button and it does not work?

**Comment by XhmikosR** [comment]
I'll try again later or tomorrow and report back but it didn't work for me encrypted either way. Only unecrypted.

**Comment by XhmikosR** [comment]
OK, this time it worked if I just encrypt the token with that lock button.
