### ISSUE TITLE
Repo Rename

### ISSUE THREAD

**Issue by dhermes** [appveyor/ci#2648]
I recently renamed a repo as part of the Chocolatey package review process:

Old Repo: https://github.com/dhermes/python.pypy3
New (Named) Repo: https://github.com/dhermes/chocolatey-pypy3

Can you change the slug on my CI project:

Old name: https://ci.appveyor.com/project/dhermes/python-pypy3
New name: https://ci.appveyor.com/project/dhermes/chocolatey-pypy3

Thank you.

(I filed this based on #999 and #2412, sorry if this is the wrong place.)

**Comment by AraHaan** [comment]
Cant you rename it yourself? I was able too on my end on the settings of the project.

**Comment by dhermes** [comment]
AFAICT there is no way to change the slug, everything else has been updated via `Settings > General > Project name` and `Settings > General > GitHub repository`

**Comment by IlyaFinkelshteyn** [comment]
It is exposed in API now, please check [this](https://gist.github.com/IlyaFinkelshteyn/8f195010434075074bfa4ee48e3fa347) sample script.

**Comment by dhermes** [comment]
Thanks @IlyaFinkelshteyn, I'll convert that to a Python script so I can run it on my Linux machine. Cheers.

**Comment by IlyaFinkelshteyn** [comment]
@dhermes welcome, you can use PowerShell **Core** on Linux by the way :)

**Comment by dhermes** [comment]
Neat!

**Comment by dhermes** [comment]
Finally got around to doing the rename, easy peasy @IlyaFinkelshteyn. Thanks for being awesome!

For future readers, here is a Python version of @IlyaFinkelshteyn's gist: https://gist.github.com/dhermes/a4bc8adaf0048c4c69ddb671c61b10b2
