### ISSUE TITLE
JDK 11

### ISSUE THREAD

**Issue by triceo** [appveyor/ci#2652]
Linux already has it, see #2425.

**Comment by cheenamalhotra** [comment]
Might as well upgrade **Maven 3.3.9** to **3.5.4** for enhanced compatibility

**Comment by FeodorFitsner** [comment]
Sure, issue added: https://github.com/appveyor/ci/issues/2681

**Comment by cheenamalhotra** [comment]
Any timeline when will this be supported?

**Comment by cheenamalhotra** [comment]
As from last updates, looks like updates happen weekly or once in 2 weeks, but for this one its more a month already.. hence I asked.

**Comment by IlyaFinkelshteyn** [comment]
It is not always that often if you look deeper in the updates history. Sorry for not providing you with a specific ETA, we will try to do the update soon.
