### ISSUE TITLE
Problems using test fixtures and temporary folder with python tests

### ISSUE THREAD

**Issue by prsolucoes** [appveyor/ci#2654]
Hi. In my tests im using temporary folder to write/remove data. In my local execution and on TravisCI it is working fine. But on AppVeyor i get a lot of erros:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp07rw3115'
```

I only know that AppVeyor is Windows.
What is wrong of test temporary folder on Windows/AppVeyor?

My temporary dir extension is:

```
testfixtures==6.0.2
```

https://ci.appveyor.com/project/PauloCoutinho/ezored/build/1.0.39/job/0wwfixcpuuyq9gxx

**Comment by IlyaFinkelshteyn** [comment]
@prsolucoes if I understand correctly, [this](https://github.com/ezored/ezored/blob/994037d5da4ed7cc8419fbcdbd116963bea511a9/ezored/models/repository.py#L92) function is responsible for providing temp folder for your tests. What I would recommend is using [tempfile.mkdtemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp).

P.S. This is neither bug or feature request. We try to keep all support at https://help.appveyor.com.
