### ISSUE TITLE
Azure Cosmos DB Emulator 2.1.2

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2662]
[discussion](https://help.appveyor.com/discussions/problems/7950-unable-to-laucnh-cosmosdb-emulator)

**Comment by john-raisingit** [comment]
Is there an estimate for when this will be available?

**Comment by IlyaFinkelshteyn** [comment]
It should be already available, as part of [recent update](https://www.appveyor.com/updates/2018/11/09/). We will close this issue later today.

**Comment by iscottb122** [comment]
Apologies for jumping on the issue, but I can perhaps prevent others having to follow me down the same dark paths with dead ends ...

I think there may still be a problem with starting the emulator as installed on the image. I have a [working build](https://ci.appveyor.com/project/wintoncode/winton-domainmodelling-documentdb/builds/20272748#L81) where I uninstall and reinstall the emulator [as advised](https://help.appveyor.com/discussions/problems/7950-unable-to-laucnh-cosmosdb-emulator#comment_46167980) before attempting to start it. I can [break it](https://ci.appveyor.com/project/wintoncode/winton-domainmodelling-documentdb/builds/20273121#L54) by making a [minimal change](https://github.com/wintoncode/Winton.DomainModelling.DocumentDb/commit/8df3367d54b230cb22d6d4fd298f5c539a5537a3) which attempts to simply start the version already installed.

I can see that the uninstall step actually now removes [two versions](https://ci.appveyor.com/project/wintoncode/winton-domainmodelling-documentdb/builds/20272748#L5) of the emulator, so my best guess would be that multiple installed versions do not play nicely together. This is also consistent with behaviour I have observed in other environments when old versions are not cleaned up properly. So completely removing version 1.20.108.4 from the image (if possible) may fix the problems.

Both of these builds (working, and broken after the minimal change) were run today, within a few minutes of each other. I have also run a number of other builds with different options whilst investigating, and I observe this behaviour consistently regardless of whether I use the emulator executable directly or the installed PowerShell module, other port numbers, etc.

**Comment by IlyaFinkelshteyn** [comment]
@iscottb122 thanks a lot for investigation, very helpful. We filed separate issue to track it: https://github.com/appveyor/ci/issues/2739
