### ISSUE TITLE
`Maximum allowed artifact storage size of 50000 Mb will be exceeded.`

### ISSUE THREAD

**Issue by m-tmatma** [appveyor/ci#2672]
We got the error `Maximum allowed artifact storage size of 50000 Mb will be exceeded.`
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.930/job/6rku237voom83qjw

In https://help.appveyor.com/discussions/problems/10253-maximum-allowed-artifact-storage-size-of-1000-mb-will-be-exceeded, it seems that the size limit can be spread.

Could you spread the size limit?

**Comment by IlyaFinkelshteyn** [comment]
Sure, done!

**Comment by IlyaFinkelshteyn** [comment]
@shawkinsl you should be unblocked now, we increased it for you. We have no solution for custom policies right now, but we are OK to bump the limit if needed.

**Comment by shawkinsl** [comment]
OK, thanks for unblocking us! I'll see if I can get some kind of conditional artifact publishing set up (pointers would be helpful!) but also, +1 vote for conditional or even just configurable retention policies :)

**Comment by zhang-ray** [comment]
Hello, this issue was occurred in these days: https://ci.appveyor.com/project/zhang-ray/easy-voice-call/builds/21230903
