### ISSUE TITLE
After switching to GitHub Apps, status is "Expected — Waiting for status to be reported"

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#2675]
After following the instructions at https://www.appveyor.com/blog/2018/10/02/github-apps-integration/, the "Pull Request" status hangs at "Expected — Waiting for status to be reported". Please see https://github.com/heremaps/oss-review-toolkit/pull/926.

**Comment by sschuberth** [comment]
For some reason it started working now!

**Comment by FeodorFitsner** [comment]
OK, but I guess the issue was there. We found the issue in the code validating webhook requests. The update with the fix is coming later today.

**Comment by sschuberth** [comment]
Also my original issue seems to be back, see https://github.com/heremaps/oss-review-toolkit/pull/928.

**Comment by FeodorFitsner** [comment]
Update coming later today should fix the issue. Sorry for the inconvenience.

**Comment by FeodorFitsner** [comment]
The fix has been deployed. It should be working now.

**Comment by sschuberth** [comment]
I'm not sure whether it's related, but we started seeing builds for `continuous-integration/appveyor/branch` after switching to the GitHub App, whereas we had configured to only build `continuous-integration/appveyor/pr` before, see e.g. https://github.com/heremaps/oss-review-toolkit/pull/929. Is this also a regression?

**Comment by FeodorFitsner** [comment]
@sschuberth we are going to look into that.

**Comment by sschuberth** [comment]
Thanks, but also that problem seem to have disappear by now, see https://github.com/heremaps/oss-review-toolkit/pull/928.

**Comment by FeodorFitsner** [comment]
@sschuberth OK, thanks for the update. Anyway, we are going to do more testing to see it works correctly. Keep me posted if you see that again.

As a side note - we should definitely switch to Checks now as they look much nicer!
