### ISSUE TITLE
skip_branch_with_pr disables builds for master branch, too

### ISSUE THREAD

**Issue by Ede123** [appveyor/ci#2678]
It seems `skip_branch_with_pr` is broken (maybe only on GitLab):
For https://gitlab.com/inkscape/inkscape I [added the entry to the .appveyor.yml](https://gitlab.com/inkscape/inkscape/commit/dd1a6b9a97ba4105fea80300c6ad538cd0fc72fc).  
It seems starting with this commit no new builds whatsoever are scheduled anymore (see https://ci.appveyor.com/project/inkscape/inkscape/history).

How does the "feature branch" detection work?  
There are multiple open pull requests *into* master, but if I did not misunderstand the setting, this should not prevent scheduling builds for pushes to master itself?

**Comment by IlyaFinkelshteyn** [comment]
Can you please check `Events` tab for the project, at the moment when commit to the `master` branch was done, but build did not fired?

**Comment by Ede123** [comment]
The push hook succeeded (I actually re-sent it two times to ensure it was not a temporary issue on AppVeyor's end - no luck though).

**Comment by IlyaFinkelshteyn** [comment]
You mean push hook succeeded on GitLab side, e.g. AppVeyor returned 204, but build was not fired?

**Comment by Ede123** [comment]
Exactly (see the "Details" button above for the full data).

**Comment by IlyaFinkelshteyn** [comment]
OK, so can you please check `Events` tab for the project **on AppVeyor**. We write a warning if we skip commit and state the reason

**Comment by Ede123** [comment]
Ah, yes, I see. There I have three entries like
`
2018-10-05 0:01:53.946
Warning
Commit "dd1a6b9a" of branch "master" skipped as "skip_branch_with_pr: true" is set
`

**Comment by IlyaFinkelshteyn** [comment]
I see, will update on fix soon.

**Comment by IlyaFinkelshteyn** [comment]
Should be fixed now. Problem was that with [API call](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests) to check if PRs with specific source branch exist, we got a positive result when you have a PR from them `master` in different repo (fork). We added a check that also source project id should be the same as id of project where PR created.

**Comment by Ede123** [comment]
Fix confirmed, thank you!
