### ISSUE TITLE
build worker latest update is missing SQLSRV32.dll

### ISSUE THREAD

**Issue by niphlod** [appveyor/ci#268]
Hi,
    taking a look [here](https://ci.appveyor.com/project/niphlod/pydal/build/job/1p57fv0yb9wdc85l) seems that a DLL is missing: it never occured before, so is it due to the latest update or to something else ?

**Comment by FeodorFitsner** [comment]
Have you tried building with previous image (see the last section): http://www.appveyor.com/updates/2015/05/12



- Feodor

**Comment by niphlod** [comment]
I'll try ASAP and get back here.

**Comment by niphlod** [comment]
uhm, it seems that nothing is changed. Is a PR checked with appveyor.yml coming from the PR itself or it needs to be merged into master to pick the ``os: Previous Windows Server 2012 R2`` change ?

**Comment by niphlod** [comment]
BTW: last PR build is [here](https://ci.appveyor.com/project/niphlod/pydal/build/1.0.145/job/w9p644wvd7tj2n99)

**Comment by FeodorFitsner** [comment]
I'm not an expert in Python, but a simple comparison of [last successful](https://ci.appveyor.com/project/niphlod/pydal/build/1.0.142/job/n27xrft90c50ygwr) (on the left) and [failed](https://ci.appveyor.com/project/niphlod/pydal/build/1.0.144/job/1p57fv0yb9wdc85l) (on the right) builds gives some differences:

![image](https://cloud.githubusercontent.com/assets/5041459/7618575/d27ee87e-f967-11e4-86db-86be83bb5759.png)

**Comment by FeodorFitsner** [comment]
Also, [failed build](https://ci.appveyor.com/project/niphlod/pydal/build/1.0.143/job/3xnkj2x3lu5dcsql) was finished at 15:01 PM PST yesterday, but build worker images were updated after 9:00 PM.

**Comment by niphlod** [comment]
uhm, ok, I'll triple check dependencies. 
The thing that strikes me is that from https://github.com/web2py/pydal/pull/187 (working) to https://github.com/web2py/pydal/commit/112c7875a0bc9f156777e62988a41a52cb41392b (failing) the repo hasn't changed: just appveyor.yml and the build being the result from a PR or the merge into master... the following build,https://github.com/web2py/pydal/pull/188 (failing) is just one commit ahead with the ``os`` directive you suggested.
The traceback itself is pretty "on the last layer" of things. %WINDIR%\system32\SQLSRV32.DDL is in any ws2012r2 with SQL Server I got my hands on...

**Comment by FeodorFitsner** [comment]
Another idea - to verify that successful build can be reproduced open [this successful build](https://ci.appveyor.com/project/niphlod/pydal/build/1.0.141) and click "Re-build commit".

**Comment by niphlod** [comment]
rebuilding resulted in the [same error](https://ci.appveyor.com/project/niphlod/pydal/build/job/7hqdlt0oe863l4x6)

**Comment by FeodorFitsner** [comment]
The only reason I can think of is something has changed in external dependencies. I see some package is being downloaded during the build: https://github.com/web2py/pydal/blob/master/setup.py

**Comment by niphlod** [comment]
I'm trying hard to reproduce on my test machine but I don't see any error like it except if I remove the sqlsrv32.dll . "SQL Server Native Client" is usually what puts the dll into system32. Maybe I should hack appveyor.yml to test if that dll is effectively on the server .... thoughts ?

**Comment by FeodorFitsner** [comment]
You can add `dir c:\windows\system32\sql*` to make sure DLL is there.

**Comment by niphlod** [comment]
damn. it's tox's fault. until now it never gave me any problems, so it was the last thing I inspected. @FeodorFitsner, please accept my humble apologies. Keep up with the good work: I'm REALLY, REALLY happy that a service such as appveyor exists and that the support is so immediate.

**Comment by FeodorFitsner** [comment]
He he :) no problem! When testing *with* external dependencies you are testing those dependencies as well ;)
