### ISSUE TITLE
Build starting with # returns 404 error

### ISSUE THREAD

**Issue by dmex** [appveyor/ci#2680]
Hello,

Build versions starting with a # (hash/pound) return a 404 not found when trying to view the build log on Appveyor.

We're using "#{build}" for the build version format and after compilation our build script calls "appveyor UpdateBuild -Version" with the actual version number. This works great when builds succeed but when builds fail you can't access the build log. 

For example:
https://ci.appveyor.com/project/processhacker/processhacker/build/#209
https://ci.appveyor.com/project/processhacker/processhacker/history

**Comment by FeodorFitsner** [comment]
Will take a look, thanks for reporting that.

**Comment by FeodorFitsner** [comment]
The issue has been fixed by replacing version-based links with new build permalinks.

**Comment by dmex** [comment]
@FeodorFitsner 

Thanks for fixing issue and the very quick response ❤
