### ISSUE TITLE
Deploy Qt to default and Pro images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#269]
http://help.appveyor.com/discussions/suggestions/419
http://download.qt.io/official_releases/online_installers/
http://help.appveyor.com/discussions/questions/1298-no-performance-improvement-since-ive-bought-pro-foss-plan

**Comment by FeodorFitsner** [comment]
Online installer: http://download.qt.io/official_releases/online_installers/

Qt root folder: `C:\Qt`

Installed components:
- Qt 5.4: `C:\Qt\5.4`
  - MinGW 4.9.1 (32 bit) OpenGL: `C:\Qt\5.4\mingw491_32`
  - msvc2013 32-bit OpenGL: `C:\Qt\5.4\msvc2013_64_opengl`
  - msvc2013 64-bit OpenGL: `C:\Qt\5.4\msvc2013_opengl`
- Qt 5.3: `C:\Qt\5.4`
  - MinGW 4.8.2 (32 bit): `C:\Qt\5.3\mingw482_32`
  - msvc2013 32-bit OpenGL: `C:\Qt\5.3\msvc2013_64_opengl`
  - msvc2013 64-bit OpenGL: `C:\Qt\5.3\msvc2013_opengl`
- Tools
  - MinGW 4.8.2: `C:\Qt\Tools\mingw482_32`
  - MinGW 4.9.1: `C:\Qt\Tools\mingw491_32`

**Comment by rasky** [comment]
@FeodorFitsner thanks for this. Is it already online?

**Comment by FeodorFitsner** [comment]
Nope, it's not yet. Will online later this week - we'll send an announcement.
