### ISSUE TITLE
Nuget publish does not include xml documentation files.

### ISSUE THREAD

**Issue by AraHaan** [appveyor/ci#2695]
Please provide a repro. Ideally, AppVeyor build of public repository. Provide build configuration in YAML format. If repro does not fit into single build scenario, please provide step-by-step instructions.
If you are not sure that you found a bug, please describe your problem at https://help.appveyor.com/discussions/problems.
Repository: https://github.com/AraHaan/XmlAbstraction/
Any release build that deploys to my nuget provider will work.
Config: https://github.com/AraHaan/XmlAbstraction/blob/master/appveyor.yml#L13-L15

On these lines of the configuration when it goes to package the nuget packages, it seems your nuget packers aqre excluding the documentation xml files, locally ``dotnet pack`` and Visual Studio packing works fine for me. I think what appveyor should do is check if the csproj file is of the netstandard / netcore format and run ``dotnet pack`` to pack the nuget packages when those options are checked.

That should hopefully fix my issue where my nuget published package does not show any documentation when the user references the package using ``PackageReference``.

**Comment by IlyaFinkelshteyn** [comment]
>I think what appveyor should do is check if the csproj file is of the netstandard / netcore format and run dotnet pack to pack the nuget packages when those options are checked.

This is exactly what AppVeyor does and you can see it in the [build log](https://ci.appveyor.com/project/AraHaan/xmlabstraction/build/1.1.0.0-alpha68#L136). I do not see xml documentation files in your repo however.

**Comment by AraHaan** [comment]
Odd, the build creates them on my end when I build using the Visual Studio IDE as the xml documentations are generated from the C# source files.

**Comment by IlyaFinkelshteyn** [comment]
Try adding `GenerateDocumentationFile` to your `.csproj` as described [here](https://stackoverflow.com/questions/48663444/how-to-include-xml-documentation-file-in-nuget-package-built-from-a-project-file).

**Comment by IlyaFinkelshteyn** [comment]
Also it says to add `GenerateDocumentationFile`. I believe that it is worth to try. And ensure it works with command line (not VS) OK locally too.

**Comment by AraHaan** [comment]
Alright, also it seems that element works in the VS IDE as well. At least I got this resolved.
