### ISSUE TITLE
After switching to GitHub Apps, "skip_branch_with_pr" is not taken into account anymore

### ISSUE THREAD

**Issue by sschuberth** [appveyor/ci#2696]
As a follow-up to my comment over [here](https://github.com/appveyor/ci/issues/2675#issuecomment-427290472), I'm still seeing two builds being triggered for each PR after the switch to GitHub Apps despite `skip_branch_with_pr` being set to `true`, see e.g. https://github.com/heremaps/oss-review-toolkit/pull/968.

**Comment by IlyaFinkelshteyn** [comment]
Sorry for some delay with reply. I think that you are talking about [this](https://ci.appveyor.com/project/heremaps/oss-review-toolkit/build/1.0.3800/job/a5r1uq0sam4evaw0) feature branch build.

This is normal behavior and behaves the same way when you use OAuth. When you create a PR, branch build first created and initial commit is created in the feature branch (`maven-svn` in this case). Immediately `push` event webhook to AppVeyor is being sent and at that moment AppVeyor has no knowledge about any PR (when it calls GitHub API). And then PR is being created and `pull_request` event webhook is sent.

All subsequent changes to the `maven-svn`  should be skipped while open PR actually exist. 

If you do not want to any `push` commits to be built, you can check `Do not build on "Push" events` UI-only setting on General tab.

I am closing this issue. Please let me know if you think it should stay open.
