### ISSUE TITLE
Gitea integration

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2704]
https://try.gitea.io/api/swagger#/repository/repoCreateKey

**Comment by NepPure** [comment]
😆This is exactly what I want!
Does on-premise version consider a plugin mechanism? Community may can help improve such needs without core code. @FeodorFitsner 
Thanks!

**Comment by FeodorFitsner** [comment]
We'll do 1-st class integration with Gitea/Gogs. The idea with plugins sounds great.

**Comment by FeodorFitsner** [comment]
Gitea known issues:

* Gitea push webhook payload does not contain the information about added/removed/modified files. As a result filtering in appveyor.yml based on files won't be supported.

**Comment by FeodorFitsner** [comment]
Gogs support moved to a separate issue as its API is different from Gitea: https://github.com/appveyor/ci/issues/3077

**Comment by FeodorFitsner** [comment]
Submit PR with AppVeyor listing in CI/CD section:

* https://docs.gitea.io/en-us/ci-cd/
* https://github.com/go-gitea/gitea/blob/master/docs/content/doc/advanced/ci-cd.en-us.md
