### ISSUE TITLE
OpenSSL 1.1.1

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2706]
While reviewing [Windows pre-installed software](https://www.appveyor.com/docs/windows-images-software/), I noticed that both OpenSSL 1.0.2 and 1.1.0 are installed.

I believe 1.1.1 has been released and is available.  It would be helpful to add 1.1.1 along with keeping 1.0.2 & 1.1.0, as 1.0.2 is an LTS version with security fixes thru 2019-12-31 (See https://www.openssl.org/source/ for info).

Reminder #2571

Thanks, Greg

**Comment by FeodorFitsner** [comment]
OpenSSL 1.1.1 will be installed in the following directories:

```
C:\OpenSSL-v111-Win32
C:\OpenSSL-v111-Win64
```
