### ISSUE TITLE
Option to follow log

### ISSUE THREAD

**Issue by double-beep** [appveyor/ci#2713]
Hello,
Can you please add an option to follow log?

Thanks a lot
@double-beep

**Comment by IlyaFinkelshteyn** [comment]
@double-beep can you please elaborate the scenario in more details?

**Comment by double-beep** [comment]
A button like this:
```html
<button>Follow log</button>
```
in pages https://ci.appveyor.com/project/*/*/builds/19862096/job/***********
or https://ci.appveyor.com/project/*/*/builds/***********
The button should always "scroll into view" the user to the latest output when it is pressed.

Hope this helps!
@double-beep

**Comment by IlyaFinkelshteyn** [comment]
I see. By the way [Webpage Auto Scrolldown](https://chrome.google.com/webstore/detail/webpage-auto-scrolldown/aegbbdpcnbnddiipcggakoglcmlgejem/related?hl=en) or similar extension does the job.

**Comment by double-beep** [comment]
It would be better for everyone to implement this.

**Comment by tooomm** [comment]
Same as https://github.com/appveyor/ci/issues/2638

**Comment by double-beep** [comment]
@tooomm yes it is.

@IlyaFinkelshteyn I found https://stackoverflow.com/questions/8773921/how-to-automatically-scroll-down-a-html-page and https://stackoverflow.com/questions/8773405/how-to-auto-scroll-to-target-div-with-jquery/8773563#8773563 about this topic. Is it going o be implemented?

**Comment by IlyaFinkelshteyn** [comment]
It should be fixed now

**Comment by Danny-UKDM** [comment]
Any word on this? Was just thinking that this would be a great feature of the console view and came across this!
