### ISSUE TITLE
Update 7zip from 16.04 to 18.05

### ISSUE THREAD

**Issue by justalemon** [appveyor/ci#2720]
I recently compared the versions of 7zip from my local machine and the VS 2017 AppVeyor image with the following result:

On AppVeyor:
```
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
```
On my local machine:
```
7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
```

If I'm not wrong, there have been 6 updates since 16.04 without breaking changes and is safe to update. For more information check the 7zip changelog [here](https://www.7-zip.org/history.txt).

**Comment by FeodorFitsner** [comment]
Thanks! I'm closing this issue in favor of: https://github.com/appveyor/ci/issues/2472
