### ISSUE TITLE
VC++ 2017 version 15.5 v14.12 toolset on VS 2017 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2724]
Original issue: https://help.appveyor.com/discussions/problems/17817-installing-vc-2017-version-155-v1412-toolset

**Comment by chrisdembia** [comment]
Awesome! Thank you.

**Comment by chrisdembia** [comment]
Do you have an estimate for when the next image update will be?

**Comment by FeodorFitsner** [comment]
Working on the image. This weekend or early next week should be in production.

**Comment by chrisdembia** [comment]
Excellent. Thank you.

**Comment by chrisdembia** [comment]
Thank you!
