### ISSUE TITLE
Use appveyor-retry to fetch git repository and cache

### ISSUE THREAD

**Issue by ken2812221** [appveyor/ci#2728]
The cache can't be fetched by the virtual machine occasionally due to [this](https://status.appveyor.com/incidents/2lmgmh6jghld) issue. If the VM could retry fetch cache, that would be better. That could save a lot of clicking cancel and restart and human monitoring time.

**Comment by FeodorFitsner** [comment]
Good suggestion, will look into that.

**Comment by josch** [comment]
Related: https://help.appveyor.com/discussions/problems/18487-please-do-not-overwrite-the-cache-if-it-failed-to-download

I retrying still fails, the build should be stopped. It doesn't make sense to continue building in an environment where errors already have happened.
