### ISSUE TITLE
`appveyor_repo_tag` does not work on Ubuntu images

### ISSUE THREAD

**Issue by chipitsine** [appveyor/ci#2736]
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.appveyor.yml#L74-L80

repro

https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/builds/20106073

(windows artefacts are uploaded, ubuntu artefacts are not)

**Comment by IlyaFinkelshteyn** [comment]
@chipitsine:

- artifact upload is not deployment. In this build each of 4 jobs uploaded artifacts to AppVeyor artifact storage which you can see on `Artifacts` tab for each job. Deployment did not happen during any of the job.

- [Deployment section](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.appveyor.yml#L74-L80) you refer to, does not exist in `.appveyor.yml` file in [commit](https://github.com/SoftEtherVPN/SoftEtherVPN/commit/da518914c1b5c7d010e8931e7105dff658d5880c) being built.  You can check that by clicking `Browse files` in that commit. Indeed I see that you added GitHub deployment section to `master` [day later](https://github.com/SoftEtherVPN/SoftEtherVPN/commit/aa9effbf4ead3c1778c966768ff20c0a20becfb1#diff-11c909939117928998b102a1fff7d363) after this commit. Then you probably tagged the commit which does not have GitHub deployment section. This is the reason GitHub deployment did not fired at all.

Please feel free to ask any additional questions, this can be confusing :)

**Comment by chipitsine** [comment]
@IlyaFinkelshteyn  thank you for your feedback. I will provide debug tomorrow

**Comment by chipitsine** [comment]
hello,

sorry for delay.

let me explain what I did (and what I expected to get)

https://github.com/chipitsine/SoftEtherVPN - my own fork of SE VPN.
so, I did tag there (you can see it in commit history)


I expected that .appveyor.yml should "deploy" release (and include build artifacts as nothing else is specified)

artifact were build and stored at app veyor:

https://ci.appveyor.com/project/chipitsine/softethervpn/builds/20318696

but "deploy" was not triggered. I've no idea why

**Comment by IlyaFinkelshteyn** [comment]
No worries. Deployment did not start because you specify to [deploy only on tags](https://github.com/chipitsine/SoftEtherVPN/blob/master/.appveyor.yml#L80), but this is not a tagged commit. If you create  atag in git or in GitHub UI, AppVeyor sees this information in incoming webhook and sets `appveyor_repo_tag` environment variable to `true`. If you need it to deploy from non-tagged builds, simple remove that settings from your YAML.

**Comment by chipitsine** [comment]
to save time, I added you as collaborator to https://github.com/chipitsine/Softethervpn
after you approve, I'll give you admin rights

**Comment by chipitsine** [comment]
seems that app veyor did not enable tag builds when it was added

![Uploading Screenshot from 2018-11-17 14-06-29.png…]()

**Comment by chipitsine** [comment]
![screenshot from 2018-11-17 14-06-29](https://user-images.githubusercontent.com/2217296/48659479-9cf15380-ea73-11e8-8a82-0d5123ac49e8.png)

**Comment by chipitsine** [comment]
ping

**Comment by IlyaFinkelshteyn** [comment]
Environment variable names are case-sensitive on Linux platform. We even [updated](https://github.com/appveyor/website/commit/6c57d93b6ca608572fcdd4bfb8034799a38520a2#diff-7b4070e67f168d73c7681c3c445b6137) samples [here](https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only) to eliminate confusion like this.
