### ISSUE TITLE
Azure Cosmos DB Emulator 2.1.2 does not start properly

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2739]
Temporary workaround is using `Previous` build worker image.

Workaround: https://github.com/appveyor/ci/issues/2662#issuecomment-438401597

**Comment by IlyaFinkelshteyn** [comment]
Fixed for `Visual Studio 2017`. Still need to be done for ` Visual Studio 2017 Preview` and `Visual Studio 2015` (`Previous Visual Studio 2015` still OK).

**Comment by FeodorFitsner** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/2843
