### ISSUE TITLE
Visual Studio 2017 15.9.4

### ISSUE THREAD

**Issue by matt77hias** [appveyor/ci#2741]

**Comment by xt0rted** [comment]
15.9.2 was released today https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.9.2

**Comment by xt0rted** [comment]
15.9.3 was released today https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.9.3

**Comment by IlyaFinkelshteyn** [comment]
New `Visual Studio 2017` image has been deployed.
