### ISSUE TITLE
CMake error when linking with Clang-cl (lld-link); requires vcpkg update

### ISSUE THREAD

**Issue by Farwaykorse** [appveyor/ci#2742]
When building with CMake and Clang-cl.
CMake reports an error while linking. See: [AppVeyor build of MS/GSL](https://ci.appveyor.com/project/neilmacintosh/gsl/builds/20279665/job/qn4157fquq0sjau4)
```
 The C++ compiler "C:\Program Files\LLVM\bin\clang-cl.exe" is not able to
  compile a simple test program.
...
lld-link.exe : error : could not open C:\Tools\vcpkg\installed\x86-windows\debug\lib\*.lib: no such file or directory
```

This is a known issue with the installed vcpkg version.
Issue: https://github.com/Microsoft/vcpkg/issues/4359
Fixed in: https://github.com/Microsoft/vcpkg/pull/4573

Temporary workaround:
Pull the latest vcpkg sources during the install phase. See: [documentation](https://www.appveyor.com/docs/lang/cpp/#vc-packaging-tool). (Bootstrapping vcpkg is not needed.)
````
install:
  - cd C:\Tools\vcpkg
  - git pull
  - cd %APPVEYOR_BUILD_FOLDER%
````

**Comment by IlyaFinkelshteyn** [comment]
@Farwaykorse thank you for the report. As part of https://github.com/appveyor/ci/issues/2733 we will update vspkg during next build worker image update.

**Comment by XVilka** [comment]
Isn't this one fixed already?

**Comment by IlyaFinkelshteyn** [comment]
Yes, it must be, closing, Thanks @XVilka
