### ISSUE TITLE
VS VM's - intermittent lack of resources (slow builds)

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2743]
Relatively recently, it seems that build times vary by the time of day, sometimes by a factor of two.

I've got a CRON job running at the hours of 3,9,16.  03:00 normally runs fine, 09:00 was intermittently worse, and 16:00 was often the longest.  Today, 09:00 ran slowly, and still having issues.

Testing is running parallel (and random).  The factor of two time differences are looking at build time, and hence aren't affected by testing.  Also, my testing has timeouts, and probably 95% of previous builds have been fine.  Now, it seems I need to increase the timeouts.

I can't complain, as I'm running an OSS account, but I thought I'd point it out...

Thanks, Greg

**Comment by IlyaFinkelshteyn** [comment]
We just scaled out our resources, this should be consistent now.

**Comment by MSP-Greg** [comment]
Occasionally mid day builds take longer, but I no longer have any issues with this.  Closing.
