### ISSUE TITLE
vcpkg on AppVeyor fails to find CONTROL file for fribidi

### ISSUE THREAD

**Issue by tobbi** [appveyor/ci#2749]
vcpkg on AppVeyor fails to find fribidi despite it being present in the vcpkg repository. 

Builds:
https://ci.appveyor.com/project/supertux/supertux-9ml4d/builds/20365833 (32 Bit)
https://ci.appveyor.com/project/supertux/supertux-o8t59/builds/20365835 (64 Bit)

appveyor.yml files:
https://github.com/SuperTux/supertux/blob/master/appveyor.yml
https://github.com/SuperTux/supertux/blob/master/appveyor64.yml

AppVeyor fails to find a control file for fribidi when CLEARLY there is one in the vcpkg repo as of this PR https://github.com/Microsoft/vcpkg/pull/4627

Are the port definitions outdated?

**Comment by IlyaFinkelshteyn** [comment]
Can you please update vcpkg at `install` stage as described [here](https://www.appveyor.com/docs/lang/cpp/#vc-packaging-tool). If works, please wait for next [Windows build worker image update](https://www.appveyor.com/updates/) (subscribe to "Technical updates" at https://ci.appveyor.com/notifications to get notified). After next image update remove the workaround.

**Comment by tobbi** [comment]
That seems to have worked. Thanks!
