### ISSUE TITLE
Does not render or hide ANSI escape sequences for some output from Ginkgo Go testing framework

### ISSUE THREAD

**Issue by douglaswth** [appveyor/ci#275]
On my terminal the Ginkgo Go testing framework outputs some red text blocks:

![image](https://cloud.githubusercontent.com/assets/77890/7693527/84ced08e-fd87-11e4-8949-6cae062a4101.png)

However this is not the case in AppVeyor, where the other colors show up fine, but those red things come through without being rendered as red or hidden:

```
[91m• Failure [0.017 seconds]
Yolo Octo Wookie
C:/projects/go/src/github.com/douglaswth/yolo-octo-wookie/yolo-octo-wookie_suite_test.go:21
  The Universe
  C:/projects/go/src/github.com/douglaswth/yolo-octo-wookie/yolo-octo-wookie_suite_test.go:20
    [91mshould be okay [It]
    C:/projects/go/src/github.com/douglaswth/yolo-octo-wookie/yolo-octo-wookie_suite_test.go:19
 
    [91mExpected
        <bool>: true
    to equal
        <bool>: false
 
    C:/projects/go/src/github.com/douglaswth/yolo-octo-wookie/yolo-octo-wookie_suite_test.go:18
------------------------------
 
 
[91mSummarizing 1 Failure:
 
[91m[Fail] Yolo Octo Wookie The Universe [91m[It] should be okay 
C:/projects/go/src/github.com/douglaswth/yolo-octo-wookie/yolo-octo-wookie_suite_test.go:18
 
[91mRan 1 of 1 Specs in 0.017 seconds
[91mFAIL! -- 0 Passed | [91m1 Failed | 0 Pending | 0 Skipped --- FAIL: TestYoloOctoWookie (0.02s)
```

You can see at https://ci.appveyor.com/project/douglaswth/yolo-octo-wookie/build/1.0.64#L141. On Travis CI, it at least doesn't show these escape sequences even though it does not show the colors https://travis-ci.org/douglaswth/yolo-octo-wookie/builds/63094334#L147.

**Comment by FeodorFitsner** [comment]
`91` is like "bright" (high intensity) red: http://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by FeodorFitsner** [comment]
A fix has been deployed.
