### ISSUE TITLE
Mingw-w64 8.1.0

### ISSUE THREAD

**Issue by trexinc** [appveyor/ci#2754]
Mingw-w64 8.1.0 was released in May. could you please add it to the Visual Studio 2017 image?

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/

Thank you!

**Comment by FeodorFitsner** [comment]
This will be installed into `C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0`.

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)

**Comment by stefantalpalaru** [comment]
Please add a 32-bit version of 8.1.0 (or newer).

I'm trying to get reproducible builds, but the linker in 6.3.0 doesn't seem to do the right thing with "--no-insert-timestamp". Might be this old issue: https://www.bountysource.com/issues/37990498-mingw-ld-no-insert-timestamp-does-not-insert-a-zero-value-for-the-timestamp

I also think this table is missing a green dot for most Mingw-w64 version on the "Visual Studio 2017" image: https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin

**Comment by EwoutH** [comment]
Can we also get Mingw-w64 8.1.0 on the Visual Studio 2019 image?

**Comment by FeodorFitsner** [comment]
https://github.com/appveyor/ci/issues/3312
