### ISSUE TITLE
Return code of deploy hooks seems to be completely ignored

### ISSUE THREAD

**Issue by paulsavoie** [appveyor/ci#2755]
When calling a deployment web hook and the web hook returns a 400 or 500 HTTP error code, the deployment is still considered successful. Please fail the deployment in such cases and display an according error message.

I tested it by setting http://httpstat.us/400 and http://httpstat.us/500 as deploy hook URLs and the deployment step just says

    Deploying using Webhook provider
    Calling webhook http://httpstat.us/500...OK
    Build success

Example build log: https://ci.appveyor.com/project/PaulSavoie/nugetdummylogger-swgqd/builds/20469366

**Comment by paulsavoie** [comment]
closed because I opened an issue on the appveyor forum: https://help.appveyor.com/discussions/problems/18299-return-code-of-deploy-hooks-seems-to-be-completely-ignored

**Comment by IlyaFinkelshteyn** [comment]
@paulsavoie lets keep it open here, as forum is for support questions, while we are trying to keep bugs and feature requests on GitHub. This seems like a bug, looking into it.

**Comment by paulsavoie** [comment]
Hello @IlyaFinkelshteyn: Did you already find something concerning this bug? Cheers

**Comment by IlyaFinkelshteyn** [comment]
Sorry, fix is on its way. will update as deployed.

**Comment by paulsavoie** [comment]
Hello @IlyaFinkelshteyn: Sorry to bother you again, just wanted to ask if there is an update concerning this issue? Thanks!

**Comment by IlyaFinkelshteyn** [comment]
It is me who has to apologize... Will be deployed during a week.

**Comment by paulsavoie** [comment]
Hello @IlyaFinkelshteyn, any updates...?

**Comment by IlyaFinkelshteyn** [comment]
@paulsavoie fix has been deployed. Sorry for delay.

**Comment by paulsavoie** [comment]
Thanks! Just verified it myself. Would be really helpful to also print the body for debugging reasons (to figure out what went wrong). But I guess that's a new issue!

**Comment by IlyaFinkelshteyn** [comment]
Body of requests? People can have secrets there, which can be dencrypted from secure variables and sent with webhook. It is unsafe to print the body, especially for public projects...

**Comment by paulsavoie** [comment]
I believe it is up to the developers of Webhooks to not leak any secrets in their error messages when something goes wrong (it would be really bad practice to do so). In my opinion, it is best practice to include details about what went wrong (e.g. when returning 400 bad request) in the body - otherwise the calling service cannot possibly know how to fix the request.

**Comment by drauch** [comment]
I also don't understand why a web hook developer should return a secret as part of the response's body. The secret is normally sent by the web hook CALLER to identify himself.

**Comment by fschmied** [comment]
> Body of requests? People can have secrets there, which can be dencrypted from secure variables and sent with webhook. It is unsafe to print the body, especially for public projects...

@IlyaFinkelshteyn I think this was a misunderstanding and @paulsavoie meant the body of the error _response_, not the request.

I, too, would consider it really important for debugging to get this error information. When I'm setting up a deploy hook and it fails with 400, I really need to know what went wrong so I can fix my mistake. Should I create a dedicated issue for this?

**Comment by IlyaFinkelshteyn** [comment]
Understood. Sorry for the silence, we were very busy with delivering [AppVeyor Server](https://www.appveyor.com/blog/2019/05/01/appveyor-server-available-for-download/). Do you guys need full body of error response for **Inline** or **Environment** deployments or both (difference [here](https://www.appveyor.com/docs/deployment/#overview))?

**Comment by fschmied** [comment]
Wow, congrats for AppVeyor Server!

> Do you guys need full body of error response for Inline or Environment deployments or both (difference here)?

Well, currently we're using inline deployments. However, I guess being able to see the error output would be very useful for people using environment deployments, too.
