### ISSUE TITLE
github releases are not uploaded

### ISSUE THREAD

**Issue by chipitsine** [appveyor/ci#2756]
hi

I created personal token

![screenshot from 2018-11-28 15-52-10](https://user-images.githubusercontent.com/2217296/49147182-c6d53080-f325-11e8-8db6-c2d4941948f8.png)

also, I encrypted it using AppVeyor web interface

the same deploy settings exists in both
https://github.com/SoftetherVPN/SoftetherVPN (master)
https://github.com/chipitsine/SoftEtherVPN (fork)

however, I can upload releases in my own fork, and I cannot upload releases in main repo.

bad (SoftetherVPN/SoftetherVPN)

https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/builds/20612187/job/pgb4mw1v4q6o90e6

good (chipitsine/SoftetherVPN)

https://ci.appveyor.com/project/chipitsine/softethervpn/build/job/76vpk7va9og9sk79

can you help me in investigation ?

**Comment by IlyaFinkelshteyn** [comment]
Sorry for repeating the same again, but this is not a bug report or feature request. Please post support questions at https://help.appveyor.com next time.

This is expected behavior.  Each AppVeyor account has its own encryption key. If you want to encrypt the token so it was available for build under `SoftEtherVPN` account, you have to switch to that account (drop down in the upper left screen corner) and then encrypt.

**Comment by chipitsine** [comment]
it is not clear from documentation. actually, I can suggest the following

1) some documentation improvement
2) better error handling (i.e. the was provided encrypted token, which could not be decrypted. something like "decryption failed" would be much better)

**Comment by chipitsine** [comment]
I played a bit with `auth_token`
I could not find a way how to keep .appveyor.yml consistent across forks (we want to do merge request from forks and preserve auth_token)

**Comment by IlyaFinkelshteyn** [comment]
Maybe you can simple keep this environment variable in UI (Environment tab) only.  Unless most other settings environment variables from UI are being merged with those from YAML ([more details](https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence)). The ones from UI have higher priority.

**Comment by chipitsine** [comment]
I did it

https://ci.appveyor.com/project/chipitsine/softethervpn/build/job/u24xhquh491yjjl0

it does not work.
does it work for you ?

**Comment by IlyaFinkelshteyn** [comment]
You simple removed `auth_token` but you have to leave it and point to some variable e.g. `auth_token: $(github_token)` where `github_token` is environment variable which is set in UI for every AppVeyor project.

**Comment by chipitsine** [comment]
that works

I really think it is better UX than one described in guide
consider updating guide ?
