### ISSUE TITLE
Visual Studio 2019 Preview 1.1

### ISSUE THREAD

**Issue by janisozaur** [appveyor/ci#2759]
MSVC 2019 preview 1 is out
https://blogs.msdn.microsoft.com/visualstudio/2018/12/04/making-every-developer-more-productive-with-visual-studio-2019/

**Comment by FeodorFitsner** [comment]
The new `Visual Studio 2019 Preview` image has been introduced.

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner looks like, it hasn't been indroduced properly. See my comment https://github.com/appveyor/ci/issues/2762#issuecomment-447230403
