### ISSUE TITLE
Qt 5.12.1

### ISSUE THREAD

**Issue by ismail** [appveyor/ci#2760]
http://blog.qt.io/blog/2018/12/06/qt-5-12-lts-released/

Updating symlinks:

```
rd C:\Qt\latest
mklink /J C:\Qt\latest C:\qt\5.12.1

rd C:\Qt\5.12
mklink /J C:\Qt\5.12 C:\qt\5.12.1
```

**Comment by anatoly-os** [comment]
@IlyaFinkelshteyn Any estimation for when Qt 5.12 will be available?

**Comment by Jojo-Schmitz** [comment]
And please with msvc2017 and msvc2017_64, not (just) msvc2015_64

**Comment by patrickelectric** [comment]
Any update ?

**Comment by CHN-STUDENT** [comment]
Hope you can update it as soon as quickly. Thanks!

**Comment by CHN-STUDENT** [comment]
Would you want to add the lastest version of Qt(5.12.0) in next update? Because the Qt(5.12.0) using mingw64 6.3 is difference of the older version , so I hope we can get the update in next image. Thanks!

**Comment by Jojo-Schmitz** [comment]
? As far as I can see Qt 5.12.0 uses MinGW 7.3, not 6.3

**Comment by CHN-STUDENT** [comment]
Sorry, it is MinGW 7.3 X64

**Comment by Jojo-Schmitz** [comment]
I realised that your's got to have been a typo when I hit the Save button ;-)

**Comment by ismail** [comment]
Qt 5.12.1 is out - http://blog.qt.io/blog/2019/02/01/qt-5-12-1-released/

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)

**Comment by Radfordhound** [comment]
Hi, thanks for the update! Apologies if this is not the place to post this, but are there any plans to add support for the msvc2017/msvc2017_64 versions of Qt 5.12.1 as well?

If I understand things correctly, with this change, the newest msvc 64-bit version of Qt available to those of us using the Visual Studio 2017 image is Qt 5.10.1, whereas before the change we were able to use Qt 5.11.2, which seems sort of like a step backwards. Is this right, or did I misunderstand things?

**Comment by Jojo-Schmitz** [comment]
As mentioned ferelier:
And please **with msvc2017 and msvc2017_64**, not (just) msvc2015_64

**Comment by ismail** [comment]
Ok, so according to https://www.appveyor.com/docs/windows-images-software/#qt , up from Qt 5.10.1 all Qt releases are msvc2015 which doesn't make any sense. Is there any technical reason for this?

**Comment by variar** [comment]
Qt 5.10.1 is about one year old and does not have security updates. The only recent version for msvc2017 is Qt 5.9.7. If there is technical reason for not providing Qt 5.12.1 for msvc2017, could we at least get back Qt 5.11.2 (or better 5.11.3)?

**Comment by nschimme** [comment]
FYI, the Windows Images Software documentation doesn't specifically mention that the `Qt Tools` supports Mingw-64. Does this still need to happen?

**Comment by IlyaFinkelshteyn** [comment]
Guys, sorry for confusion. it was documentation which was not updater properly, not image. Please check now: https://www.appveyor.com/docs/windows-images-software/#qt

**Comment by Radfordhound** [comment]
Ah awesome, so it was just the documentation. Thanks for clarifying this!

**Comment by nschimme** [comment]
@IlyaFinkelshteyn not sure where I can report this but please upgrade to Qt 5.12.2 to support the MingW 32bit build prebuilt binaries

https://blog.qt.io/blog/2019/03/15/qt-5-12-2-released/

**Comment by IlyaFinkelshteyn** [comment]
@nschimme sure, please watch https://github.com/appveyor/ci/issues/2889.
