### ISSUE TITLE
.NET 3.0 Preview (3.0.100-preview-009812) on Visual Studio 2019 Preview image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2762]
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by AraHaan** [comment]
This commit will fail for me, is this only for the vspreview image or also for the stable ones as an opt-in as well? I would like to be able to use it on stable if my global.json asks for it on the build. 
https://github.com/Elskom/ReleasePackaging/commit/3086340492bea5e1f383a16880c19e0ba01e9277

the failing build: https://ci.appveyor.com/project/Elskom/releasepackaging/builds/21002033

**Comment by FeodorFitsner** [comment]
No, .NET 3.0 Preview is installed on `Visual Studio 2019 Preview` image.

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner , I have just tried to build the project with 2019Preview image, but msbuild was 15.9 and sdk was 2.2.100.
When it will be fixed?

**Comment by FeodorFitsner** [comment]
Well, this is the test: https://ci.appveyor.com/project/appveyor-tests/net-core-3
and corresponding appveyor.yml: https://github.com/appveyor-tests/net-core-3/blob/master/appveyor.yml

**Comment by VladislavAntonyuk** [comment]
https://ci.appveyor.com/project/VladislavAntonyuk/circlepacking/builds/21009402/job/7147lxg54s45cgr7

**Comment by FeodorFitsner** [comment]
Use `global.json` to pin the version of SDK as suggested.

**Comment by AraHaan** [comment]
https://ci.appveyor.com/api/buildjobs/26sewik7k6monkwn/log
nice, I would like to avoid the global.json though.

**Comment by FeodorFitsner** [comment]
If you work through `dotnet` CLI instead of `msbuild` then the latest .NET Core will be used.

**Comment by FeodorFitsner** [comment]
That's true. MSBuild path wasn't changed on VS 2019 image. What's its location btw?

**Comment by AraHaan** [comment]
@FeodorFitsner but the problem is that your build system defaults to msbuild instead of telling it to instead do "dotnet build" when it detects a dotnet sdk style project.

**Comment by VladislavAntonyuk** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin 
Or
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\

**Comment by IlyaFinkelshteyn** [comment]
Path to msbuild issue is tracked at https://github.com/appveyor/ci/issues/2776.

**Comment by VahidN** [comment]
Please install .NET Core SDK version 3.0.100-**preview7**-012821
