### ISSUE TITLE
Please turn on scheduled-builds for our repository

### ISSUE THREAD

**Issue by m-tmatma** [appveyor/ci#2764]
Please turn on scheduled-builds for our repository (https://ci.appveyor.com/project/sakuraeditor/changelog-sakura) which is managed at https://github.com/sakura-editor/changelog-sakura .

- https://www.appveyor.com/docs/build-configuration/#scheduled-builds
- https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/

We use the repository to create CHANGELOG.md for https://github.com/sakura-editor/sakura .
by using https://github.com/github-changelog-generator/github-changelog-generator .

The repository `changelog-sakura` and the repository `sakura` are separate.
So we need to build `changelog-sakura` regularly.

We're planning to build it once a day.

Regards.

**Comment by IlyaFinkelshteyn** [comment]
@m-tmatma Thank you for the detailed description. We enabled scheduled builds for your account!
