### ISSUE TITLE
Azure Web Jobs deployment

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#277]
Discussion:
http://help.appveyor.com/discussions/problems/977-deploy-web-job-using-appveyor

https://github.com/projectkudu/kudu/wiki/Web-jobs
https://github.com/projectkudu/kudu
https://github.com/projectkudu/kudu/wiki/WebJobs-API

**Comment by TWith2Sugars** [comment]
If it helps this is how I deploy webjobs: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/AzureWebJobs.fs

**Comment by FeodorFitsner** [comment]
Yeah, thanks for that. Still our main challenge is how to deploy the schedule for triggered job?

**Comment by mohamedfarrag** [comment]
Hi Feodor , any updates for this issue ?, we need it urgently !

**Comment by kevinneufeld** [comment]
@mohamedfarrag You can deploy triggered webjobs with powershell via kudu api. I have created a ps module to help, a wrapper of Invoke-RestMethod. Have a look it might help,  [PsKudu](https://github.com/deepcovelabs/PsKudu).

Example of our build workflow:
1. on commit to master runs debug build and tests
2. on pass builds and packages, api, spa, webjobs to zip
3. add `schedule.job` files to trigger jobs archive if required `{“schedule": “0 */2 * * * *”}` see [Kudu Wiki](https://github.com/projectkudu/kudu/wiki/Web-jobs)
4. deployment workflow: shutdown running webjobs, app_offline when deployment api/spa, deployment of webjobs.

    Publish-KuduWebJob 
       -WebsiteName {site_name} -Username {publishing_username) -Password {publishing_password} `
       -FilePath {C:\exampleWebjob.zip} -JobName {exampleWebJob} `
       -RunCommand {exampleWebJob.exe} -IsTriggered [Optional]

If you don't want to include the the `schedule.job` in the archive or need to change the schedule you can use the following:
    
    Set-KuduTriggeredSchedule `
        -Website {siteName} -UserName {userName} -Password {password} `
        -JobName {jobName} -Schedule “0 */2 * * * *” 

`Set-KuduTriggeredSchedule` creates a tmp schedule.jobs file and then uploads it to the specific webjob, be careful there is no error handling or validation on quartz cron `{second} {minute} {hour} {day} {month} {day of the week}`

**Comment by msiers** [comment]
I setup a project following the Visual Studio guidelines for deploying WebJobs using Visual Studio [https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-deploy-webjobs/].  
My web job project is linked to my web api project.

However I am now getting build errors about a missing appveyor.pubxml file for the web job project.
What is the best way to resolve this web job build/deployment issue?

**Comment by TurgutBtc** [comment]
Hello @kevinneufeld 

When we try to use PSkudu we always get 401 we have cheked crediantals also...

**Comment by FeodorFitsner** [comment]
If username/password are defined as secure variables then make sure it's not PR build unless secure variables are allowed for PR builds (private repos only).

**Comment by bjorncoltof** [comment]
Hi, great that it is now in! How do I use it?

**Comment by FeodorFitsner** [comment]
Here you are: http://www.appveyor.com/docs/deployment/azure-webjob
