### ISSUE TITLE
Invalid build result

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#2775]
https://ci.appveyor.com/project/VladislavAntonyuk/circlepacking/builds/21031496/job/4l9s7xbe5mvigb5m
Build started
dotnet --version
2.2.100-preview2-009404
git clone -q --branch=master https://bitbucket.org/VladislavAntonyuk/circlepacking.git C:\projects\circlepacking
git checkout -qf 40c07bed8b4feb89ee111b527537e41d03a06556
Patching .NET Core .csproj files
dotnet restore
dotnet build
Microsoft (R) Build Engine version 15.9.8-preview+g0a5001fc4d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
Build FAILED.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:00.29
Discovering tests...OK
Collecting artifacts...
No artifacts found matching '**\bin\Release' path
Build success

AR: Build success
ER: Build failed

**Comment by IlyaFinkelshteyn** [comment]
Default behaviour in PowerShell is to continue on non-terminating errors. You can use `CMD` or set `$ErrorActionPreference = "Stop";` before your PowerShell commands.

**Comment by VladislavAntonyuk** [comment]
may I set it as EnvironementVariable?
