### ISSUE TITLE
Windows Driver Kit 1809 (10.0.17763.0)

### ISSUE THREAD

**Issue by nefarius** [appveyor/ci#2780]
Building Windows drivers currently fails, most probably because the (Windows 10) [Windows Driver Kit](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#wdk-for-windows-10-version-1809) is outdated.

[Failing build example](https://ci.appveyor.com/project/nefarius/vigembus/builds/21060719)

Using `image: Previous Visual Studio 2017` fails as well.

Thanks.

**Comment by eligrey** [comment]
@FeodorFitsner Any progress?

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)
