### ISSUE TITLE
NuGet package restore failing for .NET Core 2.0

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2787]
[Discussion](https://help.appveyor.com/discussions/problems/18758-nuget-package-restore-failing-for-net-core-20-since-dec-13-windows-image-update). Lets check if it works with next `msbuild` version.

**Comment by AraHaan** [comment]
I do have a msbuild issue on my newsmake project which I had to replace with a manual ``dotnet build`` and a manual ``dotnet pack`` to make ``dotnet pack`` not fail the build.

However when I made a release tag (1.0.0) it seems to not pick up the nuget packages that was just generated and then upload them to nuget like normally.

https://ci.appveyor.com/project/Elskom/newsmake/builds/21220796

**Comment by IlyaFinkelshteyn** [comment]
Recent `Visual Studio 2017` image update fixed it.
