### ISSUE TITLE
unix-like read files style

### ISSUE THREAD

**Issue by aleksuss** [appveyor/ci#2799]
Hello. In my tests I try to calculate `sha256` and `sha512` hashes for files. I've calculated the hashes on windows host and copy-paste results in the tests. But appveyor doesn't pass this tests because reads files like on unix host as I recognized. Windows and Linux has different line endings, `\r\n` and `\n`. So when the file is read, the the content of files is different. Is it possible to change this mode ? Thanks.

**Comment by Wasapl** [comment]
You can use `dos2unix` tool to convert text files with windows line endings to Unix line endings. `unix2dos` convert in opposite direction.

But both have to be installed prior use.
To install it you can add next line in `install` section:
```
install:
  - sh: sudo apt-get install dos2unix
```

**Comment by Wasapl** [comment]
@aleksuss can you elaborate that confuses you. I'll do my best to help )))

**Comment by aleksuss** [comment]
@Wasapl thanks for your advise but I guess it doesn't solve my problem. One more time. I have a file with some content. If I open the file and calculate hash of the file on linux host I get one value but If I do the same on windows I get another. And It's ok. It's an expected result. But when `Appveyor` executes hash calculation the result like on linux host. There is a question - why. 
By the way. On `Travis CI` everything is OK. I suppose I've described more clear ?

P.S. My appveyor.yml file https://github.com/exonum/exonum/blob/master/.appveyor.yml
