### ISSUE TITLE
Ruby 2.6.1

### ISSUE THREAD

**Issue by larskanis** [appveyor/ci#2803]
[RubyInstaller-2.6.0-1](https://rubyinstaller.org/2019/01/06/rubyinstaller-2.6.0-1-released.html) has been released. Can you please add the pre-installed RubyInstaller version to the Appveyor image? RubyInstaller-2.6.0-1 is a new stable branch, which should go into a new directory.

**Comment by FeodorFitsner** [comment]
Thanks for letting know! Will deploy it during the next image update.

**Comment by larskanis** [comment]
@FeodorFitsner  RubyInstaller-2.6.1-1 is out, so you might install/update to this version directly.

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)
