### ISSUE TITLE
PostgreSQL 10.6 and 11.1

### ISSUE THREAD

**Issue by austindrenski** [appveyor/ci#2805]
PostgreSQL 10.6 and 11.1 [were released on 2018-11-08](https://www.postgresql.org/about/news/1905), but are [not currently listed](https://www.appveyor.com/docs/services-databases/#postgresql) as available.

Could we get an ETA on when these might become available?

/cc @npgsql

**Comment by FeodorFitsner** [comment]
Thanks for the kind reminder! We will update Postgres during the next image update.

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)
