### ISSUE TITLE
Selenium drives updated: Chrome 2.45, Gecko 0.24, IE 3.141.5

### ISSUE THREAD

**Issue by shinnn** [appveyor/ci#2810]
https://selenium-release.storage.googleapis.com/index.html?path=3.141/

A lot of bug fixes has been implemented since the currently installed version 3.14.0.0 was released. https://github.com/SeleniumHQ/selenium/blob/20e29a8c7bf08f4cca0bded7c15b4591c04f0c59/cpp/iedriverserver/CHANGELOG#L119-L271

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)

**Comment by shinnn** [comment]
Great. Thanks, @IlyaFinkelshteyn!
