### ISSUE TITLE
Running appcore2.0 test project fails

### ISSUE THREAD

**Issue by ravenpride** [appveyor/ci#2814]
Hello,

I'm using AppVeyor for some time now and everything was fine until my team decided to integrate a common build system which locates intermediate folders and output folders at a central place in the solution. The build system consists of property sheets and targets files that do what is expected to be done as long as running in Visual Studio 2017. AppVeyer can build the solution and everything seems ok. The test stage finds the test project, but the path of the test DLL is incorrect. It looks like the property sheets are not considered properly.

Could you please have a look at the build log?
https://ci.appveyor.com/project/ravenpride/dotnet-libs-logging/builds/21688072

```
Discovering tests...OK
Running .NET Core tests...dotnet test "C:\projects\dotnet-libs-logging\src\GriffinPlus.Lib.Logging.Tests\GriffinPlus.Lib.Logging.Tests.csproj" --configuration Release --no-build /property:Platform=AnyCPU
Test run for C:\projects\dotnet-libs-logging\src\GriffinPlus.Lib.Logging.Tests\_build\.AnyCPU.Release\netcoreapp2.0\GriffinPlus.Lib.Logging.Tests.dll(.NETCoreApp,Version=v2.0)
```

I would expect the path of the test DLL to be:
```
C:\projects\dotnet-libs-logging\_build\Logging.AnyCPU.Release\netcoreapp2.0\GriffinPlus.Lib.Logging.Tests.dll
```

Any help would be appreciated. Thank you very much!

**Comment by IlyaFinkelshteyn** [comment]
@ravenpride AppVeyor detects .NET Core test **projects** (not assemblies, e.g. `.csproj`, not `dll` files) and run `dotnet test` with appropriate switches (including `--no-build`) against them, as you can see [here](https://ci.appveyor.com/project/ravenpride/dotnet-libs-logging/builds/21688072#L290).

As you can see it is `dotnet test`, not AppVeyor is being mislead by this and it is `dotnet test` cannot find the `dll`...

Does `dotnet test` works for you locally?

**Comment by ravenpride** [comment]
Ok, thank you for the hint!
