### ISSUE TITLE
Define %ANDROID_HOME% env var

### ISSUE THREAD

**Issue by ViliusSutkus** [appveyor/ci#2831]
Image: Visual Studio 2017
Should I have to set it myself? I think it would be handy to just have that available by default, since the docs aren't telling me where exactly the SDK is installed.

**Comment by IlyaFinkelshteyn** [comment]
We have many SDKs installed on the build image, check [here](https://github.com/EwoutH/rav1e/blob/EwoutH-AppVeyor/appveyor.yml#L37). By specifying this variable I afraid we can break people. You can always explore build VM file system with running test build with something like `cd/ && dir /s <your_file> && cd %APPVEYOR_BUILD_FOLDER%` or [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/).

**Comment by ViliusSutkus** [comment]
Thanks Ilya, missed the RDP part when I first read through the docs.
