### ISSUE TITLE
Ninja 1.9.0 and Meson 0.52.1

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#2835]
Meson and Ninja are gaining popularity quickly. It's a relatively fast install, but it adds a lot of code for two very small programs that could be installed by default.
 - [ ] [The Meson Build system](https://mesonbuild.com/)
 - [ ] [Ninja](https://ninja-build.org/)

**Comment by EwoutH** [comment]
@IlyaFinkelshteyn Could you give a status update on this issue?

**Comment by FeodorFitsner** [comment]
Ninja could be easily downloaded during the build. It's just a few KB zip: https://github.com/ninja-build/ninja/releases

**Comment by EwoutH** [comment]
It saves a few lines of code in a lot of .yml files. Just because it's just a few kB's, it could easily be provided with the image.

**Comment by pavelkryukov** [comment]
Also, downloading sometimes fails and build has to be restarted

**Comment by Zingam** [comment]
Ninja usage with CMake is ubiquitous. It simply makes no sense to have CMake but not to have Ninja, especially because it is just a few KBs.

**Comment by EwoutH** [comment]
Thanks a lot!

**Comment by Zingam** [comment]
@FeodorFitsner Is Ninja also available on the Ubuntu image?

**Comment by Wasapl** [comment]
Ninja is not preinstalled on the Ubuntu images but it's very easy to install it from [pre-built package](https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages). Just add next block into your `appveyor.yml` file:
```yaml
install:
  - sh: sudo apt-get install ninja-build
```

**Comment by Zingam** [comment]
@Wasapl Sure but it would make sense to not have to do it if your script supports Windows and Ubuntu. I would like to have as little discrepancies between platforms as possible in my scripts.

**Comment by Wasapl** [comment]
Fare enough, we will add Ninja on next update of Ubuntu and MACOS images
