### ISSUE TITLE
Python InstallError

### ISSUE THREAD

**Issue by GandaG** [appveyor/ci#2845]
[Repo](https://ci.appveyor.com/project/GandaG/fomod-validator)
[Example Build](https://ci.appveyor.com/project/GandaG/fomod-validator/builds/22058730)

When running `python.exe -m pipenv sync` I'm suddenly getting `InstallError`. This works on my windows machine and I've tried to rebuild older commits that were previously working and now get the same error.

**Comment by IlyaFinkelshteyn** [comment]
Bad and good build comparison shows that before build script installed `pip-18.1`, which later changed to `pip-19.0.1`. This is most probably the root cause.

**Comment by GandaG** [comment]
Thanks for the help! If anyone else comes here, this is also documented in pypa/pip#6163
