### ISSUE TITLE
RDP enable error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#2849]
PowerShell Core
```
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
```

iex : The term 'Get-NetIPAddress' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\appveyor\AppData\Local\Temp\1\gik3io0j00.ps1:5 char:1
+ iex ((new-object net.webclient).DownloadString('https://raw.githubuse ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-NetIPAddress:String) [Invoke-Expression], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by Wasapl** [comment]
Which image did you get this error on? RDP script does not for Ubuntu images

**Comment by VladislavAntonyuk** [comment]
VisualStudio 2019 Preview

**Comment by Wasapl** [comment]
This is weird... Can you please share a link to failed build?

**Comment by VladislavAntonyuk** [comment]
https://ci.appveyor.com/project/VladislavAntonyuk/draw-go/builds/22089684/job/p5latjjaerfvusd9

**Comment by VladislavAntonyuk** [comment]
I have found that this command (Get-NetIpAdress)is available in PS Core, probably it requires different parameters. I will try with PowerShell, thank you

**Comment by VladislavAntonyuk** [comment]
yes, it works with PS, it would be nice if it worked with PS.Core
