### ISSUE TITLE
Build cache is not deleted with API properly

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2853]
Seems that `Amazon S3` type of cache storage is being skipped.

**Comment by azat** [comment]
@IlyaFinkelshteyn any news on this one?

**Comment by gep13** [comment]
@IlyaFinkelshteyn @FeodorFitsner just wanted to follow up with this one as well?  Is there anything that we can do to help with this?  Thanks

**Comment by IlyaFinkelshteyn** [comment]
@gep13 @azat sorry guys for delay, will do our best to make it work this week

**Comment by IlyaFinkelshteyn** [comment]
It should work OK now. Can you guys confirm it works for you?
