### ISSUE TITLE
Qt Installer Framework 3.0.6

### ISSUE THREAD

**Issue by flyacn** [appveyor/ci#2856]
Hi,

Would you please install the latest `Qt Installer Framework 3.0.6` (at least) on the `Visual Studio 2017` image?

https://blog.qt.io/blog/2018/12/17/qt-installer-framework-3-0-6-released/
https://download.qt.io/official_releases/qt-installer-framework/3.0.6/

Thank you.

**Comment by flyacn** [comment]
Meanwhile, version 3.1.0 was released.
Would you please install this one?
https://download.qt.io/official_releases/qt-installer-framework/3.1.0/

Thank you.

**Comment by FeodorFitsner** [comment]
Qt IFW 3.0.6 was installed (in the upcoming image) into `C:\Qt\Tools\QtInstallerFramework\3.0\bin`.

@flyacn Though we didn't find how to install Qt IFW 3.1.0.

**Comment by flyacn** [comment]
Thank you @FeodorFitsner. Indeed, it looks like the Qt downloads page had some snags. Nonetheless, Qt IFW 3.1 is available for download at https://download.qt.io/official_releases/qt-installer-framework/3.1.0/

Do you think it's possible to install version 3.1 instead of 3.0.6 in the next image update?

**Comment by IlyaFinkelshteyn** [comment]
@flyacn how would you do that? We did not see this option with qt maintenance tool wizard.

**Comment by flyacn** [comment]
By simply installing https://download.qt.io/official_releases/qt-installer-framework/3.1.0/QtInstallerFramework-win-x86.exe.
I don't know if Qt distributes the Qt IFW through the Maintenance tool, I usually download it & install it manually.

**Comment by flyacn** [comment]
Hi,

https://www.appveyor.com/docs/windows-images-software/#qt is wrong; QtITFW 3.0.6 is not installed, there's still the 3.0.1 installed. This is the output of the `dir` command on the image **Visual Studio 2017**:
`Directory: C:\qt\QtIFW-3.0.1\bin
Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
-a----        9/14/2017  11:59 AM       18101248 archivegen.exe                                                                                                                                                                      
-a----        9/14/2017  11:59 AM       18731008 binarycreator.exe                                                                                                                                                                   
-a----        9/14/2017  12:00 PM       18578944 devtool.exe                                                                                                                                                                         
-a----        9/14/2017  11:59 AM       19600896 installerbase.exe                                                                                                                                                                   
-a----        9/14/2017  11:59 AM       18491904 repogen.exe`

**Comment by IlyaFinkelshteyn** [comment]
Apparently the way we updated it (with qt maintenance tool wizard) is not correct. We will keep this issue closed in favor of https://github.com/appveyor/ci/issues/2918, where we will try using your approach.
