### ISSUE TITLE
Slash in branch name breaks Bitbucket branch URL

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2858]
Replace URL from `https://bitbucket.org/user/repo/src/branchname` to `https://bitbucket.org/user/repo/branch/branchname` as suggested [here](https://help.appveyor.com/discussions/problems/20024-the-branch-link-to-bitbucket-seems-to-be-broken)

**Comment by IlyaFinkelshteyn** [comment]
Fix has been deployed

**Comment by mminns** [comment]
Thanks
