### ISSUE TITLE
Run deploy when all build workers (running tests) in the matrix are successful

### ISSUE THREAD

**Issue by johlju** [appveyor/ci#2859]
I don't want the deploy step to run on all the matrix jobs. I solved it by only running it on a build worker with a certain job number. The problem is that when using parallel jobs, the jobs take different amount of time, and sometimes the job that runs the deploy step actually deploys before all the other jobs has reported back successfully. 

I'm looking for a way to call back into AppVeyor (API) to check the status of the build, so I can continue with the deploy step if it is the correct job number (let say number 5), and all the other jobs running (number 1-4) has finished successfully.
Or if I could say that one of the jobs (another job specific for deploy) should run sequentially, after all other parallel jobs.

**Comment by IlyaFinkelshteyn** [comment]
We are working on 1st class support for jobs dependencies. For now I believe you can use [this script sample](https://gist.github.com/IlyaFinkelshteyn/dc0b08593cb0babff2bd84dd05c4ee42) to achieve this. In your case it is last (not 1st) job should wait for others, which can be changed easily.

**Comment by johlju** [comment]
Ah, thank you, I look like that could work, I try that out! I'm running deploy in the last job. 
I'm looking forward to that new feature! Closing this issue as there is a way to achieve this.
