### ISSUE TITLE
API call does not clear cache

### ISSUE THREAD

**Issue by gabmontes** [appveyor/ci#2860]
Documentation says, provided there is no way to clear cache from the UI, to use i.e. an API call: `DELETE https://ci.appveyor.com/api/projects/{account}/{project-slug}/buildcache`.

After sending the `DELETE` request and receiving a `204` status, the build log still shows it is using the cache.

Repository: bloqinc/metronome-desktop-wallet

Log for build 1.0.549:
```
Build started
git config --global core.autocrlf input
Fetching repository commit (c3f7db8)...OK
Total: 2.8 MB in 218 files
Restoring build cache
Cache 'node_modules' - Restored
Cache 'C:\Users\appveyor\.electron' - Restored
...
```

How can the cache be effectively cleared through the UI or API?

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/2853. Working on it now. Sorry for the inconvenience.

**Comment by gabmontes** [comment]
Just for reference restoring cache can be skipped setting an environment variable: `APPVEYOR_CACHE_SKIP_RESTORE=true`. Will not clear the cache but might help too.
