### ISSUE TITLE
.NET Core SDK and Runtime v3.0.0-preview5

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2862]

**Comment by jnyrup** [comment]
Since this issue was created, [v3.0.0-preview5](https://dotnet.microsoft.com/download/dotnet-core/3.0) has been released.
Is this issue specifically about preview2 or more generally about the newest available preview?

**Comment by tidusjar** [comment]
v3.0.0-preview6 has also been released now

**Comment by ddrinka** [comment]
@FeodorFitsner We're starting to migrate some code to netstandard2.1 / netcoreapp3.0.  Could you go ahead and push this through on the VS2019 Preview image?  Is there anything preventing its installation?

**Comment by alexrp** [comment]
@IlyaFinkelshteyn Do AppVeyor images provide the `dotnet-install.ps1`/`dotnet-install.sh` [scripts](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)? This would make it very easy for users to install whichever .NET Core version they need as part of their build, without you guys having to update the image for every new preview version.

**Comment by FeodorFitsner** [comment]
The required version of .NET Core could be easily installed with these one-two liners.

On Windows:

```posh
Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
& $env:temp\dotnet-install.ps1 -Architecture x64 -Version '<CORE_SDK_VERSION>' -InstallDir "$env:ProgramFiles\dotnet"
```

where `CORE_SDK_VERSION` is .NET Core SDK version to install, for example `3.0.100-preview6-012264`.

On Linux:

```bash
wget -O dotnet-sdk.tar.gz <CORE_SDK_LINUX_URL>
sudo tar zxf dotnet-sdk.tar.gz -C /usr/share/dotnet
```

where `CORE_SDK_LINUX_URL` is a download URL of .NET Core Linux binaries from .NET Core download page. You can grab "click here to download manually" link from "Thanks for downloading" page.

**Comment by SimonCropp** [comment]
perhaps should be closed in favor of https://github.com/appveyor/ci/issues/3098 ?
