### ISSUE TITLE
Update to Visual Studio 2019 Preview 3

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#2869]
Update the `Visual Studio 2019 Preview` image to [Preview 3](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#VS2019_Preview3).

Extends on #2834.

**Comment by XVilka** [comment]
Visual Studio 2019 was released and available for downloading: https://visualstudio.microsoft.com/downloads

**Comment by moh-hassan** [comment]
Update to Visual Studio 2019 RTM. 
Vs 2019 is [released ](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)since April 02, 2019 (now  Visual Studio 2019 version 16.0.3)
