### ISSUE TITLE
Dynamic grouping for projects and environments

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#287]
Discussion: http://help.appveyor.com/discussions/suggestions/686-grouping-environments

**Comment by illusio789** [comment]
Any news on this ticket?
We have approx 150 environments (and growing).
Being able to group or tag them would be really useful.

**Comment by IlyaFinkelshteyn** [comment]
@illusio789 We plan to do major redevelopment in deployment area (including grouping) this year, but not specific ETA yet.
I am closing this issue in favor of https://github.com/appveyor/ci/issues/1536#issuecomment-300865368, please watch that issue.
