### ISSUE TITLE
Go 1.10.8, 1.11.8, 1.12.3

### ISSUE THREAD

**Issue by kortschak** [appveyor/ci#2875]
Go1.12 has been released https://golang.org/doc/go1.12.

It would be good if the Go1.12 tree were made available. See https://ci.appveyor.com/project/Gonum/gonum/builds/22653229.

Thanks

**Comment by kortschak** [comment]
Do you have an ETA on image updates?

**Comment by mholt** [comment]
We've had to ignore all our AppVeyor CI builds since Go 1.12 came out.

**Comment by mholt** [comment]
We've had to ignore all our AppVeyor CI builds since Go 1.12 came out. Seems a shame to have to spin up their infrastructure with every commit but not actually use their results.

**Comment by kortschak** [comment]
Yes, similar here. We test go1.10, go1.11 and go1.12, but have had to drop the go1.12 tests for the moment.

**Comment by IlyaFinkelshteyn** [comment]
Build image update will be in 2-4 weeks, cannot say more specific date. However it is quite easy to solve specific problem with Go, before image has been updated. For that please add the following into `install` script:

```yaml
install:
- ps: |
    Remove-Item 'C:\go' -Recurse -Force -ErrorAction Ignore
    Remove-Item 'C:\go-x86' -Recurse -Force -ErrorAction Ignore

    Write-Host "Downloading..."
    $goDistPath = "$env:TEMP\go1.12.windows-386.zip"
    (New-Object Net.WebClient).DownloadFile('https://storage.googleapis.com/golang/go1.12.windows-386.zip', $goDistPath)

    Write-Host "Unpacking..."
    7z x $goDistPath -oC:\go1120-x86 | Out-Null
    [IO.Directory]::Move('C:\go1120-x86\go', 'C:\go112-x86')
    Remove-Item 'C:\go1120-x86' -Recurse -Force
    del $goDistPath

    Write-Host "Downloading..."
    $goDistPath = "$env:TEMP\go1.12.windows-amd64.zip"
    (New-Object Net.WebClient).DownloadFile('https://storage.googleapis.com/golang/go1.12.windows-amd64.zip', $goDistPath)
    
    Write-Host "Unpacking..."
    7z x $goDistPath -oC:\go1120-x64 | Out-Null
    [IO.Directory]::Move('C:\go1120-x64\go', 'C:\go112')
    Remove-Item 'C:\go1120-x64' -Recurse -Force
    del $goDistPath

    cmd /c mklink /J C:\go C:\go112
    cmd /c mklink /J C:\go-x86 C:\go112-x86
```

Or wrap it into `.ps1` file and add a  single line to the `install` stage. It will take less than 30 seconds.

**Comment by 1dustindavis** [comment]
Any update on the timeline of Go 1.12?

**Comment by kortschak** [comment]
Travis now supports windows, though I'm finding only with go1.12 and not with go1.11 or go1.10.

**Comment by IlyaFinkelshteyn** [comment]
It has been deployed
