### ISSUE TITLE
Broken sqlite3 using Python stacks on Ubuntu1804

### ISSUE THREAD

**Issue by AxelVoitier** [appveyor/ci#2876]
Hello,

I noticed importing sqlite3 is broken from the provided python 3.7.0 or 3.7.1 on Ubuntu1804 image:
```
$ export PATH=$HOME/venv3.7.1/bin:$PATH  # Simulate stack entry in config file
$ python3.7 -c "import sqlite3"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/appveyor/.localpython3.7.1/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/appveyor/.localpython3.7.1/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

Same happens using 3.7.0 or 3.6.7 provided venv (I haven't tried older versions).

However, if I use the system-wide installed python (3.6 on Ubuntu 18.04) it works:
```
$ /usr/bin/python3.6 -c "import sqlite3"
```

Could it be that you are building these python versions without sqlite development packages installed?

Cheers,
Axel

**Comment by Wasapl** [comment]
_> Could it be that you are building these python versions without sqlite development packages installed?_
This could be a reason. Which packages should be installed prior building pythons?

**Comment by AxelVoitier** [comment]
I actually have no idea. I just run the error message into google, hit the first result and that was this really old reply mentioning installing `libsqlite3-dev` before compiling:
https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by Wasapl** [comment]
Yes, it works after installing `libsqlite3-dev` and recompiling python.
We will fix this next Ubuntu images update.

**Comment by Wasapl** [comment]
@AxelVoitier we updated Ubuntu images month ago. Is this issue fixed for you?
(I'm sorry I forgot to ask right after update).
