### ISSUE TITLE
Pre-installed golang version behind latest release

### ISSUE THREAD

**Issue by nbosscher** [appveyor/ci#2879]
I'm trying to test my code against the latest version of golang because when I do a deployment, I'm going to deploy using the latest version of golang in my docker build. As go pushes out releases, I always want to have the latest version. 

Previously, I'd use chocolatey to install the latest version of golang as part of my ci script. It worked great, after a golang release was out, it would be a day or so and I'd get the updated version. After some recent changes to AppVeyor, the ci servers are coming with golang pre-installed. Cool! But it seems that the versions are lagging behind golang's releases. (and chocolatey's too which is how I found this out). This is a problem b/c now my ci script isn't going to be testing against the latest golang version which it will be deployed with.

I understand there will always be some delay between golang releasing and it being installed on the appVeyor servers. I probably could re-organize my ci workflow to work around this issue. But this used to work without any special effort on my part and I'd like to keep it that way.

**Comment by nbosscher** [comment]
Related to #2875

**Comment by nbosscher** [comment]
Sorry, I didn't see that other ticket. But my request is a bit more like "please make sure the pre-installed version is always up to date". Not a 1-off update.

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/2875. Also that issue contains a [workaround](https://github.com/appveyor/ci/issues/2875#issuecomment-469898703).

**Comment by nbosscher** [comment]
@IlyaFinkelshteyn 
I'm concerned that you've closed this b/c my ticket is to "always have the latest golang version deployed", not "please update to golang 1.12". 

Great that there's a workaround, but I don't want to have to deal with this every time there's a new golang release. Especially since problem was very easily solved before appVeyor started having golang pre-installed
