### ISSUE TITLE
ODBC Driver for SQLite

### ISSUE THREAD

**Issue by mloskot** [appveyor/ci#2881]
Would it be possible to deploy the SQLite ODBC Driver?

Here is driver website http://www.ch-werner.de/sqliteodbc/
Installers for the current version:

-    32-bit http://www.ch-werner.de/sqliteodbc/sqliteodbc.exe
-    64-bit http://www.ch-werner.de/sqliteodbc/sqliteodbc_w64.exe

----
A while ago, I made this request on the Help forum [ODBC Driver for SQLite](https://help.appveyor.com/discussions/suggestions/1024-odbc-driver-for-sqlite) and received suggestion to download and install it on demand. 

Although it has worked very well for two years, something must have changed on the site hosting the driver installers; perhaps CI builds increased the download traffic and the owner decided to block it.
So, the download attempts regularly fail:

```
Exception calling "DownloadFile" with "2" argument(s): "Too many automatic redirections were attempted."
At line:5 char:3
+   (New-Object Net.WebClient).DownloadFile('http://www.ch-werner.de/sq ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Exception calling "DownloadFile" with "2" argument(s): "Too many automatic redirections were attempted."
At line:6 char:3
+   (New-Object Net.WebClient).DownloadFile('http://www.ch-werner.de/sq ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

e.g. https://ci.appveyor.com/project/nanodbc/nanodbc/builds/22862413/job/swn6mxoik619yapg

https://ci.appveyor.com/project/nanodbc/nanodbc/builds/22861689/job/vx1hwa8bt5746qwg

**Comment by IlyaFinkelshteyn** [comment]
Can you please confirm that download is recovered? I see it started working again for you. Also do you believe you can utilize [build cache](https://www.appveyor.com/docs/build-cache/) to be on the safe side for cases like this? Note that cache is best effort solution and you would still need to check the content of cached folder and try to download if it does not contain the file.

**Comment by mloskot** [comment]
I've configured caching  of `C:\downloads\` folder where installers are downloaded for all jobs with `DB=SQLite` defined:

https://github.com/nanodbc/nanodbc/blob/a11c902655fb188ba63dbd89d47ff7250120ba24/.appveyor.yml#L83-L114

The caching seems to work, e.g. https://ci.appveyor.com/project/nanodbc/nanodbc/builds/23224417,  `Cache 'c:\downloads' - Restored` than no downloading performed and the drivers are installed.

Problem solved for now. Thanks!
