### ISSUE TITLE
Guest OS family 6 and Azure SDK

### ISSUE THREAD

**Issue by withinfocus** [appveyor/ci#2883]
Family 6 is available:

https://azure.microsoft.com/en-us/updates/guestosfamily6announce/

This should be available for deployment in Azure SDK 2.9.6:

https://github.com/MicrosoftDocs/azure-docs/issues/23217

although in our experience this hasn't been resolved until the latest VS (15.9.8) is available. There's additional confusing documentation about this:

https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix#family-6-releases

implying that Azure SDK 3.0 should be installed but that's really for VS 2015, and your workers don't have it installed when VS 2017 is used.

When performing a cloud service deployment the following is returned on a worker:

`BadRequest : The OS family 6 you are trying to deploy is not supported by the SDK package. The SDK package supported OS families:3,4,5,1,2,98,97. Please try to deploy to a different operating system. To do this specify a different osFamily and/or osVersion in your .cscfg file.`

End result is we believe a VS 2017 refresh is in order and to try this again then. Cloud service deployments using OS family 6 which we just upgraded to fail currently.

**Comment by withinfocus** [comment]
Additional info:

https://developercommunity.visualstudio.com/content/problem/443790/the-os-family-6-you-are-trying-to-deploy-is-not-su.html

Microsoft seems to have this resolved in their March hosted image update for DevOps, hoping to see a similar update for AppVeyor. May involve an install of SDK 3.0 for your 2017 image.

**Comment by withinfocus** [comment]
Any update here? This seems to have been tagged for the next update but we're still seeing failures.

**Comment by IlyaFinkelshteyn** [comment]
Build image update has been delayed as we found some blockers (unrelated to this issue). It will land hopefully in the end of the week. Sorry for the delay.

**Comment by IlyaFinkelshteyn** [comment]
it has need deployed
