### ISSUE TITLE
Qt 5.12.2 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2889]
https://github.com/appveyor/ci/issues/2760#issuecomment-473473055

Updating symlinks:

```
rd C:\Qt\latest
mklink /J C:\Qt\latest C:\qt\5.12.2

rd C:\Qt\5.12
mklink /J C:\Qt\5.12 C:\qt\5.12.2
```

**Comment by vadi2** [comment]
The 32bit binaries is a big deal - we'd love to have access to them asap.

**Comment by nschimme** [comment]
@IlyaFinkelshteyn Clearly 3/24 is not the deadline. Are we targeting a new date for updating the image? The reason I'm asking is because checking this issue every day, lol

**Comment by nschimme** [comment]
@IlyaFinkelshteyn :tada: Thank you! :tada: Works like a charm!

**Comment by pbek** [comment]
Anyone else getting this error when starting a binary built with 5.12.2 and mingw73_32?

![](https://i.imgur.com/YMe4hQW.png)

**Comment by nschimme** [comment]
@pbek I haven't run into that with my build if you want to reference how I build my Qt app: https://github.com/MUME/MMapper/blob/master/.appveyor.yml

**Comment by pbek** [comment]
thanks a lot @nschimme, I'll take a look at your config!

**Comment by pbek** [comment]
I added some paths, that seems to have solved my issues. Thanks again, @nschimme!

**Comment by vadi2** [comment]
`-lglut` is no longer found with this version whereas it was with 5.11. Is the version of Qt hosted by Appveyor custom-compiled or is it the official one from Qt downloads?

**Comment by IlyaFinkelshteyn** [comment]
@vadi2 yes, its official. Actually installation of Qt is the only installation we could not automate so far and we do it with "QT Maintenance Tool" manually :) Do you have `-lglut` with 5.12.2 on your dev box?

**Comment by vadi2** [comment]
No, and it turns out I don't need it! On my Windows dev box I took out `-lglut` and things compiled okay. Meanwhile doing the same  AppVeyor generates so many errors that even the full log doesn't have the start of them! https://ci.appveyor.com/project/Mudlet/mudlet/builds/24031928

**Comment by IlyaFinkelshteyn** [comment]
@vadi2 Can you open the build which was successful before [QT update](https://www.appveyor.com/updates/2019/04/14/) and press `RE-BUILD COMMIT` button?

**Comment by vadi2** [comment]
All other builds that still use Qt 5.11 (and link to `-lglut`) are successful: https://ci.appveyor.com/project/Mudlet/mudlet/history

So I've created a PR that still uses 5.11 but removes `-lglut` since that works OK for me locally, and that works on AppVeyor as well: https://ci.appveyor.com/project/Mudlet/mudlet/builds/24113246

So it's just the `-lglut` + 5.12 that bombs out on AppVeyor - which is strange and I'm not sure how to proceed.

**Comment by vadi2** [comment]
Aha, got it solved - we were mixing 64bit and 32bit (https://github.com/Mudlet/Mudlet/commit/e19611549f21d88dd118fa414a90c6b268953459). Nothing to do with AppVeyor!

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for the update because I was out of ideas :)
