### ISSUE TITLE
Make APPVEYOR_REPO_COMMIT_TIMESTAMP content unambiguous

### ISSUE THREAD

**Issue by nulltoken** [appveyor/ci#289]
`APPVEYOR_REPO_COMMIT_TIMESTAMP` exposes the datetime of the commit being built in a format such as `9/5/2014 1:06:05 PM`.

However, there's no way to tell if what's reflected is a UTC timestamp or a local one.

How about rather expose an easily machine parsable format such as `2015-06-05T13:26:37Z` for instance?

**Comment by FeodorFitsner** [comment]
Yeah, that makes sense.

**Comment by FeodorFitsner** [comment]
All commit timestamps are now formatted as [ISO 8601](https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Roundtrip).

**Comment by nulltoken** [comment]
@FeodorFitsner Thanks! Is it deployed yet?

I've **[patched](https://github.com/libgit2/libgit2sharp/commit/8f1c23e02acc9d257d7f97ccf64d6dbcd8ca165e)** the `appveyor.yml` file

```
     $BuildDate = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss")
     Write-Host "Build UTC date = " -NoNewLine
     Write-Host $BuildDate -ForegroundColor "Green"
 
+    $BuildDate = $Env:APPVEYOR_REPO_COMMIT_TIMESTAMP
+    Write-Host "Commit UTC timestamp = " -NoNewLine
+    Write-Host $BuildDate -ForegroundColor "Green"
```

and it produced the following output

```
Build UTC date = 20150712091457 
Commit UTC timestamp = 7/12/2015 9:14:11 AM 
```

**Comment by FeodorFitsner** [comment]
Will be deployed later today.



- Feodor

**Comment by FeodorFitsner** [comment]
Deployed.

**Comment by nulltoken** [comment]
:heart: it!
