### ISSUE TITLE
update CMake to 3.14 in Visual Studio 2019

### ISSUE THREAD

**Issue by slodki** [appveyor/ci#2891]
CMake 3.13.3 is installed.
CMake 3.14 adds [support for VS2019](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html)

Candidate for #2887?

**Comment by onqtam** [comment]
+1 for this :D

**Comment by EwoutH** [comment]
Lets make that [CMake 3.14.2](https://blog.kitware.com/cmake-3-14-2-available-for-download/), it contains some fixes for VS 2019 v142 toolset discovery.

**Comment by EwoutH** [comment]
Why wasn't CMake updated in the latest [Windows images update](https://www.appveyor.com/updates/2019/04/14/)?

**Comment by IlyaFinkelshteyn** [comment]
Latest [Windows images update](https://www.appveyor.com/updates/2019/04/14/) was for `Visual Studio 2015` and `Visual Studio 2017` images. We are working on the new `Visual Studio 2019` image which will include this CMake.

**Comment by EwoutH** [comment]
@IlyaFinkelshteyn Do you have an ETA?

**Comment by Croydon** [comment]
@EwoutH There is already a pull request https://github.com/appveyor/build-images/pull/5 😄

**Comment by IlyaFinkelshteyn** [comment]
Updated.
