### ISSUE TITLE
CygWin installed on workers needs updating (it is broken now)

### ISSUE THREAD

**Issue by claudioandre-br** [appveyor/ci#2898]
As the "worker" is now, CygWin is not working properly. Any binary crashes:
* The error message seen inside the worker is: `Command exited with code -1073741511`

I was able to workaroud the problem doing this inside my YAML
```
  # Workaround (update CygWin)
  - appveyor DownloadFile "http://www.cygwin.com/setup-%Arch%.exe" -FileName C:\%Location%\setup-%Arch%.exe
  - ps: |
      cmd /c "C:\$env:Location\setup-$env:Arch.exe -q --no-desktop --no-shortcuts --no-startmenu --upgrade-also"
```
*****
The latest successful build was on March 6.
https://ci.appveyor.com/project/claudioandre-br/johntheripper/builds/22884186/job/jt33mhofqlp6ptgc

I noticed the error on March 21
https://ci.appveyor.com/project/claudioandre-br/johntheripper/builds/23247062/job/s5pwwwxbxoolf4qq

**Comment by IlyaFinkelshteyn** [comment]
There were no platform updates during this period: https://www.appveyor.com/updates/

Also I see that build scenario has been changed since last successful build. At least one difference that successful build installs `openssl-devel` while failed installs `libssl-devel`.

Please open March 6 successful build and press `RE-BUILD COMMIT` to eventually rule out platform changes.

**Comment by claudioandre-br** [comment]
The update is in CygWin itself.

As seen in https://cygwin.com/cgi-bin2/package-grep.cgi?grep=libssl-devel&arch=x86_64, openssl-devel no longer exist as a valid package (it resolves to `libssl1.1`).

* `openssl-devel-1.1.1b-1 - openssl-devel: Obsoleted by libssl-devel`

The build you want was done here (in March 21): https://ci.appveyor.com/project/claudioandre-br/johntheripper/builds/23246473/job/g0cuga88ag7fvdny

**Comment by IlyaFinkelshteyn** [comment]
Ah I see, sorry for misunderstanding.

**Comment by IlyaFinkelshteyn** [comment]
Updated
