### ISSUE TITLE
Python 2 encoding during PR difference

### ISSUE THREAD

**Issue by henrykironde** [appveyor/ci#2899]
Hi Folks, hope this is the right place for this issue

Looks like there is diff created when Unicode characters cannot be decoded in utf-8.
This started happening recently.

**Repo branch** https://github.com/henrykironde/retriever/tree/g4

**Build** https://ci.appveyor.com/project/henrykironde/retriever/builds/23384688

**Diff error** https://ci.appveyor.com/project/henrykironde/retriever/builds/23384688/job/j51w5x7mdq266y7k#L658

**Comment by OwenMcDonnell** [comment]
I'm not sure if I am missing the big picture here, but I forked the repo and made one small change that allowed the build to "succeed" [here](https://ci.appveyor.com/project/OwenMcDonnell/retriever/builds/23481627).
But again, please correct me if I have misunderstood the problem

**Comment by henrykironde** [comment]
Thanks @OwenMcDonnell for looking into this, really appreciate the time. Previously both python 2 and 3 were passing without changing to utf-8. However, we have decided to drop python2. We could close this and may be refer to it if something comes up.
