### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by chronoxor** [appveyor/ci#2907]
Can you please give estimations when the "Visual Studio 2019" image will be available?

**Comment by EwoutH** [comment]
[Visual Studio 2019 version 16.0.1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.0.1) is out now

**Comment by EwoutH** [comment]
[Visual Studio 2019 version 16.0.3](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes?view=vs-2019#16.0.3) was just released.

Any ETA on the VS 2019 image?

**Comment by IlyaFinkelshteyn** [comment]
Should be available this month, but cannot give a specific promises.

**Comment by Zingam** [comment]
> 
> 
> Should be available this month, but cannot give a specific promises.

Are the preview versions of VS2019 (currently 16.1.0) supported/included? I adopt some C++20 features as they become available.

**Comment by IlyaFinkelshteyn** [comment]
First draft of `Visual Studio 2019` image is available. At the moment we do not have an official list of installed software. but you can get a good idea by looking into respective [packer configuration](https://github.com/appveyor/build-images/blob/master/vs2019.json).

We will update the image per your feedback.

We enable it per request now. We already enabled it for those who reacted to [this comment](https://github.com/appveyor/ci/issues/2907#issuecomment-488345102). Send us your AppVeyor account if you do not see this image available for you.

Note that this image runs on Azure so build `Starting` stage will be 2-4 minutes (time to provision Azure VM).

**Comment by EwoutH** [comment]
@IlyaFinkelshteyn Thanks for the update!

Could you add https://github.com/Xiph, https://github.com/OpenVisualCloud and https://github.com/EwoutH?

**Comment by IlyaFinkelshteyn** [comment]
@EwoutH please try now... hopefully I guessed AppVeyor accounts (which are not always the same as GitHub users) correctly.

**Comment by mikejsavage** [comment]
Please could you enable it for this account? Appveyor user is also mikejsavage

**Comment by IlyaFinkelshteyn** [comment]
@mikejsavage enabled

**Comment by xt0rted** [comment]
@IlyaFinkelshteyn could you enable it for this account please?

**Comment by IlyaFinkelshteyn** [comment]
@xt0rted done, please try.

**Comment by Croydon** [comment]
@IlyaFinkelshteyn Could you please enable for `bincrafters` (both AppVeyor and GitHub name)?

**Comment by IlyaFinkelshteyn** [comment]
@Croydon sure, it is enabled. It was actually enabled already as we did it for all who reacted to [this comment](https://github.com/appveyor/ci/issues/2907#issuecomment-488345102) :)

**Comment by Croydon** [comment]
@IlyaFinkelshteyn Thanks!

The current installed CMake version is 3.13 https://github.com/appveyor/build-images/blob/09fe483c20cfc4dd6218deb0037a10a9dc98f035/scripts/Windows/install_cmake.ps1#L1

Unfortunately, only CMake >= 3.14 is supporting Visual Studio 2019 so all CMake builds are blocked for the moment until CMake gets upgraded

https://cmake.org/cmake/help/v3.14/release/3.14.html#generators

**Comment by matt77hias** [comment]
@IlyaFinkelshteyn could you enable it for this account please?

**Comment by IlyaFinkelshteyn** [comment]
@mancoast done.

**Comment by LePresidente** [comment]
@IlyaFinkelshteyn Could you enable it for the Appveyor Username "ModOrganizer2" Its the main appveyor account used by our team

**Comment by neilboyd** [comment]
@IlyaFinkelshteyn Please could you enable it for the account NIPOSoftware. Thanks.

**Comment by EwoutH** [comment]
- Please update Visual Studio 2019 image to [Visual Studio 2019 version 16.1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.1.0)
- Please update Visual Studio 2019 Preview image to [Visual Studio 2019 version 16.2 Preview 1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.1.0)

**Comment by atifaziz** [comment]
@IlyaFinkelshteyn Would be much appreciated if you could enable it for my account called **raboof**.

**Comment by chronoxor** [comment]
@IlyaFinkelshteyn Please enable for my account. I can test it on my open source projects!

**Comment by IlyaFinkelshteyn** [comment]
@matt77hias @chronoxor @atifaziz @neilboyd @LePresidente enabled.

**Comment by TheQwertiest** [comment]
@IlyaFinkelshteyn could you enable it for this account please?

On the related note: is it possible to add Windows SDK 10.0.18362.0 to the image? And was VS updated to the recently released 16.1?

**Comment by neilboyd** [comment]
@IlyaFinkelshteyn are you planning to add docker to the vs2019 image?

**Comment by chronoxor** [comment]
CMake is also should be updated to 3.14 because of "Visual Studio 16 2019" generator.

**Comment by LePresidente** [comment]
@IlyaFinkelshteyn Will boost 1.70 and QT 5.12.3 be added to this new image as well?

**Comment by IlyaFinkelshteyn** [comment]
@TheQwertiest enabled. WDK 1903 is [coming](https://github.com/appveyor/build-images/pull/5/files#diff-f709f3bd2210d5ded18e45f3a219633d).

**Comment by IlyaFinkelshteyn** [comment]
@neilboyd We have [Windows Server 2019](https://ci.appveyor.com/project/appveyor-tests/win2k19-azure) image for all kinds of Docker/WSL experiments and can enable it for you. This one however has only Visual Studio 2017 installed. Do you need Visual Studio 2017 **and** Docker?

**Comment by IlyaFinkelshteyn** [comment]
@LePresidente It should not be any issues to add boost 1.70. However we are not sure about QT. Will adding just boost 1.70 helps or it makes sense only with QT?

**Comment by neilboyd** [comment]
@IlyaFinkelshteyn I'm currently using the `Visual Studio 2017` image. That has Docker installed. I was hoping to change to `Visual Studio 2019` and still have Docker.
But it's not urgent.
I saw that you added Docker and then [removed it again](https://github.com/appveyor/build-images/commit/25c120f962ad9ce6ac60bce751984ea749e6b956), so I was wondering if you were planning to put it back again.

**Comment by IlyaFinkelshteyn** [comment]
@neilboyd Ah this image initially was created on the basis of [Windows Server 2019](https://github.com/appveyor/build-images/blob/master/windows.json) and this removed part is what I forgot to delete. I think we will merge both images later, when `Visual Studio 2019` stabilize. At the moment adding Docker (and hydrating it with all commonly using images) adds few hours to the image Packer build, but we want a quicker turnaround at this stage.

**Comment by neilboyd** [comment]
@IlyaFinkelshteyn Thanks. I can wait 😄

**Comment by Silarn** [comment]
@LePresidente @IlyaFinkelshteyn Actually, the preview image currently only has 5.11 which causes the main project to fail since it does use a feature introduced in 5.12. The rest of the projects are building. Going from 5.12.2 to 5.12.3 isn't the most important thing, but it would be nice to have for the fixes it includes. Boost 1.70 would be good, though it's mostly a dependency for us during the build process as it's the first version to support VS2019. If it's prebuilt it's not as important AFAIK.

**Comment by xt0rted** [comment]
@IlyaFinkelshteyn I'm using this with .net core and so far there's no issues.

**Comment by IlyaFinkelshteyn** [comment]
@TheQwertiest Windows SDK 10.0.18362.0 installed
@chronoxor Cmake 3.14 installed
@EwoutH Visual Studio 2019 version 16.1 installed

**Comment by IlyaFinkelshteyn** [comment]
@xt0rted thanks a lot for the update!

**Comment by chronoxor** [comment]
Found issue with setup/update Cygwin packages with commands:
```
  - if not exist "C:\cygwin64" mkdir "C:\cygwin64"
  - appveyor-retry appveyor DownloadFile "http://cygwin.com/setup-x86_64.exe" -FileName "C:\cygwin64\setup-x86_64.exe"
  - C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --root "C:\cygwin64" --local-package-dir "C:\cache\cygwin" --packages cmake,automake,make,gcc-core,gcc-g++,libjsoncpp19,librhash0,libuv1
```

got the build hangs and the last output was:
```
Starting cygwin install, version 2.897
User has backup/restore rights
io_stream_cygfile: fopen(/etc/setup/setup.rc) failed 2 No such file or directory
Current Directory: C:\cache\cygwin
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: C:\cygwin64 system
Selected local directory: C:\cache\cygwin
net: Preconfig
```

**Comment by XhmikosR** [comment]
@IlyaFinkelshteyn: can you enable the VS2019 image for my account? Thanks!

**Comment by RehanSaeed** [comment]
Please enable for my account. Thank you!

**Comment by Zingam** [comment]
I see only `Visual Studio 2019 Preview` is that it or there is a `Visual Studio 2019` image that I should see?

**Comment by IlyaFinkelshteyn** [comment]
@XhmikosR @ucpu-bot @RehanSaeed @Zingam enabled. Sorry for some delay :)

**Comment by janisozaur** [comment]
Please enable this for my account: `janisozaur` and the ones of OpenRCT2 team: `IntelOrca` and OpenLoco's: `AaronVanGeffen`

**Comment by IlyaFinkelshteyn** [comment]
@janisozaur done

**Comment by Zingam** [comment]
@IlyaFinkelshteyn please install the Ninja build system: https://ninja-build.org/
It is just a few kilobytes but it is the best way to build CMake projects even with VS2019, which supports CMake+Ninja builds by default from within the IDE.

**Comment by IlyaFinkelshteyn** [comment]
@Zingam @chronoxor how you workaround this now? Do you use https://chocolatey.org/packages/ninja?

**Comment by Zingam** [comment]
@IlyaFinkelshteyn I use python pip on Windows (because I am too lazy do as others do it) and apt install on linux.
Actually when I think about it. CMake & Ninja must be already installed inside of VS2019 as part of the C++ work item and are used by VS2019 default. Unfortunately they are not in the PATH.

**Comment by EwoutH** [comment]
@IlyaFinkelshteyn I would really love Ninja and Meson pre-installed! (see #2835)

**Comment by moh-hassan** [comment]
vs2019 v16.1.1 is [out ](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)May 24, 2019

**Comment by Luckz** [comment]
My account too please.

**Comment by ashalkhakov** [comment]
Could you please add my account?

**Comment by moh-hassan** [comment]
@IlyaFinkelshteyn 
I  tested the image of vs2019 and it's working fine.
Thanks for help and support.

**Comment by EwoutH** [comment]
The SVT encoders have been running on Visual Studio 2019 over the last weekend, and they perform fine!

[SVT-AV1](https://github.com/OpenVisualCloud/SVT-AV1) | [SVT-VP9](https://github.com/OpenVisualCloud/SVT-VP9) | [SVT-HEVC](https://github.com/OpenVisualCloud/SVT-HEVC)

**Comment by IlyaFinkelshteyn** [comment]
@Luckz @ashalkhakov added

**Comment by mloskot** [comment]
Why not to just release the image to the public?

Or, what's the time frame to expect it to happen?

**Comment by chronoxor** [comment]
Cygwin issue is fixed for me using additional `--site "http://mirrors.kernel.org/sourceware/cygwin"` command line argument

**Comment by nblumhardt** [comment]
@IlyaFinkelshteyn can you please add support to the @serilog account? Thanks!

**Comment by nblumhardt** [comment]
Cancel that - just tried my luck and it seems we can use it already :-)

**Comment by EwoutH** [comment]
@IlyaFinkelshteyn Could you add https://ci.appveyor.com/project/tdaede/rav1e ?

**Comment by IlyaFinkelshteyn** [comment]
We actually made `Visual Studio 2019` image available for everyone. Though it is still not mature enough, so please send us what we need to add there.

CC @mloskot

**Comment by chronoxor** [comment]
@IlyaFinkelshteyn, all my builds passed with new `Visual Studio 2019` image! Thanks a lot!

I have to update Cygwin with some packages for my build and install the latest MinGW with additional steps:
```
  # Cygwin
  - if "%type%"=="Cygwin" if not exist "C:\cygwin64" mkdir "C:\cygwin64"
  - if "%type%"=="Cygwin" appveyor-retry appveyor DownloadFile "http://cygwin.com/setup-x86_64.exe" -FileName "C:\cygwin64\setup-x86_64.exe"
  - if "%type%"=="Cygwin" C:\cygwin64\setup-x86_64.exe --quiet-mode --no-desktop --no-shortcuts --upgrade-also --root "C:\cygwin64" --local-package-dir "C:\cache\cygwin" --site "http://mirrors.kernel.org/sourceware/cygwin" --packages cmake,automake,make,gcc-core,gcc-g++,libjsoncpp19,librhash0,libuuid-devel,libuv1
  # MinGW
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
```

It will be great if you update Cygwin with some useful packages (`cmake,automake,make,gcc-core,gcc-g++,libjsoncpp19,librhash0,libuuid-devel,libuv1`) in `C:\cygwin64` and put the latest MinGW 8.1.0 to `C:\mingw64`.

Thanks in advance!

**Comment by Cheesebaron** [comment]
JavaSDK environment variable doesn't seem to be set, which makes Xamarin Android builds fail:

```
error XA5300: The Java SDK Directory could not be found. Please set via /p:JavaSdkDirectory.
```

**Comment by craftwar** [comment]
VS2019 and VS2017 are ABI-compatible, user may want to use VS2019 in VS2017 projects. It is reasonable to add everything in VS2017 image to VS2019 image.
Is it possible to just add VS2019 into VS2017 image? Can you make VS2019 and VS2017 images the same but default Visual Studio version different?

**Comment by XVilka** [comment]
I found that Inno Setup (presented in the older images) is now missing from VS2019 one: https://github.com/appveyor/ci/issues/2948

**Comment by NN---** [comment]
Please provide clang-cl with Visual Studio 2019 image.

**Comment by ashalkhakov** [comment]
Could you please provide WiX 3.11?

**Comment by heydojo** [comment]
Hi!
Looking forward to trying out the following components in the up coming 2019 image:

- IncrediBuild
- MSBuild
- MSVC v142 (v14.21) Minimum
- MSVC v142 Spectre mitigation Libs (v14.21) Minimum
- C++ Core Features
- Windows 10 SDK (10.0.18362.0) Minimum
- Windows Universal C runtime

Cheers!

**Comment by JustArchi** [comment]
@IlyaFinkelshteyn `java` command is missing in Visual Studio 2019 image, please consider adding at least one JDK (currently available in 2017 image), thank you!

**Comment by IlyaFinkelshteyn** [comment]
@JustArchi @XVilka please watch https://github.com/appveyor/ci/issues/2961

**Comment by IlyaFinkelshteyn** [comment]
@ashalkhakov please watch https://github.com/appveyor/ci/issues/2963

**Comment by IlyaFinkelshteyn** [comment]
@NN---  please watch https://github.com/appveyor/ci/issues/2964

**Comment by IlyaFinkelshteyn** [comment]
@heydojo can you please create separate issues? Please check with https://github.com/appveyor/ci/milestone/144 that no duplicates happened

**Comment by IlyaFinkelshteyn** [comment]
I am closing this issue, because it is difficult to track requests to add a software in comments. Please create a separate new issue if for each new software to add to `Visual Studio 2019` image. Please check https://github.com/appveyor/ci/milestone/144 to avoid duplicates.
