### ISSUE TITLE
Enable TTY mode for colored output

### ISSUE THREAD

**Issue by jawshooah** [appveyor/ci#291]
Many programs, such as [RSpec](http://rspec.info/) will only print colored output if a TTY is available. Is it possible for the Appveyor builder to emulate a TTY?

**Comment by FeodorFitsner** [comment]
Never though about that. Is it like running a build script through PuTTY? Are there any esc codes returned to console controlling the output?

**Comment by jawshooah** [comment]
I'm not sure exactly how you would emulate it; Windows is not my primary platform.

In any case, RSpec apparently has a `--tty` flag that forces the output destination to be treated as a TTY, so my particular use case is resolved.

**Comment by FeodorFitsner** [comment]
OK, great. I'm closing this issue then.
