### ISSUE TITLE
appveyor cmake can't find Qt5WebEngine (5.12.1) Components

### ISSUE THREAD

**Issue by dougmassay** [appveyor/ci#2914]
Just what the title says. Cmake on the Visual Studio 2015 image can find all Qt5.12.1 components except Qt5WebEngine and Qt5WebEngineWidgets.

```
-- Could NOT find Qt5WebEngine (missing: Qt5WebEngine_DIR)
-- Could NOT find Qt5WebEngineWidgets (missing: Qt5WebEngineWidgets_DIR)
CMake Warning at src/CMakeLists.txt:58 (find_package):
  Found package configuration file:
    C:/Qt/5.12.1/msvc2015_64/lib/cmake/Qt5/Qt5Config.cmake
  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:
  Failed to find Qt5 component "WebEngine" config file at
  "C:/Qt/5.12.1/msvc2015_64/lib/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake"
  Failed to find Qt5 component "WebEngineWidgets" config file at
  "C:/Qt/5.12.1/msvc2015_64/lib/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfig.cmake"
```

**Comment by dougmassay** [comment]
Never mind. It seems in their infinite wisdom, Qt/Chrome have decided that VS2017 (and the Windows 10 SDK) is the bare minimum requirement to even _build_ the QtWebEngine being included with Qt5.12.x installers. So it doesn't make much sense to be looking to use it with the VS2015 worker image and the pre-installed msvc2015_64 Qt, now, does it?

At this rate, VS2019 Preview will be required to build apps with the QtWebEngine included with Qt5.12.3. *eyeroll*

**Comment by IlyaFinkelshteyn** [comment]
Thanks for the update. FYI: we are working on `Visual Studio 2019` image with GA VS version currently.
