### ISSUE TITLE
vcpkg 2019.06.26-nohash

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2919]

**Comment by heydojo** [comment]
The file to track the version bumps in vcpkg is:  [toolsrc/VERSION.txt](https://github.com/microsoft/vcpkg/blob/master/toolsrc/VERSION.txt) and vcpkg version **2019.06.26** can be pulled using commit: _269fa0e6be13ebe64060323579a2af68c0a21e4c_

https://github.com/microsoft/vcpkg/commit/269fa0e6be13ebe64060323579a2af68c0a21e4c#diff-de54440f3045d249f145776d1590b803
