### ISSUE TITLE
GitHub integration issue: "Request to GitHub web hook has been made from prohibited IP address"

### ISSUE THREAD

**Issue by ashmind** [appveyor/ci#2922]
Some of my recent pushes didn't trigger AppVeyor builds. When I investigated, I saw that recent webhook calls are failing with "Request to GitHub web hook has been made from prohibited IP address".

![image](https://user-images.githubusercontent.com/166396/56651197-a0e96780-66dc-11e9-9389-e2582cf0b0e0.png)

I can't see the address that GitHub is using, but I assume it might be related to https://github.blog/changelog/2019-04-09-webhooks-ip-changes?

**Comment by TomGrobbe** [comment]
Getting the same issue. 😕

**Comment by MattLangers** [comment]
Thought its good to know that we are also suffering with the same problem 🤕

**Comment by FeodorFitsner** [comment]
The issue has been resolved: https://status.appveyor.com/incidents/378v468f35qq
