### ISSUE TITLE
.NET Framework 4.8 support

### ISSUE THREAD

**Issue by RalfKoban** [appveyor/ci#2924]
It would be great if the `.NET Framework 4.8` is supported on the build machines.
That would allow me to update my projects to .NET 4.8 without breaking the build.

**Comment by xt0rted** [comment]
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by SeppPenner** [comment]
Same here, this would be a great feature...

**Comment by msallin** [comment]
Is there a timeline?

**Comment by IlyaFinkelshteyn** [comment]
Sorry guys for delay. We plan images update for the next week. Meanwhile please use this workaround (consumes about 3 minutes of the build):

```
install:
- ps: |
    function install-devpack ($version, $location) {
        Write-Host ".NET Framework $($version) Developer Pack..." -ForegroundColor Cyan
        Write-Host "Downloading..."
        $exePath = "$env:TEMP\$($version)-devpack.exe"
        (New-Object Net.WebClient).DownloadFile($location, $exePath)
        Write-Host "Installing..."
        cmd /c start /wait "$exePath" /quiet /norestart
        del $exePath
        Write-Host "Installed" -ForegroundColor Green
    }
    install-devpack -version "4.8" -location "https://download.visualstudio.microsoft.com/download/pr/7afca223-55d2-470a-8edc-6a1739ae3252/c8c829444416e811be84c5765ede6148/ndp48-devpack-enu.exe"
    Write-Host "Restarting build VM..."
    sleep 5
    Restart-Computer -Force
    sleep 5
    Write-Host "Restarted" -ForegroundColor Green
```

**Comment by alexrp** [comment]
Just checking since it's been 2 weeks, what's the status on this issue?

**Comment by IlyaFinkelshteyn** [comment]
Try to make https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_dotnet_devpack.ps1 idempotent to run on older non-packer images
