### ISSUE TITLE
Update Rubies - 2.4.6, 2.5.5, 2.6.3

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2926]
Releases are available at:
https://github.com/oneclick/rubyinstaller2/releases

Thanks, Greg

**Comment by IlyaFinkelshteyn** [comment]
[internal note] Update 2.4.x, 2.5.x, 2.6.x URLs in https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_ruby.ps1
