### ISSUE TITLE
continuous-integration/appveyor/branch status report is not coming.

### ISSUE THREAD

**Issue by Ausm** [appveyor/ci#2931]
This PR https://github.com/Ausm/ObjectStore/pull/39 gets stuck even though all build ran through successfuly.
Am I doing anything wrong?

**Comment by IlyaFinkelshteyn** [comment]
From what I see, it says `continuous-integration/appveyor/branch Expected`, which means that you enabled this status check with as described [here](https://help.github.com/en/articles/enabling-required-status-checks). However in your [build history](https://ci.appveyor.com/project/Ausm/objectstore/history) I see only Pull request builds, and not PR builds lately. It seems that you disabled branch builds either in AppVeyor project General Setting UI, or in GitHub project webhook setting. If you indeed need only PR builds for protected branch, remove `appveyor/branch`  from the status check, or enable branch builds back.

**Comment by Ausm** [comment]
Thanks, I think that was due to the change of the .yml file.
I think this caused the branch not to build any more.
```
branches:  
  only:
  - master
  - V1
```
But since I only need a buildable merge product, I think I can skip those branch builds.
Thanks for your help.
