### ISSUE TITLE
aws cli on win2k19

### ISSUE THREAD

**Issue by alangford** [appveyor/ci#2934]
when running aws commands on the build process we are getting this error

` "aws : The term 'aws' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again." 
`

fixing it by manually installing aws cli but if it came pre-installed on the image that would be great!

**Comment by IlyaFinkelshteyn** [comment]
Sure, will do. You can use [this script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_aws_cli.ps1) as a temporary workaround.

**Comment by alangford** [comment]
That script successfully installs the aws cli but i am still seeing the same error above.

If i rdp into the build instance I'm able to use aws commands but the build is not able to. 

Any recommendations?

**Comment by alangford** [comment]
I think i found a work around I'm just using the exe path `& "C:\Program Files\Amazon\AWSCLI\aws.exe"` rather then the alias command and it is working now.

Thanks again!

**Comment by IlyaFinkelshteyn** [comment]
Yeah, just [updated](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_aws_cli.ps1#L11-L12).

**Comment by IlyaFinkelshteyn** [comment]
Updated image has been deployed.
