### ISSUE TITLE
Window 10 SDK 1903 10.0.18362.0

### ISSUE THREAD

**Issue by amerkoleci** [appveyor/ci#2938]
Would be possible to add 10.0.18362.0 SDK?

https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-18362

Thanks

**Comment by IlyaFinkelshteyn** [comment]
Yes, thank you.

**Comment by IlyaFinkelshteyn** [comment]
We plan updating the image in about a week. Temporary workaround is to run [this](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_wdk_1903.ps1) script at `install` stage.

**Comment by IlyaFinkelshteyn** [comment]
+ WDK 1903 (10.0.18362.1).
