### ISSUE TITLE
VS2019 image: Microsoft.CppBuild.targets(379,5): error MSB8020: The build tools for v142_xp (Platform Toolset = 'v142_xp') cannot be found.

### ISSUE THREAD

**Issue by XVilka** [appveyor/ci#2944]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8020: The build tools for v142_xp (Platform Toolset = 'v142_xp') cannot be found. To build using the v142_xp build tools, please install v142_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\projects\radare2-shvdd\build\REGEN.vcxproj]
```

See the full log here: https://ci.appveyor.com/project/radare/radare2-shvdd/builds/24853460/job/imhh2q4ma52d31tr

Trying to setup VS2019 builds on new image: https://github.com/radare/radare2/pull/13345/files

**Comment by IlyaFinkelshteyn** [comment]
@XVilka can you please clarify what component from [this list](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019) should be installed? 

We recently added `v141_xp`, as you can see [here](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_vs2019.ps1#L87), but I am not sure what should be done to add `v142_xp` and not sure it is even supported according to [this](https://docs.microsoft.com/en-us/cpp/porting/features-deprecated-in-visual-studio?view=vs-2019)

**Comment by XVilka** [comment]
@IlyaFinkelshteyn oh, didn't knew about this deprecation. Thanks for the link, then I just should change our build scripts.
