### ISSUE TITLE
Inno Setup 6.0.2 on Visual Studio 2019

### ISSUE THREAD

**Issue by XVilka** [appveyor/ci#2948]
It was installed in the VS2015 and VS2017 images, but is missing in VS2019.

**Comment by omichel** [comment]
It would be even better to install Inno Setup 6 which is backward compatible with Inno Setup 5 but offer major improvements (including the capability to create non-administrator installers).

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.

**Comment by omichel** [comment]
Where is that documented? I cannot find any reference to Inno Setup 6 here: https://www.appveyor.com/docs/windows-images-software/ (it still refers to Inno Setup 5.5.9)

**Comment by omichel** [comment]
Was it really deployed? I can see this PR https://github.com/appveyor/build-images/pull/12 was not yet merged to the master branch.

**Comment by IlyaFinkelshteyn** [comment]
@omichel yes it is deployed from the branch. You cannot see the build itself, as it is a private project running Packer build.

**Comment by IlyaFinkelshteyn** [comment]
And sorry for delay with documentation. Current one covers only older images (not `Visual Studio 2019` yet). We are working on documentation change to reflect `Visual Studio 2019` image too.

**Comment by omichel** [comment]
Great, thank you!
