### ISSUE TITLE
'yarn' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by louisnayegon** [appveyor/ci#2949]
https://ci.appveyor.com/project/louisnayegon/packer-strategy/build/job/g5y0k8t8w9mee6ja

Looks like Visual Studio 2019 image does not have yarn in it whereas 2017 does

**Comment by IlyaFinkelshteyn** [comment]
Sure, will add it. Meanwhile please use [this](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_yarn.ps1) script or Chocolatey (`choco install yarn`) at `install` stage.

**Comment by IlyaFinkelshteyn** [comment]
Update deployed
