### ISSUE TITLE
Allow expanding ZIP files when uploading artifacts to Amazon S3

### ISSUE THREAD

**Issue by mwhouser** [appveyor/ci#295]
Discussion: http://help.appveyor.com/discussions/suggestions/706-expanding-artifact-to-upload-to-s3

**Comment by lubos** [comment]
I would love to see this too. If you have a project which is generating static website to be uploaded to S3, it makes sense to generate artifact in ZIP format.

**Comment by ahilliker** [comment]
This feature would save a lot of .yml complexity.  I would also love to see this happen.  Thanks!

**Comment by IlyaFinkelshteyn** [comment]
It is done and [doc updated](https://www.appveyor.com/docs/deployment/amazon-s3/)

**Comment by ahilliker** [comment]
AWESOME!  Thanks; I'll check it out.
