### ISSUE TITLE
Bearer Token authentication not working when 2FA enabled

### ISSUE THREAD

**Issue by meganaut** [appveyor/ci#2950]
I am trying to build a script to find the first occurrence of some sporadically failing test by scanning the build logs for failed builds in a project.

My company has 2FA enabled for logging in to the front end, but this appears to be causing issues with api authentication.

When creating a Bearer token via the API Keys page and using it for api requests.
e.g. 
``` curl -X GET \
  https://ci.appveyor.com/api/projects/{my account}/{project} \
  -H 'Authorization: Bearer {my bearer token}' \
  -H 'cache-control: no-cache'
```

I always get the response:

```
{
    "message": "Account cannot be accessed with current authentication method."
}
```

I am only assuming this is related to 2FA. I cannot disable it for the company to test if it is actually the issue.

**Comment by IlyaFinkelshteyn** [comment]
Do you have API authentication methods enabled at `https://ci.appveyor.com/account/{my account}/security`?

**Comment by meganaut** [comment]
That was absolutely the issue! thanks @IlyaFinkelshteyn
