### ISSUE TITLE
Install Google Chrome on Visual Studio 2019 image

### ISSUE THREAD

**Issue by spapaseit** [appveyor/ci#2952]
Build fails due to Karma tests not being able to launch Chrome when using  `os: Visual Studio 2019`, and they work with `os: Visual Studio 2017`.

using `choco install googlechrome` fixes the issue.

Can we get Chrome installed by default on the `Visual Studio 2019` image?

**Comment by IlyaFinkelshteyn** [comment]
Sure, will do with the next update

**Comment by heydojo** [comment]
Please check the license for the widevine drm plugin which ships with Chrome.

>  Google LLC and its affiliates ("Google") own all legal right, title and
> interest in and to the content decryption module software ("Software") and
> related documentation, including any intellectual property rights in the
> Software. You may not use, modify, sell, or otherwise distribute the Software
> without a separate license agreement with Google.  The Software is not open
> source software.
> 
> If you are interested in licensing the Software, please contact www.widevine.com

You probably want a Chromium build instead. Or at least delete the file widevinecdm.dll from a Chrome installation in an image. Widevine is completely proprietary and the license is pretty clear about redistribution.

**Comment by heydojo** [comment]
I might add that if Chocolatey are unaware about the widevine drm licensing, then someone should let them know too. So that they don't fall foul of the licensing.

**Comment by IlyaFinkelshteyn** [comment]
Update deployed
