### ISSUE TITLE
DirectX SDK on Visual Studio 2019 image

### ISSUE THREAD

**Issue by ThirteenAG** [appveyor/ci#2953]
Basically same as [this](https://github.com/appveyor/ci/issues/1721), unless there's any reason it wasn't included in the first place?

**Comment by heydojo** [comment]
To avoid confusion. @ThirteenAG is talking specifically about the lack of inclusion of the DXSDK on the **2019 image** just like the 2017 image as detailed here for the 2017 image:
https://www.appveyor.com/docs/windows-images-software/#windows-sdks

**Comment by IlyaFinkelshteyn** [comment]
@ThirteenAG @heydojo can you please clarify what specific version you need?

**Comment by ThirteenAG** [comment]
I believe there's only one version, which I usually download from this link: https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe

**Comment by heydojo** [comment]
`can you please clarify what specific version you need?`

As mentioned by @ThirteenAG :

**DXSDK_Jun10**

(the same version present on the Appveyor Visual Studio 2017 image.) It's the old DirectX (9) SDK which many applications have not migrated away from due to the lack of backwards compatibility and a need for cross platform support.

**Comment by mirh** [comment]
Up?

**Comment by IlyaFinkelshteyn** [comment]
Closing as a duplicate to https://github.com/appveyor/ci/issues/3089. That issue will be closed by the end of September. Also https://github.com/appveyor/ci/issues/3089 has a temporary workaround. Sorry doe the delay with it.

**Comment by IlyaFinkelshteyn** [comment]
Copying temporary workaround... For now you can install in on-the-fly by adding this script at `init` or `install` stage. It will consume couple of minute though.

```
Write-Host "DirectX Software Development Kit..." -ForegroundColor Cyan

Write-Host "Downloading..."
$exePath = "$env:temp\DXSDK_Jun10.exe"
(New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)

Write-Host "Installing..."
$installPath = "C:\Program Files (x86)\Microsoft DirectX SDK"
cmd /c start /wait $exePath /P $installPath /U
Add-Path $installPath
Add-SessionPath $installPath

Remove-Item $exePath
Write-Host "Installed" -ForegroundColor Green
```

**Comment by ThirteenAG** [comment]
@IlyaFinkelshteyn there's some kind of a problem with installed DXSDK now.
This build compiled fine 3 months ago with manually downloaded dxsdk:
https://ci.appveyor.com/project/ThirteenAG/ultimate-asi-loader/builds/26218278
Now same build:
https://ci.appveyor.com/project/ThirteenAG/ultimate-asi-loader/builds/28266038
can't compile due to the following error:
`LINK : fatal error LNK1104: cannot open file 'd3dx9.lib' `
It worked before with VS2017 as well.

**Comment by FeodorFitsner** [comment]
Could it be applicable to your case: https://stackoverflow.com/questions/17015088/missing-files-directx-sdk-d3dx9-lib-d3dx9-h?

**Comment by ThirteenAG** [comment]
Paths seem fine to me
https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/premake5.lua#L35
And I mean, it used to work just fine, I didn't change anything at all and was using DXSDK_DIR all the time.

**Comment by ThirteenAG** [comment]
Hm, it looks like there's a line missing in premake file,
`local dxsdk = os.getenv "DXSDK_DIR"`

And it used to work due to provided hardcoded default path. Nevermind then.
