### ISSUE TITLE
AppVeyor OnPremise: Deploy to Environment never finishes the build

### ISSUE THREAD

**Issue by itniels** [appveyor/ci#2957]
Using Docker Ubuntu image:
When deploying to an Environment setup in AppVeyor, it never sees that deployment was success/failed and therefore never finishes the build.

```
deploy:
  - provider: Environment
    name: FTP-MyServer
```

Deployment was successful, but build is still running and waiting.

**Comment by FeodorFitsner** [comment]
The error appears on AppVeyor Server side, so once the update is released AppVeyor Server must be updated to the latest version.
