### ISSUE TITLE
The build tools for llvm (Platform Toolset = 'llvm') cannot be found on VS2019 image.

### ISSUE THREAD

**Issue by JayXon** [appveyor/ci#2958]
Works fine on VS2017 image.
https://ci.appveyor.com/project/JayXon/leanify/builds/24978604

**Comment by IlyaFinkelshteyn** [comment]
https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_llvm.ps1
https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain

**Comment by zufuliu** [comment]
https://bugs.llvm.org/show_bug.cgi?id=41948

**Comment by IlyaFinkelshteyn** [comment]
Update deployed
