### ISSUE TITLE
Java and JDK (1.7, 1.8, 11.0.2, 12) on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2961]
https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_java.ps1
https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_jdk11.ps1
https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_jdk12.ps1

**Comment by IlyaFinkelshteyn** [comment]
Delaying till the next update as a lot of download links worked before are broken. Need some time to review a setup script.

**Comment by Cheesebaron** [comment]
I tried running my own script in the `install` phase:

```yaml
install:
  - appveyor-retry powershell .\install-openjdk.ps1
```

However, it seems like setting Environment Variables from the script doesn't work.

My script looks something like this:

```powershell
$openjdk_version = "1.8.0.25"
$download_url = "https://dl.xamarin.com/OpenJDK/mac/microsoft-dist-openjdk-" + $openjdk_version + ".zip"

Write-Host "Installing OpenJDK ..." -ForegroundColor Cyan

$jdkPath = "C:\Program Files\Android\jdk\microsoft_dist_openjdk_" + $openjdk_version

if(Test-Path $jdkPath) {
    Remove-Item $jdkPath -Recurse -Force
}

Write-Host "Downloading..."
$zipPath = "$env:TEMP\microsoft-dist-openjdk-" + $openjdk_version + ".zip"
(New-Object Net.WebClient).DownloadFile($download_url, $zipPath)

Write-Host "Unpacking..."
7z x $zipPath -oC:\openjdk_temp | Out-Null
[IO.Directory]::Move('C:\openjdk_temp', $jdkPath)
del $zipPath

Write-Host "Setting ENV var..."
[Environment]::SetEnvironmentVariable("JAVA_HOME", "C:\Progra~1\Android\jdk\microsoft_dist_openjdk_" + $openjdk_version, "machine")
[Environment]::SetEnvironmentVariable("JAVA_SDK", "C:\Progra~1\Android\jdk\microsoft_dist_openjdk_" + $openjdk_version, "machine")
$env:JAVA_HOME="C:\Progra~1\Android\jdk\microsoft_dist_openjdk_" + $openjdk_version
$env:JAVA_SDK="C:\Progra~1\Android\jdk\microsoft_dist_openjdk_" + $openjdk_version

Add-Path $jdkPath
Add-Path $jdkPath + "\bin"
```

**Comment by ice1000** [comment]
Any updates on this?

**Comment by FeodorFitsner** [comment]
It's coming next week, sorry for the delay.

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/61119083-19ec9580-a468-11e9-815d-0b29259c4ed6.png)

How are things going now?

**Comment by IlyaFinkelshteyn** [comment]
Sorry for those delays. We hit some blocking issues while testing updated image so it was delayed. I hope it will be out sometime next week.

**Comment by ice1000** [comment]
Ok

**Comment by ice1000** [comment]
No worries, we love AppVeyor

**Comment by martijn00** [comment]
@IlyaFinkelshteyn @FeodorFitsner any update on this?

**Comment by ice1000** [comment]
Is it still blocking?
![image](https://user-images.githubusercontent.com/16398479/62714002-ab014e80-b9cb-11e9-9fca-4dfbf79a3875.png)

**Comment by IlyaFinkelshteyn** [comment]
Sorry guys for all that delays. Working on it now. Will keep you in touch.

**Comment by ice1000** [comment]
Ok

**Comment by ice1000** [comment]
Is it closed as "fixed"?

**Comment by IlyaFinkelshteyn** [comment]
Yes

**Comment by IlyaFinkelshteyn** [comment]
Check https://www.appveyor.com/docs/windows-images-software/#java

**Comment by ice1000** [comment]
I love you
