### ISSUE TITLE
clang-cl on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2964]
`Microsoft.VisualStudio.Component.VC.Llvm.Clang` (https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019)

**Comment by Zingam** [comment]
1. A stand-alone version
http://releases.llvm.org/download.html#8.0.0
or
2.“Clang compiler for Windows,” an optional component of the “Desktop development with C++” workload
 https://devblogs.microsoft.com/cppblog/clang-llvm-support-in-visual-studio/

???

**Comment by IlyaFinkelshteyn** [comment]
@Zingam yes, I think `Microsoft.VisualStudio.Component.VC.Llvm.Clang` is exactly what we need (see commit https://github.com/appveyor/build-images/commit/107e549a1277bdf558a47759bce6c18cc5359901).

It would be great if you can help creating super simple build project which fails in case this component is absent. We would put it into https://github.com/appveyor-tests which we use to validate images.

**Comment by IlyaFinkelshteyn** [comment]
Update deployed
