### ISSUE TITLE
QT 5.13.1, 5.12.5, 5.9.8 on VS 2019 image

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2970]
https://github.com/appveyor/ci/issues/2907#issuecomment-494817682

**Comment by past-due** [comment]
In addition to the latest Qt 5 LTS release (5.12), would it be possible to include Qt 5.9 LTS (5.9.7), which is supported through 2020-05-31?

**Comment by arummler** [comment]
Do you have a time estimate for Qt on the 2019 image?

**Comment by skychef** [comment]
> 
> 
> In addition to the latest Qt 5 LTS release (5.12), would it be possible to include Qt 5.9 LTS (5.9.7), which is supported through 2020-05-31?

The advice from Qt is :

> If you are still using older Qt versions, I strongly encourage all active projects to migrate to Qt 5.12 LTS if possible.

https://www.qt.io/blog/qt-5.12.5-released

I understand @past-due that not everyone may be in a position to make the move just yet.

**Comment by skychef** [comment]
@IlyaFinkelshteyn I'm not sure yet but I don't think there is Qt 5.12.3 in the Appveyor Visual Studio 2019 image (as far as I can tell) because I just had a build against it fail.

I saw this :
https://github.com/appveyor/build-images/commit/206290b1e28e984868780e2e772bfe71601f62e6
And guessed it might be the reason for no Qt at all in that image?

Also:
https://www.appveyor.com/docs/windows-images-software/#qt
does not list the Qt versions inside of the Visual Studio 2019 image.

Might I suggest that the following versions are made available inside of the Visual Studio 2019 image?

- 5.9.7 (LTS)
- 5.12.5 (LTS)
- 5.13.1

Adding Qt 5.12.3 too, might also be a smart move. I mention this because Qt 5.12.5 is brand new and Qt 5.12.4 was a bad release.

**Comment by IlyaFinkelshteyn** [comment]
Reason that QT is not in that image is that this image creation is fully automated (while all previous ones are semi-automated and QT port was always done manually). QT silent install is quite challenging problem, which we are working on.

**Comment by arummler** [comment]
I had quite success using a qt installer file which I found somewhere (would need to check if necessary). My repository which is installing qt on the 2019 image can be found here:
https://github.com/eudaq/eudaq/blob/feature-CI-v1.x-dev/appveyor/qt-installer-windows.qs
https://github.com/eudaq/eudaq/blob/feature-CI-v1.x-dev/appveyor.yml

**Comment by IlyaFinkelshteyn** [comment]
@arummler Thank you so much, this is very helpful!

**Comment by skychef** [comment]
Thanks @IlyaFinkelshteyn for the clarification. It was confusing to me that Qt was absent. But that clears up the mystery :)

https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh

May help you with a Qt silent install, if bash for Windows is present in the image. It can do win64_msvc2017_64 and win64_mingw73.

https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh#n75

**Comment by mrexodia** [comment]
This installs Qt 5.12.4 and Qt Creator 4.10.0:

```
curl -O -L https://code.qt.io/cgit/qbs/qbs.git/plain/scripts/install-qt.sh 1>nul
sh install-qt.sh --directory /c/Qt --host windows_x86 --target desktop --toolchain win32_msvc2017 --version 5.12.4 qtbase qtquickcontrols qt3d qtcanvas3d qtlocation qtquick qtscript qtwebengine extras
sh install-qt.sh --directory /c/Qt --host windows_x86 --target desktop --version 4.10.0 qtcreator
```

**Comment by ismail** [comment]
https://www.appveyor.com/updates/ says this bug is fixed, but I can't seem to see C:\Qt\5.13\msvc2019_64, any ideas?

**Comment by FeodorFitsner** [comment]
Correct, there are no VS 2019 distros for 5.13 ([the list of all packages](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5131/Updates.xml)). However, you should use VS 2017 packages instead (C:\Qt\5.13\msvc2017_64) as they are binary-compatible.

**Comment by ismail** [comment]
> Correct, there are no VS 2019 distros for 5.13 ([the list of all packages](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5131/Updates.xml)). However, you should use VS 2017 packages instead (C:\Qt\5.13\msvc2017_64) as they are binary-compatible.

Great, thanks!

**Comment by jcelerier** [comment]
finally ! thanks !
