### ISSUE TITLE
Spectre-mitigated libraries on Visual Studio 2019

### ISSUE THREAD

**Issue by dmex** [appveyor/ci#2971]
Hello,

The Visual Studio 2019 build image doesn't include the spectre-mitigated libraries that were previously included with the 2018 build image.

Here's the build output from Appveyor:
https://ci.appveyor.com/project/processhacker/processhacker/builds/25131699

They're installed the same way as the VS2017 spectre libraries: 
![image](https://user-images.githubusercontent.com/1306177/59136087-dd69dd80-8981-11e9-8686-687a136f11b6.png)

**Comment by IlyaFinkelshteyn** [comment]
Thanks for the catch!

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.

**Comment by dmex** [comment]
@IlyaFinkelshteyn 

Thanks! 👍
