### ISSUE TITLE
Chocolatey v0.10.15

### ISSUE THREAD

**Issue by mkevenaar** [appveyor/ci#2980]
Hi,

The current version of Chocolatey (v.0.10.11) is outdated. The newer version (v0.10.15) has improvements to debug issues when pushing to the Chocolatey Community Repository.

As a Chocolatey Package Maintainer, I would like to have this latest release ready to go instead of having to upgrade it on every build.

Also requested via: https://twitter.com/mkevenaar/status/1136918141056012288

Thanks,

Maurice

**Comment by IlyaFinkelshteyn** [comment]
Will add it to mainstream images during the next update. `Visual Studio 2019` image though already has it.
