### ISSUE TITLE
Include androidNDK in Visual studio 2019

### ISSUE THREAD

**Issue by OwenMcDonnell** [appveyor/ci#2981]
[discussion](https://github.com/appveyor/ci/issues/2975)

**Comment by OwenMcDonnell** [comment]
Component listed [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?vs-2019&view=vs-2019) suggests `Component.Android.NDK.R16B` though the androidNDK wiki [here](https://github.com/android-ndk/ndk/wiki) suggests there is likely a newer version.

**Comment by IlyaFinkelshteyn** [comment]
Also, not sure should we add any of this:

```
Component.Android.NDK.R16B_3264
Component.Android.SDK25.Private
Component.Android.SDK27
```

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.
