### ISSUE TITLE
.NET Framework 4.8 support on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2982]
https://github.com/appveyor/ci/issues/2924

**Comment by IlyaFinkelshteyn** [comment]
Add all devpacks installation: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_dotnet_devpack.ps1

**Comment by IlyaFinkelshteyn** [comment]
also add https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_dotnet_runtime.ps1 and https://github.com/appveyor/build-images/blob/master/scripts/Windows/prepare_dotnet_runtime.ps1 (after reboot)

**Comment by houseofcat** [comment]
@IlyaFinkelshteyn hey Ilya, any chance you can get the VS2019 Preview Image update? It's working great with NetCore 3.0 support, but now NET48 is failing :(

Thanks for all the hard work!
