### ISSUE TITLE
MFC on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2985]
[discussion](https://help.appveyor.com/discussions/problems/24061-mfc-is-missing-from-latest-visual-studio-2019-image?mail_type=queue). 

It is probably `Microsoft.VisualStudio.Component.VC.ATLMFC` [component](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019) but not 100% sure.

**Comment by Xottab-DUTY** [comment]
> but not 100% sure.

Should be it.

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.
