### ISSUE TITLE
MySQL Service: Auto-create db and user

### ISSUE THREAD

**Issue by mwhouser** [appveyor/ci#299]
Please add as a feature request the ability to define a database/schema to create and a user to create with access to said database.

It's nice that you're including the MySQL service, but I would imagine that most people need a database created and perhaps a user since your default username/password is not changeable.

I know that you can create a database and user by running our own SQL script, but I think that many people would prefer a built-in option.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
