### ISSUE TITLE
WiX Toolset Visual Studio 2019 Extension

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#2992]
https://github.com/appveyor/ci/issues/2963#issuecomment-503949121

**Comment by Liryna** [comment]
Hi @IlyaFinkelshteyn ,

In the meantime, could you upgrade the WiX version to 3.11.1 Current version is 3.11.0 and does not seem to work well with the 2019 Extension.
https://wixtoolset.org/releases/
See https://ci.appveyor.com/project/Maxhy/dokany/builds/25474483#L874 
`The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/` on the Visual studio 2019 build image.

**Comment by Liryna** [comment]
See PR https://github.com/appveyor/build-images/pull/11

**Comment by csmager** [comment]
Works fine for me?

**Comment by Liryna** [comment]
3.11.0 has a [vulnerability](https://wixtoolset.org/news/). Update 3.11.1 has to be made for security reason anyway.

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.
