### ISSUE TITLE
Visual Studio 2019 - WDK for Windows 10, version 1903

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#2994]
There is a new release of the WDK for Windows 10, version 1903
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

Would it be possible to install it in the Visual Studio 2019 image ?
I see the script install it here https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_wdk_1903.ps1 but the current image is missing it for a reason. (not present in the installation list at all)

**Comment by Liryna** [comment]
Updating the download link in the script does install correctly the WDK.

**Comment by Liryna** [comment]
WDK comes with a VSIX for Visual Studio integration. Silence installation does not install it. It is an UI option at the end of the installation. The VSIX is needed otherwise VS cannot find the WDK.
VSIX is located here after the installation `C:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix`
Used this command line to install it:
```
$exePath = "$env:temp\wdksetup.exe"
(New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=2085767', $exePath)
Write-Host "Installing..."
cmd /c start /wait $exePath /quiet
Remove-Item $exePath

$vsVersion=& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationVersion | Out-String
$vsVersion = $vsVersion -replace "`n|`r"
"`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe`"  /a /f /sp /q /skuName:Community /skuVersion:$vsVersion `"C:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix`"" | out-file ".\install-vsix.cmd" -Encoding ASCII
& .\install-vsix.cmd
```

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.

**Comment by naveenimmadisetti** [comment]
The manual running of VSIX will do the integration.
