### ISSUE TITLE
Visual Studio 2019 - ARM / ARM64 Build tools

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#2995]
Only x86 build tools are for now installed, would it be possible to have the ARM & ARM64 either in VS ?

**Comment by IlyaFinkelshteyn** [comment]
Can you please provide Visual Studio installer screenshot with required check boxes to ensure we are on the same page?

**Comment by Liryna** [comment]
Images are the same from https://github.com/appveyor/ci/issues/2996#issuecomment-505146610

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.

**Comment by noloader** [comment]
@IlyaFinkelshteyn,

I manually test our project under ARM64 from command line. To do so I need to Open a Visual Studio 2017 ARM64 Developer Command Prompt.

Can you state how to open a developer command prompt when testing with AppVeyor? I can't seem to find it in the manual.

Sorry to ask.
