### ISSUE TITLE
Visual Studio 2019 - Spectre Mitigations for build tools & libraries

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#2996]
Would it be possible to have the spectre mitigations feature for each build tools platform & libraries in Visual studio ?

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(425,5): error MSB8040:
Spectre-mitigated libraries are required for this project.
Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used.
Learn more: https://aka.ms/Ofhn4c
```

**Comment by IlyaFinkelshteyn** [comment]
Here I would also ask you to provide Visual Studio installer screenshot with required check boxes.

**Comment by Liryna** [comment]
Sorry for the French, could not find to switch in english the VS Installer 😢 

![image](https://user-images.githubusercontent.com/4311419/60046079-c0921180-96c6-11e9-9191-94d15bcd3dd4.png)


![image](https://user-images.githubusercontent.com/4311419/60046102-d1428780-96c6-11e9-8c5e-1d01594e9eff.png)

**Comment by IlyaFinkelshteyn** [comment]
@Liryna great, thanks!

**Comment by IlyaFinkelshteyn** [comment]
Image update deployed.
