### ISSUE TITLE
Upgrade Coverity version to 2019 version

### ISSUE THREAD

**Issue by XVilka** [appveyor/ci#2999]
Coverity Upgrade to 2019.03
2019 June 7

>Attention SCAN users! We will begin upgrading the Coverity tools in SCAN on Monday, 17 June at 0900 MDT to make this free service even better. The SCAN team has been hard at work stabilizing the service and getting ready for this upgrade.

> SCAN will be switched to read-only during the upgrade, locking registration and triage, and halting builds. Defect data may be unavailable at times. The upgrade is expected to take three to five days.

> After the upgrade, a new version of the Coverity build package will be available for download. The old 8.7 version some users are still using will no longer work after the upgrade. Be sure to download the new build package. 

https://community.synopsys.com/s/topic/0TO2H0000001CN7WAM/coverity-scan-status

**Comment by Liryna** [comment]
Is it now include on the live image ?

**Comment by IlyaFinkelshteyn** [comment]
Image update is rolling now. This issue will be closed when its done. Note however that this issue  is related only to `Visual Studio 2015` and `Visual Studio 2017` images. For `Visual Studio 2019` follow https://github.com/appveyor/ci/issues/3038. Sorry for the confusion.

Meanwhile use [this script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_coverity.ps1) to install this on-the-fly. It will consume about 2 minutes of the build time.
