### ISSUE TITLE
Apache Ant

### ISSUE THREAD

**Issue by marscher** [appveyor/ci#3]
is a multipurpose build tool for Java - please support it. It just needs to be extracted and put on path. Despite a env variable ANT_HOME has to be set, so it can be run. Thank you!

**Comment by trexinc** [comment]
Installing ant through chocolatey fails very often, and has a lot of overhead as it downloads both x86 and x64 JDKs for some reason (and those fail every other time).
I currentl just manualy download ant during build, but it would be nice to have it somewhere on the disk (same as maven).

Latest ant is here:
https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip

**Comment by IlyaFinkelshteyn** [comment]
@trexinc I would try to add retries e.g. ` - cmd: appveyor-retry choco install ant`

**Comment by trexinc** [comment]
@IlyaFinkelshteyn thanks, that will work, but it takes several minutes to complete the processes even when it works.
IMHO, Ant is a pretty common build tool for java projects and it would be nice to have it preinstalled.
Thank you for considering this anyway.

**Comment by trexinc** [comment]
@marscher, cool, thanks.

**Comment by marscher** [comment]
you're welcome! But like you I agree that Ant should be part of the image.
