### ISSUE TITLE
Feature request: Configure the public url directly

### ISSUE THREAD

**Issue by NepPure** [appveyor/ci#3005]
Sorry for so many new issues.
I was wondering, when using a reverse proxy, can I configure the public url directly?

<img width="757" alt="QQ20190626-172013@2x" src="https://user-images.githubusercontent.com/12379907/60168058-e807ec00-9836-11e9-87ab-bdc8f5dc3994.png">

Currently modify `Application public URL` will change port binding(I'm not sure), and the SSL certificate is required when using https scheme.  Of course, we usually bind the certificate to the gateway.

This is a test for the problem https://github.com/NepPure/Abp.GeneralTree/pull/2
Github Check detail url is `localhost:8050` always starts with `Application public URL`.

Is there a solution to this problem, thank you very much.

**Comment by FeodorFitsner** [comment]
You can, basically, set anything in `Application public URL` - it won't change port binding though. Even if there is `https://` in that URL HTTPS still can be disabled.

**Comment by NepPure** [comment]
@FeodorFitsner It works! Thank you very much!
