### ISSUE TITLE
Error sending email using SMTP protocol

### ISSUE THREAD

**Issue by NepPure** [appveyor/ci#3007]
v7.0.2184
Windows Server 2016

I didn't found the error details in event logs.

<img width="468" alt="QQ20190627-101146@2x" src="https://user-images.githubusercontent.com/12379907/60228312-e8e75f00-98c4-11e9-89dc-92648833bf87.png">

Notification config:
<img width="775" alt="QQ20190627-101548@2x" src="https://user-images.githubusercontent.com/12379907/60228317-ec7ae600-98c4-11e9-9762-ddf3a9db22fc.png">

The email config:
<img width="372" alt="QQ20190627-102007@2x" src="https://user-images.githubusercontent.com/12379907/60228427-38c62600-98c5-11e9-803d-89e5a5ebc4df.png">
I have tried `SMTP host` config without port, it returns the same error.
(smtp.exmail.qq.com, require SSL，port 465) 

I'm not sure this is a config problem or smtp bug. I hope the log about email more detailed.
Thanks!

**Comment by FeodorFitsner** [comment]
Will add more detailed logging about the error, sure. Could it be that the port is just blocked somewhere on the way?

**Comment by NepPure** [comment]
> Will add more detailed logging about the error, sure. Could it be that the port is just blocked somewhere on the way?

The same server, same smtp config and another aspnetcore app, no problem.
I will wait for next update😆

**Comment by NepPure** [comment]
Solved by using port 587.
https://stackoverflow.com/questions/20228644/smtpexception-unable-to-read-data-from-the-transport-connection-net-io-connect

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update! We've added more logging anyway - hopefully it will help others to better troubleshoot SMTP-related issues.
