### ISSUE TITLE
MSYS2 on Visual Studio 2019

### ISSUE THREAD

**Issue by omichel** [appveyor/ci#3009]
It seems MSYS2, e.g., `C:\msys64`, is missing from the Visual Studio 2019 image. Will you add it or shall we revert to Visual Studio 2017 image?

**Comment by IlyaFinkelshteyn** [comment]
Yes, will add it.

**Comment by sujatapatnaik52** [comment]
I am using Windows Server 2019 image and I see neither mingw nor msys2 is present. Any update on if this will be added?
