### ISSUE TITLE
Spectre-mitigated MFC libraries missing for VS2017

### ISSUE THREAD

**Issue by manxorist** [appveyor/ci#3011]
Spectre-mitigated MFC libraries are missing from the VS2017 install.
From the install script, it looks like also spectre-mitigated ATL and Runtime libraries are also missing.

This causes OpenMPT build to fail, see https://ci.appveyor.com/project/OpenMPT/openmpt/builds/25641443 :
```
LINK : fatal error LNK1104: cannot open file 'afxnmcd.lib' [C:\projects\openmpt\build\vs2017win7\OpenMPT.vcxproj]
```

On a related note: Were MFC libraries missed in https://github.com/appveyor/build-images/commit/5c16b975d6a14e790b07ad25ec607a1804864f4e ? They are a separate option from ATL spectre-mitigated libraries in the GUI installer.

**Comment by heydojo** [comment]
It would be greatly appreciated if this issue is addressed in the VS2019 image too please.
Please make all Spectre mitigations available to compile against.
Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@manxorist can you please provide exact name of the component as it looks in the in the Visual Studio Installer UI? To ensure this is needed component, you can add **blocking** [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) at init `stage` of the build, add that component with UI and then continue the build and see if it fixed the problem. Or if you 100% sure of the component name, please post it here exactly as it appears in installer UI.
We appreciate if you can do this in next couple of days as we are finalizing images updates this week.

**Comment by manxorist** [comment]
The missing required VS2017 components are named "Visual C++ ATL (x86/x64) with Spectre Mitigations" and "Visual C++MFC for x86/x64 with Spectre Mitigations" in the installer UI.

http://manx.datengang.de/openmpt/temp/vs2017-mfc-spectre.png

**Comment by IlyaFinkelshteyn** [comment]
@manxorist great, thanks a lot!
