### ISSUE TITLE
Build cache not used (silently)

### ISSUE THREAD

**Issue by blueyed** [appveyor/ci#3015]
The build cache was not used with https://ci.appveyor.com/project/neovim/neovim/builds/25674238/job/flt4gj98p8b9r3p3, but the other job from the same build.

In the forums I've read that this might be due to different data centers, but that was an older thread already.

It would be useful to get more information in the logs at least when the cache is not used (with the reason for it).

I've started investigating this in https://github.com/neovim/neovim/pull/10390, but having one job use it, while the other does not is confusing.

Might this be due to us skipping 2 out of the 4 job configurations for PRs, and the cache handler getting confused due to this?

```yaml
init:
- ps: |
    # Pull requests: skip some build configurations to save time.
    if ($env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT -and $env:CONFIGURATION -match '^(MSVC_64|MINGW_32)$') {
      $env:APPVEYOR_CACHE_SKIP_SAVE = "true"
      Exit-AppVeyorBuild
    }
```

Also it is not clear from the documentation if jobs really use different caches per job (configuration), and what config keys play a role there then.

**Comment by IlyaFinkelshteyn** [comment]
@blueyed the link you sent is a PR job. From [documentation](https://www.appveyor.com/docs/build-cache/#how-it-works):

**Note**: By default, saving cache is disabled in Pull Request builds. Use `Save build cache in Pull Requests` checkbox on the **General** tab of project settings if you need to save cache during PR builds. This setting is not exposed in YAML to prevent unauthorized cache modifications.


Answering your other question, cache is specific per job, e.g. each job in the [build matrix](https://www.appveyor.com/docs/build-configuration/#build-matrix) uses its own cache.

**Comment by blueyed** [comment]
@IlyaFinkelshteyn 

> By default, saving cache is disabled in Pull Request builds.

I've read this, but it is about restoring caches.
I would assume that it uses the cache from the latest master (target branch) build here, or isn't that the case?

**Comment by IlyaFinkelshteyn** [comment]
Yes, it should restore cache saved latest successful non-PR build for that job. Can you please point me to the specific build which saved cache before this problem one?

Generally I believe setting `Save build cache in Pull Requests` checkbox in UI is more reliable way for you,, as most of your builds are PR builds as I see. If you want to avid this because this maybe time consuming, note that AppVeyor will nor re-save the cache in case files (CRC) was not changed.

**Comment by blueyed** [comment]
@IlyaFinkelshteyn 
It was used with https://ci.appveyor.com/project/neovim/neovim/builds/25828766/job/m4egaxgq3a10d0ko?fullLog=true (job 1), but not https://ci.appveyor.com/project/neovim/neovim/builds/25828766/job/2duqum7wug9dy676?fullLog=true (job 4) (from the same build).
The master build before this was https://ci.appveyor.com/project/neovim/neovim/builds/25827564, where job 4 failed (but neither job 1 nor 4 used the cache there).  And even though job 4 failed, it should not cause the cache to get removed, right?

Before this the master build failed for job 1, and was canceled for the others (https://ci.appveyor.com/project/neovim/neovim/builds/25816685).

We've enabled the option to save cache for PRs now, maybe that helps in this regard.

**Comment by blueyed** [comment]
It appears to have been improved for Neovim's builds (we have enabled the "Save build cache in Pull Requests" setting (which should not really have affected reads though)).

And I've seen that there is an error reported if loading the cache fails now:
```
git checkout -qf FETCH_HEAD
Unable to load build cache items - skipping cache restore
Error making request with Error Code GatewayTimeout and Http Status Code GatewayTimeout. No further error information was returned by the service.
Install-Product node 8
```

Closing for now.
