### ISSUE TITLE
Add DEBIAN_FRONTEND variable 

### ISSUE THREAD

**Issue by Wasapl** [appveyor/ci#3018]
add DEBIAN_FRONTEND=noninteractive into envs

**Comment by Wasapl** [comment]
funny story, we already have it:
https://github.com/appveyor/build-images/blob/miniubu/scripts/Ubuntu/common.sh#L207-L209
Does it means that `.profile` file not sourced while running build?

**Comment by FeodorFitsner** [comment]
you could make a test and output all vars to see if it's there

**Comment by Wasapl** [comment]
I see that it's there. But they have to be passed by sudo to apt like this:
`sudo -E apt-get install <foo_package>`
https://stackoverflow.com/a/8633575

**Comment by Wasapl** [comment]
And I found that we can force `sudo` to pass certain variables by default. We just need to list them in `sudoers` file. https://superuser.com/a/232258

**Comment by Wasapl** [comment]
Now it works without `-E` https://ci.appveyor.com/project/appveyor-tests/linux-upgrade
