### ISSUE TITLE
Visual Studio 2019 Shared Items Project creates false deprecation error

### ISSUE THREAD

**Issue by sylveon** [appveyor/ci#3024]
https://github.com/sylveon/appveyor-bug
https://ci.appveyor.com/project/sylveon/appveyor-bug

As soon as I added a shared items project to this empty solution, the build stopped working, because it says the project file is in a deprecated format (.vcproj), even though the file isn't and shared items projects are still fully supported.

**Comment by MouriNaruto** [comment]
I have found the same problem several months ago. But I found AppVeyor hasn't fixed it.

https://github.com/Project-Nagisa/Nagisa
https://ci.appveyor.com/project/MouriNaruto/nagisa

**Comment by IlyaFinkelshteyn** [comment]
Thank you guys for the catch. We were able to repro and looking into it.

**Comment by sylveon** [comment]
Preview AppVeyor image didn't resolve the issue for me, CI builds haven't been working for several months now.

https://ci.appveyor.com/project/sylveon/translucenttb/build/job/r450mr4qqwey4gd1

**Comment by FeodorFitsner** [comment]
What would be the fix for that? Is there something missing on VS 2019 image?

**Comment by sylveon** [comment]
I have no idea. I tried a while ago establishing a remote session to the worker and building it from a VS command prompt, and it worked. Something in the environment must be wrong.

**Comment by sylveon** [comment]
This is still broken, I haven't had a working build since nearly a year now and am seriously considering switching to GitHub Actions or Azure Pipelines at this point...

**Comment by FeodorFitsner** [comment]
@sylveon  Sorry for the delay with reply! Apparently, there is a bug (well, not technically a bug, but an outdated dependency) in MSBuild managed library we use to discover/analyse solution and project files.

If you replace build section with `msbuild` command it [compiles without issues](https://ci.appveyor.com/project/FeodorFitsner/appveyor-vcproj-bug):

```yaml
image: Visual Studio 2019
build_script:
- msbuild Project2.sln
```
