### ISSUE TITLE
Additional spectre mitigated libraries on Visual Studio 2019

### ISSUE THREAD

**Issue by heydojo** [appveyor/ci#3027]
When building an application using the Appveyor Visual Studio 2019 image, the following message appears and the build fails:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka.ms/Ofhn4c for more information.

This indicates that the MSVC++ spectre mitigations are not present within the Appveyor VS2019 image.

Would it be possible to add the spectre mitigations to the 2019 image so that I don't see this error message again please?

**Comment by IlyaFinkelshteyn** [comment]
@heydojo can you please provide exact name of the component? You can discover and test it on `Visual Studio 2019` the same way I described in https://github.com/appveyor/ci/issues/3011#issuecomment-511547646. Appreciate the help.

**Comment by IlyaFinkelshteyn** [comment]
@heydojo here is a screenshot of current setup on `Visual Studio 2019`. Are those marked in yellow would be enough, or maybe too much? Do you believe you and others will be needed ARM and ARM64? It would be nice of you can clarify soon as we are working on images release now.

![2019-07-16_10h32_29](https://user-images.githubusercontent.com/3248386/61316375-b0e18680-a7b5-11e9-9ad4-217725f43d82.png)

**Comment by stephenegriffin** [comment]
I'm also hitting this. I think the strategy here should be to add build tools with Spectre Mitigations for each build tools without that we include. So in your highlights, that would only be this one:
C++ MFC for v142 build tools with Spectre Mitigations (x86 & x64)

The others should only be added when people request the equivalent non spectre build tools

**Comment by heydojo** [comment]
Hi @IlyaFinkelshteyn

![2](https://user-images.githubusercontent.com/186629/61436702-435b6480-a933-11e9-9bc6-593ee55e059b.png)

Are my needs for C++ projects going forward. But it would be rather selfish of me not to also point out the libraries others may need for cross compiling:

![1](https://user-images.githubusercontent.com/186629/61436818-8289b580-a933-11e9-8863-d5da82f5f0c6.png)

In the image above, blue are items I have already installed. Marked in yellow are items I would install if doing cross compiles for ARM and ARM64. I recommend adding them if you don't mind please.

Also, as an aside; it would be really helpful if the current latest stable Windows SDK is present on the image:

![3](https://user-images.githubusercontent.com/186629/61436951-d1374f80-a933-11e9-9d44-5cb749ffea5c.png)

Many thanks!

**Comment by heydojo** [comment]
> I'm also hitting this. I think the strategy here should be to add build tools with Spectre Mitigations for each build tools without that we include. So in your highlights, that would only be this one:
> C++ MFC for v142 build tools with Spectre Mitigations (x86 & x64)

I honestly don't need MFC or ATL for any of my C++ projects using Appveyor CI. I only need **MSVC v142 and spectre mitigations for MSVC v142 (v14.21)** as will most others.

The MFC and ATL components I have installed are for a local compile I do which needs them.
MFC is kind of the old way of doing things and pretty much arbitrary IMO.
ATL is used for instance to help with creating applications which make use of  accessibility features built into Windows.
https://en.wikipedia.org/wiki/Microsoft_Foundation_Class_Library
https://en.wikipedia.org/wiki/Active_Template_Library

Unless you absolutely need them, you should probably not be trying to link against them to keep your build times down.

**Comment by vSzemkel** [comment]
By the way, this is Microsoft error to ignore /Qspectre compiler switch. They have ignored my report with comment that it's all right.

**Comment by heydojo** [comment]
> By the way, this is Microsoft error to ignore /Qspectre compiler switch. They have ignored my report with comment that it's all right.

This isn't the place for that type of discussion IMO.
It's not a bug. It's a feature.
Builds specifying /Qspectre should never complete and simply warn if /Qspectre libs are not found.
If you don't mind building without /Qspectre - then don't specify it.
Thanks.

**Comment by vSzemkel** [comment]
The bug is corrected in Visual Studio 16.2. Earlier if you don't mind building without /Qspectre you were just forced to and you must have had spectre mitigated libs installed.

**Comment by heydojo** [comment]
> The bug is corrected in Visual Studio 16.2. Earlier if you don't mind building without /Qspectre you were just forced to and you must have had spectre mitigated libs installed.

I'm not seeing anything about this in the release notes: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes
and seeing how what you describe is not the expected default behaviour, it would be really helpful if you could provide a source @vSzemkel 

I still maintain that the compiler failing to complete a build specifying /Qspectre when spectre mitigated libraries are not present on the host system is the correct course of action and as such the expected result and of course absolutely not a bug.

**Comment by Kmg2158** [comment]
MSB8040	Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c	InsightDriver	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	486	

I have installed all packages related to C++ Spectre-mitigated. But still getting error.

**Comment by Mouriya05** [comment]
MSB8040 Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c InsightDriver C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets 486

I have installed all packages related to C++ Spectre-mitigated. But still getting error.
