### ISSUE TITLE
CMake 3.15.1

### ISSUE THREAD

**Issue by zufuliu** [appveyor/ci#3035]
https://cmake.org/download/

**Comment by zufuliu** [comment]
They released 3.15.1 on today.
https://github.com/Kitware/CMake/releases

**Comment by gunterkoenigsmann** [comment]
This update seems to have broken the following construct wxMaxima uses:

     find_package(wxWidgets 3 REQUIRED std xml html adv aui core net base richtext)
     include(${wxWidgets_USE_FILE})

The wxWidgets libraries are no more found even if the Right Path to them is specified and the right wxWidgets flavour has been selected:

     cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -LAH -DwxWidgets_CONFIGURATION=mswud -DwxWidgets_ROOT_DIR=C:\wxWidgets\ -DwxWidgets_LIB_DIR=C:\wxWidgets\lib\vc141_x64_dll -DCMAKE_BUILD_TYPE=debug ..

**Comment by gunterkoenigsmann** [comment]
Upstreamed the cmake bug: https://gitlab.kitware.com/cmake/cmake/issues/19569

**Comment by gunterkoenigsmann** [comment]
Upstream responded in next to no time: It is no longer possible to explicitly request the wxWidgets component "std". The rest runs fine.

**Comment by IlyaFinkelshteyn** [comment]
@gunterkoenigsmann you can always change cmake version by running modified version of [this script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_cmake.ps1) at `install` stage.

**Comment by minggo** [comment]
But the cmake is still 3.10? As the error message in my [ci log](https://ci.appveyor.com/project/minggo/cocos2d-x/builds/26813643/job/grsm37968lecdby0)
```
{"cookie":"","inReplyTo":"configure","message":"CMake Error at CMakeLists.txt:1 (cmake_minimum_required):\n  CMake 3.14 or higher is required.  You are running version 3.10.2\n\n","title":"Error","type":"message"}
```

**Comment by IlyaFinkelshteyn** [comment]
@minggo It is `3.15.1` and you can check it by running `cmake /V` in the begining of the build. It seems that your build script itself [installs older cmake](https://ci.appveyor.com/project/minggo/cocos2d-x/builds/26813643/job/grsm37968lecdby0#L959).

**Comment by minggo** [comment]
@IlyaFinkelshteyn thanks. It seems cmake is installed when installing Android SDK.

**Comment by IlyaFinkelshteyn** [comment]
@minggo I would recommend explore two options: 
- use [existing pre-installed](https://www.appveyor.com/docs/windows-images-software/#xamarin) android SDK. 
- reinstall cmake over after Android SDK installation use [our script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_cmake.ps1) or [chocolatey](https://chocolatey.org/packages/cmake) for that.

**Comment by minggo** [comment]
@IlyaFinkelshteyn thanks for you suggestion.
