### ISSUE TITLE
install failed on Mac

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/ci#3044]
```
brew install appveyor-server
Updating Homebrew...
==> Installing appveyor-server from appveyor/brew
==> Downloading https://appveyordownloads.blob.core.windows.net/appveyor/7.0.232
######################################################################## 100.0%
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "appveyor-server"
Download failed: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2329/appveyor-server-7.0.2329-macos-x64.tar.gz
```
how to fix this?

**Comment by FeodorFitsner** [comment]
Thanks for trying out AppVeyor on Mac!

Are you able to download https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2329/appveyor-server-7.0.2329-macos-x64.tar.gz directly from your browser or with curl?

**Comment by ArgoZhang** [comment]
yes I can. but download speed very slow. this issue caused by brew install has been interrupted before.

**Comment by ArgoZhang** [comment]
Can you share the startup appveyor script?
I got the appveyor-server-7.0.2329-macos-x64.tar.gz package

**Comment by FeodorFitsner** [comment]
You can try "extracting" instructions from Formulae: https://github.com/appveyor/homebrew-brew/blob/master/Formula/appveyor-server.rb#L8-L31

It's basically, changing some missing values in `appsettings.macos.json` then copying it to a right location. After that you can either start `appveyor-server` executable from command-line or create a launch daemon with plist.

**Comment by ArgoZhang** [comment]
thanks. it works
