### ISSUE TITLE
Install Vulkan SDK

### ISSUE THREAD

**Issue by hhyyrylainen** [appveyor/ci#3045]
It would be nice to have [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) preinstalled on the Windows build images.

There is a way to install the Vulkan SDK before build like this:
```
init:
  - curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
  - VulkanSDK.exe /S
  - rm -f VulkanSDK.exe
```

I found this approach from here: http://www.asawicki.info/news_1655_how_to_use_vulkan_sdk_with_appveyor_and_travis_ci.html

The problem with that is that the vulkan site has really slow downloads. Looking at the time since build started, it took a few seconds over **4 minutes** to download the sdk file. So it greatly increases the build times.

**Comment by IlyaFinkelshteyn** [comment]
Can you please try to leverage AppVeyor [build cache](https://www.appveyor.com/docs/build-cache/) for that? For simplicity I would try to cache just `VulkanSDK.exe`, but still do installation on the fly. Note however that you will be needed to check if `VulkanSDK.exe` restored from the cache and if not download it -- because cache is "best effort" approach and you should not 100% rely on it. Also do that at `install` stage, not `init` -- because cache is being restore after repo clone.

**Comment by hhyyrylainen** [comment]
I changed my config to:
```
environment:
  VULKAN_SDK: C:/VulkanSDK/1.1.114.0

cache:
  - VulkanSDK.exe

install:
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
  - VulkanSDK.exe /S
```
Which hopefully utilises the cache.

I noticed something worrying on that build cache page. There are now limits listed on the cache size, with the smallest being 1 gigabyte. The vulkan SDK is already a little over 300 megabytes. Combined with the fact that I'm building open source C++ projects, I'm very worried that I'm going to run out of cache room.

**Comment by IlyaFinkelshteyn** [comment]
But if you cache just `VulkanSDK.exe`, default cache size should be enough. If you hit the limit, ping us we will see what we can do.

**Comment by hhyyrylainen** [comment]
VulkanSDK can fit just fine in the cache. But I think I'm already very likely to hit the cache size limit. I'm caching the intermediate build files, which add up to almost 10 gigabytes on my computer, so I'm surprised it even works currently...
