### ISSUE TITLE
Lock / Limit environments to a project (or multiple projects?) 

### ISSUE THREAD

**Issue by gnpretorius** [appveyor/ci#305]
We generally have multiple environments per projects, however without this limit developers are able to deploy projects to completely different environments, effectively bringing down an entire site.  It's basic human error and there is no way to control it. 

If we could limit an environment to a projects (or multiple projects), then this would not be an issue. 

Thanks

Gordon

**Comment by gjstockham** [comment]
Yes, I'm finding this a big issue as well.  There doesn't seem to be a way to restrict this.

Adding conditions to an environment such as project, branch etc. would make this so much easier.

**Comment by FeodorFitsner** [comment]
This will be a part of the next deployment functionality refresh we are currently working on.
