### ISSUE TITLE
MySQL 5.7 on VS 2019 image

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#3057]
[discussion](https://twitter.com/RavenX0123/status/1161650959002603522)

**Comment by artiomchi** [comment]
This has been opened since August! It's almost October.

Surely it's not that complicated to install MySql into one of your build images?

Is there an ETA for a fix for this?

**Comment by IlyaFinkelshteyn** [comment]
@artiomchi it is on its way, hope to update in a week or two. Sorry for delay.

**Comment by NotAdam** [comment]
Does the new milestone title imply that we're getting an image update later today or...?

**Comment by FeodorFitsner** [comment]
Yep, working on delivering image update today.

**Comment by FeodorFitsner** [comment]
Image update has been deployed. Let me know how it worked.

**Comment by NotAdam** [comment]
Awesome, thanks, I'll give that a go later today

**Comment by artiomchi** [comment]
Amazing news! Thanks

Can confirm that the new image has MySql - now I can test and fix my build \^_\^

**Comment by FeodorFitsner** [comment]
Great, thanks for the update!
