### ISSUE TITLE
Visual Studio 2019 Preview 1 installation

### ISSUE THREAD

**Issue by ajai1109** [appveyor/ci#3059]
My current project is built in using VS 2019 preview 1 and I have update preview 2 in my system and it required some changes in my project. Can I install the previous version visual studio preview 1 instead of latest preview2?

**Comment by IlyaFinkelshteyn** [comment]
You can maintain your own image with [private build cloud](https://www.appveyor.com/docs/build-environment/#private-build-cloud) solution. Lee us know if you are interested and we will provide you with details.

**Comment by SergeGautherie** [comment]
@ajai1109, your question is somewhat unclear.
Which AppVeyor image are you talking about?
Which VS version(s) does it have? Which one would you want?

**Comment by SimonCropp** [comment]
perhaps should be closed in favor of https://github.com/appveyor/ci/issues/3098
