### ISSUE TITLE
Environment Variables do not support new lines

### ISSUE THREAD

**Issue by soopercool101** [appveyor/ci#3060]
I'm attempting to automate a release so that the release's changelog is pulled from a text file generated on build. Though the method I use works and formats properly on my own system, on AppVeyor it formats without any line breaks, which entirely invalidates my changelog format.

Setting the variable on my own system:
![image](https://user-images.githubusercontent.com/35675593/63235892-64dc9400-c1f0-11e9-8b7f-8eca4c54e1c1.png)

Setting the variable on AppVeyor:
![image](https://user-images.githubusercontent.com/35675593/63236003-ea604400-c1f0-11e9-9ceb-5b871b6f5d55.png)

This, of course, results in the awful formatting seen here:
![image](https://user-images.githubusercontent.com/35675593/63236049-154a9800-c1f1-11e9-928d-a41e7ddc601d.png)

If I missed a better way to do this (or a proper workaround) let me know.

**Comment by IlyaFinkelshteyn** [comment]
This can be related to the line endings. Please update your `appveyor.yml` (or UI settings if you do not use YAML configuration) with this:

```
init:
  - git config --global core.autocrlf true
```

**Comment by soopercool101** [comment]
That unfortunately did not fix the issue in question. I get the same result when that is added to my init script.

**Comment by IlyaFinkelshteyn** [comment]
Try to save that txt file as an [artifact](https://www.appveyor.com/docs/packaging-artifacts/) and see is it really has new lines when you open it locally. Also share link to the build and `appveyor.yml`.

**Comment by soopercool101** [comment]
I uploaded the changelog txt file in question as an asset so I could take a look at it. It correctly generates with both a newline and carriage return, matching the Windows standard:
![image](https://user-images.githubusercontent.com/35675593/63311487-0af0d280-c2b3-11e9-8899-a56f115c4986.png)

**Comment by soopercool101** [comment]
Exported Appveyor.yml: https://pastebin.com/C2Zxsx29 
Build: https://ci.appveyor.com/project/soopercool101/brawlcratenext-eanke/builds/26813653

**Comment by IlyaFinkelshteyn** [comment]
What you try on local computer is not an **environment** variable, e.g. if you try to use `$env:CHANGELOG` instead of `$CHANGELOG`, you will get the same results as on AppVeyor.

**Comment by soopercool101** [comment]
So it is. I needed to add `-raw` to my `GET-CONTENT`, and it works perfectly. Closing as this was user-error.

**Comment by soopercool101** [comment]
Continued with a separate but related issue in #3062 which I believe is not user-error (though I could always be incorrect)
