### ISSUE TITLE
Build Worker API add test error latest Ubuntu 1804

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#3061]
[Discussion](https://help.appveyor.com/discussions/problems/24784-dotnet-test-from-ubuntu1804-started-failing-to-post-results-to-appveyor-api)
[Repro](https://ci.appveyor.com/project/IlyaFinkelshteyn/projecta/builds/26813275) with direct API call from PowerShell

**Comment by Wasapl** [comment]
fixed in recent [Linux images update](https://www.appveyor.com/updates/2019/08/28/)
