### ISSUE TITLE
NuGet deployment provider not publishing .snupkg packages

### ISSUE THREAD

**Issue by dazinator** [appveyor/ci#3066]
According to this: https://github.com/appveyor/ci/issues/2753

The Nuget Deployment provider should publish .snupkg packages.

However please see these builds:
- https://ci.appveyor.com/project/dazinator/dotnettency/builds/26878461
- https://ci.appveyor.com/project/dazinator/dotnettency/builds/26879359

I have a `.snupkg` package being produced, but in the nuget deploy step, there is no sign that it is published. I have tried modifying and remoiving the `artifacts` regex to no avail.

**Comment by IlyaFinkelshteyn** [comment]
Please see https://github.com/dazinator/Dotnettency/pull/60. Hopefully it is self-explainable. 

You package nuget with `after_build` so you do not need built-in AppVeyor nuget packaging, If you later decide to switch to built-in AppVeyor nuget packaging, it should have `publish_nuget: true` and `artifacts` section will not be needed.
