### ISSUE TITLE
MSVC++ 14.21 compiler side-by-side support on VS 2019 image

### ISSUE THREAD

**Issue by TheQwertiest** [appveyor/ci#3068]
Would it be possible to install MSVC 14.21 compiler for VS2019 images (in addition to the currently latest 14.22)?

Reason: v14.22 has a bug that broke my build and there is no workaround available (other than using the older compiler). It's been a month since the bug appeared and, regretfully, it's yet to be fixed...

Example of the broken build (notice the ICEs): https://ci.appveyor.com/project/TheQwertiest/foo-spider-monkey-panel/builds/26917708/job/hkbpxy5km6o5pyr2
The corresponding VS issue: https://developercommunity.visualstudio.com/content/problem/663321/ice-error-c1001-when-using-precompiled-header.html

Side-by-side installation should not bring any problem for other users, since the only way to use the older compiler is to enforce it's usage manually (e.g. https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/c3802ff4b367bcb0676be924c974422622839051)

**Comment by IlyaFinkelshteyn** [comment]
Sure. Can you please specify exact component as it listed [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019) or provide a Visual Studio Installer screenshot with a specific component selected?

**Comment by TheQwertiest** [comment]
Thanks! 
List of the components in question:
- Microsoft.VisualStudio.Component.VC.14.21.x86.x64
- Microsoft.VisualStudio.Component.VC.14.21.ATL
- Microsoft.VisualStudio.Component.VC.14.21.MFC

**Comment by TheQwertiest** [comment]
It seems that 14.21 compiler was installed on VS2019 image, thanks!
ATL/MFC are seem to be missing though: https://ci.appveyor.com/project/TheQwertiest/foo-spider-monkey-panel/build/job/ygwxa9ceqx9r81i2#L568

**Comment by TheQwertiest** [comment]
PS: the bug is still not fixed in VS (including v16.3.1)... So the issue is still relevant.

**Comment by TheQwertiest** [comment]
Latest image seems to have everything my build needs! Thank you!

**Comment by TheQwertiest** [comment]
Should I close the issue?

**Comment by FeodorFitsner** [comment]
Sure, go ahead. Thanks for confirming.
