### ISSUE TITLE
Visual Studio 2019 Preview image misses Windows SDK 10.0.18362.0 (1903)

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3069]
My project has
`<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>`.

VS2015 and VS2017 images find it.
VS2019P image does not.

Check/Install recent SDK(s).

**Comment by SergeGautherie** [comment]
Currently, which SDK versions are available on this image?
Out of the values I tried, it seems to find `8.1` only...

**Comment by IlyaFinkelshteyn** [comment]
The one which is going to be rolled out today tonight has [those](https://github.com/appveyor/build-images/blob/master/vs2019.json#L114-L117) steps.
Scripts are [here](https://github.com/appveyor/build-images/tree/master/scripts). So you can see for yourself what and how is being installed :) Though we will update [software list](https://www.appveyor.com/docs/windows-images-software/) with Visual Studio 2019 too.

**Comment by SergeGautherie** [comment]
Thanks for the pointers.
If I read scripts right:
`10.0.17763.0`: already installed, and found :-)
`10.0.18362.0`: will be skipped.
`10.0.18362.1`: will be added.

**Comment by IlyaFinkelshteyn** [comment]
Correct :)

**Comment by SergeGautherie** [comment]
Ah, VS2019 image was updated. (And I am using it from now on.)

Yet, VS2019P image is still outdated, instead of being ahead: see #2887 too.

**Comment by SergeGautherie** [comment]
Related/Duplicate of newer #3098?

**Comment by FeodorFitsner** [comment]
Install SDKs as part of VS 2019 installation and remove `install_winsdk_*.ps1` scripts.
