### ISSUE TITLE
Visual Studio 2019: some "pre-heated" VMs?

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3070]
Could there be some ready-to-use VS2019 VMs, to avoid the few minute startup delay? (To be like VS2015 and VS2017...)
Thanks.

**Comment by IlyaFinkelshteyn** [comment]
Yes, it will be moved to the datacenter where we can preheat VMs later this year.

**Comment by SergeGautherie** [comment]
Done a few hours ago :-)
