### ISSUE TITLE
VS 2017 C++ x64/x86 build tools (v14.16) on VS 2019 image

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3071]
VS2017 + v140: found.
VS2019 + v140: found.

VS2019 + v141:
`error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.`

It seems odd VS2019 supports v140 but not v141. Is that intended?
Thanks.

**Comment by IlyaFinkelshteyn** [comment]
No it is not intended, we add whatever customers need, per request. Please provide us exact component ID from  [this list](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?vs-2019&view=vs-2019) or Visual Studio installer screenshot with the component selected.

**Comment by SergeGautherie** [comment]
I am not sure, though I assume:

In:
`Desktop development with C++`

Is already installed:
`Microsoft.VisualStudio.Component.VC.140 	MSVC v140 - VS 2015 C++ build tools (v14.00) 	16.0.28625.61 	Optional`

Is wanted too:
`Microsoft.VisualStudio.Component.VC.v141.x86.x64 	MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16) 	16.1.28829.92 	Optional`

**Comment by IlyaFinkelshteyn** [comment]
Can you RDP to build worker at `init` stage, add what you need and continue the build to double-sure it works and this is enough? Results as a screenshots from VS installer UI are OK. we will translate them to component IDs.

**Comment by jamesmcguirepro** [comment]
We need Microsoft.VisualStudio.Component.VC.v141.x86.x64 too.

And Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core, if it's not already part of the VS2019 image.

**Comment by SergeGautherie** [comment]
Installed and tested over RDP: confirmed.

**Comment by IlyaFinkelshteyn** [comment]
Thank you so much guys, we will update the image during September (probably in the second half).

**Comment by SergeGautherie** [comment]
Fixed by last VM update :-)
