### ISSUE TITLE
Containers, Hyper-V and WSL features on Visual Studio 2019

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#3075]

**Comment by Random-Liu** [comment]
Thanks for filing the issue! :)

We are working on supporting windows containers in containerd, and trying to use appveyor for the presubmit test.

However, the test can't run because the `Containers` feature is not enabled in 2019.

**Comment by IlyaFinkelshteyn** [comment]
@Random-Liu we target to update the image by the end of this month.
