### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded

### ISSUE THREAD

**Issue by alabuzhev** [appveyor/ci#3084]
Hello,

We got the error `Maximum allowed artifact storage size of 50000 Mb will be exceeded` in [this](
https://ci.appveyor.com/project/FarGroup/farmanager/builds/27243520/job/u92e91x79ri95k80) build.

Is it possible to remove any stale artefacts or change the limit please?

**Comment by OwenMcDonnell** [comment]
We've increased your limit so you should be able to build without that error now. Let us know if this problem persists.

**Comment by alabuzhev** [comment]
Thanks!

**Comment by alabuzhev** [comment]
Hello, we're getting [Maximum allowed artifact storage size of 75000 Mb will be exceeded](https://ci.appveyor.com/project/FarGroup/farmanager/builds/29452040/job/0vyydrg6n2uw29hx).
Is it possible to remove any stale artefacts or change the limit please?

**Comment by FeodorFitsner** [comment]
Yep, the limit has been extended. Wow, FAR. Some of my friends are still using it! :)

**Comment by alabuzhev** [comment]
Thanks

**Comment by alabuzhev** [comment]
Hello again, we're getting [Maximum allowed artifact storage size of 75000 Mb will be exceeded](https://ci.appveyor.com/project/FarGroup/farmanager-tgu1s/builds/31801228/job/a4sianq9m424ls6n). Is it possible to remove any stale artefacts or change the limit please?

**Comment by FeodorFitsner** [comment]
It should be extended by now. Try to modify build to upload only essential artifacts, such as releases, or artifacts on `master` branch. Thank you!

**Comment by alabuzhev** [comment]
We just did, hope to stay within the limit now. Thanks!
