### ISSUE TITLE
write-host doesn't work in Powershell script

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/ci#3086]
hi, 
please review the following output info on appveyor console
![output](https://raw.githubusercontent.com/LongbowActions/images/master/appveyor/Screen%20Shot%202019-09-08%20at%2009.30.15.png)

appveyor.yml
```
test_script:
- ps: >-
    powershell .\test.ps1
```

.\test.ps1
```powershell
function testProj ($target) {
    $projName = "test\$($env:APPVEYOR_PROJECT_NAME).Test"
    write-host "dotnet test $projName -f $target" -ForegroundColor Cyan
    dotnet test $projName -f $target
}

$branch = $($env:APPVEYOR_REPO_BRANCH)
if ($branch -eq "master") {
	testProj net472
	testProj netcoreapp2.2
}
else {
    write-host """$($env:APPVEYOR_REPO_PROVIDER)"" UnitTest has been skipped as environment variable has not matched (""APPVEYOR_REPO_BRANCH"" is ""$($env:APPVEYOR_REPO_BRANCH)"", should be ""master"")" -BackgroundColor yellow -ForegroundColor black
}
```

as you see. what wrong with 
`write-host """$($env:APPVEYOR_REPO_PROVIDER)"" UnitTest has been skipped as environment variable has not matched (""APPVEYOR_REPO_BRANCH"" is ""$($env:APPVEYOR_REPO_BRANCH)"", should be ""master"")" -BackgroundColor yellow -ForegroundColor black`
it should be colored right?

**Comment by FeodorFitsner** [comment]
In a new Build Agent there is an experimental PTY emulation which is disabled by default.

You can enable coloring by defining `APPVEYOR_CONSOLE_ENABLE_PTY` = `true` environment variable on project settings. The output could be garbled sometimes though.

Let me know how it worked.

**Comment by ArgoZhang** [comment]
it looks doesn't work 😃 
[appveyor.yml](https://raw.githubusercontent.com/LongbowActions/appveyor/master/appveyor.yml)

**Comment by ArgoZhang** [comment]
you can check the output info from https://ci.appveyor.com/project/ArgoZhang/longbow-tasks/builds/27270496

**Comment by ArgoZhang** [comment]
I think this is maybe can improved by CI. it will work fine without Powershell key word. 
https://ci.appveyor.com/project/ArgoZhang/longbow-tasks/builds/27354228

### Solution
remove the **Powershell** key word
change `Powershell ./build.ps1` to `./build.ps1`
