### ISSUE TITLE
DirectX SDK on VS 2019 image

### ISSUE THREAD

**Issue by skychef** [appveyor/ci#3089]
The directx sdk https://www.microsoft.com/en-us/download/details.aspx?id=6812
is missing from the Visual Studio 2019 image.

When attempting to compile an application against the DXSDK using the Appveyor - Visual Studio 2019 image, I see the following message inside of the appveyor web console:
```
direct3d.h(23,10): error C1083:  Cannot open include file: 'd3dx9math.h': No such file or directory (compiling source file

Command exited with code 1
```

The DXSDK was available inside the Visual studio 2017 image.
Could the DXSDK please be added to the appveyor Visual Studio 2019 image?

IIRC the DXSDK installation location also needs to be added to the PATH but I suggest looking at how it is done in the 2017 image as it works correctly there.
Thanks.

**Comment by IlyaFinkelshteyn** [comment]
Will do. For now you can install in on-the-fly by adding this script at `init` stage. It will consume couple of minute though.

```
Write-Host "DirectX Software Development Kit..." -ForegroundColor Cyan

Write-Host "Downloading..."
$exePath = "$env:temp\DXSDK_Jun10.exe"
(New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe', $exePath)

Write-Host "Installing..."
$installPath = "C:\Program Files (x86)\Microsoft DirectX SDK"
cmd /c start /wait $exePath /P $installPath /U
Add-Path $installPath
Add-SessionPath $installPath

Remove-Item $exePath
Write-Host "Installed" -ForegroundColor Green
```

**Comment by skychef** [comment]
Cool. Thanks! @IlyaFinkelshteyn
