### ISSUE TITLE
PowerShell Core 6.2.3

### ISSUE THREAD

**Issue by bergmeister** [appveyor/ci#3096]
Background: PowerShell Core support policies state that after a patch release, one has to upgrade within a month to stay within support and for a minor version release, one has to update to the newer version in 6 months. https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-6

- The `Visual Studio 2019` image uses PowerShell Core `6.2.0`, which was released months ago, `6.2.2` or `6.2.3` should be used. Patches of PowerShell Core are usually only due to security and therefore non-breaking
- This means that in 2 weeks, PowerShell 6.1 generally goes out of support in 2 weeks but what does that mean for the Visual Studio 2017 image, which uses `6.1.0` (which has received several patches already as well in the last months and therefore unsupported as well)? Whilst I understand, you do not want to disrupt people in those legacy images, using unuspported version does not seem to be the right solution either. Please come up with a plan.

**Comment by bergmeister** [comment]
Any updates @FeodorFitsner  At the moment, I'd expect the new patch versions of PowerShell to be deployed.

**Comment by FeodorFitsner** [comment]
Will fix it early next week. Thanks for letting know about the issue!
