### ISSUE TITLE
Google GCloud SDK pre-installed on Linux build image

### ISSUE THREAD

**Issue by mattmckinstry** [appveyor/ci#3097]
Could we get the Google GCloud SDK pre-installed on the Linux build image?

**Comment by Wasapl** [comment]
Oh, Thank you for noticing this!
We were going to pre-install it but it fell through the cracks.
It will be installed in the next images update.

**Comment by mattmckinstry** [comment]
Actually, it would be good if this could be on the Visual Studio images too
