### ISSUE TITLE
Visual Studio 2019 Preview image with .NET Core 3.0 rc1

### ISSUE THREAD

**Issue by damienbod** [appveyor/ci#3098]
Just wondering if it would be possible to update the Visual Studio 2019 Preview image to support dotnet 3.0 rc1 SDK

Also wondering if there is an easy way to get the latest dotnet SDK as part of the build.

Best regards Damien

**Comment by SimonCropp** [comment]
a temp workaround 

```
install:
- cmd: choco install dotnetcore-sdk --pre
```

**Comment by FeodorFitsner** [comment]
And another fast way to install any version of .NET during the build:

```posh
Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
& $env:temp\dotnet-install.ps1 -Architecture x64 -Version $env:CORE_SDK_VERSION -InstallDir "$env:ProgramFiles\dotnet"
```

where `$env:CORE_SDK_VERSION` is the version of .NET Core SDK to install, e.g. `3.0.100-preview7-012821`.

**Comment by ddrinka** [comment]
v3.0.0 RTM is out today.  However VS 2019 16.3 isn't yet.  Love to have an image with RTM support up and running, even before the final VS 2019 release hits.

**Comment by christophwille** [comment]
We are actually hitting an issue with the current vs2019 image & installing netcore3.0 rtm: https://ci.appveyor.com/project/icsharpcode/avalonedit/build/job/vov6xg03r0k1sa7o seems that final SDK bits don't like working with 16.2 msbuild bits.

**Comment by damienbod** [comment]
16.4 is out now, maybe you could update the VS?

Greetings Damien

**Comment by EwoutH** [comment]
Can we update:

- Visual Studio 2019 image to [16.3](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.3.0)
- Visual Studio 2019 Preview image to [16.4 Preview 1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.4.0-pre.1.0)

It would be nice to keep te VS 2019 preview image up to date.

**Comment by IlyaFinkelshteyn** [comment]
`Visual Studio 2019` is updated to 16.3.0 and .NET SDK 3.0.100/runtime 3.0.0

**Comment by SimonCropp** [comment]
@IlyaFinkelshteyn thanks heap :) was the `Visual Studio 2019 Preview` image updated as well, or is that a different task?

**Comment by IlyaFinkelshteyn** [comment]
@SimonCropp that is different, that's why I am not closing this issue. Sorry for delay...

**Comment by FeodorFitsner** [comment]
Closing because of https://github.com/appveyor/ci/issues/3111
