### ISSUE TITLE
Bugbounty 

### ISSUE THREAD

**Issue by kenkit** [appveyor/ci#3099]
Hi,
Does appveyor offer some kind of  bugbounty program ?
I may have found bumped into possible security bug.

**Comment by FeodorFitsner** [comment]
Hi,

we don't have an official bugbounty program, but you may help us to make AppVeyor more secure by submitting issue details via email to team@appveyor.com.

Thank you!

**Comment by kenkit** [comment]
Ok,I will do so, let me first confirm if it's really a security issue.
