### ISSUE TITLE
OnPremise: Unable to upload artifacts to storage

### ISSUE THREAD

**Issue by itniels** [appveyor/ci#3109]
After updating to `7.0.2396`

I am now getting this error message when it's ready to upload to artifact storage!
On every single project!

`Error uploading artifact the storage: Unexpected end of Stream, the content may have already been read by another component. `

![image](https://user-images.githubusercontent.com/15611687/65722803-54e88780-e0ad-11e9-8522-36f6a3888dc9.png)

**Comment by FeodorFitsner** [comment]
Are there any other issues with that release? How was the update from previous version?

**Comment by itniels** [comment]
I have not found any other issues except the above :)
Upgrading went perfectly fine with no errors.
`7.0.2329 => 7.0.2396`

Update command run:
`
/opt/appveyor/server/appveyor version && cd /tmp && rm -f appveyor-server_latest_amd64.deb && curl -L https://www.appveyor.com/downloads/appveyor/appveyor-server.deb -o appveyor-server_latest_amd64.deb && dpkg -i appveyor-server_latest_amd64.deb
`

It's running on a `Ubuntu 18.04.3 LTS` virtual machine.

**Comment by FeodorFitsner** [comment]
Got it, it's Linux. Good, upgrade issue was on Windows.

Will be looking into be problem with artifacts upload, sorry for the inconvenience.

**Comment by itniels** [comment]
No worries and thank you @FeodorFitsner for very quick response :)

**Comment by itniels** [comment]
**Complete Environment Information**
AppVeyor: `v7.0.2396`
OS: `Ubuntu 18.04.3 LTS`
Cores: `2`
RAM: `4 GB`
Disk: NVMe SSD 40 GB
Build Image: `Based on “appveyor/build-image:minimal-ubuntu-18.04”`

**Comment by FeodorFitsner** [comment]
Could you please try upgrading into this (not yet officially released) release and let me know how it worked: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2414/appveyor-server_7.0.2414_amd64.deb

It contains a fix for uploading artifacts.

**Comment by itniels** [comment]
I re-built all the failed ones, and everything seems to work perfectly again! 😃 👍

**Comment by FeodorFitsner** [comment]
Sounds great, thanks for the update!

**Comment by itniels** [comment]
Thank you for the quick fix :)

**Comment by itniels** [comment]
Confirmed working in `7.0.2417` 👍 😃
