### ISSUE TITLE
Add v142 Platform Toolset to Visual Studio 2019 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3113]
Original request: https://help.appveyor.com/discussions/problems/25054-v140-and-v141-build-tools-are-missing-from-visual-studio-2019-image

**Comment by igagis** [comment]
I'm not sure about `v142`, I haven't checked if it is there or not

**Comment by SergeGautherie** [comment]
I am confused by this issue: doesn't `v142 == VS2019` (default)?
At least, It was when I last used VS2019 image, before its update a few days ago.

**Comment by igagis** [comment]
yes, I think this issue can be closed
