### ISSUE TITLE
WSL bash.exe conflicting with Git/MSYS one

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3133]
WSL installs `bash.exe` into `C:\Windows\System32` which takes precedence over bash.exe available in Git bin directory (`C:\Program Files\Git\usr\bin`) which is working and preferable by customers.

Possible solution is to rename WSL's bash to something like `wsl-bash.exe`.

As a quick workaround in your builds you can add to `appveyor.yml`:

```
init:
- del C:\Windows\System32\bash.exe
```

**Comment by Dekken** [comment]
@FeodorFitsner 

did anything come of that shell idea you mentioned here https://help.appveyor.com/discussions/problems/25118-bash-breaks-between-vs-2017-2019-images

eg.
```
- sh: 
```
