### ISSUE TITLE
Self-hosted Nuget package returns localhost url

### ISSUE THREAD

**Issue by NepPure** [appveyor/ci#3136]
Version:7.0.2417 
Windows Server 2016

![image](https://user-images.githubusercontent.com/12379907/66742372-0f4bfd00-eeaa-11e9-8616-27c074cefdc7.png)

![image](https://user-images.githubusercontent.com/12379907/66742418-2be83500-eeaa-11e9-8f82-f34e953b66f9.png)

**Comment by NepPure** [comment]
Using IIS reverse proxy

**Comment by NepPure** [comment]
Maybe can add this
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#other-proxy-server-and-load-balancer-scenarios
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    services.Configure<ForwardedHeadersOptions>(options =>
    {
        options.ForwardedHeaders = 
            ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseForwardedHeaders();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }

    app.UseStaticFiles();
    // In ASP.NET Core 1.x, replace the following line with: app.UseIdentity();
    app.UseAuthentication();
    app.UseMvc();
}
```

**Comment by FeodorFitsner** [comment]
This is what we have now in the code:

```csharp
            var forwardOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.All
            };
            app.UseForwardedHeaders(forwardOptions);
```

Maybe IIS is not forwarding those headers to AppVeyor? The current solution works with NGINX, but it should be properly configured to pass `X-Forwarded-*` headers.

**Comment by NepPure** [comment]
IIS 10 does not set X-Forwarded-Host header, I'm now looking for a solution.

**Comment by NepPure** [comment]
Solved by https://support.sonatype.com/hc/en-us/articles/115005086988-How-to-Configure-IIS-as-a-Reverse-Proxy-for-Sonatype-Products

**Comment by FeodorFitsner** [comment]
Thanks for posting the solution!
