### ISSUE TITLE
VS2019 and VS2019P: "find: ' ': No such file or directory"

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3147]
It looks like https://www.appveyor.com/updates/2019/10/13/ caused a "regression".

--

https://ci.appveyor.com/project/SergeGautherie/reactos/builds/28185866
```
call %APPVEYOR_BUILD_FOLDER%\configure.cmd %clang_configure_option%
find: ' ': No such file or directory
find: 'cmake version': No such file or directory
Unable to find cmake, if it is installed, check your PATH variable.
Command exited with code 1
```

**Comment by SergeGautherie** [comment]
Guess: related to issue 3133?

**Comment by FeodorFitsner** [comment]
You mean this issue: https://github.com/appveyor/ci/issues/3133? It was fixed, actually. Could it be another reason you get regression? In [line 38](https://ci.appveyor.com/project/SergeGautherie/reactos/builds/28150533/job/of59mm33wi8hq32s#L38) you are getting a "different" cmake, not cmake 3.15.1 installed by default and [available in the PATH](https://ci.appveyor.com/project/FeodorFitsner/bitbucket-private-git/builds/28157994#L12).

**Comment by SergeGautherie** [comment]
> You mean this issue: #3133?

Yes.

> It was fixed, actually.

Yes, I am wondering whether that fix could have caused this regression. Only a guess...

> Could it be another reason you get regression?

Sure. You know more than me what changed in that update...

> In line 38 you are getting a "different" cmake, not cmake 3.15.1 installed by default and available in the PATH.

Yes, that project uses its own custom CMake and updated PATH. As you can see, it has always worked fine, until the last image update.

**Comment by FeodorFitsner** [comment]
If your build was using/depending `bash.exe` from WSL distribution then you can move it back in PATH to have precedence and give it another try. Other than that it's hard to tell why the build is broken. I can only suggest to hop into VM via RDP and see what's going on there.

**Comment by SergeGautherie** [comment]
> If your build was using/depending bash.exe from WSL distribution

Project default is to use VS2015 image with x32/VS2010 and x64/VS2015. These builds still succeed.
Were/Are they affected by that bash/WSL issue?

> move it back in PATH to have precedence and give it another try

What should I add to my `appveyor.yml` to test that?

**Comment by SergeGautherie** [comment]
@FeodorFitsner, ping...

**Comment by SergeGautherie** [comment]
After https://www.appveyor.com/updates/2019/11/08/ ,
Preview/Regular are not fixed, Previous is now broken too,
Then, ReactOS project cannot be built with (any) VS2019 anymore :-(

**Comment by SergeGautherie** [comment]
I commented out updating the PATH: same broken result (but current cmake version).
https://ci.appveyor.com/project/SergeGautherie/reactos/builds/28732135

**Comment by SergeGautherie** [comment]
Git `find.exe` is used instead of Windows one :-/ (Wrong install option? Intended?)
And using a pipe, as in `xxx | find "yyy"` fails!
See https://ci.appveyor.com/project/SergeGautherie/reactos/builds/28732472

Workaround: `del "C:\Program Files\Git\usr\bin\find.exe"`.

**Comment by FeodorFitsner** [comment]
Good finding! Indeed, while building image we put `C:\Program Files\Git\usr\bin` in front of `PATH`, so git's `bash.exe` has precedence over WSL's `C:\Windows\bash.exe`. I kind of agree that hiding native `find` (and possibly other utilities) doesn't look good. What would be solution here?

**Comment by FeodorFitsner** [comment]
I think renaming `C:\Windows\System32\bash.exe` to something like `wsl-bash.exe` would be a better solution rather than pushing forward git's bin directory. If anyone needs WSL's bash in their builds they could rename it back. I added a new issue to fix in the next update: https://github.com/appveyor/ci/issues/3193

**Comment by SergeGautherie** [comment]
> What would be solution here?

With regard to WSL (`bash.exe`), I am not familiar with it and I don't know what requirements/issues are on AppVeyor.

With regard to Git, when I install v2.10 locally, I can choose from 3 `PATH` options: nothing, Git only, Git and utilities. I choose 'Git only', which is recommended (to avoid such overlaps) and enough (for my usual use)...

**Comment by SergeGautherie** [comment]
`VS2019`:
fixed by https://www.appveyor.com/updates/2019/12/09/ :-)
(`Git` now comes later than `System32`, in the `PATH`.)

`VS2019 Preview`:
will hopefully be fixed on its next update (of all other tools too: `7-Zip`, `CMake`, ...).
