### ISSUE TITLE
BYOC in AppVeyor Server - setup new build cloud with ease

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3149]

**Comment by xclayl** [comment]
Would it include a checkbox for "Docker Host" within Assisted Setup?  If not, I'll add another issue for Docker.

**Comment by FeodorFitsner** [comment]
Could you elaborate more on your request please?

**Comment by xclayl** [comment]
There are checkboxes to include ".NET Framework Developer Packs (4.5.2 - 4.8)" and "Java 7-8" (and many others) in the Assisted Setup.  There isn't an option to include a Docker Host with the ability to run Linux and Windows images.  I'd love to see a checkbox for that, b/c it sounded complicated to get everything in Docker working right.

**Comment by FeodorFitsner** [comment]
Got it. So, are you building images in Azure, right?
