### ISSUE TITLE
Fetching repository commit (64a6c61)...Cannot download GitHub repoitory contents: Forbidden

### ISSUE THREAD

**Issue by hugovk** [appveyor/ci#315]
Making a [PR](https://github.com/python-pillow/Pillow/pull/1298), I get:

```
Build started
ECHO %PYTHON%
C:/Python27-x64
Fetching repository commit (64a6c61)...Cannot download GitHub repoitory contents: Forbidden
```
https://ci.appveyor.com/project/Pythonpillow/pillow/build/2.9.pre.46

Travis CI can access can access the commit and build the PR:
https://travis-ci.org/python-pillow/Pillow/builds/68436723

The same thing builds on my own AppVeyor account:
https://ci.appveyor.com/project/hugovk/pillow/build/2.9.pre.6

Both my repo and the target repo are public.

Any idea what's wrong?

**Comment by FeodorFitsner** [comment]
We are looking into that. It's related to GitHub organization permissions that are in effect now: https://developer.github.com/changes/

As a workaround remove `shallow_clone: true` from `appveyor.yml`: https://github.com/python-pillow/Pillow/blob/master/appveyor.yml#L2

**Comment by wiredfool** [comment]
Looks like we're good with the workaround. And... fast too. Got a build (successfully) finishing in 2 minutes, when last week it was more like 5.

**Comment by FeodorFitsner** [comment]
That's because we are moving OSS accounts to a new environment: http://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support

**Comment by wiredfool** [comment]
Cool. The speedup is really nice.

**Comment by FeodorFitsner** [comment]
Right now I'm unable to reproduce this issue on our public and private test repos.

AppVeyor uses this URL to download repo as tarball: https://api.github.com/repos/python-pillow/Pillow/zipball/64a6c61516d12ef45c2c07d719fb5cdc0297816b and it works fine.

**Comment by FeodorFitsner** [comment]
Here I'm simulating this scenario: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.540

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by hugovk** [comment]
@FeodorFitsner Thank you!

**Comment by Jens-G** [comment]
All of a sudden we get these messages as well:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/thrift/builds/31754248/job/wa491yoobkitqhni

What could be the reason?

**Comment by FeodorFitsner** [comment]
Try checking if GitHub authorization is still valid/active for your AppVeyor account (either "New project" page or "Account -> Authorizations".

**Comment by juergba** [comment]
We have the same errors at Mocha. Restarting the failed job once (sometimes twice or 3x) executes the tests successfully.

**Comment by FeodorFitsner** [comment]
@juergba could you drop a link to project please?

**Comment by juergba** [comment]
Yes, the errors have been happening since approx. two weeks.
[Mocha](https://ci.appveyor.com/project/boneskull/mocha/builds/31716384)
[Mocha](https://ci.appveyor.com/project/boneskull/mocha/builds/31800951)

**Comment by FeodorFitsner** [comment]
A "good" thing about these errors is that there is 403 Forbidden status which comes from GitHub which means it's not a connectivity issue, but a request reached the destination and response was received.

403 looks like API rate limiting - could you please make sure GitHub authorization is still OK for `boneskull` account and you can see the list of repositories on "New project" page? When authorization is set a token is passed to GitHub API to increase rate limits.

**Comment by juergba** [comment]
Thank you. Yes, GitHub authorization for `boneskull` account seems ok and I can see the repository list "Select repository for your new project". It takes a few seconds to build the list though.
