### ISSUE TITLE
Visual Studio 2017 Preview: sync' image, based on VS2017 image

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3151]
The `VS2017P` image is not a "`VS2017` + a few previews" that I would expect:
```
VS2017 : msbuild 15.9.21.664  , ...
VS2017P: msbuild 15.9.19.36755, 'Windows SDK version 10.0.18362.0 was not found', ...
```

I suggest to either resync' it (similar to #3132) or simply remove it (see #3125)...

--

Currently, `VS2017P` fails to build WinBtrfs project, obviously.
See https://ci.appveyor.com/project/SergeGautherie/btrfs/builds/28167529 .

--

You might, or not, want to upgrade Windows on both `VS2017` and `VS2017P`: to `WS2019 (10.0.17763)` from `WS2016 (10.0.14393)`.

**Comment by FeodorFitsner** [comment]
So, why would we need "Visual Studio 2017 Preview" image if there are no VS 2017 previews anymore? We should discontinue that image instead to avoid any confusion.

**Comment by SergeGautherie** [comment]
> We should discontinue that image

I concur: let's proceed with #3125 then.
