### ISSUE TITLE
Go 1.13.3, 1.12.12, 1.11.13

### ISSUE THREAD

**Issue by thrasher-** [appveyor/ci#3156]
Go 1.13 has been released: https://golang.org/dl/. I can see it is supported on the [Linux image](https://www.appveyor.com/docs/windows-images-software/#golang) but not on [Windows](https://www.appveyor.com/docs/windows-images-software/#golang). Just wondering when AppVeyor will add support for it?

**Comment by FeodorFitsner** [comment]
Thanks for letting know! Will include it during the next image update.

**Comment by thrasher-** [comment]
No problem, also is there any ETA on the next image update for Windows?

**Comment by FeodorFitsner** [comment]
Week-two - we are currently working on the next update.

In the meantime, you can use the following snippet to install Go 1.13.3 into `C:\go113` during the build:

```posh
$goDistPath = "$env:TEMP\go1.13.3.windows-amd64.zip"
(New-Object Net.WebClient).DownloadFile('https://dl.google.com/go/go1.13.3.windows-amd64.zip', $goDistPath)
7z x $goDistPath -oC:\go1133-x64 | Out-Null
[IO.Directory]::Move('C:\go1133-x64\go', 'C:\go113')
Remove-Item 'C:\go1133-x64' -Recurse -Force
del $goDistPath
```

**Comment by thrasher-** [comment]
Thanks @FeodorFitsner !
