### ISSUE TITLE
Node 13.0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3157]

**Comment by kendaleiv** [comment]
Could we update the `STABLE`/`CURRENT` and `LTS` versions too if that isn't already planned?

**Comment by FeodorFitsner** [comment]
Stable/Current has been updated to `13.0.1` and `LTS` to `12.13.0`.

**Comment by gengjiawen** [comment]
Is it possible to make 13 default instead of 8 ?

**Comment by FeodorFitsner** [comment]
I'm afraid it's going to break a lot of builds. 13.x is not even LTS, it's "Current".

Instead you may switch to 13.x during the build:

```
install:
  - ps: Install-Product node 13
```
