### ISSUE TITLE
Update Cygwin and preinstall on VS 2019

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#3160]
[Cygwin](https://www.cygwin.com/) is currently using an outdated version, and isn't preinstalled on the Visual Studio 2019 image,

 - [ ] Update Cygwin 2.10.0 x64 to Cygwin 3.0.7 x64
 - [ ] Install Cygwin x64 on the Visual Studio 2019 image

**Comment by FeodorFitsner** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/3101
