### ISSUE TITLE
hitting artifact storage limit

### ISSUE THREAD

**Issue by Optiligence** [appveyor/ci#3178]
>Maximum allowed artifact storage size of 50000 Mb will be exceeded.

https://github.com/knossos-project/knossos
https://ci.appveyor.com/project/knossos/knossos/builds/28588924/job/p2316ac1db57pyax

Can you increase our limit?

**Comment by FeodorFitsner** [comment]
It's been increased.

**Comment by Optiligence** [comment]
hi, hitting it again
>Maximum allowed artifact storage size of 70000 Mb will be exceeded.

Can you increase it further?

**Comment by FeodorFitsner** [comment]
It's been bumped.

**Comment by Optiligence** [comment]
hi
>Maximum allowed artifact storage size of 100000 Mb will be exceeded.
Can you increase it further again?

**Comment by FeodorFitsner** [comment]
Done.
