### ISSUE TITLE
Error connecting Host Agent to AppVeyor: The server disconnected before the handshake could be started.

### ISSUE THREAD

**Issue by belidzs** [appveyor/ci#3184]
I'm trying to connect a Windows 10 build agent to my self-hosted AppVeyor instance running on a separate linux box, but the agent can't seem to connect to the server.

## Agent environment
* Windows 10 Enterprise 1903
* behind NAT
* newest Host Agent as of today (8th Nov)

## Server environment
* Linux gcp-1 4.15.0-1047-gcp #50-Ubuntu SMP Wed Oct 2 00:50:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* AppVeyor Team Edition 7.0.2546
* Running on localhost behind SSL reverse proxy
* Reverse proxy: nginx/1.16.1, configuration: https://pastebin.com/QNdzRX8Y

## Logs
* event viewer log of host agent: [appveyor.zip](https://github.com/appveyor/ci/files/3826191/appveyor.zip)
* nginx access log: https://pastebin.com/bCP5FXH1
* relevant syslog: https://pastebin.com/7KKwYNh4

The agent was installed using the powershell commands which were generated by the web interface. The install was successful, the new build cloud appeared on the interface and the script reportede success however it still shows as offline and an error is thrown in the event log.

**Comment by belidzs** [comment]
I have temporarily opened up 8050 to directly connect the host agent to the server and now it works that way so the problem must be in the reverse proxy configuration

Is there any way I can crank up the log level for the host agent?

**Comment by FeodorFitsner** [comment]
Thanks for trying that config and for the update! Host Agent is already logging on Information level. I don't think we'd get more detailed information from SignalR with increased verbosity level.

Do you have any WebSocket-specific configuration settings in NGINX config? Last time we tried AppVeyor with NGINX as reverse proxy the config was quite trivial.

**Comment by belidzs** [comment]
I don't think there's anything special which would affect websockets but sadly I'm not an nginx expert at all. I have other services using websockets using more or less the same config and they run just fine.

Is running AppVeyor behind a reverse proxy an unusual thing to do? Since it has to face the internet to receive webhooks I imagined it's better to put it behind a more robust web server

**Comment by FeodorFitsner** [comment]
AppVeyor Server is a "classic" ASP.NET Core 3.0 app. Take a look at this SO thread: https://stackoverflow.com/questions/48300288/signalr-in-asp-net-core-behind-nginx - maybe this could be helpful.

**Comment by FeodorFitsner** [comment]
Similar: https://medium.com/@alm.ozdmr/deployment-of-signalr-with-nginx-daf392cf2b93

**Comment by belidzs** [comment]
Thanks for the useful links, they were very useful and led me to fix this issue.

The key was that the SignalR endpoints at `/HostAgentHub`, `/BuildAgentHub` and `/BrowserHub` had to be served with the `Connection "upgrade"` header while everything else had to be sent with the typical `Connection "keep-alive"` header.

When everything was sent with the `upgrade` header the agent was able to connect but I couldn't start a new build on the website by clicking on the play button. When I tried that, a message with red background popped up (containing my password in clear text in a big JSON object)

Without the `Connection "upgrade"` the agent wasn't able to connect to the AppVeyor API.

So it seems that everything works now, I was able to run a simple build. Here's my final config, maybe it's useful for others:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name example.com;

    ssl_certificate /root/.acme.sh/example.com/fullchain.cer;
    ssl_certificate_key /root/.acme.sh/example.com/example.com.key;

    access_log /var/log/nginx/access-appveyor.log;
    error_log /var/log/nginx/error-appveyor.log warn;

    location / {
        proxy_pass        http://localhost:8050;
        proxy_http_version 1.1;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection keep-alive;
        proxy_set_header  Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_set_header  X-Real-IP $remote_addr;
    }

    location ~ ^/(HostAgentHub|BuildAgentHub|BrowserHub)$ {
        proxy_pass        http://localhost:8050;
        proxy_http_version 1.1;
        proxy_set_header  Upgrade $http_upgrade;
        proxy_set_header  Connection upgrade;
        proxy_set_header  Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_set_header  X-Real-IP $remote_addr;
    }
}
```

Thanks @FeodorFitsner for your repeated help!

**Comment by FeodorFitsner** [comment]
Fantastic! Thanks for sharing the final and working config!
