### ISSUE TITLE
Rename WSL's bash.exe in favor of Git's bash.exe

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3193]
Original discussion: https://github.com/appveyor/ci/issues/3147

Solution:

```
takeown /F C:\Windows\System32\bash.exe
icacls C:\Windows\System32\bash.exe /grant administrators:F
ren C:\Windows\System32\bash.exe wsl-bash.exe
```

**Comment by SergeGautherie** [comment]
Is that what people usually do locally?
Should that be the default, or should affected people explicitly set a different bash.exe (Git or other) up?
