### ISSUE TITLE
Add vcpkg to linux image

### ISSUE THREAD

**Issue by adam4813** [appveyor/ci#3194]
VCPKG works greats on the windows images and it is available for all major OSs now. By adding it to the standard linux image it would allow us to cache the packages used on linux builds as well.

**Comment by Raffaello** [comment]
the linux tool documentation page might be worth to be updated too: https://www.appveyor.com/docs/linux-images-software/

also would be nice to have it on macOS if not already present

**Comment by FeodorFitsner** [comment]
Docs have been updated. Added an issue to install `vcpkg` on macOS images: https://github.com/appveyor/ci/issues/3416
