### ISSUE TITLE
CygWin with Python 3.8

### ISSUE THREAD

**Issue by andy-maier** [appveyor/ci#3196]
Python 3.8 has been released end of october 2010. Other CI environments already provide support for that released version.

The request is for Appveyor to provide Python 3.8 for the CygWin 32-bit and 64-bit environments.

**Comment by FeodorFitsner** [comment]
We'll add Python 3.8 to Cygwin during the next images update.

For now, you can use the following workaround to install `python38` package:

    cmd /c start /wait C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -P python38

You should have `python3.8.exe` in the PATH after that.
