### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by stekyne** [appveyor/ci#3200]
https://ci.appveyor.com/project/csound/csound/builds/28865829 

We've started hitting this lately after some increased activity on the project. Is it possible to clear out our older builds or increase the cap?

Ideally, it would be nice to discard artefacts for particular branches. Is this possible?

**Comment by FeodorFitsner** [comment]
The quota has been increased.
