### ISSUE TITLE
Xcode 9 on macOS images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3212]

**Comment by past-due** [comment]
It would be fantastic if you could keep the latest stable / point release of each major Xcode release around.

i.e.
+ Xcode 9.4.1
+ Xcode 10.3

Then users can decide which one to use at build-time via:
`xcode-select -switch <path/to/>Xcode.app`

For example, some folks install all the versions side-by-side with paths like:
/Applications/Xcode_11.3.1.app
/Applications/Xcode_10.3.app
/Applications/Xcode_9.4.1.app

(In your VM image you can then set the default via `xcode-select -switch /Applications/Xcode_11.3.1.app`)

**Comment by cfillion** [comment]
Having a range of major Xcode versions to choose from at build-time would be extremely useful.

Xcode 9 is the last major version to support 32-bit builds, and the new Xcode 12 is required for making arm64 builds for Apple's new CPUs.

**Comment by FeodorFitsner** [comment]
Cool, working on the update!

**Comment by cfillion** [comment]
Has there been any progress on the update? (I don't want to bother too much, but with Travis CI's new OSS pricing I'm suddenly left without a way to reliably produce 32-bit macOS builds.)

Just to be precise, Xcode 9 can only be installed on the Mojave image (it's [broken](https://developer.apple.com/forums/thread/126967) on 10.15) and Xcode 12 can only be installed on the Catalina image.

Also, adding to @past-due's comment, `Contents/Developer` must be appended to the path when using `xcode-select --switch`.
```sh
xcode-select --switch /Applications/Xcode-9.4.1.app/Contents/Developer
xcode-select --switch /Applications/Xcode-11.3.1.app/Contents/Developer
xcode-select --switch /Applications/Xcode-12.2.app/Contents/Developer
```

**Comment by FeodorFitsner** [comment]
XCode 9.4.1 has been added to `macos` and `macos-mojave` images: https://www.appveyor.com/updates/2020/12/27/
