### ISSUE TITLE
Python stack is not working on macos image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3213]
From the original report:

```
Enabling Python 2.7.16
/usr/local/Cellar/appveyor-build-agent/7.0.2546/bash-shell.sh: line 62: /Users/appveyor/venv2.7.16/bin/activate: No such file or directory
Error enabling 'python' stack: Command exited with code 1
```

According to https://www.appveyor.com/docs/macos-images-software/#python the image should have v2.7.17, so I modified my appveyor.yml file to specify 2.7.17 but then I get this error instead:
Error enabling 'python' stack: Python version not found: 2.7.17. Available Python versions: 2.6.9, 2.7.16, 3.4.9, 3.5.7, 3.6.8, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0

**Comment by joachimmetz** [comment]
It looks like `stack` only works on linux images.

For a work-around after some experimentation
* `python` gives me `2.7.10`
* `python3` gives me `3.7.5`

thought invoking `python3` does not seem to work all the time, instead invoke `/usr/local/bin/python3.7` directly.

**Comment by jacobq** [comment]
> It looks like `stack` only works on linux images.

Shouldn't it be ignored by other images then? For example, it doesn't seem to cause a problem on `Visual Studio 2017`. Should I be setting it inside of `for` then?

**Comment by joachimmetz** [comment]
@jacobq I don't know, just put my observations here.

**Comment by jacobq** [comment]
@FeodorFitsner I hate to be a nag and post an "Is there any update on this?" comment, but it's been a few months of silence, and this problem is preventing me from using the MacOS images to build our app in CI. Are there any public links you can share regarding work that's being/been done on these images or this particular problem?

**Comment by jacobq** [comment]
🎉 Thank you! 🙏 🥂 🚀
