### ISSUE TITLE
Notifications: Event data jobs array is randomly sorted

### ISSUE THREAD

**Issue by cfillion** [appveyor/ci#3219]
I am trying out the pull request notification feature to post a consolidated list of artifacts across all jobs in a build. The event data's `jobs` array appears to have the jobs sorted in no particular order (it randomly changes every time): [example](https://github.com/cfillion/sws/pull/1#issuecomment-557863593).

Could the jobs be sorted in the order they were run? I am using the following configuration in .appveyor.yml:

```yaml
notifications:
  - provider: GitHubPullRequest
    template: |-
      {{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
      {{#passed}}{{#jobs}}

      <details>
      <summary>{{name}}</summary>

      {{#artifacts}}
      - [{{fileName}}]({{permalink}})
      {{/artifacts}}
      </details>
      {{/jobs}}{{/passed}}
```

**Comment by FeodorFitsner** [comment]
Thanks for reporting that. We'll fix that and deploy an update later this week.

**Comment by cfillion** [comment]
It's been almost a year and the `jobs` array is still in random order in notifications. Any updates?

**Comment by FeodorFitsner** [comment]
I'm on it, sorry about that!

**Comment by FeodorFitsner** [comment]
It should be fixed now.

**Comment by cfillion** [comment]
Thank you!
