### ISSUE TITLE
PostgreSQL 12

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3223]
Original request: https://help.appveyor.com/discussions/problems/25522-postgresql-12

**Comment by mikependon** [comment]
Hi @FeodorFitsner, I am interested on this update. I am currently using AppVeyor for all my Unit and Integration Tests.  I get stumbled as well on PostgreSql as it (AppVeyor) seems not supporting the latest version. When do we expect this service be available?

**Comment by FeodorFitsner** [comment]
We've just deployed updated images with PGSQL 12 pre-installed.

**Comment by mikependon** [comment]
Thank you for the updates. I just looked at my CI build, I could not see PostgreSql 12 in the Environment Service.

Are your referring to the POSTGRESQL service?

**Comment by FeodorFitsner** [comment]
UI is not updated yet. Just add `net start postgresql-x64-12` at the beginning of your build to start PostgreSQL 12 service.
