### ISSUE TITLE
GitVersion on VS 2019 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3228]

**Comment by gep13** [comment]
@FeodorFitsner just wanted to give you a heads up on this...

What version of GitVersion were you planning on installing on the base image, and also what implementation of GitVersion, i.e. .Net Global Tool, Full Framework etc?

The reason that I ask is that there is a known issue with the 5.1.2 release of GitVersion specifically when running on AppVeyor.  The team are working on fixing this, but just wanted to make sure that this didn't immediately bite you once you release the base image.

**Comment by FeodorFitsner** [comment]
Thanks for the heads up! Indeed, we are installing the latest version available. We'll fix the version for now.

**Comment by gep13** [comment]
@FeodorFitsner let us know if you run into any problems with it!

**Comment by jameswoodley** [comment]
Am getting the issue @gep13 mentioned today. I'm not installing GitVersion in an install: part, just using the version in the image. Get the error:

```
ERROR [12/12/19 10:29:28:01] An unexpected error occurred:
System.TypeLoadException: Could not load type 'System.ComponentModel.AsyncCompletedEventArgs' from assembly 'System.Net.WebHeaderCollection, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at GitVersion.BuildServers.AppVeyor.GenerateSetParameterMessage(String name, String value)
   at GitVersion.OutputFormatters.BuildOutputFormatter.GenerateBuildLogOutput(IBuildServer buildServer, VersionVariables variables)
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
   at GitVersion.ExecCommand.Execute()
   at GitVersion.GitVersionExecutor.VerifyArgumentsAndRun(Arguments arguments)
```

If you wanna see the build:
https://ci.appveyor.com/project/james_lightestnight/system-caching/builds/29490559

**Comment by FeodorFitsner** [comment]
On image we've got 5.1.1, not 5.1.2. Does it have the issue too?

**Comment by jameswoodley** [comment]
Seems to I'm afraid. Following some advice on Stackoverflow and other Google articles I could find, the best bet was to fix to version 4.0.0 - can confirm this has worked, I haven't gone searching up the versions to find the one that breaks it

**Comment by FeodorFitsner** [comment]
So, all 5.x versions don't work in AppVeyor environment?

**Comment by jameswoodley** [comment]
Just tried it with 5.0.0 and it failed so without manually going through each version, I'd argue yes, anything 5.x.x doesn't work in AppVeyor
