### ISSUE TITLE
Unable to find package dbup-core with version (>= 4.3.1)

### ISSUE THREAD

**Issue by pwelter34** [appveyor/ci#3230]
When trying to update dbup-sqlserver to version 4.3.1, i get an error `Unable to find package dbup-core with version (>= 4.3.1)`.  If you [look under nuget](https://www.nuget.org/packages/dbup-sqlserver/), you'll see that it lists dbup-core version 4.3.1 as a dependence.  When you [look at dbup-core](https://www.nuget.org/packages/dbup-core/), there is not version with that number.

**Comment by FeodorFitsner** [comment]
Could you please elaborate how it's related to AppVeyor?

**Comment by pwelter34** [comment]
weird, swear i put this on the dbup repo.  Sorry about that.
