### ISSUE TITLE
Update clang on Ubuntu image

### ISSUE THREAD

**Issue by swaldhoer** [appveyor/ci#3237]
On Windows a current clang version is installed (9.0.0). On the Ubuntu image a pretty old version is installed (6.0.1).

For  the ``Ubuntu`` image install instructions should be (locally tested and worked):
```sh
sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
sudo apt-get install -y clang-9
sudo update-alternatives --install /usr/bin/clang clang /user/bin/clang-9 100
```

For  the ``Ubuntu 1604`` image install instructions should be (untested as I do not have a Xenial machine):
```sh
sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main"
sudo apt-get install -y clang-9
sudo update-alternatives --install /usr/bin/clang clang /user/bin/clang-9 100
```

**Comment by zufuliu** [comment]
clang+llvm 9.0.1 binary for Ubuntu 16.04 (clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz) is ready at https://github.com/llvm/llvm-project/releases/tag/llvmorg-9.0.1

**Comment by Wasapl** [comment]
We have updated Ubuntu images with preinstalled clang 9.0.1.
