### ISSUE TITLE
.NET Core SDK 3.1.100 on Ubuntu images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3238]
Original request: https://github.com/appveyor/ci/issues/3234#issuecomment-562496374

**Comment by PureKrome** [comment]
Any update on this please?

**Comment by jchannon** [comment]
I moved to Github Actions

**Comment by FeodorFitsner** [comment]
Updated images are coming in a few days. Thanks for your patience!

**Comment by PureKrome** [comment]
Thanks @FeodorFitsner

**Comment by Wasapl** [comment]
.NET Core SDK 3.1.100 preinstalled on Ubuntu images
