### ISSUE TITLE
How to fix 'msbuild' is not recognized as an internal or external command error?

### ISSUE THREAD

**Issue by dehghani-mehdi** [appveyor/ci#3239]
I can run msbuild commands via cmd, so msbuild is definitely exists in the `PATH`. I tried to restart the `Appveyor.Server` service, but still got the error. what should I do?

I can build the solution via cmd using following command _copied form appveyor_
> msbuild Test.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\Server\netfx\Appveyor.MSBuildLogger.dll"

**Comment by FeodorFitsner** [comment]
Make sure it's in `PATH` and then restart the service.

**Comment by dehghani-mehdi** [comment]
@FeodorFitsner I think I already mentioned about `PATH` and restarting service.

**Comment by FeodorFitsner** [comment]
OK, try adding `echo %PATH%` to your build to see what you have there.

**Comment by dehghani-mehdi** [comment]
Thank you @FeodorFitsner , that was helpful and I found the problem.
