### ISSUE TITLE
Git 2.25.0

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#3242]
Over at AOMediaCodec/[libavif](https://github.com/AOMediaCodec/libavif) we have problems using `git clone --shallow-since` on the AppVeyor VS 2017 image. We suspect heavily that it's caused by the older Git version that VS 2017 provides (currently 2.17). To avoid future problems, could Git be updated to [2.24](https://github.com/git/git/releases/tag/v2.24.0) on (at least) the VS 2017 and VS 2019 images?

```
Cloning into 'aom'...
fatal: Server does not support --shallow-since
fatal: The remote end hung up unexpectedly
```

- [Example build](https://ci.appveyor.com/project/louquillio/libavif-93od3/builds/29410381)
- [PR](https://github.com/AOMediaCodec/libavif/pull/34)

**Comment by FeodorFitsner** [comment]
Sure, will update Git in the next images update.

**Comment by EwoutH** [comment]
[Multiple Git vulnerabilities in 2.24 and older](https://github.blog/2019-12-10-multiple-git-vulnerabilities-in-2-24-and-older/)

**Comment by FeodorFitsner** [comment]
Got it, thanks for heads up!

**Comment by zufuliu** [comment]
2.25 is already released.
