### ISSUE TITLE
Qt 5.14.0 on VS 2019 image

### ISSUE THREAD

**Issue by Megamouse** [appveyor/ci#3245]
See: https://www.qt.io/blog/qt-5.14-has-released

**Comment by nschimme** [comment]
@FeodorFitsner Any reason we didn't put this on 2017 as well?

**Comment by FeodorFitsner** [comment]
Image size, basically, which is growing fast because of Qt :). Is it possible for you to try VS 2019 image where Qt 5.14 is available?

**Comment by nschimme** [comment]
I did @FeodorFitsner but it doesn't seem to work. There is some packaging problem that I can't explain:

https://github.com/MUME/MMapper/pull/182
https://ci.appveyor.com/project/nschimme/mmapper/builds/30300880/job/yse5ow8d5gl1b4mg

**Comment by nschimme** [comment]
@FeodorFitsner there seems to be an upstream Qt 5.14 bug preventing MingW builds from packaging their targets. We will need to upgrade to Qt 5.14.1 ASAP when they release it.

More details: https://bugreports.qt.io/browse/QTBUG-80763

**Comment by FeodorFitsner** [comment]
Sure, will update it once it's released.

**Comment by nschimme** [comment]
@FeodorFitsner FYI: https://www.qt.io/blog/qt-5.14.1-released

**Comment by FeodorFitsner** [comment]
It's not merged to the master yet, but you can give a try to this script that allows you installing any Qt component of any version during the build: https://gist.github.com/FeodorFitsner/61741c22b8ec5f34959dab1cfe2a9481

Maybe we should publish it as PowerShell Gallery module...
