### ISSUE TITLE
Qt 5.12.6 on VS 2019 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3248]
Original request: https://help.appveyor.com/discussions/questions/44952-any-timeline-for-qt-5126-in-windows-images-fatal-bug-in-qt-5125

**Comment by tsteven4** [comment]
I need it with vs2017, can we have it there as well?

**Comment by FeodorFitsner** [comment]
That will be deployed as well.

**Comment by tsteven4** [comment]
This doesn't seem to have made it to the Visual Studio 2017 build image:
https://ci.appveyor.com/project/gpsbabel/gpsbabel/builds/30045887/job/q8vucrcbmgvj13op
