### ISSUE TITLE
Allow common configuration in branches-specific appveyor.yml

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#325]
Dicsussion: http://help.appveyor.com/discussions/suggestions/728-shared-settings-for-appveyoryml-with-conditional-branches

**Comment by briandonahue** [comment]
:+1: on this - I could definitely use it.

**Comment by saper** [comment]
Same here (https://help.appveyor.com/discussions/questions/1655-less-code-duplication-in-appveyoryml-when-using-branchesony).

There was a [suggestion](https://github.com/sass/node-sass/pull/1135#issuecomment-138894003) that some YAML parsers accept `>>` syntax to include named nodes.

**Comment by remkoboschker** [comment]
any updates on this?

**Comment by AlexHayton** [comment]
We could really use this for our deployment process (the only difference is one line between the steps). We are currently implementing a powershell polyfill for this. @FeodorFitsner do you have any plans to include this soon?

**Comment by kneumei** [comment]
:+1:

**Comment by FeodorFitsner** [comment]
We may start working on that soon. @AlexHayton what's the idea behind your PS polyfill?

**Comment by AlexHayton** [comment]
I've written a powershell script that inspects $env:APPVEYOR_REPO_BRANCH
and $env:APPVEYOR_PULL_REQUEST_NUMBER, if it matches a list of environments
it runs the deploy.

For some reason this script isn't running when I set it as deploy_script:,
so I added it at the end my custom build steps.

**Comment by PureKrome** [comment]
@FeodorFitsner any chance we could _please_ get this worked on next. PLEASE!! We're starting to find that our `appveyor.yml` files are starting to get really big because we're copying/pasting massive amounts of common sections.

**Comment by espoelstra** [comment]
+1 for the Yaml anchors &configname and references to "inherit" values from where it was originally defined.

**Comment by lukefrake** [comment]
👍 like the sound of this!

**Comment by steven-dawkins** [comment]
this would be really useful for us!

**Comment by flanza** [comment]
really looking forward to it!

**Comment by flanza** [comment]
Is there some pespective of getting this feature released? It would be really usefull for all the comunity.

**Comment by IlyaFinkelshteyn** [comment]
We may need to include tags in scenario too.

**Comment by FeodorFitsner** [comment]
The feature has been delivered and documented here: https://www.appveyor.com/blog/2017/08/01/sharing-configuration-between-branches-in-appveyor-yml/

Let us know if you have any questions/comments.

**Comment by sehcheese** [comment]
Great thank you!

**Comment by PureKrome** [comment]
Loving the new `Sharing` facility in `.yml` files!
