### ISSUE TITLE
Python 3.8.1 x64 image using Visual Studio 10.0 instead of 14.0

### ISSUE THREAD

**Issue by robbmcleod** [appveyor/ci#3250]
In trying to continuous integration for the Python package NumExpr for Python 3.8.1, I see that it tries to build the 64-bit version with Visual Studio 10.0:

https://ci.appveyor.com/project/robbmcleod/numexpr/builds/29583748/job/dnld6soovq6co339

whereas the 32-bit version uses the right compiler:

https://ci.appveyor.com/project/robbmcleod/numexpr/builds/29583748/job/302ytaw6yeclyvrk

Here's the `appveyor.yml` file that was used:

https://github.com/pydata/numexpr/blob/master/appveyor.yml

**Comment by Harmon758** [comment]
This is likely because [the target is Windows 7](https://github.com/pydata/numexpr/blob/master/appveyor/run_with_env.cmd), as the build console log shows.

Also, Python 3.8.1 hasn't been released yet, so this is with Python 3.8.0, as the build console log also shows.

**Comment by robbmcleod** [comment]
Our fault, sorry. I forgot I didn't write the appveyor scripts for `numexpr`.
