### ISSUE TITLE
Install doxygen and graphviz on Windows and Ubuntu

### ISSUE THREAD

**Issue by swaldhoer** [appveyor/ci#3263]
It would be good to have doxygen and Graphviz installed on Windows and Ubuntu.

**Windows**
- Doxygen
  - ``curl -o doxygen-x64.zip http://doxygen.nl/files/doxygen-1.8.17.windows.x64.bin.zip``
  - ``7z e doxygen-x64.zip``
  - Add directory ``<downloaddirectory>\doxygen`` to %PATH%
- Graphviz:
  - ``curl -o graphviz.zip https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.zip``
  - ``7z x graphviz.zip`` (``x`` is important, not ``e``)
  - Add directory ``<downloaddirectory>\release\bin`` to %PATH%

**Ubuntu**
- Doxygen (not via apt, as the package is quite old)
  - ``curl -o doxygen.tar.gz http://doxygen.nl/files/doxygen-1.8.17.linux.bin.tar.gz``
  - ``tar -xzf doxygen.tar.gz``
  - Add ``<downloaddirectory>/doxygen-1.8.17/bin`` to $PATH
- Graphvi:
  - ``apt-get install -y graphviz``

**Comment by Wasapl** [comment]
We have updated Ubuntu images with doxygen and graphviz

**Comment by swaldhoer** [comment]
Will these also be installed on Windows Images?

**Comment by swaldhoer** [comment]
Is there a chance that thid will be inlcuded on the Windows images?

**Comment by FeodorFitsner** [comment]
Will add them to VS 2019 image during the next image update.

**Comment by swaldhoer** [comment]
@FeodorFitsner Doxygen and Graphiviz have not been added to the [latest VS 2019 update](https://www.appveyor.com/updates/2020/05/29/). How are the chances that they will installed in the next image update?

**Comment by FeodorFitsner** [comment]
@swaldhoer Sorry about that! Will be included into the next update!

**Comment by swaldhoer** [comment]
@FeodorFitsner doxygen and graphviz are both not mentioned in https://www.appveyor.com/updates/2020/07/03 therefore I assume doxygen and graphviz habe not been added?

**Comment by FeodorFitsner** [comment]
Ah, sorry for that!
