### ISSUE TITLE
build_success doesn't work inside for?

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#3264]
Issue can be seen here:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/29792399
Relevant commit can be seen in the repository:
https://github.com/IsraelHikingMap/Site/commit/3028d525a8f81baacc3e49328069194aa486d1d0#diff-180360612c6b8c4ed830919bbb4dd459R50
I have tried to use `build_success` instead of `after_build` to manually run my tests in order to get coverage. so I needed to set `test: off` and so I can't use the `after_test` hook.

**Comment by FeodorFitsner** [comment]
It should be `on_success`, not `build_success`.

**Comment by HarelM** [comment]
Please fix the docs then:
https://www.appveyor.com/docs/build-configuration/

**Comment by FeodorFitsner** [comment]
It's been fixed, thanks for the catch!
