### ISSUE TITLE
path-utils file provision missing from some packer templates

### ISSUE THREAD

**Issue by NotOats** [appveyor/ci#3269]
https://github.com/appveyor/build-images/commit/0a0ea053ecf4351d0747df76dd2da95bd081d72a changed how path-utils.psm1 was provisioned to the vhd but only updated vs2019.json. The remaining packer template files (ws2019.json, minimal-windows-server.json) are still missing the file provision entry and causing vhd builds to fail.

Those template files also seem to be missing cleanup_windows.ps1 as well. Not sure if that's intended or not.

**Comment by FeodorFitsner** [comment]
Sorry about that. We are working on the fix.
