### ISSUE TITLE
GitHub deploy fails on releases with more than 100 assets

### ISSUE THREAD

**Issue by Optiligence** [appveyor/ci#3275]
>Error uploading release asset. Validation Failed: (resource=ReleaseAsset, code=already_exists, field=name)

see https://ci.appveyor.com/project/knossos/knossos/builds/29558610#L2120
if it is re-build it still fails
only after manually removing the asset on GitHub doing a re-build succeeds
https://github.com/knossos-project/knossos/blob/master/.appveyor.yml

**Comment by FeodorFitsner** [comment]
Thanks for reporting that!

Looks like a bug as we check only 100 first assets (1st page) within the release :-/

Going to fix it and deploy an update later this week.
