### ISSUE TITLE
Update Node releases

### ISSUE THREAD

**Issue by guidobouman** [appveyor/ci#3278]
While waiting for #3277 can we gat the node versions updated in the meantime?

Some stale branches for indication:

| Branch | AppVeyor | Current |
|--------|-----------|---------|
| LTS/Dubnium | 10.17.0 | 10.18.1 |
| LTS/Erbium | 12.13.1 | 12.14.1 |
| current | 13.2.0 | 13.6.0 |

Note: 10.18.0 & 12.14.0 are security releases that released last month.

**Comment by FeodorFitsner** [comment]
All Node.js branches have been updated to the latest versions.

**Comment by guidobouman** [comment]
Thanks!
