### ISSUE TITLE
Unexpected token `sudo' under if statement

### ISSUE THREAD

**Issue by q4a** [appveyor/ci#3291]
I'm getting error 
/opt/appveyor/build-agent/bash-shell.sh: eval: line 62: syntax error near unexpected token `sudo'
when using it in Ubuntu under if statement like:
if [%PLATFORM%]==[x86] (
  sudo dpkg --add-architecture i386 && sudo apt-get -qq update && sudo apt-get install -y gcc-multilib
)
Looks like bug.

Here is full log:
https://ci.appveyor.com/project/q4a/xray-16/builds/30175654/job/td9tda91css7yu5i
Here is full appveyor.yml:
https://github.com/q4a/xray-16/blob/b01de268b4c5a47e11696ce6e09e25f36ea77fdc/appveyor.yml

**Comment by Wasapl** [comment]
On Ubuntu images we execute commands in bash and in powershell shells. By default, if there is no prefix `sh` or `ps` given, we execute commands with bash. But in your `appveyor.yml` `if` clause is not written in bash syntax.
Please refer [Bash and Powershell](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#bash-and-powershell) for more details.

**Comment by Wasapl** [comment]
This is how I would write those parts of the yml file:
```
    - if [ "$PLATFORM" = "x86" ]; then
        sudo apt-get install -y libglew-dev libegl1-mesa-dev libgles2-mesa-dev libpugixml-dev libopenal-dev libtbb-dev libcrypto++-dev liblockfile-dev libfreeimage-dev libfreeimageplus-dev &&
        sudo apt-get install -y cmake liblua5.1-0-dev libssl-dev libogg-dev libtheora-dev libvorbis-dev liblzo2-dev libjpeg-dev libncurses5-dev &&
        wget http://launchpadlibrarian.net/297657749/libsdl2-2.0-0_2.0.5+dfsg1-1ubuntu1_amd64.deb &&
        wget http://launchpadlibrarian.net/297657747/libsdl2-dev_2.0.5+dfsg1-1ubuntu1_amd64.deb &&
        sudo dpkg -i *.deb &&
        sudo apt-get -f -y install &&
        CFLAGS="-w" CXXFLAGS="-w" cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION &&
        make -j $core_count package &&
        file openxray_1.6.02_*.deb
      fi

    - if [ "$PLATFORM" = "x86" ]; then
        sudo dpkg --add-architecture i386 && sudo apt-get -qq update && sudo apt-get install -y gcc-multilib g++-8-multilib libpulse-dev:i386 libglib2.0-dev:i386
      fi

**Comment by q4a** [comment]
I tested and got new error:
bash-shell.sh: eval: line 63: syntax error: unexpected end of file
on this file:
https://github.com/q4a/xray-16/blob/6cfb40ce1e5a89096ea5b845dd25a8453e7c53ec/appveyor.yml
here is full log:
https://ci.appveyor.com/project/q4a/xray-16/builds/30204521/job/7h6vj1xadb1b912l

**Comment by Wasapl** [comment]
Lets rewrite it in more formal way:
```
    - sh: |
        if [ "$PLATFORM" = "x86" ]; then
        sudo apt-get install -y libglew-dev libegl1-mesa-dev libgles2-mesa-dev libpugixml-dev libopenal-dev libtbb-dev libcrypto++-dev liblockfile-dev libfreeimage-dev libfreeimageplus-dev &&
        sudo apt-get install -y cmake liblua5.1-0-dev libssl-dev libogg-dev libtheora-dev libvorbis-dev liblzo2-dev libjpeg-dev libncurses5-dev &&
        wget http://launchpadlibrarian.net/297657749/libsdl2-2.0-0_2.0.5+dfsg1-1ubuntu1_amd64.deb &&
        wget http://launchpadlibrarian.net/297657747/libsdl2-dev_2.0.5+dfsg1-1ubuntu1_amd64.deb &&
        sudo dpkg -i *.deb &&
        sudo apt-get -f -y install &&
        CFLAGS="-w" CXXFLAGS="-w" cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION &&
        make -j $core_count package &&
        file openxray_1.6.02_*.deb
        fi

    - sh: |
        if [ "$PLATFORM" = "x86" ]; then
        sudo dpkg --add-architecture i386 && sudo apt-get -qq update && sudo apt-get install -y gcc-multilib g++-8-multilib libpulse-dev:i386 libglib2.0-dev:i386
        fi

**Comment by q4a** [comment]
Thanks, this worked. Please, include more samples with "if - else -fi" for windows and linux (or link to good cmd/bash syntax docs) in appveyor's documentation.
