### ISSUE TITLE
Missing Qt 5.12 alias in documentation

### ISSUE THREAD

**Issue by dalboris** [appveyor/ci#3297]
(Note: already mentionned in #3197, but making a separate issue)

In the Windows build machines, there is currently an alias from C:\Qt\5.12 to C:\Qt\5.12.6. However such alias is not mentionned in https://www.appveyor.com/docs/windows-images-software/#qt.

Could the page https://www.appveyor.com/docs/windows-images-software/#qt  be updated to add the following sentence, like for all other Qt versions?

"C:\Qt\5.12 mapped to C:\Qt\5.12.6 for backward compatibility"

Thank you!

**Comment by FeodorFitsner** [comment]
Done.

**Comment by dalboris** [comment]
Thanks!
