### ISSUE TITLE
Cannot find Qt5 on Visual Studio 2017 build image

### ISSUE THREAD

**Issue by naavis** [appveyor/ci#3302]
Builds that worked 6 months ago are now failing on AppVeyor, when building a C++ program with CMake: https://ci.appveyor.com/project/naavis/haloray/builds/30364800

I was using Qt 5.12.2 which was removed from the AppVeyor VM images with VS2017, but I cannot get the builds to work with any Qt version now. According to this 5.12.6 should be available: https://www.appveyor.com/docs/windows-images-software/#qt

The AppVeyor config file is here: https://github.com/naavis/haloray/blob/fix-qt5-appveyor/appveyor.yml

**Comment by naavis** [comment]
I added the debug line `ls $env:Qt5_DIR` in my build script. It shows the following output: `ls : Cannot find path 'C:\Qt\5.12.2\msvc2017_64\' because it does not exist.`

This seems to indicate that the environment variable `Qt5_DIR` points to Qt 5.12.2, even though I set it to 5.12.6 in the `appveyor.yml` file. Why is that? Is it possible it is somehow using the config from the `master` branch?

**Comment by FeodorFitsner** [comment]
Make sure `Qt5_DIR` variable is not defined on project settings UI (`Environment` tab). Variables defined on UI will override those defined in YAML.

**Comment by naavis** [comment]
Thanks, that was the issue! Seems like I had forgotten to remove those definitions after creating a YAML file for the configs.
