### ISSUE TITLE
Builds with snupkg do not upload them to the configured symbol_server

### ISSUE THREAD

**Issue by GGG-KILLER** [appveyor/ci#3305]
I previously configured [one of my repos](https://github.com/GGG-KILLER/GParse/tree/16f15c77a01721104578f923e82298a64b499a3c) with a appveyor.yml and enabled `.snupkg` creation and uploading as I thought MyGet supported it ([though it seems next month they'll start supporting it](https://myget.uservoice.com/forums/135675-general/suggestions/36274102-support-snupkg-symbol-packages-and-pushing-them-t)).

But to my surprise, it seems that the NuGet Deployment agent still pushes the snupkgs to nuget.org instead of what I had configured as the `symbol_server` in the `appveyor.yml` (I originally thought the issue was that this kind of configuration was not supported through the UI so I added one).

EDIT: [The failed build](https://ci.appveyor.com/project/GGG-KILLER/gparse/builds/30140352#L186)

**Comment by FeodorFitsner** [comment]
Looks like a bug. We'll fix that and deploy updated agent by the end of this week.
