### ISSUE TITLE
Qt 5.12.8

### ISSUE THREAD

**Issue by tsteven4** [appveyor/ci#3306]
Please update the MSVC 2017 and MSVC 2019 images with Qt 5.12.7.
thanks

**Comment by EwoutH** [comment]
Also, Qt 5.14.0 to [Qt 5.14.1](https://www.qt.io/blog/qt-5.14.1-released) please :)

**Comment by tsteven4** [comment]
At this point can we go straight to 5.12.8?

**Comment by FeodorFitsner** [comment]
@tsteven4 Of course!

**Comment by tsteven4** [comment]
At this point can we got straight to 5.12.9?  And can we please have the Visual Studio 2015 and 2107 updates - this is 4 months old now.  We would like to build release code without having to install Qt on the build machine.  thanks

**Comment by FeodorFitsner** [comment]
Sure, added a new issue: https://github.com/appveyor/ci/issues/3470

**Comment by tsteven4** [comment]
@FeodorFitsner are we going to get an update to the Visual Studio 2015 and 2017 versions with Qt 5.12.9?  It's been over 6 months.

**Comment by FeodorFitsner** [comment]
Yes, we are working on that. Thanks for your patience!

**Comment by tsteven4** [comment]
I am still seeing Qt 5.12.6 with the Qt 5.12 link in the VS 2017 image.  Are the VS 2015 and VS 2017 images no longer receiving updates?

**Comment by FeodorFitsner** [comment]
They are, but slower than VS 2019 one.

This is how you can install MinGW package of 5.12.9 during the build:

```posh
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_qt_module.ps1'))
Install-QtComponent -Version '5.12.9' -Name 'win32_mingw73' -ExcludeDocs -ExcludeExamples
ConfigureQtVersion 'C:\Qt' '5.12.9'
```
