### ISSUE TITLE
Azure Service Fabric 7.0 Fourth Refresh

### ISSUE THREAD

**Issue by konradkalita** [appveyor/ci#3309]
Do you have plans to add Azure Service Fabric SDK to VS 2019 image? SDK is available on VS2015 and VS2017.

**Comment by FeodorFitsner** [comment]
Why not? Will include it in the next update.

**Comment by jezzsantos** [comment]
Need this too, please

**Comment by JohnNilsson** [comment]
Any ETA on this?

**Comment by FeodorFitsner** [comment]
Working on that. Should be early next week, thanks for your patience!

**Comment by FeodorFitsner** [comment]
https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-0-fourth-refresh-release/ba-p/1205414
https://github.com/Azure/service-fabric/blob/master/release_notes/Service-Fabric-70CU4-releasenotes.md
