### ISSUE TITLE
*.snupkg Deployments to nuget.org stopped working?

### ISSUE THREAD

**Issue by lordmilko** [appveyor/ci#3315]
The last time I deployed my [project](https://ci.appveyor.com/project/lordmilko/prtgapi) to nuget.org was two months ago (December 9th). I have an Environment setup that specifies "Do not publish symbol packages" (so Appveyor doesn't attempt to upload symbols.nupkg files to smbsrc.net instead of snupkg files to nuget.org) and then an Artifact(s) wildcard that specifies to include both *.nupkg and *.snupkg files.

This solution allowed me to work around the fact Appveyor previously didn't know how to process snupkg files properly, but by instructing Appveyor to just treat them as "regular nupkg files" I was able to publish them to the correct destination (nuget.org)

When I deployed in December, everything worked great

```
Downloading artifact PrtgAPI.0.9.11.nupkg to temporary location...OK
Publishing PrtgAPI.0.9.11.nupkg to https://www.nuget.org/api/v2/package...OK
Downloading artifact PrtgAPI.0.9.11.snupkg to temporary location...OK
Publishing PrtgAPI.0.9.11.snupkg to https://www.nuget.org/api/v2/symbolpackage...OK
Total packages published: 2
```

However when I tried to deploy today, I got an error

```
Downloading artifact PrtgAPI.0.9.12.nupkg to temporary location...OK
Publishing PrtgAPI.0.9.12.nupkg to https://www.nuget.org/api/v2/package...OK
Downloading artifact PrtgAPI.0.9.12.snupkg to temporary location...OK
Publishing PrtgAPI.0.9.12.snupkg to https://nuget.smbsrc.net/api/v2/symbolpackage...
Error publishing package. NuGet server returned 405: Method Not Allowed
```

You can see that for some reason Appveyor is trying to publish the snupkg to smbsrc.net. My understanding previously was this is wrong - nuget.smbsrc.net is for symbols.nupkg files only - hence why I ticked the "don't publish symbols" checkbox, so everything (including symbols) would be pushed to nuget.org

Has the destination snupkg files are "meant" to be published to changed, is this just a bug in Appveyor, or perhaps something else?

**Comment by FeodorFitsner** [comment]
Looks like a bug, thanks for reporting that! Will fix that and deploy an update tomorrow. To workaround, specify `https://www.nuget.org` as symbol server.

**Comment by phatboyg** [comment]
Same issue, subscribed: https://ci.appveyor.com/project/phatboyg/masstransit/build/job/21x8j7q131kn33b6

**Comment by lordmilko** [comment]
Manually pushing my snupkg with

```powershell
dotnet nuget push PrtgAPI.0.9.12.snupkg --source https://www.nuget.org/api/v2/symbolpackage -k <key>
```
worked, confirming `https://www.nuget.org/api/v2/symbolpackage` is still the correct location for snupkg files

**Comment by FeodorFitsner** [comment]
Update with the fix has been deployed - original behaviour restored.
