### ISSUE TITLE
7-Zip 19.00, on Ubuntu too

### ISSUE THREAD

**Issue by SergeGautherie** [appveyor/ci#3316]
Upgrade from 16.02, to match #3145.

--

https://www.7-zip.org/

https://www.7-zip.org/history.txt
`19.00          2019-02-21`

**Comment by Wasapl** [comment]
Unfortunately 7-zip.org does not provide linux binaries (or a way to build them). Instead it encourage to use [p7zip](https://sourceforge.net/projects/p7zip/) in linuxes. But it did not update since 2016.

**Comment by SergeGautherie** [comment]
You're right. Sadly. Sorry.

https://sourceforge.net/projects/p7zip/files/p7zip/
`16.02 | 2016-07-14`
