### ISSUE TITLE
Visual Studio 2019 license expires today

### ISSUE THREAD

**Issue by mauroservienti** [appveyor/ci#3319]
On build agent images Visual Studio 2019 license is going to expire in a few hours.

![image](https://user-images.githubusercontent.com/1325611/74609956-1cdef100-50ef-11ea-92d4-0fa452ef3998.png)

**Comment by FeodorFitsner** [comment]
Update is coming today or early tomorrow.

**Comment by jchoksijudopay** [comment]
Checked today and the license is still expired:

```
Microsoft Visual Studio 2019 Version 16.4.3.
Copyright (C) Microsoft Corp. All rights reserved.
The license for Visual Studio has expired.
The evaluation period for this product has ended.
Command exited with code 1
```

**Comment by FeodorFitsner** [comment]
Updated image has been deployed. Thanks for your patience!
