### ISSUE TITLE
Broken Qt 5.13.2 install on Visual Studio 2019 image (18 February 2020 update)

### ISSUE THREAD

**Issue by keneanung** [appveyor/ci#3322]
When building our project https://github.com/Mudlet/Mudlet with the `Visual Studio 2019` image (18 February 2020 update), we get the error message `Could not find qmake spec 'win32-g++'.` which seems to indicate a broken Qt 5.13.2 installation (which is what we use). See https://ci.appveyor.com/project/Mudlet/mudlet/builds/30900627

Going back to the `Previous Visual Studio 2019` image fixes this (see https://ci.appveyor.com/project/Mudlet/mudlet/builds/30901135).

**Comment by nikolaseu** [comment]
Similar issue with the new image:

```
Warning: Unable to read c:\Users\qt\work\install\mkspecs\qconfig.pri: The system cannot find the path specified.
Unable to find dependent libraries of c:\Users\qt\work\install\bin\Qt5Widgets.dll :Cannot open 'c:/Users/qt/work/install/bin/Qt5Widgets.dll': The system cannot find the path specified.
```

https://ci.appveyor.com/project/nikolaseu/neuvision/builds/30909600

**Comment by FeodorFitsner** [comment]
Looking into that. Thanks for reporting the issue!

**Comment by hluk** [comment]
Same issue with Qt 5.12.6.

Did some diffing of recent logs ([older build without this issue](https://ci.appveyor.com/project/hluk/copyq/builds/30888936/job/uv8aj8fcotoe0rxh) and [newer with this issue](https://ci.appveyor.com/project/hluk/copyq/builds/30917633/job/43gmijoxj6c3veu1)) and found out that some files in Qt installation are missing -- namely in directory `C:\Qt\5.12.6\mingw73_32\bin`, files `qt.conf` and `qtenv2.bat`.

**Comment by FeodorFitsner** [comment]
The image has been fixed. Thanks for your patience!
