### ISSUE TITLE
Visual Studio 2019 is not activated on Previous Visual Studio 2019 image

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3327]
it looks weird why visual studio **community** requires activation.

the workaround for this issue is to connect to build machine using rdp, run Visual Studio, authenticate using Microsoft account. But it is really annoying.

**Comment by FeodorFitsner** [comment]
It is weird, yes. We should look into activating it during unattended installation.

**Comment by VladislavAntonyuk** [comment]
it shows the 30 days trial is expired. probably there are some changes from Microsoft side, which requires authentication

**Comment by FeodorFitsner** [comment]
Yes, the user should sign in to "unlock" Community edition: https://docs.microsoft.com/en-gb/visualstudio/ide/signing-in-to-visual-studio?view=vs-2019 However, looks like there is no way to (easily) automate that during unattended installation with Packer?

**Comment by VladislavAntonyuk** [comment]
https://docs.microsoft.com/en-us/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2019

**Comment by VladislavAntonyuk** [comment]
https://github.com/appveyor/ci/issues/3319
