### ISSUE TITLE
Python 3.8.2

### ISSUE THREAD

**Issue by minrk** [appveyor/ci#3329]
Visual Studio images still have Python 3.8.0 in C:\Python38. There have been two bugfix releases, 3.8.1 and 3.8.2 since then. Mac builds [have 3.8.1 and 3.8.2rc2](https://www.appveyor.com/updates/2020/02/26/) as of yesterday. Python 3.8.2 was released on Feb 24, 3.8.1 on Dec 18.

**Comment by SylvainCorlay** [comment]
Thanks!

It would also be greatly appreciated the base appveyor image included `Miniconda38` and `Miniconda38-x64` alongside the other versions.
