### ISSUE TITLE
SSH block does not work on MacOS image

### ISSUE THREAD

**Issue by jacobq** [appveyor/ci#3330]
From [the docs](https://www.appveyor.com/docs/how-to/ssh-to-build-worker/):
> If you need to investigate worker on build finish, add export APPVEYOR_SSH_BLOCK=true to display SSH connection details and pause the build until a special “lock” file on VM user home directory is deleted:

```
on_finish:
  - sh: export APPVEYOR_SSH_BLOCK=true
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
```

However, this results in an error on the Mac platform (tried the current `macos` image).
```
...
Running "on_failure" scripts
export APPVEYOR_SSH_BLOCK=true
curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
sudo: ufw: command not found
sudo: ufw: command not found
Command exited with code 1
Build failed
```

> Please provide a repro. Ideally, AppVeyor build of public repository. Provide build configuration in YAML format. If repro does not fit into single build scenario, please provide step-by-step instructions.

TODO: @jacobq to add public repro

**Comment by Wasapl** [comment]
We have updated `enable-ssh.sh` script to make it work for both ubuntu and macos.
Please test it on your side.

**Comment by jacobq** [comment]
> We have updated `enable-ssh.sh` script to make it work for both ubuntu and macos.
> Please test it on your side.

Appears to work now; thanks!
