### ISSUE TITLE
Python stack: pip install is not working on macos image

### ISSUE THREAD

**Issue by mayeut** [appveyor/ci#3331]
Now that #3213 has been resolved, builds are going a bit further but fails on `pip intall`
c.f. https://ci.appveyor.com/project/joerick/cibuildwheel/builds/31131688/job/cvs0qm8akakwgsxq
built from https://github.com/joerick/cibuildwheel/pull/230

**Comment by FeodorFitsner** [comment]
Have you tried the suggestion from here: https://github.com/pypa/pip/issues/5448?

**Comment by mayeut** [comment]
@FeodorFitsner, the workaround proposed is for certificate issue.
In the logs of the failing build, we can see that the SSL module is not available, probably because it failed to build.

**Comment by Wasapl** [comment]
It should be fixes now. Could you please test it from your side?

**Comment by mayeut** [comment]
Working fine now, thanks !
