### ISSUE TITLE
i686-8.1.0-posix-dwarf-rt_v6-rev0

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3334]

**Comment by culler** [comment]
Thank you, Feodor.  This will be very helpful for building Python extension modules for Windows.  The x86 version of Python is still very heavily used, for some reason, and the i686 toolchain is needed to build extensions for it with mingw.  This release of the toolchain adds compatibility with the Universal CRT, which greatly simplifies deployment.
