### ISSUE TITLE
Install Qt 5.5 add-on modules

### ISSUE THREAD

**Issue by jakepetroules** [appveyor/ci#334]
In Qt 5.5 we deprecated a bunch of modules (including QtScript, which I need for my AppVeyor build job). Could you please ensure the Qt 5.5 add-on modules are installed as well?

**Comment by TheOneRing** [comment]
I would need that module too

**Comment by FeodorFitsner** [comment]
These components have been already added to "Pro" and "OSS" environments:

Qt 5.5 add-on modules:

* Qt Quick Controls
* Qt Location
* Qt Script
* Qt3D
* Qt WebEngine
* Qt Quick 1
* Qt Canvas 3D

Azure update is coming
