### ISSUE TITLE
Inno Setup 6.0.4

### ISSUE THREAD

**Issue by dingpengyu** [appveyor/ci#3350]
hi appveyor team
inno setup 6.0.4 has been released, the following is the specific update log.[inno setup6.0.4 changes](https://jrsoftware.org/files/is6-whatsnew.htm)
It is recommended to update the mirrored version of appveyor's inno setup to the latest version.
thanks

**Comment by FeodorFitsner** [comment]
my concern is downloaded `innosetup-6.0.4.exe` is getting blocked by antivirus.

**Comment by FeodorFitsner** [comment]
Interesting that for Chocolatey package the executable is embedded into the package, but it has a different SHA from the one on original site: https://chocolatey.org/packages/InnoSetup#files

**Comment by dingpengyu** [comment]
> Interesting that for Chocolatey package the executable is embedded into the package, but it has a different SHA from the one on original site: https://chocolatey.org/packages/InnoSetup#files
It may be that chocolatey re-uploaded inno setup6.0.4.

**Comment by FeodorFitsner** [comment]
OK, I've asked for clarification on InnoSetup forums: https://groups.google.com/forum/#!topic/innosetup/YWB3IS-kFd8

**Comment by dingpengyu** [comment]
> OK, I've asked for clarification on InnoSetup forums: https://groups.google.com/forum/#!topic/innosetup/YWB3IS-kFd8

hello FeodorFitsner
Thanks for your work

**Comment by dingpengyu** [comment]
I will close this issue
Because the Visual Studio 2019 image was updated on January 16, 2021 it already integrates with inno setup 6.1.2.
thanks
