### ISSUE TITLE
JDK 14

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3352]

**Comment by fabdouglas** [comment]
The documentation sates JDK 14 is available for VS 2019: https://www.appveyor.com/docs/windows-images-software/#java

However, the related `C:\Program Files\Java\jdk14` does not exist.

![image](https://user-images.githubusercontent.com/579170/78502440-7ebbee80-7761-11ea-8d71-b27509fc017d.png)

**Comment by FeodorFitsner** [comment]
It's currently on `Visual Studio 2019` image only.

**Comment by fabdouglas** [comment]
The previous "DIR" screenshot is based on a `Visual Studio 2019` image as configured in the settings of the project.
![image](https://user-images.githubusercontent.com/579170/78508131-ca33c400-7784-11ea-937e-a415e79247ce.png)

However, I may have missed something: when I display the environment variables, I get this:
![image](https://user-images.githubusercontent.com/579170/78508179-2b5b9780-7785-11ea-98f3-1d1397e94930.png)

And yet, I have no environment configuration in my [appveyor.yml](/ligoj/plugin-iam-node/blob/master/appveyor.yml), and its last [build](https://ci.appveyor.com/project/ligoj/plugin-iam-node)

**Comment by FeodorFitsner** [comment]
If there is `appveyor.yml` then UI settings will be ignored (except environment variables). Either add `image: Visual Studio 2019` to `appveyor.yml` or define `APPVEYOR_BUILD_WORKER_IMAGE` environment variable on Environment tab of project settings.

**Comment by fabdouglas** [comment]
Adding `image: Visual Studio 2019` to my `appveyor.yml`solved my JDK14 issue.
