### ISSUE TITLE
Visual Studio 2019 version 16.6 Preview 1

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3357]
Visual Studio 2019 Preview has VS 2019 16.4 preview
Visual Studio 2019 has VS 2019 16.5

Please update Preview version

**Comment by FeodorFitsner** [comment]
Release notes: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.6.0-pre.1.0

**Comment by FeodorFitsner** [comment]
`Visual Studio 2019 Preview` image has been updated with Visual Studio 2019 version 16.6 Preview 1
