### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by borg323** [appveyor/ci#3364]
We started hitting this limit. Here is an example: https://ci.appveyor.com/project/LeelaChessZero/lc0/builds/31768901
We tried to delete a few old PR builds to clear up some space, however this doesn't seem to have helped.

**Comment by FeodorFitsner** [comment]
The storage size has been extended.

**Comment by borg323** [comment]
Seems we reached the new limit again. Is there a way to clean up some old artifactls?
