### ISSUE TITLE
Xcode 11.4

### ISSUE THREAD

**Issue by cgutman** [appveyor/ci#3365]
Xcode 11.4 was released March 24th. It includes (among other things) some interesting new keyboard and mouse APIs for iOS/tvOS 13.4 which I have begun using. Unfortunately, this prevents me from building on AppVeyor since the latest included version of Xcode (11.3.1) on the image doesn't include the new APIs.

It would be great if you could include Xcode 11.4 in your next macOS image update. It's probably already on your radar, but I figured I'd create a ticket for it to be sure.

**Comment by VladislavAntonyuk** [comment]
https://github.com/appveyor/ci/issues/3419
