### ISSUE TITLE
Is it possible that the tests pass but the build fails?

### ISSUE THREAD

**Issue by OrkoHunter** [appveyor/ci#337]
I've faced a strange problem recently. The tests I've written passes over the ci, but the build fails and it says `Command exited with exit status 1`.

Here is the log for the build - https://ci.appveyor.com/project/chebee7i/networkx-metis-1lf0f/build/1.0.33/job/30g29dksvsoirbec

What is going wrong over there?

**Comment by FeodorFitsner** [comment]
Looks like it's `popd` command existing with 1 code, not tests.

**Comment by OrkoHunter** [comment]
Yes! I thought we could use `pushd` and `popd` on windows as well.
