### ISSUE TITLE
Visual Studio 2019 version 16.5.2

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#3372]
Current Visual Studio 2019 on appveyor is version 16.5.0 that has some build issue with WDM.
https://developercommunity.visualstudio.com/content/problem/926865/wdmh-internal-compiler-error-with-code-analysis.html

Would it be possible to upgrade to 16.5.2 ?
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.5.2

**Comment by FeodorFitsner** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/3379
