### ISSUE TITLE
Build fails fetching Gradle with no error message

### ISSUE THREAD

**Issue by HariSekhon** [appveyor/ci#3375]
Repost from https://help.appveyor.com/discussions/problems/26756-build-fails-fetching-gradle-with-no-error-message as my email replies and posts are not long arriving there

=========================

Hi,

I've got a build which always fails at this step, but it succeeds on all other CI systems and when run manually. There is no error in the AppVeyor log to explain why this build only fails in AppVeyor, the end output is:

```
./gradlew clean install uploadArchives
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Downloading https://services.gradle.org/distributions/gradle-5.6.3-bin.zip
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

The build can be found here:

https://ci.appveyor.com/project/HariSekhon/lib-java/branch/master

This seems to be an issue specific to AppVeyor.

Any help would be appreciated.

Cheers

Hari

**Comment by HariSekhon** [comment]
Another one of my gradle builds fails in exactly the same way, but only on AppVeyor:

https://ci.appveyor.com/project/HariSekhon/Nagios-Plugin-Kafka/bran...

Log:

https://ci.appveyor.com/api/buildjobs/5a0iilfpj22ch6vw/log

**Comment by HariSekhon** [comment]
The dots are default download progress dots, standard Gradle output when it's
pulling the right version of Gradle to build the project with.

**Comment by HariSekhon** [comment]
So it looks stuck downloading the file, every time, but this is not the case in any of my other CI systems builds for this repo, which are pulling the exact same version of Gradle defined in the build wrapper code, implying that it is not an upstream issue but something AppVeyor specific.

I don't know if this is an issue with some AppVeyor specific timeout, but my other non-grade builds take longer than this and Gradle doesn't fail to download in other CI systems or when run locally.

The progress dots are usually there to ensure that systems like this know that there is an ongoing operation occurring and the build hasn't become stuck ie. to not time out a command because it is still outputting messages.

Is it possible that AppVeyor is not registering the progress output to keep alive due to it all being on one line?

**Comment by FeodorFitsner** [comment]
Thanks for reporting that! We've got a short and nice repro and are looking into fixing that.

**Comment by FeodorFitsner** [comment]
We deployed a new image with updated build agent and got a better behavior (per my testing it fails like 2 of 10). I'm still leaving this issue open as we continue investigation.

**Comment by FeodorFitsner** [comment]
Just to let you know we are still working on that. The version of Build Agent we have now internally shows pretty stable results. Must be released this week.

**Comment by HariSekhon** [comment]
Thanks for letting me know, eager to see these JVM builds go green!

**Comment by FeodorFitsner** [comment]
The issue has been fixed: https://ci.appveyor.com/project/FeodorFitsner/lib-java/builds/32764392?fullLog=true#L42
