### ISSUE TITLE
Perl on Visual Studio 2019 image

### ISSUE THREAD

**Issue by d1vanov** [appveyor/ci#3377]
Hello, as I can see [here](https://www.appveyor.com/docs/windows-images-software/#perl), there's currently no perl installation in Visual Studio 2019 image. Are there any plans to add perl to this image?

**Comment by SergeGautherie** [comment]
The website page seems to need an update:
```
perl -v
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi
Copyright 1987-2018, Larry Wall
```

--

Nonetheless,
http://strawberryperl.com/
has
strawberry-perl-5.30.2.1-64bit.msi

Time to update?

**Comment by SergeGautherie** [comment]
'Visual Studio 2019 image update on April 19, 2020' added Strawberry.

Yet, result seems a bit odd:
Strawberry is in `PATH`, but after Git, so that is either useless or mixed up.

```
where perl
C:\Program Files\Git\usr\bin\perl.exe
C:\Strawberry\perl\bin\perl.exe

which perl
/usr/bin/perl

perl -v
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi

PATH=...;C:\Program Files\Git\cmd;...;C:\Program Files\Git\usr\bin;...;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;...
```

I assume: Git may use its own perl if need be, but user should use Strawberry only/by_default.

**Comment by FeodorFitsner** [comment]
I'm still unsure what would be the best course of action here... should be move Strawberry's path in front of Git's (break something else?) or remove Strawberry's path altogether as it's as you noted is hid by Git's anyway? Thoughts?

**Comment by SergeGautherie** [comment]
This issue reminds me of #3193, somewhat.

I assume `C:\Program Files\Git\cmd` is enough as default.
Does removing `C:\Program Files\Git\usr\bin` break something?

**Comment by FeodorFitsner** [comment]
Yes, removing `C:\Program Files\Git\usr\bin` breaks everything 💥 as it contains `ssh.exe` required to fetch private repos.

**Comment by craftwar** [comment]
How about using Windows built-in ssh.exe?
%SYSTEMROOT%\System32\OpenSSH\

**Comment by SergeGautherie** [comment]
> removing `C:\Program Files\Git\usr\bin` breaks everything

Well, as I am reporting since #3147, it seems to me that having this path is repeatedly breaking things.
While probably "easy", it seems odd to me to depend on a software (i.e. Git) to ("silently") provide additional utilities.
See #3387 about the same kind of `PATH` issue.

Why not either explicitly install separate softwares or copy (only) the needed ones to a new separate path?
We are at least talking about: bash (...), perl (Strawberry Perl!), ssh (OpenSSH?), ...
