### ISSUE TITLE
$artifacts variable is not propagated on Windows images

### ISSUE THREAD

**Issue by WallyCZ** [appveyor/ci#3380]
I have this testing yaml:

```
version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu1604
- macOS
build_script:
- pwsh: |-

    Write-Host "Hello" > testfile
artifacts:
- path: /*
deploy_script:
  - pwsh: |-
 
      $artifacts

      foreach ($artifactName in $artifacts.keys)
      {
          Write-Host $artifacts[$artifactName].path
      }
```

Output on Visual Studio 2017 image (not working):

```
...
Write-Host "Hello" > testfile
Hello
Discovering tests...OK
Collecting artifacts...
Found artifact 'testfile' matching '*' path
Uploading artifacts...
[1/1] testfile (5 bytes)...100%
$artifacts
foreach ($artifactName in $artifacts.keys)
{
    Write-Host $artifacts[$artifactName].path
}
Build success
```

Output on macOS (on Ubuntu1604 it is similar - everything OK):

```
...
Running "build_script" scripts
Write-Host "Hello" > testfile
Hello
Running "test" phase
Collecting artifacts...
Found artifact 'testfile' matching '*' path
Uploading artifacts...
[1/1] testfile (5 bytes)...100%
Running "deploy_script" scripts
$artifacts
foreach ($artifactName in $artifacts.keys)
{
    Write-Host $artifacts[$artifactName].path
}
Name                           Value
----                           -----
8606db91-d04b-4671-8236-aab1b… {path, customUrl, sourcePath, name…}
/Users/appveyor/projects/testproject/testfile
Build completed
```

**Comment by WallyCZ** [comment]
Update: It does not work even on Visual Studio 2019 and Visual Studio 2015 images

**Comment by FeodorFitsner** [comment]
That's right, `$artifacts` variable is currently not injected into PowerShell Core context. Though you may export it from PowerShell to a json and then import in PS Core.

**Comment by WallyCZ** [comment]
I am not PS specialist, so sorry for maybe dump question, but is there any technical reason, that it can't work in PS Core? And why on Linux/macOS images $artifacts are injected even in PS Core? They have different scripts or it is because of different environment?

**Comment by FeodorFitsner** [comment]
On Linux/macOS there is a newer Build Agent re-written in .NET Core which works differently. The new agent is not yet ready for full roll-out to Windows images though.

**Comment by WallyCZ** [comment]
Thank you, now it's clear. I make some workaround until re-written agent will be also on Windows images.

**Comment by FeodorFitsner** [comment]
Cool, thanks!
