### ISSUE TITLE
There was an error while trying to complete the current operation. Please contact AppVeyor support.

### ISSUE THREAD

**Issue by KermitThefrog13** [appveyor/ci#3381]
help what is this i was trying to create a new project and this popup?

**Comment by FeodorFitsner** [comment]
Your account should be unlocked now.

**Comment by SoninnM** [comment]
> Your account should be unlocked now.

I also have this problem.how to unlock my account? I sign up for free.

**Comment by FeodorFitsner** [comment]
@SoninnM What is your AppVeyor account name?

**Comment by sahgilbert** [comment]
@FeodorFitsner I have the same problem, having just signed up for a free account.

My AppVeyor account name is inspirecodeorg

Please can you enable my account?

Thanks

**Comment by FeodorFitsner** [comment]
@sahgilbert should be good now.

**Comment by Aliaksandr-Zuyeuski** [comment]
@FeodorFitsner I have a similar problem. Just registered. Please tell me what can be done about it. Thanks.

**Comment by FeodorFitsner** [comment]
@Aliaksandr-Zuyeuski should be enabled now.

**Comment by Aliaksandr-Zuyeuski** [comment]
> @Aliaksandr-Zuyeuskiдолжен быть включен сейчас.

Thank you. Everything is working now.

**Comment by EvgeniiaSanochkina** [comment]
@FeodorFitsner Hello. I got the error "Build not found or access denied". Can you help please?

**Comment by agrawalp99** [comment]
@FeodorFitsner  Can u enable account agrawal99

**Comment by Chuzhoi** [comment]
@FeodorFitsner При попытке сделать сборку выдаёт ошибку There was an error while trying to complete the current operation. Please contact AppVeyor support. Помогите пожалуйста.

**Comment by FeodorFitsner** [comment]
@Chuzhoi should be fixed now.

**Comment by NotCodinNoroi** [comment]
I too suffer from this problem, my username is NotCodinNoroi, can you fix it?

**Comment by NotCodinNoroi** [comment]
@FeodorFitsner I too suffer from this problem, my username is NotCodinNoroi, can you fix it?

**Comment by FeodorFitsner** [comment]
@NotCodinNoroi should be fixed now.

**Comment by murqq** [comment]
@FeodorFitsner just registered. I have a similar problem "There was an error while trying to complete the current operation. Please contact AppVeyor support". I have several hits with support. Username @murmeownqq. Can you help me? 
<img width="1038" alt="Снимок экрана 2023-07-25 в 21 13 49" src="https://github.com/appveyor/ci/assets/130483177/fc5269cc-c053-47e3-8d5e-7dc8d1f47c10">

**Comment by Gameunkulus** [comment]
Hello, can you please help with Error? I' trying to press on New Build and then there comes message
![Screenshot_49](https://github.com/appveyor/ci/assets/100800324/2cdb8078-0b1f-42ea-885b-635eddd4903b)

**Comment by FeodorFitsner** [comment]
@murqq, @Gameunkulus Fixed.

**Comment by DimensionDruid** [comment]
@FeodorFitsner I have a similar problem. Just registered. Please tell me what can be done about it. Thanks. And also its not possible to delete old projects

**Comment by dousmartin** [comment]
Hello, can you please help with Error? I' trying to press on New Build and then there comes message
![Снимок экрана 2023-08-02 в 20 30 06](https://github.com/appveyor/ci/assets/138994531/0fdffe51-fbeb-45b3-8159-f05321bf84d8)

**Comment by FeodorFitsner** [comment]
@dousmartin fixed.

**Comment by szechnaya** [comment]
@FeodorFitsner

please help with same issue

name=LycoRevId

thanks

**Comment by FeodorFitsner** [comment]
@szechnaya done!

**Comment by BLKSerene** [comment]
@FeodorFitsner Hi, I have the same problem. My username is BLKSerene. Can you help me?

**Comment by szechnaya** [comment]
@FeodorFitsner

I still get that notification.

LycoRevId

my email redm---d@gmail.com

**Comment by FeodorFitsner** [comment]
@szechnaya Fixed?

**Comment by marskzj** [comment]
@FeodorFitsner   Hi, I have the same problem. My username is asdDaD. Can you help me?

**Comment by natalikazakova87** [comment]
При попытке сделать сборку выдаёт ошибку There was an error while trying to complete the current operation. Please contact AppVeyor support. Помогите пожалуйста. 
![Снимок](https://github.com/appveyor/ci/assets/132995732/f3d47e6c-5f23-426a-962a-fa470bff3265)

**Comment by soterekhova** [comment]
@FeodorFitsner Hello
I have the same problem - getting the above error when trying to build project, encrypt YAML or even delete the project.

Registered a new account just today: sofia.terekhova@gmail.com

Thanks in advance

**Comment by system12333333** [comment]
please help with same issue

name=system12333333

thanks

**Comment by BLKSerene** [comment]
@FeodorFitsner Hi, could you please help me? I'm always having this problem, whatever the operation. Thank you.

**Comment by gnunez-net-com-uy** [comment]
@FeodorFitsner Hi, I have the same problem.
My username is: gnunez-net-com-uy
Email: enc@gnunez.net.com.uy
Can you help me?

**Comment by Anna-Belyaeva** [comment]
@FeodorFitsner Добрый день, у меня такая же проблема, помогите, пожалуйста, моё имя Anna-Belyaeva
![1](https://github.com/appveyor/ci/assets/105930064/cec78f8e-1a80-4829-95d2-250fe775bb83)

**Comment by gluk2309** [comment]
Добрый день, точно такая же проблема, помогите пожалуйста.
имя пользователя : gluk2309
 почта : gluk2309@mail.ru
![Problem](https://github.com/appveyor/ci/assets/129311843/15a9c20f-d97f-4f59-8b99-4f8066a280fe)

**Comment by gluk2309** [comment]
> @FeodorFitsnerДобрый день, у меня такая же проблема, помогите, пожалуйста, мое имя Анна-Беляева ![1](https://user-images.githubusercontent.com/105930064/265965249-cec78f8e-1a80-4829-95d2-250fe775bb83.png)

Решили  проблему?

**Comment by Apach11** [comment]
## Apach11
  Здравствуйте, у меня такая же проблема помогите пожалуйста.
![image](https://github.com/appveyor/ci/assets/137404803/b6a63582-aa58-46e4-b52a-39b2287ae9cb)

**Comment by gluk2309** [comment]
Добрый день, точно такая же проблема, помогите пожалуйста.
имя пользователя : 
Gluk230927468
почта : [gluk2309@gmail.com](mailto:gluk2309@gmail.com)
![Screenshot_9](https://github.com/appveyor/ci/assets/129311843/f23912fe-fc4e-4517-b178-e48531c61105)
Помогите пожалуйста

# Help me please

**Comment by CryptoGazer** [comment]
Hey! I also have the same problem! My username: Pavel Ciugunov; email: chugunov.py@gmail.com

**Comment by tominagaf** [comment]
Same problem here

**Comment by tominagaf** [comment]
Hi, same problem here, could you please unlock my account? 
Usename: Fernando67526

**Comment by Alligator-1** [comment]
@FeodorFitsner Hi, I have the same problem
account email: alligator.ak@gmail.com

**Comment by S-tokarev** [comment]
hi. Can you help me? thx id: deluxprofi
![image](https://github.com/appveyor/ci/assets/136193148/9ca01a12-8502-4b92-b1ea-d8b2772284e6)

**Comment by dannyysy** [comment]
i have the same problem, account name is dannyysy

**Comment by fbermudez231** [comment]
Hello, I haven't been able to use appveyor since I imported some projects I was trying to work. Is my account locked? This is my username fbermudez

**Comment by holgeralbert** [comment]
Hello, I created an account recently and can't use AppVeyor with the same error message as above. Can you look into this for me, please? Account: holgeralbert

**Comment by FeodorFitsner** [comment]
@holgeralbert should be good now

**Comment by holgeralbert** [comment]
Thank you for your assistance.

**Comment by rahulpurohitcore** [comment]
@FeodorFitsner  Hey Please unlock my account as well. Username: Rahul19159

Thanks

**Comment by delhidenny** [comment]
I am unable to do anything on the AppVeyor account as it keeps giving me the error "There was an error while trying to complete the current operation. Please contact AppVeyor support.".

can you please help?

![image](https://github.com/appveyor/ci/assets/19587539/9d9ab5d2-bba0-45d2-a340-029ed14ede70)


username: delhidenny

Thanks

**Comment by DaniilZhiborkin** [comment]
![Безымянный](https://github.com/appveyor/ci/assets/171682567/8c301e9b-45bc-415e-bd7e-037249ff68cd)
Hello! could you please  help with this issue?
Appveyor account name DaniilZhiborkin

Thanks

**Comment by GadgetHack** [comment]
Hi, could you please unlocked my account. My username is Gadget-Hack

**Comment by fa1seut0pia** [comment]
Hey, My Hero @FeodorFitsner , Please unlock my account as well. Username: fa1seut0pia

Thanks

**Comment by Oogway-the-turtle** [comment]
Hello, can you help me @FeodorFitsner 
There was an error while trying to complete the current operation. Please contact AppVeyor support.
My username: Oogway-the-turtle

**Comment by linhntx** [comment]
Hello, could you help me to unlock my account @FeodorFitsner 
my username: linhnt
my email: linhnguyentruong227@gmail.com

**Comment by Wanna-Pizza** [comment]
![image](https://github.com/user-attachments/assets/e5808b14-9857-4350-891d-3faba852e64d)
Hello, can you help me @FeodorFitsner
