### ISSUE TITLE
Qt 5.14.2 on VS 2019 image

### ISSUE THREAD

**Issue by erikboto** [appveyor/ci#3395]
While the Qt 5.14.1 release is not very old, it unfortunately contained a regression on MSVC in that zlib was missing. See https://bugreports.qt.io/browse/QTBUG-81724.

This is fixed in 5.14.2, and since Qt 5.14 came with some nice improvements in BLE support on Windows it would be awesome to get it available in AppVeyor.

**Comment by craftwar** [comment]
I got mail about Visual Studio 2019 image update on April 25, 2020
But I still get old QT, it's not updated.
https://ci.appveyor.com/project/craftwar_appveyor/ci-test/builds/32447467

**Comment by FeodorFitsner** [comment]
Thanks for letting know! We are looking into that.

**Comment by FeodorFitsner** [comment]
Fixed!
