### ISSUE TITLE
Maximum allowed artifact storage size of 75000 Mb will be exceeded.

### ISSUE THREAD

**Issue by borg323** [appveyor/ci#3410]
Seems we reached the new limit again, e.g. <https://ci.appveyor.com/project/LeelaChessZero/lc0/build/job/9e4vvpk6l9y1vhrv>.
Is there a way to clean up some old artifactls?

**Comment by FeodorFitsner** [comment]
The fix is on the way!

In the meantime, I've bumped the quota for your account.
