### ISSUE TITLE
"Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by julianxhokaxhiu** [appveyor/ci#3417]
Hi there,

I've reached this error message but I'm not sure how can I solve it. Searching through the issues here it seems only you can. Can you help in getting this fixed?

I usually try to cleanup all the builds done until now, I only leave the tags ( which are not much ). If it's needed I can clear them up.

This is the AppVeyor job where I'm hitting this: https://ci.appveyor.com/project/julianxhokaxhiu/ffnx/

Repo: https://github.com/julianxhokaxhiu/FFNx

Thank you in advance!

**Comment by julianxhokaxhiu** [comment]
I did cleanup all my projects history artifacts and the message does still come up. See https://ci.appveyor.com/project/julianxhokaxhiu/ffnx/builds/32699349

Not sure anymore what to do.

**Comment by FeodorFitsner** [comment]
It should be fine now. Thank you!

**Comment by julianxhokaxhiu** [comment]
Can confirm that it works like a charm! Thank you :D
