### ISSUE TITLE
Windows Server 2019 image missing PostgreSQL 12

### ISSUE THREAD

**Issue by k-rus** [appveyor/ci#3418]
I use image `Windows Server 2019` and service `postgresql12` both in GUI and `appveyor.yml` and I get the following error in a [build](https://ci.appveyor.com/project/timescale/timescaledb/builds/32708015):
```
Starting PostgreSQL 12
6Start-Service : Cannot find any service with service name 'postgresql-x64-12'.
7At line:1 char:1
8+ Start-Service 'postgresql-x64-12'
9+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10    + CategoryInfo          : ObjectNotFound: (postgresql-x64-12:String) [Start-Service], ServiceCommandException
11    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StartServiceCommand
```

The relevant part in `appveyor.yml`:
```yml
image: Windows Server 2019
services:
  - postgresql12
  - docker
```

Can you also check if PostgreSQL 11 is also missing in Windows Server 2019 image?

**Comment by FeodorFitsner** [comment]
`Windows Server 2019` image does not have PGSQL. It contains bare minimum + Docker.

Use `Visual Studio 2019` image instead which has PGSQL 9, 10, 11 and 12 (https://www.appveyor.com/docs/windows-images-software/#databases).

**Comment by k-rus** [comment]
@FeodorFitsner Thank you for the reply! I am new AppVeyor and I was confused since another [our build](https://ci.appveyor.com/project/timescale/timescaledb/builds/32741644) uses Windows Server 2019 image with PG 10, thus I was assuming other PG in there too.

I will switch to use Visual Studio 2019, which I am already experimenting with.
