### ISSUE TITLE
XCode 11.4.1 for macOS

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3419]
current version is 11.3.1

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner if possible, please install the latest XCode (11.5 at the moment of writing)

**Comment by FeodorFitsner** [comment]
Yep, I've got a different issue for that: https://github.com/appveyor/ci/issues/3463

The idea was having 11.4.1 and 11.5 side-by-side on the same image. I'm reverting this issue back to 11.4.1.
