### ISSUE TITLE
v141 toolset for ARM and ARM64 on Visual Studio 2019 image

### ISSUE THREAD

**Issue by barnson** [appveyor/ci#3421]
To build native libraries for VS2015, VS2017, and VS2019, you need to use VS2019 and install the downlevel platform toolsets. The VS2019 image includes the v140, v141, and v142 toolsets for x86 and x64. However, it includes only v142 toolsets for ARM and ARM64. Please include the v141 toolsets for ARM and ARM64 as well. (There are no v140 toolsets for ARM/ARM64.)

The Visual Studio Installer components are:

- MSVC v141 - VS2017 C++ ARM build tools (v14.16)
- MSVC v141 - VS2017 C++ ARM64 build tools (v14.16)

**Comment by barnson** [comment]
Thanks!

**Comment by EwoutH** [comment]
Thanks, great addition!
