### ISSUE TITLE
[ Github Deployment ] Allow move of one tag from commit to commit

### ISSUE THREAD

**Issue by julianxhokaxhiu** [appveyor/ci#3432]
Hi,

I'm not sure if someone else did ask for this feature already, or if it's covered by your environment, although I did my best searching here in the issue list, in your documentation as well as around the net and I crossed nothing.

My current issue is that in one of my proejcts I do have the need to move a "continuous" build tag ( named `canary` ) always to the latest commit. This would help in making sure that the canary figures out always on top of the latest release.

I know I could handle this by hand in my own codebase, but I was more looking into an automated one that could work also when I merge PRs for example.

I do not have currently a proposal for a solution on how this should look like in the YML manifest but I'm open to anything that makes sense.

Thank you in advance,
Julian

**Comment by FeodorFitsner** [comment]
There is no built-in functionality for that, sorry.

**Comment by julianxhokaxhiu** [comment]
Bummer. Can this be implemented somehow or one day? It would be great.

Thank you in advance.
