### ISSUE TITLE
MSYS2 won't update

### ISSUE THREAD

**Issue by loganmc10** [appveyor/ci#3439]
Trying to build this project:

https://ci.appveyor.com/project/loganmc10/m64p
```
error: could not open file /var/cache/pacman/pkg/msys2-runtime-3.1.4-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/msys2-runtime-devel-3.1.4-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
Command exited with code 1
```
See related issue with MSYS2 here:
https://github.com/msys2/MSYS2-packages/issues/1962

Sounds like installing MSYS2 using the latest nightly installer instead of the latest stable build fixes the issue

**Comment by mati865** [comment]
As workaround upgrade pacman first:
```
pacman -Sy pacman
pacman -Su
```

**Comment by jeroen** [comment]
This no longer works either because pacman is now also a zst so it cannot update itself.

The only solution is for appveyor to update to the latest msys2 on their build image.
