### ISSUE TITLE
"Log is empty" timeouts

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#345]
This has happened twice in the last day - ref https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.7356/job/ab7sav4ibga11wth and https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.7410/job/8cfoqqcutwv5947x

**Comment by FeodorFitsner** [comment]
Most probably connection has lost between build worker and AppVeyor.

**Comment by tkelman** [comment]
Did you do something that cancelled every build from 7411 on?

**Comment by FeodorFitsner** [comment]
Yes, sorry for that. There were issues with Redis cache on our side and those builds were stuck already.

**Comment by tkelman** [comment]
Will reopen if it happens again.
