### ISSUE TITLE
Could not load file or assembly 'DotNet.Glob' error while collecting artifacts

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3453]
Original report: https://help.appveyor.com/discussions/problems/27406-macos-build-could-not-load-file-or-assembly-dotnetglob

**Comment by lockie** [comment]
I've been hit with a problem with similar error message, here's the [log](https://ci.appveyor.com/api/buildjobs/f47it20kxbqbk4og/log). Here's the [appveyor.yml](https://gitlab.com/lockie/darkness-looming-the-dawn/-/raw/master/.appveyor.yml). Mind lending me a hand with this one?

**Comment by FeodorFitsner** [comment]
I can't reproduce it with a test build on `macos` and `macos-mojave` images. It could be something happening during the build is affecting .NET Core, I'm not sure... If you could narrow down what minimal steps from your build cause the error that would be helpful.
