### ISSUE TITLE
docker-compose fails with client version is too old 

### ISSUE THREAD

**Issue by mauroservienti** [appveyor/ci#3454]
I'm trying to use `docker-compose` in one of my builds to set up the tests environment and it fails because of the following error:

![image](https://user-images.githubusercontent.com/1325611/83172685-3e04a400-a118-11ea-97ec-f031ed88990e.png)

I'm using Visual Studio 2019 build image.

- build project: https://ci.appveyor.com/project/mauroservienti/nservicebus-integrationtesting
- GitHub repo failing PR: https://github.com/mauroservienti/NServiceBus.IntegrationTesting/pull/37

Might be related to https://github.com/appveyor/ci/issues/3443

**Comment by FeodorFitsner** [comment]
Try switching Docker to Linux mode before calling your build script:

```
build:
- docker-switch-linux
- cmd: ./build.cmd
```

**Comment by mauroservienti** [comment]
Worked perfectly thanks. The only downside is that the build takes way much longer. I’ll see if I can move it entirely to Linux

**Comment by FeodorFitsner** [comment]
Of course, it takes time to spin off "MobyLinuxVM" Hyper-V VM.
