### ISSUE TITLE
Qt 5.15.0

### ISSUE THREAD

**Issue by patrickelectric** [appveyor/ci#3456]
https://www.qt.io/blog/qt-5.15-released

**Comment by habersaa** [comment]
Hello !
Do you know when the Windows images (VS2019) will be updated to Qt 5.15 ?
We have some work in hold, waiting to be validated by the CI and requiring the new features of Qt 5.15 (e.g. new frame-less custom QML windows).
Thanks & Best regards !

**Comment by patrickelectric** [comment]
Thanks @FeodorFitsner !

**Comment by nschimme** [comment]
@FeodorFitsner FYI, this script does not work with Qt 5.15.0 and complains about a bad path.

https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_qt_module.ps1

**Comment by FeodorFitsner** [comment]
This is how it worked during the recent image bake: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_qt_fast.ps1#L9-L73

**Comment by magnus-gross** [comment]
You also forgot to update the `C:/Qt/latest` path, it is still pointing to Qt 5.13.
Much appreciated if you would update the symlink.

**Comment by FeodorFitsner** [comment]
`Visual Studio 2019` image looks good: https://ci.appveyor.com/project/appveyor-tests/qt-tests/builds/33896865

**Comment by magnus-gross** [comment]
What about mingw?
https://ci.appveyor.com/project/magnus-gross/quickcurver/builds/34094792#L17
