### ISSUE TITLE
macOS: unable to run .NET Core tools

### ISSUE THREAD

**Issue by AdmiringWorm** [appveyor/ci#3457]
Currently, there are problems with running .NET Core global tools due to .net core SDKs are installed to a custom path, and the tools directory is not available on the path.

While this is something that *can* be fixed on the users end by manually setting the environment variables `DOTNET_ROOT=/Users/appveyor/.dotnet` and `PATH=$PATH:/Users/appveyor/.dotnet/tools` manually, it would have been nice if this was already set on the appveyor ci.

Builds:
- Faling due to missing `DOTNET_ROOT`: https://ci.appveyor.com/project/AdmiringWorm/pkg/builds/33106168/job/emky0l04qe4m5wui
- Failing due to missing `PATH`: https://ci.appveyor.com/project/AdmiringWorm/pkg/builds/33106070/job/twm061y1ah7r9xs4
- Success when both is set: https://ci.appveyor.com/project/AdmiringWorm/pkg/builds/33157352/job/7x071ua3dw6s3it3

**Comment by FeodorFitsner** [comment]
We are going to install .NET Core SDKs to the standard location `/usr/local/share/dotnet` and add it to `PATH`. Not sure about `DOTNET_ROOT` variable though - it's not being set by .NET Core `.pkg` installer. Is it required?

**Comment by AdmiringWorm** [comment]
Since the location `/usr/local/share/dotnet` is considered the global location for .NET Core, there shouldn't be a need to set the `DOTNET_ROOT` variable in when the SDKs gets installed there.

**Comment by AdmiringWorm** [comment]
When thinking about this a little more, I am not entirely sure if setting the `PATH` variable to `/usr/local/share/dotnet` would work as expected. If I remember correctly, .NET Core global tools will still get installed to `/Users/appveyor/.dotnet/tools` in either case, so I *think* the `PATH` variable would need to include that path as well.

However, that is something that would need to be confirmed, which I can not do since I do not own any Mac OSX machines.

**Comment by AdmiringWorm** [comment]
@FeodorFitsner I removed the workarounds I had regarding this issue earlier today. While there is no longer a need to set the `DOTNET_ROOT` environment variable to work around the issue, there is still a need to add the .NET Core tools directory to the `PATH` environment variable still. Would it be possible to have that added as well?

Failing without setting the `PATH` variable: https://ci.appveyor.com/project/AdmiringWorm/pkg/builds/33389873/job/e70peqryw47adv37
Success when the `PATH` variable is updated: https://ci.appveyor.com/project/AdmiringWorm/pkg/builds/33390258/job/axtrfyjg41ms2k12.

**Comment by FeodorFitsner** [comment]
Ah, tools! I though it's all about the path to `dotnet` "tool", but you mean tools installed with `dotnet tool install`! Sorry, my bad.

So, are the tools are always getting installed to `$HOME/.dotnet/tools` directory? .NET Core is now in `/usr/local/share/dotnet`.

**Comment by AdmiringWorm** [comment]
> Ah, tools! I though it's all about the path to dotnet "tool", but you mean tools installed with dotnet tool install! Sorry, my bad.

No worries, I re-read my initial comment and see I should have been a bit clearer on that point. So I am sorry as well.

> So, are the tools are always getting installed to $HOME/.dotnet/tools directory? .NET Core is now in /usr/local/share/dotnet.

As far as I know, yes it is always installed to `$HOME/.dotnet/tools` directory when trying to install global tools using the `-g` argument (I know at least on Linux it does that, and I assume it works the same on OSX).

**Comment by FeodorFitsner** [comment]
I've added another issue to add tools to PATH: https://github.com/appveyor/ci/issues/3466
