### ISSUE TITLE
SonarQube - PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#3459]
Since monday, sonarqube scanner fails to send analyze report and return an error:
`PayloadTooLargeError: request entity too large`
https://ci.appveyor.com/project/Maxhy/dokany/builds/33267288/job/fqwdw8s2lcvnop6w#L1128

Here is the YAML configuration
https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L201-L210
https://github.com/dokan-dev/dokany/blob/master/scripts/sonar-build.ps1#L20-L22

Searching for the error message, people often say it is a network / proxy issue. Would it be possible Appveyor can produce the error ?

**Comment by FeodorFitsner** [comment]
There are no proxies between AppVeyor VMs and the internet and build agent easily manages to upload gigabyte artifacts. I suspect it's a change on Sonar side. What's the size of the payload and the server you are sending it to?

**Comment by Liryna** [comment]
it is using their public server https://sonarcloud.io
I have created an issue on their side https://community.sonarsource.com/t/cssfamily-incorrectly-detect-a-file-and-fail-with-payloadtoolargeerror-request-entity-too-large/25736
thank you @FeodorFitsner for the support !
