### ISSUE TITLE
.NET Core 5 Preview 5 on macOS images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3461]

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner preview 6 is available

**Comment by FeodorFitsner** [comment]
Link?

**Comment by VladislavAntonyuk** [comment]
https://github.com/dotnet/installer Master

**Comment by FeodorFitsner** [comment]
But there is preview 5 only. Or you mean "master" is Preview 6?

**Comment by VladislavAntonyuk** [comment]
yes, if you take a look at version in the first column, you will see preview.6 there

**Comment by FeodorFitsner** [comment]
Could you drop a screenshot please?

**Comment by VladislavAntonyuk** [comment]
![CAA18DAC-3FA1-4E22-B851-0E7598514225](https://user-images.githubusercontent.com/33021114/83698910-53dc0280-a60b-11ea-9b22-630340216363.jpeg)

**Comment by FeodorFitsner** [comment]
Ah, it's 7! Where is 6 then? :)

**Comment by VladislavAntonyuk** [comment]
At the moment of writing the first comment it was version 6
