### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded in this build

### ISSUE THREAD

**Issue by asfernandes** [appveyor/ci#3464]
We got the error Maximum allowed artifact storage size of 50000 Mb will be exceeded:

https://ci.appveyor.com/project/FirebirdSQL/firebird/builds/33320947/job/hwxak0d3mwbl4uv3

Is it possible to change the limit please or remove old builds?

**Comment by FeodorFitsner** [comment]
The limit has been increased.
