### ISSUE TITLE
Python 3.9 betas on MS Windows

### ISSUE THREAD

**Issue by mr-c** [appveyor/ci#3467]
Hello,

Python 3.9.0b3 is out and it would be useful to have that available on the `Visual Studio 2019` and earlier images: https://www.python.org/downloads/release/python-390b3/

Thanks!

**Comment by FeodorFitsner** [comment]
You can install it during the build with the following script: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_python.ps1#L88-L108

**Comment by cclauss** [comment]
Can this issue be closed or is there a ToDo?
