### ISSUE TITLE
snupkg artifacts are not being uploaded by a nuget environment

### ISSUE THREAD

**Issue by brianfeucht** [appveyor/ci#3474]
We are generating and adding snupkg files as part of the build:
https://ci.appveyor.com/project/brianfeucht/headlesschromium-puppeteer-lambda-dotnet/build/artifacts

When I run a deployment using my Nuget Environment the process does not include the snupkg:
```
Downloading artifact HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.42.nupkg to temporary location...OK
Publishing HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.42.nupkg to https://www.nuget.org/api/v2/package...OK
Total packages published: 1
```

The expected output would be this package is uploaded to nuget.org as part of the deployment process by default.

**Comment by FeodorFitsner** [comment]
Could you drop (email?) a screenshot of your environment settings please (with all sensitive data removed/redacted/blurred)?

**Comment by brianfeucht** [comment]
API Key redacted.  Running all defaults:
![image](https://user-images.githubusercontent.com/1063445/85775228-72965c00-b6d4-11ea-8761-748bdaed037c.png)

**Comment by FeodorFitsner** [comment]
OK, the issue is that `.snupkg` artefact is uploaded without a type specified:

![image](https://user-images.githubusercontent.com/5041459/85776020-2a2b6e00-b6d5-11ea-92ed-82bce9bd8e46.png)

Should be "NuGetPackage`.

**Comment by brianfeucht** [comment]
Thank you!  The default `Auto` in my Cake build script was the problem.  I [explicitly set it](https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/commit/070d5b9c86269d6ba57ccfa023475ae077793b73) and the snupkg was uploaded

```
Downloading artifact HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.43.nupkg to temporary location...OK
Publishing HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.43.nupkg to https://www.nuget.org/api/v2/package...OK
Downloading artifact HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.43.snupkg to temporary location...OK
Publishing HeadlessChromium.Puppeteer.Lambda.Dotnet.1.0.1.43.snupkg to https://www.nuget.org/api/v2/symbolpackage...OK
Total packages published: 2
```
