### ISSUE TITLE
Linux deploy behaves differently than Windows when using Nuget

### ISSUE THREAD

**Issue by mauroservienti** [appveyor/ci#3475]
[One](https://ci.appveyor.com/project/ServiceComposer/servicecomposer-aspnetcore) of our projects uses a build matrix to build against Windows (Visual Studio 2019 image) and Linux (Ubuntu 20.04 image). The [AppVeyor.yml](https://github.com/ServiceComposer/ServiceComposer.AspNetCore/blob/master/appveyor.yml) configuration collects as artifacts the Nuget package (*.nupkg) and the Symbols package (*.snupkg).

For example, artifacts collected from Linux:

![image](https://user-images.githubusercontent.com/1325611/86087473-9545bd80-baa4-11ea-9c27-0d23bbe9ed26.png)

and Windows, during the same build:

![image](https://user-images.githubusercontent.com/1325611/86087509-aabae780-baa4-11ea-8d7a-16be6af2db29.png)

However, when deploying to Nuget from Linux only the Nuget package is pushed:

![image](https://user-images.githubusercontent.com/1325611/86087620-f077b000-baa4-11ea-91be-d81521d173d5.png)

In contrast to deploying from Windows which correctly pushes both the Nuget package and the Symbol package:

![image](https://user-images.githubusercontent.com/1325611/86087697-100ed880-baa5-11ea-9535-d7f7d11d2d88.png)

## Expected behavior

Both `nupkg` and `snupkg` packages are pushed regardless if they are deployed from Linux or Windows.

**Comment by FeodorFitsner** [comment]
That's because in Ubuntu build `.snpkg` artifact is pushed with generic "File" type: https://ci.appveyor.com/project/ServiceComposer/servicecomposer-aspnetcore/build/job/yf3hmtwspfyjkyn0/artifacts, but it should be `NuGetPackage` in order to be picked by deployment provider.

**Comment by mauroservienti** [comment]
Is there anything I can do to fix that? Otherwise, I can live with that 😄

**Comment by FeodorFitsner** [comment]
Sure, replace [this](https://github.com/ServiceComposer/ServiceComposer.AspNetCore/blob/master/appveyor.yml#L27-L29) with:

```yaml
artifacts:
- path: ./**/*.nupkg
  type: NuGetPackage
- path: ./**/*.snupkg
  type: NuGetPackage
```

**Comment by mauroservienti** [comment]
Thanks! Closing.
