### ISSUE TITLE
Ruby and bundler on macOS CI

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#3486]
I might be missing out on something silly...
I'm trying to `gem install bundler` on a macOS and I'm getting a permission error.
The fact that I can't install gems on CI with macOS kinda misses the point of Ruby development I believe.
There are probably workarounds which I'm currently looking for as I'm new to Ruby and Fastlane which is basically my goal with appveyor but it should work out of the box, shouldn't it?

**Comment by AdmiringWorm** [comment]
@HarelM you probably need to use `sudo`.
ie:
`sudo gem install bundler`.

That is just a guess though, as I am not familiar with `gem` nor `macosx`

**Comment by HarelM** [comment]
Not sure I can use sudo in the ci environment, can I?

**Comment by AdmiringWorm** [comment]
Not sure about the OSX image, but I know it can be used on the Linux image so I would believe you could in that image as well.

**Comment by HarelM** [comment]
Well, everywhere I read it is advised against using sudo and ruby. 
Having said that and just for the record, I can simply write `sudo ...` and it will work (assuming it is the same as the Linux image?)

**Comment by HarelM** [comment]
Adding `sudo` does seems to solve this issue but I still believe there's a problem with permissions in this image - `.rvm` folder should probably not require root permissions and gem installation should work without `sudo` I believe...
Not sure, maybe someone from @maintainers can shed some light on the matter...

**Comment by FeodorFitsner** [comment]
It's certainly looks like a bug. Of course, installing Ruby packages shouldn't require `sudo`. Will fix during the next image update.
