### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by rerrahkr** [appveyor/ci#3493]
Hello,

I got the error `Maximum allowed artifact storage size of 50000 Mb will be exceeded.`:
https://ci.appveyor.com/project/rerrahkr/bambootracker/build/job/2r408f5tlu41gd8y

I found it is possible to increase the storage size through some issues.
Would you please change the limit of artifact storage size?

**Comment by FeodorFitsner** [comment]
Should be fixed now.
