### ISSUE TITLE
v142 UWP build tools in VS2019 image

### ISSUE THREAD

**Issue by lukasf** [appveyor/ci#3504]
See failed build here, after switching to VS2019:

https://ci.appveyor.com/project/lukasf/ffmpeginteropx/builds/34439609

After switching back to VS2017 image, build works. So VS2017 image has v142 UWP tools, but VS2019 does not. Please note that this is about C++ UWP tools. These UWP tools are not included by default, so you have to manually add them to the installation: "C++ (v142) Universal Windows Platform tools".

**Comment by FeodorFitsner** [comment]
VS 2019 installation has [these UWP components](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_vs2019.ps1#L236-L238) selected. What additional components would you need from [this page](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019#universal-windows-platform-development)?

**Comment by lukasf** [comment]
I think building C++ UWP project should work (both v142 and v141) when adding these two component groups:

Microsoft.VisualStudio.ComponentGroup.UWP.VC
Microsoft.VisualStudio.ComponentGroup.UWP.VC.v141
