### ISSUE TITLE
Ubuntu 20.04 "focal" for images with WSL support

### ISSUE THREAD

**Issue by billziss-gh** [appveyor/ci#3506]
Any possibility of adding the Ubuntu 20.04 release to images with WSL support (i.e. "Visual Studio 2019")?

Unfortunately Ubuntu 18.04 is missing some packages that I need (e.g. packages related to `fuse3`).

**Comment by FeodorFitsner** [comment]
Sure, adding that for the next image update.

**Comment by billziss-gh** [comment]
@FeodorFitsner thanks.

Just curious on the time frame for this: if it is more than a few days then I will install Ubuntu 20.04 via the `appveyor.yml` file and remove those changes once you add the distribution to the image.

**Comment by FeodorFitsner** [comment]
Right, it's going to be updated in a week-two. Please modify `appveyor.yml` to install it during the build. This is how Ubuntu 18.04 is installed during image build: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_wsl.ps1#L51-L68 - hope it works similar for 20.04 - let me know.

**Comment by billziss-gh** [comment]
Many thanks! I will try to adapt your instructions for 18.04 to 20.04.

**Comment by billziss-gh** [comment]
@FeodorFitsner just to let you know that I was able to install Ubuntu 20.04 via `appveyor.yml` by adapting the Powershell script that you linked.

The changes were minimal:

- Changed download link to `https://aka.ms/wslubuntu2004`.
- Changed executable file name to `ubuntu2004.exe`.
- Adapted to the AppVeyor YAML format.

Related [commit](https://github.com/billziss-gh/winfuse/commit/30a52479a46320f09d2b928ed1e2cb148e49019e).

Again thanks for your help.
