### ISSUE TITLE
An option for Pull Requests to _not_ increment the version number

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#351]
Original conversation [is here](http://help.appveyor.com/discussions/suggestions/742-option-to-allow-prs-to-_not_-perm-increment-the-build-number). 

### Suggestion

An an optinal tickbox / yaml file entry, to allow build numbers to *not* increment when a PULL REQUEST check occurs.

![image](https://cloud.githubusercontent.com/assets/899878/9076089/42b5b1dc-3b61-11e5-86e5-767f02310bc6.png)

*Yaml File example*
```
pull_requests:
  do_not_increment_build_number: true
...
```

### Notes
The build number always has to be unique. As such, when this option is *TICKED* the build should have a `guid` or `timestamp` _appended_ to the build number, to keep it (temporarily) unique.

**Comment by micdenny** [comment]
+1

**Comment by PureKrome** [comment]
Any update on this @FeodorFitsner ?  Maybe add a milestone to this issue (beg...)

**Comment by FeodorFitsner** [comment]
I'm experimenting with this feature at the moment and there is something still unclear to me.

What would be the value of this behavior (i.e. do not increment build number on PRs) if there are multiple PRs are submitted/in-progress? I mean I can understand if it's just you working on the repo and you submit PR and then immediately merge it - this case it works. But what if there are other builds happening between the moment PR is opened and merged? Build number will be increment, right? Something like:

If you are working alone or non-busy project:
```
you - push - build #1
you - open PR - build #2-random
you - merge PR - build #2
```

If you are not working alone or busy project:
```
you - push - build #1
someone - push - build #2
you - open PR - build #3-random
someone - push - build #3
someone - push - build #4
you - merge PR - build #5
```

**Comment by PureKrome** [comment]
My thoughts..

```
you - push - build #1
you - open PR - build #PR-commithash-random-guid
you - merge PR - build #2
```

```
you - push - build #1
someone - push - build #2
you - open PR - build #PR-commithas-randomguid
someone - push - build #3
someone - push - build #4
you - merge PR - build #5
```

So the take away here is:
- PR : we _really_ don't care about the build number. We do NOT need to connect it to a _real_ build (number) at all.
- Merge/Push: we care.

**Comment by FeodorFitsner** [comment]
I've got something:

![image](https://cloud.githubusercontent.com/assets/5041459/9410497/78e2fa14-47d5-11e5-9707-056b9c4156b3.png)

Right, commit hash is not unique. Right now it follows defined version format and appends a random alphanumeric string, so the version compatible with semver format and works with AssemblyInfo.cs, nuget packaging, etc.

**Comment by PureKrome** [comment]
Looking great!

**Comment by PureKrome** [comment]
> so the version compatible with semver format and works with AssemblyInfo.cs, nuget packaging, etc.

Kewl ... but ... useless? Meaning, it's a PR build .. there is not deployment, etc. Any dll's created are not used. It's mainly to check that the code builds and tests pass.

Not hating! Love this work effort :) Just .. seeing if I've missed something ....

**Comment by FeodorFitsner** [comment]
Sure, no rush with deployment of this feature :) Let's think again what business problem we are trying to solve here? Maybe there are other ways to solve it.

**Comment by PureKrome** [comment]
Your current solution looks good IMO. 

Problem (we're trying to solve): When _anyone_ submits a PR, the build number increments, which ruin public NuGet projects semver's.

Solution: the build number (which is used for semver when assembly patching) is never used in a PR ... so it's therefore a garbage (but unique) string value.

Looking at your solution/screenie above - that's great :) that works! I was just curious about your comment how u made the build version semver-happy ... because I was wondering _why_ (out of curiosity).

I still :heart: what you've shown, though :) :+1: :balloon: :cake:

**Comment by micdenny** [comment]
great job guys, I like the the way posted by @FeodorFitsner I think is the right path

**Comment by FeodorFitsner** [comment]
Cool, shall we deploy that then? :)

Re: version - it's not like *AppVeyor* sets semver when it's PR build, it's just that example. AppVeyor just takes version format currently defined for the project and appends `-random`.

**Comment by micdenny** [comment]
@FeodorFitsner would this change good for everybody or should we think to push as a toggle functionality? so that from appveyor config file we can enable or disable that behavior. What do you think?

**Comment by FeodorFitsner** [comment]
Obviously, the behavior is disabled by default, but can be enabled on UI:

![image](https://cloud.githubusercontent.com/assets/5041459/9423608/624756e6-4880-11e5-89f7-53ca5c644c3f.png)

or in `appveyor.yml`:

```
pull_requests:
  do_not_increment_build_number: true
```

**Comment by micdenny** [comment]
@FeodorFitsner that's perfect, and I just realized that was in the very first description of this issue, sorry :)

to me you can deploy it :smile: a feature that could be loved by the ones that wants a perfect build history ;)

**Comment by gep13** [comment]
@micdenny @PureKrome Just wanted to point out that there is a tool called GitVersion, which already supports AppVeyor, that can help with asserting the Semantic Version of your application, based on the current state of your repository.  You can find out more information about it here:

http://gitversion.readthedocs.org/en/stable/

Just wanted to point it out as, based on the discussion here, I think it could be quite useful to you.

**Comment by micdenny** [comment]
Thanks @gep13 we're (in [Radical](https://github.com/RadicalFx/Radical)) definitively taking in consideration GitVersion, I was not aware of the appveyor yml generator in GitVersion, will give it a try later this months.

**Comment by FeodorFitsner** [comment]
The feature has been deployed.

**Comment by micdenny** [comment]
![image](https://cloud.githubusercontent.com/assets/1633595/9427860/38fb4834-4992-11e5-98e7-7fa61799f92a.png)

that's great!! :smile:

**Comment by micdenny** [comment]
here's in action, it just works!!

https://ci.appveyor.com/project/radical-bot/radical-windows-presentation-unity3/build/0.1.0-alpha1+3-o22qsh0d

**Comment by PureKrome** [comment]
![](https://31.media.tumblr.com/43e63461d1e3f22a49b18dbf15227a1d/tumblr_inline_n3t10oQfIh1solpjm.gif)

**Comment by PureKrome** [comment]
@FeodorFitsner I know this issue has been closed / working .. but is there an _environment variable_ for this? So we can test/use this in a Powershell script?

The `yml` file has the option:

```
pull_requests:
  do_not_increment_build_number: true
```

so maybe it's related?

**Comment by FeodorFitsner** [comment]
There is no variable. Why would you need that?

**Comment by PureKrome** [comment]
Right now, I have to manually run my powershell script in a build step. I'm currently using `on_success` to do this. Why this step? Compile has passed _and_ Tests have passed. There's no deployment because _this_ is the deployment step (until hopefully #128 might be considered and implemented :+1: ) I am using.

As such .. I do not want to deploy if this is a PR :)

So i need to do a check in the PS script (I assume). Unless there's a better way.

eg..
```
on_success:
  - if NOT a PR then:
    - PS script number 1
    - PS script number 2
```

did that make _any_ sense?

**Comment by FeodorFitsner** [comment]
You can check if `APPVEYOR_PULL_REQUEST_NUMBER` is set.

**Comment by PureKrome** [comment]
How do I do that with Powershell? i'm guessing `$env:APPVEYOR_PULL_REQUEST_NUMBER` ?

**Comment by FeodorFitsner** [comment]
Correct.

**Comment by PureKrome** [comment]
Sweeet. works. all good. ta.
