### ISSUE TITLE
Microsoft Visual Studio 2019 Version 16.7.2

### ISSUE THREAD

**Issue by dmex** [appveyor/ci#3514]
The VS2019 build image currently has version 16.6.5 but the latest release is 16.7.2.

16.7.2 and later is needed to compile binaries with features such as CET:
https://docs.microsoft.com/en-us/cpp/build/reference/cetcompat?view=vs-2019

**Comment by FeodorFitsner** [comment]
We are working on the image update right now: https://github.com/appveyor/ci/issues/3517. Thanks for your patience.
