### ISSUE TITLE
Update Cygwin to 3.1.7 in Windows images

### ISSUE THREAD

**Issue by dra27** [appveyor/ci#3520]
One of our CI runs must be run on at least Cygwin 3.1.7 for x86. Doing a full Cygwin upgrade in every run is very slow, so please could your next round of Windows image updates do an upgrade to the x86 Cygwin installation?

**Comment by dra27** [comment]
Affected build example: https://ci.appveyor.com/project/AltGr/opam/builds/34910769/job/m7s6glk0ew1pmtld#L18

**Comment by FeodorFitsner** [comment]
Please use `Visual Studio 2019` image with the most recent Cygwin installed.

**Comment by dra27** [comment]
I didn't realise you could specify different images for different parts of the matrix - handy! However, the VS 2019 image doesn't have the latest Cygwin (it's on 3.1.6) - https://ci.appveyor.com/project/AltGr/opam/builds/34911577/job/evd1h6gemrv13238#L14

**Comment by FeodorFitsner** [comment]
We are currently updating VS 2019 image - should be available by the end of this week.

Could you please give me a simple command to check installed cygwin version?

**Comment by dra27** [comment]
`uname -a` or `cygcheck -dc cygwin` both include it

**Comment by dra27** [comment]
That’s great, thanks!
