### ISSUE TITLE
Confusing error for branch build

### ISSUE THREAD

**Issue by tdegeus** [appveyor/ci#3526]
While appveyor is running without problems for the "pr" I'm getting the following error message for the "branch":
```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
While in fact this concerns *the same build*? 

References:
* https://github.com/tdegeus/GMatElastoPlasticQPot/pull/31
* https://ci.appveyor.com/project/tdegeus/gmatelastoplasticqpot/builds/35124560

**Comment by FeodorFitsner** [comment]
That `ci` [branch/commit](https://github.com/tdegeus/GMatElastoPlasticQPot/tree/435c7b064d803334e11001eaab9f2092b7393143) doesn't have `.appveyor.yml`, so AppVeyor is running "default" build pipeline for MSBuild.
