### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded.

### ISSUE THREAD

**Issue by parachvte** [appveyor/ci#3527]
Run out of artifacts storage: https://ci.appveyor.com/project/parachvte/luban/builds/35178751

**Comment by FeodorFitsner** [comment]
It should be fixed now for your account.

**Comment by Pyrdacor** [comment]
@FeodorFitsner  Hi I don't want to open a new issue for this. Can you please increase my limit as well. I also get the 50000 MB message: https://ci.appveyor.com/project/Pyrdacor/ambermoon-net
