### ISSUE TITLE
The license for Visual Studio 2019 expires in 7 days.

### ISSUE THREAD

**Issue by smartblade** [appveyor/ci#3528]
The license for Visual Studio 2019 expires in 7 days in the `Visual Studio 2019` image.
- [AppVeyor build log](https://ci.appveyor.com/project/smartblade/bldmystery/builds/35297963/job/jc8niu0q5nfk6ukj#L34)
- [AppVeyor YAML file](https://github.com/smartblade/BldMystery/blob/master/appveyor.yml)

**Comment by FeodorFitsner** [comment]
Closing in favour of: https://github.com/appveyor/ci/issues/3529
