### ISSUE TITLE
Build number collisions

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#353]
This is happening increasingly frequently at https://ci.appveyor.com/project/StefanKarpinski/julia/history, and it's getting to be disruptive. Something needs to be made more atomic when the build number increments upon starting a new build.

**Comment by FeodorFitsner** [comment]
Right, will be working on that with higher priority.

**Comment by Mailaender** [comment]
I can confirm that this happens frequently:

![image](https://cloud.githubusercontent.com/assets/756669/9092284/7cf6e8cc-3ba5-11e5-9bcc-0c89ea6ac7cf.png)

**Comment by FeodorFitsner** [comment]
What account is OpenRA under?

**Comment by Mailaender** [comment]
https://ci.appveyor.com/project/OpenRA/openra/history

**Comment by Mailaender** [comment]
Also it didn't fix itself. I had to manually increment the build number. https://github.com/OpenRA/OpenRA/pull/8839#issuecomment-128072110

**Comment by tkelman** [comment]
I've had to do the same. We've gotten multiple builds now for 1.0.7651, 1.0.7647, and 1.0.7624 just within the last day.

**Comment by Mailaender** [comment]
It now happens multiple times per day:

![image](https://cloud.githubusercontent.com/assets/756669/9116830/c08a7722-3c66-11e5-9473-ac86bd8b60c7.png)

**Comment by FeodorFitsner** [comment]
What time of the day is it usually happening?

**Comment by Mailaender** [comment]
The state sadly also butchers build times. Not sure if this is helpful:

* 6 Aug, 2015 10:27:15 - 10:49:55
* 5 Aug, 2015 19:03:36 - 19:25:41
* 19 Jul, 2015 6:00:16 - 9:25:33
* 18 Jul 2015, 20:44:20 - 9:05:30

**Comment by vtjnash** [comment]
It happened recently again on https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.7696 with build times of:
5 hours ago (1.0.7695 successful)
26 minutes ago (1.0.7696 failed)
4 minutes ago (1.0.7696 failed)
4 minutes ago (1.0.7696 failed)

**Comment by FeodorFitsner** [comment]
We are working on the solution. Restart the build - there were two stuck jobs.

**Comment by Mailaender** [comment]
Seems to happen at least daily now: 7 Aug, 2015 6:00:39 but the times seem to differ.

**Comment by FeodorFitsner** [comment]
What was the build number?

**Comment by Mailaender** [comment]
https://ci.appveyor.com/project/OpenRA/openra/build/1.0.5509

**Comment by tkelman** [comment]
I think this has been mitigated successfully for a few days, thanks. Will reopen if it happens again.

**Comment by ihnorton** [comment]
This is still happening. See all of the 1.0.7841 repeats at https://ci.appveyor.com/project/StefanKarpinski/julia/history

**Comment by FeodorFitsner** [comment]
Will check what happened. I've reset the queue - start a new build.

**Comment by tkelman** [comment]
This hasn't happened in a while. Will call it fixed unless I see it again.
