### ISSUE TITLE
load pubkey invalid format with Git 2.28.0 on VS 2019 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3539]
Related issue: https://github.com/git-for-windows/git/issues/2743
Relevant discussion on HN: https://news.ycombinator.com/item?id=24612487

The issue should be fixed in the next release of Git for Windows. For now, we are rolling back to Git 2.26.2.

**Comment by zootopialover** [comment]
Still getting `git version 2.28.0.windows.1` in VS 2019 image.

Any steps to apply this rolling back to 2.26.2? 

@FeodorFitsner

**Comment by FeodorFitsner** [comment]
Working on the update. Thanks for your patience.
