### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by hugovk** [appveyor/ci#3541]
Python 3.9.0 was released yesterday, 2020-10-05:

* https://discuss.python.org/t/python-3-9-0-is-now-available-and-you-can-already-test-3-10-0a1/5375?u=hugovk

Please could you also add support in AppVeyor for Python 3.9?

Thank you!

PS It took 25 days for 3.8: https://github.com/appveyor/ci/issues/3142 :)

**Comment by hugovk** [comment]
@FeodorFitsner Is 3.9 now available to use for AppVeyor or do we need to wait for a deploy? Thank you!

**Comment by AvdN** [comment]
@hugovk I just tried to complete my builds and it is not there (yet). Would have been more clear if this was not closed until resolved (ie. proven to be functional).

**Comment by dvarrazzo** [comment]
Not there yet: https://ci.appveyor.com/project/psycopg/psycopg2/build/job/igre2hjljb3ythao

**Comment by FeodorFitsner** [comment]
It's on `Visual Studio 2019` image.

**Comment by ahtik** [comment]
@FeodorFitsner As I understand, https://ci.appveyor.com/project/psycopg/psycopg2/build/job/86s3me5nj6x2l5gu does use the "Visual Studio 2019" image (see build title). Is there a way to see the base image name used for the build?

**Comment by FeodorFitsner** [comment]
As there is `appveyor.yml` in the repo UI settings are ignored. Add this to `appveyor.yml` instead:

    image: Visual Studio 2019

**Comment by albertosottile** [comment]
Are there plans to put Python 3.9 also in the other images, e.g. Visual Studio 2015?

**Comment by hugovk** [comment]
> PS It took 25 days for 3.8: #3142 :)

This year it took 21 days! 🎈 

* https://twitter.com/hugovk/status/1321536957965574151
