### ISSUE TITLE
AppVeyor OnPremise: WebHook option to accept selfsigned certificates

### ISSUE THREAD

**Issue by itniels** [appveyor/ci#3543]
I wrote a Linux deployment agent for AppVeyor for my NetCore projects, expecting to consume the WebHook JSON and handle the rest from the service.

But i get the following error when deploying in appveyor:
```
Error calling webhook https://<domain>:<port>/deployment/submit: The SSL connection could not be established, see inner exception.
```

This indicates to me it get's rejected due it being a selfsigned certificate generated on startup of the agent.
I have no feasible way of including a "real" certificate!

I would love an option to accept any certificate, the important thing is SSL in my case.
Thanks in advance 🙂

**Comment by FeodorFitsner** [comment]
Why not to install Let's encrypt certificate then? ;)

**Comment by itniels** [comment]
Thanks for the quick reply @FeodorFitsner 🙂 

Indeed, I love LE and use it for everything else!
But like I stated, it is not feasible in the current environment where it will be spun up and running unfortunately!

So would love the option above, as cleatext basic auth is not a solution.... 😱
If this is not something you are willing to add, then I will just have to figure out an alternative solution, but would love to know either way so i can make a decision.

Thanks again.

**Comment by FeodorFitsner** [comment]
OK, looking into that.

**Comment by itniels** [comment]
Thankyou, I really appreciate that very much 🙂

**Comment by FeodorFitsner** [comment]
OK, give 7.0.2954 build a try:

* Linux: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2954/appveyor-server_7.0.2954_amd64.deb
* Windows: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.2954/appveyor-server-7.0.2954-win-x64.msi

It has a new "Skip SSL certificate check" option for both webhook deployments and notifications.

Let me know how it worked.

**Comment by itniels** [comment]
Thankyou so much @FeodorFitsner!
I will give this a try ASAP today. 😊

**Comment by itniels** [comment]
Fantastic! it works perfectly!
Thankyou ever so much @FeodorFitsner 🙌

```
Calling webhook https://<domain>:<port>/deployment/submit...OK
```

**Comment by itniels** [comment]
@FeodorFitsner Should I close the issue or would you like it kept open for now? 🙂
And have a great weekend.

**Comment by FeodorFitsner** [comment]
Sure, let's close it. Thank you!
