### ISSUE TITLE
WSL Ubuntu 20.10

### ISSUE THREAD

**Issue by tmiguelf** [appveyor/ci#3561]
I'm trying to setup a VS preview build using WSL g++10.2 C++20. But the linker (ld version 2.34) seems to have a bug that fails to compile the code (silently). ld version 2.35.1 doesn't seem to have this problem but unfortunately this version is only packaged for Ubuntu 20.10.

Getting an image with WSL Ubuntu 20.10 would solve this problem.

Thanks.

**Comment by FeodorFitsner** [comment]
Installing Ubuntu 20.10 into WSL is a bit hacky right now: https://discourse.ubuntu.com/t/installing-ubuntu-20-10-on-wsl/18941

Wondering if you could script and give a try to both methods (or maybe second one with sideloading) during the build?

**Comment by tmiguelf** [comment]
Thanks, that works.
The first solution works for me it only adds 10mins to my build, which feels acceptable. (note: not the do-release-upgrade route because that will ask for user to type stuff on the keyboard and you can't script that, so it's useless)

**Comment by FeodorFitsner** [comment]
That's nice! Would you mind sharing the solution?

**Comment by tmiguelf** [comment]
Sure, I managed to narrow it down to 3 lines:
    - wsl sudo sed --in-place 's/focal/groovy/g' /etc/apt/sources.list
    - wsl sudo apt update
    - wsl sudo apt install -y g++

I.e. Updating the repository list from focal to gorila, and just installing the tools that I need from it.  I figured this would lead to the least amount of overhead.

**Comment by FeodorFitsner** [comment]
Thank you!
