### ISSUE TITLE
dotnet 5 stable on macos 

### ISSUE THREAD

**Issue by SimonCropp** [appveyor/ci#3565]
dotnet 5 stable have been released. Would it be possible to include them in the next macos image

**Comment by SimonCropp** [comment]
can i help with this in any way?

**Comment by FeodorFitsner** [comment]
You don't necessary need to wait for an updated image to get the latest .NET 5. It could be easily added during the build with this two-liner:

```bash
curl -fsSL https://download.visualstudio.microsoft.com/download/pr/0871336f-9a83-4ce4-80ca-625d03003369/2eb78456e0b106e9515dc03898d3867a/dotnet-sdk-5.0.100-osx-x64.tar.gz -o dotnet-sdk.tar.gz
sudo tar zxf dotnet-sdk.tar.gz -C /usr/local/share/dotnet
```

**Comment by RehanSaeed** [comment]
I am having trouble with installing the latest .NET SDK on Mac OS. When I then run `dotnet tool restore` I get a `Command exited with code 132` error.

More info in https://github.com/appveyor/ci/issues/3314#issuecomment-760081464.

**Comment by FeodorFitsner** [comment]
Try doing `sudo dotnet tool restore`.

**Comment by SimonCropp** [comment]
this was done a while ago

**Comment by RehanSaeed** [comment]
I've still been getting errors when running xUnit tests on Mac OS while Windows and Linux work just fine:

> [xUnit.net 00:00:26.79]     [FATAL ERROR] System.AppDomainUnloadedException

https://ci.appveyor.com/project/RehanSaeed/schema-net/branch/main/job/9eym36pbvdfo6e64
