### ISSUE TITLE
Maximum allowed artifact storage size of 75000 Mb will be exceeded.

### ISSUE THREAD

**Issue by rerrahkr** [appveyor/ci#3575]
We encountered an error in storage size: `Maximum allowed artifact storage size of 75000 Mb will be exceeded.`
https://ci.appveyor.com/project/rerrahkr/bambootracker/build/job/o5hpsx20cbd034w8

We made the artifact size smaller than in the previous issue (#3493), but ran out of space. Would you please expand the storage size again?

**Comment by FeodorFitsner** [comment]
Should be good now.
