### ISSUE TITLE
Miniconda 3.10.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#359]
Miniconda 3.10.1 (Python 2.7.9.1):

    C:\Miniconda
    C:\Miniconda\Scripts

Miniconda 3.10.1 x64 (Python 2.7.9.1):

    C:\Miniconda-x64
    C:\Miniconda-x64\Scripts

Miniconda 3.10.1 (Python 3.4.3):

    C:\Miniconda3
    C:\Miniconda3\Scripts

Miniconda 3.10.1 x64 (Python 3.4.3):

    C:\Miniconda3-x64
    C:\Miniconda3-x64\Scripts

To use Miniconda in your build add appropriate version to `PATH`, for example:

    install:
    - set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%

**Comment by ctaggart** [comment]
Or if you are using PowerShell:
``` PowerShell
$env:path = "C:\Miniconda;C:\Miniconda\Scripts;$env:path"
```

**Comment by Juanlu001** [comment]
I see that AppVeyor only ships Windows Server x64. Would you please clarify what's the difference between `C:\Miniconda3` and `C:\Miniconda3-x64` then?

**Comment by Juanlu001** [comment]
Self-answer: https://www.appveyor.com/docs/installed-software#python :smile:
