### ISSUE TITLE
Visual Studio 2019 license has expired

### ISSUE THREAD

**Issue by yfdyh000** [appveyor/ci#3595]
The license for Visual Studio has expired. [The logs](https://ci.appveyor.com/project/yfdyh000/sqlitebrowser/builds/36851275#L345).

**Comment by FeodorFitsner** [comment]
It should be fixed now.

**Comment by ntamas** [comment]
Apologies if I'm missing something trivial, but it seems like the Visual Studio 2019 license has either expired again or it is still expired; see the [build logs](https://ci.appveyor.com/project/ntamas/python-igraph-jst2e/build/job/896891hruy6oomdq#L630) in my project.

**Comment by FeodorFitsner** [comment]
Updated image is on the way!

**Comment by FeodorFitsner** [comment]
Should be OK now.
