### ISSUE TITLE
typo on doc, and there is no documentation for removing obsolete libraries

### ISSUE THREAD

**Issue by yfdyh000** [appveyor/ci#3596]
https://www.appveyor.com/docs/windows-images-software/#qt
> Qt 5.15.2: **C:\Qt\5.15.1** (C:\Qt\5.15 mapped to C:\Qt\5.15.2 for backward compatibility)

The "C:\Qt\5.15.1" is not matched. And it does not exist now, I'm not sure if this is documented.

**Comment by FeodorFitsner** [comment]
Thanks for the catch! It's been fixed.
