### ISSUE TITLE
Unable to build using Visual Studio 2019, error with nuget restore

### ISSUE THREAD

**Issue by bclothier** [appveyor/ci#3617]
When we try to build using the `Visual Studio 2019` image, we are getting the error:
```
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.
```

Googling suggests that this is due to TLS 1.3 needing to be enabled but this seems beyond the scope of AppVeyor yml configuration. We've tried few times to rule out the intermittent network issues. 

We are able to build other builds using `Visual Studio 2017` image.

Modified AppVeyor config file:
https://github.com/rubberduck-vba/Rubberduck/blob/04d562204d1a404e47690c72d7fcda47531d6792/appveyor.yml

AppVeyor log:
https://ci.appveyor.com/project/rubberduck-vba/rubberduck/builds/37690691

**Comment by Vogel612** [comment]
https://github.com/NuGet/Home/issues/10491 seems like it's related, considering that's a recently surfacing certificate issue around the v3 api...

**Comment by FeodorFitsner** [comment]
I'm testing on `Visual Studio 2019` and it works: https://ci.appveyor.com/project/FeodorFitsner/appveyor-bot-test-2r9sv/builds/37691662

In my build it displays the version of NuGet: `NuGet Version: 5.8.0.6930`.

Could you add `where nuget` to see where does Nuget.exe come from?

**Comment by bclothier** [comment]
```
where nuget
C:\Tools\NuGet\nuget.exe
```

https://ci.appveyor.com/project/rubberduck-vba/rubberduck/builds/37692059

**Comment by FeodorFitsner** [comment]
This might be a problem: https://github.com/bclothier/Rubberduck/tree/5888678c3786739aeb816e3179024e04c69e7245/.nuget 

Remove it and it should do the trick. .csproj must be cleaned as well to do not load nuget targets: https://github.com/bclothier/Rubberduck/blob/5888678c3786739aeb816e3179024e04c69e7245/RubberduckBaseMetaProject.csproj#L53

**Comment by bclothier** [comment]
Thanks for the suggestions!

I've removed the folder containing those nuget stuff and also removed the target in this commit:
https://github.com/rubberduck-vba/Rubberduck/pull/5239/commits/edddd8b35c11027497c164a4a7c3dc792c874730

However, the AV still fails for same reason:
https://ci.appveyor.com/project/rubberduck-vba/rubberduck/builds/37692432

**Comment by FeodorFitsner** [comment]
Oh, finally see it. This is the issue: https://github.com/rubberduck-vba/Rubberduck/blob/4797188e7600cc57825c360af19e04246aa8f5ee/appveyor.yml#L5

**Comment by bclothier** [comment]
To be honest, I'd never have seen the issue myself! I _think_ those stuff you asked me to remove were a very old workaround to the issues with `nuget restore`. Thank you very much for your help!
