### ISSUE TITLE
DirectX June 2010 on Visual Studio 2019

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3628]
Direct download URL: https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe

https://www.microsoft.com/en-us/download/details.aspx?id=6812
https://help.appveyor.com/discussions/problems/28994-dxsdk-on-visual-studio-2019-broken

**Comment by fahad12346** [comment]
.github/workflows/build.yml

**Comment by fahad12346** [comment]
> Direct download URL: https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe
> 
> 
> 
> https://www.microsoft.com/en-us/download/details.aspx?id=6812
> 
> https://help.appveyor.com/discussions/problems/28994-dxsdk-on-visual-studio-2019-broken

**Comment by fahad12346** [comment]
https://github.com/TASVideos/desmume/blob/master/.github/workflows/build.yml
