### ISSUE TITLE
PyQt install broken since 3.1.0

### ISSUE THREAD

**Issue by The-Compiler** [appveyor/ci#363]
Since the [latest AppVeyor update](http://www.appveyor.com/updates) 3.1.0, my build which installs PyQt [seems to fail](https://ci.appveyor.com/project/The-Compiler/qutebrowser/build/dirbrowser-536) as it can't import sip/PyQt anymore.

I install it by downloading the PyQt installer and running it with `/S`, see [ci_install.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/dev/ci_install.py#L58-L65).

When I use `os: Previous Windows Server 2012 R2` in my `appveyor.yml` it [works again](https://ci.appveyor.com/project/The-Compiler/qutebrowser/build/appveyor-fix-553).

I don't see any chances in the list which could've impacted this (like Python changes) - so any idea what could be going on here?

**Comment by FeodorFitsner** [comment]
You were testing not on previous actually, but on image before previous - July 27. Previous one was Aug 8. I've changed that - give it another try please.

**Comment by The-Compiler** [comment]
Thanks for the quick reply! :+1:

I forced a new build and it still seems to work with the Aug 8 image:

https://ci.appveyor.com/project/The-Compiler/qutebrowser/build/master-555

**Comment by FeodorFitsner** [comment]
OK, it's the last update then. My guess would be MIniconda. You can try looking via RDP: http://www.appveyor.com/docs/how-to/rdp-to-build-worker

Let me know about your findings.

**Comment by The-Compiler** [comment]
Your guess seems to be right, I get this when trying to install it:

> A copy of PyQt5 for Python v3.4 is already installed in C:\Miniconda3-x64 and should be uninstalled first.

I guess in headless mode, the installer aborts at this point.

However, when trying to use `C:\Miniconda3-x64\python.exe`, that seems to be broken as well:

```
>>> from PyQt5 import QtCore
...
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Unfortunately, even after running the uninstaller for Miniconda, the PyQt installer still picks up `C:\Miniconda-x64` as install location...

**Comment by FeodorFitsner** [comment]
Try using `C:\Miniconda3\python.exe` one

**Comment by The-Compiler** [comment]
That one doesn't have PyQt at all: `ImportError: No module named 'PyQt5'`

**Comment by FeodorFitsner** [comment]
Have you tried uninstalling Miniconda right after cloning repo, say in `install` section?

**Comment by FeodorFitsner** [comment]
Looks like it can't be automatically and silently uninstalled...

I'm just wondering if it's possible to deploy Miniconda without actually installing it, i.e. just unpack zip with it? It shouldn't have files outside `C:\miniconda` folder, right?

**Comment by The-Compiler** [comment]
Oh - it seems PyQt doesn't actually exist with miniconda on the AppVeyor image - it's just that PyQt detects that folder and installs it there...

**Comment by The-Compiler** [comment]
Miniconda can in fact be uninstalled silently by passing the `/S` switch - but it still doesn't seem to work after that...

I'll continue investigating tomorrow, I need some sleep now - thanks for the great support so far! :zzz:

**Comment by The-Compiler** [comment]
Okay - it seems Miniconda sets its Python interpreter as default in the `HKEY_CURRENT_USER\Software\Python\PythonCore\3.4\InstallPath` registry key, and keeps that even after uninstalling it...

I worked around it by setting the path back in the registry before installing PyQt: https://github.com/The-Compiler/qutebrowser/commit/9eca7ae55615cd4c57007e2daa8c3ad300014912

Would it be possible to install the "normal" Python versions after installing Miniconda? Then I guess those paths would be set correctly.

**Comment by FeodorFitsner** [comment]
Brilliant! Thanks for troubleshooting that!

So, to fix that the following command could be added into `appveyor.yml`

```
install:
- REG ADD HKCU\Software\Python\PythonCore\3.4\InstallPath /f /ve /t REG_SZ /d C:\Python34
```

Yes, we'd re-install "standard" Python on top of Miniconda. Let's keep this issue open.

**Comment by parkouss** [comment]
Ok apparently github automatically referenced the issue. :)

So I had the same bug, but for PyQt4 and Python27.

Adding:
```yaml
REG ADD HKCU\Software\Python\PythonCore\2.7\InstallPath /f /ve /t REG_SZ /d %PYTHON%
```
Before installing PyQt4 fixed the issue. Thanks @The-Compiler !

https://github.com/mozilla/mozregression/blob/76ccdb31212947179617f3f9399bce34a74b6189/appveyor.yml#L11-L14
