### ISSUE TITLE
Visual Studio 2017 image does not come back online after reboot

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#3650]
Hi,

At [Dokany](https://github.com/dokan-dev/dokany) we have a need to enable Windows features that requires a reboot.
We are using the 2019 / 2017 & 2015 image for testing and the 2017 seems to have an issue to never come back online after the reboot.
This can easily be reproduced with this YAML: https://github.com/Liryna/dokany/blob/master/appveyor.yml
An example of the Build: https://ci.appveyor.com/project/Liryna/dokany/builds/38489578

Thanks again for your service!

**Comment by FeodorFitsner** [comment]
It looks like it takes "some" time to update the password of "appveyor" local user account. It's done asynchronously in build agent while the build is running, so the password is not yet updated when you put VM into restart.

Look at this appveyor.yml: https://gist.github.com/FeodorFitsner/7abb7ff1f45171c67741c0fab6c2254e - that does restart on VS 2017 image. However, if `Start-Sleep -s 30` removed it won't work. Hope that helps.

**Comment by Liryna** [comment]
Indeed! it fixed the issue https://ci.appveyor.com/project/Maxhy/dokany/builds/38541860
Thanks as always!
