### ISSUE TITLE
Bintray sunset has broken 'apt update'

### ISSUE THREAD

**Issue by cgutman** [appveyor/ci#3668]
It looks like the RabbitMQ repo is still pointing to Bintray which has been taken down as of May 1 per [Bintray's announcement in February](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

```
Err:28 https://dl.bintray.com/rabbitmq-erlang/debian xenial Release
  403  Forbidden
Err:29 https://dl.bintray.com/rabbitmq/debian xenial Release
  403  Forbidden
[snip]
E: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://dl.bintray.com/rabbitmq/debian xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Here is a link to a broken build: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38971639/job/4uuer43qko98gi7r
and the AppVeyor yml: https://github.com/moonlight-stream/moonlight-qt/blob/0f930918489fff2bc8144e41762f676ccf2657a3/appveyor.yml

A simple build configuration that attempts to run `apt update` should be sufficient to reproduce the issue. I suspect the issue is not specific to `Ubuntu1604`, but I haven't confirmed that.

**Comment by cgutman** [comment]
I confirmed that `Ubuntu2004` is also affected. https://ci.appveyor.com/project/cgutman/moonlight-packaging/builds/38972929/job/xrcjffyqanwhixtl

**Comment by FeodorFitsner** [comment]
Thank you! Working on the update.
