### ISSUE TITLE
GitHub artifact upload fails when release exists

### ISSUE THREAD

**Issue by Snaipe** [appveyor/ci#367]
Appveyor does not seem to support GitHub deployment when the release already exists. I feel that it should upload the artifact if the release already exists for those that use more than 1 CI server (I use Travis for Linux & OS X builds, and Appveyor for windows builds)

**Comment by kinke** [comment]
May I ask why you closed that issue? I'm still experiencing it:
```
Deploying using GitHub provider
Creating "LDC Win64 master" release for repository "ldc-developers/ldc" tag "LDC-Win64-master" commit "0dd0b4a56cfaaaa94a4bb4d7f501d5be0125b2f7"...Skipped (Release with tag "LDC-Win64-master" already exists)
Uploading "ldc-x64.7z" to release assets...Error uploading release asset. Validation Failed: (resource=ReleaseAsset, code=already_exists, field=name)
```
I don't plan an uniquely naming each version, as I don't wanna end up with 1000+ downloads for the rolling release...

**Comment by FeodorFitsner** [comment]
It should be unique within the given release. The error above means there's already an asset with such file name under that release.



- Feodor

**Comment by kinke** [comment]
Okay, thx for the very quick answer.
