### ISSUE TITLE
Projects quota exceeded appears when adding a new project

### ISSUE THREAD

**Issue by ANF-Studios** [appveyor/ci#3673]
Hello there,
I was trying to add a new project on AppVeyor for my purposes, though.. oddly enough, I see this:
![image](https://user-images.githubusercontent.com/68814933/117355735-f2f32500-ae80-11eb-979f-d23799d5c6c6.png)
I don't think my "quota" would exceed after having only one project there. And on top, this is not just me! I've had two other colleagues of mine try it too on their accounts. Could you please explain what I am missing here? There's no documentation on project quota either.

My username is, as you could guess, `ANF-Studios`, if that helps.

**Comment by FeodorFitsner** [comment]
It's been fixed.

**Comment by ANF-Studios** [comment]
Works for me now, thanks!
