### ISSUE TITLE
Ruby 2.2.3, 2.1.7, and 2.0.0-p647 + latest Bundler

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#368]
https://twitter.com/sodabrew/status/634004623058010112

**Comment by sodabrew** [comment]
RubyInstaller builds coming next week: https://groups.google.com/forum/#!msg/rubyinstaller/15lypPdoyrI/K-A4W6JFDQAJ

**Comment by FeodorFitsner** [comment]
Nice, nice :)

**Comment by sodabrew** [comment]
The builds are [finally] available! http://rubyinstaller.org/downloads

**Comment by FeodorFitsner** [comment]
Wow, nice! Finally! :)

**Comment by sodabrew** [comment]
:trophy:  https://ci.appveyor.com/project/sodabrew/eventmachine/build/56
