### ISSUE TITLE
repro

### ISSUE THREAD

**Issue by OsvaldoRino** [appveyor/ci#3689]
Please provide a repro. Ideally, AppVeyor build of public repository. Provide build configuration in YAML format. If repro does not fit into single build scenario, please provide step-by-step instructions.
If you are not sure that you found a bug, please describe your problem at https://help.appveyor.com/discussions/problems.

**Comment by godrose** [comment]
@OsvaldoRino I put a link to a public repo inside the ticket. It contains build config in YAML format. What else do I need to provide?
https://ci.appveyor.com/project/LogoFX/logofx-client-mvvm-viewmodel-extensions
