### ISSUE TITLE
Git for Windows 2.6.3

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#369]
Discussion: http://help.appveyor.com/discussions/suggestions/788-git-for-windows-250

Download URL: https://github.com/git-for-windows/git/releases/tag/v2.5.0.windows.1

Update PATH variable to point to new installation dir.

`ssh.exe` is in `\usr\bin` now.

    git config --global core.autocrlf input

**Comment by vszakats** [comment]
Git for Windows is very much welcome.

Two issues with it so far:
- `curl.exe` (along with a bunch of other tools) is located in `\mingw64\bin`, so it'd be nice to add this directory to `PATH`.
- `patch.exe` is missing from the package. This may be a problem for some scripts.

**Comment by danilaml** [comment]
@vszakats 
`patch` is not missing now with 2.5.1: https://github.com/git-for-windows/git/releases/tag/v2.5.1.windows.1

**Comment by vszakats** [comment]
Nice, many thanks for the correction @danilaml! (not sure how I missed this)

**Comment by vszakats** [comment]
@FeodorFitsner Thanks for committing this in the latest update!

On a related note, the documentation don't seem to reflect the change, yet: http://www.appveyor.com/docs/installed-software

Did GfW replace the existing Git stack or is it an extra package? If the latter, where is it installed to?

**Comment by FeodorFitsner** [comment]
It replaces the existing 1.9.x Git. Will update the documentation, thanks for the catch.



- Feodor

**Comment by vszakats** [comment]
Thank you!
