### ISSUE TITLE
Missing *Microsoft.NET.Sdk*

### ISSUE THREAD

**Issue by Sholtee** [appveyor/ci#3693]
After the [14th of June image update](https://www.appveyor.com/updates/2021/06/14/ ) my [project](https://github.com/Sholtee/proxygen ) using [DocFX](https://dotnet.github.io/docfx ) stopped generating documentations. In the [build log](https://ci.appveyor.com/project/Sholtee/proxygen/branch/master/artifacts ) you can see that DocFX is complaining of the "missing Microsoft.NET.Sdk" which is interesting since all the other build tasks work like a charm (I suppose, DocFX requires an exact SDK version that had been removed).

Note that:
- until the next image update I could manage this issue by using the *Previous Visual Studio 2019* image
- I tried to update DocFX to the latest version

**Comment by FeodorFitsner** [comment]
Could you please give me a link to the exact location with error? I see all builds are green in the history and can't find an error.

**Comment by Sholtee** [comment]
In [this](https://ci.appveyor.com/api/buildjobs/ahirfwwo9tpjknrq/artifacts/log.txt ) log for instance. The history is green since DocFX handles this issue as a warning (see the log) so the build doesn't fail.

**Comment by Sholtee** [comment]
After reverting the image version [it](https://ci.appveyor.com/api/buildjobs/f3hkf8eekxrqyujr/artifacts/log.txt ) worked well again.

**Comment by FeodorFitsner** [comment]
It could be an issue with DocFX and the latest VS 2019 as `Microsoft.NET.Sdk` kind of project can be built with practically any version of .NET Core CLI. The strange thing that .NET Core was not changed bwteeen current and previous VS 2019 image.

**Comment by Sholtee** [comment]
is there any way to use specific VS 19 version (instead of "previous")?

**Comment by FeodorFitsner** [comment]
Nope, unfirtunately. Have you tried updating DocFX to the latest 2.58 version? 2.46 is quite old.

**Comment by Sholtee** [comment]
v2.58 seems to work :)

**Comment by FeodorFitsner** [comment]
Glad it worked! :)
