### ISSUE TITLE
There was an error while trying to complete the current operation. Please contact AppVeyor support.

### ISSUE THREAD

**Issue by watain666** [appveyor/ci#3695]
HI, Appveyor support team, I'm using my Github account to login,
But now I can't do anything, it will keep showing this alert saying

`There was an error while trying to complete the current operation. Please contact AppVeyor support.`

Am I do something wrong?

Please help me deal with this, thanks a lot!

<img width="996" alt="CleanShot 2021-07-30 at 04 04 39@2x" src="https://user-images.githubusercontent.com/19923168/127564257-5676dfaf-73b8-4369-a461-8dfe6ee1f140.png">

**Comment by FeodorFitsner** [comment]
Your account has been permanently disabled for breaking ToS, specifically bots and cryptomining are not allowed on AppVeyor platform.
