### ISSUE TITLE
Inno Setup 6.2.0

### ISSUE THREAD

**Issue by Jaex** [appveyor/ci#3698]
Hi, can we get Inno Setup 6.2.0 update please. Currently Inno Setup 6.1.2 is installed.

6.2.0 (2021-06-03) https://jrsoftware.org/files/is6-whatsnew.htm

**Comment by Jaex** [comment]
Recently we decided to update [Inno Dependency Installer](https://github.com/DomGries/InnoDependencyInstaller) script we were using. Script is now using new InnoSetup built in downloader feature to download dependencies, but this script requires InnoSetup 6.2.0 to function therefore our AppVeyor builds are failing to compile setup file.

Because we are relying on AppVeyor builds to generate setup files and upload them to GitHub and also for dev build testing, currently our workflow is broken. So hopefully you can update Inno Setup version.

**Comment by FeodorFitsner** [comment]
We'll update it during the next image update.

In the meantime you can install it during the build (takes few seconds) with the following PowerShell script:

```posh
Write-Host "Installing InnoSetup 6.2.0..." -ForegroundColor Cyan

$exePath = "$env:TEMP\innosetup-6.2.0.exe"

Write-Host "Downloading..."
(New-Object Net.WebClient).DownloadFile('https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe', $exePath)

Write-Host "Installing..."
cmd /c start /wait $exePath /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
Remove-Item $exePath

Write-Host "InnoSetup installed" -ForegroundColor Green
```
