### ISSUE TITLE
Visual Studio 2019 version 16.11

### ISSUE THREAD

**Issue by teo-tsirpanis** [appveyor/ci#3702]
Visual Studio 2019 version 16.11 was released, which means that version 16.10, the version installed in AppVeyor Windows images __is not supported__.

**Comment by FeodorFitsner** [comment]
VS 2019 version will be bumped during the next image udpate.

**Comment by teo-tsirpanis** [comment]
Thanks for updating it.

As a sidenote, until now, the Windows machine's maximum .NET SDK version was 5.0.3xx, while on Ubuntu it was 5.0.400; that discrepancy was breaking my builds for a while. Updating the .NET SDK was the reason I asked about Visual Studio. It would be helpful if you coordinate such changes among operating systems in the future (I know about manually installing the SDK myself but it would slow down the build).
