### ISSUE TITLE
Version 30.8 of macOS image seems to have problem with xcode-select

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#3704]
I'm not entirely sure what changed in the macOS image but my build started failing yesterday:
See the following build:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/job/a8k8oe8c3k45np5c
It seems there's a problem with `xcode-select` according to the error message and the following SO question:
https://stackoverflow.com/questions/60573595/npm-install-fails-on-node-gyp-rebuild-with-gyp-no-xcode-or-clt-version-detec
Code can be found here:
https://github.com/IsraelHikingMap/Site
The relevant build script that is running is the following:
https://github.com/IsraelHikingMap/Site/blob/master/Scripts/BuildAndPublishIOS.ps1

Let me know if there's any more info you need to check this.
I prefer not to remove and install xcode as part of the build as suggested in the SO solution.

**Comment by FeodorFitsner** [comment]
Looking into that, thanks for reporting.

**Comment by FeodorFitsner** [comment]
Can you please check if you can build on `macos-bigsur` image? At least on that image I'm not getting an error during `npm install`:  https://ci.appveyor.com/project/FeodorFitsner/site/builds/40593799

**Comment by HarelM** [comment]
Sure, I'll check in a few hours. Thanks a lot for the quick response!

**Comment by FeodorFitsner** [comment]
OK, adding this line should fix the build: https://github.com/FeodorFitsner/Site/blob/master/appveyor.yml#L65

We are working on incorporating that into images.

**Comment by HarelM** [comment]
Cool! Thanks!

**Comment by FeodorFitsner** [comment]
The fix has been applied to the images.

**Comment by HarelM** [comment]
Thanks!! I've re-run the failing build and now it passes. :-)
I'm always surprised that I'm the first to report an issue in all kind pf places, but I make a habit of reporting bugs when I see them because a lot of people do not report issue even when they see them.
As an open source project maintainer these reports are critical since I know I don't have the bandwidth to test all the possible scenarios.
I'm also surprised to see that you are still here @FeodorFitsner after all those year, appveyor is probably important to you :-) 
It's a pleasure to see how fast you response to issues and the level of professionalism in which you fix them.
Keep up the good work!!
P.S. Feel free to close this issue.

**Comment by FeodorFitsner** [comment]
Thank you for your kind words! :) Bugs/odds related to the freshly-released image are important, indeed.
