### ISSUE TITLE
Include Latest SDK/WDK Windows 10/11 in windows build VM image.

### ISSUE THREAD

**Issue by xavier2k6** [appveyor/ci#3708]
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
https://developer.microsoft.com/en-gb/windows/downloads/sdk-archive/
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

Windows 10 SDK version 2104 (10.0.20348.0)
https://go.microsoft.com/fwlink/?linkid=2164145

Windows 10 WDK version 2104 (10.0.20348.0)
https://go.microsoft.com/fwlink/?linkid=216414

Windows 11 SDK (22000.1)
https://go.microsoft.com/fwlink/?linkid=2166460

Windows 11 WDK (22000.1)
https://go.microsoft.com/fwlink/?linkid=2166289

**Comment by nefarius** [comment]
Well, these are outdated now, any chance to have the latest greatest integrated? 😇

**Comment by FeodorFitsner** [comment]
Yep, 10.0.22621.0 was recently deployed to "Visual Studio 2022" image: https://www.appveyor.com/updates/2022/06/06/

**Comment by nefarius** [comment]
Nice, thanks for the update! Any chance on refreshing the VS 2019 images as well? Some solutions still don't play well with VS 2022.

**Comment by FeodorFitsner** [comment]
You mean adding 10.0.22621.0 to VS 2019 as well?

**Comment by nefarius** [comment]
> You mean adding 10.0.22621.0 to VS 2019 as well?

Correct 👍

**Comment by nefarius** [comment]
> You mean adding 10.0.22621.0 to VS 2019 as well?

Actually, you might scratch that, seems like there are **still** known bugs with that WDK version and VS 2019 *sigh*
