### ISSUE TITLE
Visual Studio 2013 license expired

### ISSUE THREAD

**Issue by Margen67** [appveyor/ci#3709]
https://ci.appveyor.com/project/Margen67/tf2-base-with-bots/builds/40645586/job/dpqkk5vci5f4di2d#L42:
`The license for Visual Studio has expired.`

**Comment by FeodorFitsner** [comment]
Should be fixed now.

**Comment by Margen67** [comment]
> 
> 
> Should be fixed now.

This still occurs with the `Visual Studio 2015` image.

**Comment by FeodorFitsner** [comment]
Looking into that...

**Comment by FeodorFitsner** [comment]
OK, it should be fixed.
