### ISSUE TITLE
Include Boost 1.74.0, 1.75.0 & 1.76.0 in Windows build VM's (Visual Studio 2019)

### ISSUE THREAD

**Issue by xavier2k6** [appveyor/ci#3711]
Can you include Boost 1.74.0, 1.75.0 & 1.76.0 in Windows build VM's (Visual Studio 2019)

https://www.boost.org/
https://www.boost.org/users/history/version_1_74_0.html
https://www.boost.org/users/history/version_1_75_0.html
https://www.boost.org/users/history/version_1_76_0.html
https://github.com/boostorg/boost/releases

**Comment by FeodorFitsner** [comment]
Why would you need *every* version of boost?

**Comment by xavier2k6** [comment]
Not every version is exactly required......1.75 is though as a different repo/dependency is looking to change master branch to 1.75 but it isn't available.

I didn't think adding the other two would be an issue?? since there's 5 versions available for msvc2017 & 7 available for msvc2013 images.

**Comment by FeodorFitsner** [comment]
You can actually download and unpack missing Boost library during the build, from here: https://sourceforge.net/projects/boost/files/boost-binaries/1.75.0/
Look how it's done for 1.73, for example: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_boost_1.73.0_vs2019.ps1

We'd avoid installing any version to the image as it adds to its size substantially.

**Comment by xavier2k6** [comment]
@FeodorFitsner Thanks for the tip.

Under MSVC2019 now there's Boost 1.73.0 & 1.77.0, are those two to remain or will 1.73.0 be removed in favor of 1.77.0 (latest)

I'm just wondering what the plan is for when let's say Boost 1.78.0 gets released in December.....will it take the place of 1.77.0 etc. etc.

This is the release schedule of Boost:
https://github.com/boostorg/wiki/wiki/Releases%3A-Schedule#release-dates

Thank you for taking the time to answer my queries.

**Comment by FeodorFitsner** [comment]
Ideally, we'd love to keep two most recent releases, like 1.77.0 and 1.76.0 and then 1.78.0 and 1.77.0 when 78 is out. Would that work?

**Comment by xavier2k6** [comment]
@FeodorFitsner Is there any plan to drop/update the boost versions available on MSVC2013/15/17 Images?

Does the same https://github.com/appveyor/ci/issues/3711#issuecomment-913861164 apply to these images?

**Comment by FeodorFitsner** [comment]
No, we are not going to change boost on those images.

**Comment by xavier2k6** [comment]
@FeodorFitsner Ok, I'm going to close this now. Thank you so much for the info & help.
