### ISSUE TITLE
Ubuntu1804 x86 broken after the September update

### ISSUE THREAD

**Issue by asfernandes** [appveyor/ci#3728]
x86 build of https://github.com/FirebirdSQL/ stopped working in September giving error with VirtualBox package: https://ci.appveyor.com/project/FirebirdSQL/firebird/builds/40726862/job/14hoqc5ik9a4oyj6

After change to "Previous Ubuntu1804" it works again: https://ci.appveyor.com/project/FirebirdSQL/firebird/builds/40732534

**Comment by FeodorFitsner** [comment]
In the latest Ubuntu image update priorities for GCC versions have been changed: https://github.com/appveyor/build-images/blob/master/scripts/Ubuntu/common.sh#L1604-L1623

[Increasing the priority of GCC 7](https://github.com/FeodorFitsner/firebird/blob/master/appveyor.yml#L30) makes the build [working again](https://ci.appveyor.com/project/FeodorFitsner/firebird/builds/40749980).
