### ISSUE TITLE
Support multi-code ANSI codes

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#373]
Discussion: http://help.appveyor.com/discussions/suggestions/197-support-ansi-color-codes

**Comment by nicolas-grekas** [comment]
Two issues in fact:

- Only single codes are supported ( \e[1m ). Multiple codes sequences are not handled ( \e[1;2;3m ). See e.g. https://ci.appveyor.com/project/fabpot/symfony/build/1.0.72

- sometimes, colors are not correctly reseted, several \e[0m are required to reset several color settings, but only one should required to reset all of them, see e.g.:
https://ci.appveyor.com/project/fabpot/symfony/build/1.0.74#L1256

**Comment by konserw** [comment]
Hi,
Could you take a look at line 888 of: [my build](https://ci.appveyor.com/project/konserw/cucumber-cpp/build/app-ci-80/job/cvs5u605f8tmfcxj)
I managed to get cucumber colored output in appveyor with pretty ugly hack :) but as you can see it's not perfect, as there are some codes printed, ex: [32m

BTW. hack i've done for cucumber, if anyone comes here looking for it:
```
- ps: (Get-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '\ST\DERR.puts %', '#nope' | Set-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb
- ps: (Get-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '    Cucumber::', '#nope'     | Set-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb
- ps: (Get-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '^Cucumber::', '#nope' |     Set-Content C:\Ruby200\lib\ruby\gems\2.0.0\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb
- ps: (Get-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '\ST\DERR.puts %', '#nope' | Set-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb 
- ps: (Get-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '    Cucumber::', '#nope'     | Set-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb
- ps: (Get-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb) -replace '^Cucumber::', '#nope' |     Set-Content C:\Ruby193\lib\ruby\gems\1.9.3\gems\cucumber-1.3.20\lib\cucumber\formatter\ansicolor.rb
```

**Comment by FeodorFitsner** [comment]
AppVeyor update improving ANSI colors support in build console has been deployed.

**Comment by gucong3000** [comment]
Which level are AppVeyor support? basic, 256 or full color?
