### ISSUE TITLE
Qt 6.2.0

### ISSUE THREAD

**Issue by xavier2k6** [appveyor/ci#3738]
Qt 6.2.0 is scheduled to be released on 30th September....will this make it into `vs2019-image-update-2021-10-01`??

https://wiki.qt.io/Qt_6.2_Release#Qt_6.2_release_plan

https://lists.qt-project.org/pipermail/releasing/2021-September/002893.html

https://download.qt.io/official_releases/qt/

**Comment by FeodorFitsner** [comment]
Sure, why not, if it's released tomorrow. I guess we could remove 6.0 then and keep 6.1.3 and 6.2.0 only, right?

**Comment by xavier2k6** [comment]
It's available to download now: https://download.qt.io/official_releases/qt/6.2/6.2.0/

https://www.qt.io/blog/qt-6.2-lts-released

>we could remove 6.0 then and keep 6.1.3 and 6.2.0 only, right?

Entirely your choice.

`Qt 6.0.4` is the last release for the Qt 6.0 Series. (No future updates planned)
`Qt 6.1.3` is the last release for the Qt 6.1 Series. (No future updates planned)
`Qt 6.2.0` is the first release in the Qt 6.2 **LTS** Series.
