### ISSUE TITLE
NuGet task in Visual Studio 2015 image does not restore solution packages

### ISSUE THREAD

**Issue by uhaciogullari** [appveyor/ci#374]
It probably occurs in the images that use NuGet v3. Check this build [log](https://ci.appveyor.com/project/uhaciogullari/simplemvcsitemap/build/1.0.59), it doesn't install the [solution packages](https://github.com/uhaciogullari/SimpleMvcSitemap/blob/master/src/.nuget/packages.config). I resolved it by using the older binary that's generated with package restore. It's a NuGet bug but it may cause some trouble for the people using AppVeyor.

**Comment by FeodorFitsner** [comment]
You can restore them with nuget v3 like that:

```
before_build:
  - nuget restore src\SimpleMvcSitemap.sln
  - nuget restore src\.nuget\packages.config -PackagesDirectory src\packages
```

or, alternatively just override nuget.exe with 2.8.x one:

```
before_build:
  - ps: (New-Object Net.WebClient).DownloadFile('https://www.nuget.org/nuget.exe', 'C:\Tools\NuGet\NuGet.exe')
  - nuget restore src\SimpleMvcSitemap.sln
```
