### ISSUE TITLE
Dependency problems prevent configuration

### ISSUE THREAD

**Issue by tomcass240** [appveyor/ci#3740]
When trying to install from the .deb package I get the following dependency problems on Debian 11.

> dpkg: dependency problems prevent configuration of sdrangel:
>  sdrangel depends on libopencv-core4.2 (>= 4.2.0+dfsg); however:
>   Package libopencv-core4.2 is not installed.
>  sdrangel depends on libopencv-imgcodecs4.2 (>= 4.2.0+dfsg); however:
>   Package libopencv-imgcodecs4.2 is not installed.
>  sdrangel depends on libopencv-imgproc4.2 (>= 4.2.0+dfsg); however:
>   Package libopencv-imgproc4.2 is not installed.
>  sdrangel depends on libopencv-videoio4.2 (>= 4.2.0+dfsg); however:
>   Package libopencv-videoio4.2 is not installed.
>  sdrangel depends on libgl1-mesa-glx; however:
>   Package libgl1-mesa-glx is not installed.
> 
>

**Comment by FeodorFitsner** [comment]
I'm sorry, how is this related to AppVeyor?

**Comment by tomcass240** [comment]
Not sure how this got here I've never heard of AppVeyor before. This comment was supposed to be posted to a project called SDRAngel. I have absolutely no idea how my comment has ended up on a totally different project that I've never visited before. My apologies.

**Comment by FeodorFitsner** [comment]
No worries!
