### ISSUE TITLE
.Net Core 6 support

### ISSUE THREAD

**Issue by Giorgi** [appveyor/ci#3745]
.Net Core 6 Release Candidate is already available and it will RTM in the first week of November so are there any plans to support it in near future?

**Comment by FeodorFitsner** [comment]
We'll deploy it when it's RTM'd.

In the meantime .NET 6 RC could be installed during the build with the following two-liner:

```posh
Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
& $env:temp\dotnet-install.ps1 -Architecture x64 -Version '6.0.100-rc.2.21505.57' -InstallDir "$env:ProgramFiles\dotnet"
```

**Comment by SimonCropp** [comment]
it has RTM’d 🥳

**Comment by FeodorFitsner** [comment]
Yep, working on `Visual Studio 2022` image.

**Comment by SimonCropp** [comment]
awesome. thanks

**Comment by FeodorFitsner** [comment]
“Visual Studio 2022” image is now available: https://www.appveyor.com/blog/2021/11/10/visual-studio-2022-image/

**Comment by SimonCropp** [comment]
@FeodorFitsner thanks so much
