### ISSUE TITLE
Provide VS 16.11.2 image

### ISSUE THREAD

**Issue by rseanhall** [appveyor/ci#3748]
Since VS 2019 16.11.3, WiX no longer builds on the `Visual Studio 2019` image. With the new image update, we can no longer fallback to the `Previous Visual Studio 2019` image for a working build. See https://help.appveyor.com/discussions/problems/30452-build-broken-after-20211002-update-to-visual-studio-2019-image and https://developercommunity.visualstudio.com/t/libucrtlibstreamobj-error-lnk2001-unresolved-exter/1544787.

Please provide the ability to specify the 2021/09/04 version of the `Visual Studio 2019` image until we can build with an updated Visual Studio image that doesn't have that bug.

**Comment by FeodorFitsner** [comment]
Oh, sorry about that. So, you need like "Previous Previous Visual Studio 2019" image then? Could you send the link to your project please?

PS: Microsoft team can obviously create an account and do a repro build. Wondering what's wrong with the image. Neither VS 2019 installation script, nor WiX setup changed for a while. Have you tried doing the repro while in RDP to a build worker?

**Comment by rseanhall** [comment]
It is a legitimate bug in Visual Studio, I think we're past needing them to be able to reproduce it. Right now, yes we need a "Previous Previous Visual Studio 2019" image but that might keep on sliding depending on when they actually fix the bug so it's specifically the 2021/09/04 image we would want to use.

We feel bad asking for support on this since we're using the free tier, so thanks for anything that you can do. Our project is https://ci.appveyor.com/project/wixtoolset.

**Comment by FeodorFitsner** [comment]
No problem, we've added a new `vs2019-16-11-2` image which is available just to `wixtoolset` account. Give it a try and let me know how it worked.

**Comment by rseanhall** [comment]
Thanks! The build has already passed the point where it fails on the newer images, so this looks like it was exactly what we needed. https://ci.appveyor.com/project/wixtoolset/wix4/builds/41398567

**Comment by FeodorFitsner** [comment]
Nice! Let me know when VS fixed the issue and the image is no longer needed.

**Comment by rseanhall** [comment]
@FeodorFitsner Microsoft diagnosed the issue and we are able to work around it, so we are able to use the latest `Visual Studio 2019` image. We don't need the special image any more.

The problem was that we were statically linking an x64 and ARM64 .dll with the v141 toolset and Win11 SDK. This is why that first image broke us - the Win11 SDK was installed on the image. Microsoft still hasn't fixed the bug, so someone could still theoretically run into this issue. It was probably unusual that we were building with v141 with VS2019 though, since v141 is the C++ toolset for VS2017.

**Comment by FeodorFitsner** [comment]
OK, thanks for the update! We are disabling that image then.
