### ISSUE TITLE
Appveyor OnPremise: Pull request webhook from gitea fails with bad request

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [appveyor/ci#3750]
### Environment Information

AppVeyor: `v7.0.2942`
OS: `Windows Server 2019`

Gitea:  `gitea-1.15.6-windows-4.0-amd64.exe`
OS: `Windows Server 2016`
GitVersion: `2.33.1`
DB: `SQLite`

### Issue Description

I have a on-prem gitea instance connected with on-prem AppVeyor server.
Problem occurs when I create a pull request for one branch to another branch of the same or different repo.
The AppVeyor server is then responding with bad request (400) and message:

`"The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')"`

Other webhooks, e.g. for push, are working fine.

### Gitea Log

https://gist.github.com/DoLearnWhileAlive/a971df255fa9e4b7fbf65a22fe5a639e

### Screenshot Gitea

![grafik](https://user-images.githubusercontent.com/64268800/140075719-36b758d1-18f2-4fad-96f8-c68e1203fc3f.png)

**Comment by FeodorFitsner** [comment]
Could you give me the response of this API call (details of head commit):

    GET https://giteaserver.local/api/v1/repos/devgroup/test/git/commits/dbd6120dd2798e167702771dcc133856871d9ff9

**Comment by DoLearnWhileAlive** [comment]
The 'created' timestamps seems not correct.

```
{
  "url": "https://giteaserver.local/api/v1/repos/devgroup/test/git/commits/dbd6120dd2798e167702771dcc133856871d9ff9",
  "sha": "dbd6120dd2798e167702771dcc133856871d9ff9",
  "created": "0001-01-01T00:00:00Z",
  "html_url": "https://giteaserver.local/devgroup/test/commit/dbd6120dd2798e167702771dcc133856871d9ff9",
  "commit": {
    "url": "https://giteaserver.local/api/v1/repos/devgroup/test/git/commits/dbd6120dd2798e167702771dcc133856871d9ff9",
    "author": {
      "name": "User Name",
      "email": "user.name@company.com",
      "date": "2021-11-03T14:08:28+01:00"
    },
    "committer": {
      "name": "User Name",
      "email": "user.name@company.com",
      "date": "2021-11-03T14:08:28+01:00"
    },
    "message": "new file\n\nnew file\n",
    "tree": {
      "url": "https://giteaserver.local/api/v1/repos/devgroup/test/git/trees/dbd6120dd2798e167702771dcc133856871d9ff9",
      "sha": "dbd6120dd2798e167702771dcc133856871d9ff9",
      "created": "0001-01-01T00:00:00Z"
    }
  },
  "author": {
    "id": 9,
    "login": "user1",
    "full_name": "User Name",
    "email": "user.name@company.com",
    "avatar_url": "https://giteaserver.local/user/avatar/user1/-1",
    "language": "",
    "is_admin": false,
    "last_login": "0001-01-01T00:00:00Z",
    "created": "2018-06-13T17:46:49+02:00",
    "restricted": false,
    "active": false,
    "prohibit_login": false,
    "location": "",
    "website": "",
    "description": "",
    "visibility": "public",
    "followers_count": 0,
    "following_count": 0,
    "starred_repos_count": 2,
    "username": "user1"
  },
  "committer": {
    "id": 9,
    "login": "user1",
    "full_name": "User Name",
    "email": "user.name@company.com",
    "avatar_url": "https://giteaserver.local/user/avatar/user1/-1",
    "language": "",
    "is_admin": false,
    "last_login": "0001-01-01T00:00:00Z",
    "created": "2018-06-13T17:46:49+02:00",
    "restricted": false,
    "active": false,
    "prohibit_login": false,
    "location": "",
    "website": "",
    "description": "",
    "visibility": "public",
    "followers_count": 0,
    "following_count": 0,
    "starred_repos_count": 2,
    "username": "user1"
  },
  "parents": [
    {
      "url": "https://giteaserver.local/api/v1/repos/devgroup/test/git/commits/9575edc645bdcd12517c85476fff43e978c259ea",
      "sha": "9575edc645bdcd12517c85476fff43e978c259ea",
      "created": "0001-01-01T00:00:00Z"
    }
  ],
  "files": [
    {
      "filename": "test.md"
    }
  ]
}
```

**Comment by DoLearnWhileAlive** [comment]
Just compared with test repo on Gitea demo site https://try.gitea.io.

```
GET https://try.gitea.io/api/v1/repos/DoLearnWhileAlive/TestGiteaAppveyor/commits?sha=3f150d39b9
```

Also here the 'created' timestamps are '0001-01-01T00:00:00Z'. So not specific to my gitea instance. 
Sadly I cannot repro gitea pull requests on https://ci.appveyor.com and https://try.gitea.io.

**Comment by FeodorFitsner** [comment]
I'm looking at Gitea implementation in AppVeyor. For commit details it's looking for `commit/timestamp` which is absent in your result (could be because we were targeting older versions of Gitea). Even if we fix it by additionnally looking for `created` it still looks invalid: `0001-01-01T00:00:00Z`. I see `commit/author/date` contains a usable date, but is it correct?

**Comment by FeodorFitsner** [comment]
Would you mind filing an issue in Gitea repo or ask on their forums about commit timestamp?

**Comment by DoLearnWhileAlive** [comment]
> 
> 
> I'm looking at Gitea implementation in AppVeyor. For commit details it's looking for `commit/timestamp` which is absent in your result (could be because we were targeting older versions of Gitea). Even if we fix it by additionnally looking for `created` it still looks invalid: `0001-01-01T00:00:00Z`. I see `commit/author/date` contains a usable date, but is it correct?

Timestamp in `commit/author/date` is correct.



> 
> 
> Would you mind filing an issue in Gitea repo or ask on their forums about commit timestamp?

Sure, no problem. I'll open an issue tomorrow.

**Comment by FeodorFitsner** [comment]
Thanks! Once clarified we'll release a quick update.

**Comment by DoLearnWhileAlive** [comment]
Gitea issue created: https://github.com/go-gitea/gitea/issues/17543

**Comment by DoLearnWhileAlive** [comment]
I've tried to find out if `commit/timestamp` was removed some time ago from `api/v1/repos/{owner}/{repo}/commits`.
However it seems `commit\timestamp` was never provided by `api/v1/repos/{owner}/{repo}/commits`.

According to gitea swagger template (https://github.com/go-gitea/gitea/blob/main/templates/swagger/v1_json.tmpl) `api/v1/repos/{owner}/{repo}/commits` responsis with:
- `#/responses/CommitList` containing:
  - `#/definitions/Commit` containing:
    - `#/definitions/RepoCommit`

And in `#/definitions/RepoCommit` I found in no gitea release a property `timestamp`.

Only for `api/v1/repos/{owner}/{repo}/branches` I found `commit/timestamp`. Which is defined as `#/definitions/PayloadCommit` in [v1_json.tmpl](https://github.com/go-gitea/gitea/blob/main/templates/swagger/v1_json.tmpl).

So are you sure this is the api query causing the issue:
```
GET https://try.gitea.io/api/v1/repos/DoLearnWhileAlive/TestGiteaAppveyor/commits?sha=3f150d39b9
```

**Comment by FeodorFitsner** [comment]
Looking at the fix for https://github.com/go-gitea/gitea/issues/17543 I assume we can safely use `commit/committer/date` for commit date?

**Comment by DoLearnWhileAlive** [comment]
Sure that's a valid commit date and also provided by older Gitea versions. `created` sounds more meaningful for me, but it's the same value behind.

**Comment by FeodorFitsner** [comment]
Alright, please update to 7.0.3111 which contains the fix for Gitea commit timestamp: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.3111/appveyor-server-7.0.3111-win-x64.msi

Let me know how it worked.

**Comment by DoLearnWhileAlive** [comment]
The update to appveyor-server version 7.0.3111 fixes the issue.
Many thanks for the prompt reaction and fix. I really appreciate it. :+1:

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!
