### ISSUE TITLE
WiX Toolset in Visual Studio 2022 image

### ISSUE THREAD

**Issue by barnson** [appveyor/ci#3754]
WiX v3.11 and v3.14 both support running from Visual Studio 2022's MSBuild. Integration into Visual Studio is not yet available (https://github.com/wixtoolset/issues/issues/6493) but that integration is only used for editing/building inside Visual Studio (interactively).

**Comment by FeodorFitsner** [comment]
Oh, that's good to know.

Fortunately, WiX Toolset could be easily installed during the build with a few lines:

```posh
$exePath = "$env:TEMP\wix311.exe"
(New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe', $exePath)
cmd /c start /wait "$exePath" /q
```

**Comment by cinderblocks** [comment]
I attempted to install Wix in a VS 2022 image using these commands, but it seems to hang indefinately using the install.
```
(New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe', 'C:\wix311.exe')
cmd.exe --% /c start /wait 'C:\wix311.exe' /q
```
