### ISSUE TITLE
Will Visual Studio 2022 image eventually use Qt binaries built with MSVC2022?

### ISSUE THREAD

**Issue by xavier2k6** [appveyor/ci#3755]
Currently (I know this was an initial release) if running the `Visual Studio 2022 image` & using let's say the [Qt 5.15.2 binaries](https://www.appveyor.com/docs/windows-images-software/#qt), it appears that `C:\Qt\5.15.2\msvc2019_64` has to be used, in a future release will these be built with MSVC2022 & reside somewhere like `C:\Qt\5.15.2\msvc2022_64` for the `Visual Studio 2022 image`?

**Comment by FeodorFitsner** [comment]
It depends on Qt releases. If they start publishing VS 2022 binaries we'll definitely include them to the image.

**Comment by xavier2k6** [comment]
@FeodorFitsner Thank you!
