### ISSUE TITLE
Documentation error with Qt on Ubuntu2004 image

### ISSUE THREAD

**Issue by GenericMadScientist** [appveyor/ci#3756]
The most recent update to the Ubuntu2004 image replaced Qt 6.1.2 with Qt 6.1.3 and added Qt 6.2.1. This can be confirmed with `ls $HOME/Qt`. However, the update notes do not mention this and the list of pre-installed software has not been updated to reflect this change.

**Comment by FeodorFitsner** [comment]
Good catch! The docs have been updated: https://www.appveyor.com/docs/linux-images-software/#qt
