### ISSUE TITLE
Qt6 is missing the serialport module

### ISSUE THREAD

**Issue by tumic0** [appveyor/ci#3761]
The msvc2019 64-bit build of Qt 6.2.2 is missing the serialport module. In addition to direct serial port access from the applications, it is also required by the Qt NMEA positioning plugin.

**Comment by FeodorFitsner** [comment]
Will add those during the next update.

In the meantime you can easily install any missing addons with the following PS script:

```posh
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_qt_module.ps1'))
Install-QtComponent -Version "6.2.2" -Name "addons.qtserialport" -Path C:\Qt -ExcludeDocs -ExcludeExamples
Install-QtComponent -Version "6.2.2" -Name "addons.qtserialport.win64_msvc2019_64" -Path C:\Qt -ExcludeDocs -ExcludeExamples
ConfigureQtVersion C:\Qt "6.2.2"
```
