### ISSUE TITLE
Install the Qt 6.2 ARM64 TP on Windows images

### ISSUE THREAD

**Issue by cgutman** [appveyor/ci#3762]
Qt 6.2 has preview-quality support for Windows on ARM64. Even though it's just a preview in Qt 6.2, having it available on AppVeyor images will allow us to ensure there are no build breaks for our Qt projects on Windows ARM64.

It should just be as simple as checking the box in the Qt Maintenance Tool:
<img width="950" alt="Screen Shot 2021-12-06 at 10 47 52 PM" src="https://user-images.githubusercontent.com/2695644/144968517-bb7979f6-f8d5-485c-bef6-36be6c029d7a.png">

**Comment by FeodorFitsner** [comment]
We'll add them during the next image update.

For now you may use the following script to install missing libs:

```posh
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_qt_module.ps1'))
@(
	"addons.qtactiveqt.win64_msvc2019_arm64"
	"addons.qtcharts.win64_msvc2019_arm64"
	# ... other components
) | ForEach-Object {
	Install-QtComponent -Version "6.2.2" -Name $_ -Path C:\Qt -ExcludeDocs -ExcludeExamples
}
ConfigureQtVersion C:\Qt "6.2.2"
```
