### ISSUE TITLE
Coverity Scan 2021.12

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3773]
Original request: https://help.appveyor.com/discussions/problems/31211-coverity-scan-update

**Comment by Flamefire** [comment]
Where exactly is this deployed? Running the "Visual Studio 2017" image I still get Coverity Scan 2019.03 which fails the builds.

Could the updated tool be deployed to all images? Especially for testing with different VS versions one needs the "older" images.

**Comment by Flamefire** [comment]
@FeodorFitsner Any info?

**Comment by FeodorFitsner** [comment]
We'll look into that though I can't give you an ETA.

**Comment by Flamefire** [comment]
Reminder that this is still unanswered. 

> @FeodorFitsner closed this as [completed](https://github.com/appveyor/ci/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [on 1 Apr](https://github.com/appveyor/ci/issues/3773#event-6353921865)

This looks like the updated tool has been deployed? Is that the case and if so to which image(s)?

**Comment by FeodorFitsner** [comment]
It was added to "Visual Studio 2019" and "Visual Studio 2022" images.
