### ISSUE TITLE
Meson 0.61.1

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#3774]
Meson [0.61.1](https://github.com/mesonbuild/meson/releases/tag/0.61.1) was released today!

0.61.x [release notes](https://mesonbuild.com/Release-notes-for-0-61-0.html).

**Comment by eli-schwartz** [comment]
I notice this was only closed yesterday. By now, 0.61.4 was also released -- and so was the next feature release, 0.62.0

**Comment by FeodorFitsner** [comment]
Created a new issue: https://github.com/appveyor/ci/issues/3793
