### ISSUE TITLE
Appveyor OnPremise: running 'New build' fails for Gitea repository

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [appveyor/ci#3779]
### Environment Information

AppVeyor: `v7.0.3134`
OS: `Windows Server 2019`

Gitea:  `gitea-1.16.1-windows-4.0-amd64.exe`
OS: `Windows Server 2016`
Git: `2.35.1`
DB: `SQLite`

### Issue Description

I have an on-prem gitea instance connected with on-prem AppVeyor server.
When pressing **New build** in the AppVeyor Web UI, AppVeyor throughs following error:

![grafik](https://user-images.githubusercontent.com/64268800/153623780-de2afa87-6746-49f6-91ed-c845be698214.png)

Seems related to old issue #3750.
Problem does not occur with **Re-build commit**.

**Comment by FeodorFitsner** [comment]
As with that issue could you please give me the response of the following Gitea API call:

    GET https://{giteaserver}/api/v1/repos/{owner}/{repo}/branches/{branch}

**Comment by DoLearnWhileAlive** [comment]
Here you are:
```
{
  "name": "dev",
  "commit": {
    "id": "c6f1373681329de16177f32f36d83b7317c5ffe8",
    "message": "„appveyor.yml“ changed\n",
    "url": "https://giteaserver.local/test-group/test/commit/c6f1373681329de16177f32f36d83b7317c5ffe8",
    "author": {
      "name": "Test User",
      "email": "user.name@company.com",
      "username": "testuser"
    },
    "committer": {
      "name": "Test User",
      "email": "user.name@company.com",
      "username": "testuser"
    },
    "verification": {
      "verified": false,
      "reason": "gpg.error.not_signed_commit",
      "signature": "",
      "signer": null,
      "payload": ""
    },
    "timestamp": "2022-01-04T12:59:56+01:00",
    "added": null,
    "removed": null,
    "modified": null
  },
  "protected": false,
  "required_approvals": 0,
  "enable_status_check": false,
  "status_check_contexts": [],
  "user_can_push": true,
  "user_can_merge": true,
  "effective_branch_protection_name": ""
}
```

**Comment by FeodorFitsner** [comment]
Thank you! This is the version with a fix: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.3150/appveyor-server-7.0.3150-win-x64.msi

Let me know how it worked.

**Comment by DoLearnWhileAlive** [comment]
Error is fixed, but it's not using the correct default branch. It's building last commit from 'main' branch instead of the default branch 'dev'.

**Comment by DoLearnWhileAlive** [comment]
Ok, found out that AppVeyor is not recognizing default branch changes after repository was added to AppVeyor. Manual change of default branch setting in the AppVeyor repository is required.
So problem is fixed completely. Thanks again!
