### ISSUE TITLE
Update Visual Studio 2022 to 17.1

### ISSUE THREAD

**Issue by teo-tsirpanis** [appveyor/ci#3781]
[It released yesterday.](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-1-is-now-available/)

**Comment by FeodorFitsner** [comment]
Thanks for letting know - we are working on the update!

**Comment by FeodorFitsner** [comment]
The image has been update: https://www.appveyor.com/updates/2022/02/19/

**Comment by teo-tsirpanis** [comment]
That was quick, thank you very much!
