### ISSUE TITLE
appveyor.yml file being ignored

### ISSUE THREAD

**Issue by clay-lenhart-jelly** [appveyor/ci#3788]
https://ci.appveyor.com/project/LatitudeDevelopers/bt-dmh-ppc-engine-eng-dotnet

We want to control msbuild b/c we use a private nuget server, so we have the appveyor.yml file to specify how to build it.  Recently (today) AppVeyor trys to run msbuild straight after the git checkout.  Last time we changed the yml file was Jan 5th.

We have another project that is building again (started yesterday).  The yml file tells it to not to.  So thinking this is a bug on AppVeyor's side.

**Comment by FeodorFitsner** [comment]
Make sure AppVeyor is still authorized to access GitHub, on "New project" page or "Account -> Authorizations". On "New project" page you should be able to see the list of repos.

**Comment by clay-lenhart-jelly** [comment]
Thanks @FeodorFitsner.  This is likely it.  There was a tightening on security of our github organisation.
