### ISSUE TITLE
Setting Python PATH to `C:\Python310` yields Python 2.7

### ISSUE THREAD

**Issue by paulmueller** [appveyor/ci#3789]
If I want to use Python 3.10, I get Python 2.7:

https://www.appveyor.com/docs/windows-images-software/#python

There it also reads for Python 2.7:
```
Python 2.7.15 x86 (C:\Python310 - default in PATH)
```

Is this a typo?

Example build: https://ci.appveyor.com/project/paulmueller/dcor-aid/builds/42965733#L35

**Comment by FeodorFitsner** [comment]
Python 3.10 is available on `Visual Studio 2019` and `Visual Studio 2022` images only. Add this to your `appveyor.yml`:

```yaml
image: Visual Studio 2019
```

**Comment by paulmueller** [comment]
Thanks, that solved the issue for me. But in any case, the mentioned entry in the docs is still strange:

Python **2.7.15** x86 (**C:\Python310** - default in PATH)
