### ISSUE TITLE
How can I configure the following MSBuild step?

### ISSUE THREAD

**Issue by bguiz** [appveyor/ci#379]
In the web user interface, under Settings -> MSBuild -> Configuration,
I have entered "Release"

In addition to this I would also like to specify an outDir, as in the following command:

```
msbuild UniversalApp.Windows.jsproj /p:configuration=release;outDir="dist"
```

..but I am not sure where to stick this in this settings page. Where does it go?

**Comment by FeodorFitsner** [comment]
I'd switch to "Script" mode then and provide your own build command.

Alternatively, you can define `OutDir` on environment variables. MSBuild should pick up environment variable instead of `p` argument.

**Comment by bguiz** [comment]
```ps
$env:OutDir="dist"
```

That does the trick?

**Comment by FeodorFitsner** [comment]
Sure, or you can just add environment variable on "Environment" tab.

**Comment by bguiz** [comment]
Thanks!
