### ISSUE TITLE
.NET 6 tests require NUnit.Console 3.15.0 or later

### ISSUE THREAD

**Issue by yfdyh000** [appveyor/ci#3790]
See the https://github.com/nunit/nunit-console/issues/1101, https://github.com/nunit/nunit-console/issues/1123 fixed this issue.

Appveyor still supply the NUnit.Console 3.13.0 by default.
[error](https://ci.appveyor.com/project/yfdyh000/imewlconverter/builds/42990423/job/9lsh6wimr4oqrqq5):
`NUnit Console Runner 3.13.0 (.NET 2.0)`
`----> Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

A workaround based [the post](https://help.appveyor.com/discussions/questions/47366-nunit-console-runner-version):
```
      before_build:
        - ps: |
           # nunit
           $nunitPath = "$env:SYSTEMDRIVE\Tools\NUnit3"
           Remove-Item $nunitPath -Recurse -Force
           $zipPath = "$env:TEMP\NUnit.Console-3.15.0.zip"
           $tempPath = "$env:TEMP\NUnit.Console"
           (New-Object Net.WebClient).DownloadFile('https://github.com/nunit/nunit-console/releases/download/3.15.0/NUnit.Console-3.15.0.zip', $zipPath)
           7z x $zipPath -y -o"$tempPath" | Out-Null
           [IO.Directory]::Move("$tempPath\bin\net6.0", $nunitPath)
           # logger
           $zipPath = "$env:TEMP\Appveyor.NUnit3Logger.zip"
           (New-Object Net.WebClient).DownloadFile('https://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip', $zipPath)
           7z x $zipPath -y -o"$nunitPath\addins" | Out-Null
           Move-Item "$nunitPath\addins\appveyor.addins" "$nunitPath\appveyor.addins"
```
Then,
```
      test_script:
        - C:\Tools\NUnit3\nunit3-console "C:\path\name.dll" -result=myresults.xml
```
however, appends the `;format=AppVeyor` will be thrown `Unknown result format: AppVeyor` for now.

**Comment by FeodorFitsner** [comment]
Will try it during the next image update.

Wondering why are you not using `dotnet test ...` to test .NET Core projects?

**Comment by yfdyh000** [comment]
> Wondering why are you not using `dotnet test ...` to test .NET Core projects?

Just try to fix the CI for the project, it originally worked. I'm not sure the difference between the two.
