### ISSUE TITLE
AppVeyor Server: Add setting 'Enable secure variables in all Pull Requests' for Gitea repos

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [appveyor/ci#3791]
## Problem

Currently it's not possible to allow usage of secure variables in pull requests for public or private **Gitea** repositories.

## Proposal

1. Add setting `Enable secure variables in all Pull Requests` for **private** Gitea repositories
2. Add setting `Enable secure variables in Pull Requests from the same repository only` for **public** Gitea repositories

**Comment by FeodorFitsner** [comment]
Here you are: https://appveyordownloads.blob.core.windows.net/appveyor/7.0.3212/appveyor-server-7.0.3212-win-x64.msi - let me know how that worked.

**Comment by DoLearnWhileAlive** [comment]
Works like a charm! Many many thanks. Is that a version you will also release on the AppVeyor website?

**Comment by FeodorFitsner** [comment]
Yep, released! :)
