### ISSUE TITLE
Go stack version doesn't appear to be respected

### ISSUE THREAD

**Issue by thrasher-** [appveyor/ci#3794]
On the VS 2019 Windows image, when setting the stack to `go 1.17.8` it appears that the default Go image version used is instead (1.18)

**Comment by FeodorFitsner** [comment]
I'm sorry to say, but `stack` setting is not currently supported on Windows images. To select Go 1.17.x for your build you could use:

```yaml
install:
- set PATH=C:\go117\bin;%PATH%
```

**Comment by thrasher-** [comment]
Thanks @FeodorFitsner !
