### ISSUE TITLE
Go version installed in windows image behaves differently than local installation

### ISSUE THREAD

**Issue by anjannath** [appveyor/ci#3795]
image used: Visual Studio 2022

Go versions `1.16.15` and `1.17.8` behaves differently in the CI, and shows errors which am not able to reproduce locally

Job link for Go 1.16.15: https://ci.appveyor.com/project/code-ready/crc/builds/43207543
Job link for Go 1.17.8: https://ci.appveyor.com/project/code-ready/crc/builds/43207558

We have tried to find out if there's something wrong with the code base, that triggers these errors but even on a freshly created windows VM installing the mentioned go versions, we couldn't reproduce the errors

link to the repo: https://github.com/code-ready/crc

no errors are shown when building locally:
```posh
PS> make cross
GOARCH=amd64 GOOS=darwin go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=2.0.1 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.10.4 -X github.com/code-ready/crc/pkg/crc/version.podmanVersion=3.4.4 -X github.com/code-ready/crc/pkg/crc/version.commitSha=729ea1d3 " -o out/macos-amd64/crc  ./cmd/crc
GOOS=linux GOARCH=amd64 go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=2.0.1 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.10.4 -X github.com/code-ready/crc/pkg/crc/version.podmanVersion=3.4.4 -X github.com/code-ready/crc/pkg/crc/version.commitSha=729ea1d3 " -o out/linux-amd64/crc  ./cmd/crc
GOARCH=amd64 GOOS=windows go build -ldflags="-X github.com/code-ready/crc/pkg/crc/version.crcVersion=2.0.1 -X github.com/code-ready/crc/pkg/crc/version.bundleVersion=4.10.4 -X github.com/code-ready/crc/pkg/crc/version.podmanVersion=3.4.4 -X github.com/code-ready/crc/pkg/crc/version.commitSha=729ea1d3 " -o out/windows-amd64/crc.exe  ./cmd/crc
```

(My guess is while we try to set the version of of `Go` in the `appveyor.yaml` file by setting the `PATH` its not setting the go environment properly and some env variables in `go env` still points to the default 1.18 version of Go)

**Comment by anjannath** [comment]
Update: in addition to adding `C:\Go116\bin` to the `PATH` setting `GOROOT` fixed the issue for us, thanks to @cfergeau (https://ci.appveyor.com/project/cfergeau/crc/builds/43209280)

To use Go 1.16.15 in Appveyor use the following:
```cmd
set PATH=C:\go116\bin
set GOROOT=C:\go116
```

**Comment by FeodorFitsner** [comment]
Thank you for your notes!
