### ISSUE TITLE
"unexpected exit code 254: c:\msys64\usr\bin\bash.exe --login -c exit"

### ISSUE THREAD

**Issue by LandonAndEmma** [appveyor/ci#3796]
Anyone Know How To Fix? I'm Using Windows 11 BTW...
![WM-Screenshots-20220412195313](https://user-images.githubusercontent.com/80786423/163072946-edf66563-1e95-4709-a554-25e893bc76b3.png)

**Comment by kikonen** [comment]
Completed, but *what* is the fix in Windows 11?
