### ISSUE TITLE
Rolling builds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#38]
When busy OSS projects do a lot of commits and PRs their AppVeyor account's queue is getting overwhelmed with "queued" builds. This is because there is only one concurrent job is currently allowed for free accounts.

There is an idea of "rolling" builds, so the system do not start a new build for each commit, but waits until the build is completed and then queues another build of all check-ins that have not yet been built. This could be done per-branch.

**Comment by tkelman** [comment]
Here's the PR trick I've been using, translated into Powershell:
```
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/tkelman/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
```

I can't find a great way to automatically get the username (the public AV API URL for the project as an environment variable would do the trick), so that part needs to be tweaked.

**Comment by nedbat** [comment]
I see rolling builds mentioned in many places, but no description of how to turn it on.  nodegit is mentioned as a good example, but they don't have anything in their appveyor.yml that looks like ``rolling_build: true``.  Am I missing something obvious?

**Comment by FeodorFitsner** [comment]
It can be set on UI only as this should be known *before* appveyor.yml is read.

**Comment by ogrisel** [comment]
@FeodorFitsner thanks for this option, I just enabled it and it should be very helpful for the projects I maintain. However I don't find the name very explicit. I think you should put a tooltip with a (?) icon that explains that this makes it possible to skip intermediate commits across consecutive pushes to a pull request to avoid queuing too many redundant builds on very active PR.

**Comment by FeodorFitsner** [comment]
It's explained here in docs: http://www.appveyor.com/docs/build-configuration#rolling-builds

OK, for tooltip how would you state it in one line to fit the tooltip? ;)

**Comment by jakirkham** [comment]
Is there a way to set this for a project via the API?

**Comment by IlyaFinkelshteyn** [comment]
Sure. Here is PowerShell-based example. 

```
$token = '<your_api_token>'
	
$headers = @{
  "Authorization" = "Bearer $token"
  "Content-type" = "application/json"
}

$s = Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects/<your_account>/<your_project)slug>/settings' -Headers $headers  -Method Get

$s.settings.rollingBuilds = $true

Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/projects' -Headers $headers  -Body ($s.settings | ConvertTo-Json -Depth 10) -Method Put
```

Updating JSON  sample in documentation now...

--ilya.

**Comment by jakirkham** [comment]
Thanks.
