### ISSUE TITLE
.NET SDK 6.0.300 on Linux.

### ISSUE THREAD

**Issue by jrgcubano** [appveyor/ci#3824]
Hello

Windows have been updated to .NET SDK 6.0.300. Is it possible to update Linux too?

Thanks in advance

**Comment by teo-tsirpanis** [comment]
@jrgcubano [the pre-installed software page says that it is there](https://www.appveyor.com/docs/linux-images-software/#:~:text=.NET%20Core%20SDK%206.0.301).
