### ISSUE TITLE
Maximum allowed artifact storage size of 50000 Mb will be exceeded

### ISSUE THREAD

**Issue by TheDonsky** [appveyor/ci#3826]
Hello, I've run into the "Maximum allowed artifact storage size of 50000 Mb will be exceeded" issue;
Here's my link: https://ci.appveyor.com/project/TheDonsky/jimara/history

Thing is, I do not yet deploy anywhere and the only artifacts I care about are from the latest commit, since the project is not yet ready for meaningful releases. Is there a way to clean up the storage? (deleting some of the older builds did not help much).

Thanks in advance

**Comment by FeodorFitsner** [comment]
Bumped to 75 GB.

**Comment by TheDonsky** [comment]
Thanks. I'll reduce artifact size down to the main binaries and hopefully it won't happen again.
