### ISSUE TITLE
Add more logging to build cache operations

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#383]
Discussion: http://help.appveyor.com/discussions/problems/2884-saving-the-packages-is-taking-a-really-long-time-like-10-minutes-long

**Comment by PureKrome** [comment]
Any update on this? could this be pushed up the queue to a closer milestone plz?

it's really hurting our turnaround times for an AV project to start->complete.

(remember, we restore AND then save packages, per build .. so it's like 2x the pain :( )

**Comment by FeodorFitsner** [comment]
What do you store there?

**Comment by PureKrome** [comment]
![image](https://cloud.githubusercontent.com/assets/899878/14516105/16567e9c-0243-11e6-90ff-a09a1cbfe8ff.png)

this is a screen shot from just one of our AV Projects. Double this time if the packages also changed and therefore will be saved.

These are just normal nuget packages.

**Comment by FeodorFitsner** [comment]
Some instrumentation information is written to "AppVeyor" Windows event log. You can list it by adding to `appveyor.yml`:

```
on_finish:
- ps: Get-EventLog AppVeyor | Select Message
```
