### ISSUE TITLE
Python 3.9 is missing from Ubuntu images

### ISSUE THREAD

**Issue by pavel-kirienko** [appveyor/ci#3832]
A workflow that used to work well for years recently started failing for Python 3.9 specifically (while working fine for other configurations) referring to missing Python version. Here's [an example](https://ci.appveyor.com/project/Zubax/pycyphal/builds/44180980/job/pgnjwt8tgd4wbkqb):

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3298404/179206959-3ad1b726-de2e-4c14-bdc8-1589843d2714.png">

The workflow file is pretty standard: https://github.com/OpenCyphal/pycyphal/blob/master/.appveyor.yml

**Comment by FeodorFitsner** [comment]
Looking into that. Thanks for letting know!

**Comment by FeodorFitsner** [comment]
It should be fixed now - please give it another try.

**Comment by pavel-kirienko** [comment]
Yes, it is working now. Thank you. Can you share a few words about the cause and if similar issues should be expected in the future?

**Comment by FeodorFitsner** [comment]
Python 3.9 has failed to build on Ubuntu 20.04 image during its bake in the first place.
