### ISSUE TITLE
VS 2019 image: 'make' is not recognized

### ISSUE THREAD

**Issue by Yuri05** [appveyor/ci#3835]
Hi, 

I'm trying to call **make** on a **Visual Studio 2019** build image.
I have set the VS2019-x64 command line environment via
`call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"`

However when trying to call **make** after that I'm getting the error message:
`'make' is not recognized as an internal or external command, operable program or batch file.`

Any advice what might be missing?

![grafik](https://user-images.githubusercontent.com/25061876/186143564-fb4c8673-89ad-4da3-b0c0-603e24908a85.png)

**Comment by FeodorFitsner** [comment]
What directory is `make.exe` tool located in?

**Comment by Yuri05** [comment]
my bad, never mind.
I wrongly assumed make would be part of VS

**Comment by FeodorFitsner** [comment]
Strange, right? I've seen people installing it with "choco install make" or use one from mingw.

**Comment by Yuri05** [comment]
Yes, strange...
