### ISSUE TITLE
Update Visual Studio 2022 to 17.3 and .NET 6 SDK to 6.0.4xx.

### ISSUE THREAD

**Issue by teo-tsirpanis** [appveyor/ci#3836]
I suspect that some CI failures in my code are related to the Visual Studio version not being the latest. It would greatly help me if you update Visual Studio and the .NET SDK (the latter on the Ubuntu image as well).

**Comment by FeodorFitsner** [comment]
Working on it, expect the update by Monday.

**Comment by FeodorFitsner** [comment]
VS 2022 image has been updated: https://www.appveyor.com/updates/2022/08/29/

**Comment by teo-tsirpanis** [comment]
Thanks @FeodorFitsner but Ubuntu has not been yet updated.

**Comment by FeodorFitsner** [comment]
Sorry, we are working on that.

**Comment by FeodorFitsner** [comment]
Ubuntu images have been updated.
