### ISSUE TITLE
Issue with only_commits files

### ISSUE THREAD

**Issue by amitdo** [appveyor/ci#3837]
https://github.com/tesseract-ocr/tesseract/commit/47485fe9abae769fe8ffd14a1e16832c5bf3beb3

This commit didn't trigger a ci run. Why?

Did I make a mistake or is this a bug?

**Comment by FeodorFitsner** [comment]
What is that dash in the end? https://github.com/tesseract-ocr/tesseract/commit/47485fe9abae769fe8ffd14a1e16832c5bf3beb3#diff-92ab9a36df5d8e9f7076f2fdec59492d1ac2d9cf27ea046767a7fc4d542ef3dcR21

**Comment by amitdo** [comment]
Oops. I didn't notice it. Thank you!
