### ISSUE TITLE
doxygen apt package on Ubuntu image 

### ISSUE THREAD

**Issue by winterz** [appveyor/ci#3842]
something's wrong with the doxygen apt package installation on Image: Ubuntu; Configuration: Debug; Platform: x64

For example, happens with https://ci.appveyor.com/project/winterz/libical/builds/44788062/job/ay5f08819xg42rh9

> /usr/local/bin/doxygen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/doxygen)
> CMake Warning at /usr/share/cmake-3.23/Modules/FindDoxygen.cmake:460 (message):
>   Unable to determine doxygen version: 1
> Call Stack (most recent call first):
>   /usr/share/cmake-3.23/Modules/FindDoxygen.cmake:623 (_Doxygen_find_doxygen)
>   doc/CMakeLists.txt:16 (find_package)
> -- Found Doxygen: /usr/local/bin/doxygen (found version "") found components: doxygen dot 
> /usr/local/bin/doxygen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/doxygen)
> CMake Error at /usr/share/cmake-3.23/Modules/FindDoxygen.cmake:702 (message):
>   Unable to generate Doxyfile template: 1
> Call Stack (most recent call first):
>   doc/CMakeLists.txt:16 (find_package)
>

**Comment by FeodorFitsner** [comment]
It looks like an older version of Oxygen must be installed on `Ubuntu` (which is Ubuntu 18.04) image: https://github.com/appveyor/ci/issues/3583

There is a temp solution for that: https://github.com/appveyor/ci/issues/3573

**Comment by winterz** [comment]
we can close this.
I switch to the newer Ubuntu image

**Comment by Zeex** [comment]
Same issue.
```
/usr/local/bin/doxygen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/doxygen)
```

Update:
I was able to fix the error by removing `/usr/local/bin/doxygen` and installing doxygen from the official repos.
