### ISSUE TITLE
For the Mac-Monterey Image can we get Xcode 14.1

### ISSUE THREAD

**Issue by winterz** [appveyor/ci#3846]
Xcode 14 was released about 6 weeks ago. 
It would be great to have this available in the macos-monterey image

**Comment by FeodorFitsner** [comment]
Sure, we'll add that.

**Comment by winterz** [comment]
any progress?

**Comment by FeodorFitsner** [comment]
Working on it, hopefully it will be available this week!

**Comment by winterz** [comment]
I see "XCode 14.1 on macos-monterey image" listed on https://www.appveyor.com/updates/ as of 11 December 2022

thanks!

closing this
