### ISSUE TITLE
Update OpenSSL v3 to 3.0.7

### ISSUE THREAD

**Issue by xavier2k6** [appveyor/ci#3849]
https://www.openssl.org/news/cl30.txt
https://www.openssl.org/news/newslog.html
https://www.openssl.org/source/

https://www.openssl.org/news/secadv/20221101.txt

**Comment by Bartleby2718** [comment]
Should be good to close per https://www.appveyor.com/docs/windows-images-software/#software-pre-installed-on-windows-build-vms
