### ISSUE TITLE
Update OctoTools/OctopusCLI to 9.1.7

### ISSUE THREAD

**Issue by mharen** [appveyor/ci#3851]
The ubuntu images have octo 9.0.0. Please update to 9.1.7 (or at least 9.1.2).

**Comment by FeodorFitsner** [comment]
Sure, we will update images this week.

In the meantime you can add this to your `appveyor.yml` to update octo tool:

```
install:
- curl -fsSL https://download.octopusdeploy.com/octopus-tools/9.1.7/OctopusTools.9.1.7.linux-x64.tar.gz -o /tmp/OctopusTools.tar.gz
- sudo tar zxf /tmp/OctopusTools.tar.gz -C /usr/bin
- octo version
```

**Comment by mharen** [comment]
It looks like this was resolved some time ago.
