### ISSUE TITLE
.Net 7.0 support

### ISSUE THREAD

**Issue by Jaxelr** [appveyor/ci#3854]
Hi guys,

When should we expect to see dotnet 7.0 support on the ci images?

**Comment by FeodorFitsner** [comment]
Working on the update.

**Comment by FeodorFitsner** [comment]
The image has been updated with the latest VS 2022 and .NET 7.0.

**Comment by Jaxelr** [comment]
Thank you for the quick turnaround.

**Comment by olsh** [comment]
Any updates for Ubuntu images?

**Comment by FeodorFitsner** [comment]
Yep, will update it shortly.

**Comment by cinderblocks** [comment]
Any chance that shortly is coming soon?

**Comment by FeodorFitsner** [comment]
Early next week for sure! Sorry everyone about the delay with that!

**Comment by FeodorFitsner** [comment]
Ubuntu images have been updated with .NET Core 7.0.102: https://www.appveyor.com/updates/2023/02/06/
