### ISSUE TITLE
Python 3.11 support for maCOS images

### ISSUE THREAD

**Issue by sbraz** [appveyor/ci#3858]
Hi, although Linux and Windows support was added in https://github.com/appveyor/ci/issues/3844, I still don't see Python 3.11 in macOS images. Would it please be possible to add it?

**Comment by oleksiyskononenko** [comment]
According to https://www.appveyor.com/docs/macos-images-software/#python Python `3.11` has been already added to macOS images.

**Comment by FeodorFitsner** [comment]
Yep, I'm closing this issue.
