### ISSUE TITLE
Allow to exclude configurations from the matrix

### ISSUE THREAD

**Issue by ignacio** [appveyor/ci#386]
I'd like to skip certain combinations that I know will fail (for instance, compiling with VS 2010 in 64 bits won't work).
A way to exclude combinations from the matrix would be most welcome.

**Comment by FeodorFitsner** [comment]
Yes, you can do that: http://www.appveyor.com/docs/build-configuration#allow-failing-jobs



- Feodor

**Comment by ignacio** [comment]
But that would still run the combination, right? I'd like to skip it entirely.
I added this issue because of this comment:
http://help.appveyor.com/discussions/questions/1170-testing-against-both-msvc-2013-and-2015#comment_36495053

**Comment by FeodorFitsner** [comment]
You can a simple "IF ... exit /b 1" to "init" section of your appveyor.yml to check environment variables and fail build job fast before even cloning repo.



- Feodor

**Comment by ignacio** [comment]
Tried it and it works fine. It might get cumbersome if there are to many combinations to exclude, but it does the trick for the time being.

For reference: 
https://ci.appveyor.com/project/ignacio/lua-appveyor-example/build/0.0.1.144-test

Thanks!

**Comment by ignacio** [comment]
Hi Feodor,
Will matrix exclusions be added eventually?

**Comment by rakhimov** [comment]
How is this feature missing? :open_mouth: 
@FeodorFitsner Please take a look at how Travis handles matrix ``excludes`` and also ``includes``.
This is just annoying and noisy to do by hand in appveyor config,
let alone your build queues populated by 'waiting' deads.

**Comment by webmaster128** [comment]
We also need this feature for Botan, where heavy long running C++ compiling is going on. Currently we need to reduce 24 configurations down to 8 which is a complex thing and an exclude feature would really avoid losing the overview.

**Comment by lucasvickers** [comment]
Same need here.  On [Cinder](https://github.com/cinder/Cinder) we have a 2013 project that supports vs 2013 and vs 2015, and a 2015_winr project that is only available on vs 2015.

I am working to allow failures on the invalid combination, but it clutters output.  It ideally should be excluded from the build matrix to prevent cluttering of the display and also to save machine resource.

**Comment by jagerman** [comment]
The workaround, quite frankly, sucks.  It still starts up a VM just to run `exit 1`, but more importantly it leads to a build status with a bunch of "errors" on it (which are really skipped jobs, not errors), with no good way to distinguish actual errors from skipped jobs other than viewing the job for each and every one.

It's not even like this is a major feature request: it could be implemented by just duplicating the way `allow_failures` works, but just calling it something like `exclude_jobs` plus adding a bit of logic to actually skip adding matching jobs to the queue.

**Comment by IlyaFinkelshteyn** [comment]
https://www.appveyor.com/docs/build-configuration/#exclude-configuration-from-the-matrix
