### ISSUE TITLE
[Ubuntu] Support .net 7

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#3861]
Hi,

I'm trying to run my build which I recently upgraded to .net 7 but it fails on ubuntu.
I'm guessing the image doesn't have .net 7 from the error message.
I don't know if this is planned or not, but it would be great to have .net 7 on the next ubuntu image.

Thanks for all the great work you guys are doing!!

Relevant build for examle:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/45796525/job/f7qjsku80cwcx4y1

**Comment by FeodorFitsner** [comment]
We are going to update Ubuntu images shortly.

**Comment by HarelM** [comment]
Thanks @FeodorFitsner !!

**Comment by HarelM** [comment]
As a workaround, I was able to run the following command as part of the install phase: `sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0`
So, from my point of view, this is not urgent.

**Comment by Bartleby2718** [comment]
@HarelM .NET 8 (which is an LTS, unlike .NET 7) is already available on both `Ubuntu2004` and `Ubuntu2204` per https://www.appveyor.com/docs/linux-images-software/. (I have already started using .NET 8 on Ubuntu 2204.)

 I think we can close this ticket.
