### ISSUE TITLE
Macos CI started failing since this morning

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#3868]
Hi,

The following build started to fail this morning, not sure I understand why.
I haven't changed anything dramatically on my end and there's an error saying `[error] CocoaPods is not installed.`.
This error did not happen yesterday.
Was there an image change for macos by any chance?
Failing build link:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/job/93fq8ar7q21v4m44
Passing build link:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/46355761/job/qbjuh702ui6o4mfg
Code repo:
https://github.com/IsraelHikingMap/Site

I've tried to run the build a few times to see if this was a temporary network issue, but it doesn't appear to be the case as far as I understand.

**Comment by FeodorFitsner** [comment]
Nope, there were no changes to macOS images recently.

**Comment by HarelM** [comment]
Ok, thanks for the info. I'll continue the investigation on my end...

**Comment by HarelM** [comment]
Seems that cocoapods was installed without a version and so it always took the latest verison.
Latest version does not support the ruby version that is currently installed on the CI server and so the build failed.
This issue is due to my code in general.
Sorry for spamming.
Keep up the good work!

**Comment by FeodorFitsner** [comment]
Good to know, thanks for the update!
