### ISSUE TITLE
Any plans to provide a build worker image for Ubuntu2204?

### ISSUE THREAD

**Issue by todthomson** [appveyor/ci#3870]
Hi AppVeyor,

re: [https://www.appveyor.com/docs/build-environment/#build-worker-images](https://www.appveyor.com/docs/build-environment/#build-worker-images)

Provides: Ubuntu1604, Ubuntu1804, and Ubuntu2004, but doesn't as yet have a Ubuntu2204 (the newest LTS release).

Any plans to add a Ubuntu 22.04 LTS image? :)

Cheers,

Tod.

**Comment by OwenMcDonnell** [comment]
It's been [added](https://www.appveyor.com/updates/2023/10/17/)

**Comment by vszakats** [comment]
Thank you!

This page could use an update to reflect that:
https://github.com/appveyor/website/blob/ea7b711429e1f509731c8b90bd136b73240d5013/src/docs/build-environment.md?plain=1#L153

That said, when trying the new image, it results in this:
```
Build worker image not found: Ubuntu2204
```
Ref: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/48336857/messages

What may be the problem?

**Comment by FeodorFitsner** [comment]
@vszakats it should be working now.

**Comment by bellrichm** [comment]
@FeodorFitsner 
Working for me now. Thanks!

**Comment by vszakats** [comment]
@FeodorFitsner I also confirm it working, thank you so much! Great stuff!
