### ISSUE TITLE
Provide Visual Studio 2022 Preview

### ISSUE THREAD

**Issue by gengjiawen** [appveyor/ci#3874]
Visual studio sometimes put fix on Preview, like https://developercommunity.visualstudio.com/t/cpp20-nested-namespace-cant-compile/10328893#T-ND10330571

Would be nice to test it directly.

Thx for such useful service.

**Comment by freemansammy** [comment]
@gengjiawen

**Comment by Bartleby2718** [comment]
Given that the [Visual Studio 2022 image](https://www.appveyor.com/docs/windows-images-software/#visual-studio-2022) is already available, I wonder if this issue can be closed.
