### ISSUE TITLE
GCC and Qt libs on MSYS2 and VS 2022 instance

### ISSUE THREAD

**Issue by mcallegari** [appveyor/ci#3882]
Hello, I've been using AppVeyor for many years now. Such a great tool!
However, from time to time my project fails to build because of inconsistencies between a vanilla MSYS2 installation and what AppVeyor proposes.
For example right now GCC version is still 12.2 while MSYS2 delivers 13.x since a few months now.
For this reason I'm also starting to see segfaults on Qt tools while creating translation files. I also need to patch Qt header files to be compatible with older GCC (there would be no issue with GCC 13.x)
Is it possible to advance the VS 2022 instance to be aligned with the latest packages provided by MSYS2 as of today?
It seems pacman -Syu is not enough to be up-to-date.

My project is https://github.com/mcallegari/qlcplus

Thanks in advance and regards
Massimo

**Comment by OwenMcDonnell** [comment]
The [most recent update](https://www.appveyor.com/updates/2023/07/04/) should include the latest MSYS2. Are you able to determine if it has the expected GCC version? But is the GCC version not determined by MinGW?

**Comment by mcallegari** [comment]
Hi, I confirm GCC 13.x is now upstream.
Thanks
