### ISSUE TITLE
Unable to find OpenSSL libraries in C:/OpenSSL-Win64

### ISSUE THREAD

**Issue by igsilya** [appveyor/ci#3883]
Image: Visual Studio 2019
Example of a broken build: https://ci.appveyor.com/project/igsilya/ovs/build/job/s9an8eqwv8vf0ufl
We didn't change any build configuration and it started failing since yesterday.

**Comment by HarelM** [comment]
I have an issue with openssl as well on MacOS system, not sure if this the same, but it started 4 days ago:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/47413285/job/wp6ldt3lrtt2xmpi
I'm getting:
```
bad decrypt
0036860801000000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
```
I've tried to generate the encrypted files again on my local machine with all kinds of flags, but none of them seems to solve the issue... :-(

**Comment by OwenMcDonnell** [comment]
An image update to Visual Studio 2019 had caused the initial issue. We've patched that image, so it should be resolved now. 
@HarelM Mac images have not been updated recently so this must be unrelated.

**Comment by HarelM** [comment]
There was a change, not sure what, I managed to fix it by encrypting the files again.
In any case, the error above is due to incorrect password... :-/

**Comment by igsilya** [comment]
@OwenMcDonnell The build is able to locate OpenSSL installation now.  Thanks!
