### ISSUE TITLE
Latest image doesn't support Go v1.20 despite docs saying it does

### ISSUE THREAD

**Issue by thrasher-** [appveyor/ci#3884]
Hi there,

It appears that using the VS 2022 image and the default path for Go defaults to version v1.19.10 instead of 1.20.x as the docs state: https://www.appveyor.com/docs/windows-images-software/#golang

Link to build issue:
https://ci.appveyor.com/project/thrasher-/gocryptotrader-vxsws/builds/47448750

**Comment by OwenMcDonnell** [comment]
Sorry, there was a directory naming error that was overlooked on the previous image update. 
It's been corrected in the latest [image update](https://www.appveyor.com/updates/2023/07/04/).

**Comment by thrasher-** [comment]
Can confirm that it's now working again, thanks!
