### ISSUE TITLE
Boost 1.82.0 available in Visual Studio 2019 image but not in Visual Studio 2022 image

### ISSUE THREAD

**Issue by lballabio** [appveyor/ci#3885]
See <https://ci.appveyor.com/project/lballabio/quantlib/builds/47689427>, which outputs the contents of `C:\Libraries` and, if found, of `C:\Libraries\boost_1_82_0`.

The 2022 image still has Boost 1.73 and 1.77 installed.

Moreover, the Boost 1.82 binaries installed in the 2019 image are those labeled as `msvc-14.3` (i.e., those for VS2022), not the expected `msvc-14.2`.

**Comment by OwenMcDonnell** [comment]
Thanks for bringing this to our attention. It will be rectified in the next image update. 
In the meantime you could execute [this script](https://gist.github.com/OwenMcDonnell/f7ce474cc82e92cdfe0492b889e0ba70) in the `init` phase of your build. You'll have to modify the download location to `msvc-14.2` if you want the VS2019 binaries.

**Comment by jackpoz** [comment]
![image](https://github.com/appveyor/ci/assets/1153754/e9f313c5-563c-4e27-8fd4-7cef8a0458b9)

new VS 2022 image has Boost 1.83 only even if https://www.appveyor.com/docs/windows-images-software/#boost says it should have 1.77 and 1.83

![image](https://github.com/appveyor/ci/assets/1153754/a30ed8e6-da24-4204-ab38-6889b6517847)

Please either fix the images or the documentation

**Comment by lballabio** [comment]
Same problem for the VS 2019 image.

**Comment by OwenMcDonnell** [comment]
Boost 1.77 doesn't have a 2022 binary, though 1.78 does. I can add that to the 2022 image. Is 1.77 still needed on the 2019 image or would 1.78 on both suffice?

**Comment by lballabio** [comment]
I'm ok with any version on 2022 and 2019, but I'm just speaking for myself of course.  I guess it'd be nice for versions to not just disappear without warning, in case people rely on them for settings compiler variables.

**Comment by jackpoz** [comment]
> Boost 1.77 doesn't have a 2022 binary, though 1.78 does. I can add that to the 2022 image. Is 1.77 still needed on the 2019 image or would 1.78 on both suffice?

Any version of Boost in VS 2022 image is fine for me too, even the one currently installed 1.83 , but it would help if the documentation mentioned the same versions that are installed in the images.

**Comment by OwenMcDonnell** [comment]
I've released a minor image update to address this issue. Please let me know if new builds are working as expected with respect to Boost libraries. The documentation should be brought up to date shortly as well (see [here](https://github.com/appveyor/website/pull/862))

**Comment by lballabio** [comment]
It worked for me, thanks.
