### ISSUE TITLE
Java 1.8 x64 is in PATH

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#390]
Discussion: http://help.appveyor.com/discussions/problems/2814-error-when-using-java

**Comment by jakepetroules** [comment]
Actually, after more investigation it seems that it would be best to remove `C:\ProgramData\Oracle\Java\javapath` from the PATH, and remove all java executables from `C:\Windows\System32` and `C:\Windows\SysWOW64`

**Comment by FeodorFitsner** [comment]
That's right, thanks for note. It's unbelievable that Java installer puts java.exe to System32!
