### ISSUE TITLE
`C:\PYTHON_VERSION\Scripts\pip.exe install ...` fails on specific Python versions

### ISSUE THREAD

**Issue by junkmd** [appveyor/ci#3903]
When CI was triggered at https://ci.appveyor.com/project/cfarrow/comtypes/builds/48408734 (https://github.com/junkmd/comtypes/commit/6df4f46a86d0a2a8078a40a3f783cdab8f9ff46d), it was successful, but when CI was triggered at https://ci.appveyor.com/project/cfarrow/comtypes/builds/48873456 (https://github.com/enthought/comtypes/commit/df0c3c237aa3318835702e21fe9f714c7d80e0aa), it started failing.

The `appveyor.yml` is as follows, where the `py` is assigned a string specifying an arbitrary Python version.

```yml
environment:
   matrix:
     - py: Python27
     - ...
     - py: Python312-x64
```

However, from `Python33` to `Python36-x64`, the following error messages are displayed and resulting in failures.

```
C:\%py%\Scripts\pip.exe install --upgrade setuptools
The system cannot find the path specified.
```

From what I see in https://www.appveyor.com/docs/windows-images-software/#python, I understand that AppVeyor has not discontinued support for these Python versions.

**Comment by OwenMcDonnell** [comment]
Please refer to my response, to [this](https://github.com/appveyor/ci/issues/3901) previously closed issue. 
The PR to documentation still needs to be merged however. It will be soon.

**Comment by junkmd** [comment]
> Please refer to my response, to [this](https://github.com/appveyor/ci/issues/3901) previously closed issue.
> The PR to documentation still needs to be merged however. It will be soon.

Thank you for your response.

I had missed that issue.

And I also confirmed https://github.com/appveyor/website/pull/866 was merged.
