### ISSUE TITLE
Update Qt 5.15.2 to a newer 5.15.x

### ISSUE THREAD

**Issue by limdor** [appveyor/ci#3904]
In Windows images the minor version of Qt 5.15 is the .2 that is from November 2020. Since then there has been a lot of minor releases that fixes several issues.
Please update to Qt 5.15.16.

**Comment by limdor** [comment]
I just realized that the reason why the lastest 5.15 available is 5.15.2 is because higher minor releases are only available to commercial users.

**Comment by bjorn** [comment]
Actually later versions have eventually been released as open source as well, but only as source code and not as binary installable. So you can build your Qt app against a more recent Qt 5.15 (up to Qt 5.15.12 currently), but only if you compile it yourself.

The source code can be obtained [from git](https://code.qt.io/cgit/qt/qt5.git/log/?h=5.15) or downloaded from https://download.qt.io/official_releases/qt/5.15/.
