### ISSUE TITLE
Failing to download dotnet

### ISSUE THREAD

**Issue by SimonCropp** [appveyor/ci#3905]
My build are failing after no changes on my part.

![image](https://github.com/appveyor/ci/assets/122666/521df77a-7cc7-4d32-85f0-33c06b93df1b)

Passing build: https://ci.appveyor.com/project/SimonCropp/verify-http/builds/48947028

Failing build: https://ci.appveyor.com/project/SimonCropp/verify-http/builds/48949729

Seems they are failing to download dotnet

the command that is failing is:

```
Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
```

Line in yml

https://github.com/VerifyTests/Verify.Http/blob/main/src/appveyor.yml#L8

**Comment by OwenMcDonnell** [comment]
Is this repeatable or just a transient download error? I was able to run [this minimally similar build](https://ci.appveyor.com/project/owen/test-appveyor) with success.

**Comment by SimonCropp** [comment]
@OwenMcDonnell it was repeatable for over an hour. but is working now. so will close this one for now
