### ISSUE TITLE
Qt 6.6

### ISSUE THREAD

**Issue by dismine** [appveyor/ci#3906]
https://www.qt.io/blog/qt-6.6.1-released

**Comment by bjorn** [comment]
Qt 6.6.2 is out in the meantime (https://www.qt.io/blog/qt-6.6.2-released).

I'd really like to see this update, since Qt 6.6.1 fixes the WebP image plugin shipped in the MinGW package.

**Comment by OwenMcDonnell** [comment]
Qt 6.6.2 is now part of Ubuntu images, and is on the way in Visual Studio images.

**Comment by BLumia** [comment]
Qt 6.6.3 is out btw: https://www.qt.io/blog/qt-6.6.3-released
