### ISSUE TITLE
[Ubuntu] Support .net 8

### ISSUE THREAD

**Issue by xpatos** [appveyor/ci#3908]
It was a long time since the Ubuntu image was updated. .NET 7 is no longer supported from May 14 2024, so we need to upgrade to .NET 8

**Comment by Bartleby2718** [comment]
@OwenMcDonnell What's the latest on this? I see a workaround in https://help.appveyor.com/discussions/questions/64392-net-8-build-server-image-support-for-macos-and-ubuntu, but I wasn't sure whether I should wait.

(As an aside, it'd be great if https://www.appveyor.com/docs/linux-images-software/ is updated to include . NET 8.)

**Comment by OwenMcDonnell** [comment]
@Bartleby2718 Though not documented or officially announced yet, .NET 8 is live on 20.04 and 22.04 images. 
Website PR for update is [here](https://github.com/appveyor/website/pull/870)

**Comment by Bartleby2718** [comment]
Thanks for the update @OwenMcDonnell! I see that the website was updated. I suppose this ticket should be good to close then?
