### ISSUE TITLE
Visual Studio 2017 license has expired

### ISSUE THREAD

**Issue by michaelknigge** [appveyor/ci#3909]
Visual Studio 2017 license has expired - it would be great if this can be fixed...

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.com" Janel.sln /rebuild "Release Console|Win32"
> 
> Microsoft Visual Studio 2017 Version 15.0.28307.1000.
> Copyright (C) Microsoft Corp. All rights reserved.
> 
> The license for Visual Studio has expired.
> 
> Your license for this product is expired and could not be refreshed. Please connect to the internet to continue to use this product.

See https://ci.appveyor.com/project/michaelknigge/janel/branch/enhanced

Thank you very, very much...

Bye,
Michael

**Comment by OwenMcDonnell** [comment]
https://ci.appveyor.com/project/appveyor-tests/vdproj-test
