### ISSUE TITLE
OpenSSL 3 libs missing

### ISSUE THREAD

**Issue by tumic0** [appveyor/ci#3916]
Since ~2 weeks, the OpenSSL libs that used to be in C:\OpenSSL-v30-Win64\bin are missing, see [the GPXSee Qt6 build](https://ci.appveyor.com/project/tumic0/gpxsee/builds/49533593/job/75gf4lxft00ct3kp) job as an example (nothing has changed in the yml file).

**Comment by tumic0** [comment]
I have noticed that in the [list](https://www.appveyor.com/docs/windows-images-software/#tools) of preinstalled tools OpenSSL 3.0 is now missing as well and switched to version 3.2 in the GPXSee build. But I really do not get the reason behind the v3.0 dissapearing as it is a LTS version that has the longest support from all current active OpenSSL versions (3.0, 3.1, 3.2)...

**Comment by OwenMcDonnell** [comment]
Sorry for the late response. In the last image update we added 3.2 and removed 3.0, not realizing the LTS status. We can add 3.0 back to the next image update.

**Comment by tumic0** [comment]
I can live with the 3.2 version. But if you want to drop some OpenSSL version to lower the required maintenance resources, than I would drop 3.1 and keep 3.0 and 3.2 which makes much more sense than keeping 3.2 and 3.1.
