### ISSUE TITLE
Update 7-Zip to 23.01

### ISSUE THREAD

**Issue by Chocobo1** [appveyor/ci#3918]
https://7-zip.org/
https://www.7-zip.org/download.html
https://www.7-zip.org/history.txt
https://sourceforge.net/p/sevenzip/discussion/45797/thread/3f550826d8/

**Comment by xavier2k6** [comment]
7-Zip 24.05 is out now.
https://sourceforge.net/p/sevenzip/discussion/45797/thread/b92679e642/
https://github.com/ip7z/7zip/releases/tag/24.05
