### ISSUE TITLE
CMake 3.29.1 has support issues

### ISSUE THREAD

**Issue by lewri** [appveyor/ci#3919]
As per https://github.com/microsoft/vcpkg/issues/37968 CMake 3.29.1 is strongly recommended to be replaced with 3.29.2 due to breaking packages.

For our specific instance at https://github.com/CorsixTH/CorsixTH the package `libsndfile` is broken in this version of CMake. Confirmed fixed with the next version of CMake (indirectly inside vcpkg issues).

**Comment by lewri** [comment]
This appears to have had some resolution inside vcpkg now
```
-- Running vcpkg install
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
A suitable version of cmake was not found (required v3.29.2) Downloading portable cmake 3.29.2...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-windows-i386.zip->C:\Tools\vcpkg\downloads\cmake-3.29.2-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-windows-i386.zip
Extracting cmake...
```

**Comment by OwenMcDonnell** [comment]
[updated](https://www.appveyor.com/updates/2024/06/18/)
