### ISSUE TITLE
Add manylinux2014 docker image to cache

### ISSUE THREAD

**Issue by OwenMcDonnell** [appveyor/ci#3924]
See [discussion](https://help.appveyor.com/discussions/questions/64836-manylinux-docker-images).

**Comment by oddy** [comment]
Thanks Owen, you're a legend :)

**Comment by OwenMcDonnell** [comment]
[Available now](https://www.appveyor.com/updates/2024/08/05/) on all Ubuntu images.

**Comment by oddy** [comment]
Thanks Owen you are a legend.
