### ISSUE TITLE
Could not create SSL/TLS secure channel in Start-FileDownloadInternal

### ISSUE THREAD

**Issue by tbeu** [appveyor/ci#3930]
I notice a 

```
Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
At C:\Program Files\AppVeyor\BuildAgent\Modules\build-worker-api\build-worker-api.psm1:242 char:2
+     Start-FileDownloadInternal -Url $Url -FileName $FileName -Timeout ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-FileDownloadInternal], Exception
    + FullyQualifiedErrorId : System.Exception,Appveyor.BuildAgent.Api.Utils.StartFileDownloadInternalCmdlet
```

in https://ci.appveyor.com/project/tbeu/matio/build/job/u1gu5tbhab09jr85 Is there anything on my side to address this issue? Thanks!

**Comment by OwenMcDonnell** [comment]
Are you using `Visual Studio 2015` image for this build? If so, there has been no changes to it for some time. 
Can you try replacing the failing `Start-FileDownload <url>` with `appveyor DownloadFile <url>` command in your `.appveyor.yml` config file and see if it still fails?

**Comment by tbeu** [comment]
Same error on https://ci.appveyor.com/project/tbeu/matio/build/job/u1gu5tbhab09jr85

```
Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
```

**Comment by OwenMcDonnell** [comment]
In that case try adding this line before the `Start-FileDownload` command. 
`- ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"`

**Comment by tbeu** [comment]
Thanks for the hint of TLS downgrade. No matter what I tried, I failed in https://ci.appveyor.com/project/tbeu/matio/history

**Comment by OwenMcDonnell** [comment]
It looks like TLS 1.2 is not so straightforward to enable on Windows Server 2012. 
I think using curl as an alternative should work.
`  - curl -fsS -o hdf5-1.8.13-win32-VS2010-shared.zip https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-shared.zip`

**Comment by tbeu** [comment]
No success
```
Invoke-WebRequest : A parameter cannot be found that matches parameter name 'fsS'.
At line:19 char:10
+     curl -fsS -o hdf5-1.8.13-win32-VS2010-shared.zip https://support. ...
+          ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by OwenMcDonnell** [comment]
Looks like curl called within a powershell script is aliased to Invoke-WebRequest. Try this instead...
```
$args = '-fsS', '-o', 'hdf5-1.8.13-win32-VS2010-shared.zip',
                'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-shared.zip'
$curlexe = 'C:\Tools\curl\bin\curl.exe'
& $curlexe @args
```

**Comment by tbeu** [comment]
Thanks for the support. I gave up on external download, but added the external files in a dedicated git repository. Both git submodule or direct git clone work as expected (via HTTPS).
