### ISSUE TITLE
Artifacts retention policy

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#394]
Retention rules based on:

* NuGet packages
* branch names (e.g. always keep artifacts based on a particular github branch name). This one is important I think and should have precedence over other configuration settings, so we can always deploy a previous release branch
* keep the artifacts of the last x builds
* remove all artifacts older than x days / weeks / months

**Comment by InesaFitsner** [comment]
It would be helpful to be able to specify artifacts in terms of time (e.g. retain < 3 months old), but also potentially by branch as well (e.g. keep at least last 5 builds of a branch).
