### ISSUE TITLE
lrelease is missing

### ISSUE THREAD

**Issue by tumic0** [appveyor/ci#3940]
Since a few days, [GPXSee Qt6 builds](https://ci.appveyor.com/project/tumic0/gpxsee/builds/51117889/job/0bfmxetkohltsjt8) end with the following error:

```
lrelease gpxsee.pro
'lrelease' is not recognized as an internal or external command,
operable program or batch file.
```

This is a regression, `lrelease` was present in Qt 6.7.2 (and is normally present in a Qt6 installation) when it was introduced on AppVeyor and quiet strange as according to the "Software pre-installed on Windows build VMs" page nothing has changed...

**Comment by OwenMcDonnell** [comment]
A new image has been released but is awaiting documentation. That release has QT 6.8.0 replacing 6.7.2. Update your environment variables and you should be fine. 
Or you can use `Previous Visual Studio 2022` image until new one is announced with all updates (which should be soon).

**Comment by tumic0** [comment]
While I may switch to a newer Qt version, a newer version does not explain why `lrelease` is suddenly  missing in an already existing version that worked fine up to now.

**Comment by tumic0** [comment]
...and in the new Qt 6.8.0 build, `lrelease` is missing as well

**Comment by OwenMcDonnell** [comment]
Two things: 
1) Qt, for some reason with 6.8, substantially altered their directory structure, and packaging in their sdk repository, from which our scripts draw to install Qt.  This has caused some significant delay as we have to change the whole install script and verify that it works the same as previous version.
2) Once a new image with repaired Qt installation is released it will not have Qt 6.7 as that is not LTS. We can't keep every version of Qt on our build images. This is not a light weight framework

**Comment by OwenMcDonnell** [comment]
https://www.appveyor.com/updates/2024/12/22/

**Comment by tumic0** [comment]
The update to Qt 6.8.1 does not solve the problem with `lrelease` being unavailable. See https://ci.appveyor.com/project/tumic0/gpxsee/build/job/p0fj5780963mrss0 as an example of a job that still fails, even with Qt 6.8.1.
