### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by narkhedegs** [appveyor/ci#410]
I get "Cannot bind argument to parameter 'Path' because it is an empty string." error when executing following command - 

dnvm use 1.0.0-beta6 -r clr -arch x86

I successfully installed the dnvm and then the 1.0.0-beta6 version of dnx but when I try to add the dnx to the PATH using dnvm use I get the above mentioned error. I am doing all of this through a powershell script.

**Comment by FeodorFitsner** [comment]
Looks like the same issue: http://help.appveyor.com/discussions/problems/2962-unable-to-install-aspnet-5-beta-6

**Comment by narkhedegs** [comment]
Thank you. Yes its the same issue. Its an issue with the latest dnvm powershell script and the solution provided at the url mentioned above (and here https://github.com/aspnet/Home/issues/899) resolved the issue.
