### ISSUE TITLE
Add build option to save build cache early

### ISSUE THREAD

**Issue by codewarrior0** [appveyor/ci#412]
I'm using the build cache to store the result of building python wheels for my project's requirements and test-requirements. Many of the requirements are not shipped as wheels, and many of those require C compilation ~~(numpy is the big one - 20 minutes to build the wheel)~~ _That may have been a heavily-loaded node or something... it's usually 5 minutes_.

The wheels are built and installed during the `install` step. However, the build cache is not saved until after the `test` (or rather, `test_script`) step. And if the testing step fails, the build cache is not saved at all. To exacerbate the problem, if I run out of time because rebuilding the wheels took a long time, the build cache is again not saved. 

I'd like to be able to save the build cache at the end of the install step.

**Comment by FeodorFitsner** [comment]
Obviously, built-in build cache can't cover all scenarios.

Why wouldn't you just use some external storage to put dependencies, like S3 or Azure blob.

**Comment by codewarrior0** [comment]
I thought this was the scenario the built-in build cache was designed for - caching dependencies. That's four of the five example use-cases on the [build cache docs](http://www.appveyor.com/docs/build-cache). Being able to save the build cache early would help all of those, too.

The only difference with python wheels is a small bit of preprocessing.

**Comment by kveretennicov** [comment]
This behaviour (not saving cache unless build succeeds) bit me too. I was setting up build for a Python project with many dependencies and big test suite, where some tests happened to fail on Windows. I couldn't understand why already fetched dependencies were not cached and instead re-downloaded every time. I assumed either a bug in AppVeyor or in my configuration, but couldn't tell exactly what's wrong.

**Comment by IlyaFinkelshteyn** [comment]
This was implemented a while ago. Doc: https://www.appveyor.com/docs/build-cache/#saving-cache-for-failed-build
