### ISSUE TITLE
WDK 10 "include" directory renamed on Visual Studio 2015 images

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#414]
Discussion:
http://help.appveyor.com/discussions/problems/3033-c-compilation-fails-to-find-standard-library

Problem:
http://stackoverflow.com/questions/31862627/vs2015-cl-cant-find-crt-libs-stido-h-ctype-h-etc-when-building-on-command-l

Solution: rename `wdf` folder as part of your build script (PowerShell):

    ren 'C:\Program Files (x86)\Windows Kits\10\include\wdf' '00wdf'

**Comment by kinke** [comment]
In my case, the MS linker was unable to find `kernel32.lib` etc. Not sure if renaming the `wdf` subdirectory is enough for that to work too (is the Win10 SDK installed?). My workaround is a bit more involved, see https://github.com/ldc-developers/ldc/pull/1079/files.

**Comment by FeodorFitsner** [comment]
OK, thanks for heads up. Let's see what others will find.

**Comment by kinke** [comment]
Glad to say simply renaming the `wdf` folder got rid of the linker issue too (i.e., the Win10 SDK is properly installed). It's important to rename it to `00wdf` or similar though, as the MS batch file uses the (alphabetically) last subdirectory of the WinSDK `include` directory to determine the SDK version *cough*, and the actual WinSDK subdirectories are of the form `10.x.y.z.`.
