### ISSUE TITLE
Generic "appveyor-retry" script

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#418]
The script can be used as:

    appveyor-retry <your-command>

Script will re-try running `<your-command>` for 3 times if exit code was non 0.

Discussion: http://help.appveyor.com/discussions/suggestions/816-generic-wrapper-for-retry
Implementation: https://github.com/appveyor/ci/blob/master/scripts/appveyor-retry.cmd

**Comment by bd82** [comment]
Is this in production/available ?

I've tried using this to workaround npm install issues in the less.js project without luck.

https://ci.appveyor.com/project/lukeapage/less-js/build/626/job/nf4ci3sqx9qjy2m1

The [travis-retry](https://github.com/less/less.js/pull/2941/files#diff-354f30a63fb0907d4ad57269548329e3R28) worked and solved the problem.

But the [appveyor-retry](https://github.com/less/less.js/pull/2941/files#diff-180360612c6b8c4ed830919bbb4dd459R18) did not work.

**Comment by IlyaFinkelshteyn** [comment]
Hi Shahar,

Thank you for the catch! Here is temporary workaround: https://github.com/less/less.js/pull/2943
Bug: https://github.com/appveyor/ci/issues/950

--ilya.

**Comment by bd82** [comment]
Thanks. 
I've integrated this into my pull request at https://github.com/less/less.js/pull/2941
