### ISSUE TITLE
Ignoring tests (test quarantine)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#42]
http://help.appveyor.com/discussions/questions/627-is-it-possible-to-force-a-rebuild-or-re-test-of-a-failed-build

Example: http://blogs.atlassian.com/2012/04/test-quarantine-continuous-integration-bamboo4/

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/2018
