### ISSUE TITLE
Python 3.5.0

### ISSUE THREAD

**Issue by maiksensi** [appveyor/ci#426]
Hey,
Python 3.5.0 was released the other day (https://www.python.org/downloads/release/python-350/). It would be great to have this installed by default. 

Cheers and thanks for the great work!

**Comment by FeodorFitsner** [comment]
It's been deployed to all workers.

Installation paths:

- Python 3.5 x86: `C:\Python35`
- Python 3.5 x64: `C:\Python35-x64`

**Comment by maiksensi** [comment]
Thanks Feodor!
