### ISSUE TITLE
Test Matrix Coverage for WMF 2, 3, 4, and 5

### ISSUE THREAD

**Issue by alx9r** [appveyor/ci#427]
I've got a bunch of powershell modules with Pester tests that I'd like to test under WMF versions 2, 3, 4, and 5.  Currently, it seems like the most coverage for the WMF version dimension is as follows:

 * WMF 4 - via the default `Windows Server 2012 R2` operating system image
 * WMF 5 - [via the "unstable" image"](https://github.com/appveyor/ci/issues/255#issuecomment-101514578)

Is there some other way I can run tests against WMF versions 2 and 3?  Are there Windows Server 2008 R2 and Windows Server 2012 images that I have missed?

**Comment by FeodorFitsner** [comment]
All images are based on Windows Server 2012 R2 only.
