### ISSUE TITLE
Improve performance of build cache

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#438]

**Comment by Korijn** [comment]
Just a :+1: from our end (@clinicalgraphics), our install step typically pulls in anywhere between 1 - 2,5 GB of dependencies, which easily takes up 90% of the  job duration. Just increasing the build cache size would save us countless hours of waiting time.

**Comment by Korijn** [comment]
Any news? Plans?

**Comment by FeodorFitsner** [comment]
Still in progress, sorry. There is a bigger milestone we are working on right now called "private build clouds" and improved build cache could be part of it.
