### ISSUE TITLE
Global "before" and "after" scripts for Agent deployment transaction

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#44]
More info: http://help.appveyor.com/discussions/questions/620-environment-vars-with-agent-deployment#comment_35143692

**Comment by Martaver** [comment]
Leaving my footprint here too... http://help.appveyor.com/discussions/questions/1360-using-the-appveyor-deployment-agent-how-do-i-run-a-ps-script-once-all-my-deployments-have-finished

I'd also find this useful.

**Comment by Martaver** [comment]
Hi Feodor,

Just noting that we have a real-world need for this feature. At the moment we're deploying a 'dummy' project in conjunction with your recent 'deployment order' hotfix to offline sites & services before they are deployed.

Ideally, the global scripts would have access to a collection of deploying artifacts and their metadata incl. types (site, service, msi etc).  

Alternatively, each deployable project could have 'globalbeforedeploy.ps1' and 'globaldeploy.ps1' files which are grouped and run at either end of the deployment set.

Is there a plan for this implementing this feature?

**Comment by FeodorFitsner** [comment]
"Dummy" project is exactly what I was about to propose as a workaround, especially now when we have `deploy_order`.

Rather than "fixing" the current architecture of deployment environments we'd like to focus on its re-design that is currently going on and based on `appveyor.yml`.

**Comment by Martaver** [comment]
Okay, sounds great! Is there something published that I can follow along regarding the future plans for deployments? I'm really interested in this stuff...

**Comment by FeodorFitsner** [comment]
Not yet, but I'm going to have design document very soon, available for your comments.

**Comment by Martaver** [comment]
Looking forward to it!

**Comment by IlyaFinkelshteyn** [comment]
Implemented a while ago. Docs: https://www.appveyor.com/docs/deployment/agent/#running-powershell-scripts-on-target-server-during-deployment
