### ISSUE TITLE
Request: Use Milestones & Labels

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#442]
Hi Feodor. 

With this issues list, could you start to use Milestones and Labels, please? This way we can all get some loose idea about the rollout (if at all) of any of these issues and very loose ETA's.

For example, if something has been tagged as `BACKLOG` or whatever the equiv is .. we get that, that idea might be nice but not planned, etc. Or whatever rules you devise.

---
### Clarification:

When I mention `Milestones` I mean posting them way before. So we can see things nice and clear. 

I noticed that you do use Milestones but it feels that it's as a form of tagging ... as in .. "_I've pushed some bugs/features up. so lets create a milestone, throw those issues into there and close asap._" <-- feels re-active instead of pro-active.

Suggestions:
- `Dec 2015 Build`
- `Jan 2016 Build`
- `.NET CoreCLR / .NET DesktopCLR / .NET Pew Pew Whatever`
- `User profile refactor`

etc..

of course names can change, but we get an overall idea of what you're thinking about releasing or fixing.

**Comment by IlyaFinkelshteyn** [comment]
We are using both right now :)
