### ISSUE TITLE
Go 1.5.1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#456]
Discussion: http://help.appveyor.com/discussions/problems/3255-can-golang-build-be-selectable-for-multiple-version-just-like-how-nodejs_version-is-implemented

**Comment by nathan-osman** [comment]
:+1: I have a Go application that requires the `mime/quotedprintable` package from Go 1.5.

**Comment by mvadu** [comment]
@FeodorFitsner Hi, is this implemented in any way currently? I see that you have go 1.6 by default, and for my need (InfluxDB fork) I need go 1.4.3.

**Comment by FeodorFitsner** [comment]
These are Golang versions installed on build workers: http://www.appveyor.com/docs/installed-software#go

You just need to add a line setting correct path, for example:

    set PATH=C:\go15\bin;%PATH%

**Comment by mvadu** [comment]
Thanks @FeodorFitsner that was very easy!! Btw its impressive how easy to setup the whole testbed  on your platform. Thank you for an amazing work.
