### ISSUE TITLE
Python 3.5 problems on "unstable" image

### ISSUE THREAD

**Issue by vasily-v-ryabov** [appveyor/ci#459]
I've tried Python 3.5 in my [appveyor.yml](https://github.com/vasily-v-ryabov/pywinauto/blob/master/appveyor.yml), but [the build fails](https://ci.appveyor.com/project/pywinauto/pywinauto-8b7t7/build/0.5.3.114) on calling `pip` (it's not found).

I think Python 3.5 is not installed on "unstable" image because incorrect python version is printed.

```
Build started
Fetching repository commit (a17ac73)...OK
Total: 24.8 MB in 339 files
Running Install scripts
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
%CMD_IN_ENV% python --version
Python 2.7.9
%CMD_IN_ENV% python -c "import struct; print(struct.calcsize('P') * 8)"
32
%CMD_IN_ENV% pip install --disable-pip-version-check --user --upgrade pip
'pip' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

**Comment by FeodorFitsner** [comment]
Why do you need "unstable" image?

**Comment by vasily-v-ryabov** [comment]
We need it for testing GUI automation Python library. [It works well](https://ci.appveyor.com/project/pywinauto/pywinauto-8b7t7/build/0.5.3.106) on Python 2.7/3.3/3.4.

**Comment by FeodorFitsner** [comment]
You should be able to do that on default image. No need to use unstable anymore.

**Comment by vasily-v-ryabov** [comment]
Wow! Great! Thanks a lot!
