### ISSUE TITLE
ASP.NET 5 Beta 8

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#460]
Discussions: http://help.appveyor.com/discussions/problems/3283-aspnet-5-beta-8-requires-httpplatformhandler-msi-installed-on-build-server

**Comment by sirkirby** [comment]
with beta 8 supported, will I still need to do the `dnvm instal 1.0.0-beta8` and `dnu restore` in my build script?

**Comment by FeodorFitsner** [comment]
Well, actually `dnvm` comes along with ASP.NET 5 Beta 8 upgrade, so I don't think you have to install again.

**Comment by BrianVallelunga** [comment]
How exactly do I specify a system with ASP.NET 5 Beta 8 already installed? I'm using the standard Visual Studio 2015 VM and it doesn't have DNVM or DNX at all.

**Comment by FeodorFitsner** [comment]
What account/project is that?

**Comment by sirkirby** [comment]
I'm having the same experience...I still have to run the install prior to building my project in the latest vs 2015 image.

**Comment by BrianVallelunga** [comment]
Ugg... I think there's a bug. My settings for the project had VS 2015 set. As such, I left the version blank in my appveyor.yml file. Unfortunately, the setting in the UI was not honored at all. Adding `os: Visual Studio 2015` fixed the issue. I feel like this is a bug.

**Comment by FeodorFitsner** [comment]
It's expected behavior. Whenever appveyor.yml is found and can be downloaded from branch UI settings are ignored. The only exceptions here are environment variables and notification settings defined on UI which are "merged" into appveyor.yml.

**Comment by BrianVallelunga** [comment]
Thanks, I'm new to this and assume they were always merged, with the appveyor.yml overwriting the UI settings. Maybe the build log should output that info on start-up. It would have saved me a few hours.
