### ISSUE TITLE
Delete a single build / all builds?

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#461]
Ability to delete 
- a single build
- all builds in the project

ref: [original thread](http://help.appveyor.com/discussions/questions/1777-delete-a-singleall-builds)

**Comment by ravensorb** [comment]
any upgrades on this request?

**Comment by rstarkov** [comment]
:+1:

**Comment by peto268** [comment]
Any updates on this? I too would really enjoy this feature.

**Comment by FeodorFitsner** [comment]
It's been implemented.
