### ISSUE TITLE
Python 2.6

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#463]
https://www.python.org/downloads/windows/

**Comment by mvmf** [comment]
@FeodorFitsner thanks for your fast response on the issue. It would be great to have py26 in both flavours x86 and x64 installed. Best download option would be https://www.python.org/download/releases/2.6.6/ I guess.

**Comment by wbond** [comment]
This would be excellent and would reduce the load I put on the workers for a couple of open source Python packages I write.

**Comment by mackevision** [comment]
:+1: again, we are impressed of the fast response. Thank you.
