### ISSUE TITLE
Native mingw-w64 support

### ISSUE THREAD

**Issue by matysek** [appveyor/ci#466]
In your project we need mingw-w64 to compile some C code.
- mingw-w64 contains some features that are not available in classical mingw.
- Appveyor provides mingw however our project uses some features that are available only in mingw-w64.
- As a workaround we use chocolatey - command `choco install -y mingw -x86` to install mingw-w64.
- It takes about 10-15 min. to install just mingw-w64.

Could it be possible to have `mingw-w64` already built-in so we could avoid this extra tedious step?

**Comment by FeodorFitsner** [comment]
Is it a right command `choco install -y mingw -x86` (x86?)

**Comment by matysek** [comment]
> Is it a right command choco install -y mingw -x86 (x86?)

Yes, it is because it installs 32bit mingw-w64. I need to build 32bit binaries.

**Comment by matysek** [comment]
* command `choco install -y mingw` will on 64bit windows install into `C:\tools\mingw64`.
* command `choco install -y mingw -x86` will on 64bit windows install into `C:\tools\mingw32`.
