### ISSUE TITLE
Git Large File Storage

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#468]
Discussion: http://help.appveyor.com/discussions/questions/1815-add-git-lfs-support-to-default-build-images

Download URL: https://git-lfs.github.com/

**Comment by cschroed-usgs** [comment]
Was git lfs support added to the default image?

**Comment by FeodorFitsner** [comment]
Yes.

**Comment by cschroed-usgs** [comment]
Thanks for confirming!
