### ISSUE TITLE
Webhooks decrease verbosity of labeled actions and maybe assign own configurable field.

### ISSUE THREAD

**Issue by un1versal** [appveyor/ci#469]
The verbosity level of the webhooks is extreme (to flood levels) to say the very least and can become very annoying very quickly.

For instance

**Pull Request**
Pull Request opened, closed, assigned, **labeled**, or synchronized.

If you label a pull request or issue with 3 labels you get 3 notification on channel. if you label with 4 labels 4 notifications, and if you change your mind and unlabel 1 or 2 labels it you soon have a flood in channel.

My suggestion is to cut the label/unlabelled action notification to 1 notification per any 10 seconds.
for instance:
Add one label (some silent timer is started) 1 notification is sent, anything within those 10 seconds after first notification has been sent on label/unlabelled could be ommited.

That could be configurable or not. but just cutting out the unwanted spam is already a benefit.

In my option there are many notification that could do with moving to own field and even making configurable, especially those which like lable have the potential to cause unneeded spam flood.

**Comment by FeodorFitsner** [comment]
How is it relevant to AppVeyor? Looks like an issue for GitHub.

**Comment by un1versal** [comment]
So who develops appveyors hooks for github? And wheres this dev taking pace?

**Comment by un1versal** [comment]
Never mid Im reporting this to github and linking this report to it, up to you if you want to close or leave open or whatever suits.

Thanks.
