### ISSUE TITLE
Feature request: Ability to mark build as failed if peripheral scripts failed

### ISSUE THREAD

**Issue by manastalukdar** [appveyor/ci#471]
As of now if say the script run as after_test failed, that does not allow us to make the build itself as having failed. While I understand this default behavior, it would be useful to have the option to be able to say, mark the build as failed is after_test failed. This should be applicable for:

before_test, after_test, before_build, after_build, before_deploy, after_deploy

**Comment by FeodorFitsner** [comment]
If there is non-zero exit code or PowerShell exception in `after_test` the build will fail. What do you have there in your case?

**Comment by manastalukdar** [comment]
Yes, you are correct. A powershell warning (not a non-zero exit code) during after_test resulted in build pass, not a poweshell error (a non-zero exit code). 

But, in general,
>>If there is non-zero exit code or PowerShell exception in after_test the build will fail.<< 
should also be true for before_build, after_build, before_deploy, after_deploy, if it isn't already.

I am closing this request for now.
