### ISSUE TITLE
test job keeps running after a timeout

### ISSUE THREAD

**Issue by oconnor663** [appveyor/ci#478]
See https://ci.appveyor.com/project/oconnor663/duct/build/1.0.12/job/irifecelg477mqo7

I'm running Python tests on Appveyor, and I invoke them as `py.test --timeout=5`. One of my tests is hanging (my fault), so the timeout triggers and terminates my tests. For some reason though, the Appveyor test run keeps going. I can confirm by running the same command in my own terminal, that the py.test process does die after the timeout, and that it returns error code 1. Do I need to do anything special to help Appveyor detect that my tests have failed?

**Comment by FeodorFitsner** [comment]
If the test process spawns child processes then this might prevent it from exiting. Try wrapping that `py.test --timeout=5` into some `test.cmd` and then running it from appveyor.yml.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
