### ISSUE TITLE
F# 4.0 RTM for Visual Studio 2015

### ISSUE THREAD

**Issue by laedit** [appveyor/ci#483]
I know that the [Visual F# Tools 4.0](https://www.microsoft.com/en-us/download/details.aspx?id=48179) are only RTM for now, but it is already delivered with Visual Studio 2015.
Is it possible to update it?

**Comment by FeodorFitsner** [comment]
Sure, will do.

So, VS 2015 RTM was shipped with non-RTP F# 4.0?

**Comment by laedit** [comment]
I've just looked on my VS and it looks like it's not even the RTM:
Microsoft Visual F# 2015 RC

**Comment by FeodorFitsner** [comment]
Got it. Let update it then.
