### ISSUE TITLE
Allow pull request build on public repo for owner/collaborators PR

### ISSUE THREAD

**Issue by kittikun** [appveyor/ci#485]
Following up the discussion on the [support forum](http://help.appveyor.com/discussions/suggestions/873-about-encoded-private-keys-and-pull-requests)

Because of a security concern, PR builds are currently built only for private repos.
It would be nice to allow pull request for public repo to be built too. If restricted to owner/collaborators there shouldn't be any security issues.

**Comment by FeodorFitsner** [comment]
Closing this item in favor of https://github.com/appveyor/ci/issues/917
