### ISSUE TITLE
NuGet nuspec enhancements

### ISSUE THREAD

**Issue by PureKrome** [appveyor/ci#49]
**Problem**: solutions can have multiple `.nuspec` files per solution. Each `.nuspec` will be used to create a package and push it up to NuGet gallery. AppVeyor *currently* can't handle this.

**Solution**: AppVeyor can do the following:
- Check the developer specified location (either in a `.yaml` file or the settings GUI)  for 1+ nuspec files. - If nothing found (or no location specified) have a *convention* that checks for 1+ nuspecs files into the harcoded locations. eg.
-- `\root\*.nuspec`
-- `\root\nuspec\*.nuspec`
-- `\root\nuspec files\*.nuspec`

etc..

Here's an example screen shot I cooked up to help explain this...

![wee!](http://i.imgur.com/4fWiBTQ.png)

thanks!

**Comment by luisrudge** [comment]
Yeah.. Not being able to generate more than 1 package is a shame..

**Comment by PureKrome** [comment]
This issue is really old so I might close it mainly because I've had a successful work around for ages - a custom powershell script in the `on_success` stage, [like this one](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/AppVeyor/appveyor.yml#L34).
