### ISSUE TITLE
Python 2.7 upgrade issue

### ISSUE THREAD

**Issue by isuruf** [appveyor/ci#492]
With the recent upgrade we are seeing issues in libpython2.7.a (https://ci.appveyor.com/project/isuruf/symengine-py-l1jmr/build/54) when compiling mingw extensions. It seems recent changes changed the python installation to a release with bugs. 

See https://bugs.python.org/issue24385

cc @certik

**Comment by certik** [comment]
How is that file generated? We need to compile it ourselves using mingw.

**Comment by isuruf** [comment]
Patches can be found here, http://www.lfd.uci.edu/~gohlke/pythonlibs/#libpython

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
