### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Mogztter** [appveyor/ci#493]
I'm using a Rake task to download the latest release of JDK8 and JDK9 from https://jdk9.java.net/download/ and https://jdk8.java.net/download.html ([source code](https://github.com/asciidoctor/asciidoctor.js/blob/master/rake/jdk_helper.rb#L48))

The [build was working great](https://ci.appveyor.com/project/asciidoctor/asciidoctor-js/build/334) but  now I get the following error: `Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect` ([build#405](https://ci.appveyor.com/project/asciidoctor/asciidoctor-js/build/405)).

Am I doing something wrong ? How can I troubleshoot this error ?

Thanks!

**Comment by Mogztter** [comment]
I can reproduce this issue from another machine, not related to Appveyor.
Sorry for the noise :(

**Comment by FeodorFitsner** [comment]
OK, thanks for the update!



- Feodor
