### ISSUE TITLE
Add support for Clang-cl

### ISSUE THREAD

**Issue by ldionne** [appveyor/ci#495]
I am trying to setup continuous integration on Windows for a C++14 metaprogramming library called [Boost.Hana](https://github.com/boostorg/hana). The library being quite cutting edge, it requires a fully compliant C++14 compiler. Right now, this means that only Clang will do.

I was told by a user of the library that Clang-cl (provided by LLVM [here](http://llvm.org/releases/download.html#3.7.0) under __Clang for Windows (64-bit)__) was enough to compile the library. Unfortunately, I have been trying unsuccessfully to install it and I would like to request native support for that compiler.

Related to boostorg/hana#201, in particular [here](https://github.com/boostorg/hana/issues/201#issuecomment-156007552) in the discussion.

**Comment by FeodorFitsner** [comment]
LLVM 3.8 will be installed to support that: https://github.com/appveyor/ci/issues/688
