### ISSUE TITLE
node 5.0.0 X64 package not found

### ISSUE THREAD

**Issue by Mithgol** [appveyor/ci#497]
The job https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.424/job/k5hlj0kcy40ubgq1 fails with the message `node 5.0.0 X64 package not found` on line 27 of its logs.

It was testing mapbox/node-sqlite3@2ae5a5aba47674c2d3d1fc9f1a16f4d4bff28e2a where the file [`scripts/build-appveyor.bat`](https://github.com/mapbox/node-sqlite3/blob/2ae5a5aba47674c2d3d1fc9f1a16f4d4bff28e2a/scripts/build-appveyor.bat) echoes `downloading/installing node` [on line 32](https://github.com/mapbox/node-sqlite3/blob/2ae5a5aba47674c2d3d1fc9f1a16f4d4bff28e2a/scripts/build-appveyor.bat#L32) and then calls `powershell Install-Product node $env:nodejs_version $env:Platform` [on line 37](https://github.com/mapbox/node-sqlite3/blob/2ae5a5aba47674c2d3d1fc9f1a16f4d4bff28e2a/scripts/build-appveyor.bat#L37).

I believe that's what causes `downloading/installing node` and then immediately `node 5.0.0 X64 package not found` in logs.

The job's heading indicates that environment variables were set to `nodejs_version=5.0.0` and `platform=x64`.

If the above given assumptions are correct, then the question is, why `powershell Install-Product node 5.0.0 x64` fails?

**Comment by FeodorFitsner** [comment]
"x64" should be lower case.
