### ISSUE TITLE
NuGet randomly failing

### ISSUE THREAD

**Issue by ARMmaster17** [appveyor/ci#504]
In my repository NETponents/Gerbil on the dev branch, AppVeyor randomly fails on the `nuget restore` command. Specifically, it stops when it can't find OpenCover v4.6.166. I know it is not a configuration error as it sometimes works and sometimes doesn't. NUnit.Runners also sometimes exhibits similar behavior.

**Comment by FeodorFitsner** [comment]
Can you drop a link to a build please?

**Comment by ARMmaster17** [comment]
Here's one from last night where all jobs failed with the mentioned issue:

https://ci.appveyor.com/project/ARMmaster17/gerbil/build/0.1.154-nightly

**Comment by ARMmaster17** [comment]
Here's the same build being triggered on Travis CI (Linux) to verify that this not a configuration problem:

https://travis-ci.org/NETponents/Gerbil/builds/92033727

**Comment by FeodorFitsner** [comment]
This happens sometimes. Error `Unable to find version 'X' of package 'Y'` usually means there is an index synchronization issue on NuGet.org side. Here you can find some recommendation how to deal with that: http://www.appveyor.com/docs/nuget#restore-with-retries

**Comment by ARMmaster17** [comment]
Thanks!
