### ISSUE TITLE
Python 2.7.10 (Pro environment)

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#507]

**Comment by bjorn** [comment]
Since Python 2.7.10 I am seeing linker errors like the following that I did not see with Python 2.7.9:
```
error: undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
```
On my home PC this issue is resolved again with [Python 2.7.11](https://www.python.org/downloads/) (released december 5th), so I'd really like to see AppVeyor's Python updated again.

**Comment by FeodorFitsner** [comment]
I see - there are 2.7.11 and 3.5.1 released. Will do their deployment this week.

**Comment by FeodorFitsner** [comment]
Added https://github.com/appveyor/ci/issues/556 and https://github.com/appveyor/ci/issues/557

**Comment by FeodorFitsner** [comment]
Python 2.7.11 has been deployed to all build workers.
