### ISSUE TITLE
Default curl build has problems. Suggestion: use the Git for Windows build as default

### ISSUE THREAD

**Issue by vszakats** [appveyor/ci#511]
After the November 20 update, there are two `curl.exe`s available in the build machines:
* `curl 7.45.0 (x86_64-pc-msys) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32 libssh2/1.6.0`
   as per `which curl` this is found in `/usr/bin/curl`. Not sure which native folder it translates to.
* `curl 7.45.0 (x86_64-w64-mingw32) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32 libssh2/1.6.0 librtmp/2.3`
   in `C:\Program Files\Git\mingw64\bin\` as part of Git for Windows.

Of these, the first one is in the `PATH`, so it runs when calling `curl` without a path.

But, apparently this default curl build has strange problems when parsing and processing the command-line, so in practice it can not work as expected. F.e. when trying to pass an on-disk file via the `-d @<file.ext>` option, instead of passing the file as-is, it will be truncated and part of the file interpreted as if being part of the command-line. See: https://ci.appveyor.com/project/vsz/harbour-core/build/3.4.657#L2205

Adding `C:\Program Files\Git\mingw64\bin` to the beginning of `PATH` will switch to the native (non-MSYS) build of `curl`, and [resolves these problems](https://ci.appveyor.com/project/vsz/harbour-core/build/3.4.661#L2203). Therefore, I'd suggest to do this in the default setup.

**Comment by FeodorFitsner** [comment]
There is another `git.exe` in `C:\Program Files\Git\mingw64\bin` directory - I'm afraid it could be conflicting with the one in `C:\Program Files\Git\cmd`.

**Comment by vszakats** [comment]
It looks that the `git.exe` copy inside `C:\Program Files\Git\cmd` acts as a stub/launcher for the `git.exe` inside `C:\Program Files\Git\mingw64\bin`, so, I believe it should not make any harm to start the latter directly.

Anyhow, if you add `C:\Program Files\Git\mingw64\bin` _after_ `C:\Program Files\Git\cmd` to the `PATH`, this should become a non-issue, because the same `git.exe` will be launched as now.

**Comment by vszakats** [comment]
Just noticed that the "other" curl resides in Git for Windows's `usr\bin` subdirectory. This makes my suggestion unworkable and probably a bug report would be needed, or this will be a situation where certain command-line notations are clashing. Sorry for the noise.
