### ISSUE TITLE
filter test to run depending on configuration matrix

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#513]
Hi

I am using CppUnit as testing framework and there is a need to launch unit tests under test_script depending on the configuration matrix. Can this feature be added?

Thanks

**Comment by FeodorFitsner** [comment]
You can just use batch or PowerShell script and check environment variable. Give me more details about your case and I'd suggest a solution.

**Comment by zosrothko** [comment]
OK I got it. Thanks
