### ISSUE TITLE
Build notification for bitbucket repositories

### ISSUE THREAD

**Issue by atagirov** [appveyor/ci#514]
Bitbucket publish new future - build state for commits - http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/
It will be good - integrate this into build notifications as provider - http://www.appveyor.com/docs/notifications

**Comment by FeodorFitsner** [comment]
API: https://confluence.atlassian.com/bitbucket/buildstatus-resource-779295267.html

**Comment by FeodorFitsner** [comment]
I think it should be implemented as a built-in standard feature, like it's done for GitHub, not a notification provider.

**Comment by FeodorFitsner** [comment]
It's been implemented and deployed.

**Comment by atagirov** [comment]
great, thanks :+1:
