### ISSUE TITLE
Configurable time limit

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#517]
It seems the time limit on JuliaLang/julia (under StefanKarpinski account) was recently changed to an hour. This is actually a bad thing since we are having really frequent timeouts, and sitting longer waiting for the time limit makes our queue worse. Could this be a yml configurable option?

Happy Thanksgiving.

**Comment by KindDragon** [comment]
:+1:

**Comment by tkelman** [comment]
Some of our freezes might be our bug, and some might be appveyor-specific issues, we can't always tell. But this one was definitely on appveyor's side, stuck while restoring from the build cache: https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.11566/job/a520sjq05u6fmv2o

We've had a few that looked like that, not fun to have one worker stuck for a whole hour every time that happens.

**Comment by FeodorFitsner** [comment]
Well, yes. Instead of controllable build timeout maybe it'd better having something like "Terminate build is log is not changing for X minutes"?

**Comment by tkelman** [comment]
If it's optional, that could work. Travis does that with a 10 minute default that you can't change, and I've occasionally had to come up with hacky workarounds there (they also fail jobs whose logs get longer than 4 MB).

I suspect most repo's builds and tests should usually run in a fairly predictable amount of time?

**Comment by dankan1890** [comment]
:+1:

**Comment by lygstate** [comment]
Ping for this, timeout should be configurable.

**Comment by tkelman** [comment]
Any update here on either configurable max or optional timeout-if-no-output? If not, can I request JuliaLang/julia have its timeout set to 1hr instead of 2hr for now?

**Comment by FeodorFitsner** [comment]
Sure, overall build time decreased to 60 minutes.

**Comment by chfast** [comment]
I'm not sure what the status is, but can I also ask to increase the time limit for ethereum/evmjit to more than one hour? I plan to cache most of the build dependencies but they need to be built first.

**Comment by FeodorFitsner** [comment]
@chfast  What is corresponding AppVeyor project URL for that?

**Comment by chfast** [comment]
https://ci.appveyor.com/project/chfast/evmjit

**Comment by FeodorFitsner** [comment]
OK, `ethereum` account is on trial and running on Pro environment. Does it work better for you?

**Comment by HyukjinKwon** [comment]
Could I please ask to increase the time for mine if possible? (It is https://ci.appveyor.com/project/spark-test/spark)

**Comment by FeodorFitsner** [comment]
@HyukjinKwon increased

**Comment by HyukjinKwon** [comment]
@FeodorFitsner Thank you so much for a quick action. It seems increased up to 1 hour and 30 minutes (Is this true?). I just wonder if it can be up to about 4 hours by any chance if it is fine. 

Currently, running the tests of Apache Spark takes roughly about 2 - 3 hours on Linux via Jenkins so, I guess it would take similar time on Windows as well.

I would try to work around by manually running the tests separately though if it is not feasible. I hope it is possible.

**Comment by IlyaFinkelshteyn** [comment]
@HyukjinKwon we cannot increase build time that much. However you can leverage [parallel testing](https://www.appveyor.com/docs/parallel-testing/) for your goal. Though they will not be executed in parallel (as your plan does not allow it), but if you group them so single group execution will not be longer than maximum build time they all will be executed.

**Comment by HyukjinKwon** [comment]
@IlyaFinkelshteyn Thank you so much sincerely. I will try to follow the suggestion.

**Comment by HyukjinKwon** [comment]
Hi @FeodorFitsner and @IlyaFinkelshteyn, just for @IlyaFinkelshteyn's suggestion, it works great per my intention. Thank you.

I happened to come back for another (gentle and kind) request. Just to provide the context in case, I was testing Apache Spark's Scala/Java related unit tests which takes about 2/3 hours in my case. 
In case of Apache Spark itself with ApacheSoftwareFoundation account, it runs AppVeyor tests only with R API currently which took, well, roughly 40-50 mins before. However, I and some guys observed that it now rarely hits one hour limitation, e.g.,  https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/build/824-master/messages

It seems it was so close to the end of tests but ended with hitting the limit.

```
[00:59:47] DONE ===========================================================================
```

It seems now it takes about 55 mins in general.

To resolve this problem, I think the test/build time should be decreased and/or tests should be split as I did before in my account. I will try to raise an issue about this in Spark side and try to resolve this at my best. However, I wonder it can be easily done to increase the time to 1.5 hours just as a first step in AppVeyor side.

To cut it short, could I please ask to increase the limit to 1.5 hours for this `ApacheSoftwareFoundation` account too if it could be easily done?

**Comment by FeodorFitsner** [comment]
Build timeout for `ApacheSoftwareFoundation` account has been increased to 90 minutes.

**Comment by HyukjinKwon** [comment]
Thank you so much for your help.

**Comment by EricWF** [comment]
@FeodorFitsner @IlyaFinkelshteyn First thank you for offering this service and underlying resources free to open source projects. It's greatly appreciated.

However I was wondering. Is the goal of time limits to prevent projects from hogging resources? If so is it effective at achieving that goal?

For example, An  OSS project may be active enough that it always has queued commits and therefore is always using the maximum number of resources (2 threads x 24 hours a day). From Appveyors point of view what's the difference between that project having 10 minute build times or 3 hour build times?

I apologize If I'm way off base about the rational for time limits. Thanks again.

**Comment by FeodorFitsner** [comment]
@EricWF It's been increased to 90 minutes. Let me know how that worked.

**Comment by EricWF** [comment]
I haven't seen anything go over an hour yet, but I'll let you know if there are any problems.

@FeodorFitsner Thank you for all the support. If you ever need any help with LLVM on Windows I would love to return the favor.

**Comment by FeodorFitsner** [comment]
You're welcome! 😸

**Comment by arokem** [comment]
Hi! Any chance we could get an increase for the time-out duration for our open-source neuroimaging project, https://github.com/nipy/dipy? Thanks!

**Comment by IlyaFinkelshteyn** [comment]
@arokem Yes, we can increase it, but I cannot find project connected to that repository on AppVeyor. I found [this one](https://ci.appveyor.com/project/arokem/dipy) but I am not sure this is what you need to increase timeout for.  Can you please confirm that I found right project or send us a link to the correct one?

**Comment by arokem** [comment]
Thanks! Yeah - that's the project. For now, we don't have an appveyor file in master, but we have a PR to add it here: https://github.com/nipy/dipy/pull/787. That PR gets exercised on my fork of the project: https://github.com/arokem/dipy/pull/23. For the time being, if we could get the time-out extended for my fork, we can keep trying it out there. Once we have things sorted out there, we will merge it into our master branch. Does that make sense?

**Comment by IlyaFinkelshteyn** [comment]
Sure, done!

**Comment by thewtex** [comment]
Hola :-). Could we also please get the time limit increased for this repository?:

  https://github.com/CastXML/CastXMLSuperbuild

It looks like the build almost completed before it hit the 60 minute limit.

Thank you!

**Comment by IlyaFinkelshteyn** [comment]
@thewtex  can you please clarify your AppVeyor account? I found [thewtex](https://ci.appveyor.com/project/thewtex/castxmlsuperbuild/history) but it does not look like builds there failed with timeout...

**Comment by thewtex** [comment]
@IlyaFinkelshteyn [here's](https://ci.appveyor.com/project/thewtex/castxmlsuperbuild/build/0.0.1.15) the timeout build.

**Comment by IlyaFinkelshteyn** [comment]
@thewtex OK, enjoy 90-minute timeout :)

**Comment by thewtex** [comment]
@IlyaFinkelshteyn Thank you!! :smile:

**Comment by jeroen** [comment]
Hi! I am building the Windows binaries for the r-project. I am hitting the 60min timeout, would it be possible to raise this? https://ci.appveyor.com/project/jeroen/base/build/1.0.2/messages

**Comment by IlyaFinkelshteyn** [comment]
@jeroen done, 90 minutes too!

**Comment by peterjc123** [comment]
@IlyaFinkelshteyn Can I get the limit increased for this [project](https://github.com/peterjc123/pytorch)?
The timeout build is [here](https://ci.appveyor.com/project/peterjc123/pytorch-elheu/build/job/fj4843dl2s8ca3ho).

**Comment by IlyaFinkelshteyn** [comment]
@peterjc123 yes, 90 mins now!

**Comment by UnaNancyOwen** [comment]
Hi @IlyaFinkelshteyn, 
We want to running [PCL](https://github.com/PointCloudLibrary/pcl/pull/2137) test on AppVeyor, but it failed because of a timeout. ([timeout build](https://ci.appveyor.com/project/PointCloudLibrary/pcl/build/1.0.210))
Can I extend the timeout limit up to 90 min. for this [project](https://github.com/PointCloudLibrary/pcl)?
Thanks,

**Comment by IlyaFinkelshteyn** [comment]
@UnaNancyOwen done.

**Comment by UnaNancyOwen** [comment]
@IlyaFinkelshteyn Thanks! 😄

**Comment by TimoRoth** [comment]
We could also use some more time on https://ci.appveyor.com/project/TimoRoth/oggm-anaconda/build/1.0.157
I disabled the tests for now, so uploading new builds blind, but I'd like to keep the tests active for obvious reasons.

**Comment by IlyaFinkelshteyn** [comment]
@TimoRoth sure, done.

**Comment by bgamari** [comment]
The Glasgow Haskell Compiler (https://ci.appveyor.com/project/bgamari/ghc-wohl3/build/15) could also use more time.

**Comment by IlyaFinkelshteyn** [comment]
@bgamari done.

**Comment by yasserf** [comment]
Would it be possible to also increase the limit on deepstream.io? We compile nodeJS after injecting some C++ and the node 8 version sadly requires a bit more than 60minutes =(

Thanks!

https://ci.appveyor.com/project/yasserf/deepstream-io/build/1.0.1806

**Comment by IlyaFinkelshteyn** [comment]
@yasserf done

**Comment by RalfKoban** [comment]
@IlyaFinkelshteyn Would it be possible to **decrease** the limit to 5 minutes?
https://ci.appveyor.com/project/RalfKoban/miko-analyzers

**Comment by IlyaFinkelshteyn** [comment]
@RalfKoban we can do that but this will apply to all projects under your account. Are you still sure you need it?

**Comment by RalfKoban** [comment]
@IlyaFinkelshteyn Oh, I was not aware of that it would affect all my projects. So please don't adjust it.

**Comment by bgamari** [comment]
@IlyaFinkelshteyn, are you certain that the GHCAppveyor build time limit has been increased? We are still seeing builds failing after hitting the 60 minute limit. See, for instance, https://ci.appveyor.com/project/GHCAppveyor/ghc/build/88/messages.

**Comment by IlyaFinkelshteyn** [comment]
@bgamari sorry you are right, it was not changed for some reason. Should be 90 mins now.

**Comment by domenkozar** [comment]
@IlyaFinkelshteyn could you also change https://ci.appveyor.com/project/input-output/ to 90min? 

For GHC users I recommend using https://github.com/fpco/cache-s3 - it's much better than native appveyor caching.

**Comment by IlyaFinkelshteyn** [comment]
@domenkozar done.

**Comment by yuvalmesika** [comment]
@IlyaFinkelshteyn can you please increase build time for https://ci.appveyor.com/project/JivyGroup/platfromtrunk
Does the limit affect all projects in the account (I hope so) ?

**Comment by IlyaFinkelshteyn** [comment]
@yuvalmesika yes and yes. done.

**Comment by miho** [comment]
Hi @yuvalmesika ,

for our research group we are looking for a CI solution that works great with GitHub and offers Visual Studio support. AppVeyor seems like a perfect fit for our open source projects and I am already able to use it for some of them. But unfortunately, I hit the one hour limit for a large C++ code base. Is there a way we could extend the build time for our accounts (https://github.com/miho and https://github.com/UG4, https://github.com/VRL-Studio )?

Thanks a lot!

**Comment by IlyaFinkelshteyn** [comment]
@miho, we can set it to 90 minutes for free, just let us know your AppVeyor account name or just AppVeyor project(s) URL(s).

For bigger limit you need to set up [private build cloud](https://www.appveyor.com/docs/build-environment/#private-build-cloud), but this option is not for free. We can provide more details if needed.

**Comment by miho** [comment]
90 minutes will probably work for us. Thanks for offering this free option. This is my account: https://ci.appveyor.com/project/miho .

**Comment by IlyaFinkelshteyn** [comment]
@miho we set 90 minutes for your account.

**Comment by miho** [comment]
@yuvalmesika  thanks a lot!

**Comment by IlyaFinkelshteyn** [comment]
I am not @yuvalmesika :)

**Comment by miho** [comment]
@IlyaFinkelshteyn sorry :)

**Comment by billziss-gh** [comment]
Any chance I could get the special 90 minute limit for [winfsp](https://github.com/billziss-gh/winfsp)? I run two jobs and one of the jobs is now hitting 57 minutes on some builds.

BTW, thank you for making AppVeyor freely available for open source projects. If AppVeyor did not exist, I find it unlikely that my project (a file system driver) would be nearly as stable as it is.

**Comment by IlyaFinkelshteyn** [comment]
@billziss-gh sure, increased :) And thank you, this is encouraging!

**Comment by billziss-gh** [comment]
@IlyaFinkelshteyn thank **you** for the always amazing (and free!) support.

**Comment by lucienboillod** [comment]
Hello, is there any chance to get the 90 minutes limit for llvm-conan package ? It's open source package aiming to be pushed on bincrafters repository, but the job reach more than 1hour (https://ci.appveyor.com/project/lucienboillod/conan-llvm)

**Comment by IlyaFinkelshteyn** [comment]
@lucienboillod Sure, it is 90  mins now :)

**Comment by billziss-gh** [comment]
@IlyaFinkelshteyn 

I received the message "Build execution time has reached the maximum allowed time for your plan (60 minutes)."

https://ci.appveyor.com/project/billziss-gh/winfsp/build/1064/job/asny1v29i4hjkkaa/messages

Perhaps the change to 90 mins did not take place or was reverted for some reason?

**Comment by IlyaFinkelshteyn** [comment]
@billziss-gh sorry, should be 90 minutes now.

**Comment by billziss-gh** [comment]
@IlyaFinkelshteyn thank you!

**Comment by lucienboillod** [comment]
@IlyaFinkelshteyn Thanks you for the amazing support!

**Comment by lucienboillod** [comment]
@IlyaFinkelshteyn my package is over 90 min, it is still llvm for open source conan project https://ci.appveyor.com/project/lucienboillod/conan-llvm/build/1.0.26/job/ufyvd8upuiqyaae5
 I don't now how to do with free plan to continue the work on it

**Comment by IlyaFinkelshteyn** [comment]
@lucienboillod please try to use [build cache](https://www.appveyor.com/docs/build-cache/) to speed up the build. Also I would strongly recommend to use [commits filtering](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits-2) to avoid builds like [this](https://ci.appveyor.com/project/lucienboillod/conan-llvm/build/1.0.26) which is about to consume roughly 18 hours for one word change commit in readme file. FYI AppVeyor is small bootstrap company and we carry all compute expenses ourselves to provide free builds for open source, and we expect responsible usage.

**Comment by lucienboillod** [comment]
@IlyaFinkelshteyn  As you can see I always stop build when there is minor change, I was not aware of commits filtering thanks for that! I will try to use build cache, for next build, do you think it will be enough ?

**Comment by m-tmatma** [comment]
Do you have a plan to support this?

**Comment by IlyaFinkelshteyn** [comment]
@m-tmatma  right now, you can configure build time of you  use [private build cloud](https://www.appveyor.com/docs/build-environment/#private-build-cloud), e.g. your own build workers managed by AppVeyor. For those who use AppVeyor workers (default option) we increase (in a sensible limits) by request. We can set it to 90 minutes for you too :) Or you want to be able to decrease?

**Comment by m-tmatma** [comment]
I don't need to prolong the timeout now.
When appveyor hangs, I want to shorten the timeout.
But the timeout is account-wide, it is not easy to adapt it.

**Comment by IlyaFinkelshteyn** [comment]
@m-tmatma AppVeyor never hung but if it does, call me (r) :) 

OK, we will add decrease option for projects which use AppVeyor workers. Please watch this issue.

**Comment by m-tmatma** [comment]
> AppVeyor never hung but if it does, call me (r) :)

see #2459 

> OK, we will add decrease option for projects which use AppVeyor workers. Please watch this issue.

Thanks.

**Comment by isuruf** [comment]
https://ci.appveyor.com/project/conda-forge/llvmdev-feedstock is running into build timeout. Can you please increase the time limit for this project?

**Comment by OwenMcDonnell** [comment]
@isuruf Can you point me to a build that runs into timeout?

**Comment by isuruf** [comment]
@OwenMcDonnell, master works, but the new PRs doesn't. https://ci.appveyor.com/project/conda-forge/llvmdev-feedstock/build/1.0.120/messages. Thanks for looking into this

**Comment by IlyaFinkelshteyn** [comment]
@isuruf you should be good now.

**Comment by isuruf** [comment]
Thanks @IlyaFinkelshteyn.

**Comment by FeodorFitsner** [comment]
@CatGirlsAreLife Timeout set to 15 mins.

**Comment by CatGirlsAreLife** [comment]
Thanks 👌.

**Comment by mediumTaj** [comment]
@FeodorFitsner we have some long running integration tests (waiting on model training). Can you increase the time from 60 min to 90 min? 

https://ci.appveyor.com/project/mediumTaj/dotnet-standard-sdk/

**Comment by IlyaFinkelshteyn** [comment]
@mediumTaj sure, done.

**Comment by ashleywb** [comment]
Hi, is the option configurable yet. So the default of 60 minutes can be increased?
Thanks

**Comment by wasabii** [comment]
I think this build is running into a timeout at 20 minutes. But I can't be sure. There are no apparent errors. It just seems to stop with exit code 1 after ~20 minutes. Sometimes a little longer. Sometimes a little earlier.

https://ci.appveyor.com/project/wasabii/boolexprnet/build/0.1.0-unstable.24.build.20

Is there a way I can change this myself? Or should I be tagging Feodor like everytbody else is doing? Heh. 60 minutes?!

@FeodorFitsner

**Comment by Ede123** [comment]
I'm not sure wether our build got slower or the build servers are a bit on edge right now (full rebuild used to finish in 45-50 min), but we're seeing a lot of build timeouts at https://ci.appveyor.com/project/inkscape/inkscape/ and my fork at https://ci.appveyor.com/project/Ede123/inkscape which are preventing caching from kicking in causing even more timeouts.

Would it be possible to increase the timeout so full rebuilds won't block the pipelines until we hit a fast builder by chance?

**Comment by Ede123** [comment]
Great, thanks!

Yes, I noticed there a few additional builds were triggered. 😃  
None of them passed so far (seems to be some kind of authentication issue, see for example https://ci.appveyor.com/project/inkscape/inkscape/build/master-1705/job/93bwx3nom80ho418) but maybe that was some hickup during deployment. I'll keep my eyes open on wether future MRs pass.

**Comment by IlyaFinkelshteyn** [comment]
Looks like problem is related to `clone_depth: 10` setting. Looking into that. Thanks for pointing to it.

**Comment by IlyaFinkelshteyn** [comment]
@Ede123 check how MR work now please

**Comment by Ede123** [comment]
Still running but the checkout worked properly now:  
https://ci.appveyor.com/project/inkscape/inkscape/build/master-1727

Looking good so far!

**Comment by IlyaFinkelshteyn** [comment]
Nice! Thank you.

**Comment by muschellij2** [comment]
Could I please ask to increase the time for mine if possible?https://ci.appveyor.com/project/muschellij2/antsrcore .  I'm trying on @paperspace now to see if I can get it to compile on their machine in < 2 hours.

**Comment by IlyaFinkelshteyn** [comment]
@muschellij2 set to 90 minutes for you.

**Comment by muschellij2** [comment]
Thank you @IlyaFinkelshteyn.  Would it be possible to try 2 hours?  Still timing out at 1.5 hours on https://ci.appveyor.com/project/muschellij2/antsrcore. I just want to see if the linker will even work with an extra 30 mins or if the binary is too big for the linker (which I suspect to be the case).   Either way, thanks for the extra time.

**Comment by CatGirlsAreLife** [comment]
@muschellij2 if all else fails have all the dependencies that you build on your main project in a separate repository and appveyor project build and deproy every build made in that to the private nuget feed then restore that one when building in appveyor?

**Comment by muschellij2** [comment]
@CatGirlsAreLife Can you expand a bit more and point me to a set of repos that do this?  This is for an #rstats package so it may be a bit different than some other caching as all compilation needs to be done at build time.

**Comment by IlyaFinkelshteyn** [comment]
![2018-10-13_00h47_16](https://user-images.githubusercontent.com/3248386/46902883-bc4bfe00-ce81-11e8-99c6-3b7150c6164f.png)

It is implemented. It is UI-only feature and hopefully UI tool tip explains it OK. 
- if you need to **decrease** build timeout to fail fast, you can do it. 
- if you set up [private build cloud](https://www.appveyor.com/docs/build-environment/#private-build-cloud) (more [details](https://www.appveyor.com/docs/enterprise/how-to/#private-build-clouds)), you can **increase** it as you wish. For builds on AppVeyor VMs increase over standard timeout (60 minutes for now) will not take effect.
- if you want us to increase it in sensible limits (about 90 minutes) for you for free, please send email to support@appveyor.com. We usually OK, as long as we do not see obvious abuse.
- also soon we will officially provide paid 4-hour builds.

**Comment by CyberShadow** [comment]
> if you need to **decrease** build timeout to fail fast, you can do it.

I tried setting the "Build timeout, minutes" field on https://ci.appveyor.com/project/CyberShadow/dustmite/settings to 5 (the minimum value as per the pop-up), but I get the message "Custom build timeout works with private build clouds only. Contact AppVeyor team to learn more about private build clouds.".

**Comment by IlyaFinkelshteyn** [comment]
@CyberShadow thank you for the catch. Fix is on it's way

**Comment by AmokHuginnsson** [comment]
@FeodorFitsner @IlyaFinkelshteyn
Could I request a time limit increase for the [yaal](https://ci.appveyor.com/project/AmokHuginnsson/yaal) project?
I get the feeling at current build time is just barely outside default limit (the build sometimes passes).

**Comment by pat-s** [comment]
I would also like to request a time increase for the [mlr](https://ci.appveyor.com/project/mlr-org/mlr) project. We almost make it in one hour, so a few minutes on top would be great.

**Comment by syrusakbary** [comment]
@IlyaFinkelshteyn, I'd like to request a time increase for https://ci.appveyor.com/project/syrusakbary/windows-llvm-build

Github repo: https://github.com/wasmerio/windows-llvm-build

Note: We are already paying for Appveyor but somehow the limit is still 1hr?

**Comment by IlyaFinkelshteyn** [comment]
@syrusakbary 1 hour is default timeout for both paid and free accounts. We increased yours to 90 minutes. Hope this helps.

**Comment by Ede123** [comment]
I'm often hitting the 1h limit recently at https://ci.appveyor.com/project/Ede123/inkscape 

This is a bit unfortunate, as build times are ~1 h (a little longer or shorter depending on how fast the VM is), so builds often almost succeed but are cancelled close to the end (and it's even more unfortunate as this prevents the cache from kicking in, which usually brings down build times for subsequent builds to 10-15 min).

Is there a chance of increasing the 1h limit a bit?

**Comment by FeodorFitsner** [comment]
@Ede123 Extended to 90 minutes - let me know if that helped.

**Comment by Ede123** [comment]
Thanks, yes it did!

One build actually still timed out with 1:30h, but another one just passed after 1:14h and with cache in place build times are at <0:15 again.

Seems there's some hiugher variance in build times currently, considering sometimes re-builds complete in well below 60 min and at other times even 90 min aren't enough.

**Comment by lundman** [comment]
Hoping my projects could get a little more time? Tests usually run for 2 hours, but I've trimmed it down as best I can.. could one get 90 mins maybe?
https://ci.appveyor.com/project/lundman/openzfs
Out of curiosity, if the testing causes a panic, is there any way to get the panic report?

**Comment by FeodorFitsner** [comment]
@lundman build timeout has been increased to 90 min for your account. What do you mean by panic - are you running Go tests?

**Comment by lundman** [comment]
Thank you - I test builds of ZFS for osx, which is a kext. Sometimes it goes wrong, and it panics. Now I just run the test again on local VM to attach lldb to the panicked kernel, assuming I can repeat it. But, even just getting the stack of the panic can save time. I don't think you have any methods for dealing with the CI panicking, but I thought I would ask...

**Comment by datadiode** [comment]
Can you grant me a timeout upgrade to 90 minutes for https://github.com/datadiode/SfQtWebKit?
