### ISSUE TITLE
Improvement: Add user's define dimension to the matrix

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#518]
Hi

Actually, dimensions of the configuration are: os, platform, configuration and matrix whose names are fixed. I am proposing to extend the dimension of the configration by user's defined dimension by adding enumerated values to environment variables as for exemple:

`dimensions:`
`linkmode:`
`shared`
`static`
`bundling:`
`bundled`
`unbundled`

This would add 2 dimensions to the configuration matrix by setting environment variable named 'linkmode' and 'bundling'.

**Comment by KindDragon** [comment]
You can set several user defined dimensions in matrix https://github.com/KindDragon/vld/blob/master/appveyor.yml

**Comment by zosrothko** [comment]
That's not the same thing... using environement variable mandates to repeat as many time as necessary each dimension's value to build a cartesian product. This request is asking for AppVeyor to automatically build the cartesian product.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
