### ISSUE TITLE
False positive on job result

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#519]
Hi

While the problem below happens during the job
`Microsoft Visual Studio 2013 Version 12.0.40629.0.
Copyright (C) Microsoft Corp. All rights reserved.
C:\projects\poco-olq4c\Crypto\testsuite\TestSuite_x64_vs120.vcxproj : error  : Project "C:\projects\poco-olq4c\Crypto\testsuite\TestSuite_x64_vs120.vcxproj" could not be found`

The outcome of the jobs has been success instead of failure.
`echo success`
`success`
`Updating build cache`
`Cache entry not found: c:\OpenSSL-Win32`
`Saving "c:\OpenSSL-Win64"...OK`
`Saving "c:\ProgramData\chocolatey"...OK`
`echo finish`
`finish`
`Build success`

**Comment by FeodorFitsner** [comment]
What do you have in appveyor.yml (or export project settings to YML if you configure through UI)?

**Comment by zosrothko** [comment]
Uou can sse the appveyor.yml and all components *.cmd and *.bat here
https://github.com/Kampbell/poco.git branch AppVeyor

**Comment by zosrothko** [comment]
The command is
         & .\buildwin.cmd %builder% build %linkmode% %Configuration% %platform% samples tests devenv 
which in turn call devenv with the below test
      if ERRORLEVEL 1 goto buildfailed
      echo. && echo. && echo.

So, it seem the ERRORLEVEL be different from 1 when returning from devenv

**Comment by zosrothko** [comment]
Ok.. this seems to much overloaded.. I close the issue. Sorry for the noise.
