### ISSUE TITLE
LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#520]
Hi

after one of the setup below
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
or
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd84

one gets this link error
Microsoft Visual Studio 2015 Version 14.0.23107.0.
Copyright (C) Microsoft Corp. All rights reserved.
------ Build started: Project: CppUnit, Configuration: release_shared x64 ------
  CppUnitException.cpp
  TestCase.cpp
  TestDecorator.cpp
  TestFailure.cpp
  TestResult.cpp
  TestRunner.cpp
  TestSuite.cpp
  TextTestResult.cpp
  Generating Code...
     Creating library ..\lib64\CppUnit.lib and object ..\lib64\CppUnit.exp
LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product

**Comment by zosrothko** [comment]
Hi

Could you have a look at this page which explain how to fix this issue which needs the administrator rigth for doing it.

https://connect.microsoft.com/VisualStudio/feedback/details/1651822/incorrect-mspdb140-dll-version-picked-in-x86-x64-cross-tools-environment

**Comment by FeodorFitsner** [comment]
You have full administrative access on build workers and you can copy those two files as part of your build script.

We are going to deploy VS 2015 Update 1 tomorrow.

**Comment by zosrothko** [comment]
Ok I was thinking that some sensibel directory like C:\Programs were proteced.
