### ISSUE TITLE
Cygwin: unzip not installed

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#521]
Hi

It seems that c:/cygwin/bin/unzip is missing from the installation:

c:\cygwin\bin\unzip : The term 'c:\cygwin\bin\unzip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:8 char:9
+         c:\cygwin\bin\unzip -q /cygdrive/c/mysql-5.7.9-win32.zip
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (c:\cygwin\bin\unzip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Command executed with exception: The term 'c:\cygwin\bin\unzip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again

**Comment by FeodorFitsner** [comment]
You can use `7z.exe` instead.

**Comment by zosrothko** [comment]
Ok...
I tried also to install unzip with the C:\cygwin\setup-x86.exe with command line arguments like 
` - c:\cygwin\setup-x86.exe -B -D -q -n -N -d -R cygwin -s http://mirror.csclub.uwaterloo.ca/cygwin/ -l c:\localPackageDir -P unzip-6.0-15.tar.gz`
` - cygwin\bin\unzip.exe --help`

but without success. Is there a blocking point somewhere?

**Comment by FeodorFitsner** [comment]
Unfortunately, I'm not an expert in cygwin. Have you got any errors?

**Comment by zosrothko** [comment]
Build started
`git clone -q --branch=master https://github.com/Kampbell/ISO-8583.git C:\projects\iso-8583
git checkout -qf e8bd6036fc6a163a5d0570fc74f304a7d732efa6
Running Install scripts
c:\cygwin\setup-x86.exe -B -D -q -n -N -d -R cygwin -s http://mirror.csclub.uwaterloo.ca/cygwin/ -l c:\localPackageDir -P unzip-6.0-15.tar.gz
Starting cygwin install, version 2.873
User has backup/restore rights
Current Directory: c:\localPackageDir
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
Selected local directory: c:\localPackageDir
net: Direct
site: http://mirror.csclub.uwaterloo.ca/cygwin/
io_stream_cygfile: fopen(/etc/setup/installed.db) failed 2 No such file or directory
Command exited with code -1073741571
echo on_failure
on_failure
echo on_finish
on_finish`

**Comment by zosrothko** [comment]
BY the way, I understand now why one recommand me to sue Cygwin unzip: because with 7-Zip, one cannot write in C:\ while it is ok with unzip.because of the access rigths
ERROR: Can not open output file : Accès refusé. : c:\mysql-5.7.9-win32\README

**Comment by FeodorFitsner** [comment]
You should be able to unpack to C:\ directly with 7z.

**Comment by zosrothko** [comment]
Ok I close this issue as 7z do the job...but I will come back with the cygwin setup-86.exe
