### ISSUE TITLE
APPVEYOR_JOB_NAME environment variable

### ISSUE THREAD

**Issue by KindDragon** [appveyor/ci#522]
Please add variable to get current job name. I want lookup by it same job from previous build

**Comment by FeodorFitsner** [comment]
It's been deployed.

**Comment by KindDragon** [comment]
Cool!

**Comment by rraallvv** [comment]
Does putting a different value in `APPVEYOR_JOB_NAME` allow having separate caches for each branch? like so:

    matrix:
      - APPVEYOR_JOB_NAME: "%APPVEYOR_REPO_BRANCH%"
