### ISSUE TITLE
Improvment: Support environemnet variable definition for configuration

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#531]
Hi

One naming convention on MS VS is to suffix any name compiled with Debug by a "d". It would nice to allow theconfiguration block to specify this

configuration:
- Debug:
    suffix: d
- Release:
    suffix:

so that the appveyor.yml be more generic by removing if ($env:configuraiton -eq "Debug")

**Comment by lygstate** [comment]
That's not necessary, you can derive those envs in your script.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
