### ISSUE TITLE
Using `.appveyor.yml`

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#539]
It would be nice if we could use `.appveyor.yml`, if this doesn't already work, so that the file can be hidden on some platforms. If this is already allowed, it would be nice to have this stated somewhere explicit in the documentation.

**Comment by FeodorFitsner** [comment]
You can set custom name for YML configuration file on General tab of project settings.

**Comment by sheerun** [comment]
@FeodorFitsner This is not enough, as it requires manual setup for each project that wants to use .appveyor.yml.. Coudn't you just support .appveyor.yml by default?

**Comment by FeodorFitsner** [comment]
.appveyor.yml is supported by default.

**Comment by IlyaFinkelshteyn** [comment]
https://github.com/appveyor/ci/issues/1040
