### ISSUE TITLE
NuGet 3.2 on Visual Studio 2015 images cause fail restoring packages

### ISSUE THREAD

**Issue by ma-gu** [appveyor/ci#546]
It fails if solution contains .xproj with the following message:
Could not find a part of the path 'C:\projects\demo\Demo.MVC6\Demo.MVC6.xproj\project.json'.
Command exited with code 1

It was fixed in 3.2.1 (please see this issue described here https://github.com/NuGet/Home/issues/1227)

Also this fix is mentioned in release notes: http://docs.nuget.org/release-notes/nuget-3.2.1

**Comment by FeodorFitsner** [comment]
There is even 3.3.0! :) Thanks for letting know - will deploy this week.

I've opened a new issue https://github.com/appveyor/ci/issues/548 for deployment purposes. Closing this one.
