### ISSUE TITLE
ActivePerl installed, all of a sudden

### ISSUE THREAD

**Issue by mbeijen** [appveyor/ci#550]
I'm using AppVeyor as a means of CI testing for Perl modules.
I added it for instance to DBD::mysql https://github.com/perl5-dbi/DBD-mysql and this worked quite well.

Now I tried adding it to a different module and failed because it seems like ActiveState perl is installed on my builder. This clashes with the StrawberryPerl that I was installing via Chocolatey. Also, I could not uninstall ActiveState Perl.

I don't mind using ActiveState Perl per se; but can I count on it being *always* available? I did not read anything about this on http://www.appveyor.com/updates

**Comment by FeodorFitsner** [comment]
Could you please suggest what AppVeyor account/project is that?

**Comment by mbeijen** [comment]
I'm trying to configure my project here: https://ci.appveyor.com/project/mbeijen/file-desktopentry

**Comment by mbeijen** [comment]
Also, it seems as if `ppm` can't actually connect to ActiveState's package repositories, so I can't install modules on it. This makes me unable to build and test my code.

**Comment by FeodorFitsner** [comment]
ActivePerl was installed on Pro environment (only) back in Fabruary: https://github.com/Microsoft/visualfsharp/issues/53#issuecomment-73111860

Approx month ago we moved OSS to a new environment with build worker images re-created from scratch. Now ActivePerl is part of "standard" software list on all build workers.

However, it doesn't mean you should use it in your projects. You can just change `PATH` to use Perl from another location.
