### ISSUE TITLE
Run script or Webhook after s3 deploy

### ISSUE THREAD

**Issue by onuralp** [appveyor/ci#553]
It will be nice run powershell or cmd after Amazon s3 or any environment. I am not talking about After Deploy script. When I am deploying an artifacts to different environment, I should run a custom script.

**Comment by FeodorFitsner** [comment]
"Environments" do not allow running scripts due to shared nature of AppVeyor background workers running the deployments. However, you might want to take a look at this approach: http://www.appveyor.com/blog/2015/11/04/deployment-projects

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
