### ISSUE TITLE
Deployment from various platforms overwrites file

### ISSUE THREAD

**Issue by doe300** [appveyor/ci#555]
I set up appveyor (see: https://github.com/doe300/OHMComm/blob/sip/appveyor.yml) with two platforms (x86 and x64). Both compile with success and on pushing tags, both deploy the artifact as specified.
But they use the original file-name, not the name specified for the artifacts (OHMComm-win-$(platform)) and therefore the second build overwrites the deployed file of the first one.

What I get:

    x86: Uploading "OHMComm.exe" to release assets...OK

    x64: Deleting existing release asset "OHMComm.exe"...OK
         Uploading "OHMComm.exe" to release assets...OK

What I want to get (two seperate deployed files):

    x86: Uploading "OHMComm-win-x86.exe" to release assets...OK

    x64: Uploading "OHMComm-win-x64.exe" to release assets...OK

Any help would be appreciated.

**Comment by FeodorFitsner** [comment]
Instead of setting up `artifacts` section you should use script to push artifact with different name:

```
after_build:
- ps: Push-AppveyorArtifact <path-to-OHMComm.exe> -FileName "OHMComm-win-$env:platform"
```

**Comment by doe300** [comment]
Thanks, works now perfectly:)
