### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by richardschneider** [appveyor/ci#562]
I've renamed my github repo.  Appveyor still insists that I use the old name for the URL.

I've updated the `project name` and `github repository` in `Settings | General` and still no love.

The project is https://ci.appveyor.com/project/richardschneider/ecom/ and I would like to use `.../yappy`

PS: I do like the site, +2.

**Comment by FeodorFitsner** [comment]
Oh, you mean `ecom` in AppVeyor project URL?

This can't be changed from UI (yet) - I've updated it in database.

**Comment by richardschneider** [comment]
Thanks for the quick fix, https://ci.appveyor.com/project/richardschneider/yappy now works me!
