### ISSUE TITLE
color should be set when background-color is set

### ISSUE THREAD

**Issue by mrmonday** [appveyor/ci#564]
If the `background-color` property is set in CSS, the `color` property should also always be set, and vice versa. This is not currently true for appveyor.com, leading to situations like this:

![2015-12-19-113257_1438x880_scrot](https://cloud.githubusercontent.com/assets/165689/11912768/8f5c9066-a644-11e5-97cf-d94ec79fa1de.png)

Where the text is unreadable due to custom styles. See also, note 4 here: http://www.w3.org/TR/WCAG20/#contrast-ratiodef. There's probably a better/more direct link, I couldn't find it though, unfortunately.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
