### ISSUE TITLE
Builds not starting

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#572]
Last successful build at https://ci.appveyor.com/project/StefanKarpinski/julia/history was 9 hours ago. All builds since then appear to be sitting queued indefinitely until cancelled.

**Comment by FeodorFitsner** [comment]
It should be fine now. Please cancel all queued builds and start a new one.

Sorry for the inconveniences.

**Comment by tkelman** [comment]
Looks fixed, thanks for the fast response.
