### ISSUE TITLE
WDK 8

### ISSUE THREAD

**Issue by mback2k** [appveyor/ci#573]
I would like to request Windows Driver Kit Version 8 on Visual Studio 2012 build workers.

I depend on [WindowsApplicationForDrivers8.0](https://msdn.microsoft.com/en-us/library/windows/hardware/hh454232.aspx) in order to build my project [wiasane](https://github.com/mback2k/wiasane).

Download URL: https://msdn.microsoft.com/en-US/windows/hardware/hh852365.aspx

**Comment by mback2k** [comment]
Since MSBuild is a newer version than Visual Studio 2012, please also apply the following workaround to the installation:
https://msdn.microsoft.com/de-de/library/Windows/Hardware/dn265174%28v=vs.85%29.aspx
Section 1. Correct the WindowsDriver8.0.x64.props and WindowsDriver8.0.Win32.props files.

**Comment by FeodorFitsner** [comment]
Yeah, will apply that fix. For now you can use the following PS to correct it during the build:

```posh
$p = 'C:\Program Files (x86)\Windows Kits\8.0\build\WindowsDriver8.0.x64.props'
$c = [IO.File]::ReadAllText($p)
$c = $c.Replace('''$(VisualStudioVersion)'' != ''11.0''', '''$(VisualStudioVersion)'' &lt;''11.0''')
[IO.File]::WriteAllText($p, $c)

$p = 'C:\Program Files (x86)\Windows Kits\8.0\build\WindowsDriver8.0.Win32.props'
$c = [IO.File]::ReadAllText($p)
$c = $c.Replace('''$(VisualStudioVersion)'' != ''11.0''', '''$(VisualStudioVersion)'' &lt;''11.0''')
[IO.File]::WriteAllText($p, $c)
```

**Comment by mback2k** [comment]
@FeodorFitsner Did you already apply the fix to the build workers? In that case I would like remove the PS from my build configuration.

**Comment by FeodorFitsner** [comment]
Nope. Did that script fix worked for you?

**Comment by mback2k** [comment]
Yes, it does.

**Comment by mback2k** [comment]
@FeodorFitsner Was WDK 8 uninstalled from the build systems or is it no longer provided? My latest build shows that it cannot find it any longer: https://ci.appveyor.com/project/mback2k/wiasane/build/job/grapnido33movoj4

**Comment by IlyaFinkelshteyn** [comment]
Hi Mark,
Most probably this is related to our migration from GCE to Rackspace - https://www.appveyor.com/blog/2016/07/16/migration-to-rackspace. I see that while WDK 8 seems installed, some files are missed from new VHD. We will update you with workaround or fix ETA in a day or so.
Thank you,
Ilya.

**Comment by IlyaFinkelshteyn** [comment]
It seems that we need to repair WDK 8 on Rackspace build worker VHD

**Comment by mback2k** [comment]
Thanks for the investigation. Looking forward to the fix!

**Comment by mback2k** [comment]
@IlyaFinkelshteyn Any update on this issue?

**Comment by IlyaFinkelshteyn** [comment]
Hi Marc,

I just sent you PR https://github.com/mback2k/wiasane/pull/30 with workaround. It reinstalls WDK8 and restores previous workaround with props files correction.

We cannot say right now ETA for permanent solution.

Thank you,
Ilya.

**Comment by IlyaFinkelshteyn** [comment]
We have ETA now - assigned this issue to the nearest milestone https://github.com/appveyor/ci/milestone/57 :)

**Comment by IlyaFinkelshteyn** [comment]
![image](https://cloud.githubusercontent.com/assets/3248386/17718479/0505617a-63c9-11e6-8f93-c18f79a0144c.png)

**Comment by mback2k** [comment]
@IlyaFinkelshteyn Thanks for the PR. I will wait until the 21th August to see if the permanent solution works and only apply the workaround in case it does not. :-)

**Comment by mback2k** [comment]
@FeodorFitsner and @IlyaFinkelshteyn thanks, it is finally working without a workaround. :-)
