### ISSUE TITLE
WDK requires platform name Win32 instead of x86

### ISSUE THREAD

**Issue by mback2k** [appveyor/ci#574]
WDK-based projects require the VS platform name to be Win32 instead of x86.

Since I can only select between Any CPU, x86 and x64, as well as ARM, how do I specify Win32 as MSBuild platform?

**Comment by FeodorFitsner** [comment]
Configure project through appveyor.yml where you can specify any platform.

**Comment by mback2k** [comment]
Thanks for the tip. Anyway, it would still be great if it were possible to configure any custom platform using the website.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
