### ISSUE TITLE
Special symbols in Slack notifications issue

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#577]
We’ve got three special characters in swedish, åäö.

They seem to be sent as html instead of the actual character and slack doesn’t show them right.

Should’ve said ”sökkriterier” in the screenshot. Not `s&#246;kkriterier`.

**Comment by atagirov** [comment]
i get some error for russian symbols. Get "&#1085;&#1072;" instead "на" for example.

If it's help, for fix this localy I replace "{{commitMessage}}" in standart templeate for slack notification to "{{{commitMessage}}}" for don't escaped in HTML
