### ISSUE TITLE
Calling test runners from your custom scripts: NUnit 2.6.4?

### ISSUE THREAD

**Issue by ddur** [appveyor/ci#579]
Where AppVeyor expects to find NUnit test results that will be displayed in TESTS button (build page). 
Put in to another words: Where to save NUnit 2.6.4 test results and under which name?
Thanks

**Comment by FeodorFitsner** [comment]
Test assemblies can be anywhere within build directory (`%appveyor_build_folder%`).

**Comment by ddur** [comment]
I'm not talking about assemblies, but about NUnit **TestResults.xml** 
Is there any special directory or name for them to appear here next to the button?
![appveyortests](https://cloud.githubusercontent.com/assets/3501612/11999914/e88235c2-aac9-11e5-95e7-7039edcdf8f9.png)
Thanks

**Comment by FeodorFitsner** [comment]
XML results are not imported automatically, but you could upload them: http://www.appveyor.com/docs/running-tests#uploading-xml-test-results

**Comment by ddur** [comment]
Thank you!
