### ISSUE TITLE
Restarting and cancelling a single job in the matrix

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#58]
Discussion: http://help.appveyor.com/discussions/questions/698-restarting-a-single-job-in-the-matrix

**Comment by ionelmc** [comment]
:+1: Add this feature please.

**Comment by ap--** [comment]
I would need this too.
One job failed with: "Build execution time has reached the maximum allowed time for your plan (40 minutes)." after the second command, even though everything should only take ~10minutes.

**Comment by sanemat** [comment]
:+1: :+1: :+1:

**Comment by ionelmc** [comment]
Just to make a case for this feature: without it it's very hard to get "green" build status if you have network failures (which seem to be quite frequent on appveyor).

**Comment by nicowilliams** [comment]
Some CIs support this, and indeed, it's useful.  Similarly, it's useful to be able to stop builds for specific items in the matrix.  UI-wise there should be a list of items in the matrix with the status color for each item and a stop or start and/or restart button for each item.

**Comment by ruslo** [comment]
+1 for this, build may fail because of network issues

**Comment by lasote** [comment]
:+1:

**Comment by cjermain** [comment]
I just ran into a `'Connection broken` error on one of my builds, and I can't manually restart that build like I can in TravisCI. This feature would be really nice for Appveyor!

**Comment by jakirkham** [comment]
Sorry, a simple 👍 didn't cut it. This would really be amazing for us.

**Comment by jakevdp** [comment]
👍  here. Just went searching for this after a network blip killed one of the jobs... sounds like I have to re-start all of them 😠

**Comment by photodude** [comment]
canceling and restarting a single job in a build is definitely a must

**Comment by karthikreddy09** [comment]
Would be very helpful for sporadic failures.

**Comment by darioizzo** [comment]
👍  pleaseeee

**Comment by IlyaFinkelshteyn** [comment]
If implementation will start **new build** against the **same commit**, with **only specified job**, will it be sufficient? Status of restarted job in original build will stay untouched.
Any input if this approach is acceptable is greatly appreciated.

**Comment by darioizzo** [comment]
Ideally (as it is implemented for example in Travis CI) one would not have a new build, just update the job in the current build. But your suggestion is also better than nothing :)

**Comment by andfoy** [comment]
:+1: Sometimes network errors delay all CI tests and package building processes

**Comment by ofek** [comment]
@FeodorFitsner Any progress?

**Comment by reeteshranjan** [comment]
👍 I guess this is extremely important. I have a software that works with third party systems through API calls. One network failure and I have to run the build all over again. It is a non-smart waste of time when the build takes 3-4 hours.

**Comment by reeteshranjan** [comment]
I just stopped building one of my projects on appveyor as its build is 4 hours+ and going to be even longer as more features/components get added, and I can't put time figuring out which are the lucky 4-5 hours in the day where all jobs get completed without errors. Last few builds I have been literally doing that and my releases are getting unnecessarily delayed. With Travis CI's Linux and OSX builds I get the same issues where some jobs would fail; but it's easier there with the ability to restart all failing jobs and it does not take such a big turnaround time to get the build to pass. With most of my software being about working with third party systems through API calls on network, it's pretty annoying without this feature in place.

**Comment by ilayn** [comment]
We are at SciPy also having one-off-builds and this would be a really good addition if possible.

**Comment by kasper3** [comment]
Any update on this? Are there any `technical` issues implementing it? :)

**Comment by IlyaFinkelshteyn** [comment]
@kasper3 yes it is not easy technically. But we forced it's priority as it become more critical now, with addition of Linux builds. No specific ETA, but plan to implement it is near future.

**Comment by fpelliccioni** [comment]
Please, it is very useful for long time compilations. Thanks!

**Comment by ffeldhaus** [comment]
Is there an update on the current status? The last update from May 1st was "near future", but that was half a year ago. Unfortunately network issues are still regularly causing jobs to fail and this feature along with network improvements is very important to be able to pass all jobs in the matrix!

**Comment by IlyaFinkelshteyn** [comment]
Button called `RE-RUN INCOMPLETE` will come this week or so. If matrix build has at least one successful job, this button will appear. If pressed, all cancelled and failed jobs in matrix will re-run. Build version and number will stay the same. Build ID (used in GitHub status will change). Status will be updated too.

API behind `RE-RUN INCOMPLETE` will be exposed too.

It is not exactly what this issue is about, but should cover 95% of scenarios.

**Comment by IlyaFinkelshteyn** [comment]
Please check `RE-RUN INCOMPLETE` button. 
Respective API: API: https://www.appveyor.com/docs/api/projects-builds/#re-run-build
Also we added environment variable called `APPVEYOR_RE_RUN_INCOMPLETE`. It is set to `True` if job has been rerun.
![dsln6onuuaarbdn](https://user-images.githubusercontent.com/3248386/49029420-685b5700-f159-11e8-948b-778dc745f8ed.jpg)

Closing this issue as I hope this button covers 95% of cases. Please let me know if it should be reopened.

**Comment by fredrikaverpil** [comment]
A heart emoji (:heart:) does not cut it in this case. Well done @IlyaFinkelshteyn and others involved! 🎉 👍 ❤️ 🍻 

This is a _much_ needed feature and it's fantastic that this is now available!

**Comment by IlyaFinkelshteyn** [comment]
@fredrikaverpil more than welcome :) Sorry it took that long...

**Comment by cgillum** [comment]
One thing I noticed is that when I use `RE-RUN INCOMPLETE` the failed job will re-run and complete successfully, but the GitHub status of this build never changes from _Pending_:

![image](https://user-images.githubusercontent.com/2704139/49190028-78c02d00-f325-11e8-8453-422b8c51edcd.png)

But if I click the Details link, it shows the build succeeded. Is this a known issue?

**Comment by IlyaFinkelshteyn** [comment]
@cgillum how are you :) Need some help to repro. If this PR from a fork or the same repository?

**Comment by cgillum** [comment]
Hi @IlyaFinkelshteyn, I'm good. It's good to see you again, although in a different place. :)

The last time I saw this (about an hour ago) it was a branch in the same repository. I don't remember if I saw this behavior from a fork.

**Comment by IlyaFinkelshteyn** [comment]
@cgillum it was actually a bug, thanks for bringing attention to it. Fixed now.

**Comment by relsqui** [comment]
Any chance we could either make this apply to jobs that are allowed to fail, or be able to restart individual jobs manually? Would be really helpful when debugging nonblocking jobs. :)

**Comment by IlyaFinkelshteyn** [comment]
@relsqui If you need to run only small subset of jobs, there is a not very well known way described [here](https://www.appveyor.com/docs/build-configuration/#skip-matrix-jobs-conditionally). For example with this YAML if you create a commit with the message `Something [skip-all-except-value1]`, only one job (`MyVar: MyValue1.txt`) will run from the matrix.

```
environment:
  matrix:
  - MyVar: MyValue1.txt
  - MyVar: MyValue2.txt
  - MyVar: MyValue3.txt
  - MyVar: MyValue4.txt

build:
- echo $env:MyVar

test: off

for:
-
  matrix:
    except:
      - MyVar: MyValue1.txt
  skip_commits:
    message: /skip-all-except-value1/
```
If both this and `RE-RUN INCOMPLETE` does not work for you, please elaborate your situation with more details. If you need to send a YAML which you do not want to be public, feel free to create a private discussion on our [support forum](https://help.appveyor.com) or send email to support@appveyor.com.

**Comment by relsqui** [comment]
Oh interesting! So I could do it by setting up a commit tag for it. That covers like 95% of what I'm looking for and is good enough, thanks. :) (The other 5% is when I'm running the full build but only the allowed-to-fail job failed; I don't have a way to rerun just that job, but pushing a commit with a tag in it is fine.)

**Comment by IlyaFinkelshteyn** [comment]
@relsqui now I understand, sorry should have understand it from the previous comment. Issue is that `RE-RUN INCOMPLETE` is not being displayed for "successful" builds in UI (even when some jobs failed). But you can call it with [API](https://www.appveyor.com/docs/api/projects-builds/#re-run-build), e.g:

```posh
$token = "<REPLACE>"
$buildId="<REPLACE>"
$headers = @{
  "Authorization" = "Bearer $token"
  "Content-type" = "application/json"
}
$body = @{
    buildId=$buildId
    reRunIncomplete="true"
}
$body = $body | ConvertTo-Json
Invoke-RestMethod -Uri 'https://ci.appveyor.com/api/builds' -Headers $headers  -Body $body -Method PUT
```

`buildId` you can take from the browser address, when you open that kind of build in the builds history in AppVeyor.  API token should be account-level, not "All accounts".

No need that complicated filtering approach (though you can use it for other scenarios).

We probably have to display `RE-RUN INCOMPLETE` on this kind of builds (successful but with failed jobs) in UI, but with API call you can do it right now.

Let us know if 100% of cases are covered now :)

**Comment by relsqui** [comment]
Oh, ha, I didn't think of that -- I checked to see if there was a single job option in the API but it didn't occur to me that I could use it to call the incomplete option even though it wasn't in the UI. Having the visible button would be nice but being able to do it at all does cover what I need. Thank you!

**Comment by IlyaFinkelshteyn** [comment]
@relsqui UI change has been deployed, no need for API call in your case too. Thanks for the catch!

**Comment by relsqui** [comment]
Awesome, thanks so much Ilya!
