### ISSUE TITLE
Removing project and history?

### ISSUE THREAD

**Issue by ddur** [appveyor/ci#580]
Somehow, by mistake, I managed to create duplicate AppVeyor/GitHub project. 
Pushing changes to single GitHub project triggers both AppVeyor project builds, original and duplicate.

Original:
https://ci.appveyor.com/project/ddur/dbcl
Duplicate:
https://ci.appveyor.com/project/ddur/dbcl-07tph

How to remove duplicate?
Thanks

**Comment by FeodorFitsner** [comment]
Just open project settings, go to Delete tab and delete the project.

**Comment by ddur** [comment]
Thanks :)
