### ISSUE TITLE
Environment Variables during RDP of Build Worker

### ISSUE THREAD

**Issue by beardedprojamz** [appveyor/ci#595]
Hey there, is it possible to inspect the values of the set [environment variables](http://www.appveyor.com/docs/environment-variables) during RDP of the build worker? I've followed the steps [here](https://www.appveyor.com/docs/how-to/rdp-to-build-worker) to log in on build finish (under general tab of project settings), but I don't see those env vars being set. Should I put my PS after tests run?

**Comment by FeodorFitsner** [comment]
You can't "see" those variables as they are set on process level (build agent process).

However, you can add a script to appveyor.yml to list them after tests:

```
after_test:
- SET
```

**Comment by beardedprojamz** [comment]
Nice! Thanks!
