### ISSUE TITLE
'pause' in batch files seems to stop executing...

### ISSUE THREAD

**Issue by jedie** [appveyor/ci#596]
Seems it is a good idea to remove the origin 'pause' with something "non-blocking"

e.g.:

https://ci.appveyor.com/project/jedie/pyhardlinkbackup/build/1/job/xxn1g0csoc4dq7jk

**Comment by FeodorFitsner** [comment]
Good idea. How would you replace it?

**Comment by jedie** [comment]
With something like: ```echo "pause"``` ;)

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.

**Comment by jedie** [comment]
Is this fixed in a other way, or is a work-a-round still needed?
