### ISSUE TITLE
Update MSYS 2

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#597]
Discussion: http://help.appveyor.com/discussions/suggestions/615-support-for-msys2

Installation path: `C:\msys64`

Installation:

MSYS2: http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20150916.exe/download

Run `C:\msys64\msys2_shell.bat`:
```
pacman -Sy --noconfirm pacman-mirrors
pacman -S --noconfirm pacman
update-core
pacman --sync --noconfirm base-devel mingw-w64-{x86_64,i686}-toolchain
pacman --sync --noconfirm mingw-w64-{x86_64,i686}-cmake
pacman --sync --noconfirm mingw-w64-{x86_64,i686}-ninja
pacman --sync --noconfirm mingw-w64-{x86_64,i686}-gtkmm
pacman --sync --noconfirm mingw-w64-{x86_64,i686}-wxWidgets
pacman --sync --noconfirm gyp-svn
pacman --sync --noconfirm cmake
```
Update script:

```
# Switch from SF to msys2.org (default, much faster)
pacman --sync pacman-mirrors

# Restart MSYS2 after this
update-core

# Should take a while
pacman -Syu
```

Pacman command-line options: https://www.archlinux.org/pacman/pacman.8.html

**Comment by elieux** [comment]
Corrections and explanations follow.

1) Run just this once to switch to a faster mirror *before* this big update: `pacman -Sy pacman-mirrors`

2) Update steps for regular use:
```
update-core
# Restart MSYS2 now, as suggested by the script
pacman -Su
```

Note that the last command should not be `-Syu`, as presented by "Someone".

**Comment by JanSchulz** [comment]
Not sure if this is the right issue here:

if I run 
```
- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-i686-toolchain" 
```

pacman crashes: https://ci.appveyor.com/project/JanSchulz/jq/build/1.0.9

```
[...]
reinstalling pkg-config...
reinstalling pkgfile...
      2 [main] pacman 1324 child_copy: data read copy failed, 0x100749000..0x10075D688, done 0, windows pid 1324, Win32 error 998
299991369 [main] pacman 1324 C:\msys64\usr\bin\pacman.exe: *** fatal error in forked process - WFSO timed out after longjmp
299991748 [main] pacman 1324 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
Command exited with code 1
```

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by aquynh** [comment]
first of all, thanks so much for Appveyor service. what you guys have done is amazing, and very helpful!

my question on Msys2: is there any sample `appveyor.yml` file for the latest Msys2 support, so i can learn from that?

in my build, i need to have python2, make, pkg-config, mingw-w64-x86_64-glib2 & mingw-w64-x86_64-toolchain. do i need to install them (with "pacman"), or these packages are already there by default?

thanks.

**Comment by FeodorFitsner** [comment]
Yeah, you can install any missing packages using pacman. At the top of this issue there is a script used to install/configure MSYS2 on build worker machines. Maybe some of packages you named are included in those ones.

Working with bash on AppVeyor is calling it like:

```
install:
- C:\msys64\usr\bin\bash -lc "<your-bash-script>"
```

for example:

```
install:
- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S <your-package>"
```

**Comment by aquynh** [comment]
oh it seems python2, pkg-config & mingw-w64-x86_64-glib2 are all available by default. great job, thanks!

**Comment by aquynh** [comment]
I have an issue with Appveyor: my code compiles very well on my own machine with Msys2, but fails on Appveyor. 

My configuration file is very simple, at https://github.com/unicorn-engine/autobuild/blob/master/.appveyor.yml

Appveyor reports below error (details at https://ci.appveyor.com/project/aquynh/autobuild/build/unicorn-autobuild-44/job/2vu04f6svrbapskq):

```
...
set PATH=%PATH%;C:\msys64\usr\bin
cd c:\projects\unicorn
bash make.sh cross-win64
    784 [main] make (2848) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180321400/0x180320400.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

My suspect is that the PATH points to gcc toolchain is not at `C:\msys64\usr\bin`, even though there is make.exe and so on, but I am not quite sure about this.

Any idea how to fix this issue, please?

Thanks.

**Comment by FeodorFitsner** [comment]
Try setting PATH in "install" section as the following:

    - set PATH=C:\msys64\usr\bin;%PATH%

thus giving the priority to msys.

**Comment by aquynh** [comment]
oh cool, now Msys2 can go a bit further, but still it stops with the error " ... ERROR: "x86_64-w64-mingw32-gcc" either does not exist or does not work" (see https://ci.appveyor.com/project/aquynh/autobuild/build/unicorn-autobuild-46/job/dqgtlw84ofi16xdl)

on my Windows machine, x86_64-w64-mingw32-gcc is available inside Msys environment at `/mingw64/bin`

now my guess is that the MingW environment is still not initialized properly yet. do i need to run something to setup MingW before building? currently everything i am doing is just to setup the PATH, as you suggested above.

do you think my setup needs to be fixed? https://github.com/unicorn-engine/autobuild/blob/master/.appveyor.yml


thanks!

**Comment by FeodorFitsner** [comment]
Maybe you should install missing packages like shown [above](https://github.com/appveyor/ci/issues/597#issuecomment-193922667).

**Comment by aquynh** [comment]
i put in this line into https://github.com/unicorn-engine/autobuild/blob/master/.appveyor.yml:

    C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Suy python2 make pkg-config mingw-w64-x86_64-glib2 mingw-w64-x86_64-toolchain"

but still i have the same error: ERROR: "x86_64-w64-mingw32-gcc" either does not exist or does not work...

see https://ci.appveyor.com/project/aquynh/autobuild/build/unicorn-autobuild-47/job/7dtmln8ymst65ing

do you have any ideas? 

thanks

**Comment by FeodorFitsner** [comment]
There might be conflicting things in `C:\cygwin\bin` and `C:\Program Files\Git\usr\bin` folders, I guess. First, modify PATH before doing package installation/upgrade. Then also try removing `C:\Program Files\Git\usr\bin` from PATH as well.
