### ISSUE TITLE
Add support for REST deployments.

### ISSUE THREAD

**Issue by MicahZoltu** [appveyor/ci#599]
While it would be great if AppVeyor supported every artifact and web hosting system on the planet, it may be a while before all that will be complete.  In the meantime, it would be nice if there were some deployment providers made available that made working with random deploy targets easier.  One in particular is a REST deployment provider.

The REST deployment provider would take a URI (ideally with support for replacement strings from environment variables), a set of headers (also with environment variable replacement support) and perhaps standard style key/value pair query string parameters.  It should also support standard upload protocols for HTTP via POST/PUT.

BinTray is an example of a deployment target that could be accessed via a REST provider and may make for a good test case.

One thing to make sure of is provide a way to submit headers via encrypted values.  The authorization header in particular.  As an added bonus, it would be nice if AppVeyor knew how to populate the Authorization header with some of the standard stuff like Bearer tokens and Basic Authentication.

**Comment by FeodorFitsner** [comment]
Webhook deployment provider could cover this scenario: https://www.appveyor.com/docs/deployment/webhook/
