### ISSUE TITLE
Unbuffered deploy_script output

### ISSUE THREAD

**Issue by alberthdev** [appveyor/ci#604]
Currently, I'm able to follow the progress of `install_script` and `build_script` live as it happens on the build VM. For my `install_script`, I run a Python script to perform the necessary tasks to build my project. I had to ensure that Python wasn't buffering output so that the output wouldn't just show up at the end. After enforcing unbuffered output mode (`-u`), I was able to see the output as it was printed from my script.

However, when running my deployment Python script, enforcing the mode with `deploy_script` doesn't have an effect! The deploy script does take a while to run, so I'd like to see the output as tasks get completed by the script. Would it be possible to have the `deploy_script` output not get buffered?

(For reference, my project is running on AppVeyor here: https://ci.appveyor.com/project/alberthdev/cemu)

**Comment by FeodorFitsner** [comment]
Interesting. Actually, there is no difference in the way AppVeyor executes commands in either `build_script`, `deploy_script` or other sections.

**Comment by alberthdev** [comment]
That's interesting... the only other possibility is that the first command is buffered, while the rest are not. In my `appveyor.yml`, my `build_script` runs a command before running the long-duration task, while my `deploy_script` only runs the long-duration task. Of course, this is purely speculation, and when I get a chance I'll have to test it out.

**Comment by FeodorFitsner** [comment]
I did some changes to Build Agent (while working on another issue, but this may be related) and added a new `test` image under your account.

Could you please add `os: test` to your `appveyor.yml` and run build on that test image to see if it makes any difference.

**Comment by alberthdev** [comment]
Sorry for the delay! I just tested with an update to my configuration, and it looks like deployment unbuffered output work - thanks for the fix! Do you know when this will be rolled out to the main image(s)?

**Comment by FeodorFitsner** [comment]
Can you test one more time please? I did some changes.

**Comment by alberthdev** [comment]
Installation, building, and deployment output are all being displayed live (unbuffered) correctly!

In addition, it looks as if the build is completing much faster - last time, it was very, very slow - jumping from a <30 minute build time to 30-40+ minutes. Output seems to be much faster as well, with blocks of text coming out all at once, versus a somewhat slow line-by-line. Of course, this could just be a placebo effect, but it does seem like things are working better this time. (Less CPU usage on the server side maybe?)

All in all, things are looking great - thanks again for the fix! Should I continue to use `os: test` or should I switch? (It doesn't look like the builds are breaking from the test image...)

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!

Remove "os: test" image for now. We'll deploy an update across default images later this week.

**Comment by alberthdev** [comment]
Will do. Thanks again for your help!
