### ISSUE TITLE
Add "before_package" build step

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#617]
Discussion: http://help.appveyor.com/discussions/questions/2048-after-build-step-runs-after-nuget

**Comment by niemyjski** [comment]
Is it possible to specify a on branch step on before_package? For example. I only want to run my GitLink command on master branch.

I'm looking for something like this

```
before_package:
  - on
    branch:master
  - GitLink .\
```

I might want this for tests too (to selectively specify what tests I want to run on different branches).

**Comment by niemyjski** [comment]
Also, I believe your online yml spec is out of date.

**Comment by FeodorFitsner** [comment]
You can do:

```
before_package:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" GitLink .\
```
