### ISSUE TITLE
Newman test runner not installed by default

### ISSUE THREAD

**Issue by DarinMacRae** [appveyor/ci#618]
I know it is rather easy to install in the init step but would you consider adding Newman to your list of pre-installed testing tools?

http://blog.getpostman.com/2015/04/09/installing-newman-on-windows/

**Comment by FeodorFitsner** [comment]
I see it's comes in form of npm module. How long does it take to install it during the build?

My main concern is that any node.js module installed globally may fail when you switch between node.js versions. AppVeyor allows testing against multiple node.js versions: http://www.appveyor.com/docs/lang/nodejs-iojs

I'd stick to installing it during the build.

**Comment by DarinMacRae** [comment]
Understood. If I can trust the timing numbers in the tool-tips in the console output then it takes 27 seconds it seems. Its not a big deal but wanted to throw it out there in case it was low-hanging fruit.

**Comment by FeodorFitsner** [comment]
Yeah, 27 seconds is not bad.
