### ISSUE TITLE
Environments dashboard

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#626]
Improving current "static" Environments screen by adding the information about last deployment next to each environment - very much like current Projects page shows the most recent build for each project.

**Comment by estei** [comment]
If this means we have a single page where we can see what is deployed on environments it would be lovely.

Before the change we could easily in the deployments "tab" on a project see what version was deployed to different environments, that is really missing now after the change.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
