### ISSUE TITLE
Slack incoming_webhook notification doesn't work if incoming_webhook uses secure

### ISSUE THREAD

**Issue by crunis** [appveyor/ci#628]
Slack incoming_webhook notification doesn't work if incoming_webhook uses secure.
When using "secure", I get this error:

```Error sending Slack notification: Value cannot be null.
 Parameter name: Either incoming webhook URL or Slack authentication token is required.```

The exact same configuration without encrypting the incoming_webhook works:

This works: 
```
[...]
notifications:
  - provider: Slack
    incoming_webhook: https://xxxxx
```

This doesn't work:
```
[...]
notifications:
  - provider: Slack
    incoming_webhook:
      secure: VLdYu/VfRvWLsIwZKnvR9KVPX4+7PPaWJsmmsdfSDSCD0LYkVtONTxG736t0SIzs9aGn1xImso1NZ2pCG1f7EMAdFNRNPptAY=
```

**Comment by FeodorFitsner** [comment]
Will take a look. Thanks for reporting that!

**Comment by FeodorFitsner** [comment]
It's been fixed. Update will be deployed shortly this week.

For now you can setup Slack notification with incoming webhook on project settings UI - they will be "merged" with those ones defined in appveyor.yml.

**Comment by FeodorFitsner** [comment]
Update with a fix has been deployed.
