### ISSUE TITLE
Ruby 2.2.4, 2.1.8 and 2.0.0-p648

### ISSUE THREAD

**Issue by deivid-rodriguez** [appveyor/ci#632]
Hi @FeodorFitsner !

Ruby installers [are now available](https://github.com/oneclick/rubyinstaller/issues/300) for latest rubies! Could we get those in Appveyor?

Thanks a lot!

**Comment by FeodorFitsner** [comment]
Great, thanks for letting us know!

**Comment by FeodorFitsner** [comment]
Gems updated:

* RubyGems 2.5.2
* Bundler 1.11.2
