### ISSUE TITLE
Customizable build status badge prefix

### ISSUE THREAD

**Issue by lightmare** [appveyor/ci#636]
With `passingText` et al. we can customize the text in the right half of the badge (colored background). But then there's no text in the left half (grey background).

Using the example from http://www.appveyor.com/docs/status-badges: `https://ci.appveyor.com/api/projects/status/32r7s2skrgm9ubva?svg=true&passingText=master%20-%20OK`
![master-ok](https://ci.appveyor.com/api/projects/status/32r7s2skrgm9ubva?svg=true&passingText=master%20-%20OK)

I want to do this: `https://ci.appveyor.com/api/projects/status/32r7s2skrgm9ubva?svg=true&buildText=branch-x&passingText=ok`
![custom badge](https://camo.githubusercontent.com/c3a4ca497f08f1ce9c3e155d2c98cc39761505f0/68747470733a2f2f63646e2e7261776769742e636f6d2f6c696768746d6172652f64613336613466366533323233616362393435382f7261772f663439383264663331616635323237333563626163346266393336653064333164373736323239612f6170707665796f722d62616467652d637573746f6d2d6275696c642d746578742e737667)

**Comment by FeodorFitsner** [comment]
OK, will take a look. Thanks for the suggestion.

**Comment by 304NotModified** [comment]
+1
