### ISSUE TITLE
Qt5.5+ and MSVC 2015 (x86/x64)

### ISSUE THREAD

**Issue by Nava2** [appveyor/ci#640]
I apologize if this is the wrong place, but I need Qt5.5+ and MSVC 2015, preferably against x86 and x64.

Only Qt > 5.5 supports MSVC 2015.

This library is absolutely massive, and I understand it's likely to be a hassle.

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by bjorn** [comment]
Qt 5.6 and 5.7 are by now provided for MSVC 2015 for both x86 and x64, so this issue can be closed.

https://www.appveyor.com/docs/installed-software/#qt
