### ISSUE TITLE
Add project bug?

### ISSUE THREAD

**Issue by Cyberunner23** [appveyor/ci#645]
Adding the same repo multiple times lists the repo multiple times in the projects tab. Not sure if this is intentional though...

**Comment by FeodorFitsner** [comment]
I'm not sure I understand. Could you please drop a screenshot explaining the issue?

**Comment by Cyberunner23** [comment]
Here it is https://imgur.com/GkLAGl9

**Comment by FeodorFitsner** [comment]
Ah, this is by design. You can add as many projects based on the same repository as you need. Each project could be a build with different configuration/platform or deploying to a different environment. Project display name can be changed on General tab of project settings.
