### ISSUE TITLE
/arch:SSE2 and /fp:strict fail under win32 py34

### ISSUE THREAD

**Issue by ThomasLecocq** [appveyor/ci#647]
Hi,

building a c module under python 3.4 on win32 fails in the case where /arch:SSE2 and /fp:strict are passed as arguments to cl.exe. 

```
error: Command "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /arch:SSE2 -DWIN32=1 -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\lib\site-packages\numpy\core\include -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\include -IC:\Python34_32\envs\_build_placehold_placehold_placehold_placehold_placehold_pla\include /Tcobspy\mseed\src\obspy-readbuffer.c /Fobuild\temp.win32-3.4\Release\obspy\mseed\src\obspy-readbuffer.obj /fp:strict" failed with exit status 2
```

The problem seems to be known and there is an hotfix available from MS:

https://support.microsoft.com/en-us/kb/955025

would it make sense to apply that hotfix to visual studio 10 ?

Thanks !

**Comment by ThomasLecocq** [comment]
not sure the hotfix exists for visual studio 2010, the link I mentionned is for 2008

**Comment by FeodorFitsner** [comment]
Well, that KB explicitly says it's for 2008 - I don't think it could be applied to 2010. Also, found this on the matter: https://social.msdn.microsoft.com/Forums/vstudio/en-US/00094bc3-af5f-4f8a-a02b-164f9296c5ae/is-there-a-fixpatch-available-for-issue-sse2-instructions-generated-when-archsse-is-specified?forum=vcgeneral

**Comment by ThomasLecocq** [comment]
Indeed... it seems that they said SP1 would correct that "bug"... what is installed on the workers ? 2010 vanilla or SP1 ? Thanks

**Comment by FeodorFitsner** [comment]
Yes, VS 2010 SP1 is installed (https://www.microsoft.com/en-us/download/details.aspx?id=23691)
