### ISSUE TITLE
"Do not sync ACLs" setting for Web Deploy provider

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#648]
Discussion: http://help.appveyor.com/discussions/suggestions/948-includesetaclproviderondestination-option-in-deployments

**Comment by IlyaFinkelshteyn** [comment]
Set `APPVEYOR_WAP_SKIP_ACLS` environment variable to `true` to create WAP package, which will keep Web Deploy from updating ACLs.
