### ISSUE TITLE
symbolic links in git

### ISSUE THREAD

**Issue by fommil** [appveyor/ci#650]
I have a repository

https://github.com/ensime/ensime-sbt/

that has a few symbolic links in it, but they are not being translated correctly when checked out in windows, and they look like junk.

Can you please add an option to convert these into copied files, or windows links?

**Comment by FeodorFitsner** [comment]
How are they configured? How to see them in that repo?

**Comment by fommil** [comment]
some examples https://github.com/ensime/ensime-sbt/tree/master/src/sbt-test/ensime-sbt/java-flags/project

I'm trying out this hack that I found on stackoverflow, seems legit

```
  - ps: |
      $symlinks = &git ls-files -s | gawk '/120000/{print $4}'
      foreach ($symlink in $symlinks) {
        write-host $symlink
        &git update-index --assume-unchanged $symlink
      }
```

**Comment by FeodorFitsner** [comment]
Nice, thanks for sharing the solution!

**Comment by fommil** [comment]
(unconfirmed "solution" :wink:)

**Comment by fommil** [comment]
doesn't work :-(

https://ci.appveyor.com/project/fommil/ensime-sbt/build/1.0.5

**Comment by fommil** [comment]
ok, I understand why. The "fix" just marks the files as unchanged. I'll see if I can fix this properly by resolving them.

**Comment by fommil** [comment]
now trying out

```
  - cmd: git config core.symlinks false
  - cmd: git reset --hard
```

if that works, I'd recommend setting `core.symlinks=false` as the default.

**Comment by fommil** [comment]
nope, trying `true`

**Comment by fommil** [comment]
that works!

**Comment by FeodorFitsner** [comment]
Nice!

**Comment by fommil** [comment]
it works on appveyor, but not on my local Windows 7 VirtualBox image, so I suspect this is not a universal solution.

**Comment by gvanrossum** [comment]
(According to http://stackoverflow.com/questions/5917249/git-symlinks-in-windows you must run this in Administrator mode and use a recent git version. Maybe this helps.)
