### ISSUE TITLE
Limit concurrent jobs per project

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#655]
Discussions:

- http://help.appveyor.com/discussions/questions/2123-how-to-stop-project-branches-building-concurrently
- http://help.appveyor.com/discussions/questions/2127-queue-limit-per-project
- http://help.appveyor.com/discussions/questions/2461-limit-build-agent-per-project
- http://help.appveyor.com/discussions/questions/2465-can-only-run-1-build-at-a-time-when-using-a-matrix

**Comment by FeodorFitsner** [comment]
http://help.appveyor.com/discussions/questions/2127-queue-limit-per-project

**Comment by markwalsh-liverpool** [comment]
As with the other branch. I am guessing this is now in production?

Do you have an example usage?

**Comment by FeodorFitsner** [comment]
Yes, it can be set in appveyor.yml as:

    max_jobs: 1

**Comment by markwalsh-liverpool** [comment]
Great, thanks very much

**Comment by PureKrome** [comment]
@FeodorFitsner thank you kindly for adding this feature!

Side note: Docs need to be updated. E.G. https://www.appveyor.com/docs/appveyor-yml/

**Comment by FeodorFitsner** [comment]
Updated 😉

**Comment by PureKrome** [comment]
You guys are awesome! thanks!!
