### ISSUE TITLE
no rebuild button

### ISSUE THREAD

**Issue by fommil** [appveyor/ci#660]
![2016-02-27-214751_1918x1078_scrot](https://cloud.githubusercontent.com/assets/1914041/13375593/c769f85c-dd9b-11e5-8a2c-29a9a3ec77c5.png)

**Comment by FeodorFitsner** [comment]
What username (email) are you accessing that project?

**Comment by fommil** [comment]
Sam Halliday (gmail)

**Comment by FeodorFitsner** [comment]
I see. That username doesn't have any access to `aemoncommon` account. Ask owner of that account  to add you as collaborator.

**Comment by fommil** [comment]
The account is ensime, appveyor must have it wrong - unable to deal with organisation accounts maybe?

**Comment by FeodorFitsner** [comment]
`ensime` is probably GitHub account. AppVeyor account is what you see in project URL. It can be changed on https://ci.appveyor.com/account

Take a look at this guide for setting up the team: http://www.appveyor.com/docs/team-setup

**Comment by fommil** [comment]
@FeodorFitsner sorry, I've now read that guide a couple of times and I find it very confusing. Is there a simple practical step that we can take to give all members of the github `ensime` organisation the necessary `role` on AppVeyor? @aemoncannon you might need to do something.

**Comment by fommil** [comment]
possibly Aemon needs to add people to https://ci.appveyor.com/team ? But it sounds like we might need to do that for each person.

**Comment by FeodorFitsner** [comment]
I assume you currently use "GitHub" sign-in button to login AppVeyor. Suppose you have some team already under "ensime" organization, say `ensime/Developers`. Aemon, who is the owner of `aemoncannon` AppVeyor account, should add that `ensime/Developers` team on https://ci.appveyor.com/team and associate it with some AppVeyor role, say "Administrator". Then you should re-login and choose "aemoncannon" account on Sign in page.

**Comment by fommil** [comment]
@FeodorFitsner I've just bought an OSS subscription for myself, because I'm using AppVeyor heavily and I'd like to get the speed benefits. I've sent you a question about plans on the support system, but to continue this thread...

my plan is for my github account `fommil` but I'd also like to use that plan for all the repositories under the github `ensime` user.

Unfortunately, right now (for reasons unknown), the github `ensime` account is using the appveyor `aemoncannon` username. Can you please move the `ensime` builds to use my account instead? I'll add the ensime developers team.

**Comment by fommil** [comment]
ok, I was able to do this myself by deleting all the webhooks, and adding a new project.
