### ISSUE TITLE
Error when calling /api/account/encrypt

### ISSUE THREAD

**Issue by Cyberunner23** [appveyor/ci#665]
Hello I am using the /api/account/encrypt endpoint in my program but I keep receving an error ({"message":"The request is invalid.","modelState":{"request.plainValue":["An error has occurred.","An error has occurred."]}}) and I can't figure out what I'm doing wrong...

Here are the parameters I'm using:
Header:
```
Authorization: *api token*
Content-Type: application/json;charset=utf-8
Content-Length: 81
```
Body:
```
{"plainValue":"1234123412341234d9feee697b50c3c3191af309aa8f31566019c0812341234"}
```

**Comment by FeodorFitsner** [comment]
How do you call it?

-Feodor




On Mon, Feb 29, 2016 at 6:35 PM -0800, "Alex" <notifications@github.com> wrote:












Hello I am using the /api/account/encrypt endpoint on my program but I keep reving an error ({"message":"The request is invalid.","modelState":{"request.plainValue":["An error has occurred.","An error has occurred."]}}) and I can't figure out what I'm doing wrong...



Here are the parameters I'm using:

Header:

Authorization: *api token*
Content-Type: application/json;charset=utf-8
Content-Length: 81




Body:

{"plainValue":"1234123412341234d9feee697b50c3c3191af309aa8f31566019c0812341234"}

**Comment by Cyberunner23** [comment]
I use the POST request and I'm using the hyper library for the rust language.

**Comment by FeodorFitsner** [comment]
I've just tested it from PowerShell and it worked like a charm:

```posh
$headers = @{
  "Authorization" = "Bearer $token"
  "Content-type" = "application/json"
}
$body = '{"planValue":"Hello, world!"}'
Invoke-WebRequest https://ci.appveyor.com/api/account/encrypt -Method POST -Headers $headers -Body $body
```

Results:
```
StatusCode        : 200
StatusDescription : OK
Content           : Nk5v+tmR+nQ==
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Content-Length: 24
                    Cache-Control: no-cache
                    Content-Type: text/plain
                    Date: Tue, 01 Mar 2016 03:33:51 GMT
                    Expires: -1
                    Server: Microsoft-IIS/8.5
                    X-AspNet-Version:...
Forms             : {}
Headers           : {[Pragma, no-cache], [Content-Length, 24], [Cache-Control, no-cache], 
                    [Content-Type, text/plain]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 24
```

**Comment by Cyberunner23** [comment]
Thats odd... I'm even doing another api call right before this one the same way and it works fine yet it breaks on this one...

**Comment by FeodorFitsner** [comment]
Try running it from Fiddler or Postman.

**Comment by Cyberunner23** [comment]
waiiiiit i figured it out..., I made a typo in my code and was giving hyper the wrong length for the body, it was probably cutting out a bit of the body making it invalid json....
