### ISSUE TITLE
phantomjs.launcher fails with com error

### ISSUE THREAD

**Issue by alexandru-calinoiu** [appveyor/ci#666]
Hi,

This is occuring the last couple of days, running karma test's fails from time to time with on change to the actual code. The error we get is:

```
[09:49:17] Starting 'runKarma'...
01 03 2016 09:49:17.362:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
01 03 2016 09:49:17.378:INFO [launcher]: Starting browser PhantomJS2
01 03 2016 09:49:17.674:ERROR [phantomjs.launcher]: SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"

```

**Comment by FeodorFitsner** [comment]
What project is that?

**Comment by alexandru-calinoiu** [comment]
https://ci.appveyor.com/project/agilefreaks/jll

**Comment by FeodorFitsner** [comment]
What was the build when it happened for the first time?

**Comment by alexandru-calinoiu** [comment]
I've traced to this one https://ci.appveyor.com/project/agilefreaks/jll/build/1.0.149

**Comment by FeodorFitsner** [comment]
I've looked at the logs of that build. Looks like that error is non-fatal, i.e. it continues to run tests after it and all tests pass, right?

**Comment by branneman** [comment]
I've encountered the same error on my project: [BranvanderMeer/argus-eyes](https://ci.appveyor.com/project/BranvanderMeer/argus-eyes)
```
SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
```

However, this seems like this bug is in Qt or PhantomJS itself if I see this issue:
https://bugreports.qt.io/browse/QTBUG-38993

**Comment by johnnyreilly** [comment]
I'm seeing this as well...

**Comment by johnnyreilly** [comment]
But like @FeodorFitsner says - it's non erroring and so more of an irritation than anything else.

**Comment by XhmikosR** [comment]
@FeodorFitsner: https://ci.appveyor.com/project/giakki/uncss/build/374/job/ampr1awnrbofmgcu

For me it's a fatal error.

**Comment by sergey-s-betke** [comment]
@FeodorFitsner , https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.7.0-appveyor.49.build.23

For me it's a fatal error... What can I do?

**Comment by FeodorFitsner** [comment]
That's the thing AppVeyor Build Agent works as an interactive process, not a service. You can see it running in Task bar when you log in via RDP to a build worker.

However, I think the reason for this error maybe "headless" nature of Google Compute Engine virtual machines.

**Comment by sergey-s-betke** [comment]
@FeodorFitsner , I need help with `SetProcessDpiAwareness`. I tried change `qt.conf` for miktex (`WindowsArguments = dpiawareness=0`), but - https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.7.0-appveyor.64.build.38.

I tried `Install-WindowsFeature Server-Gui-Shell –Restart`, but GUI installed on build server??? How I can resolve error with `SetProcessDpiAwareness` API on appveyor build server?

**Comment by FeodorFitsner** [comment]
Hi Sergey,

I've moved your account to a different environment with Hyper-V VMs. Let me know if you are still getting that error.

**Comment by sergey-s-betke** [comment]
Hi, @FeodorFitsner, unfortunately, the result still: https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.7.0-appveyor.66.build.41

**Comment by sergey-s-betke** [comment]
@FeodorFitsner, build processes start from service account or from "user" account? "cmd" steps run with hidden `cmd.exe` windows or with visible window?

In my infrastructure I start miktex utilites on windows 8, 8.1 from user account, on windows server 2012 R2 from service account - without errors!..

**Comment by FeodorFitsner** [comment]
It's started under user account in visible window. Try using RDP for troubleshooting: http://www.appveyor.com/docs/how-to/rdp-to-build-worker

**Comment by sergey-s-betke** [comment]
@FeodorFitsner, now, on "clear" windows 2012 R2 server virtual machine (with GUI) - without errors...

**Comment by sergey-s-betke** [comment]
Workaround for MikTeX:

        $null = Install-Package -Name 'miktex' -MinimumVersion '2.9' -ProviderName Chocolatey -Source chocolatey;
        Set-ItemProperty `
                -Path 'HKLM:\Software\MiKTeX.org\MiKTeX\2.9\MPM' `
                -Name 'AutoInstall' `
                -Value 1 `
                -Force `
        ;

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
