### ISSUE TITLE
cURL seems to hang.

### ISSUE THREAD

**Issue by Cyberunner23** [appveyor/ci#667]
Hello on my [TrelloBST](https://github.com/Cyberunner23/TrelloBST) project I am calling some poweshell code in on_failure: and on_success: However the build keeps hanging at the curl call (i think) and I don't know why. In addition I tried printing the data I'm suplying curl with Write-Host and it does not output anything even though there is text that is supposed to be printed...

**Comment by FeodorFitsner** [comment]
What URL are you calling? What curl are you using? Have you tried calling it with PowerShell?

**Comment by Cyberunner23** [comment]
I am using powershell and I'm using https://api.trello.com/1/cards as the url and I'm using the command line interface curl

**Comment by FeodorFitsner** [comment]
I'm seeing "Cannot GET /1/cards" when calling that URL. Is that correct? Does it require authentication?

**Comment by Cyberunner23** [comment]
It's supposed to be a POST, the thing is I'm doing the same curl call in another repo and it works fine, maybe its a command before the curl call?

**Comment by FeodorFitsner** [comment]
What command is that?

**Comment by Cyberunner23** [comment]
The curl command I'm using is curl -s --data $($data) https://api.trello.com/1/cards

**Comment by FeodorFitsner** [comment]
Could you please do a simple repro of this issue in a public repository?

**Comment by Cyberunner23** [comment]
Here it is https://ci.appveyor.com/project/Cyberunner23/trellobst/build/1.0.12 I notices that there was an error in the definition of some variables, now I am wondering why it's hanging in my main build instead of giving of an error as it is in the repro...

**Comment by FeodorFitsner** [comment]
In that repro PowerShell is having some issues. Try replacing it with this one:

```
$appveyor_branch = "[$($env:APPVEYOR_REPO_BRANCH)]"
$ci_name         = "[AppVeyor]"
$os_name         = "[Windows]"
$compiler        = "[$($env:COMPILER)]:%20"
$pass            = "#$($env:APPVEYOR_BUILD_NUMBER)%20FAILED"
$card_name       = "name=$($appveyor_branch)$($ci_name)$($os_name)$($compiler)$($pass)"
$additional_data = "&due=null&pos=top"
$description     = "&desc=\[Logs\]:%20https://ci.appveyor.com/project/$($env:APPVEYOR_REPO_NAME)/build/$($env:APPVEYOR_BUILD_VERSION)/job/$($env:APPVEYOR_JOB_ID)"
$trello_data     = "&idList=$($env:TRELLO_API_LIST_ID)&idLabels=$($env:TRELLO_API_BUILD_PASS_ID)&token=$($env:TRELLO_APP_TOKEN)&key=$($env:TRELLO_API_KEY)"
$data            = "$($card_name)$($additional_data)$($description)$($trello_data)"
Write-Host $($data)
```

**Comment by Cyberunner23** [comment]
That fixed it, I did this in my main build and it also fixed the issue, now seems to me that invalid powershell code in on_failure: hangs the build...

**Comment by FeodorFitsner** [comment]
what do you have in `on_failure`?

**Comment by Cyberunner23** [comment]
The same code in build_script: in the repro.

**Comment by FeodorFitsner** [comment]
So, it hangs on "curl" command (if you see $data in a build log)?

**Comment by Cyberunner23** [comment]
Actually at the beginning I thought curl was hanging but it was hanging on the missing " in the powershell code describing a variable it seems. I also forgot to add $ in front of "compiler" and "pass" on the $card_name line. Maybe that could of caused the hang too.

**Comment by Cyberunner23** [comment]
I fixed those little mistakes in my main build and in the appveyor_repro branch and now its working fine so my guess is that if powershell return some sort of error in on_fail: and perhaps on_success: the build hangs.

**Comment by Cyberunner23** [comment]
I just performed reproduction to what I think the issue is. Having invalid powershell code in on_failure: (didn't test for on_success yet) causes the build to hang. I basically took my main branch which now works and removed a " at the end of $card_name and the build hangs.

https://ci.appveyor.com/project/Cyberunner23/trellobst/build/1.0.95/job/u45lpxkdqh3oo0tn

**Comment by FeodorFitsner** [comment]
Hm, nice finding. Could you please create another issue then and close this one. I will take a look into why it hangs if PS is broken.
