### ISSUE TITLE
Golang 1.6

### ISSUE THREAD

**Issue by calavera** [appveyor/ci#670]
I know it's hard to catch up, but it'd be awesome if you could preinstall Go 1.6, so I don't have to do this in every build:

```
rmdir c:\go /s /q
appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
msiexec /i go%GOVERSION%.windows-amd64.msi /q
```

Thanks for making testing on Windows boxes so straight forward :heart:

**Comment by FeodorFitsner** [comment]
Yep, will schedule its deployment.
