### ISSUE TITLE
appveyor.yml in PR not picked up

### ISSUE THREAD

**Issue by pzychotic** [appveyor/ci#679]
I created a PR for a forked project that made it necessary to also update the .appveyor.yml file to make the project compile with my changes. Unfortunately the PR keeps failing because my changes in the .appveyor.yml file are not used, it still tries to build with the old version of the build script.

Is this scenario not yet supported or is this a bug?

see: electronicarts/EASTL#32

**Comment by FeodorFitsner** [comment]
`.appveyor.yml` is ignored because it should be `appveyor.yml` (without dot at the start). You can update project settings and specify custom name for YML configuration file on "General" tab.
