### ISSUE TITLE
GitHub deployment provider: update release details if exists

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#680]
Requested here: https://github.com/appveyor/ci/issues/480#issuecomment-193263278

**Comment by cyberium** [comment]
Thank you for this issue (maybe a new feature tag will be more clear)

I dont see any way in github API to edit TAG btw. Maybe the best is to delete tag and recreate it, but this force to delete the attached releases separatly. And following their API that need the use of the release id wich is available after a GET request that should be provessed to retrieve its ID from the json response. Is there an easy way to retrieve that id from tag name?

As i dont want to wait you with crossed arms to implement this i am trying to implement something similar using curl.

**Comment by FeodorFitsner** [comment]
Well, I've been thinking about updating tag name and commitish through this API: https://developer.github.com/v3/repos/releases/#edit-a-release I'm not sure about re-creating a tag.

**Comment by cyberium** [comment]
Ah yes that should do the trick. I hope it will update the date and the commit hash as well.

**Comment by cyberium** [comment]
Nice, but how its supposed to work now? Did it supposed to update release details automaticaly?

**Comment by FeodorFitsner** [comment]
No, you should add `force_update: true` to the provider settings.

**Comment by cyberium** [comment]
https://ci.appveyor.com/project/cyberium/avtest/build/job/cghb3j77koboy8vw
In this log, for any reason the last operation whose consist of deleting release file before updating with the last one failed.
However i see the tag is updated anyway. So the result is an updated tag with an old binary :(

**Comment by FeodorFitsner** [comment]
I've seen that once while testing the provider. Looks like it's something intermittent - can you try again please?

**Comment by cyberium** [comment]
Yes its intermittent and probably a github issue. I just want to point the fact that if for any reason the file cannot be updated the tag have to not be updated too.
(the rebuild succeed so i cannot reproduce it)

**Comment by FeodorFitsner** [comment]
Interesting. There is the following content in the response:

    <html><head><title>405 Not Allowed</title></head><body bgcolor="white"><center><h1>405 Not Allowed</h1></center><hr><center>nginx</center></body></html>

I will report to GitHub.

Regarding release update - I agree it should be updated *after* all assets have been successfully uploaded.
