### ISSUE TITLE
deleting branch leads to failed build

### ISSUE THREAD

**Issue by johannjacobsohn** [appveyor/ci#681]
Appveyor is triggered by deleting a branch via `$ git push --delete <branch>`. That branch doesn't really exist, so the build fails.

```
Build started
git clone -q --branch= https://bitbucket.org/jjacobsohn/so2-camera.git C:\projects\so2-camera
fatal: Remote branch  not found in upstream origin
Command exited with code 128
```

https://ci.appveyor.com/project/jjacobsohn/so2-camera/build/1.0.256

**Comment by FeodorFitsner** [comment]
Can you please send me webhook request corresponding to that commit (BitBucket -> repo Settings ->  Webhooks -> View Requests)?

**Comment by johannjacobsohn** [comment]
Hi, I cannot see any requests?

**Comment by FeodorFitsner** [comment]
For that repository is webhook configured under Services or Webhooks?

**Comment by johannjacobsohn** [comment]
https://ci.appveyor.com/api/bitbucket/webhook?id=wtsnd28pv7ymsabg

**Comment by FeodorFitsner** [comment]
I mean on BitBucket side?

**Comment by johannjacobsohn** [comment]
I am not sure if I understand what you want me to do

**Comment by FeodorFitsner** [comment]
Go to BitBucket, repository Settings then check whether webhook is configured on Webhooks page (new webhooks) or Services page (POST service - old webhooks).

**Comment by johannjacobsohn** [comment]
Its configured on the Service page

**Comment by FeodorFitsner** [comment]
Oh, OK. Then there is no history for those webhooks.

I tried playing with this yesterday but wasn't able to reproduce. I'm just wondering if you could do a simple repro in a public repository, i.e. repo with few fake files then a list of git commands leading to the issue? Thanks!

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
