### ISSUE TITLE
artifact not generated

### ISSUE THREAD

**Issue by malublu** [appveyor/ci#686]
I get the message:

Packaging artifacts...OK
Deploying using FTP provider
Neither artifacts nor application were uploaded.
Build success

Also there is no artifact in the webpannel.

But my config has the artifact:

branches:
  only:
    - master
    - stable
install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake project.pro -r
  - mingw32-make
  - mingw32-make clean
  - windeployqt .\release\Main.exe
  - 7z a win32-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_REPO_BRANCH%.zip .\release\
artifacts:
  - path: win32-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_REPO_BRANCH%.zip
    name: win32-%APPVEYOR_REPO_COMMIT%-%APPVEYOR_REPO_BRANCH%
deploy:
  provider: FTP
  protocol: sftp
  host:
    secure: *******
  username:
    secure: *******
  password:
    secure: *******
  folder:
    secure: *******

Is that my bug?
7z generated the zip file successful.

**Comment by FeodorFitsner** [comment]
To use environment variables in artifacts definition it should be:

```
artifacts:
  path: win32-$(APPVEYOR_REPO_COMMIT)-$(APPVEYOR_REPO_BRANCH).zip
  name: win32-$(APPVEYOR_REPO_COMMIT)-$(APPVEYOR_REPO_BRANCH)
```

**Comment by malublu** [comment]
thank you :)
