### ISSUE TITLE
LLVM 3.8.0 (x64)

### ISSUE THREAD

**Issue by reupen** [appveyor/ci#688]
http://llvm.org/releases/download.html#3.8.0

I haven't had any problems using the 64-bit version with VS so it should be fine to use that.
http://llvm.org/releases/3.8.0/LLVM-3.8.0-win64.exe

**Comment by FeodorFitsner** [comment]
As a result of this update path to LLVM command line tools will change to `C:\Program Files\LLVM\bin`.
