### ISSUE TITLE
Add "Python for Windows Extensions" (pywin32) to workers

### ISSUE THREAD

**Issue by kveretennicov** [appveyor/ci#689]
From https://sourceforge.net/projects/pywin32/

The problem is that pywin32 has no silent installation mode at the moment and it cannot be installed with normal `pip install` or even `msiexec /i`. So I had to use a workaround suggested by pywin32 author: download installer, unpack it, copy relevant files into Python and run post-install script. This is quite cumbersome and took some time to figure out.

**Comment by FeodorFitsner** [comment]
Can you drop a link to your project please (if it's public)?

**Comment by kveretennicov** [comment]
Yep, see pywin32 dance starting at https://ci.appveyor.com/project/kveretennicov/kallithea/build/45#L112. It's finished by https://ci.appveyor.com/project/kveretennicov/kallithea/build/45#L1452.

**Comment by FeodorFitsner** [comment]
We have multiple Python versions preinstalled on build workers. How does this thing co-exist with regular Python? Does it go as an upgrade to certain Python version or it's a strand alone product? Does the installer modify PATH or registry thus interfering with pythons?

**Comment by kveretennicov** [comment]
Pywin32 is a kind of add-on to standard Python. Its installer finds installed Python location and adds a few extra modules to it. It doesn't modify PATH.

I've checked locally with a mix of Python 2.7, 3.4 and 3.5, both 32- and 64-bit. Installed pywin32 for each Python variant and they co-exist peacefully.

**Comment by FeodorFitsner** [comment]
I've noticed the approach you use to install pywin32 during the build takes around 30-40 seconds which is not bad? You may further beautify it by removing excessive output from curl and 7z.

**Comment by kveretennicov** [comment]
Yes, it's not too bad. Though it took some time to figure it out and get working.

Another possibility could be using pypiwin32 as a drop-in replacement for pywin32. It lacks some less often used stuff, like COM, but is pip-installable.
