### ISSUE TITLE
"GitHub Pull Request" notification provider

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#690]
Requested by @exalted

**Comment by exalted** [comment]
Is there anything I could do to help implementing this?

**Comment by FeodorFitsner** [comment]
I think we can have it working this week

**Comment by exalted** [comment]
👏

--
Ali




On Mon, Mar 14, 2016 at 11:23 AM -0700, "Feodor Fitsner" <notifications@github.com> wrote:












I think we can have it working this week

**Comment by FeodorFitsner** [comment]
Too bad there is no API for new emotions, kind of placing "wow" on broken build :)

**Comment by exalted** [comment]
I guess you could use unicode emojis for that.

**Comment by FeodorFitsner** [comment]
Take a look at this GitHub PR notification test: https://github.com/FeodorFitsner/simple-console/pull/14

AppVeyor comments from two users: failed build/deployment and successful. Notification template can be updated.

Does it make sense to have two accounts for color coding? What would be the best default template?

**Comment by exalted** [comment]
@FeodorFitsner neat!

However I personally am not sold to the idea about two accounts for color coding, how about using :white_check_mark: (`:white_check_mark:`) and :x: (`:x:`) respectively? ([Back then](https://github.com/github/hubot-scripts/blob/master/src/scripts/semaphoreapp.coffee#L160-L162) I implemented something similar for http://semaphoreci.com and [HUBOT](https://hubot.github.com/).)

Also, configuration options...

```
on_build_success: true|false
on_build_failure: true|false
on_build_status_changed: true|false
```

... will still be valid also for this provider?

**Comment by FeodorFitsner** [comment]
Nice idea with emoji, thanks! I agree, colorful appveyor users don't look cool :)

**Comment by FeodorFitsner** [comment]
Here you are: https://github.com/FeodorFitsner/simple-console/pull/14

**Comment by exalted** [comment]
How are things about this feature? Is there anything else I could help you with? Thanks.

**Comment by FeodorFitsner** [comment]
It's implemented. We are going to deploy an AppVeyor update with it later this week.

**Comment by exalted** [comment]
:clap:

**Comment by FeodorFitsner** [comment]
Documentation: http://www.appveyor.com/docs/notifications#github-pull-request-bot

**Comment by exalted** [comment]
I will setup one my my public repos and come back with feedback in case any issue arises. In any case thanks a bunch for :shipit: this so quick! :pray: 

:clap: :clap: :clap:

**Comment by exalted** [comment]
P.S.: http://www.appveyor.com/docs/appveyor-yml is missing a new section for this new notification kind.

**Comment by exalted** [comment]
@FeodorFitsner not entirely sure how am I supposed to configure this to work for a public repository. I tried https://github.com/wedoit-io/WEDOBADGE/pull/16/files but when a build fails, @AppVeyorBot doesn't seem to comment on the PR.

Any ideas?

**Comment by exalted** [comment]
> @FeodorFitsner not entirely sure how am I supposed to configure this to work for a public repository. I tried https://github.com/wedoit-io/WEDOBADGE/pull/16/files but when a build fails, @AppVeyorBot doesn't seem to comment on the PR.

Just ignore that: https://github.com/wedoit-io/WEDOBADGE/pull/16#issuecomment-202882950

My bad, sorry! :pray:

**Comment by exalted** [comment]
@FeodorFitsner although `on_build_status_changed: true` is enabled, after a failing build @AppVeyorBot didn't comment on the PR when a later build was successful.

You can see it action at https://github.com/wedoit-io/WEDOBADGE/pull/16

This time I am pretty sure... :wink:

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
I've been unable to reproduce it, yet. Could you please let me know when it happens again.

**Comment by exalted** [comment]
@FeodorFitsner there [you have it](https://github.com/exalted/try_appveyor/pull/1). You can see builds here: https://ci.appveyor.com/project/exalted/try-appveyor.

I was expecting a "build completed/succeeded" after [build failed](https://github.com/exalted/try_appveyor/pull/1#issuecomment-203419307) comment.

Also, let me requote, in case you missed it:

> P.S.: http://www.appveyor.com/docs/appveyor-yml is missing a new section for this new notification kind.

**Comment by exalted** [comment]
More feedback: as I understand it current implementation uses [issues API](https://developer.github.com/v3/issues/comments/#create-a-comment) to create a comment on a PR, but I think it's better to create a commit comment using [repos API](https://developer.github.com/v3/repos/comments/#create-a-commit-comment), because those comments will still appear in PR comments (as well as on branches); and above all, if a commit is later "removed" from history (e.g., via `rebase`, etc.) then GitHub will mark it as "superseded".

What do you think?

**Comment by FeodorFitsner** [comment]
Well, I think it's a good idea, though it doesn't sounds like "PR" notification anymore, but it's sort like "commit status notification". I think we can have two approaches in the same notification provider.

I've added a new issue for that: https://github.com/appveyor/ci/issues/724

**Comment by exalted** [comment]
@FeodorFitsner I think you have a very valid point from a technical point of view. If you think about it from product/feature side though, I don't think there isn't a much compelling reason to have to choose between the two.

As a user I want to be notified if a PR is :white_check_mark: or :x: , that's all. AppVeyor is your product and definitely you will make the right calls, but I think you should be able to _technically_ use repos API to comment on commits and if they're part of a PR. From product's point of view _I think_ this should would have the same UX as if @AppVeyorBot would comment on PR directly.

**Comment by exalted** [comment]
> I think we can have two approaches in the same notification provider.

Re-reading this, I realize, we might be in agreement actually. :+1:

**Comment by exalted** [comment]
> I think we can have two approaches in the same notification provider.

@FeodorFitsner any progress on this one please? :beers: 

> http://www.appveyor.com/docs/appveyor-yml is missing a new section for this new notification kind.

... still missing. :pray: 

Should I be opening new issues for each of the points above perhaps? :bulb:

**Comment by FeodorFitsner** [comment]
So, in case with commit messages I guess provider auth token should allow access to "source" repository (in terms of PR), not "target" repo where PR resides, right?

**Comment by exalted** [comment]
Hmmm... Sounds about right. Is this an issue for the current implementation or?

**Comment by exalted** [comment]
@FeodorFitsner heads-up! :wine_glass:

**Comment by FeodorFitsner** [comment]
Oh, almost forgot! Will try to deliver commit comments this week.

**Comment by exalted** [comment]
🤘 I hope I am not being too pushy, my intention for the heads-up was constructive entirely. Looking forward... 

Keep up the good work!

**Comment by FeodorFitsner** [comment]
Well, I think I'm going to postpone this item. After looking into current notifications implementation there is missing data about head commit repository. Some things should be refactored.
