### ISSUE TITLE
Install AMD APP SDK (OpenCL)

### ISSUE THREAD

**Issue by dlemstra** [appveyor/ci#692]
We are using AppVeyor to create the binaries of ImageMagick.We would like to publish a binary that has OpenCL support but we need to install the AMD APP SDK. To install the 3.0 version that can be found here: http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/ we need to use a web installer. And to download the installer we need accept a license so it won't be that easy and maybe even impossible to do automate that as you suggested here: http://help.appveyor.com/discussions/suggestions/806-install-amd-app-sdk-opencl. We would like to have the AMD APP SDK pre-installed on your/our build images.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
