### ISSUE TITLE
Cygwin x64

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#695]
Discussion: http://help.appveyor.com/discussions/problems/4302-cygwin64-usrbinuname-returns-an-invalid-string-msys_nt-63-appveyor-vm-240029253-2016-01-07-1939-x86_64-msys

Cygwin root folder: `C:\cygwin64`

Installer downloaded from https://cygwin.com/setup-x86_64.exe and available as `C:\cygwin64\setup-x86_64.exe`

Installed modules:
```
autoconf
automake
bison
gcc-core
gcc-g++
mingw-runtime
mingw-binutils
mingw-gcc-core
mingw-gcc-g++
mingw-pthreads
mingw-w32api
libtool
make
python
gettext-devel
gettext
intltool
libiconv
pkg-config
git
wget
curl
```

Installation command used:
```
C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl
```

**Comment by zosrothko** [comment]
Thanks for this quick setup

**Comment by zosrothko** [comment]
Hi

I installed openssl on Cygwin but it does not seems to be available to the runner vm. Did I miss something
c:\cygwin\setup-x86.exe -B -q -n -N -d -l C:/cygwin/var/cache/setup -R c:\cygwin -s http://cygwin.mirror.constant.com  -P openssl
Starting cygwin install, version 2.873
User has backup/restore rights
Current Directory: C:/cygwin/var/cache/setup
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: c:\cygwin system
Selected local directory: C:/cygwin/var/cache/setup
net: Direct
site: http://cygwin.mirror.constant.com/
Adding required dependency desktop-file-utils: Selecting version 0.22-2 for installation.
Adding required dependency libnghttp2_14: Selecting version 1.7.1-1 for installation.
Adding required dependency libpsl5: Selecting version 0.12.0-1 for installation.
Adding required dependency perl-Unicode-Normalize: Selecting version 1.25-1 for installation.
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/desktop-file-utils/desktop-file-utils-0.22-2.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/nghttp2/libnghttp2_14/libnghttp2_14-1.7.1-1.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/libpsl/libpsl5/libpsl5-0.12.0-1.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/openssl/openssl-1.0.2g-3.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/perl-Unicode-Normalize/perl-Unicode-Normalize-1.25-1.tar.xz
Running preremove script for  openssl
Uninstalling openssl
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/desktop-file-utils/desktop-file-utils-0.22-2.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/nghttp2/libnghttp2_14/libnghttp2_14-1.7.1-1.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/libpsl/libpsl5/libpsl5-0.12.0-1.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/openssl/openssl-1.0.2g-3.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/perl-Unicode-Normalize/perl-Unicode-Normalize-1.25-1.tar.xz
Changing gid back to original
running: c:\cygwin\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
running: c:\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/0p_update-info-dir.sh"
running: c:\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_desktop-file-utils.sh"
Changing gid to Administrators
Ending cygwin install
...
sh.exe : ls: cannot access /usr/include/openssl/: No such file or directory
At line:1 char:1
+ & sh -c "ls -l /usr/include/openssl/"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ls: cannot acce...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError


include/Poco/Crypto/OpenSSLInitializer.h:26:28: fatal error: openssl/crypto.h: No such file or directory

**Comment by FeodorFitsner** [comment]
Sorry for confusion - I've added this issue to install Cygwin 64 over this week. It's not yet deployed to build workers.

...even if it were installed already you are using wrong command. It should be `C:\cygwin64\setup-x86_64.exe` when Cygwin 64 is installed on build workers.

**Comment by zosrothko** [comment]
Your remark is correct... but I am also installing openssl on C:\cygwin but it does not work and I used this issues to mention it because the issue on C:\cygwin installation is closed.

**Comment by FeodorFitsner** [comment]
You would better create a new issue or post it on [forums](http://help.appveyor.com/dashboard). Post your `appveyor.yml` there please.
