### ISSUE TITLE
Cygwin: Installation of openssl using setup-x86.exe

### ISSUE THREAD

**Issue by zosrothko** [appveyor/ci#696]
Hi

The loined appveyor.yml is sued to download and install the Cygwin OpenSSL component but it seems openssl is not really installed. See the log below

c:\cygwin\setup-x86.exe -B -q -n -N -d -l C:/cygwin/var/cache/setup -R c:\cygwin -s http://cygwin.mirror.constant.com -P openssl
Starting cygwin install, version 2.873
User has backup/restore rights
Current Directory: C:/cygwin/var/cache/setup
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
root: c:\cygwin system
Selected local directory: C:/cygwin/var/cache/setup
net: Direct
site: http://cygwin.mirror.constant.com/
Adding required dependency desktop-file-utils: Selecting version 0.22-2 for installation.
Adding required dependency libnghttp2_14: Selecting version 1.7.1-1 for installation.
Adding required dependency libpsl5: Selecting version 0.12.0-1 for installation.
Adding required dependency perl-Unicode-Normalize: Selecting version 1.25-1 for installation.
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/desktop-file-utils/desktop-file-utils-0.22-2.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/nghttp2/libnghttp2_14/libnghttp2_14-1.7.1-1.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/libpsl/libpsl5/libpsl5-0.12.0-1.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/openssl/openssl-1.0.2g-3.tar.xz
Downloaded C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/perl-Unicode-Normalize/perl-Unicode-Normalize-1.25-1.tar.xz
Running preremove script for openssl
Uninstalling openssl
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/desktop-file-utils/desktop-file-utils-0.22-2.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/nghttp2/libnghttp2_14/libnghttp2_14-1.7.1-1.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/libpsl/libpsl5/libpsl5-0.12.0-1.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/openssl/openssl-1.0.2g-3.tar.xz
Extracting from file://C:/cygwin/var/cache/setup/http%3a%2f%2fcygwin.mirror.constant.com%2f/x86/release/perl-Unicode-Normalize/perl-Unicode-Normalize-1.25-1.tar.xz
Changing gid back to original
running: c:\cygwin\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
running: c:\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/0p_update-info-dir.sh"
running: c:\cygwin\bin\bash.exe --norc --noprofile "/etc/postinstall/zp_desktop-file-utils.sh"
Changing gid to Administrators
Ending cygwin install
...
sh.exe : ls: cannot access /usr/include/openssl/: No such file or directory
At line:1 char:1

    & sh -c "ls -l /usr/include/openssl/"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CategoryInfo : NotSpecified: (ls: cannot acce...le or directory:String) [], RemoteException
        FullyQualifiedErrorId : NativeCommandError

include/Poco/Crypto/OpenSSLInitializer.h:26:28: fatal error: openssl/crypto.h: No such file or directory

Joined the appveyor.yml

[appveyor.yml.txt](https://github.com/appveyor/ci/files/175959/appveyor.yml.txt)

**Comment by FeodorFitsner** [comment]
I believe what you are looking for is `openssl-devel` package:

    c:\cygwin\setup-x86.exe -B -q -n -N -d -l C:/cygwin/var/cache/setup -R c:\cygwin -s http://cygwin.mirror.constant.com -P openssl-devel

`openssl` contains OpenSSL command line utility only.

**Comment by zosrothko** [comment]
ok you're rigth... sorry for the noise...

**Comment by zosrothko** [comment]
It seems that the package openssl-devel is not remanent over builds. What should be done to make it remanent?

**Comment by FeodorFitsner** [comment]
What do you mean by that?

**Comment by zosrothko** [comment]
Below the steps I have done
1/ first build: download & instal openssl-devel using setup-x86, found openss/crypto.h
2/ second build with the download of openssl removed and gcc did not find the openssl/crypto.h

So my understanding is that the openssl package isnot remanent over builds...

**Comment by FeodorFitsner** [comment]
I see. That's correct behavior, AppVeyor does not preserve worker state between builds, because it provisions a completely new VM for every build. You should keep that line installing custom libraries in project config.

**Comment by zosrothko** [comment]
I understand your point, but I am trying to reduce the overall time of the CI which already takes 3h45 without cygwin jobs...Moreover, I need all those packages
  - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P mysqlclient-devel -P libsqlite3-devel 

Also, the build will have to download the same set of package for cygwin64...

Thus, I come back to my inital remark. is there a way to make those packages permanent?

**Comment by FeodorFitsner** [comment]
Wow, 3:45 is pretty long. Do you have multiple build jobs? What account/project is that? Installing those additional cygwin packages shouldn't take very long - on my experience it was like a minute-two.

**Comment by zosrothko** [comment]
Look at this job https://ci.appveyor.com/project/zosrothko/poco/build/build%20CygwinOnAppVeyor-266 which takes 4h28 mn... (Moreover, the VS2015 matrix is not build since some jobs are longer than one hour which make the overall build failed)
