### ISSUE TITLE
Alternative options to skip a build

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#7]
More details:
http://help.appveyor.com/discussions/questions/499-alternative-options-to-skip-a-build

**Comment by danilaml** [comment]
Is it doable to skip CI when only certain files are modified, e.g. readme?

**Comment by FeodorFitsner** [comment]
Nope, currently it's impossible to skip based on file.

**Comment by danilaml** [comment]
Thanks. Is this planned though? Or it's too hard to implement?

**Comment by FeodorFitsner** [comment]
You can just add `[skip ci]` to the commit message after updating readme.

**Comment by danilaml** [comment]
@FeodorFitsner I'd like that to be done automatically, so anyone contributing won't trigger ci where it's not necessary.
