### ISSUE TITLE
MinGW 4.9.3-1

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#702]

**Comment by jasonwilliams200OK** [comment]
Any ETA on this? Its 2016 and we still don't get std::mutex and std::thread with MinGW on AppVeyor with pre-installed mingw..

**Comment by jasonwilliams200OK** [comment]
I take it back, configured it using `MSYS Makefiles` generator and it worked! Earlier I was using `MinGW Makefiles` generator which complains on `std::<anything-c++11>` even with `-c++11` switch. Still think it can be documented somewhere that using `MinGW Makefile` first ignores `-c++11` flag and hence compiler throws errors on cpp11 features usage, second require you to remove sh.exe from the PATH, i.e. this issue: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe. With `MSYS Makefiels` none of the issues exist.

My working appveyor.yml: https://github.com/WebAssembly/binaryen/blob/6e346ab/appveyor.yml

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
