### ISSUE TITLE
Cannot install Node in custom PS script

### ISSUE THREAD

**Issue by felixfbecker** [appveyor/ci#704]
I have an [appveyor.yml](https://github.com/felixfbecker/vscode-php-debug/blob/45514e4aa67f4f0d4a9c1ac4c112c5638a74c3ce/appveyor.yml) that executes [a custom powershell install script](https://github.com/felixfbecker/vscode-php-debug/blob/45514e4aa67f4f0d4a9c1ac4c112c5638a74c3ce/appveyor-install.ps1#L26), that installs Node 4.1.1. `$ErrorActionPreference` is set to `Stop` to abort on a failed script. Everything works fine, but the Node installation fails with

```
Uninstalling node 0.12.7 (x86)... 
Installing node 4.1.1 (x64)... 
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation completed successfully.
```

[Build](https://ci.appveyor.com/project/felixfbecker/vscode-php-debug/build/1.0.4/job/8koua98yymtljdld)

**Comment by FeodorFitsner** [comment]
Try removing `$ErrorActionPreference = "Stop"` and see what's happening.

**Comment by felixfbecker** [comment]
It is working now, but that of course makes the script not abort on errors...
I don't think this should happen. As you can see the error message is actually "The operation completed successfully"...

**Comment by FeodorFitsner** [comment]
Where does that message come from - install-product cmdlet?

**Comment by felixfbecker** [comment]
Yeah, it normally prints that when it finished. But when $ErrorActionPreference is set to Stop, it is somehow interpreted as an error message

**Comment by FeodorFitsner** [comment]
Will take a look what might be wrong with that.

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.

**Comment by felixfbecker** [comment]
Not sure if there is any activity I can provide. Did you take a look at what could cause this inside `Install-Product`?

**Comment by OwenMcDonnell** [comment]
Apologies for closing this issue if you are still facing it. We are trying to get the number of issues down to a manageable amount.
Due to interactions between custom powershell host and `Install-Product`, probably the best workaround at this point, if you want to keep `$ErrorActionPreference = "Stop"`, is to call `Install-Product` with cmd like this:
```yml
cmd /c powershell Install-Product node $env:NODE_VERSION
```
