### ISSUE TITLE
Self-hosted GitLab support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#711]

**Comment by olafleur** [comment]
What would be needed to support this?

Is it relatively similar to Gitlab.com repos?

**Comment by FeodorFitsner** [comment]
Yes, presumably GitLab on-prem API should be 100% compatible with hosted one. We'll add support for GitLab on-prem by AppVeyor Enterprise release.

**Comment by bgamari** [comment]
Has there been any progress on this? We are an open-source project currently using Appveyor for CI and considering switching to self-hosted GitLab. It would be nice to have a good story for integrating the two.

**Comment by IlyaFinkelshteyn** [comment]
@bgamari Oh, it is actually implemented (including Merge requests). Sorry, forgot to close the issue.

**Comment by bgamari** [comment]
Perhaps, but the documentation does leave something to be desired. In particular a note describing what "GitLab URL" is supposed to be set to would quite helpful. Is this the base URL of the instance?

**Comment by IlyaFinkelshteyn** [comment]
Yes, it is. I admit that we are behind on documentation, but this kind of experience should not require a documentation. We need to add a tool tip to `Authorize access to GitLab CE or EE` dialog. Anyways, were you able to make it work?

**Comment by bgamari** [comment]
Yep, I was indeed able to make it work. That being said, it would be nice if an error message were given when a certificate errors are encountered (I had forgotten my GitLab instance was still deployed with a development certificate); it currently just spins for a few seconds and then does nothing else.
