### ISSUE TITLE
b2 is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by jakwings** [appveyor/ci#713]
https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%201

When I am compiling boost, the b2.exe is not recognized. The batch file is here:
https://github.com/jakwings/librime/blob/41c80e1b6d2e66e0b414f647e6027b242829c148/appveyor.bat#L18

I did not meet this problem before. Maybe an update of the platform causes this bug?

**Comment by FeodorFitsner** [comment]
Boost libs are identical across all environments. I don't see `b2.bat` or `b2.cmd` in `C:\Libraries\boost_1_59_0` directory, but `bootstrap.bat` is there. Should `b2` appear after calling `bootstrap.bat`?

**Comment by jakwings** [comment]
Yes, according to the boost document here: http://www.boost.org/doc/libs/1_59_0/more/getting_started/windows.html#simplified-build-from-source

I checked the directory, don't know why it cd into the cloned project. I also changed `pushd` to use `cd <absolute path>` to avoid `bootstrap.bat` mistakenly calling `popd`, but that doesn't work. Also, it skipped [another command block in the same batch file](https://github.com/jakwings/librime/blob/f4f811c0b9363d95a1c87dfa55ba0ca5147e3cc9/appveyor.bat#L25-L31).

https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%204
https://github.com/jakwings/librime/blob/f4f811c0b9363d95a1c87dfa55ba0ca5147e3cc9/appveyor.bat#L16-L22

**Comment by FeodorFitsner** [comment]
It wasn't built from sources, but pre-built binaries were installed from here: https://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/

**Comment by jakwings** [comment]
Actually, this does not seem to be a problem of boost, because I can mandatorily `cd` back into the boost folder and run `b2` successfully. However, another `if` block is still skipped.

https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%205

I will create another simple test to see if it is a universal problem.

**Comment by FeodorFitsner** [comment]
what `if` block do you mean?

**Comment by jakwings** [comment]
This file: https://github.com/jakwings/librime/blob/1b8daade0e907eb4828d7c9b90b8f2319db86a02/appveyor.bat#L25-L31

Two `if` blocks on line 14 and 25 have the same condition, but line 25 has no effect.

**Comment by jakwings** [comment]
I've setup a simple repository to illustrate some problems about running a batch file. Please see the build history of test 1-2:
https://ci.appveyor.com/project/jakwings/appveyor/history

Test 1: put all build commands in `appveyor.yml` (b2 run successfully)
Test 2: put all build commands in `appveyor.bat` (b2 was not run, no error)

**Comment by FeodorFitsner** [comment]
Prefix commands with `call`: https://github.com/jakwings/appveyor/pull/1
When you call batch within batch the next command it not executing: http://stackoverflow.com/questions/13276109/batch-file-doesnt-run-the-next-command-after-gem-install

**Comment by jakwings** [comment]
That's exactly the main cause. Now all problems solved. Thank you very much!

**Comment by AnkitaS7** [comment]
I'm facing the same problem
![screenshot 101](https://cloud.githubusercontent.com/assets/26872230/24753161/a1782df8-1aee-11e7-83de-7347b4a16818.png)

**Comment by Halal-Dev** [comment]
Im still facing this too
