### ISSUE TITLE
Add TESTSIGNING Boot Configuration Option

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#715]
Hi,

Could it be possible to have the TESTSIGNING boot option enabled by default or in another special instance ?
This option is mendatory for installing selfsigned driver. Our project Dokany (https://github.com/dokan-dev/dokany) need it for running teste suite on appveyor.

Appveyor user cannot enable himself this option because it need a reboot to be activated.
```
Bcdedit.exe -set TESTSIGNING ON
```
Info: https://msdn.microsoft.com/en-us/library/windows/hardware/ff553484
https://github.com/Microsoft/Windows-driver-samples/blob/master/video/KMDOD/README.md

Thanks in advance and great work !

**Comment by FeodorFitsner** [comment]
AppVeyor supports restarting build workers. Just add the following PS commands to your build configuration:

```
install:
- Bcdedit.exe -set TESTSIGNING ON
- ps: Start-Sleep -s 5
- ps: Restart-Computer
```

**Comment by Liryna** [comment]
Hi @FeodorFitsner ,

I didn't know it was possible ! Yes it would fit my need !

But I made a test and I have an error unfortunately at the call of Restart-Computer:
```
Object reference not set to an instance of an object.
```
https://ci.appveyor.com/project/Liryna/dokany/build/1.0.0-10
https://github.com/Liryna/dokany/blob/master/appveyor.yml#L49

**Comment by FeodorFitsner** [comment]
Will take a look. Looks like a bug with restart and cache. Disable cache for now.

**Comment by Liryna** [comment]
Ok I have disable cache for now.

It seems that it reboot but the build does not resume after it :cry: 

https://ci.appveyor.com/project/Liryna/dokany/build/1.0.0-11

**Comment by FeodorFitsner** [comment]
OK, swap `start-sleep` and `restart-computer`:

```
    - ps: Restart-Computer -Force 
    - ps: Start-Sleep -s 10
```

**Comment by Liryna** [comment]
It work perfect ! Thank you @FeodorFitsner for the help and the great work :+1:
