### ISSUE TITLE
Cygwin install on Visual Studio 2015 images not working properly

### ISSUE THREAD

**Issue by Andne** [appveyor/ci#718]
We've seen an interesting behavior occur once the default image was changed to VS2015.  A cygwin autotools build started failing and hasn't been working since.  I've been able to get it working again by changing the os/image setting to use Visual Studio 2013 instead.

Here's a build that ran the morning of the default image switch (guessing before the switch occurred):
https://ci.appveyor.com/project/basvodde/cpputest/build/3.7.0-ci702/job/2ytmx0j9qmaf8lw3

Here's a build that ran the evening of the default image switch (guessing after the switch occurred):
https://ci.appveyor.com/project/basvodde/cpputest/build/3.7.0-ci703/job/r4um7x8emtgbesys

Some more investigation on my part leads me to think that the error was that autoreconf was getting SIGTERM for some reason.  It behaved better if I ran cygwin setup again and passed the upgrade parameter in, but then programs would randomly disappear from the path during execution (halfway through the build, g++ could no longer be found).  Removing the cygwin setup and using the Visual Studio 2013 image is the only solution that appears to have fully worked.

Could there be something bad in the cygwin install on the VS2015 image?  Or maybe another difference that interferes with cygwin usage?  I tried running cygwin with only it's own path which fixed autoreconf but caused other issues as well.

**Comment by FeodorFitsner** [comment]
That switch occured on March 18th was applicable to customers running on Pro Hyper-V based environment. OSS accounts/projects were left intact. I checked logs - both 702 and 703 builds ran on `Visual Studio 2015` image.

Btw, we are going to deploy new images today/tomorrow with `C:\cygwin` re-installed, if that matters.

**Comment by Andne** [comment]
Huh, well that's just weird then.  If both ran on the Visual Studio 2015 image, then why did one start failing?  Well, hopefully a reinstall corrects it then I guess.  Kind of sounds like something corrupted the 2015 image maybe?

Oh, now I found the problem, setup-x86.exe returns immediately, not when the command has finished running...  So my build was trying to use cygwin while I was also modifying the cygwin install.
