### ISSUE TITLE
GitHub Pull Request notifications to put commit message

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#724]
Per discussion here: https://github.com/appveyor/ci/issues/690#issuecomment-203838918

**Comment by Rondom** [comment]
Hope it is okay to ask here: Are there any plans to implement this?

**Comment by Rondom** [comment]
I this implemented or a won't-fix?

**Comment by FeodorFitsner** [comment]
It's won't fix for now, sorry. If there is more interest on this feature we might re-open it in the future. We'd like to bring current issues list to some manageable size.
