### ISSUE TITLE
Build version X.X.X already existed and a random string was appended to its version to avoid collision. Update next build number or change version format.

### ISSUE THREAD

**Issue by jaumard** [appveyor/ci#730]
Why when a PR is synchronize from master the build was in error with : 
`Build version X.X.X already existed and a random string was appended to its version to avoid collision. Update next build number or change version format.`

A user synchronize his PR and all was in error. 
Here is the project page https://ci.appveyor.com/project/tjwebb/trails/history

Normally AppVeyor have to increment the version number right ?

**Comment by FeodorFitsner** [comment]
Looks like build number counter was restarted for that project. Those versions indeed exist on history page. Open General tab of project settings and set next build number to 8.

**Comment by tjwebb** [comment]
I didn't restart the build number counter. Either way, I don't know why this should cause the build to fail.

**Comment by sebright** [comment]
I also saw this error message, and I didn't reset the build number: https://ci.appveyor.com/project/instrumentationjavateam/instrumentation-java/build/1.0.7-dup-7hhip8o3

The history page shows both `1.0.7` and `1.0.7-dup-7hhip8o3`.

**Comment by IlyaFinkelshteyn** [comment]
What could happen that UI page with next build number (Settings > General) remains open while build number changed. Then this `Save` was pressed on that UI page (for some another reason), which effectively reset build number.

**Comment by thisismydesign** [comment]
Same here. Didn't update the build number, only changed env var setting and triggered manual re-runs. This issue should be re-opened and addressed properly.

**Comment by HarelM** [comment]
I just encountered this issue too:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/40076867
I changed a file in github which triggered a build and it failed with this error message.
The change was a file rename and nothing else, if this help narrowing down the root cause.
The appveyor settings are not opened or edited anywhere so this seems like a glitch somewhere in the backend server...
