### ISSUE TITLE
Ruby 2.3.0

### ISSUE THREAD

**Issue by deivid-rodriguez** [appveyor/ci#734]
Hi @FeodorFitsner !

Ruby installers are now available for latest ruby 2.3.0! Could we get it in Appveyor?

Thanks a lot!

**Comment by FeodorFitsner** [comment]
Installation paths:

Ruby 2.3 x86: `C:\Ruby23`
Ruby 2.3 x64: `C:\Ruby23-x64`

**Comment by deivid-rodriguez** [comment]
@FeodorFitsner Thanks! I just tried this but Ruby version doesn't seem to be selected properly. See here: https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/483/job/paejghc675kku55r

**Comment by FeodorFitsner** [comment]
It's not yet deployed, sorry. That was just a comment during the process.

**Comment by deivid-rodriguez** [comment]
Aaaah ok, my bad!!

**Comment by jacebrowning** [comment]
Which images should this be available in? I don't see it listed here: https://www.appveyor.com/docs/installed-software#ruby

and I'm still seeing:

```
set PATH=C:\Ruby23;%PATH%
ruby --version
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
```

**Comment by jacebrowning** [comment]
My bad. I had to add `C:\Ruby23\bin` to the PATH.

It would still be great to get those docs updated. 😉
