### ISSUE TITLE
Automatic nuget publishing different for Visual Studio 2015 from Visual Studio 2013 worker image

### ISSUE THREAD

**Issue by matthewrwilton** [appveyor/ci#739]
Hi

We have some projects that were automatically publishing nuget packages with the Visual Studio 2013 worker image. When we upgraded to Visual Studio 2015 they stopped publishing automatically. I looked into it and the cause was that our .nuspec files were named differently to our .csproj files. Looking at this [question from Jul 2015](http://help.appveyor.com/discussions/questions/1438-not-sure-how-to-publish-to-the-official-nuget-server), the naming seemed to be a requirement and was part of the documentation. 

It's no longer part of the documentation, so I am not sure if this is a regression with the new worker image. If it's not, I can submit a pull request for a documentation update.

Cheers

**Comment by FeodorFitsner** [comment]
Right, currently `.nuspec` should have the same name as `.csproj` (`.vbproj`) file. There was a fix regarding that functionality: https://github.com/appveyor/ci/issues/707

Yes, please feel free to submit a PR to documentation - it should reflect that change. Thank you!
