### ISSUE TITLE
NuGet 3.4.2-rc command-line for Visual Studio 2015 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#745]
Update script:

```posh
    if(-not (Test-Path 'C:\Program Files (x86)\MSBuild\14.0\Bin')) { Write-Host "NuGet 3.4.2-rc installation skipped"; return }
    $nugetDir = 'C:\Tools\NuGet'
    if(Test-Path 'C:\Tools\NuGet3') {
        $nugetDir = 'C:\Tools\NuGet3'
    }

    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.4.2-rc/nuget.exe', "$nugetDir\NuGet.exe")
    Write-Host "NuGet 3.4.2-rc installed"
```

**Comment by MikhailTymchukDX** [comment]
Hello,

I noticed today, that our project is failing to build: https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/63
However, another project that uses `nuget restore` command is working ok: https://ci.appveyor.com/project/MikhailTymchukDX/appveyortest/build/1.0.90

The main difference is that the former project caches NuGet packages: https://github.com/DevExpress/AjaxControlToolkit/blob/master/appveyor.yml

I worked around it defining Visual Studio 2013 worker image.

However, I think the current issue is related to this bug.
Could you please look into it?

**Comment by FeodorFitsner** [comment]
Yes, looks like there is a regression in 3.4.2. It worked with 3.3: https://ci.appveyor.com/project/FeodorFitsner/ajaxcontroltoolkit/build/2

**Comment by FeodorFitsner** [comment]
Would you report to NuGet project or me? :smiley:

**Comment by MikhailTymchukDX** [comment]
No, I will not report to NuGet, because I can not describe the bug properly.
Moreover, we found it very convenient to keep Visual Studio 2013 image, because this ensures that we stay in stable build environment.
Thank you very much for your time!

**Comment by FeodorFitsner** [comment]
Well, "Visual Studio 2013" environment does not necessary mean it's stable. There is nuget 2.8.6 right now, but we'd need to deploy a newer version if they bump to 2.8.x or 2.9, or discontinue 2.x at all when 3.x is more or less stable.

**Comment by MikhailTymchukDX** [comment]
Ok, I will keep it in mind if things go wrong.
