### ISSUE TITLE
Not found DevKit for Ruby 2.x

### ISSUE THREAD

**Issue by cosmo0920** [appveyor/ci#747]
The discussion says:

> for all Ruby 2.x versions DevKit is installed in a single location C:\Ruby21\DevKit.

ref: http://help.appveyor.com/discussions/problems/2504-what-is-the-right-way-to-include-the-ruby-devkit

But I got following error:

```log
ls "%devkit%"
ls: cannot access C:\Ruby21-x64\DevKit: No such file or directory
```

ref: https://ci.appveyor.com/project/cosmo0920/fluentd/build/70/job/bcjqvblpe7vm0v0v#L12

Above discussion's information is old for now?

Regards.

**Comment by FeodorFitsner** [comment]
It's in `C:\Ruby23-x64\DevKit` now.

**Comment by cosmo0920** [comment]
Wow, thanks for the quick response!
I'll try to verify it.

**Comment by cosmo0920** [comment]
I've confirmed that I can use `C:\Ruby23-x64\DevKit` for Ruby 2.1 and 2.2 (32bit/64bit) in AppVeyor.
