### ISSUE TITLE
Artifacts page uses wrong title for Name

### ISSUE THREAD

**Issue by codethug** [appveyor/ci#749]
On the Artifacts Page, when I define a new artifact, I give it a name.  This should be the Artifact Name.  However, the UI shows it as 'Deployment Name'.

![image](https://cloud.githubusercontent.com/assets/1145092/14497230/2c803526-0164-11e6-8e4f-a12193a58f75.png)

It would be helpful to change this so that it shows 'Artifact Name' instead of 'Deployment Name'

**Comment by FeodorFitsner** [comment]
Good point. Sounds better than "Deployment name". There are many places in documentation though referring it as "Deployment name" - will take a look.

**Comment by FeodorFitsner** [comment]
We are slowly changing docs to have "Deployment name" everywhere which is semantically more correct.

**Comment by khyveasna** [comment]
#2725

**Comment by khyveasna** [comment]
Idea
