### ISSUE TITLE
Visual Studio "15" Preview

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#753]
A new "Visual Studio "15" Preview" image with only basic stuff like:
- Git
- Mercurial
- ...
- Ruby
- Node.js
- Python
- Active Perl

**Comment by mosra** [comment]
I'm all for this if it would result in a speedup of the builds. I'm using only the C++ compiler and Windows Store/Phone SDK (plus CMake&Ninja) and the builds seem to be really slow compared to what I remember on the default `os` image.

**Comment by madskristensen** [comment]
It would be **really** nice to have the VS "15" SDK as well so we can build VS extensions for VS "15"

**Comment by FeodorFitsner** [comment]
We'll deploy VS "15" when it reaches RC, or at least Beta state. Does it make sense?

**Comment by madskristensen** [comment]
Yes it does 👍
