### ISSUE TITLE
Appveyor only use default branch

### ISSUE THREAD

**Issue by malublu** [appveyor/ci#754]
Simple question:
Why appveyor not build the dev branch:
https://github.com/engor/Jentos_IDE/blob/master/appveyor.yml

Thank you for your help.

**Comment by FeodorFitsner** [comment]
Can you drop a link to AppVeyor build please?

**Comment by malublu** [comment]
Here: https://ci.appveyor.com/project/malublu/jentos-ide

**Comment by FeodorFitsner** [comment]
How did you start that build: by pushing to repo or by pressing "New build" button?

**Comment by malublu** [comment]
Both. After i push some changes on the dev branch no building start on appveyor.
I delete and recreate appveyor project.
I alos try to press the new build button.
Only master would build.

**Comment by FeodorFitsner** [comment]
Can you check "Recent deliveries" for AppVeyor webhook on GitHub repo settings?

**Comment by malublu** [comment]
I can't check it because i'm the second developer of the project.
But i create on my own project appveyor, it works.
I check any stuff tomorrow again.
I push laos some code to check it again.
