### ISSUE TITLE
Push-AppveyorArtifact cmdlet hangs if required $path parameter is missing

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#759]
Should throw instead.
Check other cmdlets too.

**Comment by vors** [comment]
There is support for thatiIn PowerShell engine.
Custom hosts need to declare themselves as non-interactive. Then PS would not prompt and would throw.

You can try it out:
```powershell
> powershell -NonInteractive -Command "Get-Credential"
```

vs

```
powershell -Command "Get-Credential"
```

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.
