### ISSUE TITLE
Install Qt Script for Qt 5.6

### ISSUE THREAD

**Issue by TheOneRing** [appveyor/ci#760]
Hi thanks for adding Qt5.6 in https://github.com/appveyor/ci/issues/698
For the quassel CI I'd need qtscript which is part of the add-on modules so it would be great if you could install them too.
See https://github.com/appveyor/ci/issues/334 for Qt5.5.

Thanks!

**Comment by FeodorFitsner** [comment]
OK, will add it during the next environment update window. I saw it was deprecated and thus unnecessary anymore :)

**Comment by TheOneRing** [comment]
Thanks, yes it is deprecated but its still used and as qt 5.6 is a lts release its probably staying alive for some time.

**Comment by mamontov-cpp** [comment]
I am very sorry, but QtScript is inavailable for Qt 5.9.1/winrt_x86_msvc2017 . Is there somehow it could be installed?
