### ISSUE TITLE
Missing DLL freezes build process

### ISSUE THREAD

**Issue by Malvineous** [appveyor/ci#766]
If there is a DLL missing, then when you try to run an .EXE that requires the missing DLL, the [build process freezes](https://ci.appveyor.com/project/Malvineous/libgamecommon/build/1.0.26) until after one hour the process terminates.

I think what is happening is that running the .EXE results in a popup message complaining about the missing DLL file, and waits for you to click OK - which you can't.

When I run the same thing through Visual Studio, it does not pop up with a MessageBox about the missing DLL, and instead reports that the .EXE file returned an error code (and it then fails the build process.)

Somehow Visual Studio is able to, when running programs as part of the build, tell them that there is no UI available so they don't throw up message boxes or anything.

Could this feature be added to Appveyor, so that any issues like this will cause the build to fail instead of freezing for one hour?

**Comment by FeodorFitsner** [comment]
I will try something and let you know if that worked.

**Comment by Malvineous** [comment]
Were you able to solve this one in the end?

**Comment by FeodorFitsner** [comment]
Yeah, it shouldn't be freezing now.
