### ISSUE TITLE
AzureWebJob deployment occasionally fails with "A task was canceled"

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#769]
Discussion: http://help.appveyor.com/discussions/problems/4551-azurewebjob-deployment-occasionally-fails-with-a-task-was-canceled

**Comment by jamesdixon** [comment]
@FeodorFitsner was wondering when this fix might be released? Just ran into this issue as well.

Thanks!

**Comment by FeodorFitsner** [comment]
Will updates build worker images tomorrow.
