### ISSUE TITLE
Java 6 update 45

### ISSUE THREAD

**Issue by tolbertam** [appveyor/ci#772]
One of the libraries we build and test using appveyor supports JDK 6-8.  We'd like to be sure our tests run well on windows for JDK6.  I see that java 7 and java 8 are installed via [Build Worker installed software](http://www.appveyor.com/docs/installed-software#java) but not java 6 understandably since it has been EOL'd.

Is there any possibility we could get Java 6u45 JDK installed (both x86 and x64 variants preferably) on the Build workers?   Alternatively we could install it as part of the build process but would prefer not to go that route.

**Comment by FeodorFitsner** [comment]
How long does it take to install it with script during the build?

**Comment by FeodorFitsner** [comment]
Will deploy Java 6 on build workers this week.

**Comment by tolbertam** [comment]
{quote}
How long does it take to install it with script during the build?
{quote}

I'm unsure at the moment.   I think i'd be able to pull down an archived zip file somewhere and extract it, and then cache it so it could be used for subsequent builds, but I think the archive will be fairly large (at least 60mb) so that may not work.

{quote}
Will deploy Java 6 on build workers this week.
{quote}

That would be excellent, thanks!

**Comment by tolbertam** [comment]
Working great, thanks!
