### ISSUE TITLE
Azure WebJob Custom Deployment Directory

### ISSUE THREAD

**Issue by jamesdixon** [appveyor/ci#775]
Is is possible to deploy an Azure WebJob to a custom directory? From the documentation, it seems that the job gets published to either `app_data/jobs/continuous` or `app_data/jobs/triggered` dependending on whether a schedule is provided. 

The reason I'm asking for this ability is because I'm using the [WebJobs Scripthost](https://github.com/Azure/azure-webjobs-sdk-script) to allow me to take advantage of the WebJobs SDK through Node. It requires that the Script Host is setup as a continuous web job and then within that folder, you put your jobs that should be scripted against the WebJobs SDK. Therefore, the path I need to deploy to ends up looking like `app_data/jobs/continuous/ScriptHost/{jobName}`.

Thanks!
James

**Comment by FeodorFitsner** [comment]
I'm not sure if Kudu API for Web Jobs allows that: https://github.com/projectkudu/kudu/wiki/WebJobs-API

However, you can have this directory structure inside of your job zip, no?

**Comment by jamesdixon** [comment]
~ However, you can have this directory structure inside of your job zip, no?

You're completely right 👍  I'll close this.

**Comment by jamesdixon** [comment]
@FeodorFitsner as you suggested, I created the directory structure in my webjob, which should work. However, I ran into an issue: the `scripthost` directory that lives under `app_data/jobs/continuous` and contains binaries. When I run the build, the deployment fails with "Uploading "webjob.zip" to "scout-api-staging" website as continuous WebJob with name "email-notifications"...A task was canceled." To test, I tried deploying a job in another directory, and it worked properly. That said, I suspect the web job deployment attempts to delete the files beforehand, which causes a timeout and subsequently causes the job to fail. Do you see a way to resolve this?

Thanks!
James

**Comment by jamesdixon** [comment]
Seems like there isn't an option in the WebJobs API to prevent it from replacing the entire job.

**Comment by jamesdixon** [comment]
@FeodorFitsner not sure if there is an actual difference, but I ended up just deploying my webjob via standard webdeploy, which appears to work fine. Just wanted to bring it up in case anyone else runs into this issue.

**Comment by FeodorFitsner** [comment]
You mean deployed jobs as part of application's Web Deploy package?

**Comment by jamesdixon** [comment]
Essentially. I have them as separate repositories, but just using the web deploy method.
