### ISSUE TITLE
GitHub deploy should have option of creating a draft release and upgrading to release upon completely uploading all assets

### ISSUE THREAD

**Issue by paddie** [appveyor/ci#776]
Our build pipeline is constructed around a new release being created in Github and triggering a webhook.

The GitHub deployment can either create a _release_ or a draft. Only a full release triggers the webhook for a new release. The trouble we are having, is that when creating a release, the webhook is triggered prior to the assets being uploaded.

If the GitHub deploy had some way creating a draft release while it was uploading the assets, and then promoting the release to a release upon completion, that would be fantastic.

**Comment by FeodorFitsner** [comment]
You mean GitHub triggering webhook?

**Comment by paddie** [comment]
Aye, our deployments are listening to Github webhooks that are triggered when a non-draft release is triggered.

If the AppVeyor Github deploy could do a promotion of a draft-release to a full release upon uploading all the assets, it would solve all our problems.

**Comment by FeodorFitsner** [comment]
Well, that makes sense. Will take a look.

**Comment by paddie** [comment]
Does it make sense to actually make that the default behaviour when selecting draft=false?

**Comment by FeodorFitsner** [comment]
Looks like it does.

**Comment by paddie** [comment]
@FeodorFitsner hey! I just wanted to chime in and bump this one since it is something that is blocking us. Thanks a lot for looking at it!

**Comment by FeodorFitsner** [comment]
Yeah, it's implemented already. I'm going to deploy it early this week. Thanks for your patience!

**Comment by paddie** [comment]
Briliant! Thank you!

**Comment by paddie** [comment]
@FeodorFitsner I've signed up for notifications on this issue, so if you just close it when you release, we can give you quick feedback on it if you want.

**Comment by paddie** [comment]
Verified. This works for us now, thank you so much for moving on this one! 

❤️
