### ISSUE TITLE
PowerShell 5

### ISSUE THREAD

**Issue by Cobster** [appveyor/ci#778]
It would be great if the base virtual machines were running PowerShell 5.

**Comment by FeodorFitsner** [comment]
Great idea! We are going to "dogfood" PS 5 on open-source environment to see if there are any issues. Then it will be rolled out to the rest of build workers.

**Comment by Cobster** [comment]
Fantastic! PS5 has a lot of new features I'm excited to introduce to help streamline the build process.  Specifically Install-Module to suck down dependencies and the new Archive module for packaging build artifacts.
