### ISSUE TITLE
Increase time limit for MSYS2

### ISSUE THREAD

**Issue by renatosilva** [appveyor/ci#780]
Hi Feodor, can you please increase the time limit for the MSYS2 project?

* https://ci.appveyor.com/project/alexpux/mingw-packages
* https://ci.appveyor.com/project/alexpux/msys2-packages

MSYS2 uses AppVeyor for testing contributions to many packaged projects, but some of them may take longer to build. In these cases we are simply unable to verify whether the CI build was successful. Not sure about the value but GCC for example takes up to several hours to complete. How about one day?

**Comment by FeodorFitsner** [comment]
I've boosted CPU performance for `alexpux` account. Let me know how that worked.
