### ISSUE TITLE
7zip was removed?

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#785]
This broke builds on JuliaLang/julia. If it's still installed but not on the path any more we can fix it with an absolute path if we can find where it happens to be right now. Otherwise we'd have to add run time to every build to install it from chocolatey or similar.

**Comment by FeodorFitsner** [comment]
Nope, it's still in PATH. Where do you get this error?

**Comment by tkelman** [comment]
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.1092/job/ykdfn2qx5efedy2m
is msys2 overwriting the path in a login shell?

**Comment by FeodorFitsner** [comment]
We've been testing a new build worker image (not it's rolled bacl to a previous) with 7z and MSYS2 re-installed to the latest versions.

What would be a simplest script to test 7z with bash?

**Comment by FeodorFitsner** [comment]
Also, where do I check what `PATH` is being set by msys2 login shell?

**Comment by tkelman** [comment]
`echo $PATH` ?

**Comment by FeodorFitsner** [comment]
right, but where is it initialized when `C:\msys64\usr\bin\sh.exe` started?

**Comment by tkelman** [comment]
not sure I understand the question, there are a lot of places that might be setting the path. it may be the case that the old image happened to have msys2's copy of 7z installed and had been using that

**Comment by tkelman** [comment]
something like `C:\msys64\usr\bin\sh.exe -lc "echo $PATH; which -a 7z; 7z x testfile.7z"` should work as a test

**Comment by FeodorFitsner** [comment]
OK, there is no magic there: https://sourceforge.net/p/msys2/discussion/general/thread/dbe17030/?limit=25

Looks like it was in some recent change as `pacman -Syu --noconfirm` breaks default "inherit" behavior. I'm modifying msys2 installation script to set machine-wide `MSYS2_PATH_TYPE=inherit`

**Comment by tkelman** [comment]
Good find, that's a pretty huge change to make in default behavior. Add another to my list of technical disagreements about the way MSYS2 does things...
