### ISSUE TITLE
IIS is stopped on VM worker

### ISSUE THREAD

**Issue by MikhailTymchukDX** [appveyor/ci#786]
I try to deploy Web application to local IIS before Selenium testing.
The package is assembled with "Package Web Applications for Web Deploy" UI option and deployed with "Before tests script" PS script:
```
& "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:iisApp="$env:APPVEYOR_BUILD_FOLDER\AjaxControlToolkit.Jasmine" -dest:iisApp=`"Default Web Site/JasmineTests`"
```
This successfully creates application on IIS, but all application pools and Default Web Site is stopped by default:
![2](https://cloud.githubusercontent.com/assets/17080984/14988477/a7355bc2-115c-11e6-86b6-b197af14c8ce.png)
![1](https://cloud.githubusercontent.com/assets/17080984/14988476/a732d136-115c-11e6-9128-8154c8dc981f.png)

Is it intended and I have to start site and pool explicitly or I missed something when deploying IIS application?

**Comment by FeodorFitsner** [comment]
Yes, that's is intentionally - all "optional" services are stopped (set to Manual start) to minimize VM boot time.

You can start IIS either [declaratively](http://www.appveyor.com/docs/services-databases#internet-information-services) or with PS `Start-Service w3svc` or `net start w3svc` commands.
