### ISSUE TITLE
Give Golang 1.6 its Own Top Level Directory

### ISSUE THREAD

**Issue by boumenot** [appveyor/ci#791]
I like that there are top-level directories for each major version of Go as detailed in the [docs](https://www.appveyor.com/docs/installed-software#go).  But, there isn't one for 1.6 (latest).  The current image has Go in c:\go, but when this gets bumped to 1.7 a project automatically gets opt-ed in.  This may or may not be desirable.  Would it be possible to add a c:\go16 and c:\go16-x86, so projects can lock to this major/minor version.  If projects want latest released, they can just stick with c:\go.

**Comment by FeodorFitsner** [comment]
Instead of duplicating it in C:\go16 would symlinking work (install into C:\go16 and then do C:\go as symlink to it)? Are there any known issues with go and symlinks?

**Comment by boumenot** [comment]
I like that idea better.  I just tested this on some repositories that I have, and I did not see any issues with using a symlink. :+1: Granted, you're getting advice from me.
