### ISSUE TITLE
Add SCons to tools

### ISSUE THREAD

**Issue by techtonik** [appveyor/ci#792]
Hi.

Is it possible to add SCons 2.5.0 to
https://www.appveyor.com/docs/installed-software#tools ?

`pip install --egg scons` should be enough to make it work.

**Comment by FeodorFitsner** [comment]
It basically takes seconds to install! We'd like to keep Python installations as basic as possible. Besides there are [multiple versions of Python](http://www.appveyor.com/docs/installed-software#python) and all of them would need this package.

**Comment by techtonik** [comment]
@FeodorFitsner yes, but can you upgrade `pip` then to latest 8.x? Because it doesn't install smoothly with current pip 7.1.2 - https://github.com/GodotBuilder/godot-builds/pull/2

**Comment by FeodorFitsner** [comment]
I'd recommend updating pip during the build as well (we can't keep all dependencies "always fresh"):

    pip install --upgrade pip

**Comment by techtonik** [comment]
Understood. Still it looks like SCons and pip are still not compatible. My system has SCons wheel cached, so I thought that upgrading pip will help, but it appears that it doesn't.
