### ISSUE TITLE
Old 7zip version on free plan

### ISSUE THREAD

**Issue by yuyichao** [appveyor/ci#793]
Ref https://github.com/JuliaLang/julia/issues/16188#issuecomment-217245628 this seems to be causing julia build to fail on my AppVeyor account for the past few days.

Feel free to close if this is transient due to some on-going upgrade.

**Comment by FeodorFitsner** [comment]
Right, will update 7zip on OSS images today.

**Comment by FeodorFitsner** [comment]
7zip has been updated on OSS environment.

**Comment by yuyichao** [comment]
Thanks!
