### ISSUE TITLE
Unified YAML config for all kind of build services

### ISSUE THREAD

**Issue by XVilka** [appveyor/ci#799]
Currently there are bunch of the build services, each one require its own file with the configuration for various builds. I'm suggesting to use one YAML configuration file (if presented) - something like `.build.yml`, which will have corresponding sections for:
- [ ] Appveyor
- [ ] Travis CI https://github.com/travis-ci/travis-ci/issues/6032
- [ ] Jenkins
- [ ] etc

Also, supporting common configuration options between those sections would be a plus, to simplify the building configuration.

**Comment by IlyaFinkelshteyn** [comment]
This is way out of what AppVeyor team can do...
