### ISSUE TITLE
Linking to GitHub account fails

### ISSUE THREAD

**Issue by hassankhan** [appveyor/ci#800]
When I try and link my Github account, it fails with the following message:

`HTTP GET to https://api.github.com/user/teams?per_page=100&page=1 returned 404: Not Found`

**Comment by FeodorFitsner** [comment]
Thanks for reporting that! It's been fixed - will deploy an update tomorrow.

**Comment by FeodorFitsner** [comment]
It's been fixed and updated deployed.

**Comment by hassankhan** [comment]
Yep, working for me as well. Thanks!
