### ISSUE TITLE
Make public keys available for programmatic encryption

### ISSUE THREAD

**Issue by bmcorser** [appveyor/ci#803]
You offer almost the same encryption functionality as Travis CI, with the critical difference that I cannot access the public key for my repo and as such, the only way I can encrypt environment variables is "manually" through a web UI.

I assume you use a standard encryption scheme such as RSA (like Travis CI does) that will allow me to easily and _programmatically_ encrypt data for my builds -- if only I had access to my public key!

**Comment by FeodorFitsner** [comment]
You can use REST API to encrypt the data for appveyor.yml: http://help.appveyor.com/discussions/questions/1892-encryption-through-api

**Comment by bmcorser** [comment]
Indeed. However, it appears I must be authenticated to use the endpoint mentioned in the webpage you link to.

**Comment by bmcorser** [comment]
In any case, the endpoint you mention doesn't specifically address the subject of the issue, namely access to the public key.

**Comment by bmcorser** [comment]
But thanks for the quick response :metal:

**Comment by FeodorFitsner** [comment]
AppVeyor does use symmetric algorithm to encrypt appveyor.yml values, so there is no public key.

**Comment by bmcorser** [comment]
Hence the authentication requirement on that endpoint. Ok then.
