### ISSUE TITLE
Enable URL for HipChat server to be specified for notifications

### ISSUE THREAD

**Issue by tvanfosson** [appveyor/ci#804]
I would like to be able to send notifications to a HipChat room on our private HipChat server but there does not seem to be a way to specify the server URL in the notifications interface.

**Comment by FeodorFitsner** [comment]
It's duplicate of https://github.com/appveyor/ci/issues/65

**Comment by FeodorFitsner** [comment]
It's been deployed. There is a new "HipChat Server URL" setting on UI and `server_url` in appveyor.yml.

**Comment by tvanfosson** [comment]
Awesome. Thanks for the quick turn around.  I've got it set up and running.
