### ISSUE TITLE
Can't build Python 3.5 64 bit

### ISSUE THREAD

**Issue by giampaolo** [appveyor/ci#806]
Hello, I've been trying different configurations but so far I've never been able to compile psutil against Pyhon 3.5 64 (3.5 32 bit and all other Python versions are fine):
https://ci.appveyor.com/project/giampaolo/psutil/build/647
This is my conf:
https://github.com/giampaolo/psutil/blob/master/appveyor.yml
And here's the support file:
https://github.com/giampaolo/psutil/blob/master/.ci/appveyor/run_with_compiler.cmd
Any idea?

**Comment by FeodorFitsner** [comment]
Look if that project could be an example: https://ci.appveyor.com/project/pymssql/pymssql/build/3

**Comment by giampaolo** [comment]
That helped. Thanks a lot!
