### ISSUE TITLE
add locale configuration

### ISSUE THREAD

**Issue by yumetodo** [appveyor/ci#809]
I'm a Japanese user so that to compile .sln, 

``` powershell
Set-WinSystemLocale ja-JP
Restart-Computer
```

such script is required as init script.

However, restarting computer is a waste of time.

So, I propose to add locale configuration which used before start VM.

**Comment by FeodorFitsner** [comment]
Have you tried `Set-Culture` - it works without restarting: http://help.appveyor.com/discussions/problems/2491-period-instead-of-comma-fails-unit-test-in-appveyor-despite-ok-in-vs2012#comment_37386047

**Comment by yumetodo** [comment]
hmm...

https://ci.appveyor.com/project/yumetodo/dxlibex

``Set-Culture`` seem broken...

**Comment by FeodorFitsner** [comment]
We are closing this issue because it has been inactive for a long time.

**Comment by yumetodo** [comment]
@FeodorFitsner From last year, I'm not using appveyor because of this issue. This issue is fixed?
