### ISSUE TITLE
cURL usage as per the docs seems not working

### ISSUE THREAD

**Issue by akien-mga** [appveyor/ci#812]
Having download issues with the ``appveyor DownloadFile`` command (see https://github.com/OpenDungeons/OpenDungeons/pull/1188 for context), I tried to switch to cURL following the docs instructions: https://www.appveyor.com/docs/how-to/download-file#curl

I used the exact same syntax as in the docs (commit https://github.com/OpenDungeons/OpenDungeons/pull/1188/commits/39f05dc4a2dfe3cbb24ebb6caf59b2ee01791ca0), i.e.:
```
$file = "C:\od-deps-win32.7z"
$urlDeps = "http://download.tuxfamily.org/opendungeons/dependency/od-deps-win32.7z"
curl -fsSL -o $file $urlDeps
```

But the build fails with an error hinting that it might be using Invoke-WebRequest instead of cURL: https://ci.appveyor.com/project/hwoarangmy/opendungeons-crxx4/build/1.0.237/job/rfc6d6to4k8achrc

```
Invoke-WebRequest : Parameter cannot be processed because the parameter name 'o' is ambiguous. Possible matches include: -OutFile -OutVariable -OutBuffer.
At line:4 char:12
curl -fsSL -o $file $urlDeps
           ~~
    CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by FeodorFitsner** [comment]
In your case it's called as PowerShell and PS has its own alias for "curl". When running from PS prefix it with `cmd /c`:

    cmd /c curl ...

**Comment by akien-mga** [comment]
Thanks!
