### ISSUE TITLE
SFTP and newer openssh

### ISSUE THREAD

**Issue by maths22** [appveyor/ci#821]
Since changing servers, and therefore switching to a new openssh version, I see the following error on deployment: `Cannot connect SFTP server: An established connection was aborted by the software in your host machine.`
On the server logs, I see `fatal: mm_answer_moduli: bad parameters: 2048 2048 1024`

**Comment by FeodorFitsner** [comment]
How do you deploy?

**Comment by maths22** [comment]
I use SFTP with a password configured through an encrypted key.  This error also occurs, however, when I attempt to manually deploy an artifact.

**Comment by FeodorFitsner** [comment]
Will take a look if there is a newer FTP client library. Don't have a server with SFTP set to test.

**Comment by FeodorFitsner** [comment]
Well, looks like that [FTP library](https://sshnet.codeplex.com/) we use for SFTP is not updated any more :disappointed: 

I know some customers use [WinSCP](https://chocolatey.org/packages/winscp.portable) ([scripting manual](https://winscp.net/eng/docs/scripting)). Other customers use `scp.exe` or `sftp.exe` from MinGW package with SSH keys.

You can try those options.

**Comment by maths22** [comment]
Thank you.  I'll look into it.  I also will point you towards (this thread)[https://github.com/duplicati/duplicati/issues/1687], which points to (this issue)[https://sshnet.codeplex.com/workitem/1973] suggests that both latest beta (from 2014!) fix this issue.  I can, however, see why using beta versions of a library in a production environment might not be ideal.  That said, I might suggest an update to the documentation to address this issue.

**Comment by FeodorFitsner** [comment]
Thanks for the hint. I will update the library to the latest beta and deploy update this week.

**Comment by FeodorFitsner** [comment]
We've just deployed an update to AppVeyor with that updated FTP library. It should work from "Environments", but not yet from the build (build agents should be updated). Let me know how that worked.

**Comment by maths22** [comment]
That works!  Thank you for taking care of this.  Let me know once it makes its way onto the build agents.

**Comment by FeodorFitsner** [comment]
Will do. Thanks for the update!

-Feodor Fitsner, AppVeyor



On Sun, May 29, 2016 at 12:16 PM -0700, "Jacob Burroughs" <notifications@github.com<mailto:notifications@github.com>> wrote:


That works! Thank you for taking care of this. Let me know once it makes its way onto the build agents.

-
