### ISSUE TITLE
Branch commit status builds are not running for external collaborators

### ISSUE THREAD

**Issue by jacebrowning** [appveyor/ci#824]
The feature implemented in https://github.com/appveyor/ci/issues/384 does not seem to be working. All of my PRs from outside collaborators look like this:

<img width="784" alt="screen shot 2016-05-27 at 2 23 11 pm" src="https://cloud.githubusercontent.com/assets/939501/15617356/9557d4c6-2416-11e6-94b2-c7c98cda5266.png">

where the `continuous-integration/appveyor/branch` build never starts.

**Comment by FeodorFitsner** [comment]
Edit protected branches and disable `continuous-integration/appveyor/branch`

**Comment by jacebrowning** [comment]
Thanks! The name of that build must have changed since I enabled protection.
