### ISSUE TITLE
Haskell Stack support

### ISSUE THREAD

**Issue by hanjoosten** [appveyor/ci#825]
I am trying to [use appveyor on a haskell project](https://ci.appveyor.com/project/hanjoosten/ampersand/build/1.0.3), using [Stack](https://www.stackage.org/). I followed the instructions that [Noon van der Silk has written down in a blog](https://silky.github.io/posts/2016-01-05-build-windows-haskell-app-with-stack-and-appveyor.html) recently. However, because there is no support for Haskell yet, It takes too long for my project to finish within 60 minutes. 
There are several things that would be great as an enhancement to appveyor, so that projects like mine could be built:
 * Add support for Haskell
 * containerbased infrastructure, like on travis-ci, enables a very cool caching mechanism, so build times go down a lot.

Thanks a lot for this great infrastructure!

**Comment by FeodorFitsner** [comment]
Hi Han,

Thanks for trying out AppVeyor for running Haskell project!

What would that mean "supporting Haskell"? Do we need to install anything on build workers?

**Comment by hanjoosten** [comment]
Currently, the way Haskell projects build, is by using Stack. Stack takes care of having a proper compiler, takes care of the right versions of libraries etc. Pretty cool alltogether. However, to do so, stack fills a directory with quite a lot of stuff. Normally, it only builds it whenever it is not allready built. A perfect usecase for caching, I would say. The cache limit of appveyor is too small for medium sized haskell projects. The folks at stack have been [working with AppVeyor before, and decided to disable the cache alltogether](https://github.com/commercialhaskell/stack/commit/e1605b888953124737ecff1dae3c790fd2a537c6#comments). See also [this issue], where @borsboom comments that by disabling the cache, build times are very long. I know that travis-ci does not have this problem. Maybe it is as simple as relaxing the current cache limit for haskell projects? The nice guys at stack(@snoyberg)  might have even better ideas than I have on this

**Comment by hanjoosten** [comment]
@FeodorFitsner As you can see, this is a showstopper for us to use AppVeyor. Could there be anything done in lifting some restrictions on the building time, storage, without having to upgrade to a paid plan?

**Comment by FeodorFitsner** [comment]
I've boosted CPU performance for `hanjoosten` account. Let me know how it worked.

**Comment by hanjoosten** [comment]
This works great! Now an executable got built as it should be. Now I can continue to learn how to get this ampersand.exe automatically into a realease. Thanks!

**Comment by FeodorFitsner** [comment]
Sounds great!
