### ISSUE TITLE
npm: No compatible version found

### ISSUE THREAD

**Issue by mdreizin** [appveyor/ci#830]
https://ci.appveyor.com/project/mdreizin/webpack-config/build/101/job/u3aaxfqg1p0kme1h#L17

**Comment by FeodorFitsner** [comment]
is it AppVeyor-specific issue?

**Comment by mdreizin** [comment]
@FeodorFitsner Yes, it is. Required version of `babel-runtime` is already published to `npm`.

Please see https://www.npmjs.com/package/babel-runtime

**Comment by mdreizin** [comment]
The following build was successfully passed:

https://ci.appveyor.com/project/mdreizin/webpack-cluster/build/1/job/khlkw9ove7lkta58#L252

I have triggered a new build and I will wait for result.

**Comment by FeodorFitsner** [comment]
The difference between "bad" and "good" builds is that the former has cache restore line: https://ci.appveyor.com/project/mdreizin/webpack-config/build/101/job/u3aaxfqg1p0kme1h#L5

Looks like caching `npm-cache` can give you unpredictable behavior sometimes.

**Comment by mdreizin** [comment]
@FeodorFitsner I have found workaround:

Delete old one project and create a new one.

But it looks like that cache invalidation doesn't work well.

**Comment by FeodorFitsner** [comment]
can you drop a link to appveyor.yml please?

**Comment by mdreizin** [comment]
@FeodorFitsner https://github.com/mdreizin/webpack-config/blob/master/appveyor.yml

**Comment by FeodorFitsner** [comment]
Try adding `package.json` dependency to `%APPDATA%\npm-cache` as well?

**Comment by mdreizin** [comment]
@FeodorFitsner like this?

```yml
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache -> package.json'
```

**Comment by FeodorFitsner** [comment]
Yep

**Comment by mdreizin** [comment]
@FeodorFitsner Thanks again, now it works fine.
