### ISSUE TITLE
can't dynamically read version number from project

### ISSUE THREAD

**Issue by LER0ever** [appveyor/ci#833]
I think appveyor does not read sys variables when judging whether my version is same as the previous one, while travis does. 
**I have a VERSION file in the project root, in the file is 0.1.0.0003**
And in my appveyor.yml I use
```
- for /f  %%i  in (VERSION) do (set VERSION_NUMBER=%%i)
- echo %VERSION_NUMBER%
- FOR /f %%a IN ('WMIC OS GET LocalDateTime ^| FIND "."') DO SET DTS=%%a
- set TIMESTAMP=%DTS:~8,6%
version: Windows-g++-$(VERSION_NUMBER)-$(TIMESTAMP)
```
these command to generate a Version Number like **_0.1.0.0003-115619_**
But Appveyor seems to think that my version number is always the same！
It keeps telling me that "_Build version Windows-g++-- already existed and a random string was appended to its version to avoid collision. Update next build number or change version format._" 
**It's very likely that it does not read the env variable when judging the build number.**
So how can I do this using Appveyor?

**Comment by FeodorFitsner** [comment]
You should use Build Worker API to change build version in runtime: http://www.appveyor.com/docs/build-worker-api#update-build-details

Your example can look like:

```
- for /f  %%i  in (VERSION) do (set VERSION_NUMBER=%%i)
- echo %VERSION_NUMBER%
- FOR /f %%a IN ('WMIC OS GET LocalDateTime ^| FIND "."') DO SET DTS=%%a
- set TIMESTAMP=%DTS:~8,6%
- appveyor UpdateBuild -Version "Windows-g++-%VERSION_NUMBER%-%TIMESTAMP%"
```

Alternatively, you can use this PowerShell one-liner (make sure it runs during `install` phase when sources are fetched):

    install:
    - ps: Update-AppveyorBuild -Version "Windows-g++-$(Get-Content .\version)-$(get-date -f HHmmss)"

**Comment by LER0ever** [comment]
Thank you! I haven't noticed the Worker API, I guess it's properly getting my version number.
