### ISSUE TITLE
MikTeX

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#835]
Please, add MikTeX to images. Download time of this package is very large, but it is required for all TeX projects...

**Comment by FeodorFitsner** [comment]
Can you drop download link please?

**Comment by sergey-s-betke** [comment]
May be, install it from chokolatey?

    Import-Module `
        -Name PackageManagement `
    ;
    
    switch ( $env:PROCESSOR_ARCHITECTURE ) {
        'amd64' { $ArchPath = 'x64'; }
        'x86'   { $ArchPath = 'x86'; }
        default { Write-Error 'Unsupported processor architecture.'}
    };
    $ToPath = @();
    Install-Package `
        -Name 'miktex' `
        -MinimumVersion '2.9' `
        -Force `
    ;
    $MikTex = `
        Get-ChildItem `
            -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall `
        | ?{ $_.Name -like '*MiKTeX*' } `
        | Get-ItemPropertyValue `
            -Name InstallLocation `
    ;
    $MikTexBinPath = "$MikTex\miktex\bin\$ArchPath";
    Write-Verbose "MikTeX bin directory: $MikTexBinPath";
    $ToPath += $MikTexBinPath;

    Write-Information 'Preparing PATH environment variable...';
    if ($PSCmdLet.ShouldProcess('PATH', 'Установить переменную окружения')) {
        $Path = `
            ( `
                ( $env:Path -split ';' ) `
                + $ToPath `
                | Sort-Object -Unique `
            ) `
        ;
        Write-Verbose "Path variable: $Path";
        $env:Path = $Path -join ';';
        [System.Environment]::SetEnvironmentVariable( 'PATH', $env:Path, [System.EnvironmentVariableTarget]::User );
    };

**Comment by sergey-s-betke** [comment]
URL for download: http://www.miktex.org/download. But from chocolatey - it is simple...

**Comment by sergey-s-betke** [comment]
How I can test MikTeX in install script? `choco list MikTeX -localonly`?

**Comment by FeodorFitsner** [comment]
Installing miktex with Chocolatey took around 2,5 minutes: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.2179

I'd say it makes sense to run its installation as part of the build (for now).

**Comment by sergey-s-betke** [comment]
https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.7.0-appveyor.52.build.24,

[00:02:56] VERBOSE: GetChocolateyWebFile miktex => http://mirror.utexas.edu/ctan/systems/win32/miktex/setup/basic-miktex-x64.exe
[00:18:52] The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to download from URI 'http://mirror.utexas.edu/ctan/systems/win32/miktex/setup/basic-miktex-x64.exe' to ''.

It depends on the selected mirror of the ctan archive...

**Comment by sergey-s-betke** [comment]
Now MikTeX installed in 5-10 minutes. No problem.
