### ISSUE TITLE
OpenSSL Light 1.0.2h

### ISSUE THREAD

**Issue by un1versal** [appveyor/ci#841]
Both 32-bit and 64-bit: also idk why such components aren't (or dont seem t be) auto-updated to keep up with CVE fixes and vulnerability fixes 
https://www.openssl.org/news/vulnerabilities.html#y2016
I would have thought that generally speaking this would be a good thing.

Current OpenSSL version on build workers is 1.0.1**e** current release of OpenSSL version is 1.0.1**h**

Download: https://slproweb.com/products/Win32OpenSSL.html

**Comment by FeodorFitsner** [comment]
Thanks for pointing that out!

**Comment by un1versal** [comment]
@FeodorFitsner 

Please dont add light version, now it wont build
