### ISSUE TITLE
.NET Core 1.0 RTM

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#842]
Discussion: http://help.appveyor.com/discussions/kb/44-net-core-rtm-support

This is how to uninstall `Microsoft .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1`: http://stackoverflow.com/questions/37624775/how-do-i-uninstall-microsoft-net-core-1-0-0-rc2-vs-2015-tooling-preview-1

Uninstalling Microsoft ASP.NET 5 RC1: http://download.microsoft.com/download/1/8/0/18048EDD-9F45-479A-B208-6F7C91CF2ECC/AspNet5.ENU.RC1_Update1_KB3137909.exe

https://www.microsoft.com/en-us/download/details.aspx?id=49959

**Comment by nicpillinger** [comment]
hey @FeodorFitsner do you guys have a timeframe for the RTM of Core to be available on appveyor? I realise its only just out there but we have an RC2 app which we want on the RTM release asap. cheers

**Comment by FeodorFitsner** [comment]
It's going to be available today.

**Comment by nicpillinger** [comment]
@FeodorFitsner :+1: 
how do we get it?

**Comment by nicpillinger** [comment]
Ignore me, rebuild and its all working - nice work, thanks.
