### ISSUE TITLE
Qt 5.6.1-1

### ISSUE THREAD

**Issue by bjorn** [appveyor/ci#843]
Please update the Qt 5.6 packages to Qt 5.6.1, which was [just released](http://blog.qt.io/blog/2016/06/08/qt-5-6-1-released/).

This release fixes many issues, among which a crash fix affecting applications showing system file icons (which of course includes my application :)).

**Comment by uglide** [comment]
@FeodorFitsner Do you have any ETA for this?

**Comment by FeodorFitsner** [comment]
Will deploy updated images later today.

**Comment by uglide** [comment]
@FeodorFitsner thanks!

**Comment by FeodorFitsner** [comment]
Found last minute issue with git. Didn't make it today, but definitely will deliver this week.

**Comment by Dessa** [comment]
FYI: upstream respun to [5.6.1-1](https://blog.qt.io/blog/2016/06/22/qt-5-6-1-1-released/).
