### ISSUE TITLE
Support a different code page

### ISSUE THREAD

**Issue by yan12125** [appveyor/ci#846]
I'm working on pypa/virtualenv and got the following issue: neither CMD nor PowerShell can recognize Chinese characters in ```%PATH%``` unless the system code page can handle Chinese (936, 950, etc.) Could you provide an image/an appveyor.yml option for a different default locale than English? Thanks.

For details: pypa/virtualenv#927 and pypa/virtualenv#900.

**Comment by FeodorFitsner** [comment]
Is it possible to change/set that code page from command line?

**Comment by yan12125** [comment]
The only way as far as I know is: http://windows.microsoft.com/en-us/windows/change-system-locale#1TC=windows-7
Unfortunately this requires an reboot.

**Comment by FeodorFitsner** [comment]
System locale can be changed with [`Set-WinSystemLocale` cmdlet](https://technet.microsoft.com/en-us/library/hh852118.aspx) and computer restart is also supported during AppVeyor builds:

```
init:
- ps: Set-WinSystemLocale <your-required-locale>
- ps: Start-Sleep -s 5
- ps: Restart-Computer
```

**Comment by m-tmatma** [comment]
> System locale can be changed with Set-WinSystemLocale cmdlet and computer restart is also supported during AppVeyor builds:
> init:
> - ps: Set-WinSystemLocale <your-required-locale>
> - ps: Start-Sleep -s 5
> - ps: Restart-Computer

F.Y.I
see #2433, #2435
