### ISSUE TITLE
.appveyor.yml support

### ISSUE THREAD

**Issue by sheerun** [appveyor/ci#847]
Hey,

I'm maintainer of bower/bower project, we use appveyor for our CI test, great product!

When cloning bower repo, `appveyor.yml` receives little too much visibility. Would it be possible for Appveyor to support `.appveyor.yml` file as well? Just like `.travis.yml`

**Comment by FeodorFitsner** [comment]
Hi Adam,

You can configure a custom name for appveyor.yml on General tab of project settings.
