### ISSUE TITLE
Broken TypeScript build (duplicate identifiers) after upgrading to typescript@next

### ISSUE THREAD

**Issue by otbe** [appveyor/ci#849]
Hi,

Im observing some broken builds (duplicate identifiers) after upgrading to ```typescript@next``` (1.9.0-dev.20160612-1.0). I can't reproduce this on my own machine (VM) and an issue on [TypeScript](https://github.com/Microsoft/TypeScript/issues/9049#issuecomment-225117604) did not help either. 
Is there a potential problem with my appveyor setup or with appveyor itself?

Broken build: https://ci.appveyor.com/project/otbe/dwatch/build/0.4.72
Project (PR that causes broken builds): https://github.com/otbe/dwatch/tree/update-notification

Thankful for some hints :)

**Comment by FeodorFitsner** [comment]
I don't think it's AppVeyor environment. I'm getting errors while run it locally:

![image](https://cloud.githubusercontent.com/assets/5041459/15994024/1ddd1b74-30ad-11e6-8710-f26c013700f0.png)

I'm on Windows 10. Re-installed Node.js 6.2.1 x64, removed `%appdata%\npm-cache` then ran these commands:

```
git clone --branch=update-notification https://github.com/otbe/dwatch.git c:\projects\2\dwatch
cd c:\projects\2\dwatch
npm install
npm run test
```

**Comment by otbe** [comment]
@FeodorFitsner thanks for answering!
Please try the "update-notification" branch. This fixes typing errors from inversify and emock.

**Comment by FeodorFitsner** [comment]
I've been trying exactly that branch. Look at clone command above...or am l doing that wrong?

**Comment by otbe** [comment]
@FeodorFitsner yeah overlooked it :)
See my edited comment.

**Comment by FeodorFitsner** [comment]
I think it's wrong to assume if it works on Mac/Linux it *should* work on Windows. I also tried on a different non-OS environment with different build workers images and got same errors. What do you have installed on your VM? I might build mine in the meantime and try there (if that helps)?

**Comment by otbe** [comment]
@FeodorFitsner thanks for your help!
Im now able to reproduce this issue on my VM and this issue can be closed.
Tracked it down to a TypeScript bug on windows if used via LanguageService API.
See https://github.com/Microsoft/TypeScript/issues/9123 for more information.

**Comment by FeodorFitsner** [comment]
Thanks for the update!
