### ISSUE TITLE
Scheduled builds stopped running 2 weeks ago?

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#857]
I had daily scheduled builds set up for several low-traffic repositories where I wanted to check that the external services they rely on for installation don't introduce any issues (or if they do, I can track down when it started happening). The last one of these to trigger successfully was just over 2 weeks ago, see e.g. https://ci.appveyor.com/project/tkelman/glpk-jl/history. What happened?

**Comment by FeodorFitsner** [comment]
There was an [outage of Service Bus on June 5th](https://azure.microsoft.com/en-us/status/#history) and some scheduled jobs were affected. Just re-save project settings to start scheduled builds again.
