### ISSUE TITLE
Correct handling of carriage return (\r) in build log

### ISSUE THREAD

**Issue by Lemongrass3110** [appveyor/ci#858]
Appveyor seems to be unable to work with carriage returns.
I think the best way to show it to you is by example:
https://ci.appveyor.com/project/Lemongrass3110/rathena/build/master-20/job/u4603gnvxy9yji03#L895

From here our tool starts updating the same line over and over again, counting up and rewriting the line. On appveyor however it is all thrown into a single line, which makes it unreadable and creates a very very long build log.

If you need further input just let me know.

**Comment by FeodorFitsner** [comment]
Can you make a simple reproduce for that issue?

**Comment by Lemongrass3110** [comment]
You can easily try it by adding a powershell test script like this to your build:
```
Write-Host "First line`rSecond line"
```
This is intended to output "First line" then reset the cursor position to the beginning of the line and print "Second line" over it. So the absolute output you get should be "Second line".
You can try this on any local windows copy that supports powershell.

I could not find any command that supports this for windows batch files though.
But in C or Java for example you can just use `\r` to get to the same result.

I also found #798 which seems to be a similar issue, which might be a little harder to fix and does not include the normal carriage return character.

**Comment by FeodorFitsner** [comment]
So, how would you see `\r` reflected in a build log - similar to `\n`? For example, if the app outputs `line1\rline2` to a build log we'll be displaying:

    line1
    line2

**Comment by Lemongrass3110** [comment]
As you can see on the line I have linked you to everything is thrown into one line(you can see it on the line numbers).
For our project this means, that a few hundred lines are thrown into one line, which makes the output unreadable. We iterate over a few hundred files and load them and to show the progress without flooding the console window we use `\r` to rewrite the line all the time.
Travis seems to handle that correctly, here is what it should look like:
https://travis-ci.org/rathena/rathena/jobs/139340399#L1545

**Comment by FeodorFitsner** [comment]
OK, I see now, thanks. Will be working on a fix.

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by Lemongrass3110** [comment]
Works perfectly now - thanks for the fast fix!
