### ISSUE TITLE
Mingw-w64 

### ISSUE THREAD

**Issue by wbraswell** [appveyor/ci#861]
MinGW.org has been effectively replaced by Mingw-w64, and MinGW.org is permanently broken.

Specifically:

"...the MinGW.org implementation of include/math.h does have a bug in its inline implementation of hypotf (float, float); the bug is triggered when compiling C++, with the affected header included (as it is when cmath is included), and any compiler option which causes __STRICT_ANSI__ to become defined is specified..."

http://stackoverflow.com/questions/29450016/o1-2-3-with-std-c1y-11-98-if-cmath-is-included-im-getting-error-hypo

PLEASE PLEASE PLEASE replace the deprecated and broken MinGW.org with the up-to-date and fully-functional Mingw-w64.  Thanks!  :-)

Direct link to the installer: http://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win32%2FPersonal%2520Builds%2Fmingw-builds%2Finstaller%2F&ts=1467053226&use_mirror=tenet

Installed into:

    C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0

**Comment by FeodorFitsner** [comment]
Can you share installation instructions for it please?

**Comment by wbraswell** [comment]
@FeodorFitsner 
Okay I will get you some info shortly, thanks!

**Comment by wbraswell** [comment]
@FeodorFitsner 

There are a few different methods for installing Mingw-w64, I think it may be best to start trying using the Chocolatey package manager, it is using a slightly older version of Mingw-w64 but that should be okay:

https://chocolatey.org/packages/mingw

Secondly, there is the option of using the EXE installer:

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/

Lastly, there are a number of other installation mechanisms which will likely require a bit more manual effort:

http://mingw-w64.org/doku.php/download

(FYI, I am not personally a Windows user, I am working with my Windows programming partner to solve this issue.)

Does that help answer your question?

**Comment by FeodorFitsner** [comment]
Cool, thanks! I've got stuck on this dialog :smile: What options do people use the most?

![image](https://cloud.githubusercontent.com/assets/5041459/16253769/26668f62-37ee-11e6-8699-59b8505ecce4.png)

**Comment by wbraswell** [comment]
Version: Newest available (5.3.0 should be fine)
Arch: i686
Threads: posix
Exception: dwarf
Build Revision: not sure yet, 0 should work?  

I can check more on the Build Revision if 0 doesn't work...

**Comment by FeodorFitsner** [comment]
Do they have a public issues list? Just noticed a typo while installing it:

![image](https://cloud.githubusercontent.com/assets/5041459/16394800/e0e3667c-3c6b-11e6-9b08-c6f8a1fafa5d.png)

**Comment by wbraswell** [comment]
@FeodorFitsner :+1: 
Thanks so much for this fix!
RPerl is passing (relaxed) tests on AppVeyor, at long last!
https://ci.appveyor.com/project/wbraswell/rperl/build/1.0.306
