### ISSUE TITLE
CMake build fails from ps but works from cmd

### ISSUE THREAD

**Issue by jibsen** [appveyor/ci#868]
I am working on building [squash](https://github.com/quixdb/squash) with various versions of Clang on Windows. I ran into an issue with executing the build from powershell in the AppVeyor script. Using:

~~~.ps
if ($env:GENERATOR -eq "MinGW Makefiles") {
  mingw32-make VERBOSE=1
} else {
  cmake --build . --config $env:CONFIGURATION
}
~~~

the MinGW Makefiles [build fails](https://ci.appveyor.com/project/quixdb/squash/build/506) with the somewhat strange error message

> Command executed with exception:  generated.

If, on the other hand, I use the equivalent cmd script:

~~~.cmd
if "%GENERATOR%" == "MinGW Makefiles" ( mingw32-make VERBOSE=1 ) else ( cmake --build . --config %CONFIGURATION% )
~~~

the [build succeeds](https://ci.appveyor.com/project/quixdb/squash).

Is there some limit to how much output ps can handle from a command?

**Comment by FeodorFitsner** [comment]
This is because cmake writes some messages to StdErr which is treated as exception by PowerShell.

**Comment by jibsen** [comment]
Interesting. It's not CMake, but rather Clang that writes warnings to stderr. This is common practice, gcc does the same.

Does this mean you cannot run any tool that may emit a warning to stderr from a ps script?

**Comment by FeodorFitsner** [comment]
There are workarounds, of course.

For example, you can put PowerShell logic into separate `test.ps1` file and then call it from `appveyor.yml` as:

    - PowerShell .\test.ps1

**Comment by jibsen** [comment]
Okay, thanks for clearing this up.
