### ISSUE TITLE
Broken OpenSSL due to using light version since #841

### ISSUE THREAD

**Issue by un1versal** [appveyor/ci#870]
It doesnt have includes or library paths, you will receive many complaints this is the first one.

---
Win32 OpenSSL v1.0.2h Light 	2MB Installer 	Installs the most commonly used essentials of Win32 OpenSSL v1.0.2h (**Recommended for users by the creators of OpenSSL**). Note that this is a default build of OpenSSL and is subject to local and state laws. More information can be found in the legal agreement of the installation.

----

Win32 OpenSSL v1.0.2h 	16MB Installer 	Installs Win32 OpenSSL v1.0.2h (**Recommended for software developers by the creators of OpenSSL**). Note that this is a default build of OpenSSL and is subject to local and state laws. More information can be found in the legal agreement of the installation.

It will fail to build both 32-bit/64-bit
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
```

64-bit logs https://ci.appveyor.com/project/DarthGandalf/kvirc/build/0.0.0.0.1-branch-master-build-1823/job/862ithrwuuq32vae

32-bit logs https://ci.appveyor.com/project/DarthGandalf/kvirc/build/0.0.0.0.1-branch-master-build-1823/job/x4b2qyvqwlwmf9k4

Please use full version...

#841 was never about light, someone changed the title for that ticket.

**Comment by FeodorFitsner** [comment]
We are going to push another images update for .NET Core RTM, so we'll fix OpenSSL too.

**Comment by un1versal** [comment]
thx, any idea when?

**Comment by FeodorFitsner** [comment]
Tomorrow, hopefully.
