### ISSUE TITLE
Do not start two builds on feature branch

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#882]
The problem:

> When you push to a feature branch and there is an open PR for that branch then AppVeyor triggers two builds: one for the branch "push" and the second one for PR "synchronize".

Discussion: http://help.appveyor.com/discussions/questions/1700-pushing-a-feature-branch-schedules-two-builds

We can have another option on General tab of project settings, kind of `Do not build feature branch if open PR exists` (feel free to suggest a better, more clear name) which when enabled check if there are any opened PRs for push branch and if there any PRs build won't be started assuming there will be another build for PR(s).

There is an API for querying repository pull requests and filtering them by head branch: https://developer.github.com/v3/pulls/#list-pull-requests

Sample query:

    GET https://api.github.com/repos/appveyor/test-pr/pulls?state=open&head=appveyor:test1

**Comment by msarahan** [comment]
That sounds perfect.  Thanks for looking into this.  Looking forward to the fix.  If you need help testing, please let me know.

**Comment by markwalsh-liverpool** [comment]
Hello @FeodorFitsner, is this now possible I'm production?

**Comment by FeodorFitsner** [comment]
Yes, it can be configured either on UI ("General" tab of project settings - `Do not build feature branches with open Pull Requests`) or in appveyor.yml:

    skip_branch_with_pr: true

**Comment by markwalsh-liverpool** [comment]
Cool thanks.

**Comment by TomasVotruba** [comment]
Cool feature. So this disable PR branch?

> skip_branch_with_pr: true

How to actually disable master branch?

**Comment by FeodorFitsner** [comment]
Like this? https://www.appveyor.com/docs/branches/#white--and-blacklisting

**Comment by TomasVotruba** [comment]
Thank you for fast response! Will try and let you know.

I've seen it on Symfony repo:

https://github.com/symfony/symfony/pull/20281

![image](https://cloud.githubusercontent.com/assets/924196/19628185/44541c30-9958-11e6-891f-8208185496a9.png)

There is only `continuous-integration/appveyor/pr` 

---

But on my repo https://github.com/Symplify/Symplify/pull/12

![image](https://cloud.githubusercontent.com/assets/924196/19628206/b95a62b4-9958-11e6-96b6-688f52c0a4b4.png)

There is `/branch` one.

---

I have looked to [`appveyor.yml` of Symfony](https://github.com/symfony/symfony/blob/master/appveyor.yml) but didn't find any clue how to do that.

**Comment by sschuberth** [comment]
I'm having the same issue as @TomasVotruba: Despite `skip_branch_with_pr: true` being present in [appveyor.yml](https://github.com/heremaps/oss-review-toolkit/blob/master/appveyor.yml#L1), I continue to see *both* `continuous-integration/appveyor/branch` and `continuous-integration/appveyor/pr` builds in PRs, see e.g. https://github.com/heremaps/oss-review-toolkit/pull/303.

@FeodorFitsner, @IlyaFinkelshteyn, any idea why that is?

**Comment by IlyaFinkelshteyn** [comment]
@sschuberth I do not `ontinuous-integration/appveyor/branch` only `continuous-integration/appveyor/pr`... Can you please help me to understand the problem?
![2018-02-09_09h48_29](https://user-images.githubusercontent.com/3248386/36041793-87b5980a-0d7e-11e8-92c3-53596ce3d2a2.png)

**Comment by sschuberth** [comment]
@IlyaFinkelshteyn, for past PR it looks like it worked, but for still open PRs you'll see the `continuous-integration/appveyor/branch`: https://github.com/heremaps/oss-review-toolkit/pull/306

![image](https://user-images.githubusercontent.com/349154/36042866-9384e9ca-0dcd-11e8-9853-79e59f2da1dd.png)

**Comment by sschuberth** [comment]
FYI, I just found out why I was still seeing these bogus `continuous-integration/appveyor/branch` builds despite me having set `skip_branch_with_pr: true`:  I still had it included as a required status check in the branch protection settings.

**Comment by IlyaFinkelshteyn** [comment]
Ah, thanks a lot the update! I was trying to understand how it happen that we set those statuses and could not...

**Comment by pasqoo** [comment]
Is it possible to obtain the opposite behaviour?
Meaning: do not build the PR, but still build the branch, ignoring that there is a Pull Request attached to it.

**Comment by IlyaFinkelshteyn** [comment]
@pasqoo there is a checkbox called `Do not build on "Pull request" events` in General Setting tab.
