### ISSUE TITLE
Create "Visual Studio 2015 Update 2" image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#891]
* http://help.appveyor.com/discussions/problems/4906-new-msbuild-in-vs2015-update-3-impacting-node-gyp-native-compilation
* https://github.com/appveyor/ci/issues/890

**Comment by XhmikosR** [comment]
I assume you will add Update 3 too?

**Comment by bsipocz** [comment]
@XhmikosR - If you check the referenced issues you'll see that Update 3 is the current default, and we have some problems with it, thus the need for a more robust workaround.

**Comment by FeodorFitsner** [comment]
The purpose of this issue is collecting accounts affected by Visual Studio 2015 Update 3. We are going to release `Visual Studio 2015 Update 2` image to these selected accounts only, so if you need that image add a new comment here with a link to your project or the name of AppVeyor account.

**Comment by FeodorFitsner** [comment]
Looks like another case: https://github.com/appveyor/ci/issues/904

**Comment by XhmikosR** [comment]
I see. I suppose someone has already reported the issue to Microsoft?

**Comment by KevinMartin** [comment]
@FeodorFitsner it seems like one my projects is affected by this. It's linked to my GitHub account. Would you be able to add Update 2 image to that project please?

**Comment by FeodorFitsner** [comment]
Added.

**Comment by inducer** [comment]
Could you please add access  to the image for the `conda-forge` account as well?

It's required to get this to build: https://github.com/conda-forge/pyopencl-feedstock/pull/1. Thanks!

**Comment by FeodorFitsner** [comment]
@inducer - added

**Comment by inducer** [comment]
Thanks!

**Comment by LinuxDonald** [comment]
Can we have the image too please? https://ci.appveyor.com/project/LinuxDonald/fifengine

**Comment by FeodorFitsner** [comment]
@LinuxDonald added.

**Comment by sosey** [comment]
I think I'm having the same issue...https://ci.appveyor.com/project/spacetelescope/imexam

**Comment by IlyaFinkelshteyn** [comment]
@sosey sorry for delay, we added `Visual Studio 2015 Update 2` to your account

**Comment by pfernique** [comment]
@FeodorFitsner @IlyaFinkelshteyn, All [StatisKit](http:/github.com/Statiskit) C++/Python projects aren't working with Visual Studio 2015 Update 3 (due to the usage of Boost.Python wrappers). They are linked to my GitHub account. Would you be able to add Update 2 image to the account please?

**Comment by IlyaFinkelshteyn** [comment]
@pfernique done

**Comment by pfernique** [comment]
Thanks !

**Comment by pfernique** [comment]
@FeodorFitsner @IlyaFinkelshteyn Hello again, I created an organization account on AppVeyor (StatisKit26764), that require  Visual Studio 2015 Update 2 for same resons as before. Would you be able to add Update 2 image to this account please?

> @FeodorFitsner @IlyaFinkelshteyn, All [StatisKit](http:/github.com/Statiskit) C++/Python projects aren't working with Visual Studio 2015 Update 3 (due to the usage of Boost.Python wrappers). They are linked to my GitHub account. Would you be able to add Update 2 image to the account please?

**Comment by IlyaFinkelshteyn** [comment]
@pfernique OK, done.
