### ISSUE TITLE
Test view - wrong file name shown for NUnit 3 tests

### ISSUE THREAD

**Issue by Husqvik** [appveyor/ci#896]
When multiple assemblies' tests executed all tests have associated the last test assembly file name.

**Comment by FeodorFitsner** [comment]
Can you please drop a screenshot (or elaborate more) of what you mean?

**Comment by Husqvik** [comment]
Two test files discovered:

![image](https://cloud.githubusercontent.com/assets/6512856/16545058/0dadba0c-411e-11e6-9ebb-c6dc84faebaa.png)

Tests from SqlPad.Oracle.Test are shown with file name SqlPad.Test

![image](https://cloud.githubusercontent.com/assets/6512856/16545069/601b939a-411e-11e6-8978-67d080af1231.png)

Tests from SqlPad.Test miss the file name:
![image](https://cloud.githubusercontent.com/assets/6512856/16545093/1f51040c-411f-11e6-9714-4f47dca82eb1.png)

**Comment by FeodorFitsner** [comment]
Is it a public or private project?

**Comment by Husqvik** [comment]
Public: https://github.com/Husqvik/SQLPad

**Comment by FeodorFitsner** [comment]
Thanks...and can you also drop a link to AppVeyor build then?

**Comment by Husqvik** [comment]
https://ci.appveyor.com/project/Husqvik/sqlpad/build/0.4.0.376/tests
