### ISSUE TITLE
git clone with submodules

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#899]
I use submodules in my project (https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/1.0.48).

Please, add ` --recursive ` to git command line...

**Comment by sergey-s-betke** [comment]
workaround in .yml:

    clone_script:
    - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME% %APPVEYOR_BUILD_FOLDER%
    - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

But `--recursive` - usable for all projects, for my opinion...

**Comment by FeodorFitsner** [comment]
Thanks for sharing the solution!

...and there is another script: https://gist.github.com/FeodorFitsner/99d5ba9b6171063804f9db08534becb2

**Comment by sergey-s-betke** [comment]
@FeodorFitsner , but where is  `--recursive`  for submodules in Your script :-) ?

**Comment by FeodorFitsner** [comment]
Oh, there is not, but you can use it as a base as it supports PR builds :)

**Comment by sergey-s-betke** [comment]
Thank You!

**Comment by sergey-s-betke** [comment]
New workaround version:

    clone_script:
    - cmd: >-
        git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
        cd %APPVEYOR_BUILD_FOLDER%
        git checkout -qf %APPVEYOR_REPO_COMMIT%
        git submodule update --init --recursive

**Comment by scoder** [comment]
The proposed command failed to parse in the Windows shell, but this variant worked for me:
```yaml
clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive
```

**Comment by FeodorFitsner** [comment]
Wonderful! Thanks for sharing a working example!

**Comment by shubham2892** [comment]
Adding the following `appveyor.yml` worked for me:

```
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

```

**Comment by DanRStevens** [comment]
Using the `install:` section for Git submodule checkout doesn't play nice with cache restore if the cache depends on a file from a Git submodule. The cache restore happens before the `install:` section runs, so the dependent file won't be present.

**Comment by FeodorFitsner** [comment]
You can use custom `clone_script` section and include both `git clone` and modules init commands there.

**Comment by DanRStevens** [comment]
Yes, I ended up going with `clone_script`, using your template as a base. I had first tried to use `cmd` syntax, but the multiline if wasn't working for me. I switched to `ps` syntax, which worked, except for the recursive submodule update addition was giving an error from `ps`. I ended up with an odd mixed solution where the final submodule update was done from `cmd`:
```
clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive
```
