### ISSUE TITLE
Maven 3.3.3 is Missing

### ISSUE THREAD

**Issue by sunchenglong** [appveyor/ci#901]
Apache maven 3.3.3 is missing, this web-site is 404:
http://apache.mirrors.pair.com/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.zip

Some test is wrong:
https://ci.appveyor.com/project/uwolfer/gerrit-rest-java-client/build/1.0.29

**Comment by FeodorFitsner** [comment]
...but looks that file doesn't exist indeed. I'm trying to download that locally:

![image](https://cloud.githubusercontent.com/assets/5041459/16590210/7c368120-428b-11e6-9eac-8338ab3cb657.png)

**Comment by sunchenglong** [comment]
Thank you!  It's my fault, I'm sorry to diturb you.

**Comment by FeodorFitsner** [comment]
OK, thanks for the update!
