### ISSUE TITLE
CPack naming conflict

### ISSUE THREAD

**Issue by MattSturgeon** [appveyor/ci#908]
Hi, there are two programs installed on the system that add "cpack" to the PATH. CPack from CMake, and `choco pack` from Chocolatey.

Personally I need to use CPack, and since the help text from `choco pack` includes the following, I would suggest removing the shortcut to `choco pack`

```
Chocolatey will attempt to package a nuspec into a compiled nupkg. Some
 may prefer to use `cpack` as a shortcut for `choco pack`.

NOTE: `cpack` has been deprecated as it has a name collision with CMake. Please 
 use `choco pack` instead. The shortcut will be removed in v1.
```

**Comment by FeodorFitsner** [comment]
I see, that's an issue.

You may add to your build something like:

    del C:\ProgramData\chocolatey\bin\cpack.exe

or modify PATH to move CMake folder forward:

    set PATH=<path-to-cmake>;%PATH%

**Comment by MattSturgeon** [comment]
> I see, that's an issue.

Yeah, would be great to have it resolved!

For anyone interested, I'm using the following work around for now

```
init:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%
```

**Comment by FeodorFitsner** [comment]
Agree. I would imagine people use CPack more often.

**Comment by FeodorFitsner** [comment]
Update script:

```posh
remove-path 'C:\ProgramData\chocolatey\bin'
add-path 'C:\ProgramData\chocolatey\bin'
cmd /c where cpack
```

**Comment by ferventcoder** [comment]
👍
