### ISSUE TITLE
Failed to build psycopg2

### ISSUE THREAD

**Issue by henrykironde** [appveyor/ci#909]
`Environment: PYTHON=C:\Python34-x64, PYTHON_VERSION=3.4.x, PYTHON_ARCH=64`

Using this environment `psycopg2` has just started failing. 
Previously this was getting installed and tests were using the driver for both python 2 and 3

The installation of `psycopg2` was done using a [requirements file](https://github.com/weecology/retriever/blob/master/requirements.txt) 

**Reference**:
[Eco Data Retriever build](https://ci.appveyor.com/project/ethanwhite/retriever/build/job/gc3xmm0pry8eemp4)  
[Eco Data Retriever Appveyor yaml](https://github.com/weecology/retriever/blob/master/appveyor.yml)

Could the use of mirrors be a possible option?
`pip install -r requirements.txt --use-mirrors`

###### [Eco Data retriever](https://github.com/weecology/retriever)

**Comment by FeodorFitsner** [comment]
You mean that config was working before? When did it start failing? What was the last successful build?

**Comment by henrykironde** [comment]
@FeodorFitsner, we have been using the same configuration.
It started failing yesterday,  around midnight. 
The last successful build for this branch is (1.0.218).
This had pass and I resorted to this branch for validation. 

The last commit on this [branch repair-encoding](https://github.com/weecology/retriever/pull/552) fails. 
if you check the diff, with the previous commit `add latin-1 encoding  …			833f63d`, the only difference is a full stop in the comments. Basically it should have passed.

**Comment by FeodorFitsner** [comment]
Then it must be some external dependency, I'm afraid, as the last update to build workers was on June 28th: http://www.appveyor.com/updates/2016/06/28

**Comment by henrykironde** [comment]
Thank you @FeodorFitsner, I am closing because the tests have started passing. #https://github.com/weecology/retriever/pull/552
The proposed solution also worked #https://github.com/weecology/retriever/pull/554 

`os: Previous Visual Studio 2015`
