### ISSUE TITLE
Validate uploaded xUnit, NUnit test results

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#91]
xUnit schema: https://gist.github.com/FeodorFitsner/b64dd48e9fc300bc6c14
NUnit schema: https://gist.github.com/FeodorFitsner/0e89b7ce1c8a551f2756

**Comment by sschuberth** [comment]
Once #92 is implemented we would need the JUnit schema, too: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
