### ISSUE TITLE
python3.5 broken for 64 bit

### ISSUE THREAD

**Issue by piem** [appveyor/ci#914]
Hi all,

When building aubio with:

```
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
```

I get:

```
RuntimeError: Broken toolchain: cannot link a simple C program
```

See https://ci.appveyor.com/project/piem/aubio/build/job/ymgut0tw9qq660uw

This used to work before, and in the mean time, Python 3.4 build was fixed:
 - before: https://ci.appveyor.com/project/piem/aubio/build/1.0.1.203
 - after: https://ci.appveyor.com/project/piem/aubio/build/1.0.1.204

Let me know if there is anything I can try.

Best, Paul

**Comment by FeodorFitsner** [comment]
This "before" commit was built on the 1st of July, but the last change to AppVeyor build worker images was on [June 28](http://www.appveyor.com/updates/2016/06/28).

Try rebuilding that commit from build details page: https://ci.appveyor.com/project/piem/aubio/build/1.0.1.203

**Comment by piem** [comment]
Hi @FeodorFitsner ,

The re-triggered build now passes on Py34+64, but also fails on Py35+64:

See https://ci.appveyor.com/project/piem/aubio/build/1.0.1.211

Let me know if there is anything else I can try,

Best, piem

**Comment by FeodorFitsner** [comment]
Have you tried building it with `Previous Visual Studio 2015` build worker image?

**Comment by piem** [comment]
Hi @FeodorFitsner ,

The build was somehow [failing again for Python 3.5 / x64](https://ci.appveyor.com/project/piem/aubio/build/1.0.1.235/job/aaurt5hvh8tugi7j), but it seems adding the following to PATH [helps](https://ci.appveyor.com/project/piem/aubio/build/job/0jrf18wy7bn53i55):

    c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin


thanks, Paul

**Comment by FeodorFitsner** [comment]
Thanks for the note!
