### ISSUE TITLE
Coverity 8.5.0.1

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#915]
There's v8.5.0 out which should be compatible with VS2015.

**Comment by FeodorFitsner** [comment]
Thanks for letting know. When you submit an issue for installing/updating specific software please include its version into title, so later it can be used in automatic what's new, for example "Coverity 8.5.0 for Visual Studio".

**Comment by XhmikosR** [comment]
All right, I wasn't aware of that.

**Comment by XhmikosR** [comment]
Coverity 8.5.0.1 is out.

**Comment by XhmikosR** [comment]
Version: 8.5.0.1
Updated: August 3rd, 2016 

It seems they updated the packs again on August 3rd.
