### ISSUE TITLE
Enable secure variables for PRs from the same repository

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#917]
Related discussions and issues:
http://help.appveyor.com/discussions/questions/2477-detecting-forks
https://github.com/appveyor/ci/issues/485
http://help.appveyor.com/discussions/suggestions/873-about-encoded-private-keys-and-pull-requests
http://help.appveyor.com/discussions/questions/2386-encrypted-variables-in-pr-builds

**Comment by XadillaX** [comment]
When can this feature be deployed?

**Comment by FeodorFitsner** [comment]
It's deployed already.

**Comment by XadillaX** [comment]
So how to config my project?

**Comment by FeodorFitsner** [comment]
It's on General tab of project settings.

**Comment by XadillaX** [comment]
https://ci.appveyor.com/project/XadillaX/aliyun-ons

But it seems no environment variables still

**Comment by FeodorFitsner** [comment]
What variables do you set and where?

**Comment by XadillaX** [comment]
`SETTINGS` -> `Environment` -> `Environment variables`

**Comment by FeodorFitsner** [comment]
Can you try configuring some "test" secure variable and then output its value in a build log?

**Comment by XadillaX** [comment]
https://ci.appveyor.com/project/XadillaX/aliyun-ons/build/1.3.67 still no

```
> ons@2.0.0-rc.4 test C:\projects\aliyun-ons
> _mocha
[undefined]
  #producer
```

it expected to be

```
> ons@2.0.0-rc.4 test C:\projects\aliyun-ons
> _mocha
[I'm here!]
  #producer
```

**Comment by XadillaX** [comment]
It seems no env var when I rebuild the PR.

**Comment by PureKrome** [comment]
Is this fixed?
Is there a yml setting for this?

**Comment by FeodorFitsner** [comment]
It should be working. There is no setting for .yml - it's on UI only.

**Comment by XadillaX** [comment]
I don't know what happened, but it really works now.
