### ISSUE TITLE
Rebuild single job

### ISSUE THREAD

**Issue by dantti** [appveyor/ci#918]
Is it possible to rebuild just a single job?
For some reason AppVeyor builds got much faster recently but is randomly failing my build jobs, so If I trigger rebuild it rebuild everything and fails in another job, it somehow feels like some job is running parallel to another one.
You can see:
https://ci.appveyor.com/project/dantti/cutelyst/build/142
https://ci.appveyor.com/project/dantti/cutelyst/build/143
are for the same commit and give errors on different jobs.

**Comment by FeodorFitsner** [comment]
OSS build VMs have 2 CPU cores now. Could it be a problem?

**Comment by dantti** [comment]
Since I don't explicit set make -jX I would think now, does the VM run more than one build job at the same time? If that was the case could maybe mean that the environment is not clean.
As my google search on "jom" returned something like that...

**Comment by FeodorFitsner** [comment]
There is always dedicated and clean VM for every build job.

**Comment by dantti** [comment]
Ok, then maybe it's a parallel issue with nmake as it's the common one that gives error, since I don't use/have Windows, I guess I'll have to try to fix the number of jobs. Thanks

**Comment by IlyaFinkelshteyn** [comment]
Closing in favor of https://github.com/appveyor/ci/issues/58
