### ISSUE TITLE
Secure Boot Policy and Testsigning

### ISSUE THREAD

**Issue by billziss-gh** [appveyor/ci#919]
My build produces a kernel-mode driver and uses the Testsigning option in order to test it. Unfortunately the Testsigning option no longer works as of July 14, 2016:

    bcdedit /set testsigning on
    An error has occurred setting the element data.
    The value is protected by Secure Boot policy and cannot be modified or deleted.

As per the instructions in #715 I use the following script to set Testsigning on:

    install:
    - git submodule update --init --recursive
    - appveyor AddMessage "Change boot configuration and reboot" -Category Information
    - bcdedit /set testsigning on
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10

Here is the full log of the last failed builds:

- https://ci.appveyor.com/project/billziss-gh/winfsp/build/111
- https://ci.appveyor.com/project/billziss-gh/winfsp/build/110

And here is the last successful build from July 11, 2016:

- https://ci.appveyor.com/project/billziss-gh/winfsp/build/109

Thank you!

**Comment by FeodorFitsner** [comment]
Nice catch, thanks for letting know! Will fix that today.

**Comment by billziss-gh** [comment]
Excellent. Thank you for the quick turnaround!

**Comment by Liryna** [comment]
:+1: same issue here. Thank you for the quick answer !

**Comment by FeodorFitsner** [comment]
It should be fixed now. Let me know how it worked.

**Comment by Liryna** [comment]
:+1: fixed on my side ! Thank you !

**Comment by FeodorFitsner** [comment]
Sounds great!

**Comment by billziss-gh** [comment]
Worked here as well. Thanks!
