### ISSUE TITLE
JUnit test results support

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#92]

**Comment by luisrudge** [comment]
holy crap.. This is the UNIVERSAL test format. Every test tool exports to jUnit. Please add support to jUnit files

**Comment by FeodorFitsner** [comment]
Can you please drop a sample XML with results?



- Feodor

**Comment by luisrudge** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="JUnitXmlReporter" errors="0" tests="0" failures="0" time="0" timestamp="2013-05-24T10:23:58" />
   <testsuite name="JUnitXmlReporter.constructor" errors="0" skipped="1" tests="3" failures="1" time="0.006" timestamp="2013-05-24T10:23:58">
      <properties>
         <property name="java.vendor" value="Sun Microsystems Inc." />
         <property name="compiler.debug" value="on" />
         <property name="project.jdk.classpath" value="jdk.classpath.1.6" />
      </properties>
      <testcase classname="JUnitXmlReporter.constructor" name="should default path to an empty string" time="0.006">
         <failure message="test failure">Assertion failed</failure>
      </testcase>
      <testcase classname="JUnitXmlReporter.constructor" name="should default consolidate to true" time="0">
         <skipped />
      </testcase>
      <testcase classname="JUnitXmlReporter.constructor" name="should default useDotNotation to true" time="0" />
   </testsuite>
</testsuites>
```

if you want the .xsd, it's here: http://help.catchsoftware.com/display/ET/JUnit+Format

**Comment by luisrudge** [comment]
:+1: Thanks! :)

**Comment by sschuberth** [comment]
Well, the issue was closed, but was it also implemented? :-) Usually we would see the commit which resolves the issue, and it still has the "in progress" label.

**Comment by FeodorFitsner** [comment]
Yes, it's been implemented and deployed. In progress would be "need docs" :)

**Comment by sschuberth** [comment]
Cool, thanks for the confirmation!

**Comment by luisrudge** [comment]
There are no docs about this. How do I make appveyor to read my junit xml file?

**Comment by sschuberth** [comment]
I guess [analogous to xUnit](http://www.appveyor.com/docs/running-tests#xunit), i.e. replace `xunit` with `junit` in the URL.

**Comment by luisrudge** [comment]
upload the file?

**Comment by sschuberth** [comment]
Yes.

**Comment by luisrudge** [comment]
Is there any way to make appveyor aware of those files? Seems like update a file is an unnecessary step, since the file is already available at the jobs's location

**Comment by sschuberth** [comment]
BTW, I've verified that uploading the JUnit XML basically works, see

https://ci.appveyor.com/project/sschuberth/gradle-launch4j/build/tests

However, as you can see in that table, the "Test Name" is very long, and also wrong IMO. It seems AppVeyor appends the `testcase`'s `classname` and `name`, whereas it should only be the `name`.

Also, the "File Name" seems to be the `testsuite`'s `name` or the `testcase`'s `classname`, but not the file name, which would be "TEST-edu.sc.seis.launch4j.Launch4jPluginExtensionTest.xml" in this case.

**Comment by luisrudge** [comment]
nice! Only some rough edges then!

**Comment by sschuberth** [comment]
One more thing: The tests are not listed in the same order as in the XML, but IMO they should be. Badly written test may influence each other, so the execution order is of interest if you are debugging such issues.

**Comment by luisrudge** [comment]
I fully agree ordering is important!

**Comment by FeodorFitsner** [comment]
Sorry, never dealt with junit. So, if you don't need classname in the name of the test where do we supposed to put it on the current view? We can't just ignore it, right?

**Comment by sschuberth** [comment]
It depends on what the "File name" column is supposed to mean. In my comment above I was assuming it should hold the file name of the test results file, which probably is not the case when looking at the xUnit examples. Instead, I guess it should name the (source code) file containing the test. As we do not have that filename as part of JUnit reports, I agree that the `classname` is the closest substitute.

**Comment by sschuberth** [comment]
@FeodorFitsner Any progress on removing the fully qualified test class name from the "Test Name" column? If you look at [1], the "edu.sc.seis.launch4j.Launch4jPluginExtensionTest." should not be in front of a human-readable test name like "Running the task to create the executable succ...".

[1] https://ci.appveyor.com/project/TheBoegl/gradle-launch4j/build/1.0.33/tests

**Comment by FeodorFitsner** [comment]
Well do deploy update this week. So, you don't need that part (class name) at all?

**Comment by sschuberth** [comment]
See [my comment above](https://github.com/appveyor/ci/issues/92#issuecomment-147839577): "As we do not have that filename as part of JUnit reports, I agree that the classname is the closest substitute" (for the "File Name" column).

**Comment by FeodorFitsner** [comment]
So the rule is "if there is no `name` attribute defined on `testsuite` element then use testcase's `classname` attribute value to display in File Name field"?

**Comment by sschuberth** [comment]
Yes, I think it makes sense that way.

**Comment by FeodorFitsner** [comment]
OK, now `classname` is always used as "File Name". If `classname` does not exist then suite name is used. Will deploy update later this week.

**Comment by FeodorFitsner** [comment]
An update has been deployed. Let me know how it works.

**Comment by sschuberth** [comment]
> OK, now classname is always used as "File Name". If classname does not exist then suite name is used.

Isn't the above the exact opposite of what you said before:

> So the rule is "if there is no name attribute defined on testsuite element then use testcase's classname attribute value to display in File Name field"

Anyway, the "Test Name" (as well as the "File Name") columns for my use case look fine now:

https://ci.appveyor.com/project/sschuberth/gradle-launch4j/build/1.0.28/tests

**Comment by webknjaz** [comment]
Hello @FeodorFitsner,

I'm seeing my test runner tool name in FILE NAME column. It's `py.test` and it's specified in `name` attribute of the `<testsuite>`. However each `<testcase>` has correct `file` attribute stated, which holds the real file name where the test is specified.

Ref: https://ci.appveyor.com/project/jaraco/cherrypy/build/job/djlc9un31j0o7u00/tests

**Comment by leonard84** [comment]
For others that might need an example (use `after_build` or `after_test` depending on which step generates the JUnit reports):

```yml
after_build:
# upload test results via rest-api
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }
```

**Comment by tlinkowski** [comment]
> For others that might need an example (use `after_build` or `after_test` depending on which step generates the JUnit reports): [...]

If you need to upload test reports for failed builds too (like I did), use `on_finish` instead of `after_build` or `after_test`.
