### ISSUE TITLE
Python 2.7 Reg InstallPath missing

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#922]
Hi,

Since some couple of days, appveyor image no longer seems to have InstallPath set in `HKCU\SOFTWARE\Python\PythonCore\2.7`.

This test that I was using for a long time for detectiong python 2.7 no longer work:
```
set PythonRegKey=HKCU\SOFTWARE\Python\PythonCore\2.7
reg query %PythonRegKey%\InstallPath /ve >nul 2>&1 || (echo Cannot find Windows Python >&2 & exit /b 1)
```

Is this made in purpose ?

**Comment by FeodorFitsner** [comment]
When was the last successful build for that (and what's its URL)?

**Comment by Liryna** [comment]
7 days ago last success (no other run seens): https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-644/job/v47pvouqcdtsmghm
Yesterday failure: https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-645/job/ym5pv9l3pcnr5vg5#L579

The script:
https://github.com/Liryna/winfstest/blob/master/TestSuite/run-winfstest.bat#L3

**Comment by FeodorFitsner** [comment]
That's key is in `HKLM` hive on that environment: `HKLM\SOFTWARE\Python\PythonCore\2.7`, i.e. installed for "All users". I think it's more safe to check both keys or maybe folder instead.

**Comment by Liryna** [comment]
I moved to `HKLM` thank you ! :+1:
