### ISSUE TITLE
builds suddenly failing (Cython related?)

### ISSUE THREAD

**Issue by superbock** [appveyor/ci#923]
Hi,

all my builds are suddenly failing, all at the same point. More precisely, the go on forever and one test seems to be in an endless loop with an error I can not really explain. This is a current example: 

https://ci.appveyor.com/project/superbock/madmom/build/1.0.157/job/xjyiraa4udxield8

The weird thing is that the very same commit and tests (i.e. the same build as above) did succeed 2 days ago (2016-07-13).

https://ci.appveyor.com/project/superbock/madmom/build/1.0.115/job/42s48ar2joo9paoa

The only visible difference up to line 575 is the `PATH`. Both builds generate the same warnings during the Cython compilation phase (lines 188-189 and 198-200). But then [one fails at line 575](https://ci.appveyor.com/project/superbock/madmom/build/1.0.157/job/xjyiraa4udxield8#L575), whereas [the other passed the same test](https://ci.appveyor.com/project/superbock/madmom/build/1.0.115/job/42s48ar2joo9paoa#L575) two days earlier.

I'm not able to reproduce the same error locally. Was there a change in the build environment? https://www.appveyor.com/updates does not list anything for the last days.

**Comment by IlyaFinkelshteyn** [comment]
Hi Sebastian,
Indeed, your build problems exactly correlate to environment migration which we are currently doing (from Google Cloud Engine to Hyper-V infrastructure on Rackspace). 

To confirm this, I forked your repository, set it internally to run against old environment, and got the same test infinite loop issue. Therefore, I cannot say that it is 100% related to new environment. 

When I commented out TestCRFBeatDetectorProgram test class,  DBNDownBeatTracker started failing the same way, and after I TestDBNDownBeatTrackerProgram test class – everything finished OK. 
It looks like only CRFBeatDetector and DBNDownBeatTracker did not built correctly. Do you have any idea what else to look into?

Thank you,
Ilya.

**Comment by superbock** [comment]
Hi Ilya,

thanks for looking into this. Actually, I have no clue what's going on. If it was only `CRFBeatDetector` then it would be somehow clear where to look. But since `DBNDownBeatTracker` fails, I'm somehow clueless. The C-extensions used by this program is also used by others which do not fail. Thus I don't think it is triggered by the compiled C-extensions, but I am not sure.

I'll try to get rid of the warnings and see if it works then. But this may take come time. I'll let you know when it is done (via PR to your clone).

Thank you,

Sebastian

**Comment by IlyaFinkelshteyn** [comment]
Hi Sebastian,

To ensure that this not related to our environment migration, I tried to do last known good build (commitId="8d328404") on both Rackspace and GCE environments. Both stuck the same way:
Rackspace - https://ci.appveyor.com/project/IlyaFinkelshteyn/madmom/build/1.0.13
GCE - https://ci.appveyor.com/project/IlyaFinkelshteyn/madmom/build/1.0.14

I wonder, can it be if some external dependency which you download before build is changed… The only difference I see that in old logs it was cython-0.24, in newer logs it is cython-0.24.1. But both last known good and at least few first stuck builds use the same 0.24 version, so it was changed to 0.24.1 later than problem started…

**Comment by superbock** [comment]
**Update:** It seems that issue was/is caused by multiprocessing on Windows and is not Cython related. Setting the number of concurrent threads to 1 lets all tests pass and fixes the problem of stuck builds.

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot for update!
