### ISSUE TITLE
Merging PR before completion of checks should not cause "fail" status

### ISSUE THREAD

**Issue by c-lipka** [appveyor/ci#924]
This is related to #77 and #29, but I don't think either of them properly cover this:

When I merge a PR before the completion of checks, I do this because I'm absolutely positively sure the pending jobs would complete fine. It is therefore unexpected and highly undesired behaviour that this scenario actually results in a "fail" status being reported to GitHub.

Apparently it happens because:
- Merging a PR currently causes any pending jobs to be cancelled. (#77)
- Canceling a pending job currently causes a "fail" status to be reported to GitHub. (#29).

While taken individually the current behaviour with respect to both #77 and #29 can be argued to be reasonable, their _combination_ is certainly not. So presuming neither #77 nor #29 are to be revisited (since they're both closed), a scenario-specific solution should be implemented to ensure that a cancelled job is _not_ reported as "failed" _if_ the reason for cancellation is a merge of the corresponding PR.

**Comment by FeodorFitsner** [comment]
There is `Always build closed Pull Requests` option on General tab of project settings.
