### ISSUE TITLE
appveyor pushArtifact: how push multiple files as one artifacts?

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#938]
I need analog for:

    artifacts:
      - path: testFolder
        name: folderArtifactAsZip
        type: zip
      - path: testFolder2/*.ttf
        name: ttf

- How I can push **multiple** files for `ttf` artifact with `appveyor pushArtifact`?
- How I can push **folder** as zip file for `folderArtifactAsZip` with `appveyor pushArtifact`?

**Comment by FeodorFitsner** [comment]
Please find script samples for pushing artifacts here: http://www.appveyor.com/docs/packaging-artifacts#packaging-multiple-files-in-different-locations-into-a-single-archive

**Comment by sergey-s-betke** [comment]
For makefiles:

    SHELL_SPECIAL_STRINGS = ; " ' ` $$ @ $$(LEFT_BRACKET) $$(RIGHT_BRACKET) & | \
    # $(call shellEncode, commandLine)
    $(eval shellEncode = $$(strip $(foreach specialString,$(SHELL_SPECIAL_STRINGS),$$$(LEFT_BRACKET)subst $(specialString),\$(specialString),)$$(1)$(foreach specialString,$(SHELL_SPECIAL_STRINGS),$(RIGHT_BRACKET))))
    
    # $(call pushDeploymentArtifactFile, DeploymentName, Path)
    pushDeploymentArtifactFile = $(call shellEncode,\
      powershell \
        -NoLogo \
        -NonInteractive \
        -Command & { \
          $$ErrorActionPreference = 'Stop'; \
          @( $(foreach file,$(2),,'$(file)') ) \
          | Get-Item \
          | % { Push-AppveyorArtifact \
            $$_.FullName \
            -FileName $$_.Name \
            -DeploymentName ${1} \
          } \
        } \
      )

    # $(call pushDeploymentArtifactFolder, DeploymentName, Path)
    pushDeploymentArtifactFolder = $(call shellEncode,\
      powershell \
        -NoLogo \
        -NonInteractive \
        -Command & { \
          $$ErrorActionPreference = 'Stop'; \
          $$root = Resolve-Path '$(2)'; \
          [IO.Directory]::GetFiles($$root.Path, '*.*', 'AllDirectories') \
          | Get-Item \
          | % { Push-AppveyorArtifact \
            $$_.FullName -FileName \
            $$_.FullName.Substring($$root.Path.Length + 1) \
            -DeploymentName ${1} \
          } \
        } \
      )

    pushDeploymentArtifact = $(call pushDeploymentArtifactFile,$@,$^)
