### ISSUE TITLE
Not all of junit XML is parsed

### ISSUE THREAD

**Issue by ned14** [appveyor/ci#939]
If you try feeding Appveyor a junit XML with multiple testsuites like https://gist.github.com/ned14/d081017c334b5b95b132dfd44d689e70 then only the first testsuite is shown, despite that the tab correctly shows 6 test results.

See https://ci.appveyor.com/project/ned14/boost-afio/build/2.00.55-master/tests for an example.

What should happen is that Appveyor displays each testcase under a section named after each testsuite.

**Comment by FeodorFitsner** [comment]
It's been fixed and update deployed.

**Comment by ned14** [comment]
Many thanks for the fix! Any chance of sorting by name or categorising the test results, maybe with a dynamically expandable AJAX toggle or something? It would scale much better to a lot of test results.

**Comment by FeodorFitsner** [comment]
Yes, we'll add sorting and searching to that screen.
