### ISSUE TITLE
Repository level permissions?

### ISSUE THREAD

**Issue by jakirkham** [appveyor/ci#946]
Maybe this exists and I simply don't know how to do it. If not, this would be a really amazing feature. It would be nice if I could grant the ability to start and stop builds to users with write permissions on a given repository. Though still not give them permissions to all builds in the org.

cc @pelson @ocefpaf

**Comment by jakirkham** [comment]
So I have been playing around and it seems I can do the following.

1. Create a [roll]( https://www.appveyor.com/docs/team-setup/#role ) with no permissions.
2. Set/override [permissions on a project]( https://www.appveyor.com/docs/team-setup/#permissions ) for that roll.
3. [Link]( https://www.appveyor.com/docs/team-setup/#understanding-relationship-between-github-team-and-appveyor-role ) a GitHub team to an AppVeyor roll.

I have just done this procedure for the `setuptools` team and roll of the same name for demonstration purposes. Relevant screenshots shown below.

<img width="1554" alt="screen shot 2016-11-03 at 14 55 30" src="https://cloud.githubusercontent.com/assets/3019665/19980777/b9e2b7b0-a1d5-11e6-9579-e1c3fe8dde4c.png">

<img width="1554" alt="screen shot 2016-11-03 at 14 56 23" src="https://cloud.githubusercontent.com/assets/3019665/19980778/b9f4b992-a1d5-11e6-93d7-8e7d7f621b94.png">

**Comment by jakirkham** [comment]
Having now done this exercise I have a couple of questions.

1. Can we do this through the AppVeyor API?
  1. If so, how?
  2. If not, can this be added?
2. How well does this scale?
  1. Can we add ~1300 roles like this?
  2. What sort of limitations do we have when adding these? (e.g. rate limiting)
  3. How will the web interface for pages like these behave?
3. Anything else we should be aware of?

**Comment by FeodorFitsner** [comment]
1. Everything can be done via API - take a look at "Network" tab of browser Developer Tools to see what's being sent to AppVeyor REST API from UI.
2. You can give it a try, though be careful as it might be close to system abuse 😉
