### ISSUE TITLE
Visual Studio 2015 image incompatible with nuget restore

### ISSUE THREAD

**Issue by dcs619** [appveyor/ci#951]
I've got a [VS 2015 solution](https://github.com/NewSpring/Rock/blob/pre-alpha-release/Rock.sln#L2) that won't build on the VS 2015 image.  My install and before_build scripts run fine but `nuget restore` gives me the error `given path's format is not supported`: 

![image](https://cloud.githubusercontent.com/assets/1210933/17225175/ddcac75e-54d1-11e6-8c46-557fd275058e.png)

Using the [VS 2013 image](https://github.com/NewSpring/Rock/blob/pre-alpha-release/appveyor.yml#L31), `nuget restore` works fine.

**Comment by IlyaFinkelshteyn** [comment]
Hi David,

I got the same error not only on appveyor, but on my local machine. I realized that replacing http://rock.dev:6229 with some string which does not contain a colon (“:”) “fixes” the issue. IU believe that some code thinks about it only as a file stream (assumes csproj only) and throws if sees “illegal” character.

Does it builds locally for you? If yes, what exact versions of nuget and msbuild you have?

Thank you,
Ilya.

**Comment by dcs619** [comment]
@IlyaFinkelshteyn that's the standard start path for any web projects in an SLN ([another example](http://stackoverflow.com/q/213719/1853867)).  If I change that to another value, VS won't open the web project.

Locally MSBuild v12 will fail since I'm using C# 6:

![image](https://cloud.githubusercontent.com/assets/1210933/17279096/b4df14e2-573a-11e6-8fed-38304f279c8e.png)

MSBuild v14 works:

![image](https://cloud.githubusercontent.com/assets/1210933/17279120/26a6ec8a-573b-11e6-91ea-4f43e8faef7e.png)

Using Nuget 2.8:

![image](https://cloud.githubusercontent.com/assets/1210933/17279384/b820a886-5740-11e6-870e-f83931d7db32.png)

**Comment by IlyaFinkelshteyn** [comment]
Hi David,

Sure I understand that your SLN file is valid :) I believe this is latest nuget issue. At least it also works for me if I use older 2.8.6 nuget.

Can you try to add the following before nuget restore:

appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe

This will make it use the same nuget version which works OK for you, thus mitigating the issue.

Thank you,
Ilya.

**Comment by dcs619** [comment]
This seems to be working for now.  Hopefully it won't crop up again.
