### ISSUE TITLE
Visual Studio license has expired

### ISSUE THREAD

**Issue by billziss-gh** [appveyor/ci#952]
I am assuming this must be affecting others, but a search through the issue list did not reveal another report. I am receiving the following message on my builds:

    Microsoft Visual Studio 2015 Version 14.0.25420.1.
    Copyright (C) Microsoft Corp. All rights reserved.
    The license for Visual Studio has expired.
    Your license for this product is expired and could not be refreshed. Please connect to the internet to continue to use this product.

Example of failed build: https://ci.appveyor.com/project/billziss-gh/winfsp/build/131

**Comment by IlyaFinkelshteyn** [comment]
HI Bill,

We are looking into this and will update you as soon as we can. Sorry for the trouble.

--ilya.

**Comment by FeodorFitsner** [comment]
It's been fixed.

**Comment by billziss-gh** [comment]
Thanks. Confirming that it works for me now.
