### ISSUE TITLE
Windows SKD tool unavailability on WMF5 image

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#957]
@FeodorFitsner , on WMF 5 image `signtool` unavailable from command line. What is correct way for Windows SDK path detecting on AppVeyor?

https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.7.6-rc.33.build.183

**Comment by FeodorFitsner** [comment]
`Signtool.exe` comes with any SDK version, for example it's available in here: `C:\Program Files (x86)\Windows Kits\10\bin\x64` - just append that path to your `PATH` variable.

**Comment by sergey-s-betke** [comment]
Ok. Thank You.
