### ISSUE TITLE
Specify pickup folder for XML test results

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#96]
Source: http://help.appveyor.com/discussions/questions/328-recognizing-test-result-output

**Comment by sschuberth** [comment]
Where the XML test results could be in any supported format. Currently that would be xUnit and NUnit, but once #92 is implemented that would also include Ant's JUnit XML format.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
