### ISSUE TITLE
C:\Program Files\AppVeyor\BuildAgent\ not in PATH now!

### ISSUE THREAD

**Issue by sergey-s-betke** [appveyor/ci#973]
@FeodorFitsner, now `appveyor` unavailable! Why?

P.S. C:\Program Files\AppVeyor\BuildAgent\ not in the PATH variable now!

https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.8.0-extract-makeutils.150.build.217

**Comment by IlyaFinkelshteyn** [comment]
Hello Sergey,

It is still there. Please note that it is being set as build process level PATH, not machine level path. You can ensure that it exists and also will be able to check the difference between machine and process level path, if you run the following PowerShell commands during the buils at some stage:

Write-host "Machine Environment Path" -foregroundcolor Yellow
(([Environment]::GetEnvironmentVariables("Machine")).Path).Split(";")
Write-host "Process Environment Path" -foregroundcolor Yellow
(([Environment]::GetEnvironmentVariables("Process")).Path).Split(";")

By default it should be transparently for processes which are running as part of Appveyor build. However it seems that something inside your build script is ignoring process level variables.

Please let us know if this was helpful.

Thank you,

**Comment by sergey-s-betke** [comment]
I change `PATH` on install step. In `install.ps1`:

    $Path = `
        ( `
            ( $env:Path -split ';' ) `
            + $ToPath `
            | Sort-Object -Unique `
        ) `
    ;
    Write-Verbose 'Path variable:';
    $Path | % { Write-Verbose "    $_" };
    $env:Path = $Path -join ';';
    [System.Environment]::SetEnvironmentVariable( 'PATH', $env:Path, [System.EnvironmentVariableTarget]::User );

and, `$env:Path` does not contain "C:\Program Files\AppVeyor\BuildAgent\"!

**Comment by sergey-s-betke** [comment]
Now I change `install.ps1`:

    $Path = `
        ( `
            ( ( [Environment]::GetEnvironmentVariable( 'PATH', [System.EnvironmentVariableTarget]::Process ) ) -split ';' ) `
            + $ToPath `
            | Sort-Object -Unique `
        ) `
    ;
    Write-Verbose 'Path variable:';
    $Path | % { Write-Verbose "    $_" };
    $env:Path = $Path -join ';';
    [System.Environment]::SetEnvironmentVariable( 'PATH', $env:Path, [System.EnvironmentVariableTarget]::User );

build in process.... https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.8.0-extract-makeutils.152.build.219

**Comment by sergey-s-betke** [comment]
Line 1475 in build log... `PATH` does not contain "C:\Program Files\AppVeyor\BuildAgent\"! 

    ( [Environment]::GetEnvironmentVariable( 'PATH', [System.EnvironmentVariableTarget]::Process ) )

does not contain "C:\Program Files\AppVeyor\BuildAgent\" in install step! Why?

**Comment by IlyaFinkelshteyn** [comment]
Sergey,

Maybe recently added appveyor.yml init statement  - cmd: set PATH=%PATH%;%ProgramFiles(x86)%/Windows Kits/8.1/bin/x64 breaks things? Can you try to remove it and check if it helps?

Thank you,
Ilya.

**Comment by sergey-s-betke** [comment]
No! In the other project: https://ci.appveyor.com/project/sergey-s-betke/signcode/build/1.0.3-rc.26.build.50 
But this project does not contain **init** statement!

PATH variable, what accessible from init and build steps, does not contain NOW (just last two-three days!) "C:\Program Files\AppVeyor\BuildAgent\"!

@IlyaFinkelshteyn , @FeodorFitsner , please - **HELP!!!**

**Comment by sergey-s-betke** [comment]
https://ci.appveyor.com/project/sergey-s-betke/signcode/build/1.0.3-rc.35.build.67

Add "C:\Program Files\AppVeyor\BuildAgent\" to `PATH` (line 2). But `appveyor` unaccessible (line 749)!

Where is `appveyor.exe` now? **I CAN NOT FIND IT!!!**

**Comment by IlyaFinkelshteyn** [comment]
Sergey, can you please try to run `$env:path -split ";"` at `init `step, before everything. This should show us if this path exist in the very beginning.

--ilya.

**Comment by sergey-s-betke** [comment]
https://ci.appveyor.com/project/sergey-s-betke/signcode/build/1.0.3-rc.36.build.69

On init step `PATH` contain "C:\Program Files\AppVeyor\BuildAgent\". But on build step, make does not find `appveyor`... But before all is ok: https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81/build/0.8.0-extract-makeutils.128.build.198

**Comment by sergey-s-betke** [comment]
https://ci.appveyor.com/project/sergey-s-betke/signcode/build/1.0.3-rc.38.build.73

`PATH` contains `"C:\Program Files\AppVeyor\BuildAgent\"` on init step, and on install step. **BUT** does not contain it on **build step**! Lines 753-756.

Please, help!

**Comment by FeodorFitsner** [comment]
I did a simple repository just to test the case. `path` contains `C:\Program Files\AppVeyor\BuildAgent\` on all stages: https://ci.appveyor.com/project/FeodorFitsner/env-vars. Tested on both Pro and GCE environments.

**Comment by IlyaFinkelshteyn** [comment]
Sergey,

This line is breaking path

$null = Install-Package -Name chocolatey -MinimumVersion 0.9.10.3 -ProviderName Chocolatey;

We will try to understand why, but for now I think you can safely remove it, as we already have Chocolatey on build worker images.

Thank you,
Ilya.

**Comment by sergey-s-betke** [comment]
@IlyaFinkelshteyn , Thank You!
