### ISSUE TITLE
Exit with code 1, no details

### ISSUE THREAD

**Issue by haf** [appveyor/ci#978]
Hi,

I'm trying to compile Logary on Appveyor, but it just exits...

https://ci.appveyor.com/project/haf/logary/build/4.0.59

Works fine on mono.

**Comment by IlyaFinkelshteyn** [comment]
Hi Henrik,

Appveyor fails if any command during job sequence return error code other than 0. In your case rake/msbuild return 1. There are at least 3 places in the build log with obvious errors. They are:
https://ci.appveyor.com/project/haf/logary/build/4.0.59#L120
https://ci.appveyor.com/project/haf/logary/build/4.0.59#L186
https://ci.appveyor.com/project/haf/logary/build/4.0.59#L231

Does it work on your local Windows machine if you repeat those commands?

--ilya.

**Comment by haf** [comment]
You're right, there are errors there. They only seem to happen on Windows. It's probably due to the F# 4.0 [functions introduced](https://github.com/Microsoft/visualfsharpdocs/issues/184#issue-160734387) which are picked up by the mono xbuild system but not msbuild, because it references v3.1 of F#...

Now sure how to handle this... I would like to use F# 4.0 in general.

**Comment by IlyaFinkelshteyn** [comment]
Hi Henrik,

If you could let us know what specifically should we add to Appveyor build worker images for this to start working that would be great.

Ilya.

**Comment by haf** [comment]
I'll have a think and reopen if I come up with a solution.
