### ISSUE TITLE
Modify build log so copy-pasting does not include line numbers?

### ISSUE THREAD

**Issue by tkelman** [appveyor/ci#98]
Minor enhancement to the web interface, not sure how feasible it is. Travis manages to do this, FWIW.

When copying a block of lines from a log (usually a multi-line error message) to refer to in an email or a Github discussion, it would be convenient if the line numbers didn't get copied along with the content.

**Comment by FeodorTest** [comment]
Makes sense. Will take a look.

-Feodor

**Comment by gep13** [comment]
Completely unrelated question...

@FeodorFitsner are you aware you are posting as your test account @FeodorTest 

:smile_cat:

**Comment by FeodorFitsner** [comment]
Oh, snap! :) It's bound to my personal email and used when I reply from phone.

**Comment by gep13** [comment]
> Oh, snap! :) It's bound to my personal email and used when I reply from phone.

Ah gotcha.

**Comment by FeodorFitsner** [comment]
It's been implemented.

**Comment by tkelman** [comment]
Thanks Feodor! Works great!

```
    CC src/support/operators.o
    CC src/support/utf8.o
    CC src/support/ios.o
```
