### ISSUE TITLE
Add an option to include hidden folders/files in cache

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#982]
Use case: bundle caching a git dependency; the .git folder is hidden thus not restored.

**Comment by XhmikosR** [comment]
@FeodorFitsner: so does the cache include hidden folder by default, or is there a new option for it?

**Comment by FeodorFitsner** [comment]
by default, includes everything

**Comment by XhmikosR** [comment]
Should I try this in the website staging branch or wait until you merge the existing PR?

**Comment by FeodorFitsner** [comment]
give it a try
