### ISSUE TITLE
WDK 10 Redux

### ISSUE THREAD

**Issue by billziss-gh** [appveyor/ci#983]
My build produces a kernel mode driver. Running a build today (2016-08-15) I am receiving the following message:

    fatal error C1083: Cannot open include file: 'ntifs.h': No such file or directory

This appears to be related to #589 although that issue was closed a long time ago. You may need to update to the latest WDK 10.

Failed build: https://ci.appveyor.com/project/billziss-gh/winfsp/build/141

**Comment by IlyaFinkelshteyn** [comment]
Hi Bill,

Thanks for catching this and sorry for allowing this inconsistency. Pleas watch this https://github.com/appveyor/ci/issues/987 issue for a fix.

For now as temporary workaround please add the following into your appeveyor.yml:
image: Previous Visual Studio 2015

Thank you,
Ilya.

**Comment by IlyaFinkelshteyn** [comment]
Also could you please provide a hello world sample to repro this issue. We will add it to our regression tests collection. Thanks!

**Comment by billziss-gh** [comment]
Hi, Ilya,

Thanks for the quick response.

I have created a minimal driver project which you can use to test for further regressions of this issue and issue #919 (which I also reported). This project was created by stripping down my winfsp project. The project can be found here:

https://github.com/billziss-gh/winfsp.citest

This project compiles on my machine, but currently fails on AppVeyor with the same fatal error as before:

https://ci.appveyor.com/project/billziss-gh/winfsp-citest/build/1

**Comment by IlyaFinkelshteyn** [comment]
Thanks a lot, those small projects are priceless for us :)

**Comment by billziss-gh** [comment]
Any progress on this? There is currently no milestone assigned to #987.

**Comment by IlyaFinkelshteyn** [comment]
Hi Bill,

Sorry, it will be fixed in the nearest update, in the end of this week.

Thank you,
Ilya.

**Comment by billziss-gh** [comment]
Hi, Ilya:

I am seeing that there is a new platform update today, which lists #987. Unfortunately the test project still fails:

https://ci.appveyor.com/project/billziss-gh/winfsp-citest/build/8

Thanks,

Bill

**Comment by FeodorFitsner** [comment]
The image has been rolled back, again. Sorry. Will be rolling out it again later today.

**Comment by billziss-gh** [comment]
No problem and thanks as always for the quick response.

**Comment by FeodorFitsner** [comment]
OK, the fixed image is back now! Give it another try.

**Comment by billziss-gh** [comment]
Thank you. I can confirm that both the original project as well as the test project derived from the original build correctly.
