### ISSUE TITLE
Update node.js and npm

### ISSUE THREAD

**Issue by am11** [appveyor/ci#99]
The latest stable version of node.js is 0.10.35, if we have the following in our appveyor config:

```yaml
environment:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
  matrix:
    - nodejs_version: 0.10.35
```

It says `Unknown version: 0.10.35`.

If we set *lose version* (0.10 -- without the [patch number](http://semver.org/)), it picks `0.10.32`.

I would highly recommend appveyor team to integrate [nvmw](https://github.com/hakobera/nvmw) or [nvm-windows](https://github.com/coreybutler/nvm-windows), and automate this process. Note that the original [nvm](https://github.com/creationix/nvm) doesn't support windows. :)

The other option is to have [an automated](https://github.com/madskristensen/WebEssentials2013/blob/e100d71b2c9b6048aa4c41d5e84151b0616039af/EditorExtensions/PreBuildTask.cs#L181) routine or service to fetch and keep all [released](http://nodejs.org/dist/latest/) and [nightly](http://nodejs.org/dist/nightlies/) versions in sync. The downside is that you can't get latest npm from nodejs distro, as npm is discontinued from nodejs distro and the latest versions are not landing anymore. To capture the latest npm, here is a small recipe:

* Follow https://github.com/npm/npm/releases/latest/, and capture the redirected URL. It will be something like `https://github.com/npm/npm/releases/tag/v2.1.18`.
* Extract the tag number and interpolate in a string to make it look like `https://github.com/npm/npm/archive/v2.1.18.zip`.
* Download and extract the zip.

Something like this:

```powershell
# This is powershell
# This script downloads latest stable npm's  zip achieve

Function Get-RedirectedUrl {
  Param (
    [Parameter(Mandatory=$true)]
    [String]$url
  )

  $request = [System.Net.WebRequest]::Create($url)
  $request.AllowAutoRedirect=$true

  try{
    $response=$request.GetResponse()
    $response.ResponseUri.AbsoluteUri
    $response.Close()
  }

  catch {
    "ERROR: $_"
  }
}

$url = Get-RedirectedUrl -URL https://github.com/npm/npm/releases/latest/
$slugs = $url.Split('/')
$taggedAchieve = $slugs[$slug.Length - 1] + ".zip"
$url = "https://github.com/npm/npm/archive/" + $taggedAchieve
$destination = "some/path/" + $taggedAchieve

(New-Object System.Net.WebClient).DownloadFile($url, $destination)
```

**Comment by FeodorFitsner** [comment]
Sure, we'll update pre-installed Node.js up to the latest one.

For now you can use another cmdlet doing complete re-install:

    Update-NodeJsInstallation <version> [bitness]

For example:

    Update-NodeJsInstallation 0.10.35

**Comment by am11** [comment]
Thanks @FeodorFitsner, we will wait for the latest one to land in default configuration. :)

Would be nice if we have support for tags like `stable` and `nightly` in `appveyor.yml` as well, which point to latest of each. This way when (for example) node.js v1.0 is release, we don't won't have to update configuration files (0.10 => 1).

**Comment by am11** [comment]
I can see now that AppVeyor has updated node.js to latest version.

Thank you! :tada:
