### ISSUE TITLE
Maven 3.3.9

### ISSUE THREAD

**Issue by mprins** [appveyor/ci#998]
This is a request for enhancement to install a recent version of Maven (3.3.9) on the build worker images.

referencing: jruby/jruby#4075

FeodorFitsner [said](https://github.com/jruby/jruby/issues/4075#issuecomment-241524760): 
> The issue with pre-installed Maven is that we have several Java SDKs pre-installed on build worker VM.

I'm not sure how having multiple JDK's poses a problem; by default Maven requires:

  - java 7 (this may be a problem as you still have oracle jdk 6 installed...)
  - the startup batch/command/sh file to be in the path
  - the JAVA_HOME environment to be set (which is/can be done from the build matrix eg. https://github.com/GeoDienstenCentrum/sass-maven-plugin/blob/master/appveyor.yml)

**Comment by FeodorFitsner** [comment]
The guide was used to install Maven on build workers: https://www.mkyong.com/maven/how-to-install-maven-in-windows/

**Comment by mprins** [comment]
That would be great; so I could just use a build file like in mprins/maven-compass-example#4

**Comment by mprins** [comment]
thanks a lot for this! :sparkling_heart:
