### ISSUE TITLE
Repo rename 

### ISSUE THREAD

**Issue by Jericho** [appveyor/ci#999]
I have renamed two GitHub projects but can't seem to be able to change the name used by AppVeyor in the URL. I believe this is the same issue as discussed in #562. Can you please update the following two projects:

Old name: https://ci.appveyor.com/project/Jericho/picton
Desired new name: https://ci.appveyor.com/project/Jericho/picton.messaging

Old name: https://ci.appveyor.com/project/Jericho/picton-d73oi
Desired new name: https://ci.appveyor.com/project/Jericho/picton

**Comment by FeodorFitsner** [comment]
Done.

**Comment by Jericho** [comment]
Excellent thank you
